### ISSUE TITLE
Manage user authenticaion state using React Context

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1005]
We need to improve how we deal with logged in user state in the frontend app.  Currently we determine that a user is logged in using the return code (403 or 200) of hitting the `/user/info` route.  If a user is logged in, we give back a User Object, for example:

```json
{
  "name": "David Humphrey",
  "email": "david.humphrey@sencollege.ca",
  "id": "5cb1175813",
  "isAdmin": true
}
```

This information affects how a bunch of things work in the frontend.  Because lots of different components need it, I'm suggesting that we explore using the [React Context](https://reactjs.org/docs/context.html) to share the User object through our pages and component tree without having to use props. 

This [blog](https://kentcdodds.com/blog/authentication-in-react-applications) might help as well.

Once we do this, we can start refactoring the frontend to use the User context and remove localized hits to `/user/info` and props.

**Comment by Silvyre** [comment]
Just curious: will this (can this) be tied to [the work we've already done with GraphQL authentication/context](https://github.com/Seneca-CDOT/telescope/pull/824)?

**Comment by humphd** [comment]
It's not related.  One is server-side, the other on the client.

**Comment by cindyledev** [comment]
This would be an interesting read for #77
