### ISSUE TITLE
Reduce the size of the rendered DOM

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1012]
A lot of our UI is repeating the same components, and it creates a really huge DOM.  Lighthouse suggests we might be able to use react-window (and other techniques) to reduce the amount of elements we render, see https://web.dev/virtualize-long-lists-react-window/?utm_source=lighthouse&utm_medium=devtools

**Comment by Jasper-Mui** [comment]
I would be interested in working on this. Has anything changed with this issue as it is fairly old? I think that telescope currently still has this issue as the huge DOM is generated as we continue to scroll down to load more posts.

**Comment by humphd** [comment]
This has been fixed, closing.  Do you want to chat with me on Slack to find a bug that you can work on?

**Comment by Jasper-Mui** [comment]
@humphd Sure, that would be great.
