### ISSUE TITLE
My Feeds should redirect unauthorized users to our new 403 page

### ISSUE THREAD

**Issue by Silvyre** [Seneca-CDOT/telescope#1016]
Currently, the My Feeds page redirects unauthorized users to a `/404` route:

https://github.com/Seneca-CDOT/telescope/blob/038769be13640b00f4e48396eeab63d320148240/src/frontend/src/pages/myfeeds.js#L48

We should make use of [our new error page](https://github.com/Seneca-CDOT/telescope/pull/925) by redirecting unauthorized users to `/error?status=403` instead.

**Comment by humphd** [comment]
@smilegodly @manekenpix can we close this now?

**Comment by manekenpix** [comment]
Yes, #1155 is dealing with this.
