### ISSUE TITLE
Confirm local dev login flow still works

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1021]
I think I may have broken the local dev login stuff when working on https://github.com/Seneca-CDOT/telescope/issues/982#issuecomment-614896213.  We need to confirm that you can still login/logout locally with the docker login container.

**Comment by cindyledev** [comment]
Can confirm that login/logout locally with Docker login container on Windows 10 Pro using Firefox. I can log in using user2 and log out successfully. However, when I try logging in right after logging out, it doesn't ask for my credentials again. Not sure if it's a cookie setting or something on my browser. I don't have it set to save my password.
Steps I took to test:
- `git pull upstream master`
- `npm install`
- `docker system prune -af --volumes`
- `npm run clean`
- `npm run build`
- `docker-compose up --build`
- `npm start`
- `npm run develop`
- browse to `localhost:3000` and sign in with `user2` credientials

**Comment by cindyledev** [comment]
I tried this on Linux (Ubuntu) with Docker redis/login/elasticsearch containers using Google Chrome and the same thing happens: I can login and logout but it wont ask for my credentials after trying to login again. Is this what we intended or is this something we should look into?

**Comment by humphd** [comment]
Thanks for testing this, it sounds like we can close this.

Things are working as expected, but I'd like to improve it.  The "logout" is only happening on our app, and not on the remote SSO provider, which is why you're still logged in when you click Login again.

As I mentioned in https://github.com/Seneca-CDOT/telescope/issues/982#issuecomment-614896213, we could use `forceAuthn: true` to always require this, or maybe we'll get ITS to help us diagnose why they crash when we try to send a proper logout request.

**Comment by cindyledev** [comment]
That's good. I also just finished testing login/logout on Linux using native redis/elasticsearch and Docker login container. It works too :)
