### ISSUE TITLE
Going to /myfeeds when not logged in shows 404

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1023]
If you go to https://telescope.cdot.systems/myfeeds, it should offer to let you login. Instead, you get a 404.  cc @raygervais 

Are we doing the right thing with a 403 from the authenticated user info?

**Comment by Silvyre** [comment]
IMHO, this is a duplicate of https://github.com/Seneca-CDOT/telescope/issues/1016

**Comment by humphd** [comment]
Nice catch, closing as dupe.
