### ISSUE TITLE
Eliminate horizontal scrolling on mobile

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1029]
When I'm reading on mobile and try to scroll down, my movement often scrolls the screen horizontally.  Our content should be occupying the full width, and there should be no scrolling.

![scroll-bug](https://user-images.githubusercontent.com/427398/79696153-e3d71000-8248-11ea-8147-3b19780dc7c5.gif)

I'm not sure what's adding the extra width.  We should get rid of it and/or set `overflow-x: hidden`.

**Comment by cindyledev** [comment]
I'm pretty sure it's the YouTube videos that causing it. #869 should fix it

**Comment by humphd** [comment]
Indeed, you are correct!

<img width="341" alt="Screen Shot 2020-04-19 at 3 00 04 PM" src="https://user-images.githubusercontent.com/427398/79697055-804fe100-824e-11ea-970a-58992b60ef9c.png">

So maybe in this PR we should stop misbehaving content from making us scroll at all, and crop overflowing content.

**Comment by chrispinkney** [comment]
No longer an issue due to UI 2.0.
