### ISSUE TITLE
Remove extra padding on code blocks

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1038]
We're styling code blocks with highlight.js now, so we don't need to add extra padding.  It's causing the first line to get shifted:

![code-padding-bug](https://user-images.githubusercontent.com/427398/79908570-78787400-83e9-11ea-8c91-a24154bba2c0.gif)

Code is:

https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Post/telescope-post-content.css#L57-L59

**Comment by agarcia-caicedo** [comment]
I'll work on it
