### ISSUE TITLE
Improve our app's startup performance

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1042]
We're not doing well on startup:

<img width="1080" alt="Screen Shot 2020-04-22 at 10 00 55 AM" src="https://user-images.githubusercontent.com/427398/79991497-609fff00-8480-11ea-844f-247ff8b4d928.png">

In the startup trace above, you can see that from 1s to 5s we are idle, waiting on data from 4 separate requests.

Step one to faster loading: figure out how to get that time down to as close to nothing as possible.  I suspect we'll need a bunch of things to happen together (it won't be one fix).

**Comment by humphd** [comment]
First question I have: why does it take 5 seconds for our web server to respond to any requests?  What's causing all of these to be slow?  I could understand if it was the `/stats` call, since it does a lot of work in the backend.  But the `/health` one should be really fast.  They all take ~5 seconds, which is odd.

**Comment by humphd** [comment]
Testing these routes on their own, they don't seem to be the bottleneck (I'm getting ~100ms response times from nginx and the node app:

```
time curl https://dev.telescope.cdot.systems/health
{"status":"ok","info":{"version":"1.0.0","sha":"56a665b3827b9bf9a070c8eebdfd9ae0caf21732","gitHubUrl":"https://github.com/Seneca-CDOT/telescope/commit/56a665b3827b9bf9a070c8eebdfd9ae0caf21732"}}
real	0m0.097s
user	0m0.012s
sys	0m0.006s
[humphd@mbp ~/repos/telescope (backend-syntax-highlight)]$ time curl https://dev.telescope.cdot.systems/stats/year
{"posts":136,"authors":22,"words":102986}
real	0m0.087s
user	0m0.011s
sys	0m0.006s
[humphd@mbp ~/repos/telescope (backend-syntax-highlight)]$ time curl https://dev.telescope.cdot.systems/posts
[{"id":"f73c70ec05","url":"/posts/f73c70ec05"},{"id":"7214f24833","url":"/posts/7214f24833"},{"id":"ee6e66f2a1","url":"/posts/ee6e66f2a1"},{"id":"84b9351eb9","url":"/posts/84b9351eb9"},{"id":"fb9cc58a5b","url":"/posts/fb9cc58a5b"},{"id":"01fc9e2328","url":"/posts/01fc9e2328"},{"id":"3b28e823bd","url":"/posts/3b28e823bd"},{"id":"6fa1eb7729","url":"/posts/6fa1eb7729"},{"id":"2d0ae8f941","url":"/posts/2d0ae8f941"},{"id":"fa11eb478a","url":"/posts/fa11eb478a"},{"id":"ee682b5560","url":"/posts/ee682b5560"},{"id":"c2e3dd0b97","url":"/posts/c2e3dd0b97"},{"id":"cb52fd849e","url":"/posts/cb52fd849e"},{"id":"a409e6b22b","url":"/posts/a409e6b22b"},{"id":"3e2d0dd48c","url":"/posts/3e2d0dd48c"},{"id":"7add55787c","url":"/posts/7add55787c"},{"id":"f238cbfc28","url":"/posts/f238cbfc28"},{"id":"23a8896750","url":"/posts/23a8896750"},{"id":"013b494902","url":"/posts/013b494902"},{"id":"1e2b3bacf1","url":"/posts/1e2b3bacf1"},{"id":"f0858bd849","url":"/posts/f0858bd849"},{"id":"a90ac76767","url":"/posts/a90ac76767"},{"id":"138ea02893","url":"/posts/138ea02893"},{"id":"f0406212ab","url":"/posts/f0406212ab"},{"id":"8d1b99409f","url":"/posts/8d1b99409f"},{"id":"fbd958b170","url":"/posts/fbd958b170"},{"id":"49d4ef0631","url":"/posts/49d4ef0631"},{"id":"f544aa011a","url":"/posts/f544aa011a"},{"id":"82d35540c2","url":"/posts/82d35540c2"},{"id":"40f5466ee1","url":"/posts/40f5466ee1"},{"id":"b4139ea792","url":"/posts/b4139ea792"},{"id":"e98f72ee64","url":"/posts/e98f72ee64"},{"id":"bb528aea4f","url":"/posts/bb528aea4f"},{"id":"91cd872f0a","url":"/posts/91cd872f0a"},{"id":"2d9b385128","url":"/posts/2d9b385128"},{"id":"5a0e567944","url":"/posts/5a0e567944"},{"id":"9e4e5652f8","url":"/posts/9e4e5652f8"},{"id":"b2ad1ece7d","url":"/posts/b2ad1ece7d"},{"id":"650e01a42f","url":"/posts/650e01a42f"},{"id":"919722fb8f","url":"/posts/919722fb8f"},{"id":"07ec654b45","url":"/posts/07ec654b45"},{"id":"ff1f121c46","url":"/posts/ff1f121c46"},{"id":"0512601702","url":"/posts/0512601702"},{"id":"ecfd8e36db","url":"/posts/ecfd8e36db"},{"id":"11c42676d1","url":"/posts/11c42676d1"},{"id":"0176a1bffb","url":"/posts/0176a1bffb"},{"id":"5aedfe40f2","url":"/posts/5aedfe40f2"},{"id":"fd81a8f5c3","url":"/posts/fd81a8f5c3"},{"id":"765d111ffe","url":"/posts/765d111ffe"},{"id":"1c9ed1d2d9","url":"/posts/1c9ed1d2d9"}]
real	0m0.108s
user	0m0.012s
sys	0m0.006s
```

**Comment by humphd** [comment]
I do note that this lines up perfectly with an animation (in purple):

<img width="619" alt="Screen Shot 2020-04-22 at 12 12 17 PM" src="https://user-images.githubusercontent.com/427398/80006208-977f1080-8492-11ea-8268-08dfc50fffa4.png">

Can we parallelize these downloads to happen as early as possible so we don't block startup?

Also, can we reduce the time this animation is blocking things?

**Comment by humphd** [comment]
Goal #1: increase Perf score of 35 :)

<img width="766" alt="Screen Shot 2020-04-22 at 12 20 35 PM" src="https://user-images.githubusercontent.com/427398/80007012-afa35f80-8493-11ea-9d53-fae67fadd30d.png">

**Comment by humphd** [comment]
Merged #1045, which makes a big difference:

<img width="1079" alt="Screen Shot 2020-04-22 at 1 49 18 PM" src="https://user-images.githubusercontent.com/427398/80015685-1e86b580-84a0-11ea-908b-3accd4b3f56c.png">

But we are still essentially idle for 2 seconds, then spend another second rendering.  Let's get this faster still.

**Comment by humphd** [comment]
PR up at #1046 to add gzip compression.

**Comment by humphd** [comment]
gzip compression is in, and we're getting faster:

<img width="435" alt="Screen Shot 2020-04-22 at 8 18 59 PM" src="https://user-images.githubusercontent.com/427398/80045799-8a841080-84d6-11ea-9f35-0eb3227ed8c0.png">

**Comment by humphd** [comment]
Filed https://github.com/Seneca-CDOT/telescope/pull/1048 to move lazy loading processing for `<img>` and `<iframe>` to the backend during processing of the feed.

**Comment by humphd** [comment]
More nginx tweaks, and we're getting closer:

<img width="418" alt="Screen Shot 2020-04-23 at 1 56 49 PM" src="https://user-images.githubusercontent.com/427398/80132869-55c19900-856a-11ea-8ad6-9cc41992311f.png">

**Comment by humphd** [comment]
Fixing size of DOM in #1056.

<img width="727" alt="Screen Shot 2020-04-23 at 2 11 14 PM" src="https://user-images.githubusercontent.com/427398/80134184-5e1ad380-856c-11ea-8e64-8f2337db63da.png">

**Comment by humphd** [comment]
Fixing cache headers on static resources in #1057.

<img width="736" alt="Screen Shot 2020-04-23 at 2 28 17 PM" src="https://user-images.githubusercontent.com/427398/80135876-e5694680-856e-11ea-85a8-e56c4b962422.png">

**Comment by humphd** [comment]
Reducing number of posts loaded at a time helped a lot:

<img width="410" alt="Screen Shot 2020-04-23 at 3 26 48 PM" src="https://user-images.githubusercontent.com/427398/80141045-eaca8f00-8576-11ea-9c8f-59913c0455ec.png">

**Comment by humphd** [comment]
Filed https://github.com/Seneca-CDOT/telescope/pull/1061 to work on our font loading.

**Comment by humphd** [comment]
The fixes from the past few days got us into the green:

<img width="408" alt="Screen Shot 2020-04-24 at 12 04 22 AM" src="https://user-images.githubusercontent.com/427398/80173906-399c1700-85bf-11ea-8477-0733a5457ed9.png">

**Comment by manekenpix** [comment]
![image](https://user-images.githubusercontent.com/23108901/80296449-5ebc9100-8749-11ea-9e20-c4776fdb3264.png)

**Comment by manekenpix** [comment]
![image](https://user-images.githubusercontent.com/23108901/80296541-3da87000-874a-11ea-8c6e-3713df6b7091.png)

**Comment by humphd** [comment]
I'm going to close, and we can do follow-ups as we find the need.  Thanks for all the help getting this into the green.
