### ISSUE TITLE
Set worker_processes and worker_connections in our nginx config

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1047]
The first two things you generally set in an nginx config are the number of processes to run (`worker_processes`), and how many simultaneous connections you can process per second (`worker_connections`).

You determine the values for these like this:

1. `worker_processes` should be the number of cores on the box
1. `worker_connections` should be the value of `ulimit -n`

https://www.digitalocean.com/community/tutorials/how-to-optimize-nginx-configuration is a good doc on this.

@manekenpix can you give us the numbers above for the staging and prod boxes?  Then we can tweak the nginx configs.

**Comment by manekenpix** [comment]
@humphd 
Dev:
- `CPU: Intel i7-2700K (8) @ 3.900GHz`, specs [here](https://ark.intel.com/content/www/us/en/ark/products/61275/intel-core-i7-2700k-processor-8m-cache-up-to-3-90-ghz.html)

Prod:
- `CPU: Intel i7-4790 (8) @ 4.000GHz`, specs [here](https://ark.intel.com/content/www/us/en/ark/products/80806/intel-core-i7-4790-processor-8m-cache-up-to-4-00-ghz.html)

**Comment by humphd** [comment]
What does `unlimit -n` print on these?

**Comment by manekenpix** [comment]
@humphd sorry, `ulimit -n` is `1024` for both.
