### ISSUE TITLE
Kubernetes for Telescope

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#1049]
**What would you like to be added**:
We should look into using Kubernetes now that we have shipped 1.0. 

**Why would you like this to be added**:
It was a previous MVP feature

**Comment by Silvyre** [comment]
_From [the ashes](https://github.com/Seneca-CDOT/telescope/issues/4) we start anew!_

**Comment by cindyledev** [comment]
Quite a lengthy discussion went on back then :o
I'm excited to lurk and learn this

**Comment by humphd** [comment]
I'm going to side-line this for now, since we're using docker-compose for the 2.0 cycle.  Moving to cloud orchestration can happen later.
