### ISSUE TITLE
Better mobile experience for post header

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1069]
Follow-up from #1034. I'd like to rethink the header for a post a bit on mobile.  It's too tall, and tries to jam in too much text.  I think we should have it be the same height as the main nav bar, and reduce what goes in it.  We should also consider whether to show the main nav header and the post header, or only the post header, or only the main one when you scroll up, etc.

![mobile-header](https://user-images.githubusercontent.com/427398/80241797-3f7f1000-8632-11ea-9a12-a92ae215a8c0.gif)

**Comment by Jasper-Mui** [comment]
I would like to work on this.

**Comment by humphd** [comment]
@PedroFonsecaDEV how much is left to do on this after #1223 lands?  I don't want to send @Jasper-Mui down a rabbit hole if your fix will also cover this.

**Comment by PedroFonsecaDEV** [comment]
@humphd I hope landing #1223 tomorrow. 

I already made all changes on src/frontend/src/components/Header/MobileHeader.jsx that #1223 needed.
@Jasper-Mui can use my last commit [ba3fecd5](https://github.com/Seneca-CDOT/telescope/pull/1274/commits/ba3fecd58d2a5657e9bcde90928c203630a5cc7b)
 from #1223 to work on this issue. 
The Vercel's build from the last commit is [here](https://telescope-pmw3r49rx.vercel.app)

**Comment by Jasper-Mui** [comment]
I am not seeing the interaction shown in the gif on master as I see Pedro's PR has been merged. Should I be working on a different branch? Or has we decided to change how the header works?

**Comment by PedroFonsecaDEV** [comment]
@humphd ^^

**Comment by humphd** [comment]
I think this is now fixed with the work in #1223.  I'm going to close.  Thanks for pointing this out @Jasper-Mui.
