### ISSUE TITLE
Fix scroll overlap bug with header bars

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1070]
Follow-up from #1034, we need to deal with the two header bars overlapping and not playing nicely together:

![scroll-bug](https://user-images.githubusercontent.com/427398/80241500-b071f800-8631-11ea-9424-efb3150a3565.gif)

**Comment by PedroFonsecaDEV** [comment]
I would like to take a look and give a try.

**Comment by tonyvugithub** [comment]
I was about to file the same issue but decided to check the issue list first.
