### ISSUE TITLE
Add /feeds/:id/flag route to flag/unflag feeds and update backend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1071]
An admin user should be able to flag a feed, and have it not appear in the frontend, or get returned as one of the feeds in our various queries or other data routes.

We will need the following routes, accessible only to admin users:

1. `PUT /feeds/:id/flag` - would set the feed with `id` as flagged
2. `DELETE /feeds/:id/flag` - would unflag the feed with `id

In Redis, we can add a new set, `t:feeds:flagged` to manage these.  Given a feed that we want to flag (e.g., `id` of `NirlSYranl`), we'd add the key `NirlSYranl` to the set `t:feeds:flagged`.  When we delete a feed from Redis, we'd need to delete it from both `t:feeds` and perhaps `t:feeds:flagged` as well.

Our code for getting "all" feeds should be updated so that it uses [SDIFF](https://redis.io/commands/sdiff) to get the set of all feeds that ARE `t:feeds` but NOT in `t:feeds:flagged`.  This will automatically exclude all flagged feeds when we do processing.

Flagged feeds should not show up in the UI, and should not be returned as part of normal API requests.  It would be the same as if they didn't exist.

**Comment by c3ho** [comment]
could we use a `smove` here instead to move a feed from `t:feeds` to `t:feeds:flagged`? This would allow us to avoid having to change the `getFeeds()` function
