### ISSUE TITLE
Blog post header overlaps the ScrollToTop button

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#1077]
**What happened**:
Follow up bug of #1034 . The blog post header overlaps the scroll-to-top button, this can be seen on mobile.

![1077_mobile](https://user-images.githubusercontent.com/36822198/80314192-12f7ff00-87be-11ea-846d-58962c3d61eb.gif)

**Comment by humphd** [comment]
Dupe of #1070?

**Comment by cindyledev** [comment]
#1070 deals with two headers conflicting, this one is the blog post header vs the scroll to top button :o 

The new blog post header has beef with two different things
