### ISSUE TITLE
Alignmnet of "scroll down" FAB on main screen on mobile

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1079]
I think we might have broken something:

<img width="345" alt="Screen Shot 2020-04-26 at 10 53 53 AM" src="https://user-images.githubusercontent.com/427398/80311202-534e8180-87ac-11ea-8971-fc433800f69b.png">

Is the down arrow FAB supposed to be in the centre?  Also, why do we have a ~5px empty space at the bottom of the main image?

For reference, here is what it looked like before we landed the new server-side Unsplash fixes:

<img width="328" alt="Screen Shot 2020-04-26 at 10 56 13 AM" src="https://user-images.githubusercontent.com/427398/80311250-9c063a80-87ac-11ea-9803-f2c913ffb1e1.png">

**Comment by agarcia-caicedo** [comment]
Is this still a bug that needs to be fixed?

**Comment by cindyledev** [comment]
> Is this still a bug that needs to be fixed?

Yes, please fix this 🙏

**Comment by agarcia-caicedo** [comment]
> > Is this still a bug that needs to be fixed?
> 
> Yes, please fix this 🙏

I'll work on it then
