### ISSUE TITLE
Hook new feed parser into feed worker

### ISSUE THREAD

**Issue by robertbegna** [Seneca-CDOT/telescope#108]
Hello, 
My previous requests weren't able to get merged, and I am unsure of how to contribute to this project. Does anyone have any issues they could recommend for me to try?

**Comment by humphd** [comment]
I'm going to morph this into a bug for @robertbegna.  We are about to land #37, which adds url to xml feed parsing.  We need to hook that into our feed worker.  We can do something really basic to start, and I've got a model in https://github.com/Seneca-CDOT/telescope/pull/37#pullrequestreview-314522718.

**Comment by jayson528** [comment]
i spoke with the prof in class and i was assigned to this issue
