### ISSUE TITLE
Investigate missing charset on JSON files

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1082]
[According to webhint](https://webhint.io/scanner/619fd876-7b16-4ef5-86e1-b53394750d41#hint-content-type-1), we aren't serving the correct charset (utf-8) with JSON files.  I think JSON is always uft-8, so maybe it's not actually necessary?  I also don't understand why the default charset setting we have isn't taking for these files.

**Comment by cindyledev** [comment]
Is this still a problem?

**Comment by humphd** [comment]
I don't think we've ever fixed this, no.  It would need to happen in nginx's config I think.

**Comment by humphd** [comment]
I think this is a non-issue.
