### ISSUE TITLE
Add icons for admins to flag and delete feeds from timeline

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1088]
If an admin is reading the timeline, and notice something problematic, they should be able to flag (#1075) or delete the feed right there.  I suggest we add two new icons to the upper-right corner of the blue post header bar.  Here's a rough sketch of what I mean:

<img width="812" alt="Screen Shot 2020-04-28 at 12 33 56 PM" src="https://user-images.githubusercontent.com/427398/80513749-82e8bf80-894d-11ea-8e64-9eb3c13bf534.png">

**Comment by humphd** [comment]
We should probably have some kind of pop-up dialog for confirmation: "Are you sure you want to flag this post?"

**Comment by humphd** [comment]
See also #1089, which could form the basis for this panel of buttons being added.

**Comment by c3ho** [comment]
Do we want this functionality when we search by posts/authors as well?
