### ISSUE TITLE
Feature Request: display full blog title after click

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#1089]
**What would you like to be added**:
We need a way to display the entire blog title (especially on mobile); we only see the title before the ellipsis. I wanna see the rest of the title but only when I want to. Maybe display the full blog title after a click to expand the rest of the title and collapse after another click? 

![Screenshot_20200428-160451_Chrome](https://user-images.githubusercontent.com/36822198/80532581-60b16a80-896a-11ea-9db1-92720fb81812.jpg)

**Comment by humphd** [comment]
This is a really great idea.  Here's my suggestion: let's merge this, or follow-up with, the work in #1088, and use an [Expansion Panel](https://material-ui.com/components/expansion-panels/) to contain the overflow items in the header, which could include extra overflow text, more info about who wrote it, when they wrote it, and icons for doing extra things with the feed (e.g., for admins).

**Comment by c3ho** [comment]
I've been at this css for 3+ hours now while reading documentation and everything. I've been playing with this sandbox: https://codesandbox.io/s/brave-napier-noks1?file=/demo.js:642-648 . The only problem I have now is when you click on it... the text doesn't expand. I tried testing a hover css selector on it and instead of wrapping, the title ends up not wrapping and goes all the way to the right

**Comment by yuanLeeMidori** [comment]
Hi, is there any one working on this issue? I'd like to give it a try. Thank you!

**Comment by manekenpix** [comment]
@yuanLeeMidori all yours!

**Comment by manekenpix** [comment]
Closed via #1380

**Comment by humphd** [comment]
@yuanLeeMidori you need to use the format `Fixes #....` when you do your PRs in the first comment you leave so that it automatically closes the issue when you merge.  Next time, please.

**Comment by yuanLeeMidori** [comment]
@humphd Got it. I'll follow the convention next time. Thank you for pointing it out for me.
