### ISSUE TITLE
Improper entities in code blocks

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1091]
We're altering `<pre><code>...</code></pre>` blocks to use entities, and shouldn't.  Here's my recent blog post.  On the left, the original (notice the `=>` arrow function on line 2), and on the right, Telescope's version:

<img width="1512" alt="Screen Shot 2020-04-30 at 10 05 27 AM" src="https://user-images.githubusercontent.com/427398/80720099-6faf2e80-8aca-11ea-8431-d069befe1616.png">

This is probably our HTML sanitizer trying to protect us.

For writing a test case, here is what the HTML actually looks like:

```
<span class="hljs-string">', ...].map((number) =>;
    twilio.messages.create({
      body: '...'
</span>
```

**Comment by smilegodly** [comment]
Is it alright if I work on this one ?

**Comment by manekenpix** [comment]
> Is it alright if I work on this one ?

@smilegodly absolutely!
