### ISSUE TITLE
404 for /legacy/planet.css

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1093]
I don't know when we broke the static asset serving for the legacy planet, but it no longer works (and I want it back!):

<img width="1230" alt="Screen Shot 2020-04-30 at 9 25 57 PM" src="https://user-images.githubusercontent.com/427398/80773900-525d7d00-8b29-11ea-8311-70243c1e90ae.png">

We register it [here](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/index.js#L38), and that hasn't changed [for while](https://github.com/Seneca-CDOT/telescope/commit/bc62eb63bcd17bfe9275176bf076652744349ed0).

**Comment by manekenpix** [comment]
This is what `nginx` says when trying to serve `planet`:
```nginx
nginx_1          | 142.114.232.196 - - [01/May/2020:05:14:00 +0000] "GET /planet HTTP/2.0" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
nginx_1          | 142.114.232.196 - - [01/May/2020:05:14:00 +0000] "GET /legacy/planet.css HTTP/2.0" 404 154 "https://dev.telescope.cdot.systems/planet" "Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
nginx_1          | 2020/05/01 05:14:00 [error] 9#9: *1 open() "/var/www/data/legacy/planet.css" failed (2: No such file or directory), client: 142.114.232.196, server: dev.telescope.cdot.systems, request: "GET /legacy/planet.css HTTP/2.0", host: "dev.telescope.cdot.systems", referrer: "https://dev.telescope.cdot.systems/planet"
nginx_1          | 142.114.232.196 - - [01/May/2020:05:14:00 +0000] "GET /legacy/planet-cdot-logo.png HTTP/2.0" 304 0 "https://dev.telescope.cdot.systems/planet" "Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
nginx_1          | 142.114.232.196 - - [01/May/2020:05:14:00 +0000] "GET /legacy/feed-icon-10x10.png HTTP/2.0" 304 0 "https://dev.telescope.cdot.systems/planet" "Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
nginx_1          | 142.114.232.196 - - [01/May/2020:05:14:00 +0000] "GET /favicon.ico HTTP/2.0" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
```

**Comment by humphd** [comment]
This is really helpful, especially:

```
[error] 9#9: *1 open() "/var/www/data/legacy/planet.css" failed (2: No such file or directory)
```

This means that nginx is trying to satisfy this request with static data vs. letting express handle it with routes.  Do we need to move the express stuff up in the order that nginx processes things?

**Comment by manekenpix** [comment]
I'm very confused by this. I can't understand why nginx looks for `planet.css` in the Gatsby stuff. I thought since the requests is trying to reach `/planet` it'd be forwarded to telescope.

**Comment by humphd** [comment]
It makes me wonder why any of the routes work, if this one fails.

I just tested a theory, and express is serving this file correctly without express.  So this is somehow an nginx change.

**Comment by manekenpix** [comment]
I did some testing and it seems to work without this:
```nginx
location ~* \.(?:js|css)$ {
  expires max;
  add_header Cache-Control "public, max-age=31536000, immutable";
}
```
My theory is that when nginx reads that nested location it somehow creates an association between all the `.css` files and `var/www/data` (the `/` location has `root /var/www/data` in it), and maybe that's why it looks for `planet.css` in `/var/www/data`.

The only way I found to be able to keep the nested location is adding this:
```nginx
    # Non-cached routes /admin /user /health /auth
    location ~ ^/(admin|user|health|auth) {
      proxy_cache_bypass 1;
      proxy_pass http://telescope_staging:3000;
    }

    # I added this location to take care of anything related to GET /legacy
      location /legacy {
        expires max;
        add_header Cache-Control "public, max-age=31536000, immutable";
        proxy_pass http://telescope_staging:3000;
      }

    # Static content
    location / {
      # Directory from which we serve Gatsby's static content
      root /var/www/data;
...
```
With this, nginx is able to serve `planet.css`:
```sh
nginx_1 | 70.31.145.165 - - [03/May/2020:05:41:55 +0000] "GET /planet HTTP/2.0" 200 148058 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
nginx_1 | 70.31.145.165 - - [03/May/2020:05:41:55 +0000] "GET /legacy/planet.css HTTP/2.0" 200 628 "https://dev.telescope.cdot.systems/planet" "Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
nginx_1 | 70.31.145.165 - - [03/May/2020:05:41:55 +0000] "GET /legacy/planet-cdot-logo.png HTTP/2.0" 200 16938 "https://dev.telescope.cdot.systems/planet" "Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
nginx_1 | 70.31.145.165 - - [03/May/2020:05:41:55 +0000] "GET /legacy/feed-icon-10x10.png HTTP/2.0" 200 469 "https://dev.telescope.cdot.systems/planet" "Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
```

**Comment by humphd** [comment]
I think what you've done here is right, based on my reading of the docs.  Excellent detective work!  Would you be willing to open a PR that does this?

**Comment by manekenpix** [comment]
Absolutely! I'll have it ready later today.
