### ISSUE TITLE
[Discussion] Agile Project Management Practice (Suggestion)

### ISSUE THREAD

**Issue by Reza-Rajabi** [Seneca-CDOT/telescope#11]
While we are working in such a mid-size project with a large number of contributors, one thing that could be helpful and could let us act more efficiently would be project management consideration. Moreover, it is an opportunity for us as a student to get used to the best practices.
We can use the Github project management feature or any other similar technologies for the following concerns :

**Project scope and project implementation plan:**
 Right now we don't have a clear scope for the project, but as we go we will elaborate one. More importantly, in the first few days, we might better make some common pictures/points of view about our project. Currently, we have started some discussions that their topics could be seen as our project work packages.  As we discuss, the outcomes of our discussions can be summarized as deliverable tasks in a TODO like list.

**Project realization:** 
Once the above list is partially made, we can:
- Assign tasks to ourselves, or maybe each other (with some considerations)
- See which tasks are available or are taken more clearly
- Feedback on our progress more effectively all in one place 
- Have a final destination to summarize our discussion, issues, pull  requests
- Each task can be seen and approved by the project sponsor (Dave) more efficiently
- Tasks can be broken down into smaller tasks (if needed) more clearly
- Tasks can easily be prioritized
- The changes in the project scope (adding/removing new tasks) could be observed (after related discussion) in one place

_**To have a tangible view/ an example:**_
Our discussions could be summarized in some project board, for example as such:

To Do:
- implementing text analysis function1 ( issue #7)
- implementing text analysis function2 ( issue #7)
- implementing text analysis functionN ( issue #7)
- making decision about basic unit test (...)
- test for function1,2 ... N
- Linter automation
- issue tags classification
- Kubernetes research
...

**Comment by jatinAroraGit** [comment]
We could start by creating issues for each enhancement/feature/function to be added and then we can leverage what github already gives us like Assignees on each issue and use github labels to indicate what kind of issue it is.

**Comment by Reza-Rajabi** [comment]
@humphd Would you like to let us play with the Project section of the Github? I am trying to convince everybody that it might be beneficial for us. Maybe I need two weeks to fail or succeed in this idea. I want to maintain and update the project status based on our progress to see what we can get out of it.

**Comment by humphd** [comment]
@Reza-Rajabi I've added you all as collaborators, so go ahead and set up whatever you want!
