### ISSUE TITLE
Implement trending, most viewed and other tags to blog post 

### ISSUE THREAD

**Issue by asyam1** [Seneca-CDOT/telescope#110]
As seen on other websites, it would be nice to see hashtags and tags to find which is the most treading or latest blog post to read. We can use #26 to find which blog post has most views and likes to automatically arrange them. @humphd I would be happy to work on this if you think this is a good feature for the project

**Comment by miggs125** [comment]
we've decided not to go with these features. Feel free to look at the issue list to see what we need help with :)
