### ISSUE TITLE
Location in 'nginx_production.conf' redirects to 'telescope_staging' instead of 'telescope_production'

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#1107]
**What happened**:

In [`nginx_production.conf`](https://github.com/Seneca-CDOT/telescope/blob/master/nginx-production.conf), one of the locations redirects to `telescope_staging` instead of `telescope_production`, causing `nginx` to crash.

```diff
diff --git a/nginx-production.conf b/nginx-production.conf
index 71f7dd3..1e972c6 100644
--- a/nginx-production.conf
+++ b/nginx-production.conf
@@ -101,7 +101,7 @@ http {
     location /legacy {
       expires max;
       add_header Cache-Control "public, max-age=31536000, immutable";
-      proxy_pass http://telescope_staging:3000;
+      proxy_pass http://telescope_production:3000;
     }
 
     # Static content
```

**Comment by Metropass** [comment]
Just to make sure, you wanted `proxy_pass` to have the address `telescope_production` with the same port of 3000?

**Comment by manekenpix** [comment]
> Just to make sure, you wanted `proxy_pass` to have the address `telescope_production` with the same port of 3000?

yes, exactly that

**Comment by Metropass** [comment]
Sweet! I'll run it locally first and then I'll make a PR tonight! :)
