### ISSUE TITLE
Replace Redis for Windows in CI and Contributor Docs

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#1119]
The new version of `redis` for windows on `chocolatey` was causing `TravisCI` to fail. [A patch was added](https://github.com/Seneca-CDOT/telescope/pull/1117) to fix this problem, but since the project is [no longer maintained](https://chocolatey.org/packages/redis-64/), it'd be better to consider a different solution, for example using [`Memurai`](https://www.memurai.com/).

**Comment by chrispinkney** [comment]
I'm having issues dealing with this and chocolatey so I can investigate this if you like

**Comment by manekenpix** [comment]
@chrispinkney thanks you!

**Comment by humphd** [comment]
We need to solve this in general, as too many people run into trouble trying to get this running on Windows.

Obviously docker is one route, but some people struggle with that on their machines.  Using WSL is another and doing https://redislabs.com/blog/redis-on-windows-10/.

We could have people run Memurai, but it's not open source https://www.memurai.com/get-memurai.

We could also have people mock redis via env, and not bother installing it.

**Comment by manekenpix** [comment]
I suggest we close this issue and open a new one that address the problem generally (development + CI)

**Comment by humphd** [comment]
@manekenpix whatever you like.

I bet that most developers don't really need redis at all, and could just use the mock stuff we have already.

**Comment by manekenpix** [comment]
@humphd let's do that then. Mocking redis FTW!

**Comment by humphd** [comment]
We could mock Elastic too I bet https://www.elastic.co/blog/smooth-mocking-with-the-elasticsearch-node-js-client
