### ISSUE TITLE
Meta Issue for Best practices research on using Bull and Redis

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#112]
We're using Redis and Bull to implement our backend queue pipeline.  Most of our development team has never used either before, so this bug is a starting point for documenting things *other* established projects do when they use these two technologies together.  To start I've been going through these:

- https://github.com/sourcegraph/sourcegraph
- https://github.com/coralproject/talk
-  https://github.com/zeit/node-file-trace
-  https://github.com/salesforce/refocus
-  https://github.com/OriginProtocol/origin
-  https://github.com/syuilo/misskey
-  https://github.com/Requarks/wiki
-  https://github.com/Chocobozzz/PeerTube
-  https://github.com/GetStream/Winds
-  https://github.com/withspectrum/spectrum
-  https://github.com/outline/outline
-  https://github.com/LearningLocker/learninglocker
-  https://github.com/ParabolInc/action

The goal of this bug is to highlight things we could also do.  People should file specific Issues and do Pull Requests to add/fix things in this list (i.e., this bug isn't about fixing them directly).  For people looking for things to work on, this list has some ideas, and if you dig through the code above, you'll find more.

## Redis

1. ~~Move the Redis URL into our `.env` and when we make Bull Queues, pass this URL on via the constructor.  With #105, we can do this.  Doing so will make it easier to switch between development and production environments:~~ happening in #144
1. We could take this one further and also add username, password, etc like [this code does](https://github.com/syuilo/misskey/blob/873444c3c6f7e3b9ecb6cce569d8cdb3fa032012/src/queue/index.ts#L17-L25).  See also [this code](https://github.com/syuilo/misskey/blob/65d359b57ae94ab9f53f995082dde645ebf7bf11/src/db/redis.ts) which manages the Redis client instance using it.
1. Wrapping Redis calls and exposing them as JS operations is an interesting idea, see [this code](https://github.com/Chocobozzz/PeerTube/blob/2b4dd7e26d93c2d9bef4f365cb03c511eff4ca8f/server/lib/redis.ts) especially lines 210 onward.  If we use [ioredis](https://github.com/luin/ioredis), as I've suggested in #71, it already has promise support.
1. I notice that we can pass our `.env` through to Redis via Docker Compose [like this](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option), as seen [here](https://github.com/Chocobozzz/PeerTube/blob/f1b38883922fd59b36f093e44a5091e090d20862/support/docker/production/docker-compose.yml#L28)

## Queues

1. One of our design goals is to have failed downloads of feeds get automatically retried some number of times, but to apply an exponential backoff so we don't just go into an endless loop of failure.  [This code shows one way to do this via options to the Bull queue](https://github.com/syuilo/misskey/blob/873444c3c6f7e3b9ecb6cce569d8cdb3fa032012/src/queue/index.ts#L87-L96)
1. ~~We need to add a "graceful shutdown" for each queue, in the case that the process is being killed (by OS, user initiated via SIGHUP, etc).  The [docs on this with Bull are here](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueclose), and you can see it happen in [this file](https://github.com/Chocobozzz/PeerTube/blob/2b4dd7e26d93c2d9bef4f365cb03c511eff4ca8f/server/lib/job-queue/job-queue.ts#L101-L106)~~ #173 

## Logging

1. ~~For each queue that we create, we should add logging for all the various events that can occur.  [This is a great example of how to do it](https://github.com/OriginProtocol/origin/blob/e9881d687241fdbf557239a90eeac12d96792d62/infra/cron/src/scheduler.js#L22-L73).  Depends on #35.~~ #145 

## Bull

1. ~~We have a bug on adding a route with visualization of how Bull is operating #62.  You can see how another project is handing this.  The route definition is [here](https://github.com/GetStream/Winds/blob/2664b1518743ed108572a45435bff97e79168a7d/api/src/routes/health.js#L11), and the [Bull Arena bit is here](https://github.com/GetStream/Wind/blob/2664b1518743ed108572a45435bff97e79168a7d/api/src/controllers/health.js#L137-L164)~~ landed in `master`  
1. ~~A cool idea that I got from [this code](https://github.com/GetStream/Winds/blob/48cda6bef1ae4cd0612368bef86becead4f0e8c5/api/src/commands/winds-og.js) is to add a node.js command line tool that lets you inject a feed URL manually into the running queue.  This would be great for debugging, and for our testing purposes right now, while we wait to get all the feeds loading automatically.~~ #112

**Comment by zufishanali** [comment]
Hi @humphd , I would like to take on the first portion of Redis.

**Comment by birtony** [comment]
Hey @humphd, it would've been nice if I could work on the second point from the Redis portion.

**Comment by humphd** [comment]
Co-ordinate with @zufishanali, who is doing something similar.  See if there is anything left for you to do.

**Comment by zufishanali** [comment]
Hi @birtony, feel free to work on it if you like! Here is PR #171 for reference on progress thus far.

**Comment by izhuravlev** [comment]
Hey @birtony, @zufishanali, @humphd 
If nobody has taken the Queues part - I would be happy to open an issue related to it and work on it.
Does this sound good?

**Comment by humphd** [comment]
@izhuravlev that would be great.  I see you filed some issues for it.

**Comment by humphd** [comment]
This has been done in follow up issues, closing.
