### ISSUE TITLE
Author Link + Date of Last Post Link for Search feature doesn't work

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#1122]
**What happened**:
Clicking on date of last post link or author link when searching by author doesn't' do anything

**What should have happened**:
Clicking on last post should link to the last post available and clicking on author should either show all posts by the author or at least link to their blog

**How to reproduce it (as precise as possible)**:
1. Search by author
2. Click on either date of last post or author in the results

**Anything else we need to know?**:

**Environment**:

- OS: Windows 10
- Browser: Chrome

**Comment by manekenpix** [comment]
Clicking on `Date of Last Post` doesn't do anything, but clicking on `Latest Post:...` does, was this intentional?

**Comment by c3ho** [comment]
I’m assuming since the other two are clickable, it should lead us somewhere. Otherwise we should not make it clickable

**Comment by c3ho** [comment]
Going to close this for now
