### ISSUE TITLE
Clicking "Load More Posts" shows the last post twice

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1123]
Scroll to the end of the available posts, click Load More Posts, it loads more, but includes the last post again.  It looks like an off-by-one error:

<img width="896" alt="Screen Shot 2020-09-17 at 6 07 48 PM" src="https://user-images.githubusercontent.com/427398/93533381-c5b52f00-f910-11ea-9b2a-1a949974824b.png">

**Comment by humphd** [comment]
Oddly it only happens with some posts (I can make it happen, but not in all cases).

**Comment by tonyvugithub** [comment]
I think this no longer an issue, but there is another issue about clicking "Load More Posts" that I have filed

**Comment by humphd** [comment]
This has been fixed, yeah.
