### ISSUE TITLE
Raw Entities in Blog Titles 

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1125]
Similar to #1091, I notice that we have raw entity values in blog titles:

<img width="700" alt="Screen Shot 2020-09-19 at 5 00 13 PM" src="https://user-images.githubusercontent.com/427398/93689136-b7464f00-fa99-11ea-9cf6-b85518bef4f1.png">

**Comment by smilegodly** [comment]
This seems similar to https://github.com/Seneca-CDOT/telescope/issues/1091

Can I work on this one ?

**Comment by humphd** [comment]
Sounds good, thanks @smilegodly.

**Comment by humphd** [comment]
@smilegodly how is this coming?

**Comment by HyperTHD** [comment]
This issue hasn't appeared in the past few months, so closing this issue
