### ISSUE TITLE
Need margin on right-hand side of "Add yours..." message

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1128]
Depending on the window size, our "...Add yours" message over the hero image is too tight to the right edge of the window:

<img width="1220" alt="Screen Shot 2020-09-20 at 10 22 47 AM" src="https://user-images.githubusercontent.com/427398/93713679-62ebaf80-fb2b-11ea-878e-556530ca74b5.png">

**Comment by cindyledev** [comment]
Whoever does this can do #981 too ;)

**Comment by smilegodly** [comment]
I can do this one
