### ISSUE TITLE
Increase feed retries on production to avoid marking invalid feeds by mistake

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1149]
I'm not sure why, but for some reason Tony's blog isn't showing up on Telescope.  I looked at the logs, and I see this:

```
{"level":30,"time":1601748100364,"pid":39,"hostname":"ca46d1637fce","msg":"Skipping resource at https://medium.com/feed/@tonyknvu. Feed previously marked invalid"}
```

Something in our system has marked this as invalid.  We need to to fix that.

I checked and there are others like this:

<details>
<summary>`cat log | grep "Feed previously marked invalid" | jq ".msg" | sort -u`</summary>
<pre>
"Skipping resource at http://admixdev.com/category/programming-2/feed/. Feed previously marked invalid"
"Skipping resource at http://alicoding.com/rss/. Feed previously marked invalid"
"Skipping resource at http://annafatsevych.com/blog/category/CDOT/feed/. Feed previously marked invalid"
"Skipping resource at http://blog.auios.com/feed.php. Feed previously marked invalid"
"Skipping resource at http://blog.cresencia.ca/category/open-source/osd600/feed/. Feed previously marked invalid"
"Skipping resource at http://blog.gabrielcastro.ca/feeds/posts/default/-/open%20source. Feed previously marked invalid"
"Skipping resource at http://blog.jordantheriault.com/category/open-source/feed/. Feed previously marked invalid"
"Skipping resource at http://blog.sidkalra.com/category/opensource/feed. Feed previously marked invalid"
"Skipping resource at http://cdot-callaghan.posterous.com/rss.xml?tag=CDOT. Feed previously marked invalid"
"Skipping resource at http://compileofcrap.com/SPO600/feed.xml. Feed previously marked invalid"
"Skipping resource at http://dailypackage.fedorabook.com/index.php?/feeds/index.rss2. Feed previously marked invalid"
"Skipping resource at http://dilanguneratne.ddns.net/tag/open-source/rss/. Feed previously marked invalid"
"Skipping resource at http://ruihui.me/OSD600/category/open-source/feed/. Feed previously marked invalid"
"Skipping resource at http://sdealmeida.com/category/open-source/feed/. Feed previously marked invalid"
"Skipping resource at http://stronglytyped.ca/category/spo600/feed/. Feed previously marked invalid"
"Skipping resource at http://www.hodgin.ca/?feed=rss2&cat=4. Feed previously marked invalid"
"Skipping resource at http://www.kypertrast.net/seneca/category/open-source/feed/. Feed previously marked invalid"
"Skipping resource at https://evlnyng.tumblr.com/tagged/osd600/rss. Feed previously marked invalid"
"Skipping resource at https://medium.com/feed/@a_elmasery. Feed previously marked invalid"
"Skipping resource at https://medium.com/feed/@alexei.kozachenko. Feed previously marked invalid"
"Skipping resource at https://medium.com/feed/@jacobshuman7/. Feed previously marked invalid"
"Skipping resource at https://medium.com/feed/@random4900. Feed previously marked invalid"
"Skipping resource at https://medium.com/feed/@tonyknvu. Feed previously marked invalid"
"Skipping resource at https://medium.com/feed/programmer-and-a-scholar/tagged/opensource. Feed previously marked invalid"
"Skipping resource at https://myasir.ca/blog. Feed previously marked invalid"
"Skipping resource at https://raygervais.dev/feed-open-source.xml. Feed previously marked invalid"
"Skipping resource at https://vldmrkl.com/rss.xml. Feed previously marked invalid"
"Skipping resource at https://www.abuzayed.ca/my-blog/. Feed previously marked invalid"
"Skipping resource at https://www.abuzayed.ca/my-blog/osd600/category/open-source/feed/. Feed previously marked invalid"
"Skipping resource at https://www.marcobeltempo.com/feed/. Feed previously marked invalid"
</pre>
</details>

**Comment by humphd** [comment]
I notice that @raygervais has one in here, too  `Skipping resource at https://raygervais.dev/feed-open-source.xml. Feed previously marked invalid"`

**Comment by humphd** [comment]
Some more details from the logs:

```
"Invalidating feed https://medium.com/feed/@tonyknvu for the following reason: unknown reason"
```

Which seems to have happened here:

```
{"level":50,"time":1601101364476,"pid":28,"hostname":"ca46d1637fce","error":{"message":"request to https://medium.com/feed/@tonyknvu failed, reason: connect ETIMEDOUT 104.16.121.127:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT","stack":"FetchError: request to https://medium.com/feed/@tonyknvu failed, reason: connect ETIMEDOUT 104.16.121.127:443\n    at ClientRequest.<anonymous> (/telescope/node_modules/node-fetch/lib/index.js:1455:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"},"msg":"Unable to fetch HEAD info for feed https://medium.com/feed/@tonyknvu"}
{"level":50,"time":1601101364477,"pid":28,"hostname":"ca46d1637fce","error":{"message":"request to https://medium.com/feed/@tonyknvu failed, reason: connect ETIMEDOUT 104.16.121.127:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT","stack":"FetchError: request to https://medium.com/feed/@tonyknvu failed, reason: connect ETIMEDOUT 104.16.121.127:443\n    at ClientRequest.<anonymous> (/telescope/node_modules/node-fetch/lib/index.js:1455:11)\n    at ClientRequest.emit (events.js:315:20)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"},"msg":"Unable to process feed https://medium.com/feed/@tonyknvu"}
{"level":50,"time":1601101364480,"pid":17,"hostname":"ca46d1637fce","error":{"message":"request to https://medium.com/feed/@tonyknvu failed, reason: connect ETIMEDOUT 104.16.121.127:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"},"msg":"Job d07ad33e33 failed."}
```

So my guess is that we tried multiple times to read and parse this feed, it failed, and we eventually marked it `invalid`.

We probably need some better UI to alert us to this fact, and for users to understand what is happening with their feed, and why it is or isn't showing up.

**Comment by humphd** [comment]
I notice that @tonyvugithub's blog is on Telescope, did someone fix?

<img width="867" alt="Screen Shot 2020-10-12 at 6 32 53 PM" src="https://user-images.githubusercontent.com/427398/95795900-87195700-0cb9-11eb-8e4c-a68f508b0dc4.png">

**Comment by manekenpix** [comment]
I had to delete our db file because it got corrupted after a reboot. It seems the back-end marked @tonyvugithub's feed as valid this time.

**Comment by humphd** [comment]
OK, makes sense.

I wonder if we should increase this to something larger: https://github.com/Seneca-CDOT/telescope/blob/master/env.production#L66.  There's no way that a Medium feed was invalid, so it must have been network issues.  Maybe we should double this to 10?
