### ISSUE TITLE
Create Test for sentiment analysis of a blog.

### ISSUE THREAD

**Issue by jatinAroraGit** [Seneca-CDOT/telescope#115]
Need to write test for code in https://github.com/Seneca-CDOT/telescope/blob/master/src/sentiment-analysis.js file to check its functionality.

I will take up this issue but will need help as I have not written tests from scratch. Also, other pull request are welcomed for fixing this issue.

**Comment by dbeigi** [comment]
@jatinAroraGit I can help you with doing some testing on this code

**Comment by jatinAroraGit** [comment]
Hey @dbeigi ,
In case you wondering what the function returns it returns a promise object which looks like this : 

{ score: 1,
  comparative: 0.010638297872340425,
  calculation: [ { progress: 2 }, { hard: -1 } ],
  tokens:
   [ 'the',
     'external',
     'project',
     'named',
     'tachiyomi',
     'is',
     'a',
     'project',
     'built',
     'using',
     'kotlin',
     'you',
     'can',
     'read',
     'more',
     'about',
     'by',
     'visiting',
     'the',
     'repository',
     'or',
     'by',
     'reading',
     'by',
     'previous',
     'blog',
     'post',
     'i',
     'chose',
     'a',
     'complex',
     'issue',
     'to',
     'work',
     'on',
     '3',
     'days',
     'ago',
     'and',
     'have',
     'been',
     'grinding',
     'and',
     'googling',
     'hard',
     'to',
     'make',
     'a',
     'fix',
     'happen',
     'the',
     'issue',
     'i',
     'am',
     'working',
     'on',
     'is',
     'a',
     'rating',
     'feature',
     'for',
     'you',
     'can',
     'look',
     'at',
     'the',
     'progress',
     'by',
     'viewing',
     'my',
     'fork',
     'of',
     'the',
     'repository' ],
  words: [ 'progress', 'hard' ],
  positive: [ 'progress' ],
  negative: [ 'hard' ] }

The test should be able to verify that the object returned must contain these properties. Jest Docs do mention a method we can use. It is called Object Containing. You can read about it in detail here : https://jestjs.io/docs/en/expect#expectnotobjectcontainingobject
