### ISSUE TITLE
Route /myfeeds goes to blank page with user not logged in

### ISSUE THREAD

**Issue by smilegodly** [Seneca-CDOT/telescope#1155]
**What happened**:

The most recent [code deletions](https://github.com/Seneca-CDOT/telescope/commit/03540d789ad9adbf138d90ba758704dd898308f5#diff-341423ac4fcd5b3e25e7dd93d2bae8e1L46-L49) in `myfeeds.js` gets rid of an exception `catch` which directs the user to the login page.  At the moment when you go to `/myfeeds` not logged in, a blank `/myfeeds` page is shown.

**What should have happened**:

The user should be prompted by a login page.

**How to reproduce it (as precise as possible)**:

To reproduce this bug go to https://dev.telescope.cdot.systems/myfeeds/ without being logged in.

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by manekenpix** [comment]
I think this is probably caused by #1141. I'll work on it.
