### ISSUE TITLE
Add Backend Tests

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#1160]
**What would you like to be added**:
Increase the coverage of our backend tests

**Why would you like this to be added**:
We need more tests so travis / circle can help us identify issues with a PR
![image](https://user-images.githubusercontent.com/18711727/95165169-7036aa00-0779-11eb-9c38-77700ca9f8d8.png)

**Comment by TDDR** [comment]
Hello @c3ho, We talked a little about this issue in the slack channel today. I would like to get assigned this for now.

**Comment by c3ho** [comment]
@TDDR Hey, thanks for taking up this issue. This is something more of a meta bug to keep track of back-end tests we're adding. I suggest you create a PR and just mention this issue in the description similar to what I did with #1161.

**Comment by chrispinkney** [comment]
As we're currently using microservices in every which way for Telescope, this is too vague to be kept open at this time.
