### ISSUE TITLE
New Semester, New Background Images needed

### ISSUE THREAD

**Issue by raygervais** [Seneca-CDOT/telescope#1170]
**What would you like to be added**:
- Since 1.0.0's release, we've been this collection which was curated by the class and contributors: https://unsplash.com/collections/9975402/photos. I think, with the new faces starting to rise they too should contribute to the collection as well.

**Comment by humphd** [comment]
*A note to students contributing to this issue this week.*

We are trying to collect a series of Unsplash photos that help tell the story of what our community is doing and who we are.  Telescope is a an open learning and technology project by the Seneca community.  We are a diverse community of individuals, and this is part of our strength.  We are also trying to create a space that is welcoming to people learning how technology works.  We'd like the first thing you see when you go to Telescope be an image that helps capture this ethos.

If you could go to https://unsplash.org and look for a photo that you think represents these ideas, or what Telescope means to you, we'd appreciate having your contribution here.  Your photo will get added to the collection that we use for the front page.

You can leave a URL in a comment on this issue, and @raygervais will add them all to the collection.

Thanks for being part of Telescope.

**Comment by chrispinkney** [comment]
How about 3?

https://unsplash.com/photos/TamMbr4okv4

https://unsplash.com/photos/2FPjlAyMQTA

... https://unsplash.com/photos/gySMaocSdqs

**Comment by humphd** [comment]
@chrispinkney second one we already have, **love** the other 2!

**Comment by hyunjiLeeTech** [comment]
How about these?
https://unsplash.com/photos/SYTO3xs06fU
https://unsplash.com/photos/FlPc9_VocJ4

**Comment by humphd** [comment]
@hyunjiLeeTech first one we have, I love that one too.  Second one is perfect!

**Comment by raygervais** [comment]
Really loving the suggestions so far, similar to this semester's contributors it appears more and more individual personalities is surfacing within Telescope! @humphd, should we set a deadline on this one or leave it open till X date? Asking so that once deadline is met, I can go about the submitted and add them to the collection (or create a new collection ala Telescope 1.5) all at once.

**Comment by HyperTHD** [comment]
https://unsplash.com/photos/TzVN0xQhWaQ
This one highlights determination to get work done and to never give up, cause the moment when your PR is finally merged into the main branch and featured on a big release is something you keep with you forever.
Also helps to pad that resume up too

**Comment by humphd** [comment]
@raygervais I asked them to do it as part of the activities for this week, so we can hopefully close this next week and add them.

**Comment by raygervais** [comment]
Awesome, sounds good.

**Comment by chawlapalak** [comment]
I like these ones, these give me the good vibes and how we all work together and help each other out here. I love the vibe of team spirit and enjoying the success and working through failures together. 
[https://unsplash.com/photos/bq31L0jQAjU](https://unsplash.com/photos/bq31L0jQAjU)
[https://unsplash.com/photos/cAtzHUz7Z8g](https://unsplash.com/photos/cAtzHUz7Z8g)
[https://unsplash.com/photos/FBiKcUw_sQw](https://unsplash.com/photos/FBiKcUw_sQw)

**Comment by VietnameZe** [comment]
I found:
https://unsplash.com/photos/842ofHC6MaI
https://unsplash.com/photos/MAYEkmn7G6E
https://unsplash.com/photos/wh-RPfR_3_M
https://unsplash.com/photos/Y_LgXwQEx2c
https://unsplash.com/photos/3V8xo5Gbusk

**Comment by tonyvugithub** [comment]
I found a few I think could represent telescope. My keywords are telescope, togetherness and network

https://unsplash.com/photos/Zyx1bK9mqmA

https://unsplash.com/photos/atSaEOeE8Nk

https://unsplash.com/photos/ZiQkhI7417A

https://unsplash.com/photos/p6gQCmySSO4

**Comment by sanji11** [comment]
I like these ones: 
https://unsplash.com/photos/XkKCui44iM0
https://unsplash.com/photos/LaqL8nxiacc
https://unsplash.com/photos/Y_LgXwQEx2c
https://unsplash.com/photos/zi5vRoAP3WY

**Comment by badalsarkar** [comment]
https://unsplash.com/photos/TamMbr4okv4
https://unsplash.com/photos/Oalh2MojUuk
https://unsplash.com/photos/WE_Kv_ZB1l0

**Comment by tianlangwu** [comment]
https://unsplash.com/photos/c8h0n7fSTqs
https://unsplash.com/photos/ZDwh_sxsX2g
https://unsplash.com/photos/vSI8ASKyMJ8
https://unsplash.com/photos/JdoofvUDUwc

**Comment by joey2031** [comment]
https://unsplash.com/photos/WE_Kv_ZB1l0
https://unsplash.com/photos/vGgn0xLdy8s
https://unsplash.com/photos/U0tBTn8UR8I
How are these?

**Comment by MLJBrackett** [comment]
https://unsplash.com/photos/ZDwh_sxsX2g
https://unsplash.com/photos/Xr1Lwph6eGI
https://unsplash.com/photos/842ofHC6MaI
https://unsplash.com/photos/XMpXzzWrJ6g

**Comment by joelazwar** [comment]
https://unsplash.com/photos/Q1p7bh3SHj8
https://unsplash.com/photos/kwzWjTnDPLk
https://unsplash.com/photos/OqtafYT5kTw

**Comment by strawberries73** [comment]
https://unsplash.com/photos/p55zezwahEk  I like this one because I feel like this a a journey of exploration and discovery.

**Comment by yzwdroid** [comment]
https://unsplash.com/photos/Yj1M5riCKk4
https://unsplash.com/photos/5JuLcub3dYg

**Comment by zg3d** [comment]
https://unsplash.com/photos/uTWKKYqt3qQ
https://unsplash.com/photos/wxLZQ3vCSYs
https://unsplash.com/photos/TlrEKUrQOXs
https://unsplash.com/photos/_ok8uVzL2gI

**Comment by PedroFonsecaDEV** [comment]
https://unsplash.com/photos/In4XVKhYaiI
https://unsplash.com/photos/U1yDO88dyAI
https://unsplash.com/photos/Oze6U2m1oYU
https://unsplash.com/photos/q1zHlqCOe4k
https://unsplash.com/photos/vpxeE7s-my4
https://unsplash.com/photos/mpN7xjKQ_Ns

**Comment by isabellaliu77** [comment]
https://unsplash.com/photos/-uHVRvDr7pg
https://unsplash.com/photos/kJxinkriuB4
https://unsplash.com/photos/MMr6FsccqB4

**Comment by raygervais** [comment]
All images have been added, with a new grand total of 82 unique Unsplash images! 🔭 💻 😃

**Comment by humphd** [comment]
Thank you so much, @raygervais!  Love this feature, and the community involvement.
