### ISSUE TITLE
Tracking Pixel from Medium Posts cause display issues

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#1172]
**What happened**:
In posts aggregated from Medium, a tracking pixel is added at the end of <content:encoded> tags in the rss feed. We display this image on Telescope with a width of 100%, giving the appearance of significant extra padding.
This is an issue when viewing Telescope using Chrome or Chromium based browsers, like Samsung internet and Edge.

Example:
Mobile, Chrome:
![image](https://user-images.githubusercontent.com/49992710/95626791-f3415400-0a48-11eb-9b59-0be1a0483d50.png)
![image](https://user-images.githubusercontent.com/49992710/95626808-fb00f880-0a48-11eb-8c52-5fd49b2e1b9a.png)
Desktop Chrome:
![image](https://user-images.githubusercontent.com/49992710/95626877-22f05c00-0a49-11eb-90a1-9429a929e66c.png)

**What should have happened**:
Since the image is not a part of the original post, it should not appear on Telescope.
![image](https://user-images.githubusercontent.com/49992710/95626439-41098c80-0a48-11eb-8b09-db3e5c337114.png)
![image](https://user-images.githubusercontent.com/49992710/95626981-5e8b2600-0a49-11eb-92d7-9447003b0524.png)

**How to reproduce it (as precise as possible)**:
Go to Telescope using Chrome, either desktop or mobile, look for a blog post originally posted on Medium.

**Anything else we need to know?**: 
Firefox does not have this issue, the image is still is in the code, but it cannot load it

**Environment**:

- OS: Windows
- Browser: Chrome, Samsung Internet, Edge

**Comment by cindyledev** [comment]
I'd like to take this one
