### ISSUE TITLE
Change Telescope Theme to a light theme

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#1173]
**What would you like to be added**:

Change the color of the components to match this new light design, which has better contrast.
![image](https://user-images.githubusercontent.com/49992710/95636910-66a19080-0a5e-11eb-98c0-56127b512973.png)
![image](https://user-images.githubusercontent.com/49992710/95636914-6bfedb00-0a5e-11eb-8427-bce325a84ad9.png)
![image](https://user-images.githubusercontent.com/49992710/95636944-7c16ba80-0a5e-11eb-9c56-6b414e4083b9.png)
![image](https://user-images.githubusercontent.com/49992710/95636922-715c2580-0a5e-11eb-90f4-7d76efdf1b8d.png)

**Why would you like this to be added**:

The current theme has contrast and user experience issues, #1055 and #1039, so the new light theme would improve the Telescope UI and provide for a better reader experience.

**Comment by agarcia-caicedo** [comment]
Pages that need to be converted

- [ ] Home
- [ ] About 
- [ ] Search
- [ ] 404
- [ ] My feeds

**Comment by hyunjiLeeTech** [comment]
Hi, if you still need to change Telescope Theme to a light theme, can you please assign me to this task? Thanks.

**Comment by humphd** [comment]
@hyunjiLeeTech if you want to work on the 404 page or My Feeds page, and follow the work that @agarcia-caicedo began in #1174 and #1176, that would be great.
