### ISSUE TITLE
Logged In mobile view formatting issues

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#1175]
**What would you like to be added**:
Our current way of dealing with the logged in state causes some UI issues. Specifically, when in mobile, the drawer has two buttons (name and logout) sharing the same line space:

![image](https://user-images.githubusercontent.com/49992710/95667476-ae92e700-0b34-11eb-9925-38fbc04aa674.png)

We need each button to have its own line, without the changes influencing the desktop view.

**Why would you like this to be added**:

Our current way causes ux issues, since its not clear where you can click to reach feeds or logout (you have to hover directly on top of logout to do so, otherwise it leads you to my feeds). it also looks odd and unlike any site.

**Comment by cindyledev** [comment]
I'd like to take this
