### ISSUE TITLE
Update Colour Palette docs

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#1179]
We need to update the docs to reflect our updated theme, the current colours we use are:

Primary: #333e64
Secondary: #0589d6
Background: #e5e5e5

Text:
default: #181818
main: #8BC2EB
secondary: #e5e5e5

**Comment by tonyvugithub** [comment]
Hi @agarcia-caicedo , can I take care of this issue? Thanks

**Comment by agarcia-caicedo** [comment]
go ahead, here is the [doc](https://github.com/Seneca-CDOT/telescope/blob/master/docs/gui-colour-palette.md)

**Comment by tonyvugithub** [comment]
@agarcia-caicedo : Hi, I try to do it correctly. Do you want me to follow the same structure as it currently is or it is ok to make changes?

**Comment by tonyvugithub** [comment]
This is what I have got so far, please let me know that it is inline with what you want!
![image](https://user-images.githubusercontent.com/55034244/95753732-04b87500-0c70-11eb-9da5-c19e94c7b12b.png)

**Comment by tonyvugithub** [comment]
I sent in a PR, please take a look.
