### ISSUE TITLE
Remove outside post padding in mobile

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#1180]
**What would you like to be added**:
After #1174 was pushed, posts on mobile have padding, which prevents them from taking up the full screen. 

What we have:
![image](https://user-images.githubusercontent.com/49992710/95693031-13634580-0bf8-11eb-8ee1-4761d963c1de.png)

What we want:
![image](https://user-images.githubusercontent.com/49992710/95693083-7654dc80-0bf8-11eb-9c06-41775315ab24.png)

**Why would you like this to be added**:
The padding makes the paragraphs more narrow than they need to be, allowing for less words per line.

**Comment by tonyvugithub** [comment]
I think the issue got fixed as I could not see the padding you mentioned on my machine. 
![image](https://user-images.githubusercontent.com/55034244/95694803-e0be4a80-0c01-11eb-8821-c1b132ebcac3.png)

**Comment by tonyvugithub** [comment]
@agarcia-caicedo : Hi, Can I take over this issue?

**Comment by humphd** [comment]
@tonyvugithub assigned, go for it!  Thanks.

**Comment by tonyvugithub** [comment]
fixed and sent in PR with detail comment

**Comment by cindyledev** [comment]
This is a problem again. Probably happened after #1217 
![Screenshot 2020-10-23 101755](https://user-images.githubusercontent.com/36822198/97015096-27247b00-1519-11eb-8629-3e7b186a9128.png)

**Comment by humphd** [comment]
We must have wrapped things in another container?  This sounds similar to the issue I have doing the timeline width https://github.com/Seneca-CDOT/telescope/issues/1226

**Comment by cindyledev** [comment]
I guess @agarcia-caicedo can work on this one too ;D

**Comment by pyvelkov** [comment]
Shoot I am so sorry I forgot to request this. 
See #1292 
Let me know what you think.

**Comment by humphd** [comment]
Assigning ti @pyvelkov.
