### ISSUE TITLE
Failed to serve front-end locally while back-end, redis, and elasticsearch ran fine 

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1182]
I tried to get Telescope work the first time locally on my machine, but failed. 

I received this error when trying to run `npm run serve` to start Gasby 
- OS: Window
- Node Version: v14.4.0

![image](https://user-images.githubusercontent.com/55034244/95759855-477e4b00-0c78-11eb-9e84-b4e7942105e0.png)

**Comment by raygervais** [comment]
@tonyvugithub, what commands did you use to run frontend?

**Comment by raygervais** [comment]
@tonyvugithub, can you share the output of running

```suggestion
npm run develop
```

**Comment by humphd** [comment]
Also, I wonder if this is worth filing upstream in Gatsby itself: it seems odd to me that running `gatsby serve` wouldn't give a better clue about the real problem, namely, that you need to run `gatsby build` first.

**Comment by tonyvugithub** [comment]
They should have included ` gasby build `when run `gatsby serve`

**Comment by tonyvugithub** [comment]
@raygervais Looks like I run the wrong command. Here is the output of `npm run develop`
![image](https://user-images.githubusercontent.com/55034244/95763993-d3df3c80-0c7d-11eb-882d-61c99137ec0d.png)
