### ISSUE TITLE
Should mention what to do with front-end module in the Environment Set up docs

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1183]
As I followed the [Environment Set up docs](https://github.com/Seneca-CDOT/telescope/blob/master/docs/environment-setup.md), I realized the docs did not mention anything about whether we should run some command like `npm run serve` to trigger the front-end locally.

The docs concluded like this: 
![image](https://user-images.githubusercontent.com/55034244/95760438-076b9800-0c79-11eb-99c0-ab6cf5cf58cc.png)
If users run `npm start`, only the backend started, so frontend would not be accessible and hence returned a 404 page when accessing localhost:3000. 

It would be clearer if the docs adds what to do for front-end module as well

**Why would I like this to be added**:
It would help new contributors like myself better navigate through the project.

**Comment by humphd** [comment]
I wonder if a simple fix here would be to modify the ending of the Environment setup docs to something like:

```
Finally

You can now start Telescope, which requires running both a back-end and a front-end.

To build and run the front-end, see the front-end docs at (https://github.com/Seneca-CDOT/telescope/blob/master/docs/gatsbyjs.md).

To run the back-end, use `npm start` and open `localhost:3000`
```

I am also going to file a bug soon that also changes how our `npm run dev` works, so new devs can do `npm install && npm run dev` and *everything* works (using mocks for backend services).

**Comment by humphd** [comment]
cc @cindyledev and @raygervais who will have thoughts on wording here.

**Comment by humphd** [comment]
I think #1182 is due to this, and us not being clear about how to build and run the frontend.  `npm run serve` is a logical choice, but wrong if you don't have a build to serve.

**Comment by humphd** [comment]
The docs for Gatsby say:

> npm run serve to serve the production site in src/frontend/public for testing

We should update this to include a note about needing to run `build` or `dev` first so there is a build that can be served.
