### ISSUE TITLE
Unnatural behaviour of posts loading when click "Load More Posts" button

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1185]
**What happened**:
When you clicked on "Load More Posts" button, your view changed from the last post of the previous patch to the last post of newly loaded patch. This is unnatural to what the viewers expect.  This has been an issue for me to follow the posts even with the current release.

**What should have happened**:
What should have happened is the view should continue to the first post of the newly loaded patch so the views can continue scrolling down. 

**How to reproduce it (as precise as possible)**:
I think we could change the logic a bit when we try to load more posts. Maybe have function to track the current position of the viewer like what post they are currently on. Most likely when the viewer see "Load More Posts" they are already on the last post of the current patch.

**Comment by humphd** [comment]
This is fixed now.
