### ISSUE TITLE
Hero Banner could be more Heroic

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1187]
I notice that at some sizes, our "full screen" hero banner image doesn't go all the way to the bottom.  I think it's more noticeable with the new light theme on staging, so maybe it's not new.

I'd like this image to sit against the bottom of the viewport (see the gap at the bottom of this screenshot):

<img width="1335" alt="Screen Shot 2020-10-12 at 1 45 06 PM" src="https://user-images.githubusercontent.com/427398/95789062-cdb38500-0caa-11eb-845b-6bb32bd92338.png">

**Comment by tonyvugithub** [comment]
@humphd Can I take over this?

**Comment by agarcia-caicedo** [comment]
Currently the Hero image is not at 100vh, which seems to work for smaller screens or bigger screens, leaving the medium ones with issues. A possible solution would be to implement breakpoints for the hero banner image
