### ISSUE TITLE
Align outline border of post header and body 

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1188]
There's a slight variation on the post header vs. body outline border.  It makes it look like the body of the post is 1 pixel wider than the header.  When I zoom in on it, you can see it's probably a slight colour variation, that makes the border disappear on the header.

Let's align them so that the whole thing reads as a single width.

<img width="276" alt="Screen Shot 2020-10-12 at 4 53 00 PM" src="https://user-images.githubusercontent.com/427398/95789481-9c878480-0cab-11eb-8de2-b2955b642ba1.png">

cc @agarcia-caicedo

**Comment by agarcia-caicedo** [comment]
I think this has to do with different boxShadow properties between the post and the header

**Comment by tonyvugithub** [comment]
I took a quick look, it turned out that the current dark color could be the problem. I changed it to the same color as in the content background then it looks like one. 
![image](https://user-images.githubusercontent.com/55034244/95791876-4cf78780-0cb0-11eb-9998-4e6110037542.png)

**Comment by Shinh18** [comment]
@humphd Can I work on this issue?

**Comment by humphd** [comment]
@Shinh18 sure, all yours.  Go ahead and assign yourself.

**Comment by Shinh18** [comment]
@humphd It looks like the box shadow is for both post header and post content. 
![Screen Shot 2020-11-16 at 2 29 41 PM](https://user-images.githubusercontent.com/48449650/99298799-3e087580-2818-11eb-8920-44754af24234.png)

**Comment by humphd** [comment]
This isn't relevant now with new design, closing.
