### ISSUE TITLE
Remove empty whitespace-only blocks from posts

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1189]
I feel like @agarcia-caicedo mentioned this in another issue, but I can't find it now.  A number of blog platforms add extra whitespace blocks to posts, for example:

<img width="576" alt="Screen Shot 2020-10-12 at 4 56 27 PM" src="https://user-images.githubusercontent.com/427398/95789805-32231400-0cac-11eb-8cee-729f79f4659c.png">

We could try doing some work in our HTML post-processing step to remove things like empty `<p>`, multiple `<br>`, `empty `<div></div>` or `<div><p></p></div>`

**Comment by agarcia-caicedo** [comment]
The issue I found, #1172, has to do with us treating Medium's tracking pixel as a regular picture.

I however have seen this behaviour too. I think I mostly see it from posts that come from blog post

**Comment by tonyvugithub** [comment]
@humphd Is this resolved already?

**Comment by humphd** [comment]
It is not resolved, no.  There are a bunch of "empty" elements and multiple blank element combos we need to consider and then remove.
