### ISSUE TITLE
Update eslint env for all environments we are using

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#119]
In `.eslintrc.js`, we currently define our environments like so:

```js
"env": {
    "jest": true,
    "browser": true,
},
```

This is good, but we should add a few more from the [list of possible env](https://eslint.org/docs/user-guide/configuring#specifying-environments), specifically:

- `node` - for node.js
- `es2017` - for ECMAScript 2017, which has `async`/`await`

**Comment by Manan311** [comment]
Hello humphd,

If it is okay I would like to work on this and if this issue could be assigned to me.

Thank You,
Manan311
