### ISSUE TITLE
Remove empty anchor elements

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1190]
Some blog platforms seem to inject heading anchors with no inner content:

<img width="597" alt="Screen Shot 2020-10-12 at 5 01 30 PM" src="https://user-images.githubusercontent.com/427398/95790037-a78ee480-0cac-11eb-9c1e-b97f9b0984e7.png">

This causes the content to shift to the right by 43px, and throws off alignment.  We could strip out these empty `<a></a>` elements from the DOM in our post-processing.

**Comment by tonyvugithub** [comment]
@humphd: Can I take care of this?

**Comment by humphd** [comment]
Yeah, we might be able to a filter https://www.npmjs.com/package/sanitize-html#filters

**Comment by tonyvugithub** [comment]
@humphd :  before you provided the link. I created a function did just what the filter function in sanitize-html does.
![image](https://user-images.githubusercontent.com/55034244/96147699-8ceb8400-0ed5-11eb-87c0-ef33bb9c5e44.png)
I learned sth new by creating this function though

**Comment by tonyvugithub** [comment]
@humphd : So I implement the option for exclusiveFilter to get rid of no content anchor as mentioned in the doc. 
![firstImplementation](https://user-images.githubusercontent.com/55034244/96162424-86193d00-0ee6-11eb-8c1a-40ad4d9aa1c6.PNG)
When I run test locally, it gave me two errors as below
![fail](https://user-images.githubusercontent.com/55034244/96162478-95988600-0ee6-11eb-846d-b3ea9702854a.PNG)
Apparently, the option also removed anchor with media children as well. So I think the text attribute only consider content not html tag. I then tried to access mediaChildren attribute as mentioned in the docs but could not do it for some reason. 
_What in the doc_
![image](https://user-images.githubusercontent.com/55034244/96162665-cd9fc900-0ee6-11eb-9208-16e2b3671d77.png)
_What in my editor_
![frameAttr](https://user-images.githubusercontent.com/55034244/96162754-e9a36a80-0ee6-11eb-9c6c-0382189d97e3.png)
Now the solution would solve the problem for this issue but failed two tests. I could continue with my custom approach and solve it. How do you think?

**Comment by tonyvugithub** [comment]
Interesting enough, they actually account for the case where between the anchor there is media tags, but for some reason it does not work as expected here. When I implemented the option, it failed the two tests that involve media children tags

**Comment by tonyvugithub** [comment]
@humphd : I created a PR using my custom way since built in filter of satinize-html kept failing two tests.
