### ISSUE TITLE
Feature: add synchronized author/post outline in desktop view

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1193]
**What would you like to be added**:

In desktop view, I'd like to have a high-level view of all the posts and authors in the current timeline, so I can jump around easily.

Here's a functional example of what I mean from the [Jest Docs](https://jestjs.io/docs/en/mock-function-api):

![scroll-sync](https://user-images.githubusercontent.com/427398/95888480-20df1380-0d4f-11eb-8d5e-a97209039e74.gif)

On the right, all of the document's major sections are listed, and as I scroll the main page, the list on the right gets synchronized with where I am.  I can easily see where I am in the entire document.

Imagine if instead of that info, we had Post Title and Author Title on the side.  We have more than enough space on the left/right of the posts to add this.

**Why would you like this to be added**:

Moving through the posts linearly is great, and I can read one, then the next, etc.  However, I also want to be able to jump around, or go back to an author or post I read a few minutes ago.  We need better visibility into what is in the feed.

This needs a little bit of design thought, too.

**Comment by manekenpix** [comment]
I'd like to try this, and I'm open to collaboration if anyone wants to join me.

**Comment by joelazwar** [comment]
Hey @manekenpix still working on this issue? I'm down to collaborate since this issue seems interesting to work on :)

**Comment by manekenpix** [comment]
@joelazwar yes, I have the functionality, and now I'm dealing with styling.

**Comment by manekenpix** [comment]
The PR #1368 was a first attempt to work on this issue when Gatsby was the main front-end. The code in that PR can be used as template for a new attempt once the Gatsby-NextJS port is completed.

**Comment by humphd** [comment]
This was a cool idea, but our UI changed to not have the author list on the side.  Closing.
