### ISSUE TITLE
Increase contrast between text and background in '/myfeeds'

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#1194]
Currently, our `myfeeds` page looks like this:

![image](https://user-images.githubusercontent.com/23108901/95890041-3d7c4b00-0d51-11eb-9d1f-db2583c1742f.png)

Because of the lack of contrast between text and background, it's very hard to read the authors and URLs.

**Comment by tonyvugithub** [comment]
@manekenpix : If we want to keep the same background color. I would change the color for text to default color, which is a blackish color, also change the "Blog feed URL" and "Blog feed author" to the same color of remove button on the right. Then the contrast should improve.

**Comment by manekenpix** [comment]
@tonyvugithub that sounds good. Let's get the experts here to get more opinions. cc @agarcia-caicedo @cindyledev

**Comment by agarcia-caicedo** [comment]
I think this is part of #1173,  since that page hasn't been converted. More or less what @tonyvugithub said needs to happen

**Comment by manekenpix** [comment]
Completely missed it in #1137. Closing this one then.
