### ISSUE TITLE
Some images are stretched too large

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1199]
We have CSS to shrink images so they don't exceed the bounds of the post container.  It works great for 95% of the images I see.  However, it also means that we expand small images to fill the space, too, and it can look odd:

<img width="814" alt="Screen Shot 2020-10-14 at 10 17 11 AM" src="https://user-images.githubusercontent.com/427398/96002042-b093c900-0e06-11eb-9c7a-9ab775c4fcb6.png">

We probably need to remove this, but it might require other tweaks too:

https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Post/telescope-post-content.css#L22

**Comment by cindyledev** [comment]
I'd like to give this a shot
