### ISSUE TITLE
Mockups for user interface

### ISSUE THREAD

**Issue by Reza-Rajabi** [Seneca-CDOT/telescope#12]
We have discussed in [issue #3](https://github.com/Seneca-CDOT/telescope/issues/3) about our frontend technology. But how our final frontend looks like? This is important that we think about it for the number of reasons:
- Knowing how our UI looks like helps us to identify our app's features and our project's scope.
- Having a UI design gives us an idea about who can work on what in terms of our front-end development (We can modularize our front-end development)
- The design itself could be somebody's task if they are interested in and if it is acceptable for the purpose of this project.

**Comment by ODAVING** [comment]
If no one is working on the mockup, I can use Adobe XD to create a mock up of what it can look like. @humphd @Reza-Rajabi Do you guys prefer the mockup? or should I just go ahead and create an HTML document issue #3

**Comment by lucacataldo** [comment]
@ODAVING I don't mind taking the reigns on the design & prototyping or helping you out. Want me to start out by making a shared XD document? That'll allow everyone to contribute ideas and whatnot to the design.

**Comment by ODAVING** [comment]
If this is acceptable then I’d like that! Otherwise we should get started
with the static html. Awaiting David’s response to this.

**Comment by lucacataldo** [comment]
Sounds good! I'll get started on a general mockup with XD regardless that way the actual creation of the HTML will be easier later on. Will make a link available later on today for review & editing.

**Comment by Reza-Rajabi** [comment]
@ODAVING @lucacataldo I made this issue more as a discussion, so feel free to start working on this as you wish.

**Comment by lucacataldo** [comment]
Here's the link to review & comment on the design, if anyone would like write / edit access to the file please contact me.

https://xd.adobe.com/view/f1e160d0-2c49-4700-4ca6-2f2f660dfb6f-87d0/

**Comment by KarlaChen** [comment]
@lucacataldo For the participants page, can we add a quick search bar then people can easy to find the people name.

**Comment by ODAVING** [comment]
This is a good place to get inputs while we build the static page

**Comment by lucacataldo** [comment]
@KarlaChen Good idea Karla, I've added a "quick and dirty" search bar design to the participants modal

**Comment by KarlaChen** [comment]
@lucacataldo I was thinking use anchorScroll or search bar which one is better, eg: There is A,B, C on the side, when you click A, it will go to the section A and show all the name start from A.

**Comment by lucacataldo** [comment]
@KarlaChen I was envisioning as a "search while you type" search bar where you can just start typing and filter down the list of participants, the functionality will likely be discussed when the development of the page starts though at which point we can test out different ideas!

**Comment by ODAVING** [comment]
Is the mockup up to date for this issue? I'm starting on enhancing the HTML portion of it in issue #61

**Comment by KarlaChen** [comment]
I want to do it as well. Is it possible to do it together?

**Comment by ODAVING** [comment]
@KarlaChen I'll add you to the slack channel, if it was containerized, with multiple pages, I'd say yes, but as of right now, it's just the index.html that's about it :(

**Comment by lucacataldo** [comment]
@ODAVING the mockup contains everything discussed in this thread but I haven't added anything from any other threads as of yet. Trying to get more people added to the XD document as contributors to spread the load and keep things up to date.

I agree though it's tough to split load in terms of templating and html cause it'll likely be one large doc and it won't work if everyone's working on the same file.

**Comment by lozinska** [comment]
Hi guys @lucacataldo, @KarlaChen, @ODAVING I was reading through this discussion and I have some questions
1. What will go into IMG part?
2. Do you think it's important to show whole post or may be just first few sentences with ability to "show more" if user wish to continue reading?

**Comment by KarlaChen** [comment]
@lozinska I prefer show more cause people can read a part of it and know they are interested in it or not.

**Comment by lucacataldo** [comment]
@lozinska I think that's a great idea! As far as the <img> goes it was just intended to show how images might be positioned / formatted in a post should someone insert them. It doesn't necessarily mean that every post will have one.

**Comment by humphd** [comment]
Do we still need this issue?  Should we start iterating on what's landed in src/frontend?  Or is there more design work you want to do here?  If we can, I'd close this and open new issues on iterating.

**Comment by Reza-Rajabi** [comment]
I think we are good to close this one.

@ODAVING @lucacataldo @KarlaChen @lozinska 
I close this issue. You might open it up again if we need to, or make a new issue to address current design concerns.
