### ISSUE TITLE
Add coverage reporting to Jest

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#120]
Having tests is great, but only if they test the code we have: all functions, branches within those functions (e.g., if/else), etc.  It can be hard to know if you are testing everything in your code without getting detailed reports.

One tool we can use is a test coverage report.  [Jest will automatically](https://jestjs.io/docs/en/cli#coverage) do this if we configure it.  Someone should enable code coverage so we can see if we're missing some part of a file.

**Comment by jpjjulie** [comment]
Hi, I would like to work on this issue.

**Comment by miggs125** [comment]
FYI this can be done by configuring jest by adding the following to the package.json file:
```json
"jest": {
    "collectCoverage": true,
    "coverageReporters": ["json", "html"],
    "testEnvironment": "node",
    "coveragePathIgnorePatterns": [
      "/node_modules/"
    ],
  }
```
Here we are telling jest to collect coverage, the type of format, ignore coverage for node_modules and the test environment (node). You can also opt to configure jest in a ```jest.config.js ``` file instead. Depending on the amount of configuration you'd like to include, the latter might make more sense and would make things easier to maintain.

You can find more information on configuring jest [here](https://jestjs.io/docs/en/configuration). If you need any help feel free to ping me here on on slack and I'll be happy to help :)

**Comment by jpjjulie** [comment]
Thank you very much @miggs125
