### ISSUE TITLE
Allow giphy.com iframes to load

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1203]
**What happened**: If the author including a gif, it does not display in Telescope

**What should have happened**: the gif should display as expected

![image](https://user-images.githubusercontent.com/55034244/96141005-958c8c00-0ece-11eb-8d8e-dd418498dbe6.png)

**Comment by humphd** [comment]
This is due to us stripping iframes from posts, due to security restrictions.  We allow iframes only from YouTube and Vimeo, but anything else gets destroyed.

I wonder if we should actually remove the entire element, or replace it with something else vs. showing this hole?

**Comment by manekenpix** [comment]
Also, I think `GIFs` are not blocked:
![Peek 2020-10-15 10-34](https://user-images.githubusercontent.com/23108901/96144219-ef428580-0ed1-11eb-805b-aa2087f4078f.gif)

**Comment by tonyvugithub** [comment]
@manekenpix : I should have said gifs from some specific hosts.

**Comment by tonyvugithub** [comment]
@humphd since this was intentional, should I close this issue?

**Comment by humphd** [comment]
The iframe in question here is https://giphy.com/gifs/web-shittyreactiongifs-4FQMuOKR6zQRO.  Let's add `giphy.com` to https://github.com/Seneca-CDOT/telescope/blob/6e1627ed5c20687e65aa40eb4ea08c84b468d120/src/backend/utils/html/sanitize.js#L49 and a new test like this one https://github.com/Seneca-CDOT/telescope/blob/6e1627ed5c20687e65aa40eb4ea08c84b468d120/test/sanitize-html.test.js#L44-L47.

**Comment by tonyvugithub** [comment]
@humphd you want me to take it as I kinda work on sanitize a bit already. I ensure I finished the other one first though.

**Comment by humphd** [comment]
Sure, sounds good.
