### ISSUE TITLE
Delete lines #61 #62 from src/frontend/src/components/ScrollToTop/ScrollToTop.jsx

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1206]
The line 61 and 62 of src/frontend/src/components/ScrollToTop/ScrollToTop.jsx should be deleted because we are no longer using it.
There are comments in the code to fix it.

**Comment by neilong31** [comment]
Hey! I'd love to do this.

**Comment by manekenpix** [comment]
@neilong31 assigned to you.
