### ISSUE TITLE
Gatsby Proxy Not working as Intended

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#1212]
**What happened**:
Trying to login using settings suggested in gatsbyjs.md for the front-end is not working. Users are redirected to localhost:3000 or loclahost:{PORT} . Users have to use `npm run build` instead to use the login functionality when developing locally, which significantly slows down development.

**What should have happened**:
Users should redirected be redirected to localhost:8000 after clicking login or upon successfully logging in.

**How to reproduce it (as precise as possible)**:
1. set `PROXY_GATSBY=1` in .env
2. Have telescope back-end running locally
3. `npm run develop`
4. Try logging in with user1 and user1pass at `localhost:8000`

**Anything else we need to know?**:

**Environment**:

- OS: MAC OS 10.15.7 Catalina
- Browser: Chrome

**Comment by c3ho** [comment]
@cindyledev  and @PedroFonsecaDEV also experienced similar issues

**Comment by humphd** [comment]
Login stuff won't work with the proxy.  You have to have the origins you authenticate from match what the authentication settings expect.  This is one case where you have to run it in a "production" like way.

Should we update docs to help people not trip over this?

**Comment by c3ho** [comment]
Definitely
