### ISSUE TITLE
Decouple Banner loading from Stats info

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1218]
We are making startup slower than in needs to be in https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Banner/Banner.jsx.  Let's split the stats display in https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Banner/Banner.jsx#L163-L168 into a `<Stats />` component and move the API call to the server there too. Similar to what we're doing in #1217, let's use https://swr.vercel.app for this, so it can cache the results on the client.  Let's get rid of https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Banner/Banner.jsx#L154 and always render the banner as soon as we can.

**Comment by PedroFonsecaDEV** [comment]
Can I give a try?

**Comment by humphd** [comment]
Yup, go for it!
