### ISSUE TITLE
Heading h1 is not inline with the rest of the post in some post

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1219]
**What happened**: The h1 heading was shift to the right thanks to extra left margin

**What should have happened**: It should have no left margin so it would be consistent with blogs from other sources.

**How to reproduce it (as precise as possible)**: Go to this blog post of Zongwei Yang
![image](https://user-images.githubusercontent.com/55034244/96658265-18b84280-1312-11eb-9dc0-209657c88530.png)

**Comment by Shinh18** [comment]
Hey, I would like to work on this issue. 
Thanks

**Comment by humphd** [comment]
OK @Shinh18 go for it

**Comment by Shinh18** [comment]
@humphd I think this issue is already fixed. 
![Screen Shot 2020-11-16 at 1 11 51 PM](https://user-images.githubusercontent.com/48449650/99291173-6179f300-280d-11eb-967d-f6e565053b3c.png)

**Comment by humphd** [comment]
cc @tonyvugithub. If it's fixed, we should close.
