### ISSUE TITLE
Catch testing error and display a more user friendly error message. 

### ISSUE THREAD

**Issue by ImmutableBox** [Seneca-CDOT/telescope#122]
Currently when running `npm test` you get this error if the Redis server is off:
```
(node:46320) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:46320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:46320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Should catch this error and display a more user friendly error message. 

Here is a link that may help facebook/jest#5311
- - -
I think this issue was mention before, but I couldn't find the issue relating to this one. Can close if it already exist.

**Comment by humphd** [comment]
See previous discussion in https://github.com/Seneca-CDOT/telescope/pull/116#issuecomment-552070543 and #48.  CC @aprilllllllll

**Comment by aprilllllllll** [comment]
Yes, I am working on this.

**Comment by humphd** [comment]
https://github.com/Seneca-CDOT/telescope/pull/494#issuecomment-565826164 is another example of the problem this needs to fix.
