### ISSUE TITLE
Better error/loading handling when posts can't be loaded

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1220]
Right now we don't do a very good job when posts are loading, or can't be loaded form the backend:

In  src/frontend/src/components/Post/Post.jsx:

```js
  if (error) {
    console.error(`Error loading post at ${postUrl}`, error);
    return null;
  }
```

and again:

```js
  if (!post) {
    return <div>Loading...</div>;
  }
```

and in src/frontend/src/components/Posts/Posts.jsx:

```js
 // TODO: need proper error handling
  if (error) {
    console.error('Error loading post data', error);
    return null;
```

We should do a better job signaling things in the UI.

**Comment by zjjiang2** [comment]
Hi professor Humphrey, I would like to work on this issue.

**Comment by humphd** [comment]
@zjjiang2 it's all yours, thank you!

**Comment by humphd** [comment]
cc @agarcia-caicedo, @cindyledev, @raygervais, etc who might have thoughts here.

What is the correct UI choice for cases there we error talking to the backend?  The timeline should somehow indicate that we've tried and failed to load post data somehow, without overloading the user.
