### ISSUE TITLE
Reduce amount of JSON sent from backend with query results

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1221]
In #1217 I'm changing the way our search code works so that we only require a Post's `id` to show results.  Let's modify how the backend `/query` route and front-end `SearchPage` work so that they don't send or require the raw text of the post.  This will involve modifying how the data we get back from an Elasticserach query is formatted.  

Relevant files:

- Elasticsearch backend - https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/indexer.js
- `/query` route in the API server - https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/query.js
- tests for `/query` route - https://github.com/Seneca-CDOT/telescope/blob/master/test/query.test.js
- `SearchPage` component - https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/SearchPage/SearchPage.jsx

Right now we return data that looks like this:

```js
{
  results: 1436
  values: [
    {
      id: '0f8021a157',
      text: 'full text of post....................'
      score: 4.913031
    },
    ...
  ]
}
```

The `results` are how many matches were found, and `values` is an array of matches on posts.  Within these we get `id` (which we want`) and `text` (which is huge and we don't need), and then `score` which may or may not be valuable, if we pre-sort on it so that the posts are already ordered by score.

**Comment by StellaJung-Student** [comment]
Hello @humphd, if nobody takes this issue, can I try this?

**Comment by c3ho** [comment]
@StellaJung-Student The data is going to looks like this
```
{
  results: 1436
  values: [
    {
      id: '0f8021a157',
      text: 'full text of post....................'
      score: 4.913031
    },
      id: '0f8021a158',
      text: 'full text of post....................'
      score: 5.132
    },
      id: '0f8021a159',
      text: 'full text of post....................'
      score: 4.8232
    },
  ]
}
```
What he's asking is to order these values by the score in descending order and then only take the top N (set by environment variable).

**Comment by StellaJung-Student** [comment]
I got it but for testing, do I need to sign up? I got this error, GET http://localhost:3000/auth/login 500.

**Comment by c3ho** [comment]
You won't need to sign in for this, since we're using the search function of telescope. You can always just `console.log(searchResults)` at line 95 of https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/SearchPage/SearchPage.jsx and open up the developer console

**Comment by StellaJung-Student** [comment]
The response data is always 'text: '{"results":0,"values":[]}' even in previous test case, query.test.js. I can commit but I don't know how I can make sure my task is correct.

**Comment by c3ho** [comment]
Do you have the backend running at least? If you have it running natively you won't need docker. I would highly recommend docker though, as it is the easiest way to run everything in the backend. Let me know if you have other questions. Feel free to ask more questions on the slack channel in Telescope if you're still having issues

**Comment by StellaJung-Student** [comment]
![image](https://user-images.githubusercontent.com/59578350/97518440-8b0dd000-196d-11eb-86cd-031ad452433b.png)

Oh I didn't know about backend setting~ ok I will talk to you on slack.

**Comment by StellaJung-Student** [comment]
Server is working~ but still I am struck on the search with no result.
![image](https://user-images.githubusercontent.com/59578350/97524839-eb0b7300-197b-11eb-8260-3d6a8bf98262.png)

**Comment by manekenpix** [comment]
@StellaJung-Student In the search page, you need to click on `filter` and select a filter (in this case, it'd be `Post`). I think we should file an issue for that.

cc @c3ho

**Comment by c3ho** [comment]
I'm so blind. I forgot the search function changed. I remember I had either of the options set by default so this doesn't happen

**Comment by StellaJung-Student** [comment]
Oh my god, Thank you so much~ if you want me to add the validation ~ let me know~. :)

**Comment by StellaJung-Student** [comment]
Thank you both of you. I learned a lot from you guys~. I will take a look at this issue~

**Comment by StellaJung-Student** [comment]
So confused about this server and I didn't get it yet. I logged and threw the error before returning values but no error...
The code and file structure is understandable but I am not sure that I am on the correct place.
![image](https://user-images.githubusercontent.com/59578350/97531851-75a79e80-198b-11eb-8360-dcfc49c02b64.png)
It turned out no errors and frontend worked well.

**Comment by c3ho** [comment]
@StellaJung-Student I think you're thinking too much into this. Here's what I suggest in [query.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/query.js) line 26 let's break it off so we have something like
```
const data = await search(req.query.search)
//code to modify our data here
res.send(sortedData)
```

**Comment by StellaJung-Student** [comment]
OK. I am not going to think too much.

For sort, I need to use _score property but it is not allowed to use by the rule of no-unserscore-dangle. 
Can I use "eslint-disable-next-line no-underscore-dangle" or I can avoid it?

**Comment by c3ho** [comment]
I don't think you need underscores as the code should look something like
```
const data = await search(req.query.search)
const sortedData = data..sort((a,b) => b.value - a.value)
// return sliced data
```

**Comment by StellaJung-Student** [comment]
I don't think this is a solution. @humphd  mentioned removing the text field is the main purpose for this task and the score is only used for sorting. In the file, indexer.js, previously, it used _id, _text, _score so I tried to delete _text and with _score, tried to sort.
Like this way, const values = hits.hits.sort((a, b) => { return b._score - a._score; }).map(({ _id }) => {  return {  id: _id,   }; });  before the return {   results,  values,  };.
Am I wrong?

**Comment by c3ho** [comment]
No, you're right. That makes it a lot easier now then.
```
  const values = hits.hits
    .map(({ _id, _score }) => {
      return {
        id: _id,
        score: _score,
      };
    })// add sort here
```

**Comment by StellaJung-Student** [comment]
Oh, thanks~ you are right~ and it is better that if I use map first.

**Comment by c3ho** [comment]
```
  const results = hits.total.value;
  const values = hits.hits
    .sort((a, b) => b.score - a.score)
    .map(({ _id }) => {
      return {
        id: _id,
      };
    });

  return {
    results,
    values,
  };
```

**Comment by StellaJung-Student** [comment]
The basic object does not have score property, which is { _id, _text, _score }
You code will cause error.
You should use _score.
Do I miss anything?

**Comment by c3ho** [comment]
use "\```" before start of code and "```" the key right to the left of the 1 on keyboard. I tested this code and it should work, I kept the score on previously so I can check if they're right or not:

![image](https://user-images.githubusercontent.com/18711727/97602825-25a7f680-19e2-11eb-9734-88ef3be11b8b.png)

**Comment by StellaJung-Student** [comment]
Of course it was working since the original code like this
```
  const values = hits.hits.map(({ _id, _source, _score }) => {
    return {
      id: _id,
      text: _source.text,
      score: _score,
    };
  });
```
The return value are changed {id, text, score} from the {_id, _text, _score}.
Did you get it?

**Comment by c3ho** [comment]
I don't even think you need to do sort, since the results are sorted already. You just need to remove the text and score from the `map` function

**Comment by humphd** [comment]
Or even just:

```js
const values = hits.hits.map(({ _id }) => ({ id: _id }));
```

So we spit back an array of `id`s.

**Comment by StellaJung-Student** [comment]
@c3ho my original question is that I thought the score is only for sort value that's why I though I needed sort.
@humphd In this case, I thought two options like below.
```
hits.hits.map(({ _id, _score }) => {  
      return {  
        id: _id,  
        score: _score,  
      };  
    })  
    .sort((a, b) => {  
      return b.score - a.score;  
    })  
    .map(({ id }) => {  
      return {   
         id  
      }  
    });  
```
I want this
```
hits.hits.sort((a, b) => {  
      return b._score - a._score;  
    })  
    .map(({ _id }) => {  
      return {  
         id: _id  
      }  
    });  
```
@humphd I know your solution. but that is not my question~

**Comment by c3ho** [comment]
Yeah, the results we get back from es are already sorted, so we only have to remove `id` and `score` from the map part. @humphd solution is correct.

**Comment by StellaJung-Student** [comment]
OK. I see~ I didn't know the elastic search provide sorted data.
Then you guys are right~
