### ISSUE TITLE
Allow paging through search results

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1222]
In #1217 I'm adding some data fetching paging logic using https://swr.vercel.app.  It could also be used for our search front-end (e.g., SearchPage.jsx) to allow us to page through the results we get back from our backend.

To do this, we need to pass the data to our `<Timeline>` component in "pages" like this:

```jsx
<Timeline pages={arrayOfArraysOfPosts} nextPage={functionToGetNextPage />
```
 
The data we get back from the server for a query looks like this:

```js
{
  results: 1436
  values: [
    {
      id: '0f8021a157',
      text: 'full text of post....................'
      score: 4.913031
    },
    ...
  ]
}
```

See #1221, where this might change a bit.  We know the number of `results`, and could request chunks of it using the `from` and `size` options in our elasticsearch query.  We'd have to update our `/query` route to accept params with this info, and then do something like this https://swr.vercel.app/docs/pagination#example-2-cursor-or-offset-based-paginated-api.

**Comment by humphd** [comment]
I'm doing something pretty similar in https://github.com/Seneca-CDOT/telescope/pull/1217 if you want to see more code like this, and https://codesandbox.io/s/swr-infinite-z6r0r?from-embed=&file=/src/App.js is helpful

**Comment by joelazwar** [comment]
@humphd I looked into PR #1343 and saw the changes for the search page. So I made a new branch based on that and added on to it to get the paging functionality working. Once that PR gets merged I'll rebase and make a PR for this. Here's the branch for now [issue-1222](https://github.com/joelazwar/telescope/tree/issue-1222)

**Comment by humphd** [comment]
@joelazwar #1343 is merged, go ahead and rebase onto master.
