### ISSUE TITLE
Merge our two "sticky headers" on scroll

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1223]
We landed a fantastic PR the other day to support scrolling and having 2 sticky headers.  The only down side of it is that the two headers take up a lot of space at the top.

Today I noticed that GitHub does something similar, but collapses the two down into a single-height header:

![scroll-header](https://user-images.githubusercontent.com/427398/96662747-0abbef00-131d-11eb-8610-45e26394a273.gif)

I wonder if we should flip our top header into the "mobile" view and show the menu on the right vs. the words/icons:

<img width="319" alt="Screen Shot 2020-10-20 at 9 44 51 PM" src="https://user-images.githubusercontent.com/427398/96662916-80c05600-131d-11eb-991c-71731b7b65f8.png">

Then we could slide the post title into the middle, empty section between the logo and search/menu icons.  That would let us do both things in the same amount of space.

**Comment by humphd** [comment]
cc @PedroFonsecaDEV, who worked on the current sticky header solution.

**Comment by PedroFonsecaDEV** [comment]
I agree with you that we need to improve this feature. 
Tomorrow I will create a sketch so we can discuss it together to find the best solution before I start to code it. 

You can assign me to this issue too. 
Thanks.

**Comment by PedroFonsecaDEV** [comment]
We need to think about #1193 if we will have both or just one of them. 
It would be nice to see some sketches about it.
@agarcia-caicedo @humphd

**Comment by PedroFonsecaDEV** [comment]
(Oct/27)Update after sketches: 
I'm working on this issue.

**Comment by PedroFonsecaDEV** [comment]
I'm still working. The last commit doesn't represent the final work.
