### ISSUE TITLE
Show all posts for an author sorted by date when searching by Author

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1224]
When I search "by Author" I really want to see all the posts we have for this user.  It would be great to either replace what we have now with a timeline of their posts, sorted by date (newest to oldest), or add that to what we have now.

**Comment by joelazwar** [comment]
hey @c3ho, i just got the telescope dev env setup on my computer after a few days of trying LOL. was wondering if i could try and attempt to fix this issue as part of my OSD assignment since it looks doable for me😂

**Comment by c3ho** [comment]
No worries, go for it
