### ISSUE TITLE
Reposition search button for search UI

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1225]
Our frontend kicks off searches every time you start typing.  I'd love to see us:

- add a button so it doesn't happen until I click or press 'enter'
- and/or debounce this keyboard event so it doesn't start happening until I finish typing

If you type something like, it will fire and re-fire the query on every letter.  That's bad UI, and it overloads the network and React.

**Comment by agarcia-caicedo** [comment]
There currently is a button, but I'm not sure about the code surrounding it, so I'm not sure if its currently doing what its supposed to or not.

**Comment by humphd** [comment]
I didn't realize that icon was clickable.  Could we move it down so it's inline with the text box that it goes with?  It looks like decoration vs. usable UI to me.

**Comment by TDDR** [comment]
Hello, I would like to take a stab at this one if you could assign me please.

**Comment by c3ho** [comment]
@manekenpix is this being fixed as part of your PR?

**Comment by manekenpix** [comment]
Yes, this is addressed in #1295

**Comment by c3ho** [comment]
@TDDR sorry about that, do you mind picking up another issue?

**Comment by manekenpix** [comment]
#1295 doesn't move its position though, so that's something that could be done. @TDDR

**Comment by c3ho** [comment]
With #1295 , I'm going to change the title of this to repositioning it instead.

**Comment by strawberries73** [comment]
@humphd I would like to work on this issue.

**Comment by humphd** [comment]
@strawberries73 go ahead and assign to yourself.
