### ISSUE TITLE
Fix timeline width in search results

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1226]
In #1217 I updated how our search results show for posts, but I couldn't get the width right on the container (there's extra padding/margin that makes it narrower than it should be):

![Screen Shot 2020-10-20 at 9 52 59 PM](https://user-images.githubusercontent.com/427398/96663488-bfa2db80-131e-11eb-825e-b1dee4fa9e95.png)

I think the posts should be the same width as the search UI above it.

**Comment by agarcia-caicedo** [comment]
I'll work on it

**Comment by humphd** [comment]
Possibly the same bug or a related issue to #1180.

**Comment by pyvelkov** [comment]
I think I just fixed this in #1292 
Pending Review.
