### ISSUE TITLE
Improve ordering of search results

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1228]
Today I needed to find a post that I know I read last week.  I remembered that the author wrote about 'UtilityBelt', so I tried searching for it.  The post gets returned, but as the 10th results, and all other results have nothing to do with this search term.

I think what's happening here is related to #1225 and I'm actually seeing results for partial strings vs. the entire string.

**Comment by manekenpix** [comment]
I think it's also related to the fact that we use [fuzzy queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html) in elasticsearch (which seemed like a good idea back when we added the search engine).

**Comment by humphd** [comment]
I think elastic is doing the right thing and this is stale data in the DOM, check this out:

<img width="1198" alt="Screen Shot 2020-10-21 at 10 18 36 AM" src="https://user-images.githubusercontent.com/427398/96732892-d5e48200-1386-11eb-9c59-74b998060316.png">

Eventually, there is a single hit, but I don't see that in the UI, I get old posts instead.

**Comment by humphd** [comment]
If I press the Search button, and re-trigger the search, it does the right thing.  So it's somehow a state thing?

**Comment by manekenpix** [comment]
Hmm, so fixing #1225 would maybe take care of this issue as well?

**Comment by humphd** [comment]
Maybe?  I'm guessing at root cause, but evidence seems to indicate we have cached nodes in the DOM somehow.

**Comment by manekenpix** [comment]
@c3ho did you last PRs fix this?

**Comment by c3ho** [comment]
Fixed via #1275
