### ISSUE TITLE
Showcase our contributors

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1232]
I notice that [node.js has this cool feature in their footer](https://nodejs.org/en/), where the highlight a contributor to their project:

<img width="399" alt="Screen Shot 2020-10-21 at 9 01 22 PM" src="https://user-images.githubusercontent.com/427398/96805906-b5e1ac80-13e0-11eb-885a-7dca81fa13ed.png">

I wonder if we could include something similar somewhere in our app?

**Comment by agarcia-caicedo** [comment]
We could implement something like this in our about page. The page there has a footer, and a picture carousel with nothing related to telescope on it right now.

**Comment by humphd** [comment]
That's a great place for it, agree.

**Comment by TDDR** [comment]
Hello, I can try to implement this if you could assign me please.

**Comment by humphd** [comment]
Yes, all yours @TDDR

**Comment by TDDR** [comment]
Just to clarify, do you want me to replace the pictures in the carousel with the contributors, or place them in the footer like on the node web page?

**Comment by humphd** [comment]
To start, let's try and do something like they do in node in the footer.  But we can play with the location and look.  I'd start by making this work at all, since you'll need to talk to the GitHub API to make it happen.

**Comment by manekenpix** [comment]
Should we close this?

**Comment by humphd** [comment]
Indeed, finished!
