### ISSUE TITLE
Migrate front-end from GatsbyJS to Next.js

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1237]
**What would you like to be added**:

We'd like to try porting the front-end from GatsbyJS to [Next.js](https://nextjs.org/).  We've been enjoying other Vercel technologies (hosting previews for our front-end changes for PRs, [`useSWR` React data hook](https://github.com/vercel/swr)), and this seems like another good fit.

**Why would you like this to be added**:

![Screen Shot 2020-10-23 at 11 36 57 AM](https://user-images.githubusercontent.com/427398/97023851-175e6400-1524-11eb-9217-bc1f2f49de19.png)

We gave Gatsby a shot, and I think it's a good tool for a particular use case, namely, data-driven 100% static sites.  However, we never built one of those.  Telescope is a data-driven SPA that relies on server calls.  This appears to be the use case for Next.js, which is made to build hybrid web apps.

Supporting changes in Gatsby has been a bit painful, and I think we're ready to try something new.

There are some good resources we can use to do this work:

- [Next.js Docs](https://nextjs.org/docs/getting-started)
- [Next.js Learning Course](https://nextjs.org/learn/basics/create-nextjs-app)
- [Migrating from Gatsby](https://nextjs.org/docs/migrating/from-gatsby)

Also, @cindyledev mentioned that there is an upcoming conference, [October 27, 2020 Online Next.js Conference (free)](https://nextjs.org/conf).

**Process**

Let's do this in stages across a bunch of PRs/Issues.  I'd like to get a bunch of people involved in my OSD/DPS class after reading week.  We can all learn it together.

The first issue I think we should solve is to create a `next` branch, and we can run two parallel versions of the frontend on `master` (Gatsby) and `next` (Next.js).  When we get the `next` branch up to par with `master`, we'll merge and do a `2.x` release.

Then we can tune our Vercel PR previews to use the new front-end.

For now, we should all do some research on how Next.js works.

**Comment by humphd** [comment]
https://adrien.harnay.me/2020-11-02-migrating-your-website-from-gatsby-to-next-js is timely.

**Comment by cindyledev** [comment]
> https://adrien.harnay.me/2020-11-02-migrating-your-website-from-gatsby-to-next-js is timely.

Wow this looks like it solves the headache of migrating the About markdown page over to Next.js

**Comment by humphd** [comment]
Done!
