### ISSUE TITLE
npm run release failed on Windows

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1238]
**What happened**: 
When ran `npm run release` on a windows machine, nothing happened. Apparently, it has something to do with the way .env file is read.

**What should have happened**:
The command should work regardless of system.

**How to reproduce it (as precise as possible)**:
Use a windows machine and run `npm run release`

- OS: Windows

**Comment by humphd** [comment]
Fixing https://github.com/Seneca-CDOT/telescope/issues/1301 might be preferable to this, so we can get rid of the cli release process completely.

**Comment by tonyvugithub** [comment]
@humphd : Should I close this issue then to prevent any overlap?

**Comment by humphd** [comment]
Sure, let's do that.
