### ISSUE TITLE
Inconsistency when run coverage vs test

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1239]
**What happened**:
When I run `npm run coverage`, there is one failed test in wiki-feed-parser.test.js, but when I run `npm run test`, everything passes. This could potentially be a bug.
The file is here https://github.com/Seneca-CDOT/telescope/blob/master/test/wiki-feed-parser.test.js
![image](https://user-images.githubusercontent.com/55034244/97034629-33b5cd00-1533-11eb-9b9d-505add0de8ff.png)

**What should have happened**:
The results should be the same for both commands.
**How to reproduce it (as precise as possible)**:
run `npm run coverage` , then run `npm run test`

**Comment by egrinberg** [comment]
I would try this out.

**Comment by manekenpix** [comment]
@egrinberg All yours!
