### ISSUE TITLE
Add tests for backend/web/routes/auth.js

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1240]
**What would you like to be added**: 
Tests for `backend/web/routes/auth.js`
**Why would you like this to be added**:
To have everything tested under `backend/web/routes`

**Comment by Shinh18** [comment]
@tonyvugithub I'd like to work on this issue.

**Comment by humphd** [comment]
This is going to be hard.  If you want to write a test for the backend, I'd pick something missing from the coverage report in https://github.com/Seneca-CDOT/telescope/issues/1160.

**Comment by humphd** [comment]
This has been done in the new auth service, closing.
