### ISSUE TITLE
Syntax highlighter not working

### ISSUE THREAD

**Issue by smilegodly** [Seneca-CDOT/telescope#1246]
**What happened**:

Was scrolling through dev and noticed no highlighting in the code blocks. Noticed it's also in prod.

**What should have happened**:
The syntax highlighter we use is https://highlightjs.org/ and the code should be the github highlight theme

**How to reproduce it (as precise as possible)**:
look at the code blocks on dev / prod

**Anything else we need to know?**:
Here is a picture

![image](https://user-images.githubusercontent.com/35276477/97154395-33dbe580-174a-11eb-8007-b5350c725948.png)

And another

![image](https://user-images.githubusercontent.com/35276477/97154189-ff682980-1749-11eb-8053-44ca37f07da5.png)

**Environment**:

- OS:
- Browser:

**Comment by smilegodly** [comment]
I'll work on this one, it upsets me.

**Comment by manekenpix** [comment]
@smilegodly All yours, thank you!

**Comment by humphd** [comment]
I screwed it up in [this PR](https://github.com/Seneca-CDOT/telescope/pull/1217/files#diff-459129dde45c8c16baf44c2d2206faed2dbc39df42342e91f4970898042c8255L34) when I removed `import 'highlight.js/styles/github.css';`
