### ISSUE TITLE
An Empty Blog Appeared

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#1249]
**What happened**:
A blog with no content got posted. The link does not link back to a blog post, but the post does exist and it has no content.

![image](https://user-images.githubusercontent.com/49992710/97252899-756b9f80-17e1-11eb-9bcb-8551ee0f1a4e.png)

**What should have happened**:
Blogs with no content should not appear

**Environment**:

- OS: Windows
- Browser: Firefox, Chrome

**Comment by humphd** [comment]
cc @chawlapalak

**Comment by chawlapalak** [comment]
Hi all, 

I can help you out with this. I did not write the content in the blogger, I was making some changes to it in my local computer and made the template of Lab 5 to post it there. I have not pasted it yet. Moreover, I did not use the "open source" label so it wont display in the Telescope feed, but it did, I guess. 

So this is what I did.

**Comment by 1jz** [comment]
Hey, I looked into this and it seems like we add posts that pass the tests found at https://github.com/Seneca-CDOT/telescope/blob/7d97026fa84687986bb7a81bb477246c1d892f63/src/backend/data/post.js#L98

The `description` which holds the html for the blog posts can contain whitespace it's context which should be invalid. I created a fix for this but I just need to find a way to test it.

**Comment by humphd** [comment]
@1jz nice!  You need to add a test case here https://github.com/Seneca-CDOT/telescope/blob/master/test/post.test.js#L143-L238, following the style of what we already have, but with empty `description`.
