### ISSUE TITLE
Syntax highlighting for <pre> vs. <pre><code>

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1250]
I noticed that we aren't syntax highlighting all code blocks:

<img width="983" alt="Screen Shot 2020-10-27 at 1 29 09 PM" src="https://user-images.githubusercontent.com/427398/97339023-70960280-1858-11eb-9383-55f277e50bb9.png">

It looks like this uses a `<pre>` without a `<code>`.  I wonder if we should be looking for `<pre>` without `<code` as well?

**Comment by smilegodly** [comment]
Can I give this a shot?

**Comment by humphd** [comment]
Yeah, go for it.  I'm a bit concerned that doing this for all `<pre>` might cause some unwanted side effects, but let's see.
