### ISSUE TITLE
/planet won't load images due to CSP

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1257]
We tweaked our Content Security Policy recently, and it's causing the `/planet` front-end to break for all images.

STR:

1. Open https://telescope.cdot.systems, notice it displays images
1. Open https://telescope.cdot.systems/planet in a second tab, notice you have no images

I get the following errors in the console:

In Chrome:

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://1.bp.blogspot.com/-UbK3cE5UlpE/X55fbQ45iTI/AAAAAAAAC3s/8DrI5X9Ee2IeT6n0_FXPPctlxs50u1OMACLcBGAsYHQ/w642-h239/telescope12234.PNG (“img-src”).
```

In Firefox:

```
Refused to load the image 'https://1.bp.blogspot.com/-UbK3cE5UlpE/X55fbQ45iTI/AAAAAAAAC3s/8DrI5X9Ee2IeT6n0_FXPPctlxs50u1OMACLcBGAsYHQ/w642-h239/telescope12234.PNG' because it violates the following Content Security Policy directive: "img-src 'self' data:".
```

Let's [update our `img-src` directive](https://content-security-policy.com/img-src/) to be less restrictive.

**Comment by zg3d** [comment]
Hey, can I work on this issue?

**Comment by humphd** [comment]
@zg3d all yours.

**Comment by zg3d** [comment]
@humphd I think this is not an issue and has been fixed in a previous commit.

**Comment by humphd** [comment]
@zg3d awesome, thank you for confirming.

**Comment by zg3d** [comment]
@humphd  the code in app.js in the current repo is accurate however when i check with a csp Evaluator in the current dev build. The https src in image-src is not shown or used ending up with the above console error.
https://github.com/Seneca-CDOT/telescope/blob/b3ea97107ac7ea6ecf91c0a9800c1de02ff4d914/src/backend/web/app.js#L31
`![image](https://user-images.githubusercontent.com/25188774/99179631-870fdb00-26ed-11eb-9c56-f0bbdae105f7.png)`

**Comment by humphd** [comment]
We should probably fix up our CSP in a few ways.  These online evaluators flag a couple of different things. @zg3d do you want to work on this or leave for someone else?

**Comment by zg3d** [comment]
Ill leave it for someone else as I am unsure of the interaction here.
