### ISSUE TITLE
Allow searching for exact phrases vs. AND'ing all search terms

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1259]
Our Elasticsearch indexer uses AND on all terms entered in a search.  It would be nice if we could also search by phrase, maybe using double-quotes?

I was trying to find a blog post by entering an exact phrase I know is in it, but that returns a ton of other searches.

**Comment by c3ho** [comment]
We currently have the following code when we perform a search on elasticsearch
```
const search = async (textToSearch) => {
  const query = {
    query: {
      match: {
        text: {
          query: textToSearch,
          operator: 'AND',
          fuzziness: 'auto',
        },
      },
    },
  };
```

I don't think AND for the operator here is the issue, but the [fuzziness](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/common-options.html#fuzziness) can be instead set to 0 to only send you exact results. If that's the case we can change the search function to see if the first char and last char in the `textToSearch` param contains quotes, if it does we can try setting `fuzziness` to 0?

**Comment by humphd** [comment]
I think AND is OK, but I want to be able to treat a term like `"a b c"` (in double-quotes) as a single string.  So doing `a b "c d"` is like saying `a AND b AND "c d"`.  Possible?

**Comment by c3ho** [comment]
Ah, ok, I understand now. It is impossible with the type of `query` we're using right now in `indexer.js`. We're using [Match](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/query-dsl-match-query.html) query currently, what I think you're looking for is [Simple Query String](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html) or [Query String](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) query.
