### ISSUE TITLE
Add autocomplete to search for Authors

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1260]
It would be great if our search page supported autocomplete on the author name.  As I'm typing, if there is a hit on part of the name, I'd love to see those results appear below the search bar, and be able to pick one.

**Comment by MSTEWARDSON** [comment]
@humphd:  I would like to try and implement this feature.

**Comment by manekenpix** [comment]
@MSTEWARDSON all yours!

**Comment by humphd** [comment]
First part of this has merged for front-end, and I've filed #1417 for the backend piece.  We'll morph this into connecting the two when that's done.

**Comment by humphd** [comment]
cc @rclee91
