### ISSUE TITLE
docker compose up --build doesn't seem to see .env

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1261]
```
$ docker compose up --build
...
telescope_1      |
telescope_1      | > @seneca/telescope@1.3.0 start /telescope
telescope_1      | > node src/backend
telescope_1      |
telescope_1      | [ 2020-11-01 20:00:18.247 ] ERROR (17 on af53c261a8b0):
telescope_1      |
telescope_1      | 	💡 It appears that you have not yet configured a .env file.
telescope_1      | 	   Please refer to our documentation regarding environment configuration:
telescope_1      | 	   https://github.com/Seneca-CDOT/telescope/blob/master/docs/CONTRIBUTING.md
telescope_1      |
telescope_1      | [ 2020-11-01 20:00:18.318 ] INFO  (17 on af53c261a8b0): Attempting to use default env in /telescope/env.example instead.
```

I'm not sure why it says this, since I have a `.env` file.

**Comment by c3ho** [comment]
I took a look at this issue. With the current master branch I ran `docker-compose up --build` created a shell for the Telescope container and did an `ls -a`, was unable to find the .env file

I tried moving the copy of the `.env` file to line 28 of the Dockerfile
![image](https://user-images.githubusercontent.com/18711727/97846796-8b370400-1cbc-11eb-80ab-667fb026d819.png)


And commented out the one in the `Front-end Builder context`

I pruned images + deleted volumes just to get a clean slate and reran `docker-compose up --build`
Didn't receive the error message

Ran the command `docker exec -it <container id> bash` and ran `ls -a`, was able to see the `.env` file.
![image](https://user-images.githubusercontent.com/18711727/97846638-4ad78600-1cbc-11eb-8aa7-de53f95a8dcb.png)

**Comment by humphd** [comment]
cc @raygervais

**Comment by raygervais** [comment]
@c3ho suggestion works as expected. It was present before Blue / Green and recent updates to Dockerfile
https://github.com/Seneca-CDOT/telescope/commit/67f4e83f08f80c3b468c98d63515d64a5ae300ce#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

Let's add it back.

**Comment by humphd** [comment]
Let's get one of our new community members to take this.

**Comment by raygervais** [comment]
Sounds good.

**Comment by isabellaliu77** [comment]
Hi, I'd like to work on this one, can you assign this one to me? Thanks! @humphd

**Comment by humphd** [comment]
@isabellaliu77 sure, thanks for offering.  All yours.
