### ISSUE TITLE
LOG_LEVEL works via shell but not .env

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1264]
I noticed today that I couldn't set my `LOG_LEVEL` via the `.env`, but could on the command line.

In both cases I used `LOG_LEVEL=debug` but got `INFO` vs. `DEBUG` when I did it via `.env`, whereas this worked on macOS:

```sh
$ LOG_LEVEL=debug npm start
```

**Comment by tianlangwu** [comment]
I would like to work on this. Could you please assign it to me :D

**Comment by humphd** [comment]
@tianlangwu all yours
