### ISSUE TITLE
Improve Logging docs to include LOG_LEVELs

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1265]
Our [docs for the logger](https://github.com/Seneca-CDOT/telescope/blob/master/docs/logging.md) aren't as clear as they could be on how to use `LOG_LEVEL`.

[Pino](https://getpino.io/#/) (our logger) supports these levels:

* trace
* debug
* info
* warn
* error
* fatal

**Comment by jiyoungsin** [comment]
I have created a PR regarding this issue [here](https://github.com/Seneca-CDOT/telescope/pull/1377). If anyone could take a look at my pull request it would be greatly appreciated.

**Comment by HyperTHD** [comment]
#1377 didn't properly close this issue, but did solve this issue, so closing this issue
