### ISSUE TITLE
Missing src attribute on img elements in posts when using data URIs

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1266]
I notice a post today that is missing images.  The `<img>` element is there, but it has no `src` attribute:

<img width="971" alt="Screen Shot 2020-11-01 at 6 15 15 PM" src="https://user-images.githubusercontent.com/427398/97818088-52703e00-1c6e-11eb-88e1-5c4666e583c8.png">

The original post does have them: https://palak-chawla.blogspot.com/2020/10/release-02-pr-4.html, but they are using Data URIs:

<img width="710" alt="Screen Shot 2020-11-01 at 6 17 40 PM" src="https://user-images.githubusercontent.com/427398/97818119-93685280-1c6e-11eb-98e5-c8f2ef198ac1.png">

**Comment by chrispinkney** [comment]
Interesting, I'll have to read up about data URIs, can't say I've heard of them until now.

Could I give this a shot?

**Comment by humphd** [comment]
A data URI is a way of embedding a resource *in* the URL itself.  You only use it for small items, for example, a favicon or an image.  The nice thing about them is that they don't require any server storage.  However, our sanitizer is filtering them out, since they don't use a secure origin.

**Comment by humphd** [comment]
Assigned to you, @chrispinkney
