### ISSUE TITLE
Creating test for summary (issue #20)

### ISSUE THREAD

**Issue by lozinska** [Seneca-CDOT/telescope#127]
Testing of summary analysis issue #20 and issue #7

**Comment by izhuravlev** [comment]
I can work on it

**Comment by ThomasLuu00** [comment]
I have already included testing for the summary feature PR #20. Once its merged you may add any other tests to the summarize.test.js file.

**Comment by lozinska** [comment]
This issue had been resolved with PR #66. Thank you @ThomasLuu00 for your great contribution to this project.
