### ISSUE TITLE
Make searches sharable via URL

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1270]
Today I needed to go and look for blog posts students have written on Pandas.  I did a search, and got back my results.  Now I want to share that search and the results with a colleague.  There is no way to do this without telling them how to recreate the search.

A better solution would be to use the React routing and History API to push some state into the URL, so you get something like `https://telescope.cdot.systems/search?q=pandas` or something.  As I type, it should update the URL so it stays in sync with my search, but not in an annoying way so that we break the Back button.

When the search page is rendered, we should read out params from the URL if present, too.

**Comment by jossiey** [comment]
I will give this a try.

**Comment by humphd** [comment]
All yours @jossiey

**Comment by jossiey** [comment]
@humphd Now, I have achieved the first step, when we are typing in search page, url will synchronize with key word, showing https://telescope.cdot.systems/search?q=keyword. I want to know that the next step you mentioned in the last sentence is that you hope to read out the params only or you want to send the url to another person,  he could open it as well.

**Comment by humphd** [comment]
@jossiey nice.  What I mean is, if I browse to the URL https://telescope.cdot.systems/search?q=keyword, I want the state of the search input box to be updated to `keyword`.  That is, I want the param to make its way into the UI, as if I typed it there and ran a search.

The end goal would be that browsing to https://telescope.cdot.systems/search?q=keyword would actually do a search for `keyword`.

**Comment by jossiey** [comment]
@humphd Thanks for the further explanation. I will keep trying to figure it out.
