### ISSUE TITLE
Long search results need the "Scroll to Top" component

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1271]
When you do a search for posts, and get back lots of results, scrolling down doesn't show the up-arrow scroll-to-top widget like you get in the main timeline view.  Let's add it.

**Comment by tianlangwu** [comment]
I would like to work on this. Could you please assign it to me :D

**Comment by humphd** [comment]
Be aware of work happening in https://github.com/Seneca-CDOT/telescope/pull/1274, which will affect this solution.  @PedroFonsecaDEV, is your new scroll-to-top stuff going to need any changes to support the search results?

**Comment by PedroFonsecaDEV** [comment]
I don't think the changes I made until now will impact this bug. But I will implement @manekenpix suggestion. Let's keep in touch.

@tianlangwu, please feel free to reach me on slack. 

Thanks.
Pedro.

**Comment by tianlangwu** [comment]
Thanks for your new scroll component! I won't start this soon, I will wait until your PR gets merged.

**Comment by humphd** [comment]
@tianlangwu or pull @PedroFonsecaDEV's branch from his remote into your repo, and start prototyping now.  You can rebase onto master later when it gets finished.

Then you can offer him some advice on any changes you need to make it work in your context.

**Comment by tianlangwu** [comment]
oh yes! I might try that way if I have time to start it soon. Thanks!
