### ISSUE TITLE
Add guide in UI to help users write queries when searching Posts

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#1276]
**What would you like to be added**:
Add some type of guide in UI to help users in writing more complex searches on this screen:

![image](https://user-images.githubusercontent.com/18711727/98015188-819bc200-1dca-11eb-8456-e1c1611b9108.png)

**Why would you like this to be added**:
#1275 will allow users to use operators + other options to fine-tune their searches:

![image](https://user-images.githubusercontent.com/18711727/97951377-fab5fd80-1d67-11eb-83bf-42cc07081660.png)

This type of syntax might not be obvious to most people, we should create some type of guide to help users in using the new syntax. Please refer to that PR for more information on writing search queries.

**Comment by MLJBrackett** [comment]
Hey @c3ho Id love take take this issue on! Could you assign me?

**Comment by c3ho** [comment]
The solution is open-ended, I'm not sure what the best solution is actually. You can add text above the search bar, a mouse-over or ask in Telescope for suggestions. I suggest you fetch my branch try out my PR with the new search feature and think of how you would like that information to be presented as a user.

**Comment by MLJBrackett** [comment]
Hey @c3ho take a look at my pull request #1306 and tell me what you think of it!
