### ISSUE TITLE
Add docs on how to debug the backend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1278]
We have a bunch of VSCode configs (e.g., [`Launch Telescope`](https://github.com/Seneca-CDOT/telescope/blob/master/.vscode/launch.json#L4-L11)) that allow devs to easily debug the backend from within VSCode.  However, if you haven't used them before, it might not be obvious.

Let's add some docs on how to do this.  See https://code.visualstudio.com/docs/editor/debugging#_launch-configurations for some info.

Let's cover how to start the server from VSCode, how to see the console for errors, how to set breakpoints, etc.

**Comment by mamadou-diallo** [comment]
I'll take care of this :) !

**Comment by manekenpix** [comment]
@mamadou-diallo thanks, all yours

**Comment by humphd** [comment]
This is in now, closing.
