### ISSUE TITLE
Better errors for failures with Search and Elasticsearch

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1279]
In our search code we have some issues with how errors are handled.  Both the backend and frontend are doing the wrong thing.

When Elasticsearch fails, it will end up right here https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/query.js#L28
src/backend/web/routes/query.js:28

```js
    res.send(`There was an error while executing your query: ${error}`);
```

This is wrong, since we're sending a 200 response with a string vs. an error code with an error message.

In the frontend, because we always send a 200 response, it assumes the error message is a result.  In this line we will get back that "error" message as a String https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/SearchPage/SearchPage.jsx#L94

```js
          const searchResults = await res.json();
```

And just assume that's the results from Elasticsearch.  It will fail on the next line, 96, and that will throw, then it will land on 103, console log, and quit.

We should be doing something better on the server and frontend when things go wrong.

**Comment by HyperTHD** [comment]
I can assume this is just as simple as ensuring an error status is sent here? Reading where the front-end code error occurs, that would seem to do the trick since the json gets parsed if the return status code is 200

**Comment by humphd** [comment]
I want the backend to send a proper error code here, and the frontend to receive it and deal with it via UI.  So it's a mulit-part fix.

**Comment by HyperTHD** [comment]
I'll give this a shot then, you or any other maintainer can assign this to me

**Comment by humphd** [comment]
@HyperTHD all yours.  Let us know if you need any help.
