### ISSUE TITLE
Add more fields to Elasticsearch

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1280]
When we store posts in Elasticsearch, we currently only include the posts' `text`:

https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/indexer.js#L12-L30

We can add more fields, and I think it would be good to include the `author` name.  This way we can convert our Author Search feature to also use Elastic vs. doing it manually.

Then we can modify our search to work against the text or the author name, as the user specifies, and limit the fields we return from Elastic.

**Comment by humphd** [comment]
From Slack:

> so this is where we index new posts, but we don't know the author, or at least we don't have direct access to it as we do to id and text https://github.com/Seneca-CDOT/telescope/blob/9f71e65bc2fafed2729feb29cabc5297f3299f13/src/backend/data/post.js#L149 -- @manekenpix

**Comment by humphd** [comment]
We could probably add title, date, etc. too.

**Comment by c3ho** [comment]
Will people need to remove their volumes if running ES through docker for this?

**Comment by humphd** [comment]
Yeah, when this gets added, we'll need to have people clean it out.

**Comment by StellaJung-Student** [comment]
Can I take this~?

**Comment by c3ho** [comment]
Before this gets worked on... can we get #1253 fixed + merged first?

**Comment by StellaJung-Student** [comment]
For me, it's hard and I really don't get how to communicate with redis... so I am not sure about my update.
When I tested it locally, the search keyword was worked on each author, text and title.
Also, when I removed the _source, the all fields are shown but again, please let me know better solution~ 
Thanks.
