### ISSUE TITLE
Remove console and proxy spam from tests

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1286]
Our tests have a ton of spam in them from stray `console.log()` and also the express proxy:

```
  ● Console

    console.info
      [HPM] Proxy created: /  -> http://localhost:4000

      at Logger.info (node_modules/http-proxy-middleware/dist/logger.js:47:27)

    console.info
      [HPM] Proxy rewrite rule created: "^/admin/build/status" ~> "/status"

      at Logger.info (node_modules/http-proxy-middleware/dist/logger.js:47:27)

    console.info
      [HPM] Proxy created: /  -> http://localhost:4000

      at Logger.info (node_modules/http-proxy-middleware/dist/logger.js:47:27)

    console.info
      [HPM] Proxy rewrite rule created: "^/admin/build/log" ~> "/log"

      at Logger.info (node_modules/http-proxy-middleware/dist/logger.js:47:27)
```

Let's remove all `console.log`s from our test files that aren't part of a test itself.

Also, let's fix our express proxy middleware to not run in testing.  I think we only need it for development?

**Comment by jiyoungsin** [comment]
Hello Professor, 

This seems like a quick fix that I could do. Could you tell me more about where these console logs are? I am having a difficult time locating a console.log in the test's directory.

**Comment by jiyoungsin** [comment]
In addition, I have a question about how I should go about this issue. I have located the root of the problem in node_modules/http-proxy-middleware/dist/logger.js, however, this will only fix this issue locally since we download everything using npm install. Do you have any idea's on how I should go abouts this?
```
class Logger {
    constructor() {
        this.setLevel('silent');  <-- changed from 'info' to 'silent'
        this.setProvider(() => defaultProvider);
    }
```

**Comment by humphd** [comment]
The `options` object you can pass to the middleware lets you set a `loglevel`: https://www.npmjs.com/package/http-proxy-middleware#options.  I'd disable it there.

**Comment by jiyoungsin** [comment]
I will take another look at this Tuesday!

**Comment by humphd** [comment]
This was fixed in https://github.com/Seneca-CDOT/telescope/pull/1958
