### ISSUE TITLE
Explore how we can use Nix / NixOS for non-unix based Developer Environments

### ISSUE THREAD

**Issue by raygervais** [Seneca-CDOT/telescope#1288]
From Slack
```
but I really am interested in it
7:13
for reproducible, declarative builds?  amazing
7:13
maybe we could add it?
```

**Comment by humphd** [comment]
Yeah, might be a fun experiment to try for adding redis/elastic/etc for devs on Linux/macOS at least.

**Comment by yzwdroid** [comment]
I can add a vagrant file to handle the redis/elastic env. Hopefully, it'll work on windows.

**Comment by humphd** [comment]
I wonder if Vagrant gains us much over using docker?

**Comment by yzwdroid** [comment]
Actually no different. I encounter some permission denied bugs with Docker compose redis and It's still not working on my fedora system. Maybe just another choice.  Too much choice is not good thing for beginners.

**Comment by humphd** [comment]
Yeah, I think we should just stick with docker.

**Comment by raygervais** [comment]
Let's close this @humphd so that others don't pick it up?
