### ISSUE TITLE
Test for analysis

### ISSUE THREAD

**Issue by lozinska** [Seneca-CDOT/telescope#129]
I just wonder if it will be possible to have one test for all type of analysis #19, #20, #84?

**Comment by Reza-Rajabi** [comment]
I think each function might better be tested as a unit.
Related functionality requires integrity tests as well.
These three that you mentioned looks to have separated scopes.

**Comment by Reza-Rajabi** [comment]
@lozinska Do you think we should have this issue still open for more ideas?

**Comment by lozinska** [comment]
@Reza-Rajabi Yes, i'm closing now
