### ISSUE TITLE
Create a Heroku based Development Setup and Docs

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1291]
Setting up Telescope is hard, especially on Windows.  We rely on a lot of different services, and stitching them all together can be a complex task.

I'd like to see if we can leverage some cloud hosting providers' free tiers to allow contributors to quickly spin up services in the cloud and make local development easier.

@raygervais suggests Heroku, and I think he's on to something.  The ["Free and Hobby Tier" of Heroku is very generous](https://www.heroku.com/pricing) and supports some or all of what we need (Elasticsearch might need some tweaks to run properly).

It should be possible to run things like Redis, databases, indexing, node app, etc. on Heroku.

The login part might not work this way, but let's see how far we can get.

**Comment by yzwdroid** [comment]
I already checked Heroku, to add a Redis plugin, we need to add a credit card. but this is a free tier of Redis. Is it ok to add the credit info to the website. Or we can try something else.

**Comment by humphd** [comment]
I think a credit card is a no-go.  Most students won't do this.  Let's look for another solution, or close this.

**Comment by humphd** [comment]
See also #1298
