### ISSUE TITLE
Fix code within blog posts

### ISSUE THREAD

**Issue by smilegodly** [Seneca-CDOT/telescope#1296]
**What would you like to be added**:

Alot of code in Telescope posts have no code blocks and are just in plain text

![image](https://user-images.githubusercontent.com/35276477/98364888-8eedc200-1fff-11eb-97c5-95d9177016d8.png)

![image](https://user-images.githubusercontent.com/35276477/98364948-ad53bd80-1fff-11eb-9798-875a21615d62.png)

**Why would you like this to be added**:

Code should be indented nicely in the posts, with syntax highlighting

**Comment by smilegodly** [comment]
This issue is similiar to https://github.com/Seneca-CDOT/telescope/issues/1250 except all the code in this issue are in  empty `<div>` tags

**Comment by humphd** [comment]
This seems risky.  How do you identify code in a post if it isn't marked up?  I also see some people use tables, rows, and table cells for code.

I think it's going to be hard to get this right.

**Comment by humphd** [comment]
Here's a post that we could maybe fix: https://egrinberg.medium.com/lab-6-dps909-11767c605e33

It uses a `<pre>` per line, so the file is `<pre>...</pre><pre>...</pre><pre>...</pre>...`.  We could probably collapse these together into a single `<pre>`.

**Comment by smilegodly** [comment]
There are going to be lots of problematic edge cases like this for this issue. In the future more are likely to pop up.

A photo of the above mentioned case

![image](https://user-images.githubusercontent.com/35276477/98743067-77a33180-237d-11eb-9284-25b9d433bc35.png)

**Comment by humphd** [comment]
It might be interesting to survey the top blog platforms, and see what the HTML they produce is like for "code" blocks.  Then we could write a parser that deals with these cases, and ignore the others (which will be rare or mistakes on the part of a user).

**Comment by smilegodly** [comment]
> Here's a post that we could maybe fix: https://egrinberg.medium.com/lab-6-dps909-11767c605e33
> 
> It uses a `<pre>` per line, so the file is `<pre>...</pre><pre>...</pre><pre>...</pre>...`. We could probably collapse these together into a single `<pre>`.

I'm picking this issue back up again.

**Comment by humphd** [comment]
I believe this is fixed.  I haven't seen any issues since we landed the changes to the parser in the fall.  Closing.
