### ISSUE TITLE
Auto hide Nav bar when scrolling down

### ISSUE THREAD

**Issue by VietnameZe** [Seneca-CDOT/telescope#1297]
Change a bit about UI, navbar will be hidden when user scroll the page down, then it will be back when user scroll up

The navigation should be hidden to make more space and comfortable to read (only post's header remain appeared). Both navbar and post header together it looks bad to me, let me know what you think about this?

**Comment by humphd** [comment]
We've got some work happening on this front already in #1274.  I'm going to close this to let that work complete.
