### ISSUE TITLE
Check for multiples of the same blog

### ISSUE THREAD

**Issue by lozinska** [Seneca-CDOT/telescope#130]
As mention in issue #21 by @jordanhui19 we probably also check for multiples of the same blog that have been added

**Comment by Reza-Rajabi** [comment]
@lozinska Would you please put more words on the title of the issue to make it more clear?

**Comment by Reza-Rajabi** [comment]
@lozinska I am wondering if I could change the title to "Check for ..." to make it clear for myself.

**Comment by humphd** [comment]
@Reza-Rajabi, with things like this, just go ahead and edit things.  This is "our" code, these are "our" issues, etc., and anything we can do **together** to improve things is welcome.

**Comment by evlnyng** [comment]
Is there anyone working on this right now? If not, I'd like to give it a shot.

**Comment by humphd** [comment]
@evlnyng I'm worried that this bug isn't well scoped, and it's going to be hard to finish it without more pieces in place.

Can I suggest another one for you to consider?  In #35 @hansal7014 is adding logging support.  Once that goes in, I want to add proper logging to our feed queue.  It would mean modifying the code in `src/feed-queue.js` to do essentially what they do in [this code](https://github.com/OriginProtocol/origin/blob/e9881d687241fdbf557239a90eeac12d96792d62/infra/cron/src/scheduler.js#L22-L73) to log all the events of a queue using the new logger we'll have.  If you're interested in this, you can file an issue on that and take it.

**Comment by evlnyng** [comment]
@humphd I will take that advice. Thank you!

**Comment by humphd** [comment]
This will be fixed when we do #522, let's deal with it there.  Closing.
