### ISSUE TITLE
Add github action to automate the release process.

### ISSUE THREAD

**Issue by yzwdroid** [Seneca-CDOT/telescope#1301]
**What would you like to be added**:
I'd like to add a GitHub action to automate the release process. When there is a release tag like `1.5.0` push to the master branch, a release will be created with the release code and description.

**Why would you like this to be added**:
automate the release process.

**Comment by humphd** [comment]
Oh, nice idea!  cc @raygervais.

**Comment by humphd** [comment]
NOTE: our release process is documented here https://github.com/Seneca-CDOT/telescope/blob/master/docs/release.md

**Comment by yzwdroid** [comment]
Thanks, @humphd. Please assign this to me.

**Comment by humphd** [comment]
@yzwdroid done!  I think you all have the ability to assign issues to yourself, though.  I added you all as collaborators on the repo.

Looking forward to seeing this happen!

**Comment by humphd** [comment]
@yzwdroid you still working on this?

**Comment by yzwdroid** [comment]
yeah, I plan to do this as a part of release 0.4. Sorry for the delay.
