### ISSUE TITLE
"Malformed input, repository not added" error message while installing Docker on Linux Mint

### ISSUE THREAD

**Issue by yuanLeeMidori** [Seneca-CDOT/telescope#1302]
**What happened**: I received the message `Malformed input, repository not added` while using the command below. This command is from the instructions of Docker installation in `environment-setup.md`.
```
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
```

**What should have happened**: There should not be any message returned after input this command.

**Environment**: 

- OS: Linux Mint 19.2 Tina
- Browser: Chrome

**Comment by manekenpix** [comment]
Closed via #1303
