### ISSUE TITLE
Add query params validation for PUT /feeds/:id/flag route using Express Validator and unit tests

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1307]
**What would you like to be added**: 
Request to add query params validation for PUT /feeds/:id/flag route using [Express-validator](https://express-validator.github.io/docs/) and also unit tests to ensure that it works

**Why would you like this to be added**:
It would be better to validate the query before it reach the route handler. 

reference: https://express-validator.github.io/docs/check-api.html

All logic for the middleware should be place inside `backend/web/validation.js`

**Comment by Jasper-Mui** [comment]
I would like to work on this.

**Comment by manekenpix** [comment]
@Jasper-Mui all yours!

**Comment by Jasper-Mui** [comment]
I found the post validator in the web/validation.js.  (https://github.com/Seneca-CDOT/telescope/blob/1e92adca98fe4581724c89c1679fce4404a85867/src/backend/web/validation.js#L78)

Would it not be better if we just use the same validation for the put instead of adding another express validator check?

**Comment by humphd** [comment]
@Jasper-Mui yes, you can use that, and write tests for your route to make sure it does what we expect for both good and bad data.

**Comment by humphd** [comment]
@Jasper-Mui can we close this now?

**Comment by Jasper-Mui** [comment]
Yes
