### ISSUE TITLE
Add query params validation for DELETE /feeds/:id route using Express Validator and unit tests

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1308]
**What would you like to be added**: 
Request to add query params validation for DELETE /feeds/:id route using [Express-validator](https://express-validator.github.io/docs/) and also unit tests to ensure that it works

**Why would you like this to be added**:
It would be better to validate the query before it reach the route handler. 

reference: https://express-validator.github.io/docs/check-api.html

All logic for the middleware should be place inside `backend/web/validation.js`

**Comment by fluentinstroll** [comment]
Hey Tony! I'd like to take a look at this if @eunbeek hasn't started already.

**Comment by humphd** [comment]
I think @eunbeek is working on #1311, so go ahead @fluentinstroll.
