### ISSUE TITLE
Add query params validation for DELETE /feeds/:id/flag route using Express Validator and unit tests

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1309]
**What would you like to be added**: 
Request to add query params validation for DELETE /feeds/:id/flag route using [Express-validator](https://express-validator.github.io/docs/) and also unit tests to ensure that it works

**Why would you like this to be added**:
It would be better to validate the query before it reach the route handler. 

reference: https://express-validator.github.io/docs/check-api.html

All logic for the middleware should be place inside `backend/web/validation.js`

**Comment by HenryZerocool** [comment]
Hi, can you assign this to me please?

**Comment by humphd** [comment]
@HenryZerocool you can assign yourself, go for it.
