### ISSUE TITLE
Add query params validation for GET /feeds/:id route using Express Validator and unit tests

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1310]
**What would you like to be added**: 
Request to add query params validation for GET /feeds/:id route using [Express-validator](https://express-validator.github.io/docs/) and also unit tests to ensure that it works

**Why would you like this to be added**:
It would be better to validate the query before it reach the route handler. 

reference: https://express-validator.github.io/docs/check-api.html

All logic for the middleware should be place inside `backend/web/validation.js`

**Comment by sonechca** [comment]
Hi Tony,

I am interested in this issue and I would like to work on this.
Can I take on this issue? 
Thank you :)

**Comment by tonyvugithub** [comment]
@sonechca : you can assign yourself to the issue. Go ahead!

**Comment by tonyvugithub** [comment]
@sonechca : Some reference for you https://express-validator.github.io/docs/check-api.html

**Comment by tonyvugithub** [comment]
@sonechca : the logic for the middleware should be placed inside `backend/web/validation.js`

**Comment by sonechca** [comment]
HI, I have finished this issue based on your advice and checking with https://github.com/Seneca-CDOT/telescope/commit/b9a87872b1775f8e8fc0cb3bee468023b0aa656a and https://github.com/Seneca-CDOT/telescope/issues/1311. 

I need your advice more can you check my [PR](https://github.com/Seneca-CDOT/telescope/pull/1363)

**Comment by humphd** [comment]
@sonechca can we close this?

**Comment by aserputov** [comment]
@humphd I think this one can be closed.

**Comment by humphd** [comment]
We moved it to posts https://github.com/Seneca-CDOT/telescope/blob/master/src/api/posts/src/validation.js. Unless we rip it out with #1907.

**Comment by humphd** [comment]
We don't expose feeds this way anymore, it's in Supabase, closing.
