### ISSUE TITLE
Add query params validation for GET /posts/:id route using Express Validator and unit tests

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1311]
**What would you like to be added**: 
Request to add query params validation for GET /posts/:id route using [Express-validator](https://express-validator.github.io/docs/) and also unit tests to ensure that it works

**Why would you like this to be added**:
It would be better to validate the query before it reach the route handler. 

reference: https://express-validator.github.io/docs/check-api.html

All logic for the middleware should be place inside `backend/web/validation.js`

**Comment by eunbeek** [comment]
Hi, 

May I work on this issue? 
I will post some code examples soon, maybe tomorrow morning, if you are okay.

Thanks

**Comment by tonyvugithub** [comment]
@eunbeek you can assign yourself to the issue

**Comment by eunbeek** [comment]
This is my suggestion about id parameter validation style. 

I looked at the function to encode "guid" to "id" with Hash algorithms and then make it slice 10 characters.
I gave up decoding "id" to "guid" and made the validation to check input param's length with express-validation package like below.  

![example](https://user-images.githubusercontent.com/50673489/98784771-9af3ce00-23c9-11eb-930c-7385ba2cdc9f.png)

express-validation has lots of function and style so I think that people, who will apply this validation to the repo, need to discuss to select one style.  

If you have any questions or requests, feel free to ask it!
Thanks.

**Comment by tonyvugithub** [comment]
The idea is to put any validation in a form of a middleware.  then put the middleware before the route handler. We tried to modulize our code, but your approach is a good start. You can take a look here https://express-validator.github.io/docs/check-api.html

**Comment by tonyvugithub** [comment]
@eunbeek : There is a file called `validation.js` under `/backend/web`, you should create a middleware in there then export it to use in your route like this example
```
feeds.post('/', protect(), **validateNewFeed()**, async (req, res) => {
    ...
}
```

**Comment by eunbeek** [comment]
Oh, I did not have this code now, I will pull and use your code soon :) Thanks!

**Comment by tonyvugithub** [comment]
@eunbeek  You can ignore the part for Ajv, which is another validator we used before but for JSON, start your middleware function right below

**Comment by eunbeek** [comment]
Hey, @tonyvugithub 
Thank you so much for your feedback.

And Hello, a developer who is coding to similar issues about express-validation feel free to ask about it.

I changed this code like below.
When the invalid id value gets in middleware, it returns a "400" error back. 

I am waiting for others to update any example on a similar issue.  
I will make it look good and pull request it on Friday morning if it is okay. 

validation.js
```
// Expect input fields not empty
const validateLength = function (schema, data) {
  return data.length === 10;
};

ajv.addKeyword('isLength', {
  validate: validateLength,
  errors: false,
});  

const postParamSchema = {
  type: 'object',
  properties: {
    id: { type: 'string', isLength: true }
  },
};

function validateParam(){
  return function(req, res, next){
    const postId = req.params;
    const valid = ajv.validate(postParamSchema, postId);

    if (!valid) {
      res.status(400).send();
    } else {
      next();
    }
  }
```

posts.js
```
const { validateParam } = require('../validation');
posts.get('/:id', validateParam(), async (req, res) => {})
```

If you have any questions or feedback, Welcome!

**Comment by tonyvugithub** [comment]
@eunbeek : I think you misunderstood it. The current code in validation.js is following the standard of Ajv which is not express-validator. Even the current code will soon be migrate to express validator. 
You should take a look at this link https://express-validator.github.io/docs/check-api.html

**Comment by tonyvugithub** [comment]
you should use their current api `query([fields, message])`

**Comment by eunbeek** [comment]
@tonyvugithub : Could you let me know how to test with Supertest?
I completed the code like below but unfortunately...I do not know how to use supertest....

posts.js
`posts.get('/:id', validateParam, async (req, res) => {}`

validation.js.
```
const validateParam = (req, res, next) => {
  param('id').isLength({ min: 10, max: 10 })(req, res, (err) => {
    console.log(err);
    try {
      validationResult(req).throw();
      next();
    } catch (e) {
      console.log(e);
      res.status(400).json({ message: 'ID Length is invalid' });
    }
  });
};
```

**Comment by tonyvugithub** [comment]
here is a reference to the do the test
https://github.com/Seneca-CDOT/telescope/blob/master/test/posts.test.js
Your test flow will most likely like this: You make a request to the app 
```
 test('should return 200 if it is valid', async () => {
    const id = <A valid id>;
    const res = await request(app).get(`/posts/${id}`);

   \\ Do test expecting here.
    expect(res.status).toEqual(200);
  });
```

**Comment by tonyvugithub** [comment]
@eunbeek : And you need a couple of these. Think about scenarios. Like what if the id is has the right length but it is invalid. What if its length is not correct.

**Comment by eunbeek** [comment]
I have a problem with git rebase...Error log returned like below.
![image](https://user-images.githubusercontent.com/50673489/99157195-eb528080-2694-11eb-9f8c-8525ba9edce5.png)

Do you have any idea to solve it?
