### ISSUE TITLE
Add query params validation for GET /posts?page=<num>&per_page=<num> route using Express Validator and unit tests

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1313]
**What would you like to be added**: 
Request to add query validation for GET /posts?page=<num>&per_page=<num> route using [Express-validator](https://express-validator.github.io/docs/) and also unit tests to ensure that it works

**Why would you like this to be added**:
It would be better to validate the query before it reach the route handler. 

reference: https://express-validator.github.io/docs/check-api.html

All logic for the middleware should be place inside `backend/web/validation.js`

**Comment by zg3d** [comment]
Ill do this.

**Comment by tonyvugithub** [comment]
@zg3d : All logic for the middleware should be place inside `backend/web/validation.js`
