### ISSUE TITLE
Add a README badge icon for our GitHub Actions build status

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1319]
Our README.md file includes a bunch of dynamic badges (icon images) that reflect build status.  Let's add one for the GitHub Actions CI we use.  See https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge.

**Comment by matt-ross16** [comment]
I can get a badge up and running for the README

**Comment by humphd** [comment]
OK @matt-ross16 all yours.
