### ISSUE TITLE
Add test for post.js to call the constructor for a Post() 

### ISSUE THREAD

**Issue by joey2031** [Seneca-CDOT/telescope#1323]
**What would you like to be added**: In post.test.js add a test for src/backend/data/post.js that tries to call the constructor for a Post() and pass it invalid dates, and make sure we are throwing.

**Why would you like this to be added**: We have tests for many functions throughout Telescope, however, we are still missing many such as this one

**Comment by c3ho** [comment]
Feel free to create a PR and mention the backend test issue.

**Comment by joey2031** [comment]
@c3ho Will do, ill start working on it and if I run into any issues ill bring it up in Slack, Thanks!

**Comment by joey2031** [comment]
@c3ho So I made quite a bit of progress for this issue I just don't know why the test keeps failing when I pass (invalidDate, validDate) I know it shouldn't throw since the fallbackDate is valid.  I tested the ensureDate function in a separate project and made some adjustments to it. In the other project, I called it in a try-catch and it didn't throw so I'm not sure what's wrong when I put it in Telescope. Thanks!


Fails at line 115
![image](https://user-images.githubusercontent.com/36198917/99121961-63547400-25cb-11eb-9a44-278488cac511.png)

```javascript
 test('Post constructor should throw if invalid dates is passed', () => {
    const createPostWithDates = (datePublished, dateUpdated) =>
      new Post(data.title, data.html, datePublished, dateUpdated, data.url, data.guid, feed);
    expect(() =>
      createPostWithDates(
        new Date('Thu, 20 Nov 2014 18:59:18 UTC'),
        new Date('Fri, 28 Nov 2014 18:59:18 UTC')
      )
    ).not.toThrow();
    expect(() =>
      createPostWithDates(
        new Date('Thu, 45 Nov 2014 18:59:18 UTC'),
        new Date('Thu, 35 Dec 2014 18:59:18 UTC')
      )
    ).toThrow();
    expect(() =>
      createPostWithDates( // this test fails.
        new Date('Thu, 40 Nov 2014 18:59:18 UTC'),
        new Date('Thu, 20 Nov 2014 18:59:18 UTC')
      )
    ).not.toThrow();
    expect(() =>
      createPostWithDates(
        new Date('Sat, 1 Nov 2014 18:59:18 UTC'),
        new Date('Thu, 35 Dec 2014 18:59:18 UTC')
      )
    ).not.toThrow();
  });
```

Modified ensureDate function
```javascript
function ensureDate(date, fallbackDate) {
  if (
    date &&
    ((Object.prototype.toString.call(date) === '[object String]' &&
      !Number.isNaN(Date.parse(date))) ||
      (Object.prototype.toString.call(date) === '[object Date]' && !Number.isNaN(Date.parse(date))))
  ) {
    return new Date(date);
  }
  if (
    Object.prototype.toString.call(fallbackDate) === '[object Date]' &&
    !Number.isNaN(Date.parse(fallbackDate))
  ) {
    return new Date(fallbackDate);
  }
  throw new Error(`post has an invalid date: ${date}'`);
}
```

What happens when I ran it in another project with try catch (dosent throw)
![image](https://user-images.githubusercontent.com/36198917/99122071-a1ea2e80-25cb-11eb-89dd-d016dd2e1d0b.png)

**Comment by c3ho** [comment]
Can you push this as a PR so I can fetch and test it out?

**Comment by joey2031** [comment]
> Can you push this as a PR so I can fetch and test it out?

Just did! Thanks! https://github.com/Seneca-CDOT/telescope/pull/1350

**Comment by c3ho** [comment]
Thanks, I'll take a look when I get back home

**Comment by joey2031** [comment]
@c3ho Thank you so much!
