### ISSUE TITLE
Load More Posts button overlaps with border of last pos

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#1325]
**What happened**:
![image](https://user-images.githubusercontent.com/18711727/98849850-dc17cc80-2421-11eb-9863-b576503b1fee.png)

Discovered while reviewing #1184 . Can confirm it happens in all mobile views

**What should have happened**:
Load More Posts button should look more elegant or at least not have the button overlap with the border of the post
**How to reproduce it (as precise as possible)**:

1. Open up dev console with f12 and switch to mobile view
2. Scroll to the very bottom

**Anything else we need to know?**:
With infinite scrolling being implemented, I have no idea if this fix will be necessary.

**Environment**:

- OS: Chrome
- Browser: Windows 10 Professional

**Comment by jiyoungsin** [comment]
Hey would it be cool if I could prepose a fix for this issue?

**Comment by humphd** [comment]
Go for it @jiyoungsin

**Comment by jiyoungsin** [comment]
This issue seems to have been resolved with the new this pull [request](https://github.com/jiyoungsin/telescope/commit/f131e8c2b4f64072cae53e020b9707a9ce73c34f). I will close this issue since it has been resolved. Thank you all for your time :)
