### ISSUE TITLE
Migrate JSON body validation of POST /feeds  from Ajv to express-validator

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1326]
**What would you like to be added**:
Initially the JSON object received by POST /feeds is validated through a package named Ajv. But the team decided to switch everything to validate with express-validator.
**Why would you like this to be added**:
Convert the current code inside `backend/web/validation.js` to use [express-validator](https://express-validator.github.io/docs/) 

Reference: https://express-validator.github.io/docs/check-api.html

All logic for the middleware should be place inside `backend/web/validation.js`

**Comment by sanji11** [comment]
Hi, I am gonna work on it, so assigning to myself hehehe

**Comment by tonyvugithub** [comment]
@sanji11 Sure. Remember to follow the link I included and all logic should be inside validation.js, you don't have to write tests for this route as they have already been done

**Comment by sanji11** [comment]
Hi, I just send a PR. Lemme know if everything looks good :)
