### ISSUE TITLE
Increase Post Title padding.

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1329]
**What would you like to be added**:
<img width="1723" alt="97935177-c5001d00-1d45-11eb-82af-f94bc9d8458f" src="https://user-images.githubusercontent.com/60857409/98861775-d5925080-2433-11eb-84ee-cafdb2c1560b.png">

Fix the padding on Posts' title. 

Our post title will have different padding after [PR-1274](https://github.com/Seneca-CDOT/telescope/pull/1274) were merged.

The left side of the photo shows how is our current padding(after PR-1274), and the right side shows what is the padding that we want to see.

**Why would you like this to be added**:
Requested by @humphd.

**Comment by jiyoungsin** [comment]
Has this issue been addresses? on my machine I see the ladder.

**Comment by c3ho** [comment]
I think this issue will happen once the mentioned PR gets merged. @manekenpix

**Comment by IcemanEtika** [comment]
Hey I'd be interested in working on this once the mentioned PR is merged.

**Comment by humphd** [comment]
It's in, go for it @IcemanEtika.
