### ISSUE TITLE
GitHub Actions is triple-reporting lint issues

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1336]
We do GitHub Actions builds on multiple platforms, and each one reports the same errors inline in our PRs.  This is annoying, and it would be better to only have lint issues reported once:

<img width="1199" alt="Screen Shot 2020-11-12 at 11 49 40 AM" src="https://user-images.githubusercontent.com/427398/98969951-62451900-24dd-11eb-9668-e8090197c5a0.png">

**Comment by yzwdroid** [comment]
Is this because we run on three different platforms?  `runs-on: ${{matrix.os}}`

**Comment by humphd** [comment]
Correct, and we want to have that build matrix.  But, we don't need triple reporting.

**Comment by yzwdroid** [comment]
I believe this report is from `"test-ci": "run-s prettier-check test",`,   how about we only run `- run: npm run test-ci`  if the `matrix.os == ubuntu`.

**Comment by humphd** [comment]
Yes, that's a possible work around if GitHub Actions has no way to harmonize these results.

**Comment by humphd** [comment]
We still have double-reporting via lint and build actions:

<img width="1215" alt="Screen Shot 2020-12-13 at 10 58 43 AM" src="https://user-images.githubusercontent.com/427398/102017022-3dd59a00-3d32-11eb-8365-a436ea514a02.png">

**Comment by humphd** [comment]
I haven't seen this in a while.
