### ISSUE TITLE
Missing argument in deploy.sh script

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#1340]
**What happened**:
The autodeployment server uses a bash script ([deploy.sh](https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/deploy.sh)) to clone and rebuild telescope, and once it's built, it shuts down the running version and deploys the new one.

In the step where the script shuts down telescope, `docker-compose` is missing an argument that specifies a yml file (`docker-compose-production.yaml`) for the staging and production servers. Without this argument, `docker-compose` tries to use the yaml file used in local deployment (`docker-compose.yml`), mixing settings for the 2 different deployments, and sometimes breaking the deployment process.

To fix this, add `-f $DOCKER_FILE` as specified in the diff.

```diff
diff --git a/tools/autodeployment/deploy.sh b/tools/autodeployment/deploy.sh
index cea4ae6..a350e64 100755
--- a/tools/autodeployment/deploy.sh
+++ b/tools/autodeployment/deploy.sh
@@ -47,7 +47,7 @@ docker-compose -f $DOCKER_FILE --project-name=$ENV build telescope
 
 # Delete associated project orphans (services) and volumes
 echo "Stopping "$OLD" Environment"
-docker-compose --project-name=$OLD down --remove-orphans
+docker-compose -f $DOCKER_FILE --project-name=$OLD down --remove-orphans
```

**Comment by hlstasiak** [comment]
Hello, I would like to work on this if that is okay with you.

**Comment by humphd** [comment]
Sounds good @hlstasiak
