### ISSUE TITLE
Search loading spinner is left-aligned vs. centred

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1341]
If you go to the search page on staging (i.e., https://dev.telescope.cdot.systems/search/) , type some text (e.g., React) and click the search button (i.e., magnifying glass), the search spinner loads for a brief moment but it is left-aligned instead of in the middle where it should be.

I can't get a screenshot of it, the search is so fast now.

**Comment by manekenpix** [comment]
I can't reproduce, whenever I am able to see the spinner (it's so fast I only see sometimes), the spinner is centered (on dev)

**Comment by humphd** [comment]
I'm seeing this on Firefox with a window width of 1245px.  I wonder it's super specific to the browser/sizing?

**Comment by agarcia-caicedo** [comment]
I've managed to reproduce a few times, but I haven't been able to figure out what triggers it. The more I searched the less it popped up

**Comment by humphd** [comment]
@VietnameZe can you file that second issue with screenshot for me?

**Comment by VietnameZe** [comment]
@humphd I just checked and this issue only on "dev telescope.." site, while on the other old one (without dev.) is running okay. should I still file it?

**Comment by VietnameZe** [comment]
> If you go to the search page on staging (i.e., https://dev.telescope.cdot.systems/search/) , type some text (e.g., React) and click the search button (i.e., magnifying glass), the search spinner loads for a brief moment but it is left-aligned instead of in the middle where it should be.
> 
> I can't get a screenshot of it, the search is so fast now.

I screen-recorded it, you can see it below. This issue is hard to reproduce probly because of the browser caching. I just tried to navigate to other web tab for a while and then go back, it is easier to reproduce than staying in same tab and try different search terms. 
![](https://i.imgur.com/xqAPgho.gif)

**Comment by humphd** [comment]
Nice!  I think I've fixed this in https://github.com/jossiey/telescope/pull/1, which is pending review for #1270.

**Comment by humphd** [comment]
Confirmed this is fixed.
