### ISSUE TITLE
Add Bottom margin to search component

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#1344]
**What would you like to be added**:
Currently, when results are displayed in the search page, there isn't much space separating the search component and the results
![image](https://user-images.githubusercontent.com/49992710/99040032-67927a00-2556-11eb-84a7-d1ba0b5c53e3.png)

**Why would you like this to be added**:
Margin will improve the design of the page

**Comment by humphd** [comment]
Assigning to @strawberries73.  From @agarcia-caicedo on Slack:

> This pr might be helpful, since it dealt with a similar issue: https://github.com/Seneca-CDOT/telescope/pull/1213
