### ISSUE TITLE
Fix environment var for Kibana in docker-compose.yml

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#1347]
**What happened**:
Issue connecting to Kibana at `localhost:5601`

**What should have happened**:
Users should see the Kibana screen when navigating to `localhost:5601

**How to reproduce it (as precise as possible)**:
`docker-compose up elasticsearch kibana`
`http://localhost:5601`

**Anything else we need to know?**:
Quick fix for the `docker-compose.yml` file
Change `SERVER_HOST` under `kibana:` to `KIBANA_HOST`

**Environment**:

- OS: WIndows 10 Pro
- Browser: Chrome

**Comment by Niaz-Ul-Haque** [comment]
Ill like to assign myself to this issue. Thank you!

**Comment by humphd** [comment]
I'm not sure we need Kibana.  I'll close for now and we can re-open if we end up wanting it.
