### ISSUE TITLE
Add infinite scrolling to search results

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1349]
Once we have #1222 finished we'll be able to page through search results.  When that happens, I want to see something similar to the work in #1332 happen in our timeline of search results.  Ideally we should be able to leverage the same component.

cc @klee214, who worked on the original infinite scrolling and can probably help mentor/review this work.

**Comment by joelazwar** [comment]
@humphd id like to work on this issue!

**Comment by humphd** [comment]
Awesome, thank you @joelazwar.  This will depend on #1222, so we need someone for that too.

**Comment by joelazwar** [comment]
@humphd Hmmm in that case I can work on that issue first. Hope it's fine if I assign that issue for myself

**Comment by humphd** [comment]
@joelazwar sounds good
