### ISSUE TITLE
Display Contributor in Footer of About Page

### ISSUE THREAD

**Issue by TDDR** [Seneca-CDOT/telescope#1355]
This issue is part of #1232 . As discussed in that issue we would like to add an area to the About page's footer that would highlight Telescopes contributors. 

You will use the `useTelescopeContributor` hook  to fetch a contirbutor that will be displayed in a manner similar to how it is shown on the [node site](https://nodejs.org/en/)

![nodeDisplay](https://user-images.githubusercontent.com/427398/96805906-b5e1ac80-13e0-11eb-885a-7dca81fa13ed.png)

**Comment by Wei-J-Huang** [comment]
I would like to try this.

**Comment by humphd** [comment]
OK, @Wei-J-Huang.  What needs to happen here is a new React component should get created (`GitHubContributorCard` or something) and it should use the hook function that @TDDR built for #1232.  @TDDR can give you some tips on using it if you need help.  Then, you will add your new component to our About page.
