### ISSUE TITLE
Avoid Redis database corruption on power failure

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1365]
When we lose power on dev or prod, we sometimes see corruption in the Redis database.  This isn't ideal, and it shouldn't be happening.

Let's figure out what we're doing wrong to cause this.  Others have reported similar situations, see:

- https://github.com/redis/redis/issues/5177
- https://groups.google.com/g/redis-db/c/Jqyk_9sHqYU?pli=1
- https://www.inovex.de/blog/redis-backup/

**Comment by NathanPang001** [comment]
Hello, just wanted to ask if I could work on this and if there was a good way to test this without having a power failure.

**Comment by humphd** [comment]
There's no easy way to test this, but yes, you can work on it.

**Comment by jiyoungsin** [comment]
I am having difficulties running the "docker-compose up --build redis elasticsearch login" command. It gives me this error log ( screenshot posted below ). However, If i delete the redis-data directory I am able to launch this repository.

![Screen Shot 2020-11-30 at 6 38 14 PM](https://user-images.githubusercontent.com/44411777/100678685-b8b6b200-333b-11eb-9a64-70a76fd2f9d9.png)

**Comment by HyperTHD** [comment]
Gonna explore possibly having an rdb file being used alongside the aof file we currently used. The rdb file would be the primary manager of the data, and the aof can be used in the case of a power failure to re-create the cached data. For future reference in case I don't end up doing this, this is one way to go about it

**Comment by humphd** [comment]
I think we need to have our `docker-compose` always validate/fix our aof file, see https://stackoverflow.com/questions/53222660/redis-server-refused-to-connect-while-using-docker-image.

**Comment by JerryHue** [comment]
I will give it a shot with @humphd recommendation. I will try to test it, as well!
