### ISSUE TITLE
Don't scale images up beyond their natural size

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1370]
We're applying a 100% width (and 100% max-width) to all images in blog posts.  It is being done to stop images from being too wide and causing overflow.  However, the opposite is now happening, and we're scaling small images too large:

![image-width](https://user-images.githubusercontent.com/427398/99211359-1e306d80-2796-11eb-8241-4e70d82dedc9.gif)

We shouldn't do this, since images go pixelated, and instead should probably centre the image in the available space.

**Comment by strawberries73** [comment]
@humphd  I would like to work on this issue.

**Comment by humphd** [comment]
@strawberries73 it looks like @phast184 already had a PR up for this.  @phast184 please communicate better in the future, and get the issue assigned to you, so that we don't have this kind of confusion.

**Comment by phast184** [comment]
@humphd thank you for your concern, sir. I would take notes the next time I want to make a PR. Better communication, better work   👍
