### ISSUE TITLE
Showing BLANK with search terms return NO result

### ISSUE THREAD

**Issue by foxviet** [Seneca-CDOT/telescope#1376]
In search page https://telescope.cdot.systems/search/ 
When user type something doesn't match any result (ex: ```reactjs html java```), the result page should show something to user. 

example on FB:
![](https://i.imgur.com/7tW1nvO.jpg)

**Comment by humphd** [comment]
This is a great idea, and we could use it for both the Posts Timeline and Search Results.

Be aware of #1328 and #1270 that are doing things related to this.  Co-ordinating everything will be key.

**Comment by VietnameZe** [comment]
> Hello, could I work on this?

Yes, go ahead!
