### ISSUE TITLE
Eslint peer dependencies 

### ISSUE THREAD

**Issue by ceterisp** [Seneca-CDOT/telescope#1393]
**What would you like to be added**:
I got npm warnings earlier when installing eslint. Apparently there are peer dependencies that are required to install. Do we need to add eslint-config-react and eslint-plugin-react as peer dependencies for eslint?

**Why would you like this to be added**:
To remove this warning when installing packages
![image](https://user-images.githubusercontent.com/36981880/99485228-0ab90a00-2930-11eb-98ce-a901842e8b6d.png)

**Comment by humphd** [comment]
This has been solved with later versions of eslint and pnpm, closing.
