### ISSUE TITLE
Add more links in the about footer

### ISSUE THREAD

**Issue by NathanPang001** [Seneca-CDOT/telescope#1394]
**What would you like to be added**:
I would like to add more links in the footer of the about page.

**Why would you like this to be added**:
It looks a little bare right now, there's not much there and more links would make the page look better.
![image](https://user-images.githubusercontent.com/54946176/99493812-e2d0a300-293d-11eb-830e-b720c6a45969.png)

**Comment by manekenpix** [comment]
I don't think this is a real issue. Telescope has a github repo and a slack channel, nothing else (also, Telescope doesn't have a twitter account, Telescope is part of CDOT, it's **not** CDOT).
