### ISSUE TITLE
Remove box border/shadow of blog posts

### ISSUE THREAD

**Issue by VietnameZe** [Seneca-CDOT/telescope#1401]
a small change but I think the site looks better without the box border/shadow. It looks just 'cleaner' to me, anyone think the same? I can see most modern sites these day they getting rid of border/shadow

Screenshots:

![](https://i.imgur.com/Na9e9Ux.jpg)
![](https://i.imgur.com/c0Yz3fe.jpg)

**Comment by Shinh18** [comment]
This issue is similar to another issue where the post content did not seem to align with post header because of box shadow, so the property was removed. #1188
