### ISSUE TITLE
Auto hide Navbar when scrolling up (Mobile)

### ISSUE THREAD

**Issue by VietnameZe** [Seneca-CDOT/telescope#1403]
I would like to optimize a bit of the site's UI (mobile version)

Screenshot:
![](https://i.imgur.com/yKHZYWE.gif)

**Comment by PedroFonsecaDEV** [comment]
@VietnameZe This was already fixed. You need to download and build our latest version.

**Comment by PedroFonsecaDEV** [comment]
We had this feature, and then we decided not to have this feature.
