### ISSUE TITLE
Overflow & Margin problem on Search page (mobile)

### ISSUE THREAD

**Issue by VietnameZe** [Seneca-CDOT/telescope#1406]
This happen on the new update of dev site (mobile):
https://dev.telescope.cdot.systems/search/

Problem: overflow part appear on the right -> refresh -> overflow part gone but losing post's header margin.

UPDATE: on local, refresh doesn't get rid of the overflow part.

See screen capture below:

![](https://i.imgur.com/tBAzuhJ.gif)

**Comment by VietnameZe** [comment]
@tonyvugithub @PedroFonsecaDEV @humphd

**Comment by PedroFonsecaDEV** [comment]
@VietnameZe go for it.
