### ISSUE TITLE
Add search result metrics info to search results

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1408]
**What would you like to be added**:

When we do a search, it would be nice to get some details about how many results matched our query, and maybe how many are currently being shown (e.g., `showing results 35 of 126`).

**Why would you like this to be added**:

We have this amazing new infinite scrolling feature for search results, but no idea how many results there are.  It would be good if we had a clue how much to scroll.

**Comment by joelazwar** [comment]
I might have something. 

![image](https://user-images.githubusercontent.com/43277890/99675425-c8b3d380-2aa9-11eb-954d-28b0fbd96bb9.png)

**Comment by joelazwar** [comment]
got it! it updates when you load more posts as well. Just need some help with the UI design now
![image](https://user-images.githubusercontent.com/43277890/99677517-60b2bc80-2aac-11eb-9d76-f79ea39f6d50.png)

**Comment by humphd** [comment]
Awesome!  cc @agarcia-caicedo for thoughts on UI.

**Comment by tuanthanh2067** [comment]
Is this issue still open? I think we can do something like bit 
![image](https://user-images.githubusercontent.com/51014333/143508725-18dde6a0-39d4-4079-a5c6-31903b2e4c57.png)

**Comment by humphd** [comment]
Yeah, it's still open.  That's an interesting idea.  I don't love it looking identical to the title, but the concept is cool.  Could also put it in the right-hand side area?  Worth experimenting.

**Comment by tuanthanh2067** [comment]
You mean right below user's information?

**Comment by humphd** [comment]
What if you put a Chip component to one side of the title: `(1 of 13)`, so it stands out from the title text as a piece of UI. https://mui.com/components/chips/

Or it could go on the right, but I think that will get cluttered with all the GitHub info.

**Comment by tuanthanh2067** [comment]
Chip components sound interesting, I will go with it

**Comment by tuanthanh2067** [comment]
I'm wondering whether or not we're able to get the total amount of posts when doing a search? Because in the `SearchResults.tsx`, it seems like it fetches 5 posts at a time

**Comment by humphd** [comment]
You access in the JSON returned, `results`:

<img width="1089" alt="Screen Shot 2021-11-27 at 6 39 17 PM" src="https://user-images.githubusercontent.com/427398/143723516-1b7e1f14-9609-4880-9c43-94a4a91b63eb.png">
