### ISSUE TITLE
Deal with inline images being streched (aka reduce the size of Tony)

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1412]
Inline images that are within an `<a>` are getting the 100% width treatment, and it ends up not being what the author intended:

<img width="924" alt="Screen Shot 2020-11-18 at 10 55 49 PM" src="https://user-images.githubusercontent.com/427398/99619390-54b5f480-29f1-11eb-8bdf-aa6e338e2484.png">

An `<img>` in an `<a>` is necessarily inline vs. block, so we could maybe fix our selector to not grab those?

**Comment by humphd** [comment]
Also, reduce the size of this guy...

<img width="869" alt="Screen Shot 2020-11-18 at 10 58 54 PM" src="https://user-images.githubusercontent.com/427398/99619553-b1191400-29f1-11eb-94ee-37a4e25a2b71.png">

**Comment by tianlangwu** [comment]
Can we just hide the avatar here? I tried a few times, don't know where is the selector. Where can I modify and select the post-content? does it automatically convert from feeds?

**Comment by humphd** [comment]
All the CSS for a post's content is in https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby/src/components/Post/telescope-post-content.css
