### ISSUE TITLE
"No search results" message shows up before searching anything

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#1415]
**What happened**:

This is what the search page looks like before doing any search:

![Peek 2020-11-19 00-38](https://user-images.githubusercontent.com/23108901/99626102-7cac5480-29ff-11eb-9349-e8af45c21761.gif)

Also, in the image, I'm hitting `ctrl+F5` to show another issue with the position of the elements.

**How to reproduce it (as precise as possible)**:
Go to the search page on telescope

**Environment**:

- OS: Linux
- Browser: Firefox

**Comment by VietnameZe** [comment]
for item alignment problem, I think @humphd has fixed this in https://github.com/Seneca-CDOT/telescope/issues/1341 which is related to another commit need to be reviewed.

I simply used textAlign and it worked
![](https://i.imgur.com/2PjOxHz.jpg)

**Comment by foxviet** [comment]
cc: @DukeManh are you interested in this?
