### ISSUE TITLE
Improve Mobile Usability by adding a bottom app bar

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#1416]
**What would you like to be added**:

Proposed design for a bottom app bar, on the left an user that has not logged in, and on the right an user that has:

![image](https://user-images.githubusercontent.com/49992710/99628168-9ea7d600-2a03-11eb-8a5a-330127755644.png)

**Why would you like this to be added**:
While on mobile, design should keep in mind the range of the thumb. Currently, we have a top bar that is not easy to reach for people that visit the site on mobile.

![image](https://user-images.githubusercontent.com/49992710/99626952-51c30000-2a01-11eb-967a-68dbd8e05375.png)

By adding a bottom app bar, it would benefit the user experience of the mobile users. As an added benefit, it could allow for the title of the post to remain sticky, since there would be enough space for the post sandwiched between the title and the bottom app bar.

**Comment by cindyledev** [comment]
*drools* 🤤

**Comment by PedroFonsecaDEV** [comment]
I really like it.

**Comment by humphd** [comment]
Yes!

Also, somewhat related on the implementation side is #801

**Comment by jiyoungsin** [comment]
Hey everyone, would it be cool if I gave this a shot?

In addition, can someone clarify the url for the persons Icon and what the hamburger menu icon should do?

**Comment by humphd** [comment]
We use Material-UI for all UI, and it has icons, see https://material-ui.com/components/material-icons/.

**Comment by humphd** [comment]
I've assigned this to you, @jiyoungsin, but be warned you're likely in for a lot of back and forth on reviews and styling to get this right.  If you're up for that and expecting it, you'll have no trouble.  You've been warned!

**Comment by jiyoungsin** [comment]
Yes, that sounds like a lovely way to spend my Saturday! I am still confused on what the persons Icon and what the hamburger menu icon should do... I will send up a PR in a few minutes with my current status.

**Comment by jiyoungsin** [comment]
I am also going to need some help with the login functionality. I have never hooked up the Microsoft 365 log in before. If anyone has any experience with this please help me out 😢 .

**Comment by humphd** [comment]
https://github.com/Seneca-CDOT/telescope/blob/master/docs/login.md discusses how to mock login stuff locally via docker.

**Comment by jiyoungsin** [comment]
Thank you for this link. I will finish up my lab 8 and get right on this! :)

**Comment by jiyoungsin** [comment]
This is where I am currently sitting at. I log into the SAML page and it directs me to localhost:3000. Nothing appears on localhost:3000, however, If I look at localhost:8000/user/info I can see the user I have logged into. Could you point me into the right direction to confirm that it is working locally?

![issue1416](https://user-images.githubusercontent.com/44411777/100535651-d32c4680-31e8-11eb-935e-af233d7f6925.gif)

**Comment by humphd** [comment]
Are you running the login container via docker-compose?

**Comment by jiyoungsin** [comment]
![Screen Shot 2020-11-29 at 3 50 23 PM](https://user-images.githubusercontent.com/44411777/100553221-9731c980-325a-11eb-8532-6d0146a3ea0e.png)
 This is how my docker is running. for some reason my telescope_telescope_1 never works. It seems like the npm start is equivalent, however, this is an assumption. I am not sure what exactly is contributing to telescope_telescope_1 not being able to communicate with elasctic-search.

**Comment by humphd** [comment]
What error is the `telescope_telescope_1` container giving when this happens (see the logs).

**Comment by jiyoungsin** [comment]
It seems like I have figured it out! Here is a video of me signing in on this gif!

https://gph.is/g/4LjQrzd

**Comment by humphd** [comment]
Is this not done now?  @chrispinkney @tonyvugithub

**Comment by tonyvugithub** [comment]
@humphd it is done!
