### ISSUE TITLE
Add author suggestions to Elasticsearch indexer backend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1417]
**What would you like to be added**:

If a user starts typing a name, we'd like to be able to present a list of Author completions/suggestions, similar to how Google's search suggestions work.  To do this, we need to add backend support to our [Elasticsearch indexer](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/indexer.js).

**Why would you like this to be added**:

In #1260 we are adding front-end support for autocomplete on an Author search.  
[Here's one good article on possible ways to do this with Elasticsearch](https://medium.com/@taranjeet/elasticsearch-building-autocomplete-functionality-494fcf81a7cf) (there are a few different options we can pick from).

We don't need to send back 1000+ names, but as you type, we could send back a dozen or so, and the more you type the closer we'd get to the name you want.

**Comment by DukeManh** [comment]
@birtony Have you started on this one?

**Comment by birtony** [comment]
Hey @DukeManh, not much yet. Do you want to collaborate?

**Comment by humphd** [comment]
We'll have to figure out whether this needs to talk to the User service or Search service to get the data it needs.  cc @chrispinkney and @raygervais.

**Comment by chrispinkney** [comment]
Hm, well the user microservice doesn't keep track of user posts at all, just feed urls, github info, etc. I haven't looked into the feed microservice yet so maybe it's more appropriate there?
