### ISSUE TITLE
Deal with GitHub sending 3 events per release to autodeployment

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1423]
@manekenpix notes that our autodeployment server receives 3 separate events from GitHub when we do a release:

![image](https://user-images.githubusercontent.com/427398/99737018-78cb1180-2a95-11eb-8bbc-95c0b6c780e2.png)

I *think* this is probably a commit, a tag, and a release being made (three different resources), but don't know.  We should see if we can ignore the ones we don't care about, and probably only deal with the release.

**Comment by humphd** [comment]
From Slack:

> oh, I see, 3 different actions: created, released, and published

**Comment by HyperTHD** [comment]
Issue was resolved in #1600. Closing
