### ISSUE TITLE
Fix the anchor tags of scroll-up/scroll-down arrows. 

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1425]
**What happened**:
The post title does not fit 100% into the Navbar when you click on the arrows. 
**What should have happened**:
The post title should fit 100% into the Navbar when using the arrows.
**How to reproduce it (as precise as possible)**:
![2020-11-19 19 02 05](https://user-images.githubusercontent.com/60857409/99739265-5f789400-2a9a-11eb-9bbb-b0ca6e807025.gif)

**Anything else we need to know?**:

**Environment**:

- OS: macOS - Big Sur (11.0.1) 
- Browser: Chrome.

**Comment by tianlangwu** [comment]
I have sent a Pull Request([PR-1429](https://github.com/Seneca-CDOT/telescope/pull/1429)) for this issue.
