### ISSUE TITLE
Scroll To Top button doesn't move to correct position

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1426]
Scroll down into the posts and then click the Scroll To Top fab we have.  It will move you up, but not quite to the right spot, so the post title is just out of alignment with the header:

<img width="1190" alt="Screen Shot 2020-11-19 at 7 13 00 PM" src="https://user-images.githubusercontent.com/427398/99739723-6227b900-2a9b-11eb-9a95-32266f5a3674.png">

**Comment by tianlangwu** [comment]
I can not find where is "#back-to-top-anchor" css setting. I try to add a #back-to-top-anchor-searchPage css to my [PR-1428](https://github.com/Seneca-CDOT/telescope/pull/1428) too.

**Comment by tianlangwu** [comment]
I have sent a Pull Request([PR-1429](https://github.com/Seneca-CDOT/telescope/pull/1429)) for this issue.
