### ISSUE TITLE
Search text param from URL not synced to input control(s)

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1427]
We had a couple of features land in 1.4.0 that affect how search params are populated in the UI.  First, we added support for URL query params to allow sharing URLs.  If you open a URL to a search URL, it will run that search.

We also reworked the search bar to add autocomplete behaviour, which meant we changed how we pass and display props.

I wonder if we missed something in a rebase and lost the ability to pass the text of the URL param do the UI input control.

For example, if you click this URL https://telescope.cdot.systems/search/?filter=post&text=react.js  you will run a search for `react.js` but it doesn't update the text in the search input:

<img width="1198" alt="Screen Shot 2020-11-19 at 7 15 53 PM" src="https://user-images.githubusercontent.com/427398/99739979-fbef6600-2a9b-11eb-9c02-aaf4ab2c2527.png">

cc @jossiey, @MSTEWARDSON

**Comment by jossiey** [comment]
@MSTEWARDSON Could you check the SearchBar.js you used? Cause in [my PR](https://github.com/Seneca-CDOT/telescope/pull/1343), I already change [`const { searchText, onChangeHandler, onFilterChangeHandler, filter, onFormSubmit} = props;` ](https://github.com/MSTEWARDSON/telescope/blob/9ddb846de54f6782e1080fe81035b57d116ffd11/src/frontend/src/components/SearchBar/SearchBar.jsx#L105)  to [`const { text, onTextChange, onFilterChange, filter, onSubmit } = props;`](https://github.com/MSTEWARDSON/telescope/blob/9ddb846de54f6782e1080fe81035b57d116ffd11/src/frontend/src/components/SearchBar/SearchBar.jsx#L105), while I saw in [your PR](https://github.com/Seneca-CDOT/telescope/pull/1387), it was the old version. I think you need fetch upstream and rebase your branch to this commit [f02d964](https://github.com/Seneca-CDOT/telescope/pull/1343/commits/f02d9645a6d51bb0acac99dac93bb090d00df285). Let me know, if you have any questions. Thank you.

**Comment by MSTEWARDSON** [comment]
@jossiey Sorry I just saw your message now.  I messed up in that PR, so another one was made. The one that was merged had your updated version of the props. `const { text, onTextChange, onFilterChange, filter, onSubmit } = props;`

**Comment by humphd** [comment]
Mistakes happen, and until we have front-end tests, it's really easy to miss little changes like this.  I missed this too in my reviews, as did the other reviewers.  This is "our" mistake as a project vs. the responsibility of one person.

Since you two understand this code better than anyone else, can one of you do a PR to correct it?

**Comment by jossiey** [comment]
@humphd Understand. I am trying to find out where the missing codes are.  @MSTEWARDSON  could you send the link of your latest PR to me? Let me figure out the problem.

**Comment by jossiey** [comment]
@MSTEWARDSON I will fix this issue. Please send me your latest PR. I will double check your code when I submit a new PR to make sure everything is correct.

**Comment by MSTEWARDSON** [comment]
@jossiey Here is the PR [Fix #1260: Added frontend support for autocomplete #1418](https://github.com/Seneca-CDOT/telescope/pull/1418)

**Comment by jossiey** [comment]
I have fixed the bug. @MSTEWARDSON suggest to double check the pull request. Thank you.
