### ISSUE TITLE
[next] Deal with Header,  Header/DesktopHeader, and Header/MobileHeader

### ISSUE THREAD

**Issue by jossiey** [Seneca-CDOT/telescope#1446]
**What would you like to be added**:
- [ ] Header/
- [ ] Header/DesktopHeader
- [ ] Header/MobileHeader

**Why would you like this to be added**:
Next.js migration

**Comment by chrispinkney** [comment]
I'll take on the DesktopHeader component, potentially the other two as well but if anyone wants one of them go for it and reply to this issue 👍
