### ISSUE TITLE
Build Gatsby and Next PR Previews

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1447]
In #1444 I'm going to merge the Gatsby and Next branches together in `master` so we will have `src/frontend/gatsby` and `src/frontend/next`.  I'd like to find a way to build both frontends on every PR, while we are porting between the two.

In theory, we can do this with Vercel via [their monorepos support](https://vercel.com/blog/monorepos).  I've tried to understand how this works, but can't, so someone could experiement and do more reading.

Another option would be to do a mix of Netlify and Vercel, one for Gatsby and one for Next.

This is a short term solution, since we'll rip out the Gatsby one once Next is ready.

**Comment by humphd** [comment]
A bunch of sites discuss the difficulty of doing this automatically from git, but that you can do it via GitHub Actions with multiple deploy steps, see https://carlosroso.com/how-to-deploy-a-monorepo-in-vercel/ for example.

**Comment by raygervais** [comment]
I'd be interested in experimenting with this, continuing my core contributions around the CI/CD & Docker space for 🔭. 
Would I need to get Vercel access? I have Netlify access (but not connected to Telescope of course). 

Given the amount of build minutes we use in a month, I imagine we'd be close to Netlify's build limit quota. https://www.netlify.com/pricing/faq/

**Comment by humphd** [comment]
@raygervais if you're open to it, that would be great.

I hope that the secondary build will be short lived while we port the frontend, and then we can turn it off.  Maybe Netlify would be ok for that period?

**Comment by raygervais** [comment]
Makes sense, I'll reach out over Slack to discuss Netlify creds or how to access under the `Seneca-CDOT` account (or walk you through it once I have config done).
