### ISSUE TITLE
Logging no longer formatted for pretty display locally

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1448]
We used to have really nice logging, pretty-printed for local debugging, but now I get raw JSON:

```
{"level":30,"time":1606175748870,"pid":88703,"hostname":"brightness.local","msg":"Starting 1 instance of feed processor."}
```

It might be something about how me `.env` is setup after the Kibana change?  Not sure, but I miss my pretty logs.

cc @c3ho

**Comment by c3ho** [comment]
It was the pino change, I have a fix for it. Regression testing for pino and then I'll submit a PR
