### ISSUE TITLE
Post header overlap (z-index) issue with hamburger menu

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1449]
Our new sticky post header is fighting with the hamburger menu, such that it overlaps Home and About:

<img width="1177" alt="Screen Shot 2020-11-23 at 9 07 31 PM" src="https://user-images.githubusercontent.com/427398/100037436-185b0d80-2dd0-11eb-8f82-ab1b09ca510d.png">

Probably a z-index issue?

**Comment by tianlangwu** [comment]
It's definitely a z-index issue.
