### ISSUE TITLE
Author links can point to /

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1455]
I've seen a few posts where the author link points to `/` which takes you back to our Telescope app vs. the author's blog URL, for example:

<img width="998" alt="Screen Shot 2020-11-24 at 4 17 37 PM" src="https://user-images.githubusercontent.com/427398/100152407-a555a380-2e70-11eb-98d5-438dfd0b9215.png">

This might be intentional (i.e., our myfeeds form might have allowed it?)  Or the wiki feed page did?

We should figure out how to **not** allow users to make this mistake.

**Comment by foxviet** [comment]
@humphd  I don't think this bug is exists now

**Comment by humphd** [comment]
https://dev.telescope.cdot.systems/search?filter=author&text=andre and you can see that it does

**Comment by foxviet** [comment]
> https://dev.telescope.cdot.systems/search?filter=author&text=andre and you can see that it does

I thought it occurs on the main page

**Comment by humphd** [comment]
We render the same timeline/post component in both places.  It seems to be specific to some posts, not all.  Could be a bug in our feed parsing?  Could be a bug with this blog?  Could be in the front-end?  Not sure.

**Comment by foxviet** [comment]
it seemed this happened to this author only,after tried a couple other authors. In one (only) blog of this author, the embedded images are broken too. 

![](https://i.imgur.com/HiHCUZw.jpg)

image url:

![](https://i.imgur.com/RfsSyCq.jpg)

**Comment by humphd** [comment]
The feed is https://abhaseen.github.io/feed.xml, which is giving 404.  Maybe I should just remove the feed from our system.

**Comment by yuanLeeMidori** [comment]
Same here, I've checked couple authors and only this specific author's link leads to `/`, which might because of the 404 user feed.

**Comment by yuanLeeMidori** [comment]
In this case, I think we can check the feed list and see if there is any 404 URL? And remove the invalid ones manually. Maybe use a bot to do this?

**Comment by humphd** [comment]
Seems to be a one-off, and we can sort this out in the future with data validation on the User service.  Closing.
