### ISSUE TITLE
LoadAutoScroll missing file extention

### ISSUE THREAD

**Issue by strawberries73** [Seneca-CDOT/telescope#1457]
**What happened**:
I noticed an error in Timeline.jsx  Missing file extention for ./LoadAutoScroll.jsx 

**What should have happened**:
The path to module should have been resolved.

![image](https://user-images.githubusercontent.com/39388566/100258948-a1c82800-2f15-11eb-8a79-238bc19f4b9e.png)

**Comment by HyperTHD** [comment]
We looked into this and this error is no longer an issue on the next port which will be the main front-end engine. Closing this
