### ISSUE TITLE
[next] Update 500 error UI styling for failed search

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1458]
When our Elasticsearch server fails, and we send the browser a 500, we show an error message:

<img width="1260" alt="Screen Shot 2020-11-25 at 4 22 18 PM" src="https://user-images.githubusercontent.com/427398/100282993-a18e5380-2f3a-11eb-866e-bd3b88bfabf8.png">

Let's improve the look of this to be more consistent with the app.  There is some similar discussion for "no results" happening in #1413, and maybe we can do a similar visual in both cases.

**Comment by sonechca** [comment]
I would like to work on this issue. Can I join in this issue?

**Comment by humphd** [comment]
Go for it.

**Comment by sonechca** [comment]
I update PR, Can you check my PR? https://github.com/Seneca-CDOT/telescope/pull/1512
Thank you :)
