### ISSUE TITLE
[next] create About page from Gatsby version

### ISSUE THREAD

**Issue by chrispinkney** [Seneca-CDOT/telescope#1463]
**What would you like to be added**:
About page, see src/frontend/src/markdown-pages/about.md

**Why would you like this to be added**:
Surely, it must be transferred.

See #1316

**Comment by humphd** [comment]
Filed #1590 on the failing build case we found in Netlify and locally.  Reverted in https://github.com/Seneca-CDOT/telescope/commit/0a23cf5774f6c970125f46ebbec0c5b475ba1c06
