### ISSUE TITLE
Scroll To Top button on the search page does not work in mobile version

### ISSUE THREAD

**Issue by tianlangwu** [Seneca-CDOT/telescope#1464]
**What happened**:
Scroll To Top button on the search page does not work for the mobile version.
**What should have happened**:
Scroll To Top button should move the scroll to the top of the page in the mobile version.
**How to reproduce it (as precise as possible)**:
1. Open telescopes in mobile version, click on the search icon to navigate to the search page.
2. Scroll the page down until the button shows, click the button, and nothing happens.

![ezgif-2-f24759f3e931](https://user-images.githubusercontent.com/60892464/100393416-8fc6b200-3007-11eb-9e03-48e365002e74.gif)

**Comment by manekenpix** [comment]
I can't reproduce. Did you test `dev.telescope.cdot.systems` or `telescope.cdot.systems`?

![Peek 2020-11-26 17-05](https://user-images.githubusercontent.com/23108901/100393949-64dd5d80-3009-11eb-98ed-abb0942a384a.gif)

**Comment by tianlangwu** [comment]
> I can't reproduce. Did you test `dev.telescope.cdot.systems` or `telescope.cdot.systems`?
> 
> ![Peek 2020-11-26 17-05](https://user-images.githubusercontent.com/23108901/100393949-64dd5d80-3009-11eb-98ed-abb0942a384a.gif)

did u test it on the search page or the main page? When I am testing, the search page one does not work on mobile version

**Comment by manekenpix** [comment]
Oh, the search page. Yes, I just tested in on the search page and it doesn't work on mobile version.
