### ISSUE TITLE
Port Error page from GatsbyJS to Next.js

### ISSUE THREAD

**Issue by hyunjiLeeTech** [Seneca-CDOT/telescope#1468]
**What would you like to be added**:
This is an issue to port Error page from Gatsby to NextJS

**Why would you like this to be added**:
Part of #1316, transitioning of the Telescope front-end from Gatsby to Next

**Comment by raygervais** [comment]
If you have any questions, feel free to reach out @hyunjiLeeTech. I've assigned you to this so it's easier to track as well.

**Comment by raygervais** [comment]
So I don't believe any of the front end logic utilizes Gatsby aside from the router. You should be good to port to NextJS and utilize NextJS Router to access the page. Unsure what's _partly done_ :confused: @hyunjiLeeTech

**Comment by hyunjiLeeTech** [comment]
@raygervais Hi, I have a question about this task. When I researched how to create Nextjs error page, it said I need to create _error.js file. I've almost done to display status code and error message but EsLint test is not passed my work because it has the rule that it doesn't allow to create the file extension not using ts or tsx. Can you please tell me whether I need to find another way to use tsx for the Error page or it is okay to keep my work?

**Comment by raygervais** [comment]
Sure let's have a look, do you have a PR open? @hyunjiLeeTech

**Comment by raygervais** [comment]
I see your PR, according to issues such as https://github.com/vercel/next.js/issues/12127 and https://github.com/vercel/next.js/issues/12256 this should be possible. What error are you encountering?

**Comment by hyunjiLeeTech** [comment]
I've seen the error 'JSX not allowed in files with extension '.js'' from EsLint test.

**Comment by hyunjiLeeTech** [comment]
Also, 
'prop-types' shold be listed in the project's dependencies. Run 'npm i -S prop-types' to add it import/no-extraneous-dependencies
message when I run 'npm test'. I've pushed my commits to resolve previous errors from lint.

**Comment by hyunjiLeeTech** [comment]
The second issue is resolved :)
