### ISSUE TITLE
Don't overlap serach input text with input search adornment

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1476]
In #1474 we are moving the search button down inside the search input.  If search text is long, it will overlap the text, and cover it.  Probably we should add internal padding to the right side to stop the text from going beyond the area covered by the adornment.

<img width="625" alt="Screen Shot 2020-12-02 at 9 12 38 AM" src="https://user-images.githubusercontent.com/427398/100883981-f2440600-347e-11eb-9f62-6daa6f09ba08.png">

**Comment by MLJBrackett** [comment]
Hey @humphd I'd like to give they a try, please assign me and I'll get to work.

**Comment by shenqu1** [comment]
Hi @humphd, how is this issue going? Can I work on it?

**Comment by humphd** [comment]
@shenqu1 go for it, that would be great.
