### ISSUE TITLE
[Next] Port AuthorResults Component to Next.js

### ISSUE THREAD

**Issue by joelazwar** [Seneca-CDOT/telescope#1478]
**What would you like to be added**:
Porting the AuthorResults component from Gatsby to Next
**Why would you like this to be added**:
as part of the front end Next.js migration task in #1316

**Comment by c3ho** [comment]
Im pretty sure this component is not used anymore in the master branch

**Comment by joelazwar** [comment]
oh my bad youre right, i completely forgot we dropped this component for searching for author posts. I'll add a note on #1316 about this unused component
