### ISSUE TITLE
Port BackToTopButtom from Gatsby to Next.js(TS)

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#1480]
What would you like to be added:
This is an issue to port BackToTopButton from Gatsby to NextJS

Why would you like this to be added:
Part of #1316

**Comment by joelazwar** [comment]
If you haven't already, I could help out with porting this if you'd like.

**Comment by c3ho** [comment]
No worries, I assigned it to you.

**Comment by tianlangwu** [comment]
isn't this part of #1469? I thought ScrollToTop contains both BackToTopButton and ScrollAction.

**Comment by tianlangwu** [comment]
I guess I can just do Scroll Action, then you can take BackToTopButton @joelazwar

**Comment by joelazwar** [comment]
@tianlangwu I think the task list on #1469 is a little outdated, some components are missing/does not exist anymore. It should definitely be updated, but sure I can take the backtotopbutton component for now
