### ISSUE TITLE
XSS Vulnerability - Content Within Inline <code> Element is Run

### ISSUE THREAD

**Issue by 1jz** [Seneca-CDOT/telescope#1488]
**What happened**:
I came across this when attempting to view a piece of regex I posted on my blog and the following appeared on telescope:

regex: `(<br>(\s?)+?){2,}`

![](https://i.imgur.com/SZRM24l.png)

**What should have happened**:
The HTML displayed should be
```
<code>(<br>(\s?)+?){2,}</code>
```

**How to reproduce it**:
When using backticks on some blogging platforms the text between the backticks are put into a \<code\> element.

If you type any HTML between the backticks the `<` and `>` symbols aren't escaped and are treated as HTML for the webpage meaning you can run scripts from any blog.

Here's another example of what's happening/possible https://jsfiddle.net/jnagc7mL/2/

**Anything else we need to know?**:
To fix this `<` and `>` symbols should be escaped with \&lt; and \&gt; entities.

**Comment by humphd** [comment]
cc @smilegodly

**Comment by humphd** [comment]
I confirmed we're OK, and added some tests for this: https://github.com/Seneca-CDOT/telescope/pull/1635
