### ISSUE TITLE
About Page - Fix content alignment.

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1490]
**What happened**:
<img width="396" alt="Screen Shot 2020-12-06 at 7 54 04 PM" src="https://user-images.githubusercontent.com/60857409/101299137-0aa97d00-37ff-11eb-97dd-aeea782cc90b.png">
<img width="424" alt="Screen Shot 2020-12-06 at 7 53 36 PM" src="https://user-images.githubusercontent.com/60857409/101299139-0aa97d00-37ff-11eb-99bf-d98bd1d955c4.png">

**What should have happened**:
The content should not create space on the right side of the page.
**How to reproduce it (as precise as possible)**:
1- Go to the "About" page.
2- Open your developer tools, and start to decrease the size of the window. While checking when the right space appears.
**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by rjayroso** [comment]
So I tried recreating this on my Firefox browser but to no avail so I tried the same test on Google Chrome and I noticed that the body element does not fit to screen, as shown below:

![Firefox/Chrome comparison](https://user-images.githubusercontent.com/48869737/105834498-8bcbf780-5f98-11eb-9b31-59855eab9dc1.png)
*Firefox on the left, Google Chrome on the right*

Does anybody have any insight as to why it is only on Chrome that this happens? It might be the solution to this styling bug.

**Comment by chrispinkney** [comment]
This will be closed when #1651 lands, closing now as a result as this pertains to Gatsby which will not be used.
