### ISSUE TITLE
[next] Port Dynamic image from Unsplash Collection, see src/frontend/gatsby-node.js to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1492]
**What would you like to be added**:
Port Dynamic image from Unsplash Collection
**Why would you like this to be added**:
Porting reason

**Comment by joelazwar** [comment]
I'm currently working on porting the DynamicImage component, is this file a dependency for it? if it is how should I go about migrating this to next?

**Comment by humphd** [comment]
@raygervais, I'm going to take this over, and I'd appreciate your guidance on the approach I should use.  I'm trying to decide how much like our current code I should make this.

Next has a fancy `<Image>` component that does exactly what we want...if you run the app with server-side rendering.  They dynamically resize/optimize/serve the correct image a runtime for you.  When you `npm run export` on a nextjs project, you lose the ability to do this.

This leaves me with a few approaches I could take:

- do the image selection and optimization server side (either at run-time or build-time).  The client component would use a URL like `https://telescope.cdot.systems/background`, which would serve a suitable, random, optimized image and cache headers to make this efficient
- use something like https://www.npmjs.com/package/next-optimized-images and hack into the `next.config.js` or write custom nextjs plugin to download all the Unsplash images, optimize them, and put them in the `/public` folder.  We'd have to find some way to then mirror what the Gatsby graphql stuff is doing now to get those optimized filenames into the front-end code (array of URLs?).

I feel like the first approach is a better option, but maybe I'm missing something, or a third possible approach.  I know you spent a lot of time thinking about this, so I wanted to get your input before I began.  Thanks for any thoughts.

**Comment by raygervais** [comment]
I agree @humphd that the first approach being the cleaner of the two, if we went that direction I'd even advise having another repo such as `telescope_backgrounds` connected as another git module; the logic being to not bear down on developers who have no care for the backgrounds in their environments. 

I'm intrigued how NextJS can do this dynamically, my only experience with Gatsby / Gridsome involved all images being processed and rendered via HTML at once. Again to your idea of having a dedicated API endpoint which already contains all the processed images, this is a terrific idea!

I also really like the idea of moving the archive from Unsplash (which still acts as a fantastic source) to make building and maintaining the collection more accessible to the community around Telescope. Perhaps with the proper JSON / YAML structure, we can still save the image metadata such as author etc and credit them appropriately as well.

A side note, this may be the perfect start of a dedicated micro-service for image asset handling and optimizations _my reasoning being that we don't clutter the backend with additional functionality that will have to be split in the future to smaller services._

I'd be open to helping / advising where possible, but cannot commit any more time than that right now.

**Comment by humphd** [comment]
@raygervais I'd like to find a time to discuss microservices as an approach for what we're doing, and figure out if it's a good fit.  I know you have a lot of experience with them.  Ping me some time when you have a chance and we can discuss more.

**Comment by humphd** [comment]
For the 1.6 release, I'm going to do a very basic version of this that just uses 1 image, and generates some static HTML for the image.  For reference, here is what Gatsby generates for that image:

```html
<div
  class="jss60 gatsby-image-wrapper"
  style="position: relative; overflow: hidden"
>
  <div aria-hidden="true" style="width: 100%; padding-bottom: 75%"></div>
  <img
    aria-hidden="true"
    src="data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wgARCAAPABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAEEAgP/xAAWAQEBAQAAAAAAAAAAAAAAAAAAAgP/2gAMAwEAAhADEAAAAYe2FmjEU//EABoQAAMBAAMAAAAAAAAAAAAAAAABAgMREiH/2gAIAQEAAQUCzS50R6Q3JpTo7H//xAAUEQEAAAAAAAAAAAAAAAAAAAAQ/9oACAEDAQE/AT//xAAUEQEAAAAAAAAAAAAAAAAAAAAQ/9oACAECAQE/AT//xAAaEAACAgMAAAAAAAAAAAAAAAAAERAhAQIx/9oACAEBAAY/ArMLkMetR//EABkQAAMBAQEAAAAAAAAAAAAAAAABETEhUf/aAAgBAQABPyHFaPvel6OGNFCftFnBNgoP/9oADAMBAAIAAwAAABCk3//EABURAQEAAAAAAAAAAAAAAAAAAAEQ/9oACAEDAQE/EAn/xAAWEQEBAQAAAAAAAAAAAAAAAAARARD/2gAIAQIBAT8QK5//xAAcEAEBAAIDAQEAAAAAAAAAAAABEQAxIUFhUXH/2gAIAQEAAT8Q+xBiqddYcWoRNkt/OMoATTrzANCUcsjBmi+879xjK5//2Q=="
    alt=""
    style="
      position: absolute;
      top: 0px;
      left: 0px;
      width: 100%;
      height: 100%;
      object-fit: cover;
      object-position: center center;
      opacity: 0;
      transition-delay: 500ms;
    "
  /><picture
    ><source
      srcset="
        /static/d43000bd57e9b5053ce67ee402e9dff9/8850c/p55zezwahEk.jpg  200w,
        /static/d43000bd57e9b5053ce67ee402e9dff9/da113/p55zezwahEk.jpg  400w,
        /static/d43000bd57e9b5053ce67ee402e9dff9/f2cbb/p55zezwahEk.jpg  800w,
        /static/d43000bd57e9b5053ce67ee402e9dff9/c26c2/p55zezwahEk.jpg 1200w,
        /static/d43000bd57e9b5053ce67ee402e9dff9/9352a/p55zezwahEk.jpg 1600w,
        /static/d43000bd57e9b5053ce67ee402e9dff9/c9bb6/p55zezwahEk.jpg 4592w
      "
      sizes="(max-width: 800px) 100vw, 800px" />
    <img
      sizes="(max-width: 800px) 100vw, 800px"
      srcset="
        /static/d43000bd57e9b5053ce67ee402e9dff9/8850c/p55zezwahEk.jpg  200w,
        /static/d43000bd57e9b5053ce67ee402e9dff9/da113/p55zezwahEk.jpg  400w,
        /static/d43000bd57e9b5053ce67ee402e9dff9/f2cbb/p55zezwahEk.jpg  800w,
        /static/d43000bd57e9b5053ce67ee402e9dff9/c26c2/p55zezwahEk.jpg 1200w,
        /static/d43000bd57e9b5053ce67ee402e9dff9/9352a/p55zezwahEk.jpg 1600w,
        /static/d43000bd57e9b5053ce67ee402e9dff9/c9bb6/p55zezwahEk.jpg 4592w
      "
      src="/static/d43000bd57e9b5053ce67ee402e9dff9/f2cbb/p55zezwahEk.jpg"
      alt=""
      loading="lazy"
      style="
        position: absolute;
        top: 0px;
        left: 0px;
        width: 100%;
        height: 100%;
        object-fit: cover;
        object-position: center center;
        opacity: 1;
        transition: opacity 500ms ease 0s;
      " /></picture
  ><noscript
    ><picture
      ><source
        srcset="
          /static/d43000bd57e9b5053ce67ee402e9dff9/8850c/p55zezwahEk.jpg  200w,
          /static/d43000bd57e9b5053ce67ee402e9dff9/da113/p55zezwahEk.jpg  400w,
          /static/d43000bd57e9b5053ce67ee402e9dff9/f2cbb/p55zezwahEk.jpg  800w,
          /static/d43000bd57e9b5053ce67ee402e9dff9/c26c2/p55zezwahEk.jpg 1200w,
          /static/d43000bd57e9b5053ce67ee402e9dff9/9352a/p55zezwahEk.jpg 1600w,
          /static/d43000bd57e9b5053ce67ee402e9dff9/c9bb6/p55zezwahEk.jpg 4592w
        "
        sizes="(max-width: 800px) 100vw, 800px" />
      <img
        loading="lazy"
        sizes="(max-width: 800px) 100vw, 800px"
        srcset="
          /static/d43000bd57e9b5053ce67ee402e9dff9/8850c/p55zezwahEk.jpg  200w,
          /static/d43000bd57e9b5053ce67ee402e9dff9/da113/p55zezwahEk.jpg  400w,
          /static/d43000bd57e9b5053ce67ee402e9dff9/f2cbb/p55zezwahEk.jpg  800w,
          /static/d43000bd57e9b5053ce67ee402e9dff9/c26c2/p55zezwahEk.jpg 1200w,
          /static/d43000bd57e9b5053ce67ee402e9dff9/9352a/p55zezwahEk.jpg 1600w,
          /static/d43000bd57e9b5053ce67ee402e9dff9/c9bb6/p55zezwahEk.jpg 4592w
        "
        src="/static/d43000bd57e9b5053ce67ee402e9dff9/f2cbb/p55zezwahEk.jpg"
        alt=""
        style="
          position: absolute;
          top: 0;
          left: 0;
          opacity: 1;
          width: 100%;
          height: 100%;
          object-fit: cover;
          object-position: center;
        " /></picture
  ></noscript>
</div>
```
