### ISSUE TITLE
[next] Port AdminButtons/ to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1494]
https://github.com/Seneca-CDOT/telescope/tree/master/src/frontend/gatsby/src/components/AdminButtons
**What would you like to be added**:
Port all components inside AdminButtons/ to NextJS
**Why would you like this to be added**:
Porting reason

**Comment by sonechca** [comment]
Hi Tony,

I ported the admin button to Next.Js and added PR
Can you check my [PR](https://github.com/Seneca-CDOT/telescope/pull/1515)? let me know if I need to fix more 
Thank you :)

**Comment by tonyvugithub** [comment]
I don't think they plan on accepting any PR now. They want to have some discussions before doing so I think. Someone like @manekenpix or @humphd might be able to answer you better

**Comment by sonechca** [comment]
Ok  I am gonna ask them. Thank you, Tony :)

**Comment by tonyvugithub** [comment]
@sonechca : is there any update on this? We are waiting on this as it is a dependent component for some others.
