### ISSUE TITLE
[next] Port GitHubContributorCard/ to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1496]
https://github.com/Seneca-CDOT/telescope/tree/master/src/frontend/gatsby/src/components/GitHubContributorCard
**What would you like to be added**:
Port all components in GitHubContributorCard/ to NextJS
**Why would you like this to be added**:
Porting reason

**Comment by joelazwar** [comment]
I'll take this one
