### ISSUE TITLE
[next] Port MyFeedsPage/ to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1497]
https://github.com/Seneca-CDOT/telescope/tree/master/src/frontend/gatsby/src/components/MyFeedsPage
**What would you like to be added**:
Port all components in MyFeedsPage/ to NextJS using TS
**Why would you like this to be added**:
Porting reason

**Comment by HyperTHD** [comment]
Issued closed with #1505
