### ISSUE TITLE
[next] Port SearchHelp/ to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1499]
https://github.com/Seneca-CDOT/telescope/tree/master/src/frontend/gatsby/src/components/SearchHelp
**What would you like to be added**:
Port all components in SearchHelp/ to NextJS using TS
**Why would you like this to be added**:
Porting reason

**Comment by joelazwar** [comment]
looks like @hyunjiLeeTech has opened another of the same issue (#1507) and taken it. I'll close this to avoid any confusion.
