### ISSUE TITLE
[next] Port contexts/User/ to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1501]
**What would you like to be added**:
Port all components in User/ to NextJS using TS
**Why would you like this to be added**:
Porting reason

**Comment by HenryZerocool** [comment]
Hi, I don't see User components in gatsby, frontend.
Are you sure it's there?

**Comment by tonyvugithub** [comment]
@HenryZerocool it is not a component. It is in the contexts folder. More like contexts.
