### ISSUE TITLE
Confine CSS to its own directory, update stylelint

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#151]
In https://github.com/Seneca-CDOT/telescope/pull/66#discussion_r344993179 we ran into an issue where our `stylelint` checks are looking at files that aren't relevant.  Right now, we're [checking every file that *isn't* being ignored](https://github.com/Seneca-CDOT/telescope/blob/master/package.json#L8).  Let's flip this around and *only* check files in certain paths.

To do this, let's move our frontend code to `src/web/*` or something, and within that create `src/web/styles/*`.  We can move our stylesheet(s) there, and tell `stylelint` to only look at that directory for now vs. our entire tree.

**Comment by cindyledev** [comment]
After this gets approved, someone should edit the index.html file links to planet.css in its new location.

**Comment by ODAVING** [comment]
Tag me when this is done and I’ll do it

**Comment by humphd** [comment]
By the way, we need to move all of our frontend web files (`index.html`, `pagination.js`, etc) out of the root and into `src/frontend/*`.  The `planet.css` is happening in the PR for this, but after that lands, can someone file an Issue/PR to do the rest?  We shouldn't have any source files in the root, only project config files.
