### ISSUE TITLE
Feeds with summary missing content

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1514]
I notice that @badalsarkar's blog posts only show the first paragraph:

<img width="811" alt="Screen Shot 2020-12-10 at 1 16 47 PM" src="https://user-images.githubusercontent.com/427398/101813024-31f79700-3aea-11eb-8080-b7ed8a2235cf.png">

[The actual post is much longer](https://badalsarkar.ca/blog-opensource/opensource/my-open-source-journey/) and I notice that the [blog feed](https://badalsarkar.ca/blog-opensource/feed.xml) contains a `<summary>...</summary>` that matches what we have on Telescope.

I wonder if we're using the `summary` vs. `content` in the feed parser?

**Comment by humphd** [comment]
This is an Atom feed with both `content` and `summary` (in that order) and it looks like the `summary` is being used for `description`, despite there being `content` too.  Some background https://github.com/danmactough/node-feedparser/issues/156.

**Comment by HyperTHD** [comment]
@manekenpix We're looking over some issues right now, we'd appreciate any feedback on this issue whenever you have the time

**Comment by manekenpix** [comment]
I wonder if this was an issue with @badalsarkar 's feed. @raygervais had a similar issue (I think) with his blog, but he changed his feed and it works now:
https://telescope.cdot.systems/search/?text=gervais&filter=author

**Comment by humphd** [comment]
It very well could be.  @raygervais so your issue was with your end vs. us?  I had assumed it was due to how we parsed RSS vs. some later versions of Atom with a summary included.

**Comment by raygervais** [comment]
That's correct, in my case (using Hugo as the CMS Platform), I had to update my RSS feed template: https://github.com/raygervais/raygervais.dev/commit/635d0978c1a9abe07debd99109442fc69ac765cc

By default, Hugo only displays the summary. So for my case, it was a problem with my site itself since it wasn't displaying the entire content in the feed.

**Comment by humphd** [comment]
OK, I'm going to close this and we'll refile if it happens again.  Thanks for the update on what happened.
