### ISSUE TITLE
<Image> text being converted to <img> tag

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1532]
<img width="819" alt="Screen Shot 2020-12-21 at 8 15 08 PM" src="https://user-images.githubusercontent.com/427398/102837179-4f214500-43c9-11eb-88f9-1741743af90c.png">

The original from https://blog.humphd.org/snowyowls-ca/ has this:

```html
<code><Image></code>
```

Maybe because it isn't wrapped in a `<pre>`?

**Comment by cindyledev** [comment]
I dug into this and according to the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/image), the `<image>` tag has been deprecated and some browsers will automatically convert `<image>` to `<img>` which is most likely what we're experiencing here. I actually tried to stick `<code><Image></code>` into random webpages using both Google Chrome and Firefox and they both automatically convert `<code><Image></code>` to `<code><img></code>`

**Comment by humphd** [comment]
Fascinating!  I didn't know this.  The web is so complicated.  Thank you @cindyledev!
