### ISSUE TITLE
Node Version 15+ Does Not Install Dependecies Properly

### ISSUE THREAD

**Issue by birtony** [Seneca-CDOT/telescope#1534]
**What happened**: I have tried to set up the project to run on my local machine. I followed [the environment setup documentation ](https://github.com/Seneca-CDOT/telescope/blob/master/docs/environment-setup.md)and on [the final step](https://github.com/Seneca-CDOT/telescope/blob/master/docs/environment-setup.md#finally) I could not start the backend. `npm start` returned an error:
![image](https://user-images.githubusercontent.com/33902374/104532074-6bd22680-55dd-11eb-965d-f4970258ddc4.png)
After trying to run `npm install` from the root of the project explicitly, I have received the following error:
![image](https://user-images.githubusercontent.com/33902374/104532122-873d3180-55dd-11eb-992f-64c3656a5c6d.png)
`node_modules` was not installed in the root directory.

**What should have happened**: Required dependencies should have been installed successfully and the backend should have started.

**How to reproduce it (as precise as possible)**: Install Node version 15+ (specifically mine was `15.5.1`) and follow [the environment setup documentation](https://github.com/Seneca-CDOT/telescope/blob/master/docs/environment-setup.md) for running the project on local. 

**Anything else we need to know?**: I have done some research on the error I got and found [a potentially linked issue open under Jest repository](https://github.com/facebook/jest/issues/10820). As suggested in Telescope's Slack channel, we might either try to manually fix this dependencies issue or set explicitly the Node engine to use version 14 until the newer version has this issue fixed.

**Environment**: Production, `Node` version `15.5.1`, `npm` version `7.3.0`

- OS: Ubuntu Linux 20.04.1 LTS (Potentially Windows and macOS as well)
- Browser: N/A

**Comment by cindyledev** [comment]
If Telescope doesn't work with Node 15, as a temporary bandaid, we need to mention that Telescope only supports Node 14 in the [environment docs](https://github.com/Seneca-CDOT/telescope/blob/master/docs/environment-setup.md) to prevent new contributors from getting Node 15 and have Telescope not work.

**Comment by chrispinkney** [comment]
I can confirm that it doesn't install or run in version 15.

**Comment by Metropass** [comment]
Made a change in .npmrc, the issue should be fixed until we reconfigure the way we install dependencies
