### ISSUE TITLE
[next] Port DeleteFeedDialogButton to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1539]
https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby/src/components/MyFeedsPage/DeleteFeedDialogButton.jsx
**What would you like to be added**:
Port DeleteFeedDialogButton component to NextJS using TS
**Why would you like this to be added**:
Porting reason

**Comment by HyperTHD** [comment]
Taking this one over
