### ISSUE TITLE
[next] Port LoadAutoScroll component to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1540]
https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby/src/components/Posts/LoadAutoScroll.jsx
**What would you like to be added**:
Port LoadAutoScroll component to NextJS using TS
**Why would you like this to be added**:
Porting reason

**Comment by PedroFonsecaDEV** [comment]
#### Reason to close this issue: 
`LoadAutoScroll` was ported on PR https://github.com/Seneca-CDOT/telescope/pull/1504
