### ISSUE TITLE
[next] Port PostSearchInput to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1542]
https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby/src/components/SearchInput/PostSearchInput.jsx
**What would you like to be added**:
Port PostSearchInput component to NextJS using TS
**Why would you like this to be added**:
Porting reason

**Comment by HyperTHD** [comment]
I'd like to handle the porting of this component if that's alright
