### ISSUE TITLE
[next] Port SearchInput to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1545]
https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby/src/components/SearchInput/SearchInput.jsx
**What would you like to be added**:
Port SearchInput component to NextJS using TS
**Why would you like this to be added**:
Porting reason

**Comment by nilan01** [comment]
Hi there! Would be happy to take this on once `AuthorSearchInput` is complete.

**Comment by chrispinkney** [comment]
Closed by #1575

**Comment by chrispinkney** [comment]
@nilan01 

Before starting this please see `AuthorSearchInput.tsx` and `PostSearchInput.tsx`.

Both search bars are currently styled locally inside the component, however the actual `SearchInput` component styles both components and passes in a themed style prop that both `SearchInput` components will need to apply.

See the Gatsby version of `SearchInput` and `AuthorSearchInput.tsx` and `PostSearchInput.tsx` or pm me on slack for more info!

**Comment by nilan01** [comment]
Will do, thanks @chrispinkney !

**Comment by PedroFonsecaDEV** [comment]
We need to clean our Issues because we have dups.
I just made this PR (it was an old PR), but the issue was #1500 a different one. 

The PR: https://github.com/Seneca-CDOT/telescope/pull/1580

<img width="964" alt="Screen Shot 2021-01-21 at 5 53 22 AM" src="https://user-images.githubusercontent.com/60857409/105341750-77a98400-5bad-11eb-87cd-c0b0ca694d6f.png">

**Comment by chrispinkney** [comment]
@PedroFonsecaDEV I don't see anyone assigned to the previous issue (#1500) until you assigned yourself 6 hours ago while Nilan expressed interest in doing this yesterday.

**Comment by nilan01** [comment]
Sorry for the mix-up this was the Searchinput that was linked on the [wiki page](https://github.com/Seneca-CDOT/telescope/wiki/Front-end-Port:-List-of-Components).

**Comment by c3ho** [comment]
Ah this was my issue, the previous merging of my other or closed this issue I think

**Comment by PedroFonsecaDEV** [comment]
> @PedroFonsecaDEV I don't see anyone assigned to the previous issue (#1500) until you assigned yourself 6 hours ago, while Nilan expressed interest in doing this yesterday.
> 
> We should double check sometime for any more dupe issues but I don't think there's anymore.

I was checking for abandoned PRs: [PR - 1520]( https://github.com/Seneca-CDOT/telescope/pull/1520)
There weren’t any comments about someone working on the PR, and we ship tomorrow. So I jumped in. 
I noticed the dup after I sent the PR when I checked the milestone progress, and I saw this issue as part of the milestone.
