### ISSUE TITLE
[next] Port SearchResults to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1546]
https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby/src/components/SearchPage/SearchResults.jsx
**What would you like to be added**:
Port SearchResults component to NextJS using TS
**Why would you like this to be added**:
Porting reason

**Comment by chrispinkney** [comment]
@rjayroso See also #1458 (Corresponding PR #1512)
