### ISSUE TITLE
[next] Port HelpPopoverButton component to NextJS

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1547]
https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby/src/components/MyFeedsPage/HelpPopoverButton.jsx
**What would you like to be added**:
Port HelpPopoverButton component to NextJS using TS
**Why would you like this to be added**:
Porting reason

**Comment by nilan01** [comment]
Hi there, I would like to take this issue on.

**Comment by humphd** [comment]
Go for it @nilan01
