### ISSUE TITLE
[next] Port global config of 1)pages/styles 2)src/frontend/src/pages/PageBase.js 3)src/frontend/src/styles/globals.css 4)styles/telescope-post-content.css 5)highlight.js/styles/github.css

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1548]
**What would you like to be added**:
[next] Deal with global config of:
|  PR |  MERGED	|  ITEM  	|
|---	|---	|---	|
|   info1	| info1 	|   ~~1.src/frontend/src/pages/PageBase.js~~	|
|   <ul><li>[x] </li></ul>	|   <ul><li>[x] </li></ul>	|   2.`src/frontend/src/styles/globals.css`	|
|   info2	|  info2	|   ~~3.`src/frontend/src/templates/template.js`~~	|
|   <ul><li>[x] </li></ul>   |   <ul><li>[x] </li></ul>	|   4.`styles/telescope-post-content.css`	|
|   <ul><li>[x] </li></ul>   |   <ul><li>[x] </li></ul>	|   5.`highlight.js/styles/github.css`	|

info1:
`PageBase` is no longer need on our NEXT.js front-end:
1) `PageBase` was used to reset our CSS globally; with NEXT.js, we perform this on our styles/globals.css. 
2) About `SEO` and `Header` please check https://github.com/Seneca-CDOT/telescope/pull/1566#pullrequestreview-572244259

info2: 
`src/frontend/src/templates/template.js` is part of the `About Page`. 

**Why would you like this to be added**:

**Comment by humphd** [comment]
Per discussion in https://github.com/Seneca-CDOT/telescope/pull/1504#pullrequestreview-546736818, we also need to include `styles/telescope-post-content.css` globally for next.js.

**Comment by PedroFonsecaDEV** [comment]
@tonyvugithub 
please check this issue description regarding your work on `SEO`.

**Comment by PedroFonsecaDEV** [comment]
@humphd 
Could you please review the description of the issue?

**Comment by PedroFonsecaDEV** [comment]
All items have been merged.
