### ISSUE TITLE
Remove all uses of React.FC in our TypeScript code

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1553]
**What happened**:

We have a mix of different approaches to defining our React components in the next.js TypeScript.  In some places we use `React.FC` for typing, and in others we don't.

Let's remove all instances of `React.FC`.

**What should have happened**:

According to https://github.com/facebook/create-react-app/pull/8177, there are some issues with always using `FC`, and we'd probably be better served by removing it.  I also think this will be a win for new React devs who don't know TS very well, and encounter `FC` for the first time in our code.

If you're reviewing new code, ask the developer to remove `FC`.  For any that slips in, let's do a sweep and remove it all later on.

See also discussion in https://github.com/Seneca-CDOT/telescope/pull/1531#discussion_r559562973.

**Comment by HyperTHD** [comment]
Update: As of January 25th, 2021, only the Banner component uses FC. I also once DynamicBannerImage is ported over and we start work on the Banner, this will change. We can close this issue and work on #1557 after the Banner component is ported over.

![1 FC Component Left](https://user-images.githubusercontent.com/16841702/105792443-75507c80-5f55-11eb-97e9-0105289f7f93.png)

**Comment by HyperTHD** [comment]
#1667 is the PR that addresses the last component using React.FC, which is the banner component. Once that's taken cared of, this issue can be closed
