### ISSUE TITLE
Add guide for working with TS, MUI, next.js

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1557]
We're using TypeScript with next.js, React, and Material UI, and there are lots of quirks and things to know.

I've been using these docs and examples a lot:

- https://github.com/typescript-cheatsheets/react#reacttypescript-cheatsheets
- https://material-ui.com/guides/typescript/
- https://github.com/vercel/next.js/tree/canary/examples/with-typescript
- https://github.com/vercel/next.js/tree/canary/examples/with-typescript-types
- https://github.com/vercel/next.js/tree/canary/examples/blog-starter-typescript
- etc (see https://github.com/vercel/next.js/tree/canary/examples for more examples)

We should consider adding some doc with links that we can use to point contributors at.

**Comment by chrispinkney** [comment]
Good comment from Abdul [here](https://github.com/Seneca-CDOT/telescope/pull/1558#pullrequestreview-570874083):

> We should probably update docs at some point or make some sore of note that we don't use FC. I know it's widely known at this point but I'm sure people new to TS might have some questions about that
