### ISSUE TITLE
Fix Material-UI Icons not rendering

### ISSUE THREAD

**Issue by chrispinkney** [Seneca-CDOT/telescope#1572]
**What happened**:
See PR #1564:

> This continues the work from #1529.
> I had to do a few more things to get this working:
> I needed to stop eslint from checking for default props, and we'll do it instead via TypeScript. It's not possible otherwise to use default values in TS.
> I had to rework how the colors were being done, to use classes and the theme.palette instead of the color prop, which won't work with theme names.
> I removed the window param from the scroll manager, and always use it by default.
> I had to change how ScrollAction was defined for children to work with typings
> However, when I test this, my elements have a width/height of 0, so it displays nothing. I can't figure out what's wrong, and would appreciate some help.

**What should have happened**:
The icon from the PR (i.e. `BackToTopButton` component) should have been rendered. The code looks fine to me, so I suspect the issue might be deeper than expected.

This needs fixing before we launch next entirely.

**Comment by cindyledev** [comment]
Regarding the BackToTopButton https://github.com/Seneca-CDOT/telescope/pull/1564#issuecomment-763814176

**Comment by tonyvugithub** [comment]
@chrispinkney : did this get handled?

**Comment by chrispinkney** [comment]
Looks like it with the latest deployment.
