### ISSUE TITLE
Use an env var to determine which front-end gets served

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#1576]
**What would you like to be added**:

We need a way to specify which front-end gets served by telescope.
Currently, the path to the folder where the front-end build lives is [hard-coded](https://github.com/Seneca-CDOT/telescope/blob/6cfd7dfce743ed80bf38a7364c5a5511e4b50001/src/backend/web/routes/index.js#L50), and it's the `Gatsby` front-end.
We could have a variable in our `env.example` (and eventually in our staging and production `env` files) to choose between the Next and the Gatsby front-end.
Something like:
```js
const { FRONTEND } = process.env;

if (FRONTEND === 'gatsby')
  router.use(express.static(path.join(__dirname, '../../../frontend/gatsby/public'))); 

else if (FRONTEND === 'next')
  router.use(express.static(path.join(__dirname, '../../../frontend/next/out'))); 

else if (FRONTEND === '...')
...

```

This will be specially useful for testing `login` locally using Next.

EDIT: path to `next` folder changed following [this](https://github.com/Seneca-CDOT/telescope/issues/1576#issuecomment-764203256) comment.

**Comment by humphd** [comment]
Per https://github.com/Seneca-CDOT/telescope/pull/1487#discussion_r561535188, the path for next's build is `out` vs. `.next`

**Comment by Metropass** [comment]
I'll try to make a mockup, should be done within the next few days.
I was thinking we can use something that is of type `enum` for this?

**Comment by manekenpix** [comment]
@Metropass I think we could use our `.env` files to decide which front-end gets served. This way, we can select the front-end we want to build without having to make changes to the code (we would have to make a PR every time we want a different front-end served).

Feel free to assign the issue to yourself!

**Comment by Metropass** [comment]
Will do!

**Comment by chrispinkney** [comment]
@Metropass See [this](https://github.com/Seneca-CDOT/telescope/pull/1487/files#diff-c3877fbd3e2c4a17fe86388d235278d2eb5c5c367d71c9a147463d2c2b7c6706R30), until this is merged I think we're using 'build' as the output directory from `npm run build:next`, so if you aren't getting the `/out` folder you know why, just make a change locally on your end until my PR is merged.

**Comment by humphd** [comment]
We're only going to have next by the end of the week, so closing.
