### ISSUE TITLE
[next] Create a context to Search components.

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1584]
**What would you like to be added**:
We are drilling props on our SeachPage components, let's create a context to solve this. 
**Why would you like this to be added**:
I don't like to drill more than one level.

**Comment by HyperTHD** [comment]
I'm gonna fix this once we land #1741 and #1745. Depending on how quick we get those PRs merged, I should be able to land this in either 1.7 or 1.8. Regardless, it's a non-blocking issue
