### ISSUE TITLE
[next] Both next's production server and telescope's back-end use port 3000

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#1586]
Next's production server runs on port 3000, like telescope's backend.
This makes it impossible to run both at the same time.

We could change the production server's port in the `package.json` located in the `next` folder:

```diff
--- a/src/frontend/next/package.json
+++ b/src/frontend/next/package.json
@@ -5,7 +5,7 @@
   "scripts": {
     "dev": "next dev -p 8000",
     "build": "next build && next export",
-    "start": "next start"
+    "start": "next start -p 8080"
   },
```

**Comment by tonyvugithub** [comment]
@manekenpix : How about port 8000 as in the case of development?
