### ISSUE TITLE
[next] Infinite Scrolling of Posts is broken

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1595]
**What happened**:

In #1504 we landed the new Posts, Post, and Timeline components for next.js.  The first page loads OK, but when you scroll down, the infinite scrolling isn't working correctly.  It looks like there is a ton of network activity (i.e., it's loading pages like it should) but it's not being updated in the UI.  I also think it's loading too much, so we may have a dependency issue with the hook that's loading things.

**What should have happened**:

You should be able to scroll down forever, like we can on Gatsby

**How to reproduce it (as precise as possible)**:

Go to https://telescope-next.netlify.app/, open your dev tools and the Network tab, and start scrolling down.  You'll get to the bottom and it won't keep working, but the network will go crazy loading pages.

We have a similar bug in the infinite scrolling for the search page, which could be connected, or just the same problem but a different cause.

cc @rogercyyu, @PedroFonsecaDEV.

**Comment by PedroFonsecaDEV** [comment]
I am working on it.
