### ISSUE TITLE
[next]  BackToTopButton issues

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1596]
**What happened**:

The ScrollToTop control in the posts timeline has a few issues:

- the colours don't match what Gatsby has (white vs. black)
- clicking the icon doesn't scroll the page

<img width="181" alt="Screen Shot 2021-01-22 at 6 36 40 PM" src="https://user-images.githubusercontent.com/427398/105560112-ea674c00-5ce0-11eb-92cb-16722e7de602.png">

**What should have happened**:

This should be the same as what we have in Gatsby

**How to reproduce it (as precise as possible)**:

1. Open https://telescope-next.netlify.app/ and scroll down to get the ScrollToTop control to appear
2. Open https://dev.telescope.cdot.systems/ and scroll down to get the ScrollToTop control to appear
3. Compare

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by PedroFonsecaDEV** [comment]
Working on it.
