### ISSUE TITLE
[next] Post banner has incorrect height/margins and alignment

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1597]
**What happened**:

The Post Header component has the wrong height/margins compared to what we have in Gatsby:

<img width="1629" alt="Screen Shot 2021-01-22 at 6 39 58 PM" src="https://user-images.githubusercontent.com/427398/105560286-58ac0e80-5ce1-11eb-8cbf-473b130d84ad.png">

**What should have happened**:

We should match the design in the current site.

**How to reproduce it (as precise as possible)**:

Compare https://dev.telescope.cdot.systems/ to https://telescope-next.netlify.app/

**Comment by humphd** [comment]
cc @rogercyyu

**Comment by humphd** [comment]
Another issue I notice is that the author and date are now on 2 lines vs. 1.

**Comment by humphd** [comment]
I wonder if this is partly due to the feature @yuanLeeMidori added last term to expand/hide the contents of the header on click?

**Comment by yuanLeeMidori** [comment]
Let me check it

**Comment by rogercyyu** [comment]
okay, might be my fault:
Post,jsx (line -165)
```js
        <Typography variant="p" className={classes.author}>
          &nbsp;By&nbsp;
          <a className={classes.link} href={post.feed.link}>
            {post.feed.author}
          </a>
        </Typography>
```
Post.tsx (line - 164)
```js
        <Typography className={classes.author}>
          &nbsp;By&nbsp;
          <a className={classes.link} href={post.feed.url}>
            {post.feed.author}
          </a>
        </Typography>
```
`variant="p"` is missing.

**Comment by yuanLeeMidori** [comment]
@humphd Hi, I don't think it's related to my expand title feature. My expand feature only apply to the `<Typography>` of title element. It seems to me like the issue is in the author name or the published time element.

**Comment by yuanLeeMidori** [comment]
I just checked it, I think @rogercyyu is right. I put the `variant="p"` to the author element and it makes the author name and published time on the same row, just like what it was in the gatsby.

**Comment by PedroFonsecaDEV** [comment]
@yuanLeeMidori, Could you please send a PR to fix this for us?

**Comment by yuanLeeMidori** [comment]
Sure, I'll send one tomorrow
