### ISSUE TITLE
Add a Vercel badge to README.md

### ISSUE THREAD

**Issue by chrispinkney** [Seneca-CDOT/telescope#1598]
**What would you like to be added**:
A Vercel deployment badge could also be placed on our `README.md` file so that the newly added Netlify badge won't be so lonely.
I think @humphd is the owner/admin of the Netlify service so I think the badge is something only he can provide us.

**Comment by humphd** [comment]
https://github.com/vercel/vercel/discussions/4824 claims it doesn't exist yet :(

**Comment by HyperTHD** [comment]
Closing because Vercel does not have a badge yet at the moment and we won't know when one is made available
