### ISSUE TITLE
Use octokit/webhooks.js in autodeployment server

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1604]
**What would you like to be added**:

Let's use the [official webhook event library from GitHub](https://github.com/octokit/webhooks.js) in our autodeployment server.

**Why would you like this to be added**:

I think it would be good to use a GitHub supported library here, since the data coming from the webhook is GitHub's.

**Comment by manekenpix** [comment]
The autodeployment server currently uses [github-webhook-handler](https://www.npmjs.com/package/github-webhook-handler).
Comparing [oktokit's](https://github.com/octokit/webhooks.js#usage) and [github-webhook-handler's](https://github.com/rvagg/github-webhook-handler#example) examples, it seems that they way they work is almost identical. What's the advantage of switching from one to the other?

**Comment by humphd** [comment]
Maintenance.  The oktokit one is maintained by GitHub, and will follow changes to the GitHub API.
