### ISSUE TITLE
LoadMoreButton is currently not working

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1610]
**What happened**:
When you scroll to the bottom of the main page and clicked on `LoadMoreButton`, it froze for a bit and gave an timeout error
![image](https://user-images.githubusercontent.com/55034244/105876672-30682c80-5fcd-11eb-9889-5b28090551b5.png)

**What should have happened**:
It should load more posts

**How to reproduce it (as precise as possible)**:
Go to the telescope website and click on `LoadMoreButton`

**Comment by tonyvugithub** [comment]
@PedroFonsecaDEV : Is this related to what you are working on with infinity scroll in Next?

**Comment by PedroFonsecaDEV** [comment]
@tonyvugithub You are creating dupes AGAIN. Please close this issue. 

Original issue: https://github.com/Seneca-CDOT/telescope/issues/1595

**Comment by tonyvugithub** [comment]
@PedroFonsecaDEV : this is happening on Gatsby production build though. Thats why Im asking.
