### ISSUE TITLE
[next] Port Banner from Gatsby to Next

### ISSUE THREAD

**Issue by chrispinkney** [Seneca-CDOT/telescope#1616]
**What would you like to be added**:
The banner should be ported from Gatsby to Next.

**Why would you like this to be added**:
We should display our banner with pride.

**Comment by HyperTHD** [comment]
This issue will also close #1553 since the banner component is the only one left, so the PR should also link there as well as here once it's up

**Comment by PedroFonsecaDEV** [comment]
@HyperTHD according to https://github.com/Seneca-CDOT/telescope/issues/1316 you are working on this right? So please assign yourself to the issue so we can track who is working on what.
