### ISSUE TITLE
Triggering search through URL doesn't work.

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#1630]
**What happened**:
#1583 will land soon, triggering search through normal use works, but triggering search through URL doesn't work.

**What should have happened**:
Triggering search through search function AND url should work like it does in our current front-end

**How to reproduce it (as precise as possible)**:
Does work:
Go to /search and choose a filter, type in text to search. Results will display

Does not work:
Type /search?filter=post&text=Telescope. No results will display.
**Anything else we need to know?**:

**Environment**:

- OS: Mac
- Browser: Chrome

**Comment by DukeManh** [comment]
Hi, I can give this problem a try. My thinking is that we only need to access the router query after page load or access it every time it changes.

**Comment by humphd** [comment]
@DukeManh sounds good, go for it.  Let us know how we can help.

**Comment by DukeManh** [comment]
Great, I will get started soon.

**Comment by DukeManh** [comment]
#1657

**Comment by DukeManh** [comment]
The new properly rebased PR is #1741
