### ISSUE TITLE
Integrate data from GitHub into our UI

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1644]
**What would you like to be added**:

Let's figure out some useful ways to integrate a user's GitHub activity into Telescope.  Currently, users blog about their work, much of it happening in GitHub. However, we don't have a way to surface this info to a reader of Telescope.

Some things that might be interesting:

- which projects is this user focused on right now?  (e.g., which repos are they working in)
- which projects are the Telescope community working in right now?  For example, during Hacktoberfest, where are we spending our time?
- recent PRs they've made (code contributions)
- recent Reviews/Issues and other non-code contributions
- week/month/semester stats.  How active is the community right now?
 
We need to give some thought as to how to surface this info without it being overwhelming or so dense that you can't really do anything with it.

We may need to create a second "timeline" to go along with the posts vs. trying to jam this into the current UI.  We might also integrate a bit of it into the Posts as links (e.g., click this link to see PRs from this user).

**Why would you like this to be added**:

In #1643 we're working on adding info about a user's GitHub account to Telescope.  

#1611 depends on this.

**Comment by humphd** [comment]
cc @Metropass

**Comment by Metropass** [comment]
Yeah, so for anyone seeing this issue now, I've started prototyping with [Octonode](https://github.com/pksunkara/octonode) to see what data we can pull. 

I'm gonna look at [OctoKit/Rest.js](https://octokit.github.io/rest.js/v18), and play around with it. 

I'll be talking about this on Friday if anyone is interested

**Comment by Metropass** [comment]
@PedroFonsecaDEV Apologies for the wait, I've been quite ill mentally so I took a step back last week.

So far the following works

- Querying on contributors to Telescope (might expand to Seneca-CDOT in general, but that's for later)
- Grabbing projects that contributors have been working on
- Telescope Issues with a certain tag on them (i.e, first issue, backend, etc.)

What I'm currently working on:

- Recent PR's posted
- Activity Logging
- Release Querying (i.e, Query that the latest release version of Telescope)

I'm getting back into the groove of things, so I might make a PR based on the Microservices API we're building.

**Comment by manekenpix** [comment]
Now that #2360, do we still need this?

**Comment by humphd** [comment]
I'd love to go deeper with it how we use GitHub data, but I see your point.  I'll file new issues when I have specifics.
