### ISSUE TITLE
Create Service for Auto discovery of Feeds for URLs

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1645]
**What would you like to be added**:

Add a way for an RSS/Atom Feed to be discovered for a URL.  This requires a few things:

1. back-end API that takes a URL and examines/tests it to determine a Feed URL.  For example, if I give you http://blog.com I might get back http://blog.com/feed.  We could do this as a microservice as part of #1627.
2. front-end component(s) that allow a user to enter a URL, trigger an API call to our feed discovery back-end service, then show the resulting feed URL or an error.

Most blogging platforms follow a pattern we can define in code:

- Wordpress: http://blog-user-name.wordpress.com/category/category-name/feed/
- Blogger: http://blog-user-name.blogspot.com/feeds/posts/default/-/categorylabel?alt=rss
- Medium: https://medium.com/feed/@blog-user-name
- Dev.to: https://dev.to/feed/blog-user-name

There are others that we can probably guess or brute force to discover.  We can also do some validation in the back-end to make sure a feed URL is valid (returns data we can parse).

**Why would you like this to be added**:

#1643 is going aiming to improve the sign-up experience for users, and this is one aspect of that work.

Reference: 
Link to current feed list: https://wiki.cdot.senecacollege.ca/wiki/Planet_CDOT_Feed_List

**Comment by tonyvugithub** [comment]
@humphd : So to confirm, this service is to return the feed URL when someone enter their blog URL, pretty much?

**Comment by humphd** [comment]
I send the API https://tonyknvu.medium.com/ and it makes sure this blog is real and exists, then figures out that the feed is https://medium.com/feed/@tonyknvu and returns that.

The React front-end can use this to accept a blog URL and then provide a feed URL to be sent when we register the user.

**Comment by tonyvugithub** [comment]
@humphd : I think I have an idea how to do this. Can you lay them out here so you can confirm for me?
1) Ping the blog URL/ send a Head request to check if the link is existing. 
2) Filter the domain to determine the blog site and return the feed URL pattern of that blog site. I am thinking to search for a library that could recognize all kind of blog site name, not sure if there is something like that. 

Am I on the right track?

**Comment by humphd** [comment]
Right, I think it should look like this:

1. client does a `POST` to `/` and sends a URL in the body: a blog URL to use (e.g., https://tonyknvu.medium.com/)
2. server makes sure we got a valid URL then either errors (400) or continues
3. server does a `HEAD` request to make sure we get back a 200 with type `text/html` (i.e., it should be a valid web page), not a 404 or something else.
4. server examines the URL and uses it to compare to known patterns for WordPress, Medium, Blogger, etc (we should collect as many as we can).  It uses this to get a candidate feed URL, for example https://medium.com/feed/@tonyknvu
5.  server sends a `HEAD` request to the candidate feed URL and checks for a `200` and proper content-type, one of:
    i. `application/rss+xml`
    ii. `application/rdf+xml`
   iii. `application/atom+xml`
  iv. `application/xml`
  v. `text/xml`
  vi. etc.
6. If the feed is valid, we send back a `200` with the feed URL on the body.  If not, a `400`

**Comment by humphd** [comment]
See the service at src/api/image for a guide on how to start this.

**Comment by tonyvugithub** [comment]
@humphd : Hi Dave, I started to get my hand on this. And I would like to have your input on my progress. My initial thought would be for each step (2-5), I would create a middleware to handle each check.  Is it the right way to think about it? It has been sometimes since I wrote an express server so looking at your Image service really helped.

**Comment by humphd** [comment]
Yeah, doing this as a chain of middleware functions would be perfect, and each one can return an error, or progress to the next step.
