### ISSUE TITLE
Add Traefik as an API Gateway for our Microservices

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1646]
**What would you like to be added**:

Let's add [Traefik](https://doc.traefik.io/traefik/getting-started/quick-start/) to Telescope, and let it manage our microservices API.

Traefik is similar to nginx, in that it acts as a reverse proxy.  However, it is container-aware, and can sit in front of a bunch of docker containers and deal with service discovery, interruption, scaling, deployment, etc.

For now we can use both Traefik and nginx together, and decide how to combine or use them in our system.  We might decide to move all the API under Traefik's control, and do the front-end only in nginx.  Or we might have nginx proxy calls into Traefik.  That all needs to be determined.

**Why would you like this to be added**:

We're starting to explore writing/re-writing the back-end as a set of microservices #1627.  We need a way to deploy, scale, and combine them into something we can use in Telescope.  Since we're already heavily invested in Docker and Docker-Compose, Traefik seems like a logical starting point for doing our api gateway and service management.

**Comment by raygervais** [comment]
@humphd, I meant to close this with our recent work but because my PR was against your branch I could not reference it. Should we close this?

**Comment by humphd** [comment]
Yeah, let's close this now, and we'll file updates on the bits that still need to happen later.  Thanks for getting us started with this code!
