### ISSUE TITLE
Update React to Version 17 to avoid new NextJS warn message

### ISSUE THREAD

**Issue by chrispinkney** [Seneca-CDOT/telescope#1653]
**What would you like to be added**:
We should update React to version 17 (AFAIK [we're currently on](https://github.com/Seneca-CDOT/telescope/blob/8ebd0e961a9326776f5d0fc93e4f92c8fe9b9583/src/frontend/next/package.json#L19) `[react": "^16.13.1]`)

**Why would you like this to be added**:
I think a day or two ago I started getting the following warning [(link/more info here)](https://err.sh/next.js/react-version) when running Telescope:
![Code_2021-02-04_14-53-10](https://user-images.githubusercontent.com/7242003/106954917-75ddd580-6702-11eb-9874-6e7744392131.png)

However, we might not even use any of the features from either React 17 or NextJS 11 (or both), making this update pointless (though the perfectionist in me says getting rid of that yellow text is reason enough.)

Curious to see what everyone else think, LMK!

**Comment by humphd** [comment]
Yeah, updating react/react-dom in src/frontend/next is probably good to do https://github.com/vercel/next-learn-starter/blob/master/learn-starter/package.json

**Comment by PedroFonsecaDEV** [comment]
Okay. I will land this tonight.
