### ISSUE TITLE
Apply Dockerfile best practices from Snyk recommendations

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1668]
I saw a nice post today from Synk about best practices for securing node apps in Docker:

https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/

<img width="1271" alt="Screen Shot 2021-02-07 at 9 41 11 AM" src="https://user-images.githubusercontent.com/427398/107149787-a69f5400-6928-11eb-8772-ec6f5ac4920c.png">

We should apply as many of these as makes sense for us to our existing Dockerfiles, and also the new ones happening in #1636 for microservices.

**Comment by Kevan-Y** [comment]
List of Dockerfile to check:

- [ ] [./Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/Dockerfile)
- [ ] [./src/api/dependency-discovery/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/dependency-discovery/Dockerfile)
- [ ] [./src/api/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/Dockerfile)
- [ ] [./src/api/feed-discovery/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/feed-discovery/Dockerfile)
- [ ] [./src/api/image/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/image/Dockerfile)
- [ ] [./src/api/parser/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/parser/Dockerfile)
- [ ] [./src/api/planet/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/planet/Dockerfile)
- [ ] [./src/api/posts/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/posts/Dockerfile)
- [ ] [./src/api/search/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/search/Dockerfile)
- [ ] [./src/api/sso/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/sso/Dockerfile)
- [ ] [./src/api/status/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/status/Dockerfile)
- [ ] [./src/docs/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/docs/Dockerfile)
- [ ] [./src/web/Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/web/Dockerfile)

**Comment by humphd** [comment]
Other things I want to see us do:

- multi-stage builds, cache dependencies vs. run-time
- use smaller run-time images

**Comment by JerryHue** [comment]
@Kevan-Y, could you tell us how much is left on this?

**Comment by Kevan-Y** [comment]
@JerryHue See https://github.com/Seneca-CDOT/telescope/issues/1668#issuecomment-1069676606,

**Comment by JerryHue** [comment]
Based on that list, I am not really sure if we can get this done by release 2.9, unless you'd like to ask for someone else's help and you can guide them on what to do.

**Comment by aserputov** [comment]
I'm ready to help. We can finish this until 2.9.

**Comment by humphd** [comment]
Thanks @aserputov, that would be a big help.
