### ISSUE TITLE
Test case for Extracting of URLs from blog feed 

### ISSUE THREAD

**Issue by dbeigi** [Seneca-CDOT/telescope#167]
Goal is to write some test cases for the issue #102

**Comment by humphd** [comment]
@dbeigi I assume you're doing this?  If so, assign yourself.  If not, ignore this.

**Comment by dbeigi** [comment]
Oh I seem to forget to assign myself

**Comment by dbeigi** [comment]
@smilegodly did you want to work on this together?

**Comment by smilegodly** [comment]
@dbeigi 
It's already in process of being written.
Thanks though for the offer.

**Comment by agarcia-caicedo** [comment]
Looks like this was merger, closing.
