### ISSUE TITLE
[next] [UI] - Mobile UI

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1675]
**What would you like to be added**:
The new mobile UI. 

https://user-images.githubusercontent.com/60857409/107325068-1f142b00-6a77-11eb-981f-5f1a78139b2d.mp4

**Comment by PedroFonsecaDEV** [comment]
We will break this issue into small parts:
Follow some ideas:

- Bottom Bar
- Post's Title Mobile

**Comment by foxviet** [comment]
I think there's some problems on this design:
- right hand user will hit logout button as 'back' button.
- bold title and smaller, put titles on top of blog posts (can be wrapped in multiple lines with author&date under), shouldn't keep it fixed on header Nav anymore due to small screen size.

**Comment by tonyvugithub** [comment]
@foxviet : The nav bar got move to the bottom, So I think you misunderstood the design. 
@PedroFonsecaDEV: Also, I agree that the logout button could be redesign so the users would not click it by accident and sign out, maybe some rethinking here.

**Comment by foxviet** [comment]
> @foxviet : The nav bar got move to the bottom, So I think you misunderstood the design.
> @PedroFonsecaDEV: Also, I agree that the logout button could be redesign so the users would not click it by accident and sign out, maybe some rethinking here.

I know, just used wrong word, should be 'fixed' title bar on top

**Comment by PedroFonsecaDEV** [comment]
Closing this issue.
REASON: We are going to work on this here: https://github.com/Seneca-CDOT/telescope/issues/1676
