### ISSUE TITLE
[UI 2.0] - Home Page - Design Reference

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1676]
**What would you like to be added**:
# DESKTOP
The new desktop UI - Please use the video and the image as a reference when working on the UI. 
![DESKTOP UI - 2 0](https://user-images.githubusercontent.com/60857409/107446664-e2930e80-6b0c-11eb-96d8-86a66d6c996d.jpg)

https://user-images.githubusercontent.com/60857409/107325178-51be2380-6a77-11eb-8105-fd45560a6934.mp4

# MOBILE

https://user-images.githubusercontent.com/60857409/107451570-8da7c600-6b15-11eb-9d74-a9b6f8881ec0.mp4

![iPhone 6, 7, 8 Plus – 2](https://user-images.githubusercontent.com/60857409/107451635-afa14880-6b15-11eb-8fc3-50ef070a3af8.jpg)

________________________________________________________________
| PR 	| MERGED 	| ISSUE 	| ASSIGNED 	|
|----	|--------	|-------	|----------	|
|     <ul><li>[x] </li></ul>	|   <ul><li>[x] </li></ul>      	|     [Light Theme](https://github.com/Seneca-CDOT/telescope/issues/1678)  	|     @tonyvugithub      	|
|    <ul><li>[x] </li></ul> 	|         <ul><li>[x] </li></ul>	|      [Post + Author Info](https://github.com/Seneca-CDOT/telescope/issues/1677) 	|       @PedroFonsecaDEV  	|
|   <ul><li>[x] </li></ul> 	|        <ul><li>[x] </li></ul>	|       [SideBar](https://github.com/Seneca-CDOT/telescope/issues/1687)	|      @DukeManh    	|
|   <ul><li>[x] </li></ul> 	|        <ul><li>[x] </li></ul>	|       [Posts](https://github.com/Seneca-CDOT/telescope/issues/1688)	|      @PedroFonsecaDEV 	|
|    <ul><li>[x] </li></ul>	|        <ul><li>[x] </li></ul>	|       [ScrollToTop](https://github.com/Seneca-CDOT/telescope/issues/1689)	|       @izhuravlev    	|
|    <ul><li>[ ] </li></ul>	|        <ul><li>[ ] </li></ul>	|       [Post's CSS content](https://github.com/Seneca-CDOT/telescope/issues/1690)	|      @huynguyez    	|

**Comment by PedroFonsecaDEV** [comment]
We will break this issue into small parts: 
Follow some ideas:
- Header will become SideBar
- Post's CSS
- Post's Title [Pedro Fonseca] (#1677)
- ScrollAction(BackToTop)

**Comment by foxviet** [comment]
what about swapping position of these 2 sections? author info on the left - right-alignment (blog content still keep in left alignment), the vertical separator can be removed or in grey to make it less significant.

**Comment by foxviet** [comment]
also Logo background color in light-er blue

**Comment by foxviet** [comment]
something like this

![](https://i.imgur.com/QBr4Ioh.jpg)

**Comment by chrispinkney** [comment]
> 
> 
> @humphd @tonyvugithub something like this, the 'search' next to telescope logo is more meaningful I guess 👯
> 
> ![](https://camo.githubusercontent.com/2e7af6bcfc7966feaa60d9b2960db7af1f890267540d1d90482cfee77c478ab5/68747470733a2f2f692e696d6775722e636f6d2f51427234496f682e6a7067)

I really like where this is heading! To clarify what we spoke of in the meeting today, you're removing the three right buttons, and moving them to the top right, right?

**Comment by foxviet** [comment]
@chrispinkney yes correct!

**Comment by PedroFonsecaDEV** [comment]
Let's keep the design the way it is on the issue description. There will be more icons in the future so we will need space for them. ( stream icon, GitHub feed, theme icon...).

**Comment by humphd** [comment]
@PedroFonsecaDEV I think @foxviet is interested in helping to iterate and get involved in the design, so I'm not sure we need to freeze things.  It would be great if you two could chat on Teams or Slack to think about various options.  We had a good discussion on the call today about some tweaks to this.

**Comment by tonyvugithub** [comment]
@humphd @PedroFonsecaDEV : Is there any PR fixing this? It seems to me that the design discussed in here already in.

**Comment by PedroFonsecaDEV** [comment]
DONE. Thank you guys.
