### ISSUE TITLE
[UI 2.0] Light Theme Colors

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1678]
**What would you like to be added**:
Light theme colors for our new UI. 

COLORS:
TITLE:#121D59
ICONS: #121D59
TEXT: #000000
BACKGROUND:#E5E5E5 
ScrollToTop background:  #A0D1FB

Please check: #1676

**Comment by PedroFonsecaDEV** [comment]
@tonyvugithub,
Let me know if you are okay with being assigned to this issue.

**Comment by PedroFonsecaDEV** [comment]
I had assigned @tonyvugithub but I didn't ask him if he was okay with that. Sorry.

**Comment by tonyvugithub** [comment]
@PedroFonsecaDEV : No worry I can update the light theme colors.

**Comment by PedroFonsecaDEV** [comment]
@tonyvugithub It's time! Fire #1692 again.

**Comment by tonyvugithub** [comment]
@PedroFonsecaDEV : UI 2.0 is done for Index page? I could not find the PR or the issue for some reason
