### ISSUE TITLE
Fix Next,js Header Telescope Icon Margins and size

### ISSUE THREAD

**Issue by izhuravlev** [Seneca-CDOT/telescope#1679]
**What happened**: After porting Header.js, MobileHeader.js, DesktopHeader.js from Gatsby to Next.js in #, we've encountered a number of bugs that need to be fixed. One of them is Telescope Icon sizing. 

**What should have happened**: The icon needs to have the same margins and be the same size as in the Gatsby version of the header. 

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by PedroFonsecaDEV** [comment]
@izhuravlev @rjayroso 
We are porting to our new UI, and this bug doesn't need to be fixed.  
Please check https://github.com/Seneca-CDOT/telescope/issues/1676 pick up an issue and assign yourself.

**Comment by PedroFonsecaDEV** [comment]
@izhuravlev @rjayroso

Sorry guys. 
there is a change in our plans. We need to finish the port and have the old UI working 100% on the NEXTJs.

**Comment by PedroFonsecaDEV** [comment]
@izhuravlev could you please check if this is the same issue as #1734 ?

**Comment by izhuravlev** [comment]
@PedroFonsecaDEV the main case here is the placement of telescope icon - if telescope's icon is placed the same way as it was in Gatsby version after merging the PR you mentioned - this one is good to be closed

**Comment by PedroFonsecaDEV** [comment]
@izhuravlev thanks.
So I believe we are good with this one.
