### ISSUE TITLE
Move all frontend files from root

### ISSUE THREAD

**Issue by lozinska** [Seneca-CDOT/telescope#168]
We need to separate frontend files (index.html, pagination.js, etc) from root to src/frontend/*. Keep in root only configuration files

**Comment by humphd** [comment]
NOTE to whoever does this: use `git mv` not `mv`

**Comment by robertbegna** [comment]
i'll work on this

**Comment by humphd** [comment]
This was fixed with https://github.com/Seneca-CDOT/telescope/pull/170, but the GitHub comment wasn't correct.  Manually closing.
