### ISSUE TITLE
Fix Next.js Header height

### ISSUE THREAD

**Issue by izhuravlev** [Seneca-CDOT/telescope#1680]
**What happened**: After porting Header from Next to Gatsby, the height of the header is different

**What should have happened**: The height of the header should be the same as in the Gatsby version.

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by PedroFonsecaDEV** [comment]
@izhuravlev @rjayroso 
We are porting to our new UI, and this bug doesn't need to be fixed.  
Please check https://github.com/Seneca-CDOT/telescope/issues/1676 pick up an issue and assign yourself.

**Comment by PedroFonsecaDEV** [comment]
@izhuravlev @rjayroso

Sorry guys. 
there is a change in our plans. We need to finish the port and have the old UI working 100% on the NEXTJs.

**Comment by PedroFonsecaDEV** [comment]
Issue closed on #1738
