### ISSUE TITLE
Add Light/Dark mode toggle to the Header 

### ISSUE THREAD

**Issue by izhuravlev** [Seneca-CDOT/telescope#1681]
**What would you like to be added**: It would be great to put the Light/Dark mode toggle to the Next.js Header

**Why would you like this to be added**: Looks neat, at it is a lot more useful to have it there than anywhere else.

You can take a look at [Material UI header](https://material-ui.com/) for motivation: 
![image](https://user-images.githubusercontent.com/36719387/107359741-1c045380-6ae6-11eb-8900-6c2df7bd9719.png)

**Comment by tonyvugithub** [comment]
It has already been done #1641. Hence, I will close this issue. Thanks for the effort though.

**Comment by izhuravlev** [comment]
Works for me :) 👍
