### ISSUE TITLE
[UI 2.0] Post's content CSS

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1690]
**What would you like to be added**:
Port our `Post`'s content to our new UI. 
You can find the CSS file here: https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/next/src/styles/telescope-post-content.css

Please check https://github.com/Seneca-CDOT/telescope/issues/1676 for reference.

**Comment by PedroFonsecaDEV** [comment]
@huynguyez 
Let's change the content font to `Roboto` and add breakpoints to change the `font-size`.

**Comment by humphd** [comment]
Another option I was looking at is [PT Serif](https://fonts.adobe.com/fonts/pt-serif#licensing-section), example:

https://time.com/collection/coronavirus-vaccines-updates/

On npm it's [here](https://www.npmjs.com/package/@fontsource/pt-serif).

**Comment by PedroFonsecaDEV** [comment]
@humphd #2010 To solve the font issue. 

@huynguyez What is the progress of this issue?

**Comment by huynguyez** [comment]
@PedroFonsecaDEV  what to do with this one? the uppercase title or something? I don't see any thing to do, or different font? I think the current font for posts is good, clean and easy to read.

**Comment by humphd** [comment]
This was fixed by @tonyvugithub.  Can we close?

**Comment by PedroFonsecaDEV** [comment]
Fixed on #2013
