### ISSUE TITLE
Implement word count feature for the contents of the blog post

### ISSUE THREAD

**Issue by birtony** [Seneca-CDOT/telescope#17]

**Comment by humphd** [comment]
Maybe we can use https://www.npmjs.com/package/wordcount?

**Comment by Reza-Rajabi** [comment]
This seems to have conflict with #7 and #19 .

**Comment by humphd** [comment]
@Reza-Rajabi I don't think they are in conflict, but rather represent parallel steps along an "analysis" pipeline.  We just have to chain them all together.
