### ISSUE TITLE
Add Let's Encrypt to Traefik Microservices router

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1705]
We want to have our microservices available on the web at the following URLs:

- https://api.telescope.cdot.systems/ (for production)
- https://dev.api.telescope.cdot.systems/ (for staging)

Doing so requires us to get SSL certificate management added to Traefik.  Luckily, this is already baked into Traefik, [we only need to configure it](https://doc.traefik.io/traefik/v1.7/user-guide/docker-and-lets-encrypt/).

Depends on:

- #1704
- #1636

**Comment by izhuravlev** [comment]
@manekenpix @humphd mentioned that you are working on this - if so, can we assign it to you?

**Comment by manekenpix** [comment]
Yes, I'll have a PR ready soon

**Comment by humphd** [comment]
@manekenpix the stuff I'm doing in #1812, do you want to get your changes in before or after that?  They are pretty closely connected.

**Comment by manekenpix** [comment]
@humphd I think I should wait until #1812 is merged so I can use the changes (doenv files).
