### ISSUE TITLE
Implement Queue Failed Feeds/Downloads Behaviour

### ISSUE THREAD

**Issue by izhuravlev** [Seneca-CDOT/telescope#172]
As described by @humphd in Issue #112:
"One of our design goals is to have failed downloads of feeds get automatically retried some number of times, but to apply an exponential backoff so we don't just go into an endless loop of failure. [This code shows one way to do this via options to the Bull queue.](https://github.com/syuilo/misskey/blob/873444c3c6f7e3b9ecb6cce569d8cdb3fa032012/src/queue/index.ts#L87-L96)"

**Comment by robertbegna** [comment]
Sure I'll try this

**Comment by robertbegna** [comment]
this issue is free for others to try

**Comment by ragnarokatz** [comment]
@humphd @izhuravlev I would like to work on this issue please.

**Comment by humphd** [comment]
Awesome @ragnarokatz, go for it.  Let us know if you need any help.

**Comment by ragnarokatz** [comment]
@humphd @izhuravlev @Reza-Rajabi I need help with writing the unit test for the `feed-worker.js` module. Please take a look at the referenced PR when you have time, thanks.

**Comment by humphd** [comment]
@ragnarokatz, see discussion in https://github.com/Seneca-CDOT/telescope/issues/210#issuecomment-555081981 which is pretty similar to what you're doing.  Also see my work in #288 that builds on @evlnyng's.  You could review that so we can merge, and it will help you here to mock the queue with redis.
