### ISSUE TITLE
Height of Navbar is inconsistent and Colors are inconsistent

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#1734]
Telescope has switched to using the next frontend on vercel instead of gatsby. Looking at it, there's a small issue with the height of the navbar. It's off by a little bit and should be resolved as an easy fix.

What the navbar should look like:

![Original navbar height](https://user-images.githubusercontent.com/16841702/107856814-cb983900-6df8-11eb-97ee-51af733d9f16.png)

How the navbar looks like on vercel:

![Vercel navbar](https://user-images.githubusercontent.com/16841702/107856822-dce14580-6df8-11eb-9d1f-bf4872230686.png)

Colors are also inconsistent and need to be fixed. See [this comment](https://github.com/Seneca-CDOT/telescope/issues/1734#issuecomment-778651988) for more info

**Comment by humphd** [comment]
<img width="293" alt="Screen Shot 2021-02-13 at 12 44 11 PM" src="https://user-images.githubusercontent.com/427398/107856896-6729a980-6df9-11eb-87d7-3392e1fa3f4c.png">

Colours are also wrong

**Comment by PedroFonsecaDEV** [comment]
Working on this.
