### ISSUE TITLE
Creating a Post microservice

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#1735]
**What would you like to be added**:

Telescope is going to undergo a huge overhaul with the backend as we're going to convert it to operate using microservices. As part of that effort, we should have a microservice to handle the posts. 

**Why would you like this to be added**:

A microservice to handle the posts would take away pressure from the feeds service we also plan on incorporating. The migration would be a little easier in that we have such operations currently running in our backend. It would also need to be updated to communicate with the user microservice work currently being done in #1642 

As per @humpd's vision of this microservice:

![Post Microservice](https://user-images.githubusercontent.com/16841702/107857674-d5706b00-6dfd-11eb-83af-55a0610bc718.png)

**Comment by humphd** [comment]
I think the way to think about this service is to begin small.  Here is my initial suggestion:

- Look at the existing code in https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/posts.js and tests in https://github.com/Seneca-CDOT/telescope/blob/master/test/posts.test.js
- Port that code over to a stand-alone service in `src/api/posts`
- Add Redis to `src/api/docker-compose.yml` similar to how it works in our root `docker-compose.yml`

We will need to figure out how to connect this to our new User service for feed info.  We won't be storing feeds in Redis anymore, so Feed and User info will have to come from the User service.  I'm not sure if we should do that in the Posts service (i.e., have it amalgamate that info into the responses) or let the client do calls to both services and aggregate the data there.  cc @raygervais for some architectural advice.

Later on I think we'll want to expand this service to include triggering indexing.

**Comment by manekenpix** [comment]
@HyperTHD I'm here if you need an extra hand. This sounds like a nice piece to work on.
