### ISSUE TITLE
Create a "post parsing/sync" microservice

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1736]
We are moving toward microservices for our back-end, and I want to refactor our current [Feed Parser](https://github.com/Seneca-CDOT/telescope/tree/master/src/backend/feed) into a separate service.

I don't know what to call this, some ideas:

- sync
- update
- parser

Whatever we call it, here is what it does:

- Connect the new User (#1642) and Posts (#1735) services via Redis
- Implements a Redis-backed job queue (we use https://github.com/OptimalBits/bull and there is also a new TypeScript port https://github.com/taskforcesh/bullmq that we could try)
- Manages getting feeds from the User service and creating jobs in the job queue
- Creates worker(s) to process jobs in the queue, parsing feeds and putting the data into Redis/Elasticsearch for use by the Posts service to consume.
- Keeps track of feeds that are invalid or causing errors, flags them in the User service
- Repeats the process of getting Feeds and Parsing them forever
- Provides an admin web dashboard of the job queue using Bull-Board https://github.com/vcapretz/bull-board

**Comment by c3ho** [comment]
Can I take this issue?

**Comment by humphd** [comment]
You can!  See `src/api/image` for a template to write yours.
