### ISSUE TITLE
Create a search microservice

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1737]
We are moving toward microservices for our back-end, and I want to refactor our current search routes into a separate service.

We have some existing code for this at https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/query.js and a working implementation for searching Posts and Authors.

To begin, let's duplicate what we have, but provide a better REST API, maybe something like this:

- `GET /search/user/?q=...&page=..&per_page=..` - allows searching for user's by the given `q` (i.e., query) string.  This probably should search their names (first, last, display, github username).  It should return paged results (e.g., `page` results with `per_page` results per page).  See the [GitHub Search API](https://docs.github.com/en/rest/reference/search#search-commits) for examples of what this might look like.

- `GET /search/post/?q=...&page=..&per_page=..` - similar idea to the above, but let's you query with post data (title, body of post) and returns results.  We might want to expand this API a bit to support things that Elastic can do, since it is a lot more powerful with it's query API.  That could happen later, though.

There are likely other things we can add search endpoints for, but would be a good start.

**Comment by raygervais** [comment]
I'd be interested in helping with this service, may not have time to fully implement but can def provide the foundation

**Comment by humphd** [comment]
Cool @raygervais, do what you can, and we'll take over from there.
