### ISSUE TITLE
Automate Docker build of Feed-Discovery service with GitHub Actions

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1743]
We're moving toward containerizing everything, and it might be time to consider using an [automated container build setup](https://github.com/docker/build-push-action) with Actions so we can build and push to a registry, then automate our deployments to pull for zero-downtime updates.

[GitHub has a new Docker registry](https://docs.github.com/en/actions/guides/publishing-docker-images), but it looks like the current Seneca-CDOT account [doesn't support it](https://github.com/orgs/Seneca-CDOT/packages)?  @ctyler do you know anything about CDOT's GitHub org being a "legacy" account?

![Screen Shot 2021-02-14 at 3 08 21 PM](https://user-images.githubusercontent.com/427398/107887781-7fbbc180-6ed6-11eb-8961-4f72a852fcaf.png)

I'm not sure if this is fixable or not, but it would be cool to use GitHub's storage for this.  I don't think there's another registry that will let us host all these containers for free?

**Comment by birtony** [comment]
I'd be keen to look into this

**Comment by humphd** [comment]
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by humphd** [comment]
See https://github.com/Seneca-CDOT/telescope/discussions/2683

**Comment by humphd** [comment]
I updated this to be about getting the feed-discovery service built and the image uploaded to the GitHub Package Registry.  Once we figure this out for feed-discovery, we can move onto the others.

**Comment by humphd** [comment]
Some useful background reading:

- [How to build and push to GitHub's Package Registry with GitHub Actions](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions)
- [Example of building multiple Docker images in a monorepo](https://ianbelcher.me/tech-blog/using-github-actions-and-package-registry-to-build-store-and-deploy-your-containers)
- [Discussion of how to re-use Docker code in GitHub Actions workflows with the build matrix](https://stackoverflow.com/questions/68608324/github-actions-multiple-workflows-for-parallel-image-build)

**Comment by humphd** [comment]
@TDDR has done great work getting us to the point of being able to do this.  However, I've discovered that the CDOT org isn't allowed to publish to the GitHub Package Registry

As I see it, our options are:

1. move Telescope to its own GitHub org that is totally open (no private repos).  This is going to cause a bit of churn while we get all kinds of things set up again with automation, permissions, connected services, etc.
2. [host our own Docker registry](https://docs.docker.com/registry/deploying/) on staging/production

I don't think there is another (free) option.  Docker Hub is not going to work for a Team, and Amazon ECR will cost.

What do people want to do?  I think we have to move toward hosting our images.  cc @manekenpix.

**Comment by sirinoks** [comment]
I'm moving the second part of this issue for 2.7. Looks like there are some decisions to be made.

**Comment by humphd** [comment]
I'll file a follow-up on what remains vs. holding this, since @TDDR's part is actually done and merged.

**Comment by humphd** [comment]
Filed #2801.
