### ISSUE TITLE
Explore using Portainer to allow admins to manage docker containers

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1744]
Our current admin setup isn't great.  You have to have shell access to physical machines to work with the setup.  We should provide a web-based way to do things, and one option is [Portainer](https://www.portainer.io/)

![image](https://user-images.githubusercontent.com/427398/107893862-81e44700-6efb-11eb-993e-6c880eebc5f5.png)

Portainer would run inside our docker instance on staging/prod, and you'd have to authenticate to get in.  Then you could manage the containers running there over the web.

Even locally this might be useful for people to understand what Docker is doing.

**Comment by manekenpix** [comment]
I'd like to help with this one.

**Comment by manekenpix** [comment]
I'm going to do some testing using the [traefik-portainer documentation](https://documentation.portainer.io/v2.0/ad/traefik/rp-traefik/). Any help is welcomed (I've never done this before).
