### ISSUE TITLE
Styling is not applied in all areas when in dark mode

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#1750]
When on the Search Page and in Dark Mode, some of the text don't have their font color changed to white so they're not visible to the user. Also, the login styling that was merged in #1703 doesn't seem to apply when in dark mode.

![Image example](https://user-images.githubusercontent.com/16841702/108112112-a2c7ac00-7063-11eb-9d74-6628e7d96367.png)

**Comment by PedroFonsecaDEV** [comment]
This should be addressed to land on 1.7 since we are going to launch it at production.

**Comment by PedroFonsecaDEV** [comment]
This is a band-aid to avoid shipping this bug on production: https://github.com/Seneca-CDOT/telescope/pull/1786
The PR doesn’t close this issue.

**Comment by HyperTHD** [comment]
Closing this issue in favor of #2003, since the new dark mode theme is applied here instead.
