### ISSUE TITLE
Author name links to feed instead of blog url

### ISSUE THREAD

**Issue by yuanLeeMidori** [Seneca-CDOT/telescope#1753]
**What happened**:

When user clicks author name on post title, it should link to author's blog itself, not author's blog feed.
![image](https://user-images.githubusercontent.com/50813726/108123640-2ab5b200-7074-11eb-850b-1d54de8bb40b.png)

After clicking author name,
![image](https://user-images.githubusercontent.com/50813726/108123872-808a5a00-7074-11eb-8b5b-ce7e8340a527.png)

**What should have happened**:
But it should be something like this,
![image](https://user-images.githubusercontent.com/50813726/108123983-a879bd80-7074-11eb-87d7-bc1b5d788f79.png)

and after clicking author name, it should link to author's blog like this,

![image](https://user-images.githubusercontent.com/50813726/108124080-c3e4c880-7074-11eb-9d8f-54ccbde932f0.png)

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS: Linux mint
- Browser: Firefox

**Comment by DukeManh** [comment]
Is anyone working on this, the problem is that the author's feed URL lives under `post.feed.link` not `post.feed.url`. It's only one word change really.

**Comment by HyperTHD** [comment]
All yours @DukeManh

**Comment by DukeManh** [comment]
#1755
