### ISSUE TITLE
Login Tab color is not correct when switching to dark mode

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#1775]
**What happened**:
When you switch to dark mode, the color of Login Tab changes to black 
**What should have happened**:
It should be the same color as other tabs
**How to reproduce it (as precise as possible)**:
Click on the theme toggle button to switch the theme
![image](https://user-images.githubusercontent.com/55034244/108366842-d0793600-71c6-11eb-96c0-e5e9e233d50c.png)

**Comment by HyperTHD** [comment]
Duplicate of #1750, please close
