### ISSUE TITLE
[UI 2.0] Telescope logo in README.md needs to be updated

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#1779]
When we're ready to start implementing the new UI, the logo icon in [README.md](https://github.com/Seneca-CDOT/telescope/blob/master/README.md) needs to be updated :)

**Comment by sumitk63** [comment]
Hey i would like to do that. Can you please direct me where can i find the new icon that needs to be placed instead of the old one.

**Comment by chrispinkney** [comment]
Looks like it's already there, which is weird because we were just talking a few hours ago how it needs to be fixed.

**Comment by manekenpix** [comment]
Can we close this then?

This is when the logo was changed (I think it's a push to master without PR?): [commit bafa23b](https://github.com/Seneca-CDOT/telescope/commit/bafa23b3e02eb14ef5e3aa7f210e2668cef93398)

**Comment by cindyledev** [comment]
Yeah, closing this because it's already done. Sorry @sumitk63 :(
