### ISSUE TITLE
Delete src/frontend/gatsby

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1790]
In #1789 we are moving to the next front-end instead of gastby.  Once that's working well, let's dump the src/frontend/gatsby dir and only have src/web as our single front-end.

We also need to remove all other scripts or calls to Gatsby in our tree:

- readme
- docs
- package.json scripts
- etc

**Comment by humphd** [comment]
Let's also tag the commit prior to removing this as something we can recover easily, `gatsby-last-known-good` or something.

**Comment by humphd** [comment]
TODO:

- We need to update `docs/gatsbyjs.md`, `docs/aws-cloud9.md` to reflect front-end changes for next

**Comment by humphd** [comment]
I created a tag `goodbye-gatsby` for the last known good version of Gatsby.

**Comment by humphd** [comment]
Filed #1797 to clean up the paths.

**Comment by tonyvugithub** [comment]
I think @manekenpix has already deleted the frontend folder including Gatsby and move Next to the web folder in #1800 . Hence closed this
