### ISSUE TITLE
Handling with inline img 

### ISSUE THREAD

**Issue by yuanLeeMidori** [Seneca-CDOT/telescope#1791]
**What happened**:
Currently, in order to center the img in blog post, we set img element to `block`. However, this is gonna affect those inline img (raw, but still exist).
Related PRs and issues: 
#1370
#1783
#1373
#1412

**What should have happened**:

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by UsernameHasBeenChanged100Times** [comment]
@yuanLeeMidori  If I use this approach

![Screen Shot 2021-02-23 at 1 47 26 PM](https://user-images.githubusercontent.com/10421864/108892373-c77cd000-75dd-11eb-9fef-af922e92ef6b.jpg)

the result will be like:

![Screen Shot 2021-02-23 at 1 45 26 PM](https://user-images.githubusercontent.com/10421864/108892400-d1063800-75dd-11eb-8855-e97559865821.jpg)

HOWEVER
for any post from 'blogspot', all images will be 32px as well, while other posts (not from blogspot) are okay.
