### ISSUE TITLE
Release GitHub Action doesn't produce Changelog

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1794]
https://github.com/Seneca-CDOT/telescope/releases/tag/1.7.0 was our most recent release, and it has zero changelog info.  We should figure out why.

**Comment by birtony** [comment]
Since the existing changelog generator was leaving some of our commits/PRs out of scope in the first place, we should look for alternatives. This seems to be a more popular and more configurable option: https://github.com/marketplace/actions/release-changelog-builder 
CC @humphd @manekenpix

**Comment by birtony** [comment]
In regards to our current changelog generator, [this issue](https://github.com/ScottBrenner/generate-changelog-action/issues/16) seems to be the reason. However, I am not why it worked the previous time 🤔
