### ISSUE TITLE
https://telescope.cdot.systems/search and https://telescope.cdot.systems/about return 404 on prod

### ISSUE THREAD

**Issue by chrispinkney** [Seneca-CDOT/telescope#1795]
**What happened**:
See title:  visiting [https://telescope.cdot.systems/search](https://telescope.cdot.systems/search) and [https://telescope.cdot.systems/about](https://telescope.cdot.systems/about) return 404 on prod

Update: You can reach `/search` and `/about` via `/` then If you refresh the page you receive a 404 too.  

**What should have happened**:
The pages should have been compiled and returned rather than a 404 error being returned instead.

**How to reproduce it (as precise as possible)**:
Visit [https://telescope.cdot.systems/search](https://telescope.cdot.systems/search) or [https://telescope.cdot.systems/about](https://telescope.cdot.systems/about)

**Anything else we need to know?**:
See [this](https://nextjs.org/docs/advanced-features/custom-server), which may or may not fix our issue. Could be a temporary fix until we figure out how to get this working on nginx.

**Environment**:
- OS: Windows 10 20H2
- Browser: Firefox 85.0.2

cc @manekenpix @humphd

**Comment by humphd** [comment]
Looks like infinite redirects

<img width="1276" alt="Screen Shot 2021-02-19 at 5 51 00 PM" src="https://user-images.githubusercontent.com/427398/108570096-1a534080-72db-11eb-88f5-c91961a915a4.png">

**Comment by chrispinkney** [comment]
Looks like navigating to http://localhost:8000/about in dev works just fine. Not sure if this is an issue that occurs when generating our production build or something related to nginx/docker/etc.

**Comment by humphd** [comment]
Assuming this is the issue, probably we need to get our nginx.conf fixed to work with next.js vs. Gatsby.  I think we thought it would work the same, but maybe not.

Some people use the next.js server and proxy it via nginx, https://steveholgado.com/nginx-for-nextjs/.  We could do that if we find the routing can't be done other ways, but it would be nice to stay totally static.

**Comment by izhuravlev** [comment]
I'll work on it
