### ISSUE TITLE
[UI 2.0] Search Page - Design Reference

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1804]
**What would you like to be added**:
Search Page UI 2.0

### DESKTOP:
![Search Desktop](https://user-images.githubusercontent.com/60857409/108666981-6acac980-74a6-11eb-8ab1-a721f0e246f6.png)

### MOBILE:
![Search_Mobile](https://user-images.githubusercontent.com/60857409/108667182-a1a0df80-74a6-11eb-9788-419a0baf6185.png)

| PR 	| MERGED 	| ISSUE 	| ASSIGNED 	|
|----	|--------	|-------	|----------	|
|     <ul><li>[x] </li></ul>	|   <ul><li>[x] </li></ul>      	|     [SearchInput](https://github.com/Seneca-CDOT/telescope/issues/1805)  	|     @huynguyez    	|
|     <ul><li>[x] </li></ul>	|   <ul><li>[x] </li></ul>      	|     [SearchResult](https://github.com/Seneca-CDOT/telescope/issues/1809)  	|     NAME   	|
|     <ul><li>[x] </li></ul>	|   <ul><li>[x] </li></ul>      	|     [SearchBar](https://github.com/Seneca-CDOT/telescope/issues/1806)  	|    @huynguyez    	|
|     <ul><li>[x] </li></ul>	|   <ul><li>[x] </li></ul>      	|     [SearchHelper](https://github.com/Seneca-CDOT/telescope/issues/1807)  	|     @rjayroso    	|
|     <ul><li>[x] </li></ul>	|   <ul><li>[x] </li></ul>      	|     [SearchPage](https://github.com/Seneca-CDOT/telescope/issues/1808)  	|    @huynguyez    	|

**Comment by humphd** [comment]
I'm not sure about the huge `i` icon for this design.  Can we keep iterating?

**Comment by PedroFonsecaDEV** [comment]
Sure. That is the idea.

**Comment by HyperTHD** [comment]
Gonna second the i logo, that thing is probably best left out. The mobile design looks great to me otherwise, with the only serious nit-pick being that we could align the author/post input select with the telescope icon.

Desktop design also needs that i logo removed. You can then modify the position of the help text by centering it below the text field where `Enter your Search here` is displayed. I'm curious as to what your commands in the search help do, but that's irrelevant to this issue.

**Comment by PedroFonsecaDEV** [comment]
@humphd @HyperTHD maybe display just the info text without the 'i'.

**Comment by HyperTHD** [comment]
Works for me, honestly.

**Comment by UsernameHasBeenChanged100Times** [comment]
@PedroFonsecaDEV  on mobile design just replace the search icon with a 'X' (to clear text in the search input)
desktop design is good! just change some border color I think it's good 

![abcxyz](https://user-images.githubusercontent.com/10421864/108652394-043bb080-7492-11eb-90c3-e3723ab72d19.jpg)

**Comment by PedroFonsecaDEV** [comment]
@humphd @UsernameHasBeenChanged100Times @HyperTHD 
Please check the updated issue description. 

@UsernameHasBeenChanged100Times I'm available on teams if you want to.

**Comment by HyperTHD** [comment]
@PedroFonsecaDEV Mobile looks good to me.

For desktop, you can maybe fix the margin of the text so it's moved a little bit up. Otherwise, looks good to me

**Comment by PedroFonsecaDEV** [comment]
DONE
