### ISSUE TITLE
[UI 2.0] Search Page - SearchHelper

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1807]
**What would you like to be added**:
For reference, please check #1804 
File can be found here: `src/frontend/next/src/components/SearchHelp.tsx`

**Comment by rjayroso** [comment]
Mind if I take over this one?

**Comment by PedroFonsecaDEV** [comment]
Sure go for it!
Please assign yourself to the issue. 
Thanks.
