### ISSUE TITLE
Run CircelCI on windows and mac environment

### ISSUE THREAD

**Issue by sukhbeersingh** [Seneca-CDOT/telescope#181]
The current config file only runs CI on a linux environment. We should add support for running the integrations on windows and mac environments.

**Comment by robertbegna** [comment]
I'll try working on this

**Comment by humphd** [comment]
Looking at https://circleci.com/docs/2.0/configuration-reference/ I can see two examples:

1. Windows - https://circleci.com/docs/2.0/configuration-reference/#example-usage-3
2. macOS - https://circleci.com/docs/2.0/configuration-reference/#example-usage-2

I think if we follow these configs, it might get us close.

@sukhbeersingh I know you worked on the original code, and I spoke with @robertbegna in the lab.  I think he'd value having someone who he can talk to about this.  Let's discuss our research here in the Issue as we go.

**Comment by sukhbeersingh** [comment]
Surely, @robertbegna let me know if you need any help. If you look [here](https://circleci.com/docs/2.0/hello-world-windows/), CircleCI has cmd, poweshell and GNU bash. You can specify whichever one you want to make your executor and then you can run commands of that shell. I would lean more towards bash. 
Also check the list of software that is pre-installed with the windows env(Node is one of them).

**Comment by robertbegna** [comment]
@sukhbeersingh 
Hi, could you take a look at my most recent commit, i'm trying to emulate what you did with the linux build, but the windows build fails because of this error "Expected Linebreaks to be 'LF' but found 'CRLF'. Also the docker images, will they be needws in the windows build and if so how can I add it to the build? Because reading through the documentation, windows executors so far only have one image win/vs2019.  Tbh, I've never used circleCI, before and I'm just trying to make sense of everything, so some help would be greatly appreciated.

**Comment by manekenpix** [comment]
@robertbegna what's `0` here?
```json
"rules": {
    "linebreak-style": 0
}
```

**Comment by humphd** [comment]
I don't have much Circle CI experience, so I'll defer to @sukhbeersingh.  But one note for you @robertbegna.  I had to fix failing tests on Travis CI last night for macOS and Windows.  [Some of what I did might help you](https://github.com/Seneca-CDOT/telescope/blob/master/.travis.yml).

The relavent bits are these:

1. We have a [hack to deal with CRLF vs. LF on Windows](https://github.com/Seneca-CDOT/telescope/blob/master/.travis.yml#L20-L25) by overriding how git does the checkout.  It's gross, and we should be able to dump it when @vitokhangnguyen does his Prettier fix, see #96.
1. On Windows I struggled a lot to figure out the right way to do Redis.  [In the end I used the `choco` package manger to install it](https://github.com/Seneca-CDOT/telescope/blob/master/.travis.yml#L38-L41), then ran the commands necessary to install and run it as a service.

I tried to get Docker builds of Redis working on all 3 platforms, but couldn't find one that worked on Windows (amd 64 Docker image for Windows vs Linux).  Someone might know how to do it, but I couldn't find the right thing.  cc @Reza-Rajabi and @manekenpix who have been working on the Redis docker stuff.  In an ideal world, we'd use Docker for all our CI for Redis, and stop having to do all these manual package installations per repository.

**Comment by Reza-Rajabi** [comment]
@humphd based on Docker [website](https://www.docker.com/blog/docker-official-images-now-multi-platform/) their official images are multiplatform (platform aware). Also, In the [Docker Hub](https://hub.docker.com/_/redis?tab=tags) I select `Windows x86-64 (latest)` and the command to pull the image is the same as all other platforms.

**Comment by humphd** [comment]
@Reza-Rajabi I couldn't get it to work on Travis, but it's quite possible that I'm just doing it wrong.  Maybe we should file a new issue and see if we can switch all Travis CI to use Docker for Redis. Someone can experiment with getting that to work.  Meanwhile, we can use the native installs it currently uses.

**Comment by Reza-Rajabi** [comment]
@humphd I make a new issue to address that.

**Comment by Reza-Rajabi** [comment]
@humphd If the issue that I made is not what you are looking for please feel free to delete or edit it or ask me to do so.

**Comment by humphd** [comment]
I think it's good.  I added a comment with some more details from my own attempts.

**Comment by humphd** [comment]
I'm going to close for now, since we have all 3 on Travis, and CircleCI has been a bit of a pain to get working.  If someone wants to do this again, please file a new issue.
