### ISSUE TITLE
Consider allowing spotify iframes

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1815]
I notice that @PedroFonsecaDEV's [recent post](https://medium.com/@pedrofonsecadev/telescope-note-feb-22-2021-8601dfbaa1f0) includes a Spotify album iframe embed, which we remove in our sanitizer.

<img width="1479" alt="Screen Shot 2021-02-22 at 11 03 18 AM" src="https://user-images.githubusercontent.com/427398/108734744-c07e9080-74fd-11eb-8fb5-083e84109803.png">

The original HTML has this:

```html
<iframe scrolling="no" id="player" src="https://open.spotify.com/embed/album/21wMUhXhWLew2zsWQhlYEM?referrer=https%3A%2F%2Fmedium.com%2F%40pedrofonsecadev%2Ftelescope-note-feb-22-2021-8601dfbaa1f0" allowfullscreen="true" frameborder="0"></iframe>
```

And we'll strip it due to this whitelist: https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/html/sanitize.js#L50

I think adding it in would be OK, since obviously students want to be able to share music with each other.

**Comment by HyperTHD** [comment]
Gonna do this and update tests
