### ISSUE TITLE
Run Travis CI on windows and mac environment

### ISSUE THREAD

**Issue by sukhbeersingh** [Seneca-CDOT/telescope#182]
The current [travis config](https://github.com/Seneca-CDOT/telescope/blob/master/.travis.yml) file only runs CI on a linux environment. We should add support for running the integrations on windows and mac environments.

**Comment by Manan311** [comment]
Hey, @sukhbeersingh I could work on adding support for window and mac environments for the current Travis config.

**Comment by Manan311** [comment]
Quick question, is there any specific version you need for mac? By default, Travis ci uses macOS 10.13 and Xcode 9.4.1 but there are other versions it also supports. The list can be found [here](https://docs.travis-ci.com/user/reference/osx/). For Windows Server, version 1803 is currently the only one supported.

**Comment by Manan311** [comment]
I am going to add the default configuration for mac and add the windows config and send in a pull request. If you want this changed let me know and I will change it.

**Comment by sukhbeersingh** [comment]
Lets go with the defaults. Thanks for picking this up.

**Comment by Manan311** [comment]
PR# [212](https://github.com/Seneca-CDOT/telescope/pull/212)

So for the mac and windows, config am I suppose to start the Redis server as well or just have them installed? When I have the servers running it waits for a connection until Travis times out and kills the test.

**Comment by humphd** [comment]
Our tests connect to a running Redis instance, yes.

**Comment by Manan311** [comment]
<img width="865" alt="Screen Shot 2019-11-15 at 10 40 08 AM" src="https://user-images.githubusercontent.com/50086671/68956356-e1522500-0795-11ea-9540-1cdfbcb9f389.png">
 Once I start the Redis server, the above screenshot, it gets initialized and is in a state to accept a connection but I am not too sure how the connection will actually be set. Right now I am just trying to make mac os run, so to establish the connection would it be the same way as running "npm start" once the server has started?

**Comment by humphd** [comment]
When we do `npm test` it will create a connection and then close it.
