### ISSUE TITLE
Create a Stats microservice

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#1829]
Create a microservice to deliver stats related to Telescope's users and posts.

There's already code in the repo for this task, so it only needs to be part of a microservice.

**NOTE**
This piece will have to be tested against the current backend until the `Post` microservice is ready.

**Comment by manekenpix** [comment]
Also, this piece could be part of the `Post` microservices, so we can discuss if it's needed or not/

**Comment by HyperTHD** [comment]
#1838 is up to deal with the Post microservice. I'm down to add this to the Post microservice if it's doable. Though if it also needs to get stats for Telescope's users, I'd prefer to make it it's own microservice.

**Comment by manekenpix** [comment]
Blocked until #1908 is implemented.

**Comment by humphd** [comment]
I really wonder if the right way to do this is via elastic vs. redis.  I think it's better suited to tracking, extracting, and aggregating stats for us, though I haven't done a lot of that.

**Comment by manekenpix** [comment]
I'll give it a go using ES. This [token_count](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/token-count.html) seems like the right thing to use for this case.

**Comment by humphd** [comment]
NOTE: that's an old version of ES, you should select 7.x or later.

Also, https://www.elastic.co/guide/en/elasticsearch/reference/7.12/search-aggregations-metrics.html is interesting.

**Comment by manekenpix** [comment]
After all the recent changes, I'm not sure about how to work on this now. Maybe it doesn't need to be its own microservice anymore, and it can be part of the status microservice. Maybe an endpoint serving posts/feeds data that can be displayed in the hero banner (original implementation), or maybe all this data can be displayed in the new dashboard, along with all the repo data.

cc: @humphd @chrispinkney @AmasiaNalbandian

**Comment by humphd** [comment]
Agreed. I think it can get distributed across other services, and the bulk of it can live in status.  Want to close it?

**Comment by manekenpix** [comment]
Yes, I'll close it then.
