### ISSUE TITLE
Make pages height at least 100% viewport height

### ISSUE THREAD

**Issue by izhuravlev** [Seneca-CDOT/telescope#1835]
**What would you like to be added**:
When trying to fix #1750, I found out that the Search page height is not 100% of the viewport. 
But when I tried to fix this, I realized that it breaks how all of our pages look - so this needed a separate issue.

![image](https://user-images.githubusercontent.com/36719387/109317484-cf4aa780-785d-11eb-9db9-a52c959500a2.png)

**Why would you like this to be added**:
This will be vital in implementing DarkMode, as we would want to change the background colour to black, and it will not be possible as small pages (like search) don't cover the entire height of the screen.

In the PR that will solve this issue, I will set the height of the page to 100% and fix the appearance of all pages that might get broken.

**Comment by UsernameHasBeenChanged100Times** [comment]
I fixed this in https://github.com/Seneca-CDOT/telescope/pull/1832

**Comment by izhuravlev** [comment]
@UsernameHasBeenChanged100Times Oh, good job! 
Let's get your PR merged then - I'll do a review.

Closing this issue due to redundancy.
