### ISSUE TITLE
The about page only shows a certain number of contributors.

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#1841]
**What happened**:
The contribution hook only fetches 29 contributors. 
**What should have happened**:
Telescope right now has 111 contributors

**Comment by humphd** [comment]
I bet the default page-size is 30, which we could likely adjust, but eventually we'll hit this again.  We might need do do some of this on the server-side.

**Comment by DukeManh** [comment]
The default perPage is indeed 30.
