### ISSUE TITLE
Temporary Avatars for the new UI. 

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1855]
**What would you like to be added**:
We could use something like:
~https://evergreen.segment.com/components/avatar/~
https://material-ui.com/components/avatars/#avatar
To generate temporary avatars for our new UI while we wait for GitHub integration.

**Comment by humphd** [comment]
MUI has this already, see https://material-ui.com/components/avatars/

**Comment by yuanLeeMidori** [comment]
@humphd I tried both evergreen and Mui's avatar component, Mui's avatar doesn't seem to generate the initials for avatar, they just provide a circle, the style and the font size, initials, will be handled by ourselves.
But for evergreen, the avatar component also generate the initials for us.

Do we still use Mui avatar? Just curious.

**Comment by humphd** [comment]
That's too bad about MUI not doing the letters.  Here's what Evergreen does to get the initials: https://github.com/segmentio/evergreen/blob/1d0927098597f7cb92461d4e8dfe529e34d1d80c/src/avatar/src/utils/getInitials.js and how they use them https://github.com/segmentio/evergreen/blob/1d0927098597f7cb92461d4e8dfe529e34d1d80c/src/avatar/src/Avatar.js.  Maybe you can hack something like that into our code to use MUI's component, but supply the initials if we don't have an image src?

**Comment by yuanLeeMidori** [comment]
I'm using similar js to get initial with Mui avatar,
![Screenshot_2021-03-10 Telescope(1)](https://user-images.githubusercontent.com/50813726/110827566-31df7280-8264-11eb-8280-39ce01b09e46.png)

![Screen Shot 2021-03-10 at 20 27 16](https://user-images.githubusercontent.com/50813726/110827541-2be99180-8264-11eb-90ff-9fa3f5173a1a.png)

Should I make the component to check if we have img src first, and if we don't have, we apply initials? Or wait till we introduce the img src and only do initials for now? I'm not sure that we have img src for author in our current db.

**Comment by humphd** [comment]
I would make our "Avatar" component take a name and image src URL.  If the latter is missing, fallback to the initials, yes.

This way it will work for every case.

**Comment by yuanLeeMidori** [comment]
`<Avatar name={post.feed.author} img="src" />`

You mean something like this, and it display img src first if it exist; if it doesn't exist, show initials from name value?

**Comment by humphd** [comment]
Yeah, it should be able to handle having an image prop or not (we don't have any data for this yet, but we will...)

```jsx
<Avatar name={post.feed.author} />
...
<Avatar name={post.feed.author} image={user.profileUrl} />
```
