### ISSUE TITLE
UI 2.0 Change all fonts from Roboto to Spartan. 

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1856]
**What would you like to be added**:
In our new UI, we are going to use the font `Spartan`. But our App still uses `Roboto`. 
**Why would you like this to be added**:

**Comment by PedroFonsecaDEV** [comment]
cc @tonyvugithub 
Maybe we can fix this using the MUI theme. 
Please check: https://blog.logrocket.com/3-ways-to-add-custom-fonts-to-your-material-ui-project/

**Comment by tonyvugithub** [comment]
@PedroFonsecaDEV yes we can do that with static font or font-face. No issue.

**Comment by PedroFonsecaDEV** [comment]
@tonyvugithub do you wanna fire a PR for us?
