### ISSUE TITLE
Header bleed through bug [safari]

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1866]
The new header has a z-index/background transparency bug that I hit in Safari today (might happen on other browsers too):

![header-bug](https://user-images.githubusercontent.com/427398/110008205-7067b100-7ce9-11eb-9394-38ada6bc7072.gif)

To reproduce this, you have to narrow the window so that the author component info is centered at the top.

Another bug I notice with this component is that the vertical alignment of the 3 elements (avatar, name, date) aren't aligned.

cc @DukeManh, @PedroFonsecaDEV

**Comment by humphd** [comment]
cc @huynguyez

**Comment by huynguyez** [comment]
Same on Chrome

**Comment by DukeManh** [comment]
I think this is supposed to be fixed in the mobile PR that @PedroFonsecaDEV is working on?

**Comment by PedroFonsecaDEV** [comment]
@humphd yes. We still don't have the mobile version.

**Comment by humphd** [comment]
Let's leave this open until we have a a PR that fixes it, so we don't lose it.
