### ISSUE TITLE
[auth] Auth JWT Passport strategy should connect to User service

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1869]
There's a big commented-out block of code in src/api/auth/src/authorization.js showing where we need to query the User service for info about a Seneca SSO user account on login.  This was done in #1796, but couldn't be completed until the User service was added (cc @chrispinkney), so we need to loop back.

**Comment by humphd** [comment]
We also need to add more claims for this user to the JWT, and include roles.

**Comment by chrispinkney** [comment]
Ugh, passport... *shudders*

Anyway, User is finally up for review and should be merged soonish so I imagine this can start being worked on relatively soon_ish_ @izhuravlev @HyperTHD

**Comment by izhuravlev** [comment]
I believe @chrispinkney's User is done, so I will look deeper into this

**Comment by humphd** [comment]
This is no longer an issue, we have this working in the SSO service with Supabase.
