### ISSUE TITLE
Switch from JSDOM to Puppeteer 

### ISSUE THREAD

**Issue by PavanKKamra** [Seneca-CDOT/telescope#187]
JSOM does not support innetText. After testing, innerHTML and textContent works fine but innerText will return 'undefined'. Furthermore, JSDOM does not support new line when converting from HTML to text. We need to switch to a full browser via Puppeteer.

**Comment by humphd** [comment]
Doing this should involve the following:

```js
const puppeteer = require('puppeteer');

// ... in your function, do something like this:
  const browser = await puppeteer.launch(); // TODO: can we reuse this instance?
  const page = await browser.newPage();
```

Once you have a `page` object, you can do something with `page.setContent()`, see [API docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetcontenthtml-options).

Then, you should be able to get the `innerHTML` back out using something like this:

```js
page.$eval(selector, (element) => element.innerHTML
// or
const text = await page.evaluate(() => document.querySelector(selector).innerHTML);
```

I'm not sure what you should use for your `selector`.  It will depend on what you inject into the page from the post's content.  Maybe we should wrap it in a container, or maybe we can do something with a DocumentFragment like we do now?

When you're done, clean up:

```js
browser.close();
```

I see that @giatuongtran9 and @PavanKKamra are both assigned to this.  Do you two want to collaborate on this, and also doing tests?

**Comment by PavanKKamra** [comment]
Yes, we want to collaborate on this. We haven't discussed it fully, however, we were thinking that @giatuongtran9 does the testing portion.

**Comment by humphd** [comment]
Great, sounds good.

**Comment by giatuongtran9** [comment]
@humphd I have noticed that in ```wiki-feed-parser.js``` function ```getData()``` is similar to what @PavanKKamra has done in ```text-parser.js```. Can you check on that?

**Comment by humphd** [comment]
@giatuongtran9 yes, you two and @cryolis had to solve essentially the same problem.

It would be good to refactor to only have a single "html to text" parser.  I'll file another issue, and someone can work on refactoring it.

**Comment by humphd** [comment]
Filed #270 for the refactor.

**Comment by giatuongtran9** [comment]
I can do the refactor thing and we can discuss on switching to puppeteer or keeping jsdom since @cryolis works fine with it
