### ISSUE TITLE
Audit auth Dockerfile and use as template for all services

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1873]
I tried to make the Dockerfile for the auth service a mult-stage build, but I'm not sure if I've done it all correctly.  I'd like to get some eyes on this, and improve it however we think makes sense, then use that as a template to improve/write all the others.  cc @raygervais.

**Comment by TDDR** [comment]
Related discussion  #2683

**Comment by cindyledev** [comment]
Resolved in #2748. New issue opened to address creating Dockerfile template for all microservices in #2803
