### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by cagomezr** [Seneca-CDOT/telescope#189]
With the new Html designed we have a few issues with font size on mobile menu, and on mobile  there is mild issues with area of access in iphones and  small phones, so fixing that issue

**Comment by cindyledev** [comment]
Yeah, we should make it responsive.

**Comment by humphd** [comment]
Font sizes were fixed.  We should file another Issue on making this responsive and work well on mobile in general.

@cagomezr, @cindyledev can one of you file that, please?
