### ISSUE TITLE
Upgrade Elasticsearch

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1897]
I'm working on our Docker-Compose setup, and notice that we're using outdated versions of Elasticsearch:

- development: 7.9.3
- production: 7.5.0

The current version is [7.11.1](https://hub.docker.com/_/elasticsearch).

**Comment by humphd** [comment]
There are docs for upgrading, https://www.elastic.co/guide/en/elasticsearch/reference/7.11/rolling-upgrades.html, but I bet we could just do it and dump our data if necessary (e.g., re-index).

**Comment by humphd** [comment]
This is now at 7.14.2.  We need to update https://github.com/Seneca-CDOT/telescope/blob/master/docker/docker-compose.yml#L273.

**Comment by humphd** [comment]
Related: #2597

**Comment by hphan9** [comment]
@humphd , so we need to downgrade the version 7.14.2 to 6.8.21 or upgrade it to 7.16.1 .  I saw the newest version is 7.16.0 https://www.elastic.co/guide/en/elasticsearch/reference/7.16/release-notes-7.16.0.html

**Comment by humphd** [comment]
I suspect we'll see a 7.16.1 shipped very soon.
