### ISSUE TITLE
Implement a reading time feature for the blog post

### ISSUE THREAD

**Issue by birtony** [Seneca-CDOT/telescope#19]

**Comment by humphd** [comment]
https://www.npmjs.com/package/reading-time probably does what we want.

**Comment by Reza-Rajabi** [comment]
@birtony This issue already mentioned in #7 . Please consider closing this issue. If you decided to close this issue, that would be greate to address the @humphd 's above comment somewhere on #7 .

**Comment by birtony** [comment]
@Reza-Rajabi I believe that #7 is quite a generic issue, and it might be useful for us to split it into smaller parts to work on. However, thank you for referring it here, as both of them are definitely related.

**Comment by cyh0968** [comment]
@birtony For this issue, @humphd recommended a reading-time library that calculates not only reading time but also word count. If we can get the information about the level of vocabulary from a text, I think we can get a more precise reading time. Plus, if we can get the information for a reader's mother tongue, I guess we can get more precise reading time based on a user's language group or language distance from English. If you don't mind, I want to do this part.

**Comment by birtony** [comment]
@cyh0968 sure, sounds good! I have already started working on the word counter in https://github.com/Seneca-CDOT/telescope/pull/78, so now I am not sure if need it anymore?

**Comment by cyh0968** [comment]
reading time = word count / the number of word per min
reading level = reading difficulty (the level of writing level) x reading time

I think they are highly coupled together, what about making them as one class? such as basic analysis?

**Comment by humphd** [comment]
@cyh0968 they can be combined eventually, but we have two people approaching the problem at once, and two pull requests with tests.  Let's take both, and then refactor our code to include both tests, but share the implementation.
