### ISSUE TITLE
SearchBar re-design

### ISSUE THREAD

**Issue by huyxgit** [Seneca-CDOT/telescope#1912]
Since I found UI problem with the current searchbar, I suggest a new design for it.

Any suggestion?
Thanks.

**Comment by humphd** [comment]
I like this.  Question: what does clicking "Advanced Search" do?  Can you include that?

Also, I think the language should be:

1. "Search in Posts"
2. "Search by Author"

**Comment by huynguyez** [comment]
@humphd as my idea, the SearchHelp will not be visible at first. People don't use it often, only 'power user' actually use, so it's better to hide it by default than seeing a big (i) or bunch of instruction texts letting people know how to search.

Only when user hit "Advanced search", it can either:
- Redirect user to a separate page for advanced search.
- Start to show SearchHelp as old design.

**Comment by PedroFonsecaDEV** [comment]
I really like this design. 
@huynguyez go for it and land it in 1.9?

**Comment by humphd** [comment]
Agreed, let's do this.  Great work @huynguyez.

**Comment by humphd** [comment]
@huynguyez what's happening with this?  I'd love to see this get in soon.

**Comment by huynguyez** [comment]
@humphd  Still trying different ways to make it work better, probably I will push it before Friday

**Comment by humphd** [comment]
Friday came and went, any updates?

**Comment by huynguyez** [comment]
@humphd  Sorry I messed up git Git again. just need to style it 
![Screen Shot 2021-03-20 at 2 57 41 PM](https://user-images.githubusercontent.com/10421864/111882615-df513500-898c-11eb-8c7e-dc6053e0ff4c.jpg)

**Comment by cindyledev** [comment]
Talking about it here https://github.com/Seneca-CDOT/telescope/issues/2894#issuecomment-1038293211

> I was playing around with TailwindCSS and mocked a Search page, we use Material UI but we can do something like this 

![2022-02-13 12_43_23-Window](https://user-images.githubusercontent.com/36822198/153767613-7405ecbc-e702-453e-8e14-9f87c35bdb9e.png)
