### ISSUE TITLE
Post's title letter-spacing issue on mobile

### ISSUE THREAD

**Issue by huynguyez** [Seneca-CDOT/telescope#1917]
![Screen Shot 2021-03-12 at 1 53 48 PM](https://user-images.githubusercontent.com/10421864/110985542-93721080-833a-11eb-858d-0658f778c3ef.jpg)

**Comment by PedroFonsecaDEV** [comment]
@huynguyez I think this only happens in devtools.
Could you please confirm if the issue persists on your phone? 
On Iphone8 is working well.

**Comment by huynguyez** [comment]
@PedroFonsecaDEV What build version you trying to run? I run the version on https://telescope-dusky.now.sh/

I tried on all 3 phones I have (Samsung S5 + S10 plus, Blackberry Key2) and it's still there. Am I running the wrong one?

**Comment by PedroFonsecaDEV** [comment]
@huynguyez 
I'm using our staging and production. 

![image](https://user-images.githubusercontent.com/60857409/111558890-f3ffb400-8765-11eb-8a7c-391976872a49.png)

Could you please provide screenshots ?

**Comment by yuanLeeMidori** [comment]
fix by PR #2006
