### ISSUE TITLE
Remove this scroll-down button on Banner

### ISSUE THREAD

**Issue by huynguyez** [Seneca-CDOT/telescope#1921]
Use something like scroll-snap in css (if possible in Next?).
Similar to https://www.tesla.com at the moment.

![Screen Shot 2021-03-12 at 2 11 57 PM](https://user-images.githubusercontent.com/10421864/110987443-15fbcf80-833d-11eb-99c8-0f24bbef4181.jpg)

**Comment by DukeManh** [comment]
I like this idea. Scroll-snap can be achieved in CSS, so it should always work in supported browsers.

**Comment by huynguyez** [comment]
> I like this idea. Scroll-snap can be achieved in CSS, so it should always work in supported browsers.

@DukeManh Yes, We don't wanna see a half banner & a half blog post at the same time. 
Also, this icon looks just so awkward to me in term of modern design, hard to adjust its position -> keep jumping up/down over the text. So try to get rid of it will make better look & experience on both desktop & mobile

**Comment by DukeManh** [comment]
@huynguyez, after playing around with scroll snap, I don't think scroll snap would work well for our page layout. You can see what I mean here https://codepen.io/Ducmanhbui/pen/oNYreYx. If you can come up with a workaround, that'll be great otherwise we might have to close this issue.

**Comment by PedroFonsecaDEV** [comment]
Let's keep the button, but let's try to add the scroll snap on our page. 
Scroll Snap: https://github.com/Seneca-CDOT/telescope/issues/2042
