### ISSUE TITLE
Adding Prettier into Satellite 

### ISSUE THREAD

**Issue by Metropass** [Seneca-CDOT/telescope#1922]
**What would you like to be added**:
Add the Prettier module that we use for Telescope into Satellite
**Why would you like this to be added**:
Currently, we have no code formatter for Satellite. It would be quite nice if we had a similar approach for the project.

**Comment by chrispinkney** [comment]
Should this be opened in Satellite repo? Pretty simply too, just copy the `.vscode` folder I think.

**Comment by humphd** [comment]
I asked @Metropass to file it here, since I want to track all work related to Telescope in one place, even though the PR will go to Satellite.

**Comment by chrispinkney** [comment]
Got it! Sorry for the confusion.

**Comment by Metropass** [comment]
Closed, since this is resolved. 

Commit: 
https://github.com/Seneca-CDOT/satellite/commit/1d5def79b02b771d2277afe738c9074061e88541
