### ISSUE TITLE
Expose create-error functionality on Satellite

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1927]
We have lots of places in our microservices that we need to create HTTP errors.  A good way to do this is with [create-error](https://www.npmjs.com/package/create-error).  Let's expose this on Satellite so people don't have to include it as a dep in every microservice.

```js
const { Satellite, createError } = require('@senecacdot/satellite');
...
const err = createError('404', 'Error message....');
next(err);
```

cc @Metropass

**Comment by humphd** [comment]
Filed #1928 to use this in the microservices.

**Comment by Metropass** [comment]
Will work on this, thanks :)

**Comment by Metropass** [comment]
Closed, as this issue has been successfully merged into Satellite.
