### ISSUE TITLE
Refactor all microservices error code to use Satellite's createError()

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1928]
In #1927, we're going to expose `createError()` on Satellite.  Let's modify all of our Microservices code to use it vs. creating their own errors, and also remove `create-error` from their deps.

**Comment by chrispinkney** [comment]
cc @HyperTHD @chrispinkney 😄

**Comment by Metropass** [comment]
I'll take charge with this, and show every instance of `createError`. In advanced, you need to have the `http-errors` module

**Comment by HyperTHD** [comment]
Looks like Satellite was updated with createError, so this can finally be worked upon now
cc @chrispinkney @humphd

**Comment by humphd** [comment]
Noticed we have this in auth, and the `http-errors` dep, which can both get fixed.

**Comment by HyperTHD** [comment]
Posts service now has createErrors used in #2165 
Gonna continue adding this on the other microservices where needed
