### ISSUE TITLE
Add authorization middleware to Users service

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1929]
The Users service exposes a `GET /` route, which lets you get all the users in Firebase.  We need to improve its current form in a few ways:

1. Only an admin should be able to do this (i.e., regular users or the general public can't do this request).  Satellite supports this via middleware:
```js
const { isAuthenticated, isAuthorized } = require('@senecacdot/satellite');
...
router.get('/', isAuthenticated(), isAuthorized({ roles: ["admin"] }), async (req, res, next) => {...}
```
2. We need to add paging.  Firestore [supports this](https://firebase.google.com/docs/firestore/query-data/query-cursors).  Let' follow the same pattern we have with [paging in the posts service](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/posts/src/routes/posts.js#L8-L72), which uses `?page=...&per_page=...`

**Comment by humphd** [comment]
See also https://github.com/Seneca-CDOT/telescope/issues/1931.

**Comment by chrispinkney** [comment]
👀

**Comment by humphd** [comment]
This got closed, but the first item above isn't completed.  Re-opening.

**Comment by chrispinkney** [comment]
> 
> 
> This got closed, but the first item above isn't completed. Re-opening.

Right, thanks for that! cc @Metropass

**Comment by chrispinkney** [comment]
Howdy @Metropass, what's the status of this?

**Comment by Metropass** [comment]
> Howdy @Metropass, what's the status of this?

Still working on this, I'm currently working on the Cache middleware for our Users service & nginx, since it's a huge chunk.  I'll be showing off the code during our meeting today.

**Comment by chrispinkney** [comment]
This has been completed.
