### ISSUE TITLE
Secure User services POST, PUT, DELETE routes

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1931]
The User service has `POST`, `PUT`, and `DELETE` routes that all work on the basis of a user's `id`.  We should add middleware to only allow 1) an admin; or 2) the owning user to do this for their own data.  We already have admin middleware in Satellite, but we need to add support to it for checking the id of a user against the `sub` claim (e.g., id) in the JWT.

It probably should look like this:

```js
const { isAuthenticated, isAuthorized } = require('@senecacdot/satellite');
...
router.post(
  '/:id',
  isAuthenticated(),
  isAuthorized({
    authorizeUser(user) {
      // Get the user id for this request
      const id = req.params.id;
      // Check that the id being used on the request matches the authenticated user's sub claim.
      // Also allow an admin user to do this.  We return `true` if this is allowed, `false` otherwise
      return user.sub === id || user.roles.includes('admin')
    }
  }),
  async (req, res, next) => {
    ...
  }
);
```

This issue will be about using the code in #1930 in the User service, once that's done.

**Comment by chrispinkney** [comment]
Awesome! Just blogged about this 😃 I'll get started on this as soon as I can and get it in before user is merged.

**Comment by humphd** [comment]
This is fixed now.
