### ISSUE TITLE
Firebase setup for Staging and Production

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1932]
The User service is designed to work with a real Firebase account and project set up.  We need to create one for Staging and another for Production.

Some questions:

- can we give multiple people access to this if using the free tier?  If not, probably I need to register them.
- we need to figure out all the values for the ENVs in staging and production.
- do I need two accounts or just two separate collections/dbs in the same account?
- we need some docs explaining the process for maintenance
- how do we import/export data?

cc @manekenpix, @chrispinkney

**Comment by chrispinkney** [comment]
I'll look into this and followup with some information ASAP.

**Comment by humphd** [comment]
https://support.google.com/firebase/topic/9137968?hl=en&ref_topic=6399725 has some details on how we can manage access.  I *think* we can have the project be administered by multiple people with a Spark (free) plan, but it needs testing.

**Comment by chrispinkney** [comment]
See #1058, we'll need to address this when this issue is worked on.

**Comment by chrispinkney** [comment]
> 
> 
> The User service is designed to work with a real Firebase account and project set up. We need to create one for Staging and another for Production.
> 
> Some questions:
> 
>     * can we give multiple people access to this if using the free tier?  If not, probably I need to register them.
> 
>     * we need to figure out all the values for the ENVs in staging and production.
> 
>     * do I need two accounts or just two separate collections/dbs in the same account?
> 
>     * we need some docs explaining the process for maintenance
> 
>     * how do we import/export data?
> 
> 
> cc @manekenpix, @chrispinkney

@humphd Here is some info I curated. See this and #2204. I can also add the below info to that doc if required, or close that PR and add it all here. Whichever is easier to search and navigate.

- can we give multiple people access to this if using the free tier?  If not, probably I need to register them.
  - Yes, however I couldn't seem to find a hard limit to the number of users we can allow access to. My gut instinct is that there is no limit (or at least no reasonable limit.)
  - you can also [tweak the roles](https://firebase.google.com/docs/projects/iam/overview?authuser=1#roles) (i.e. *permissions*) of users being added.
  - More info [here](https://firebase.google.com/docs/projects/iam/overview?authuser=1).
- we need to figure out all the values for the ENVs in staging and production.
  - This has been handled already by us three, but to reiterate:  simply replace the existing `serviceAccountKey.json` file on the prod server with the desired one.
- do I need two accounts or just two separate collections/dbs in the same account?
  - We haven't really discussed this but we could set up a prod version and a dev version, though with the inclusion of the local emulator for development it might be a better idea to simply have a prod version that both dev and prod point to so we don't have to manage two sets of data.
- we need some docs explaining the process for maintenance
  - See #2204.
- how do we import/export data?
  - See #2204.
