### ISSUE TITLE
Update posts healthcheck with Redis check

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1938]
Every [Satellite microservice includes a `/healthcheck`](https://github.com/Seneca-CDOT/satellite#satelliteoptions), which can be used to determine if the service is running.  For example, the current posts healthcheck is:

https://dev.api.telescope.cdot.systems/v1/posts/healthcheck

To make this really useful, we also need to know if any dependent service is also healthy.  In the case of posts, this means Redis needs to be up and accepting commands.

Redis has a [ping](https://redis.io/commands/PING) command that we can call and make sure it returns OK.

**Comment by HyperTHD** [comment]
This should be simple enough. We can even fix this in #1908 since we can use the ping function in redis. Assuming it doesn't get taken care of there, I'll fix this
