### ISSUE TITLE
Use posts microservice in front-end

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1946]
We just added our posts service on staging and production:

- https://dev.api.telescope.cdot.systems/v1/posts/
- https://api.telescope.cdot.systems/v1/posts/

Let's start using them in the front-end.  To do this, we have to pass the URL to the posts service into the front-end via environment variables, docker-compose, and build args in next.js.  We'll also have to update the env values in Vercel.

See the code in https://github.com/Seneca-CDOT/telescope/pull/1940 for an example of how this works.  I did it there for the image service.

**Comment by HyperTHD** [comment]
Gonna be a hassle, but worth it. Taking this
