### ISSUE TITLE
Color of Navbar icons are hard to see

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#1951]
The color choice for the navbar icons make the icons themselves very hard to visualize. This has become more apparent when we merged in the image service to the navbar itself. When a dynamic image that's darker in color is used here, the icons become hard to see. We should change the color of the icons here so that anyone that visits the Telescope site can view them regardless of what dynamic image is loaded

NOTE: This is only on the Desktop version of the icons but changing that will also affect the Mobile version as well

![image](https://user-images.githubusercontent.com/16841702/111182049-edfead00-8584-11eb-9047-15cd263998d7.png)

**Comment by huynguyez** [comment]
To be honest, only changing colors won't help much. It should be back to top-right horizontal or in a different way of design to make them noticeable.
