### ISSUE TITLE
Add Avatar in NavBar after login. 

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1956]
**What would you like to be added**:
After a user successfully logged we want to see the user avatar on the NavBar. 
<img width="192" alt="Screen Shot 2021-03-16 at 9 04 56 AM" src="https://user-images.githubusercontent.com/60857409/111313718-10510300-8637-11eb-952a-7cacaabbf3e0.png">

**Comment by HyperTHD** [comment]
Bulk of the work to be done in #1932 , will come back to this once user service is running in production

**Comment by Meneguini** [comment]
Hello, 

I would like to give this a try.

**Comment by PedroFonsecaDEV** [comment]
Sure go for it.

**Comment by humphd** [comment]
Welcome to Telescope, @Meneguini, great to have you joining us!  NOTE: after I land #2058 and #2088 the images will be accessible on `user.avatarUrl`, but for now they will be limited to the initials.

**Comment by Meneguini** [comment]
Nice! Thank you, @humphd.

**Comment by birtony** [comment]
Hey @Meneguini, please, let us know if you need any help with this issue

**Comment by Meneguini** [comment]
Hi @birtony, thank you, I'll let you know.
