### ISSUE TITLE
Setup initial configuration for Jest Snapshot testing

### ISSUE THREAD

**Issue by birtony** [Seneca-CDOT/telescope#1970]
**What would you like to be added**:
Snapshot Testing with Jest - https://jestjs.io/docs/snapshot-testing
**Why would you like this to be added**:
As discussed with @humphd and @PedroFonsecaDEV, it will allow us to catch unexpected changes in the front-end code more easily.

**Comment by HyperTHD** [comment]
So we finally bringing in front-end tests? :eyes:
