### ISSUE TITLE
Brighten Icons in header tag 

### ISSUE THREAD

**Issue by smilegodly** [Seneca-CDOT/telescope#1971]
The blue on blue makes the icons difficult to see. Can we make these Icons white or a lighter shade of blue?
 
![image](https://user-images.githubusercontent.com/35276477/111547342-64e7a180-874f-11eb-9742-cc73f04819ef.png)

**Comment by manekenpix** [comment]
@smilegodly do you want to do it?

**Comment by DukeManh** [comment]
It's mentioned in #1951.
