### ISSUE TITLE
Decorate each post with a class that matches the blog host platform

### ISSUE THREAD

**Issue by rjayroso** [Seneca-CDOT/telescope#1975]
**What would you like to be added**:
We should be able to distinguish each blog post by decorating the post with a class that matches their blogging host platform; this would allow us to style each blog post differently depending on which platform it is coming from. If the blogging platform cannot be identified we should just style it with our generic solution.

<img width="819" alt="screen_shot_2021-03-18_at_10 04 03_am" src="https://user-images.githubusercontent.com/48869737/111666574-39fe5b80-87ea-11eb-9f61-8c62406e59ce.png">

Each post has a class which we can modify to look like so:
`<section class="telescope-post-content medium">` or `<section class="telescope-post-content wordpress">` etc

This would allow us to apply CSS to specific posts like so:
```CSS
img.medium {...}

img.wordpress {...}
```

**Why would you like this to be added**:
This is especially useful since different blogging platforms execute their layout/CSS differently (which makes it hard to apply a one-size-fits-all solution). Furthermore, if we know what site the post is coming from, we can gather some hints from the original blogging platform to see how they do their images and use that in our own CSS.

In my latest PR ([here](https://github.com/Seneca-CDOT/telescope/pull/1910)), I ran into a problem where - if I apply CSS styling to handle inline images, it will also apply the same CSS styling to BlogSpot posts since they both share the same HTML structure (`div > a > img`). Thus, by fixing the styling of the inline images I had ruined the images from BlogSpot posts. By implementing the desired solution above, I would be able to apply the inline CSS stying to all posts *except* any BlogSpot posts.

**Comment by humphd** [comment]
I think the way to tackle this is probably to take the `post.url` value, turn it into a URL, and extract the host, something like this:

```js
// medium-com from https://medium.com/@pedrofonsecadev/telescope-note-feb-22-2021-8601dfbaa1f0?source=rss-d28cf09618f4------2
const blogClassName = new URL(post.url).hostname.replace('.', '-');
```
