### ISSUE TITLE
Update design of the front landing page

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1976]
I want to improve the experience of the front page.  We use a Hero Image style, which I love.  Partly, it lets the site convey meaning quickly with photography, and it's an easy way for new people to contribute to the project (i.e., suggest an Unsplash photo for us to use).

In #1974 I'm asking that we add quotes from old blog posts about learning to do open source.  Students have been doing this for 15 years at Seneca, and we have thousands of old posts in our database that contain inspiring words of wisdom and encouragement.

We also used to have real-time stats about how many people and words we'd written.  This is no longer updated, due to bugs in our stats code, and will be fixed in #1829.

But our current design, we aren't doing things as well as I'd like.  Here are some issues:

- The side-bar buttons (logo, login, about) are really hard to see against the background image.  One solution would be to get rid of the background image, but as I mentioned above, I want to keep that design aspect.  We need an improved design for showing these on the front-page: maybe they need to be done horizontally across the top until the user scrolls down to content, and then they can move to the side.  Or maybe they need to be vertically stacked but on top of a colour bar.  I'm not sure, it needs thought.
- I want to figure out how to do the image + quote in a way that works well.  This design style (hero + large "quote" on the front page) is really common.  Check out the next.js showcase page: https://nextjs.org/showcase.  Sites like [Netflix Jobs](https://jobs.netflix.com/), [Uber Marketplace](https://marketplace.uber.com/), [Hulu](https://www.hulu.com/welcome), and thousands more have found a way to do this.  Maybe we should have the hero image be less than full height?  Maybe the quote goes on the right and image on the left?  Or maybe quote is over the image?

I'm not sure, but I want to see us get this landing page working better than it is right now.  It should instantly help the user understand what we're doing on Telescope, and inspire them to want to get involved.

@DukeManh, @huynguyez, @PedroFonsecaDEV can you three help figure this out?

**Comment by humphd** [comment]
#1951 is connected to this.

**Comment by PedroFonsecaDEV** [comment]
I think #1921 is connected to this too, I will make a design for this issue.

**Comment by huynguyez** [comment]
@humphd  I wanted to move the nav to where it was (top right) when I first saw the vertical nav. And also the author info from right to left to 'balance' the page layout.

**Comment by PedroFonsecaDEV** [comment]
> @humphd @PedroFonsecaDEV I wanted to move the nav to where it was (top right) when I first saw the vertical nav. And also the author info from right to left to 'balance' the page layout.

@huynguyez Slack.

**Comment by PedroFonsecaDEV** [comment]
I'm working on the design and the implementation of the new landing page. 
We need the following enhancements to land our new landing page: 
- `NavBar`  #2041
- `Scroll Snap` #2042

**Comment by PedroFonsecaDEV** [comment]
Design will be landing tomorrow (March 31).
