### ISSUE TITLE
Add Website Verification in Google Search Console

### ISSUE THREAD

**Issue by birtony** [Seneca-CDOT/telescope#1989]
**What would you like to be added**:
We should look into verifying https://telescope.cdot.systems/ in Google Search Console.
**Why would you like this to be added**:
This comes with a number of perks as outlined at https://developers.google.com/search/docs/guides/debug#verified-site-owner-tools. It should be helpful for improving our SEO.

**Comment by birtony** [comment]
This is related to https://github.com/Seneca-CDOT/telescope/issues/1607

**Comment by birtony** [comment]
@manekenpix seems like this is specifically what Google wants us to do:
![image](https://user-images.githubusercontent.com/33902374/111810177-1a2f6c00-88ac-11eb-86ed-bd0791c2e138.png)
Accessed through https://search.google.com/search-console

**Comment by chrispinkney** [comment]
This has been addressed in #2036 and has been deemed to be "good enough." Closing.
