### ISSUE TITLE
Logout error on /myfeeds

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2000]
**What happened**:
Logging out from /myfeeds page returns an error.

**What should have happened**:
Even though the logout is successful, it should redirect to the previous page. 

<img width="1546" alt="image" src="https://user-images.githubusercontent.com/51073515/111853079-d3636580-88ef-11eb-91b0-cd32d28abf90.png">

**Comment by humphd** [comment]
We'd need to pass the full, absolute URL back to the page you want to use.
