### ISSUE TITLE
Document REST API

### ISSUE THREAD

**Issue by varshannagarajan** [Seneca-CDOT/telescope#203]
We have added some different route such as the one to view the bull queues. We should add some documentation on how to use it and any new routes we add.

**Comment by humphd** [comment]
Our REST api is getting pretty close to being "finished," and it might be good to consider adding these docs now.  There are a few automated tools we could use to generate the docs based on comments:

- [apidoc](https://apidocjs.com) which uses inline "JavaDoc" style comments
- [aglio](https://github.com/danielgtaylor/aglio) which uses [API Blueprint](https://apiblueprint.org/) formatted docs

Of the two, [apidoc](https://apidocjs.com) is probably the one we should do, unless someone has a desire to use the other.

**Comment by c3ho** [comment]
@manekenpix collab on this? https://github.com/swagger-api/swagger-node/tree/master/docs

**Comment by humphd** [comment]
https://blog.logrocket.com/documenting-your-express-api-with-swagger/

**Comment by humphd** [comment]
Perhaps related #1277

**Comment by manekenpix** [comment]
@c3ho sure, let's collab for this one.

**Comment by izhuravlev** [comment]
cc @HyperTHD

**Comment by sirinoks** [comment]
@humphd What is meant by Rest API in here in regards to Telescope? Is this the old 1.0 code chunk, is it the microservices? I want to do documentation, but I don't even know what it's about D: 
Linking specific files would also really help

**Comment by humphd** [comment]
Microservices code.  The other legacy code is going away.

There are a bunch of ways to auto-generate API docs for REST APIs, or we can do it manually.  Everything under `src/api/*` needs this.  Some of them have it already, others don't, but none of it is collected anywhere.
