### ISSUE TITLE
Colours are wrong for light and dark theme on Error page

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2038]
None of the colours is correct for https://dev.telescope.cdot.systems/error/?status=404:

<img width="1248" alt="Screen Shot 2021-03-28 at 2 27 44 PM" src="https://user-images.githubusercontent.com/427398/112763282-d3d7bc80-8fd1-11eb-9c79-c2b4ed3c3709.png">
<img width="1258" alt="Screen Shot 2021-03-28 at 2 27 27 PM" src="https://user-images.githubusercontent.com/427398/112763287-d508e980-8fd1-11eb-966a-4110c8558638.png">

**Comment by tonyvugithub** [comment]
This has been fixed. Hence closed
