### ISSUE TITLE
[U.I 2.0][Landing Page] Scroll-snap on lading page.

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#2042]
**What would you like to be added**:
In #1976 we are updating our lading page.
@huynguyez gave us https://www.tesla.com/ as a reference, and the site seems to be using some Scroll-Snap.

@DukeManh made some tests and found some issues with the implementation: 

From @DukeManh (in #1921)
>after playing around with scroll snap, I don't think scroll snap would work well for our page layout. You can see what I mean here https://codepen.io/Ducmanhbui/pen/oNYreYx. If you can come up with a workaround, that'll be great; otherwise, we might have to close this issue.

Sites with some references about scroll-snap:

https://css-tricks.com/practical-css-scroll-snapping/
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-bottom
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap

@humphd, we would appreciate some help/guidance on how to implement the scroll-snap.

**Comment by humphd** [comment]
The Tesla site is interesting.  Our site is obviously different, but I wonder if we could still do something similar, namely, have two stacked divs: first one is the landing, second is the timeline.  We could have them both be height=100%, and then do the timeline overflow inside the second div vs. in the page cc @huynguyez.

**Comment by PedroFonsecaDEV** [comment]
@DukeManh
