### ISSUE TITLE
Fix users MS e2e tests

### ISSUE THREAD

**Issue by chrispinkney** [Seneca-CDOT/telescope#2054]
[Line 3-4](https://github.com/Seneca-CDOT/telescope/pull/2027/files#diff-4ec6ae1062f8c845da78ad08d72b46a50b1d6ff94cb1252a8d1e6771764eed16R3-R4) of the users microservice prod-ify [PR](#2027) that just landed hardcodes an environment variable in order to satisfy e2e tests passing.

This is not ideal and only present because the [tests for the users microservice](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/users/test/e2e/users.test.js) are currently coded to send requests to `/` as opposed to `http://localhost/v1/users`. These tests need to get modified so they are actual e2e tests instead of unit tests.

This change could serve to complicate things with supertest, and so node fetch might have to be used as an alternative.

Once fixed the lines mentioned above can be removed from `jest.config.e2e.js`.

**Comment by humphd** [comment]
Let's get https://github.com/Seneca-CDOT/telescope/pull/2060 reviewed and merged before we start this, since I'm changing so much of the tests there.  I also need this fix in order to get the pagination tests done, after it merges.

**Comment by chrispinkney** [comment]
Agreed, that's the plan. Going to take a look at it with @manekenpix now
