### ISSUE TITLE
Switch from `bent` to `node-fetch`

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#206]
Right now, telescope is using both [`bent`](https://www.npmjs.com/package/bent) and [`node-fetch`](https://www.npmjs.com/package/node-fetch) for requests.  To avoid having multiple dependencies for doing the same, we should go with just one of them. `node-fetch` seems to be a bit more versatile than `bent`, so it'd be a good idea to replace it with `node-fetch` wherever is used.

**Comment by hansal7014** [comment]
Hi @manekenpix,
I would like to work on this. Thanks.
