### ISSUE TITLE
Search component fires a request after every keystroke

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#2062]
After landing #2046, the search component fires a request after every keystroke instead of after hitting enter.
This behaviour is not desirable, and we should revert to the way the search component was working before this PR.

**Comment by humphd** [comment]
Agree, this sounds like a regression (we had this fixed earlier).

cc @HyperTHD

**Comment by HyperTHD** [comment]
Learnt my lesson. Gonna leave the PR up, even for weeks if it means it lands properly and fixed 👍🏾
