### ISSUE TITLE
Remove unused Footer component

### ISSUE THREAD

**Issue by birtony** [Seneca-CDOT/telescope#2069]
**What would you like to be added**:
I have found out that https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/components/Footer.tsx is not used anywhere on the website. Looks like it was ported from Gatsby in https://github.com/Seneca-CDOT/telescope/pull/1526, but is not needed anymore.
**Why would you like this to be added**:
We should remove `/src/web/src/components/Footer.tsx` from the source code.

**Comment by humphd** [comment]
cc @cindyledev
