### ISSUE TITLE
Image service not working 100% of the time on preview url

### ISSUE THREAD

**Issue by tonyvugithub** [Seneca-CDOT/telescope#2077]
**What happened**:
For some of the preview build on Vercel. The service url is not correctly and hence made it failed loading the image for the banner. I checked the console and turned out that for some reason the browser used `localhost` instead of the prod url. 
![image](https://user-images.githubusercontent.com/55034244/113517953-1741a600-9551-11eb-9aec-ffe8c856144a.png)
**What should have happened**:
It should always use the correct service url
**How to reproduce it (as precise as possible)**:
Use this preview vercel build link https://vercel.com/humphd/telescope/DCJdtVMgpShtFMjcMuy4WEA7d6K3
**Anything else we need to know?**:
This does not happen 100% of the time

**Comment by humphd** [comment]
I've updated how env variables happen in Vercel just now.  Let me know if you notice this happening again.

**Comment by tonyvugithub** [comment]
@humphd : I just do another commit and it worked now. Should I close this?

**Comment by humphd** [comment]
Yeah, let's re-open if it becomes an issue again.  Keeping env vars in sync in Vercel is a bit of a manual thing, so it's going to break at some point again. We'll just have to re-open issues if we notice problems.

See something?  Say something!
