### ISSUE TITLE
Use mock responses when testing the GitHub data fetching tool

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#208]
Currently the test for the tool to fetch data from GitHub's API is not using mock responses, which has the potential to fail (network down, API down, throttling, etc).
It'd be interesting to replace the responses to make sure the tests fail when they have to, and not because of external factors.

@humphd suggested [nock](https://www.npmjs.com/package/nock), and [jest-fetch-mock](https://www.npmjs.com/package/jest-fetch-mock)

**Comment by manekenpix** [comment]
See #210

**Comment by c3ho** [comment]
Sorry, did not notice you created this issue. I can close mine if you want!

**Comment by manekenpix** [comment]
@c3ho I think we should keep both, or if anything yours, mine is too specific.

**Comment by manekenpix** [comment]
Or you can create an issue specifically for what you were working on. It was `feedParser`, right?

**Comment by c3ho** [comment]
Yeah, specifically the unit testing for it.
