### ISSUE TITLE
(Mobile) Navbar overlaps site's Footer

### ISSUE THREAD

**Issue by huynguyez** [Seneca-CDOT/telescope#2084]
Small issue as screenshot below, need to add more space from bottom on mobile version:

![Screen Shot 2021-04-06 at 4 09 30 AM](https://user-images.githubusercontent.com/10421864/113679897-4447a300-968e-11eb-8e46-763d9b4ff6a6.jpg)

**Comment by HyperTHD** [comment]
#2086 by @AbhishekkGautam resolved this issue, so closing this issue
