### ISSUE TITLE
Remove old Gatsby docs

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2097]
I noticed that we still have a doc on our Gatsby front-end, which has been replaced: https://github.com/Seneca-CDOT/telescope/blob/master/docs/gatsbyjs.md.

Let's remove this.  I'd love to see a first-time contributor pick this up.

**Comment by menghif** [comment]
I can take this one!

**Comment by chrispinkney** [comment]
@menghif All yours!

**Comment by menghif** [comment]
In [login.md](https://github.com/Seneca-CDOT/telescope/blob/master/docs/login.md) there is a reference to "Gatsby techniques like client-only routes". How is this done now with NextJS? How should I update this doc?
