### ISSUE TITLE
Dark mode not being applied fully when user logs in

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#2100]
**What happened**:

When testing #2098, I noticed that the dark mode was not being fully applied in the timeline. This is how it looks like when you login and have your theme preference set to dark mode

![Bad dark-mode image](https://user-images.githubusercontent.com/16841702/114075432-8978fa00-9873-11eb-992f-cc75db964057.png)

This is not an issue with the light-mode theme, however. That's working as expected.

**What should have happened**:
The white portions of the timeline should be black as that's the color of choice when using dark mode.

**How to reproduce it (as precise as possible)**:
To reproduce this issue, simply login with your theme preference being set to dark mode prior to the login.

**Anything else we need to know?**:
This issue is dependent on #2098 landing, since this issue was found while testing the login portion of our front-end to make sure it works as expected.

**Environment**:

- OS: Microsoft Windows 10 Home
- Browser: Google Chrome

**Comment by humphd** [comment]
@PedroFonsecaDEV said that this might be due to cached next.js builds when doing hot reloads.  It's annoying but probably not a bug?  Not sure.
