### ISSUE TITLE
Advanced search dialog in SearchBar 

### ISSUE THREAD

**Issue by huyxgit** [Seneca-CDOT/telescope#2110]
Show advanced search dialog from clicking 'gear' button in searchBar 

![Screen Shot 2021-04-09 at 2 42 32 PM](https://user-images.githubusercontent.com/10421864/114226719-ef33b780-9941-11eb-8c24-d68c8f2e7f3a.jpg)

**Comment by AmasiaNalbandian** [comment]
@humphd I can take a look into this again now, I saw the last two PRs that you linked and it seems like it's been left open. Should I continue from the work there or are there new suggestions for the search?

**Comment by humphd** [comment]
@AmasiaNalbandian Sure, if you like.  There are a few PRs already open on this that you could start with.
