### ISSUE TITLE
Write tests and enable Parser service

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2111]
We landed the Parser service today, but we have it not starting the actual parser, nor do we have any tests. We need to fix both things.  @c3ho added Jest configs for both unit and e2e tests, but there aren't any.

You can get some idea of how to work across services in tests by looking at my auth test [here](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/auth/test/e2e/auth-flows.test.js).

**Comment by chrispinkney** [comment]
@c3ho What's the status of this right? We're trying to land this for Friday if possible. Should someone else take this on?

**Comment by c3ho** [comment]
@chrispinkney Hi Chris, sorry work has been killing me... as you can tell by the time of this message. Could someone else take it on?

**Comment by humphd** [comment]
@c3ho no worries, thanks so much for getting the ball rolling on this.  We'll take it from here.

**Comment by humphd** [comment]
When this gets fixed, make sure to undo what I did in https://github.com/Seneca-CDOT/telescope/pull/2441, where I disabled the parser service.

**Comment by chrispinkney** [comment]
@manekenpix and I have been trying to work on this slowly and would like to keep going, nearing completion I think!

**Comment by humphd** [comment]
Cool.  I know that @TueeNguyen is interested in working on this as well, maybe you can collaborate?

**Comment by TueeNguyen** [comment]
Yes, I'd like to hack this. I'll start on Monday, got a Hackathon this weekend

**Comment by humphd** [comment]
@TueeNguyen cool, I'd encourage you to join in with @chrispinkney and @manekenpix, you'll learn a ton working with these two.

**Comment by TueeNguyen** [comment]
Josue helped me fix a bug and parser service now processes feed successfully. Next steps: 

- add unit tests (most unit tests are available in [test folder](https://github.com/Seneca-CDOT/telescope/tree/master/test))
- e2e tests? (not sure if we can write e2e tests for this)
- containerize the parser service

**Comment by humphd** [comment]
We can do e2e tests for sure.

**Comment by TueeNguyen** [comment]
I did some comparison between `backend` and `parser` today, I see that `parser` doesn't have `admin.js`, `user.js`, `stat.js`, does `parser` need these files or these functionalities are handled somewhere else? (Later is probably correct) @manekenpix @chrispinkney @humphd 

![image](https://user-images.githubusercontent.com/58532267/152666515-8cbece4b-1818-4658-813e-7e2c6fc7dfc7.png)

![image](https://user-images.githubusercontent.com/58532267/152666536-3c12885d-3bb1-4946-9bbf-e2933c730c89.png)

**Comment by manekenpix** [comment]
@TueeNguyen the parser service doesn't need those files. `admin` and `user` are now part of `sso`, and `stat` used to display info in the hero banner, but we don't use it anymore (the idea is make `status` do that work).

**Comment by TueeNguyen** [comment]
Thank you, I just want to confirm that those are not needed

**Comment by TueeNguyen** [comment]
Reopened because I haven't got tests in

**Comment by humphd** [comment]
Or Docker bits to turn it on in docker-compose.yml

**Comment by TueeNguyen** [comment]
@humphd, can you give me some idea how to write e2e test for this? 

I plan on adding a few valid, invalid, youtube feeds to the queue, run it and after the queue is drained, I check data in redis, queue's stats

**Comment by humphd** [comment]
An e2e test would probably have you add some feeds to the queue (later we'd inject them into the database), have the feed queue start, wait on the queue to drain, then use the posts service to query the feeds and posts data.

**Comment by TueeNguyen** [comment]
Great, my initial thought is almost correct. But, how do I use posts service in `parser`? Should I import it to `parser`?

**Comment by humphd** [comment]
You wouldn't use it in the parser, you'd `fetch()` it in your tests.  The test is connecting the two, they know nothing about each other.

**Comment by TueeNguyen** [comment]
Hi @humphd, How do I run e2e tests? I don't think I can run it locally.

**Comment by humphd** [comment]
Identical way we do it in CI:

https://github.com/Seneca-CDOT/telescope/blob/master/.github/workflows/e2e-tests-ci.yml#L28-L30

**Comment by TueeNguyen** [comment]
I did some research on testing bull queue using `ioredis-mock`, apparently, it only works with real redis connection. Refer to this issue https://github.com/OptimalBits/bull/issues/962.

**Comment by humphd** [comment]
This is why we need to write e2e vs. mock unit tests (i.e., so we have a real redis).
