### ISSUE TITLE
adding 'Share' button

### ISSUE THREAD

**Issue by huyxgit** [Seneca-CDOT/telescope#2117]
You read blogs and you might want to share that blog post or bookmark it (no way to do it at the moment (one page) unless you take a screenshot or use 'search' to find it again) 

- What to share? URL of original post. 
- Button location? at the end of a blog post or post's author info section.
- How it looks like? Not a feature to be highlighted, so only one button displayed and sharing options could be in a dialog after  a click or a dropdown on hovering, example share button on iOS:
![download](https://user-images.githubusercontent.com/10421864/114284577-d51bd700-9a1e-11eb-8247-b24e83f047ff.png)

(This could be for future student(s) who is interested)

**Comment by humphd** [comment]
I think we can extract this data with the RSS feed parser, and give you the direct link to share their blog vs. a link to Telescope.

**Comment by tonyvugithub** [comment]
@humphd : Correct me if I am wrong. Currently did we already extract the original url link in our feed parser? I remember having similar thought before and Pedro told me to hold off on it. I might still have the code of the sharing button.

**Comment by chrispinkney** [comment]
> 
> 
> @humphd : Correct me if I am wrong. Currently did we already extract the original url link in our feed parser? I remember having similar thought before and Pedro told me to hold off on it. I might still have the code of the sharing button.

I say go for it, especially if you have the code already. We can always discuss it as a PR later and see how everyone feels.

**Comment by tuanthanh2067** [comment]
I want to give this one a try, but I have a few questions about how you want this share thing go. 

1. I think I will add a share button below the image, when one clicks the button, I will copy the link the clipboard
![image](https://user-images.githubusercontent.com/51014333/143506509-1ae40ce8-25f4-4f07-9ea0-3e955a0532e7.png)

2. This is what I'm struggling. I think I'm going to have a url serving the post. The url could be something like `https://telescope.cdot.systems/postId`

**Comment by humphd** [comment]
I think you should put it beside the date, since that's the link to the blog, and I'd share the original blog URL vs. a Telescope URL.

**Comment by tuanthanh2067** [comment]
I think about something bigger like: the share button will copy the telescope url, and when a person goes to that url, the post will be displayed, and a couple of share buttons to social platforms and a button to get the original blog URL will be put at the bottom.

**Comment by humphd** [comment]
we don't have deep linking into posts in Telescope.  I would start simpler

**Comment by tuanthanh2067** [comment]
I don't understand, can you please explain it?

**Comment by humphd** [comment]
> the share button will copy the telescope url

We don't have a way to link to a specific post in Telescope (deep linking), so the only URL we should be giving to the user is the original blog URL.

**Comment by tuanthanh2067** [comment]
The author also mentioned about bookmarking posts, how do you think about it?

**Comment by humphd** [comment]
Can you say more about what you mean?  As I mentioned above, we have no way to link into Telescope in order to show a specific post, so bookmarking won't work (on the Telescope side).  However, you can bookmark or share the original post URL, which is what I'd recommend.

**Comment by tuanthanh2067** [comment]
For bookmarking, I think that I will save post id in local storage or database, and I will use these post id's to show posts just like how you show posts in search.

**Comment by tuanthanh2067** [comment]
So I need an api that can help me get all posts by id's

**Comment by humphd** [comment]
I don't think this is a good idea.  Our posts are ephemeral (i.e., we cache them, we don't store them), and they may or may not exist the next time you come.  If people want to bookmark something, it has to be the original.

**Comment by tuanthanh2067** [comment]
Oh I see but I still think bookmarking is a pretty cool feature to have in telescope. As we put all people's posts together from all different platforms, some posts are good and people want to save to read later but they want to go directly to the original sites

**Comment by humphd** [comment]
Let's do this:

- Have this issue be about providing a "Share" link/icon for the original blog URL
- File a new issue to explore the idea of allowing an authenticated Telescope user to create "collections" of posts, or something, which can be date-ordered set in Redis of post ids.
