### ISSUE TITLE
Tweak Jest configuration to make tests run faster

### ISSUE THREAD

**Issue by birtony** [Seneca-CDOT/telescope#2120]
**What would you like to be added**:
@humphd has found [an interesting article](https://dev.to/vantanev/make-your-jest-tests-up-to-20-faster-by-changing-a-single-setting-i36) that suggests that tweaking the number of workers in the Jest configuration may help improve how quickly our tests run. 
**Why would you like this to be added**:
We should consider implementing what is covered in the article.

**Comment by humphd** [comment]
I notice that Jest itself does some extra work to figure out the number of CPU cores on CI and passes that to `--maxWorkers` to optimize concurrency:

https://github.com/facebook/jest/blob/master/.github/workflows/nodejs.yml#L118-L122
