### ISSUE TITLE
Audit Wildcard ('*') Header Use in Telescope

### ISSUE THREAD

**Issue by Metropass** [Seneca-CDOT/telescope#2121]
**What would you like to be added**:

Figure out where we use the Wildcard `*` Header for CORS in Telescope
**Why would you like this to be added**:

While working on #667, I noticed that the Wildcard operator is not implemented in Safari on iOS and Firefox for Android.

Since we have a mobile UI for Telescope, we should probably audit where we use the Wildcard operator, and pass in the headers that we want to use. (if the person is using the browsers above)
![Screenshot_415](https://user-images.githubusercontent.com/58116522/114286599-3eefad00-9a2e-11eb-9e56-9a6b2bf97b22.png)

**Comment by birtony** [comment]
We specifically use two headers (`link`, `x-count`) and the old back-end sets these for CORS. We should probably set these for Satellite.

**Comment by aserputov** [comment]
Related #2444

**Comment by DiegoHdz7** [comment]
Hi, I would like to take this issue for the hacktoberfest, can I take it?

**Comment by humphd** [comment]
I don't think this is an issue.  Re-open if we find otherwise.
