### ISSUE TITLE
Establish guidelines for writing Jest tests

### ISSUE THREAD

**Issue by Silvyre** [Seneca-CDOT/telescope#213]
Presently, across all [merged](https://github.com/Seneca-CDOT/telescope/tree/master/test) and [pending](https://github.com/Seneca-CDOT/telescope/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+test%22) test files, an assortment of testing syntax is used, and few structural similarities exist. For example, some testing files use [`describe()`](https://jestjs.io/docs/en/api.html#describename-fn), while others do not; some tests use [`test()`](https://jestjs.io/docs/en/api.html#testname-fn-timeout), while others use its alias [`it()`](https://jestjs.io/docs/en/api.html#testname-fn-timeout), etc.

I feel that it would be helpful to Telescope's future maintainers if we established and started abiding by some common conventions or guidelines for writing test files. This would first require us to determine our preferred coding style for test files, including which pieces of Jest syntax each testing file should or should not utilize.

**Comment by miggs125** [comment]
This is a great idea!. We should do this in the [CONTRIBUTING](https://github.com/Seneca-CDOT/telescope/blob/master/docs/CONTRIBUTING.md) file

**Comment by humphd** [comment]
See #245, which has some excellent sample code for doing mock network requests in tests.

**Comment by humphd** [comment]
cc @manekenpix, who has written a bunch of our test code.

**Comment by humphd** [comment]
https://devhints.io/jest is really useful, we should link to it somehow in our docs.

**Comment by c3ho** [comment]
Closing this issue as it is too vague.
