### ISSUE TITLE
Remove temporary fix for dev.to RSS feed bug

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2141]
I [filed an issue upstream](https://github.com/forem/forem/issues/10927) to deal with a dev.to bug.  While it was being fixed, I [added a temporary workaround](https://github.com/Seneca-CDOT/telescope/pull/1816) in our code.

Let's remove this temporary fix in our code, now that the bug has been solved upstream.  The easiest way to do this is with a `git revert 6b36eee958f731b208eea6e981d0d2a1805c6301` to create a reverse commit, which undoes the work I did.

Let's get a new contributor to do this as their first contribution: no one with an existing contribution please :)

**Comment by mqnguyen5** [comment]
If possible, I would like to give it a try. Can you explain more about the work needed to be done? And, is there anything I should be aware of like testing before submitting it for review?

**Comment by humphd** [comment]
It's all yours @mqnguyen5.  You don't need to file an issue, this will do.  You can create a new branch for `issue-2141`, then use the command I gave above to revert the old work.  Create a pull request for the work and our automated tests will run it for you.  Let us know if you need help with any of it.

**Comment by mqnguyen5** [comment]
I understand. Thanks for the info. Will try to work on it as soon as possible!
