### ISSUE TITLE
Improve postInfo grid size to fit bigger names on mobile

### ISSUE THREAD

**Issue by Meneguini** [Seneca-CDOT/telescope#2155]
**What would you like to be added**:
Improve postInfo grid size to fit bigger names on mobile.

**Why would you like this to be added**:
<img width="259" alt="posttitle" src="https://user-images.githubusercontent.com/63076086/114952666-bbb2ca80-9e24-11eb-84ea-f68bb4566692.png">

I think we could use more of the available space.

**Comment by chrispinkney** [comment]
This is currently tagged for our 2.0 release (which is happening on friday), what's the status of this at the moment?

**Comment by Meneguini** [comment]
@chrispinkney, I just finished the PR.
