### ISSUE TITLE
Remove post title outline (on click)

### ISSUE THREAD

**Issue by huynguyez** [Seneca-CDOT/telescope#2156]
Orange on mobile, blue on desktop. 
As screenshots below:

![Screen Shot 2021-04-15 at 7 20 20 PM](https://user-images.githubusercontent.com/10421864/114952785-06344700-9e25-11eb-93a8-ca9455207d72.jpg)
![Screen Shot 2021-04-15 at 7 20 30 PM](https://user-images.githubusercontent.com/10421864/114952786-06344700-9e25-11eb-8823-204023fb5dfa.jpg)

**Comment by humphd** [comment]
@huynguyez where are you seeing this?  I can't reproduce on staging.

**Comment by huynguyez** [comment]
@humphd I just checked on recent deployment: https://telescope-qeexsdyrj-humphd.vercel.app/
,seems ok on Firefox, screenshots above were on Chrome (mac). 
Below is on Safari, I have seen this a long time ago, not new but it's still there and no one talk about it. Or am I wrong..?

![Screen Shot 2021-04-15 at 8 01 39 PM](https://user-images.githubusercontent.com/10421864/114953085-a12d2100-9e25-11eb-840a-9eecf8abcedc.jpg)

**Comment by PedroFonsecaDEV** [comment]
@huynguyez 
I can't see this on [DEV](https://dev.telescope.cdot.systems/) or Production.

**Comment by huynguyez** [comment]
> @huynguyez
> I can't see this on [DEV](https://dev.telescope.cdot.systems/) or Production.

@PedroFonsecaDEV I you tried on 3 browsers? FF is okay but the other 2 are not (at least on my mac)

**Comment by PedroFonsecaDEV** [comment]
@huynguyez 
It's hard to understand without all the instructions, but I see what you mean. Ok. go for it @huynguyez.

**Comment by manekenpix** [comment]
I can reproduce on both staging and production servers, using Chromium

![image](https://user-images.githubusercontent.com/23108901/114957685-8c558b00-9e2f-11eb-9d85-6b13e60ab399.png)

**Comment by humphd** [comment]
Fun.  OK, let's fix!  Thanks for filing @huynguyez.
