### ISSUE TITLE
Some texts are invisible in search page (dark mode)

### ISSUE THREAD

**Issue by yuanLeeMidori** [Seneca-CDOT/telescope#2168]
**What happened**:
Some texts in search page are invisible in dark mode.

"No more posts found" is invisible in dark mode
![chrome-capture (2)](https://user-images.githubusercontent.com/50813726/115088739-dd708800-9ede-11eb-9fea-a0ad5c031716.gif)

"No result found" is invisible in dark mode
![chrome-capture (3)](https://user-images.githubusercontent.com/50813726/115088747-e5302c80-9ede-11eb-8d4c-097baa1dcbcc.gif)

**Comment by HyperTHD** [comment]
Think we might need a new image specifically for dark mode. Shouldn't be too hard to find

**Comment by yuanLeeMidori** [comment]
> Think we might need a new image specifically for dark mode. Shouldn't be too hard to find

That is true. Let me open another issue, thanks!
