### ISSUE TITLE
Fix styles on SignUp page.

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#2171]
**What would you like to be added**:
We need to fix/improve the styles of our SignUp

**Comment by PedroFonsecaDEV** [comment]
@Meneguini are you in?

**Comment by Meneguini** [comment]
@PedroFonsecaDEV, yes I'm in.

**Comment by humphd** [comment]
Are there more of these coming, or has #2148 and #2190 taken care of it (i.e., can we close this)?

**Comment by PedroFonsecaDEV** [comment]
@humphd There is one more coming. Dealing with the `font size` of the pop-ups. Landing tomorrow.
