### ISSUE TITLE
Implementing Cross-Origin-Read-Blocking (CORB) for sensitive Responses 

### ISSUE THREAD

**Issue by Metropass** [Seneca-CDOT/telescope#2179]
**What would you like to be added**:

Implement Cross-Origin-Read-Blocking for sensitive responses in the future  

**Why would you like this to be added**:

We use the `Content-Type` header quite a bit to determine what the content type of the returned response actually is.
In the MDN, they mention that Browsers will do a `MIME Sniff` in order to determine what media format the returned response is, ignoring `Content-Type` in it's entirety.
(https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type)

While this is normal, there might be a scenario when we want to protect our Response data from being sniffed, or bypassed.

Google has a good page talking about what CORB is, and how we could protect Responses. They also include future work on what will be protected in the future with CORB.
(https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md#determining-whether-a-response-is-corb_protected)

**Comment by humphd** [comment]
I don't think this is needed.  Let's re-open if we decide otherwise.
