### ISSUE TITLE
Change users microservice port

### ISSUE THREAD

**Issue by chrispinkney** [Seneca-CDOT/telescope#2182]
**What happened**:
The users microservice currently uses port `6666` which is currently considered unsafe. See [this document](https://medium.com/@msinha2801/why-are-some-ports-considered-unsafe-restricted-c3c22d0596c0) for some more information.

**What should have happened**:
The port (sadly) must be changed. The contributor will have to find all instances of the port being used and change it, it's not just in one place.

PS This is an excellent issue for a first time contributor! 😄

**Comment by humphd** [comment]
See https://github.com/Seneca-CDOT/telescope/search?q=6666

**Comment by shubhammehra4** [comment]
may I take this?

**Comment by chrispinkney** [comment]
Sure, go for it!
