### ISSUE TITLE
feedparser-promised deprecated

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2197]
The feed parser module we use has been deprecated: https://www.npmjs.com/package/feedparser-promised

We need to find a new one that's being maintained.

**Comment by HyperTHD** [comment]
Gonna recommend this library: rss-parser https://www.npmjs.com/package/rss-parser

As per the README, here's an example output from the library:

![output for rss-parser](https://user-images.githubusercontent.com/16841702/115487281-63b20480-a226-11eb-8fee-8d8c2600981e.png)
