### ISSUE TITLE
Extra width causing horizontal overflow

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2201]
Something recent is adding width and making the window scroll horizontally:

![overflow](https://user-images.githubusercontent.com/427398/115648970-6b3fdf00-a2f4-11eb-8ce3-02ae394b9c15.gif)

cc @PedroFonsecaDEV @DukeManh @Meneguini

**Comment by PedroFonsecaDEV** [comment]
@humphd nothing on my end. 
How to reproduce it?

**Comment by huynguyez** [comment]
@PedroFonsecaDEV  Same, probably this happens after logged in? I can't log in with my Seneca account (need permission or sth) so I'm not sure.

**Comment by Meneguini** [comment]
@humphd @huynguyez @PedroFonsecaDEV It happened on my screen too. (it has a 1280px width resolution). Using the dev tools of chrome, I could reproduce it only by opening the dev tools and reducing the screen's width until the horizontal bar appears. I couldn't reproduce using the toggle mobile device toolbar, though. I will investigate what is causing it to happen.
