### ISSUE TITLE
Uncaught error in dialogue.js

### ISSUE THREAD

**Issue by jatinAroraGit** [Seneca-CDOT/telescope#221]
Type: Bug. 
Area: Front-End

**Description**:
There is an error originating from  dialogue.js file.

**How to reproduce**:
Make sure you are running the latest copy of the project.

1. Open index.html
2. In Chrome , open Developer settings and go to console tab

You will see the following error:

![image](https://user-images.githubusercontent.com/28763265/68974214-2c802e00-07be-11ea-862c-f20b20316410.png)

By clicking on the file name you can see what line in the file is throwing the error.

![image](https://user-images.githubusercontent.com/28763265/68974087-df9c5780-07bd-11ea-9e33-37774ec9f96f.png)

**Comment by humphd** [comment]
Looks like a DOM timing bug on startup, wrap this in a `DOMContentLoaded` event.

**Comment by jatinAroraGit** [comment]
Hey @humphd ,
I did what you recommended but it still throws the error.
Looks like there are lot of things wrong in this file.
We do not have any button with the id="participants"
and neither any span element with that class.
I ran the in-built debugger in chrome. It only hits the button call if I add the id in the participants button in index.html.
Rest I am not sure what this file was for but needs some updating.

**Comment by humphd** [comment]
See https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/index.html#L35, the `<button>` needs an `id="participants"` for this selector to work.

**Comment by ODAVING** [comment]
@jatinAroraGit during iterations of the FE the dialogue portion of index.html had gotten removed. The code for that is linked below. Please make sure that when participants button gets clicked it'll open a new animated window, where you can either close it with the 'x' mark on the top right or get rid of it if you were to click outside the dialogue box area. That was the original intention of the dialogue.js

Hope this guides you: 

index.html
`

    <div id="dialogue" class="dBox normalTheme">
        
        <div class="dBox-content normalTheme">
            <h1>Participants
                <span class="dBox-close">&bigotimes;</span></h1>
            <div class="row normalTheme" id="srchDiv">
                <div class="col">
                    <form action="#" class="srchBox" style="margin: auto; max-width: 270px;">
                        <input type="text" placeholder="Search..." name="srchBtn">
                        <button type="submit">Find</button>
                    </form>
                </div>
            </div>
            <br>
            <div class="container-fluid normalTheme">
                <div class="row">
                    <div class="col-md-2" id="dBox-text">
                        TEST CONTENT
                    </div>
                    <div class="col-md-2" id="dBox-text">
                        TEST CONTENT
                    </div>
                    <div class="col-md-2" id="dBox-text">
                        TEST CONTENT
                    </div>
                    <div class="col-md-2" id="dBox-text">
                        TEST CONTENT
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2" id="dBox-text">
                        TEST CONTENT
                    </div>
                    <div class="col-md-2" id="dBox-text">
                        TEST CONTENT
                    </div>
                    <div class="col-md-2" id="dBox-text">
                        TEST CONTENT
                    </div>
                    <div class="col-md-2" id="dBox-text">
                        TEST CONTENT
                    </div>
                </div>
            </div>
        </div>
    </div>
`
Dialogue.js
`
const dialogue = document.getElementById('dialogue');
const btn = document.getElementById('participants');
const span = document.getElementsByClassName('dBox-close')[0];

btn.onclick = function () {
  dialogue.style.display = 'block';
};

span.onclick = function () {
  dialogue.style.display = 'none';
};

window.onclick = function (event) {
  if (event.target === dialogue) {
    dialogue.style.display = 'none';
  }
};
`

**Comment by jatinAroraGit** [comment]
Hey @ODAVING ,
Thanks for this. 
I will incorporate this code and make a new commit.
