### ISSUE TITLE
Remove api:* scripts if not needed

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2212]
In `package.json` (root) we have two scripts that I think are no longer needed, but I'm not sure:

```json
  "scripts": {
    "api:start": "docker-compose -f ./src/api/docker-compose-api.yml up --build -d",
    "api:stop": "docker-compose -f ./src/api/docker-compose-api.yml down",
```

If these aren't being used anymore (e.g., in scripts outside Telescope for deployment?), let's remove.

**Comment by HyperTHD** [comment]
Agreed, we use `npm run services:start` and `npm run services:stop`, which essentially runs these 2 scripts. These two can be safely removed

**Comment by oliver-pham** [comment]
Can I take on this issue?

**Comment by humphd** [comment]
@oliver-pham Yes, please go ahead with this.  Thanks.
