### ISSUE TITLE
Use preferred theme on page load. 

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2222]
**What happened**:
When you choose dark mode, close the window and then open Telescope again, the page will start out in light mode before transitioning to dark. 

https://user-images.githubusercontent.com/51073515/116626706-b7ed7080-a919-11eb-8b9d-41428231b919.mp4

**What should have happened**:
We should see our preferred theme right away.
**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by bharati-21** [comment]
Hi @DukeManh ,
Are you using transitions to switch the theme? If yes, that may cause this.

**Comment by AmasiaNalbandian** [comment]
Should we store this in their localstorage and read the preference on load?

**Comment by humphd** [comment]
> Should we store this in their localstorage and read the preference on load?

We do, see https://github.com/Seneca-CDOT/telescope/blob/bcf9c4a59a3bf81750e42bc45683d936899d1794/src/web/src/hooks/use-preferred-theme.ts#L9

**Comment by HyperTHD** [comment]
Just tested this the way @DukeManh showed in his video, and hasn't broken for me. 
Might not be an issue anymore, can anyone else verify if this is still an issue?

**Comment by AmasiaNalbandian** [comment]
> Just tested this the way @DukeManh showed in his video, and hasn't broken for me. Might not be an issue anymore, can anyone else verify if this is still an issue?

I was able to reproduce this on the weekend... but now it's fast and I can't tell. On the weekend, you would see a quick flash of white before it swapped back to the dark theme. Today, I don't see any white background on refresh.

**Comment by humphd** [comment]
Shall we close and re-open if it starts happening again?

**Comment by AmasiaNalbandian** [comment]
I tested on Chrome and Firefox and it was fine. I think we're ok to close.
