### ISSUE TITLE
add-feed link in tools README points to nothing

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#2224]
**What happened**:
We must have removed this file from the tools directory at some point, because the link here still points to the file, which doesn't exist in the repo anymore

![url-in-question](https://user-images.githubusercontent.com/16841702/116748263-2ccdb280-a9cd-11eb-8696-d354f10640c2.png)

[This is the link that developers will see](https://github.com/Seneca-CDOT/telescope/blob/master/tools/add-feed.js). This should be removed from the README for the tools directory if it's not being used anymore

**Comment by shubhammehra4** [comment]
may I take this?

**Comment by shubhammehra4** [comment]
add-feed is also included in the "bin" in package.json and docs/git-workflow.md but as you mentioned above the file is not present in the tools directory so should I remove it from there too?
