### ISSUE TITLE
Post microservice's README has "Image Service" as title

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#2229]
The [README](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/posts/README.md) document in the `Posts` microservice has **Image Service** as title. This should be changed to **Posts Service**.

**Comment by RitikJainRJ** [comment]
Hi I would like to help you on this issue.

**Comment by PedroFonsecaDEV** [comment]
Hi @RitikJainRJ 
I really appreciate your initiative to ask to solve one of our issues. 
Unfortunately, we received a PR that will solve this issue. 
You still can pick another `good first issue` from this [list](https://github.com/Seneca-CDOT/telescope/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22), and I will help you if you need. 
Thanks.
