### ISSUE TITLE
Files in src need proper documentation

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#224]
I noticed some of the source files(including mine) are missing proper documentation, such as comments describing the functions , parameters and what it returns. 

There are a few good examples in the src directory at the moment, such as email-sender.js, github-url.js we could use as an example. I suggest we pick one of the two and use it as a standard going forward.

**Comment by serviceatclick** [comment]
I have just made an account on git hub. Previously I have made couple of accounts n git , but once I upload my bootstrap template which is also online and associated with its own domain rather then bootstrap. My account gets flagged. 

Please let me know how can I use git I want to upload my own template by using node or bootstrap repositories?

**Comment by mrmojorisin92** [comment]
[webData.zip](https://github.com/Seneca-CDOT/telescope/files/3964760/webData.zip)

**Comment by c3ho** [comment]
Closing this issue as it is too vague.

**Comment by alexjones999** [comment]
Could you please guide me how can I do the required modifications or changes as per you. So that I can do that and implement.
