### ISSUE TITLE
Use Satellite's fetch() function and remove local deps for microservices

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2240]
Now that #2135 is fixed, and v1.16.0 of Satellite is released, we can use `const { fetch }  = require('@senecacdot/satellite')` to get a `fetch()` function in our microservices.  Any of the services that are currently using `fetch()` or `got()` or the like to do client HTTP requests should switch to use this.

**Comment by HyperTHD** [comment]
Will have a PR for this up soon, so gonna claim this issue

**Comment by humphd** [comment]
Closed by https://github.com/Seneca-CDOT/telescope/pull/2242
