### ISSUE TITLE
Experiment with npm-merge-driver

### ISSUE THREAD

**Issue by birtony** [Seneca-CDOT/telescope#2243]
**What would you like to be added**:
We currently do not use the `package-lock.json` due to git conflicts that often arise out of it. We could experiment with [`npm-merge-driver`](https://www.npmjs.com/package/npm-merge-driver) to see if it can help us resolve these conflicts more swiftly and possibly allow us to use [the lock files](https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json).

**Why would you like this to be added**:
This can help us avoid unexpected dependencies updates and make sure we ship stable versions of Telescope.

**Comment by humphd** [comment]
We're going to try using pnpm, so this isn't needed any more.  Closing.
