### ISSUE TITLE
Issue in emailsender.js

### ISSUE THREAD

**Issue by neilong31** [Seneca-CDOT/telescope#226]
it seems like const transporter = nodemailer.createTransport('SMTP', {  is an old format which is failing on the Travis Ci. 
You can remove the 'SMTP to make it const transporter = nodemailer.createTransport({
This works the same way, was just trying to be more explicit
Not sure if we should leave it or change it once we get the SMTP credentials

_Originally posted by @RyanWils in https://github.com/Seneca-CDOT/telescope/pull/198#issuecomment-554545444_

email-sender.js is currently failing it's tester. It says that it cannot create property of mailer from the string we are giving, which is 'STMP' What do you guys think we should change or leave it?
![emailsenderbug](https://user-images.githubusercontent.com/31993023/68979009-5b040600-07ca-11ea-83e3-822b3ced7dcb.png)

**Comment by RyanWils** [comment]
I can create a PR for it. Nodemailer had a parameter where you can specify which connection you want to connect to to be more explicit. I will change it to the original 

Original from https://nodemailer.com/about/
![image](https://user-images.githubusercontent.com/49354833/68979470-a79c1100-07cb-11ea-8163-812009478325.png)
