### ISSUE TITLE
See if we can use the new GitHub container registry

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2264]
I've looked at this before, but I don't think the Seneca-CDOT org could use this.  Maybe we can now? https://github.blog/2021-06-21-github-packages-container-registry-generally-available/

**Comment by Grommers00** [comment]
I'll take a look at this!

**Comment by humphd** [comment]
I would love to see this happen.  In the Gitpod work we're feeling the startup cost of building so many containers.

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

It's possible that this will require us to move the repo to a new ORG that supports the container registry.  I'll do that if we have to, but I won't start by doing it.

**Comment by humphd** [comment]
I think this is a dupe of #1743.
