### ISSUE TITLE
No margin between author name and date

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#2299]
There's no margin between an author's name (when it's a long name) and a post's published date. 

![image](https://user-images.githubusercontent.com/23108901/132935048-28eb91b0-0457-4a0d-b379-11e2c0bf550b.png)

**Comment by lyu4321** [comment]
Hi @manekenpix , I'd like to try working on this if no one else is.

**Comment by humphd** [comment]
@lyu4321 yes, go for it.
