### ISSUE TITLE
Add number of lines added feature for each github PR / blog 

### ISSUE THREAD

**Issue by smilegodly** [Seneca-CDOT/telescope#23]
This counts the lines of code added and deleted and gives a result (added-deleted), for each blog post that links a Github PR..

**Comment by humphd** [comment]
I really love this idea.  When people blog about GitHub repos, issues, or PRs, we can use the [GitHub API](https://github.com/octokit/rest.js/) to pull in extra info and display it along with the post!.

I've done a bit of work like this in the past with https://github.com/humphd/github-contrib-stats, and I know others in the class have done eve more with https://github.com/Seneca-CDOT/ostep-dashboard.  Maybe we can use some of it?

To make this work, we probably need another bug filed first:

Extract all URLs from a blog post.  Once we have all the URLs referenced in a blog, one type can be GitHub URLs, which we can process here.

**Comment by Reza-Rajabi** [comment]
'Extract all URLs from a blog post. Once we have all the URLs referenced in a blog, one type can be GitHub URLs, which we can process here'.
I am setting an issue for this.

**Comment by manekenpix** [comment]
Thanks for the idea. I'm closing this issue now and we can open a new one if/when we decide to add this in the future.
