### ISSUE TITLE
Infinite SAML requests/redirects can lock up server

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2315]
Twice today I've seen prod and staging stop processing feeds.  When I want to Portainer and looked at the logs for Telescope, it shows the same thing: passport SAML objects being dumped to the logs.  Probably this is an error handler somewhere in the authentication/authorization code logging during an exception.  This is probably worth investigating, as it might point to some kind of hack attempt, or at the very least, represent a case we don't want to continue forever.

Restarting the container "fixes" it, but only until it happens again.

**Comment by JerryHue** [comment]
@humphd, how difficult would this be for a beginner to the project like me?

I'm willing to follow any pointers or guidance you have.

**Comment by Grommers00** [comment]
I'll take a look at this if thats okay ^^.

**Comment by Grommers00** [comment]
@humphd do you remember what container it happened on?

**Comment by humphd** [comment]
@Grommers00 OK, thanks for looking into this.  I'm in the same boat.  We'll leave this open for a bit and close if we don't see it again.

**Comment by humphd** [comment]
I'm going to close for now.  Let's open a new bug if this happens again.

**Comment by Grommers00** [comment]
Sounds good.
