### ISSUE TITLE
Update to react-icons ^4.3.1

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2329]
We were [broken by react-icons version 4.3.0](https://github.com/Seneca-CDOT/telescope/issues/2324), which we patched temporarily by [pinning the last-known-good version, 4.2.0](https://github.com/Seneca-CDOT/telescope/commit/c38f1b1adf54bcd901822391a7d6d3b602b832cc).  A new version, [4.3.1](https://github.com/react-icons/react-icons/releases/tag/v4.3.1), was pushed last night to fix the underlying issue. Let's get back on to latest and use `^4.3.1`.

This should be done by someone new to the project.

**Comment by Semin-J** [comment]
Hello @humphd ,
If no one is working on this yet, can I work on this one?

**Comment by SandraBiros** [comment]
Hello, Can I work on this issue ?

**Comment by humphd** [comment]
@Semin-J sure, you can take it.  @SandraBiros, I'll let @Semin-J try it first, since they asked first.
