### ISSUE TITLE
Parser is too aggressive with marking feeds invalid

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2332]
It looks like my blog has been marked invalid:

```
[ 2021-10-04 01:12:13.147 ] INFO (40 on 5bf8aa103cfd): Skipping resource at http://blog.humphd.org/tag/seneca/rss/. Feed previously marked invalid
```

I know this has happened to @raygervais in the past, too.  We need to tune our code for setting feeds invalid, see callers of https://github.com/Seneca-CDOT/telescope/blob/29951b7b60fa33d83e14b05f24d4a4c2722f9ef7/src/backend/index.js#L46-L55.

**Comment by humphd** [comment]
Discussing with @manekenpix and we also wonder if https://github.com/Seneca-CDOT/telescope/commit/71fd28e1e4e88001a02bfd7f447a75c284d60419 is helping with this on staging right now (prod doesn't have it yet).

**Comment by raygervais** [comment]
I was just convinced that my blog didn't make the Telescope™️  quality standard 🤣
