### ISSUE TITLE
Show correct dev/prod status info on front-end

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2357]
In #2356 we're adding a link to the Status API service on the front-page.  Currently, it's hard-coded to the prod instance, https://api.telescope.cdot.systems/v1/status.  Let's define `STATUS_URL` in the env and set it to this or https://dev.api.telescope.cdot.systems/v1/status (i.e., staging) and pass it through to the front-end, and define it in [config.ts](https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/config.ts).  We can then use this dynamic URL in staging or production to pick the right service URL.

Doing this requires an update very similar to what was done for the `SEARCH_URL` variable in #2140.

We'll also need an update to Vercel to add this variable to the list of env variables defined for our PR previews.

**Comment by HyperTHD** [comment]
Taking this one as I have done this previously with the posts, and search service in the aformentioned PR. Not sure how the vercel update would work but doesn't sound too difficult
