### ISSUE TITLE
Extract GitHub URLs from posts before rendering

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2361]
In #2360 @menghif is working on some new UI to render GitHub info for a post in the sidebar, below the author's name and date.  We need to get data into that component, which means we have to transform the post's raw HTML into a list of URLs, and then extract only the GitHub URLs (removing duplicates).

We can probably use `DOMParser` and `parseFromString()` to create an HTML document that we can query for `links`, see https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString#examples.

All GitHub URLs start with `https://github.com/` so that could be used to filter things out.

We render a post here: https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/components/Posts/Post.tsx and `post.html` contains the HTML we need, see https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/components/Posts/Post.tsx#L323.

Once we have this, we need to connect to the stuff in #2360 so it will render properly.

**Comment by Andrewnt219** [comment]
@humphd I'd like to help.

**Comment by humphd** [comment]
@Andrewnt219 that's just quick pseudo-code, you can do it however makes sense.  Essentially, I want to go from `post.html` to having the various GitHub data sorted into types, with dupes removed.
