### ISSUE TITLE
Include more details about Issue and Pull Requests in title attribute

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2374]
In #2367 we're adding GitHub info do a post.  We show Issues and Pull Requests discussed in a post as numbers only.  This is good for the space we have available, but when we hover over them, it would be good to add more detail.

For example, if a post talks about 2 or more repos, and then shows Issues and Pull Requests, which repo do they go with?  Instead of using `Issue #...` in the `title` attribute on hover, let's also include the repo details (user/org + repo name): `user/repo Issue#...`.  Same for Pull Requests and [Commits](https://github.com/Seneca-CDOT/telescope/issues/2372).

**Comment by HyperTHD** [comment]
I assume this is waiting for #2367 to go through, I'll take this on once that PR gets merged in if that's okay

**Comment by humphd** [comment]
Yeah, we need #2367 to go in first, which I *hope* @menghif is going to do soon...
