### ISSUE TITLE
Improve dark mode code colours

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2377]
Our dark mode isn't great for `<code>...</code>` (i.e., inline) and `<pre><code>...</code></pre>` (i.e., block):

<img width="811" alt="Screen Shot 2021-10-21 at 12 30 18 PM" src="https://user-images.githubusercontent.com/427398/138319486-1e40e7da-da0a-441b-81f0-9fa933fcc37c.png">

We should probably take a look at how GitHub and other sites render code in dark mode, and see what we can borrow.

**Comment by japneetsingh035** [comment]
<img width="499" alt="Screen Shot 2021-10-31 at 4 19 49 AM" src="https://user-images.githubusercontent.com/47236363/139574300-576adb4a-1af6-40da-b25e-f286026e371a.png">

How about this combination. It is actually similar to GitHub & dev. Please let me know!

**Comment by humphd** [comment]
The red on black isn't great for contrast.

I would look at the existing stylesheets that exist for dark-mode with highlight.js:

- https://www.npmjs.com/package/highlightjs-material-dark-theme
- https://draculatheme.com/highlightjs
- etc

**Comment by cindyledev** [comment]
Wow, someone is taking on this age-old issue? Originally #77 We had this working at some point on Telescope. It was added and removed by the Telescope 2.0 group. Maybe you can hunt down someone from that cohort who knows more... https://github.com/Seneca-CDOT/telescope/pull/1637 , as you can see, it was using the Material UI theming thing. We once had a button that we could toggle to switch to dark mode.
