### ISSUE TITLE
Remove duplicate code between Issues, Commits, Repos, PullRequest

### ISSUE THREAD

**Issue by Andrewnt219** [Seneca-CDOT/telescope#2379]
**What would you like to be added**:

As [suggested in #2360](https://github.com/Seneca-CDOT/telescope/pull/2367#discussion_r731383464). These components are quite the same, but there are still many differences in content. Therefore, we can either go with a component exposing many props or just abstract the styling and markup:
```ts
// PullRequest.tsx

<GithubResource.Container>
  <GithubResource.Title text="Pull Request" icon={<PrIcon />} />
  <GithubResouce.List>
    {prUrls.map((url) => (
      <GithubResouce.ListItem key={url}>
        <GitHubResource.Link
          href={`https://github.com${pullRequest}`}
          title={'Pull Request #' + getPullRequestNumber(pullRequest)}
          text={getPullRequestNumber(pullRequest)}
        />
      </GithubResouce.ListItem>
    ))}
  </GithubResouce.List>
</GithubResource.Container>
```

**Why would you like this to be added**:
Improve maintainability.

**Comment by humphd** [comment]
See also #2380 which should help with this.
