### ISSUE TITLE
Travis fails due to Redis error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#238]
The PR in https://github.com/Seneca-CDOT/telescope/pull/212 was merged early, and we aren't actually passing tests on macOS/Windows yet.  The problem seems to be the connection to Redis, here's an example on current `master`:

https://travis-ci.org/Seneca-CDOT/telescope/builds/612670221

We need to figure this out.  Is it due to the URL redis is using (different port on these machines?), or is Redis not actually running?

cc @Manan311, @MusaBajwa, @wajeehsheikh who wrote  and/or approved this.

**Comment by Manan311** [comment]
I wrote this. Redis is running but I couldn't figure out why the test was breaking. I think it might be because of the URL  since you mention it now but I am too sure.

**Comment by humphd** [comment]
I think I have Mac fixed, just trying to figure out Windows...

**Comment by Manan311** [comment]
For windows, can't we install Redis from choco?

**Comment by humphd** [comment]
@Manan311 I got it working.  We also need to install it as a Windows service, and start the service.  PR is up at https://github.com/Seneca-CDOT/telescope/pull/239 if you want to look.  I'll merge once it goes green.

**Comment by Manan311** [comment]
yes, that would be great, sorry for all the trouble I caused but this was a learning experience I will never forget in open source. Also, I want to clarify what do you mean by installing it as a windows service and then starting the service?

**Comment by humphd** [comment]
@Manan311 It's OK, learning how this all works is what we're here for.  The key lessons here are:

- don't land code that's not passing CI.  It will cause chaos for all the other devs who depend on it
- if part of the tests or CI is failing, move that bit to a new PR vs. landing everything at once
- make sure that tests pass vs. just installing packages.  Redis was installed, but not running

RE: starting the service.  You were installing `redis-64` via `choco`, which is right.  But that only puts the files in the VM.  It doesn't start the server.  We have to also start the `redis-server` as a Windows Service (like a daemon on Linux):

```
choco install redis-64
redis-server --service-install
redis-server --service-start
```

How did I know all this?  I didn't.  I don't use Windows (partly because of headaches like this!).  I just did a lot of reading tonight, and you can too.  Don't be afraid to research deeply.
