### ISSUE TITLE
Create HTTP redirects in nginx to autodeployment servers

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2383]
We run autodeployment servers on port `4000` on both staging (https://dev.telescope.cdot.systems:4000) and production (https://telescope.cdot.systems:4000).  From these, you can get access to a few things:

- build logs at `/log`: https://dev.telescope.cdot.systems:4000/log and https://telescope.cdot.systems:4000/log
- current status info at `/status`: https://dev.telescope.cdot.systems:4000/status and https://telescope.cdot.systems:4000/status

I can never remember the port number to access these, and it would be great if we added a redirect in nginx for something like https://dev.telescope.cdot.systems/deploy and https://telescope.cdot.systems/deploy or something, so it's easier to get to them.

Our nginx configs live in https://github.com/Seneca-CDOT/telescope/tree/master/config.  You can see an example of what a redirect looks like here:

https://github.com/Seneca-CDOT/telescope/blob/master/config/nginx.conf.template#L171-L176

**Comment by AmasiaNalbandian** [comment]
I'd like to grab this but might need more info tomorrow after I investigate further.

**Comment by humphd** [comment]
Sure, ask on Slack in #telescope and we can help you.

**Comment by manekenpix** [comment]
@humphd  Since #2455 got merged, do we still need this?

**Comment by humphd** [comment]
Yeah, let's add it.  I think it's helpful to not have to remember a magic number

**Comment by AmasiaNalbandian** [comment]
@humphd Wanted some feedback about what the route name should be for redirection? Should we do something like https://dev.telescope.cdot.systems/servers? I'm not sure if there are other servers being hosted for auto deployment.
