### ISSUE TITLE
Autodeployment server not remembering previous build info

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2384]
In https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/builds.js#L79-L80 and https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/builds.js#L68-L71 we have a bug where we don't set the ` builds.previous` to be the current build when changing to a new build, thus losing track of that info.

If you go to our autodeployment server's `/status` endpoint, you'll see that `previous` is always `null`:

- staging https://dev.telescope.cdot.systems:4000/status
- prod https://telescope.cdot.systems:4000/status

We should take whatever is `current` and move it to `previous` so we don't lose it.

**Comment by dhillonks** [comment]
@humphd Can I work on this?
