### ISSUE TITLE
Update to nextjs 12

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2401]
https://nextjs.org/blog/next-12 is out, let's update:

- Rust Compiler: ~3x faster Fast Refresh and ~5x faster builds
- Middleware (beta): Enabling full flexibility in Next.js with code over configuration
-  React 18 Support: Native Next.js APIs are now supported, as well as Suspense
-  `<Image />` AVIF Support: Opt-in for 20% smaller images
-  Bot-aware ISR Fallback: Optimized SEO for web crawlers
- Native ES Modules Support: Aligning with the standardized module system
- URL Imports (alpha): Import packages from any URL, no installs required
- React Server Components (alpha): Try it today, including SSR streaming

Here's the [upgrade guide](https://nextjs.org/docs/upgrading)

**Comment by DukeManh** [comment]
I'd be interested in taking a look at the good stuff of  NextJS 12.

**Comment by humphd** [comment]
@DukeManh you asked for this to be assigned 2 weeks ago, are you still working on it?  If not I'll un-assign so someone else can work on it.  What's the status?

**Comment by DukeManh** [comment]
I was looking at the [upgrade guide](https://nextjs.org/docs/upgrading) and thinking we only have to update NextJS, React dep, and replace Babel with SWC by removing `babel.config.js`. The other things like React Server Components and URL Imports, etc are features that we should file separate issues explore their usage in our project.

I will put up a PR for upgrading dependencies soon.
