### ISSUE TITLE
Add live build logs in status dashboard

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2415]
In #2395 we are adding an expanded status service dashboard. One thing I want to include in it is the ability to see live build logs from the [autodeployment server](https://github.com/Seneca-CDOT/telescope/tree/master/tools/autodeployment), which are exposed at `/log`, for example:

- staging is https://dev.telescope.cdot.systems:4000/log
- production is https://telescope.cdot.systems:4000/log

If there's no current build, it returns a 404, otherwise it streams the build log live.  I'd like to use [xterm.js](https://xtermjs.org/) to show a terminal with live output in the dashboard, similar to what happens when you look at build output for GitHub Actions or other CI builders.

I've started doing this in the past in React, but never finished the code, see my [autodeploy-ui branch](https://github.com/humphd/telescope/tree/autodeploy-ui), and [these files](https://github.com/humphd/telescope/tree/autodeploy-ui/tools/autodeployment/src/web) in particular.  For the new dashboard, this needs to get rewritten to be straight HTML/CSS/JS, but the logic for how I use xterm and the live build log stream is something you could borrow:

https://github.com/humphd/telescope/blob/autodeploy-ui/tools/autodeployment/src/web/components/BuildLog.js

**Comment by Andrewnt219** [comment]
@humphd I want to help with this feature.

**Comment by humphd** [comment]
Excellent!  Here are my notes on what I did, but feel free to improve:

1. We'll need to poll the [`/log` endpoint](https://github.com/humphd/telescope/blob/autodeploy-ui/tools/autodeployment/src/web/api.js#L23) every so often to see if we're building.  We could also use the `/status` endpoint to get better data (which commit we're building, who wrote it, etc).  I played around with a build header that mimics what GitHub does: https://github.com/humphd/telescope/blob/autodeploy-ui/tools/autodeployment/src/web/components/BuildHeader.js
2. Once you know there is a build, we need to read the streaming log to get processed via a Reader, see https://github.com/humphd/telescope/blob/autodeploy-ui/tools/autodeployment/src/web/api.js#L32 and https://github.com/humphd/telescope/blob/autodeploy-ui/tools/autodeployment/src/web/components/BuildLog.js#L61-L80.
3. We need an xterm in the page: https://github.com/humphd/telescope/blob/autodeploy-ui/tools/autodeployment/src/web/components/BuildLog.js#L33-L55
4. As the data streams into the reader, we need to write it to the terminal: https://github.com/humphd/telescope/blob/autodeploy-ui/tools/autodeployment/src/web/components/BuildLog.js#L75

I'm not sure if we should do this in a separate page on the admin dashboard (e.g., add a "Build" link to the sidebar that opens a build.html page)?  That might make sense, since build logs are long vertically.  But we could also try putting the terminal in the main dashboard.

Let me know if you have other questions.
