### ISSUE TITLE
Add live build status details in status dashboard

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2416]
In #2395 we are adding an expanded status service dashboard. One thing I want to include in it is the ability to see build status info from the autodeployment server, which is exposed at `/status`, for example:

- staging is https://dev.telescope.cdot.systems:4000/status
- production is https://telescope.cdot.systems:4000/status

@dhillonks started improving the code related to this in #2392.  Now I want to use it to go further. This returns a JS object with previous, current, and pending build details.  Any/all of these can be `null`, or a full JS object that we cache from the GitHub API.

Our dashboard should show some of this data in a visual way.  Things that might be interesting are:

- the git SHA that is/was built
- who pushed the code (i.e., `pusher`)
- who wrote the code (i.e., `sender` or maybe `author`, not sure)
- a link to the `compare` branch to see what changed 
- when the build started (`startedDate`)
- when the build stopped (`stoppedDate`)
- what the result code of the build was (e.g., 0 is "good" and non-zero is an "error")

**Comment by humphd** [comment]
@mqnguyen5 is going to take this.

**Comment by mqnguyen5** [comment]
@humphd Can you give me a walkthrough of what should be done?

**Comment by humphd** [comment]
There are two places where this info could go:

1. The first is to add a new widget card to the Dashboard that shows a detailed view of all we know about the previous and next builds (see list above).
2. The second would be to add a header across the top of the build log page (e.g., above the log terminal) showing details about who did what, with links, avatar, detailed info, etc.

Here's how GitHub does that:

<img width="932" alt="Screen Shot 2021-11-22 at 1 50 39 PM" src="https://user-images.githubusercontent.com/427398/142918553-7d124775-196f-4798-a776-b978fe4e33f0.png">

You might start with a card on the Dashboard that updates every minute or so, and gets the latest build info, then formats it to display all the details about what happened (or is happening).

**Comment by mqnguyen5** [comment]
I just need to build upon the code in [here](https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/builds.js) right?

**Comment by Andrewnt219** [comment]
@mqnguyen5 no, it should be a new js file inside [build-log](https://github.com/Seneca-CDOT/telescope/tree/master/src/api/status/public/js/build-log). Call it `build-header.js`

>staging is https://dev.telescope.cdot.systems:4000/status
production is https://telescope.cdot.systems:4000/status

IWhen you goes to these links, you can see the response JSON has all the details under `githubData`.

**Comment by mqnguyen5** [comment]
Hi, after spending some time working on the code, I managed to do it like this:

```js
const autodeploymentUrl = (path) => `//dev.api.telescope.cdot.systems:4000/${path}`;

export default async function getBuildStatus() {
  try {
    const res = await fetch(autodeploymentUrl('status'));
    if (!res.ok) {
      throw new Error('unable to get build info');
    }
    const data = await res.json().githubData;

    return {
      gitSHA: data.previous.ref,
      pusher: data.previous.pusher.name,
      sender: data.previous.sender.login,
      compare: data.previous.compare,
      startedDate: data.previous.startedDate,
      stoppedDate: data.previous.stoppedDate,
      resultCode: data.previous.code,
    };
  } catch (err) {
    console.error(err);
  }
}
```

I would really appreciated if someone can let me know if I'm on the right track. Thanks

**Comment by humphd** [comment]
Looks like you're heading in the right direction to me.  I would make this change:

```js
const { githubData } = await res.json()
```

Also, your `catch` is going to need to do more than just log an error (e.g., we'll have to show this in the UI as well).

**Comment by mqnguyen5** [comment]
<img width="1084" alt="Screen Shot 2021-12-01 at 10 52 49 PM" src="https://user-images.githubusercontent.com/59778930/144354666-505bd5d4-b2d1-4728-9da3-d7fe129c6d7e.png">

Messing around with the design, @humphd what do you think of it?

**Comment by humphd** [comment]
Keep going, it's looking cool.

**Comment by humphd** [comment]
One thing, if the build is currently happening, we should include some icon/animation.  Maybe instead of Start Date/Stopped Date, we have something like whether it's happening or not, and how long its been running.  If it's stopped, how long it took and when it stopped.

**Comment by humphd** [comment]
<img width="927" alt="Screen Shot 2021-12-01 at 10 58 39 PM" src="https://user-images.githubusercontent.com/427398/144355143-589806cf-9fe9-4860-9156-2457b14aeaad.png">

Consider how GitHub does it.

**Comment by mqnguyen5** [comment]
Alright, I'll see what I can do
