### ISSUE TITLE
Add GitHub stats to our status dashboard

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2417]
In #2395 we are adding an expanded status service dashboard. One thing I want to include in it is the ability to see various statistics about our `Seneca-CDOT/telescope` and `Seneca-CDOT/satellite` repos.  The GitHub API can be used to query various stats, see https://docs.github.com/en/rest/reference/repos#statistics.

Let's query GitHub for this and present some useful details visually in the dashboard.

**Comment by menghif** [comment]
I would like to try this! Any suggestions on what GitHub stats we are looking for?

**Comment by humphd** [comment]
Maybe total contributor count, weekly vs all time/yearly counts of commits, etc.  See what kinds of data you can get from the GitHub API and experiment.  It's always nice to see various numbers growing, and for us to have a way to look at the size and health of the community.
