### ISSUE TITLE
Show Posts count on status dashboard

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2419]
In #2395 we are adding an expanded status service dashboard. One thing I want to include in it is the ability to see the current number of Posts and Feeds in the database.  We expose this data as a header when you query for `/posts` or `/feeds` from the Posts service:

https://github.com/Seneca-CDOT/telescope/blob/master/src/api/posts/src/routes/posts.js#L55

Let's add a widget to the dashboard that shows the current counts for each of these.

**Comment by nguyenhung15913** [comment]
Hi David. I am interested in this issue. But I am quite new with NextJS and this project. Could you please explain to me how can I access the dashboard page?. Thanks

**Comment by humphd** [comment]
The Dashboard lives in https://github.com/Seneca-CDOT/telescope/tree/master/src/api/status, specifically in https://github.com/Seneca-CDOT/telescope/tree/master/src/api/status/public.  We have a generic dashboard there now, which is being worked on by various people.

The idea here would be to write some JS to `fetch()` this info from the Posts service, then show it in a widget.  We return an `x-total-count` header with the number when you request `/v1/posts`, for example on staging:

```sh
❯ curl -i https://dev.api.telescope.cdot.systems/v1/posts
HTTP/2 200
server: nginx
date: Tue, 09 Nov 2021 00:38:01 GMT
content-type: application/json; charset=utf-8
content-length: 2611
vary: Accept-Encoding
access-control-allow-origin: *
...
x-total-count: 4713
```

We need to add this for feeds, so you could start with Posts count.

**Comment by tuanthanh2067** [comment]
Response returned from `/feeds` is the same as from `/posts` right?

**Comment by tuanthanh2067** [comment]
Can I try this issue?

**Comment by humphd** [comment]
@tuanthanh2067 it looks like @nguyenhung15913 already asked, but I can see 2 parts to this:

- show the current Posts count in the Dashboard
- show the Feeds count in the Dashboard

The Feeds are available as a header at https://dev.api.telescope.cdot.systems/v1/posts/feeds (that's staging).

So I'll give this one to @nguyenhung15913 for the Posts count, and @tuanthanh2067 you can file another similar issue for the Feeds count, and assign to yourself.

**Comment by tuanthanh2067** [comment]
Great, sure!

**Comment by nguyenhung15913** [comment]
Hi @humphd , I reviewed the code and realized that due to the CORS, I could only access some certain headers but not the X-TOTAL-COUNT (return null). I did some research and they say that we can only fix in the server. Are there other ways? And also is there any specific route to the dashboard ("/dashboard") so that it will be much easier to add front-end features. I have been trying to find it but still have not seen one.

**Comment by humphd** [comment]
You can change the server here to allow this https://github.com/Seneca-CDOT/telescope/blob/master/src/api/status/src/server.js#L12

**Comment by nguyenhung15913** [comment]
@humphd How about the specific route to the dashboard? is there something like localhost:8000/dashboard?

**Comment by tuanthanh2067** [comment]
I'm sorry but what's the staging server?

**Comment by humphd** [comment]
Staging is https://dev.api.telescope.cdot.systems

**Comment by humphd** [comment]
I think you want to use `process.env.API_URL` which is defined in https://github.com/Seneca-CDOT/telescope/blob/master/config/env.production#L21, and for local development you can add a variable to https://github.com/Seneca-CDOT/telescope/blob/master/src/api/status/env.local to expose the proper hostname.  The proper format looks like this https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src#sources
