### ISSUE TITLE
Add search bar for the mock-ups

### ISSUE THREAD

**Issue by cyh0968** [Seneca-CDOT/telescope#242]
It seems like that the telescope has its search bar to search the participant. However, it is uncomfortable to find the search bar. I think we should expose the search bar on the top always in mobile and desktop environments. For instance, the GitHub site has a search bar on the top, so we don't have to look for it. With one click, we can search whatever we want.

**Comment by ODAVING** [comment]
I'll take on this issue.

**Comment by humphd** [comment]
I'd love to see some issues filed to figure out how we'll use this Search feature in the backend.  What are you searching for when you use it?  How should we index things to give you that data? How are results displayed, etc.  Needs more thought and issues filed.
