### ISSUE TITLE
Add GitHub avatars for users mentioned in posts

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2421]
@menghif, @Andrewnt219, and @HyperTHD have been iterating on extracting and displaying GitHub info in the sidebar of a post.  Today I thought of another one that would be nice: showing the people that are referred to.  Consider this post:

<img width="1014" alt="Screen Shot 2021-10-30 at 10 54 19 AM" src="https://user-images.githubusercontent.com/427398/139542408-78d4d1be-b9ab-4c22-8d19-4602eb5cdaa2.png">

Here we have a GitHub user URL: https://github.com/aserputov

If we append `.png` to it, we will get (redirected to) the avatar:

![https://github.com/aserputov.png](https://github.com/aserputov.png)

If we add a `?size=` we can set the size, for example 25px:

![https://github.com/aserputov.png?size=25](https://github.com/aserputov.png?size=25)

If we throw that in an avatar component (to make it rounded), we could include a "Users" section too.

**Comment by Andrewnt219** [comment]
Are users shown only when it's `github.com/user`? Or `github.com/user/repo/isssue/1` is counted as well (like what we did with repos)?

**Comment by humphd** [comment]
It's a good question.  It could be good to always show them all, or might get overwhelming.  Probably worth doing a test with both.  Easy to start with everything, and then limit it later?

This might be a good issue for us to give someone new, who hasn't hacked on this code, and you three can mentor and review.

**Comment by AmasiaNalbandian** [comment]
I can take this on please.

**Comment by humphd** [comment]
Go ahead, @AmasiaNalbandian.  @Andrewnt219, @menghif, and @HyperTHD can answer questions or provide reviews.

**Comment by AmasiaNalbandian** [comment]
Am i complicating this, or is there a way to grab the github username of the individual from a post? Right now I see there's three interfaces under index.js (feed, post, signupform). If there's a way to grab the feed author and then look up that user and grab their github username/url to construct the link to their image on github?

**Comment by humphd** [comment]
You don't need to do any backend work for this.  Look at the various GitHub components in https://github.com/Seneca-CDOT/telescope/tree/master/src/web/src/components/Posts.  You're making something just like these, but for users vs. commits/pull requests/issues.

**Comment by AmasiaNalbandian** [comment]
Right but commits/pr/issues were parsed from the blog posts from DOM. I'm not sure there's any reference in the post to parse the github user.

**Comment by humphd** [comment]
All the URLs that are extracted out will be of the form:

```
https://github.com/user/repo/*
```

So you `https://github.com/user` for each, and you're done.  Throw them in a `Set` to deal with duplicates, and then turn that into an array, `map()` it to produce the `.png` version, and put into components.

**Comment by AmasiaNalbandian** [comment]
I've misunderstood what I am changing. I think I get it now. So we want a new section with all people involved through GitHub links in the post. Should we add it's own section and call it something like "contributors" or "mentioned"

**Comment by humphd** [comment]
I think `Users` and use the GitHub icon https://react-icons.github.io/react-icons/search?q=github

**Comment by AmasiaNalbandian** [comment]
OK sounds good. Sorry about that. I thought we're pulling in the post author's github image.

**Comment by humphd** [comment]
@AmasiaNalbandian we have code for that, but it's blocked on other things in the db.
