### ISSUE TITLE
Student Quote changes on scroll

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2423]
In #2422 we added a way for the student quote to be randomly changed on the front page.  However, it's not stable per load, and changes when I scroll the page (i.e., new random number is generated on re-render).

Steps to Reproduce:

1. Go to https://dev.telescope.cdot.systems/
2. Scroll down a few inches, then back up, then down
3. Notice the quote changes over and over again

We need to deal with this function and return value differently:

```js
const getQuote = () => {
  return quotes[Math.floor(Math.random() * quotes.length)];
};
```

We need that value to be stable across renders. cc @AmasiaNalbandian

**Comment by DukeManh** [comment]
Looks like we'd have to return memoized value of the function.

**Comment by humphd** [comment]
Or put it in state.

**Comment by AmasiaNalbandian** [comment]
No worries - We can put it in state. Where are the states handled in the codebase? @humphd

**Comment by humphd** [comment]
Probably something like:

```ts
const [quote] = setState(() => getQuote());
```

We won't need a `setQuote` function, so ignore.  @DukeManh may have another suggestion.

**Comment by tuanthanh2067** [comment]
@humphd hi, I have a suggestion for this issue.

```jsx
  const studentQuote = useMemo(() => {
    return getQuote();
  }, []);
```

**Comment by humphd** [comment]
We can memoize, but typically the recommendation for `useMemo` is that it be used for expensive operations, whereas this is really just state that's not being updated.

To be honest, either is fine.

**Comment by tuanthanh2067** [comment]
Oh I see

**Comment by AmasiaNalbandian** [comment]
Kindly assign this to me, I will fix the bug using state.

**Comment by humphd** [comment]
Done.  Thank you for continuing to improve this.

**Comment by HyperTHD** [comment]
Another thought, we can use the `useRef()` hook. It has an interesting property of memoization similar to useMemo, however, it doesn't cause a re-render. Ik it's pretty niche, but something to also consider

**Comment by humphd** [comment]
I think we're over thinking this.  We just want to set some state in the app that doesn't change.  This is exactly what `useState()` is for.

**Comment by DukeManh** [comment]
Not to make this more complicated but I think the easiest way is to not use any hook and generate `studentQuote` inline.
```
const studentQuote = quotes[Math.floor(Math.random() * quotes.length)]

```

**Comment by DukeManh** [comment]
> Not to make this more complicated but I think the easiest way is to not use any hook and generate studentQuote inline.

Generate if outside of the component.

**Comment by humphd** [comment]
> Not to make this more complicated but I think the easiest way is to not use any hook and generate `studentQuote` inline.
> 
> ```
> const studentQuote = quotes[Math.floor(Math.random() * quotes.length)]
> ```

Yes, that makes sense.

**Comment by humphd** [comment]
@AmasiaNalbandian you asked for this 3 weeks ago, should I leave it with you or unassign so someone can fix?  What's the status?
