### ISSUE TITLE
Update Traefik to newer version

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2424]
We're currently [using version `v2.4.5`](https://github.com/Seneca-CDOT/telescope/blob/master/docker/docker-compose.yml#L256) of [Traefik](https://traefik.io/), and there's a [newer version available for `v2.5.x`](https://hub.docker.com/_/traefik).  Let's check the changelog and see if any will break us, and try updating.

**Comment by Qiwen-Yu** [comment]
@humphd Hi, can I take this issue?

**Comment by humphd** [comment]
All yours, @Qiwen-Yu.

**Comment by manekenpix** [comment]
@Qiwen-Yu any progress with this issue?

**Comment by Qiwen-Yu** [comment]
Hi, I am still working on this.

**Comment by Qiwen-Yu** [comment]
@humphd, in my local setup, I ran `docker run -d -p 8080:8080 -p 80:80 \
    -v $PWD/traefik.yml:/etc/traefik/traefik.yml traefik:v2.5` in terminal after install docker and docker-compose. But I am not sure if I did it correctly.

**Comment by humphd** [comment]
Please use "Fixes #..." vs. "Fix issue #..." so that GitHub autocloses.

**Comment by Qiwen-Yu** [comment]
Sorry, I should've used `Fixes #`.
