### ISSUE TITLE
Pass Gitpod urls to the frontend

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2427]
With the change from #2406, when a Gitpod workspace starts, images are built correctly but our frontend is making requests to `localhost`. We need to find a way to pass gitpod URLs to Next in build time.

I've tried to pass URL through build arguments but we prefer a monkey-patching approach where we don't have to touch the current configuration.

A way to do this would be generate an `env.gitpod` when gitpod starts with the URLs being `gp URL PORT`.

**Comment by humphd** [comment]
@DukeManh assigned to you.

**Comment by DukeManh** [comment]
Responsibility!

**Comment by DukeManh** [comment]
I'll continue hacking once I catch up with all the due dates coming.

**Comment by humphd** [comment]
cc'ing @raygervais and @cindyledev, who might have time and wisdom here.

**Comment by humphd** [comment]
Looks like the GitPod integration is working:

<img width="920" alt="Screen Shot 2021-10-31 at 10 27 21 PM" src="https://user-images.githubusercontent.com/427398/139613238-3b4396cb-6d8e-47d5-b348-24dc8b2e37fb.png">

New PRs get this button attached, see https://github.com/Seneca-CDOT/telescope/pull/2428 for example.

Question: any issues having this here without it working fully?

**Comment by humphd** [comment]
Filed #2429 to properly document this.

**Comment by DukeManh** [comment]
> Question: any issues having this here without it working fully?

We could test the frontend on it using `env.staging` and run `npm run dev`.
The doc could mention this too, like you don't have to wait for docker build if only testing the frontend.
