### ISSUE TITLE
Add documentation on how to use GitPod to develop/run the code

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2429]
We recently added support for [GitPod](https://www.gitpod.io/) in #2406.  It's not fully ready yet (see #2427), but it's close, and the integration is complete in the repo, see https://github.com/Seneca-CDOT/telescope/issues/2427#issuecomment-955874717.

We need to properly document this, so our devs know what this is, what the implications are of using it, and how to make it all work.  I especially want to make sure people don't run afoul of any pricing issues (you get 50 hours a month for free, which is probably perfect for students fixing a few issues), and know what they are clicking.

cc @DukeManh, @cindyledev.

**Comment by humphd** [comment]
- https://www.gitpod.io/docs
- https://www.gitpod.io/docs/getting-started

**Comment by humphd** [comment]
Might be nice to add a README badge too, see https://community.gitpod.io/t/is-there-any-open-on-gitpod-badge-that-i-can-just-copy-and-paste/989/6

**Comment by humphd** [comment]
Here are some things I ran into when I tried using it, which we might be able to document:

https://github.com/Seneca-CDOT/telescope/pull/2439#issuecomment-958616206

I also had questions that we should answer:

- how to turn off/stop/delete the workspace?

**Comment by DukeManh** [comment]
Seeing how many people struggling to get started, I will write a quick doc for this.

**Comment by cindyledev** [comment]
Ping me for review
