### ISSUE TITLE
Customize the dashboard so it looks like it belongs to Telescope

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2433]
Our new Dashboard is landed and running, see https://dev.api.telescope.cdot.systems/v1/status:

<img width="1389" alt="Screen Shot 2021-11-01 at 11 17 34 AM" src="https://user-images.githubusercontent.com/427398/139695602-7001617c-91a9-4fc5-b801-7ad7055e9bdb.png">

Let's fix some things so it looks and feels more like Telescope.  Here are some initial things to be fixed:

- use the Telescope logo
- use the Telescope favicon
- Change "Material Dashboard 2" to "Telescope Dashboard"
- Get rid of "Upgrade to Pro" button
- Get rid of copyright and other links in the footer
- Change the primary colour from redish/purple to use the primary Telescope colour

Plus any other small things that make sense.  This page should look like it belongs to the Telescope project when you're done.  Make sure you use the classes and utilities provided by the template, see docs at https://demos.creative-tim.com/material-dashboard/docs/2.1/getting-started/introduction.html

**Comment by suhhee1011** [comment]
Hi @humphd, Can I work on this issue?

**Comment by humphd** [comment]
Yes @suhhee1011, go for it.

**Comment by suhhee1011** [comment]
- [ ] use the Telescope logo
- [ ] use the Telescope favicon
- [ ] Change "Material Dashboard 2" to "Telescope Dashboard"
- [ ] Get rid of "Upgrade to Pro" button
- [ ] Get rid of copyright and other links in the footer
- [ ] Change the primary colour from redish/purple to use the primary Telescope colour
