### ISSUE TITLE
Outdated dependencies for package.json in Feed Discovery Service

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#2437]
Related #2387 #2389 #2404

// src/api/feed-discovery/package.json
```
Package                   Current       Wanted       Latest  Location                            Depended by
@senecacdot/satellite      1.16.0       1.17.0       1.17.0  node_modules/@senecacdot/satellite  feed-discovery
cheerio                1.0.0-rc.9  1.0.0-rc.10  1.0.0-rc.10  node_modules/cheerio                feed-discovery
nodemon                     2.0.7       2.0.14       2.0.14  node_modules/nodemon                feed-discovery
```

**Comment by hphan9** [comment]
Hi Cindy, Can I work on this issue?

**Comment by hphan9** [comment]
Hello @humphd  and @cindyledev , I checked the // src/api/feed-discovery/package.json. It seems like the file is updated:
```
 "@senecacdot/satellite": "^1.x",
   "cheerio": "^1.0.0-rc.5",
   "nodemon": "^2.0.15"
```
Maybe we don't need this issue.

**Comment by humphd** [comment]
Great, thanks for confirming this.  Do we have any other issues that should be closed that are similar?

**Comment by hphan9** [comment]
this issue #1897  https://github.com/Seneca-CDOT/telescope/issues/1897 might be similar but it is not fixed. I can take that issue.
