### ISSUE TITLE
Consider removing scroll snap on the front page

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2445]
I wanted to file this issue for a while now. In #2080, I introduced scroll-snap-like behavior on the landing page as suggested by #2042. 
However, due to Telescope's layout, we couldn't use CSS scroll snap to do that but rather had a hacky solution by using an `IntersectionObserver` and promised to improve it.
I had been having trouble triggering scroll-snap behavior consistently. Plus it causes unexpected scrolls on mobile sometimes too.
I don't think scroll snap works for us and there's not a good way to simulate that feature.

There's a good article on why not to use this too.
https://alvarotrigo.com/blog/why-not-to-use-css-scroll-snap/

**Comment by manekenpix** [comment]
@DukeManh I like this idea, but we should get more opinions. I'm going to convert this into a discussion here (good opportunity to see how that feature works).
