### ISSUE TITLE
Open all sidebar links in new page.

### ISSUE THREAD

**Issue by menghif** [Seneca-CDOT/telescope#2446]
**What would you like to be added**:

All the new Github links that we added open in a new page but clicking on the blogger's name or the date opens links in the current page.
<img width="259" alt="Screen Shot 2021-11-03 at 12 06 39 PM" src="https://user-images.githubusercontent.com/53121061/140098505-5b23a8fd-ffd4-4ef2-91a3-deb92b428b4b.png">

**Why would you like this to be added**:

This will add consistency to the sidebar behaviour.

**Comment by tuanthanh2067** [comment]
As I know, currently we only blogger's name and the date. What you'd like to add is repos, issues, pull request and commit below the date. Am I correct?

**Comment by menghif** [comment]
That's already implemented: https://dev.telescope.cdot.systems
This issue is just about opening all the sidebar links in a new page

**Comment by humphd** [comment]
We need a `target="_blank"` added for these links

**Comment by ycechungAI** [comment]
can i work on this as backup for release 0.3

**Comment by ycechungAI** [comment]
made the changes and just running npm run test now

**Comment by ycechungAI** [comment]
![image](https://user-images.githubusercontent.com/55400510/141026593-fb0da37c-cc44-4327-aa57-6cecd196c8d5.png)

**Comment by humphd** [comment]
Is there a PR you want me to look at?

**Comment by ycechungAI** [comment]
https://github.com/Seneca-CDOT/telescope/pull/2459

**Comment by ycechungAI** [comment]
just waiting for it to pass, I accidently created the branch on telescope and redo it on my own repo and ran tests again

**Comment by ycechungAI** [comment]
![image](https://user-images.githubusercontent.com/55400510/141147508-6f360394-d64e-42fe-8130-3619df4758f9.png)
not sure why my amend didnt change the repo

**Comment by ycechungAI** [comment]
Looking for someone to review these changes as well (need a 2nd reviewer)

**Comment by humphd** [comment]
@ycechungAI because you didn't use proper syntax in your PR description, this didn't autoclose on merge.  Use `Fixes #....` vs. `#....` in the future.
