### ISSUE TITLE
Add border to avatar

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2449]
I notice that GitHub uses a slight border around the avatars, and we don't:

<img width="163" alt="Screen Shot 2021-11-04 at 9 58 50 AM" src="https://user-images.githubusercontent.com/427398/140327174-80cfde7f-6502-43f3-82df-82eddafd56e8.png">

Let's steal this.  They look wrong without it.

**Comment by tuanthanh2067** [comment]
Can I steal this issue?

**Comment by humphd** [comment]
Go for it, Dustin.
