### ISSUE TITLE
Consider removing scroll snap on the front page

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#2452]
### Discussed in https://github.com/Seneca-CDOT/telescope/discussions/2448

<div type='discussions-op-text'>

<sup>Originally posted by **DukeManh** November  3, 2021</sup>
I wanted to file this issue for a while now. In #2080, I introduced scroll-snap-like behavior on the landing page as suggested by #2042. 
However, due to Telescope's layout, we couldn't use CSS scroll snap to do that but rather had a hacky solution by using an `IntersectionObserver` and promised to improve it.
I had been having trouble triggering scroll-snap behavior consistently. Plus it causes unexpected scrolls on mobile sometimes too.
I don't think scroll snap works for us and there's not a good way to simulate that feature.

There's a good article on why not to use this too.
https://alvarotrigo.com/blog/why-not-to-use-css-scroll-snap/
</div>

**Comment by juuuuuuun** [comment]
Hello, Can I work for it?

**Comment by manekenpix** [comment]
@juuuuuuun all yours.
Here's a discussion about this issue https://github.com/Seneca-CDOT/telescope/discussions/2448

**Comment by humphd** [comment]
@juuuuuuun what's the status of this?

**Comment by juuuuuuun** [comment]
> @juuuuuuun what's the status of this?

Sorry sir still I'm working on it...

**Comment by manekenpix** [comment]
@juuuuuuun any progress here?
