### ISSUE TITLE
Audit tests to replace real network requests with mocks

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#246]
In https://github.com/Seneca-CDOT/telescope/pull/245 we added code to allow a network request to be "mocked."  This means you specify what data should be returned from a network request, and then have a test do the request, but get back your mock/fake data.  This is safer than relying on the real network, since it can fail when you run your tests.

We have a few places where we are currently doing real network requests, and we should switch to using these Mocks.  See also #210.

cc @hansal7014, who might be interested in this, since you are working on the bent to node-fetch code, and this uses node-fetch with Jest to do the mocks.

**Comment by Cadesh** [comment]
Can I give a try on this one?

**Comment by humphd** [comment]
@Cadesh I think you might have done this already, but in case not, please speak with @manekenpix and @c3ho, who have been doing a bunch of this in other issues/prs.
