### ISSUE TITLE
Build Log dashboard should use same layout/CSS as rest of Dashboard

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2461]
The [new Dashboard build log](https://dev.api.telescope.cdot.systems/v1/status) doesn't look like the rest of the Dashboard:

<img width="1285" alt="Screen Shot 2021-11-11 at 9 55 06 PM" src="https://user-images.githubusercontent.com/427398/141401228-3d084181-9ba4-4b11-9f8c-3ba3c0bc4d7c.png">

vs. 

<img width="1276" alt="Screen Shot 2021-11-11 at 9 55 46 PM" src="https://user-images.githubusercontent.com/427398/141401280-d5f97125-e66b-4cd5-b0dc-0c124eb805e0.png">

Let's use the same sidebar, header, footer, etc. and just fill the available space with the terminal.

**Comment by mqnguyen5** [comment]
Can I give it a shot? And, should I wait for #2433 to finish to keep the styling consistent?

**Comment by humphd** [comment]
@mqnguyen5 go for it, and no, don't wait.  We'll adjust once #2433 is merged. cc @suhhee1011

**Comment by suhhee1011** [comment]
Oh I am almost done with the issue #2433 .I am planning to push my code in this weekend. I will comment here if I push my code :)
