### ISSUE TITLE
Automate CI checks for changes to package-lock.json

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#247]
I've been helping people merge code today, and a lot of people struggle to understand how to work with `package.json`, `package-lock.json`, `npm install`, and git.

One thing that we could try is to integrate [Danger JS](https://danger.systems/js/) to help remind people when they need to update it.  It gets run as part of CI, and reports back on things we want people to know about.

```js
const packageChanged = includes(danger.git.modified_files, 'package.json');
const lockfileChanged = includes(danger.git.modified_files, 'package-lock.json');
if (packageChanged && !lockfileChanged) {
  const message = 'Changes were made to package.json, but not to package-lock.json';
  const idea = 'Perhaps you need to run `npm install`?';
  warn(`${message} - <i>${idea}</i>`);
}
```

There's a lot you can set-up to check with a PR.

**Comment by humphd** [comment]
See https://danger.systems/js/guides/getting_started.html

**Comment by c3ho** [comment]
Hi, I’ll take this issue on. I want to try some things that are CI/CD related.

**Comment by c3ho** [comment]
This is so weird as I've rebased multiple times AND ran a npm install.

**Comment by Reza-Rajabi** [comment]
@humphd I am updating the Dockerfile and I need your thoughts about the same issue regarding the `package-lock.json` file. Node.js [documentation](https://docs.npmjs.com/files/package-lock.json) suggests keeping the `package-lock.json` to guarantee all of the developers be using the same dependencies. We might need to force ourselves using `npm update --dev` rather than `npm install`.

I have found the following points from Node.js [documentation](https://docs.npmjs.com/files/package-lock.json) about `package-lock.json` file:

>This file is intended to be committed into source repositories, and serves various purposes:
>
> - Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
>
> - Provide a facility for users to “time-travel” to previous states of node_modules without having to commit the directory itself.
>
> - To facilitate greater visibility of tree changes through readable source control diffs.
>
> - And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

**Comment by humphd** [comment]
@Reza-Rajabi it's true that using `package-lock.json` will help with deployments.  When building node apps vs. libraries, it's recommended to do it.  However, you can also use exact versioning, which we've switched to in `package.json` and `.npmrc`.  This will make sure that we're installing the same packages in dev and prod.

Later on, when development slows, we could re-introduce a package-lock.json file.  We could also have the Dockerfile use one, if you think that's important for production now.  We'd just have to remove the `.npmrc` file when we `COPY` over the files into the Docker image, and it would generate one.

**Comment by Reza-Rajabi** [comment]
@humphd Thank you. Now it is clear to me how to differentiate the deployment set up from the development.

**Comment by c3ho** [comment]
Closing this issue, exposing github token to build log is deemed a bit dangerous (required as part of danger js setup).
