### ISSUE TITLE
Wrong link used to redirect to its section of the document.

### ISSUE THREAD

**Issue by JiaHua-Zou** [Seneca-CDOT/telescope#2478]
**What happened**: When I was reading the [`environment-setup.md`](https://github.com/Seneca-CDOT/telescope/blob/master/docs/environment-setup.md) and try to press these links:

![image](https://user-images.githubusercontent.com/59105665/142091920-83b71355-10c9-4b23-a0f9-46673331eb8e.png)
It doesn't redirect me to the correct section of the document.

**What should have happened**: The link show redirect me to the correct section.

**How to reproduce it (as precise as possible)**: The link is not correctly config.

**Anything else we need to know?**: N/A

**Environment**:

- OS: Windows 10 home
- Browser: google chrome

**Comment by japneetsingh035** [comment]
Can I work on this bug @JiaHua-Zou ?

**Comment by JiaHua-Zou** [comment]
yea. I can fix it.

**Comment by JiaHua-Zou** [comment]
@japneetsingh035 sorry. I misread your message. 🤦
