### ISSUE TITLE
Remove paragraphs with only a br inside

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2479]
We have a bug where a blog can have a bunch of paragraphs with `<br>` elements inside, and nothing else.  We should remove these.

Here's an [example post](http://ycechung-opensource.blogspot.com/2021/11/lab-8-jest-enough.html) with the problem:

<img width="1276" alt="Screen Shot 2021-11-16 at 11 02 05 PM" src="https://user-images.githubusercontent.com/427398/142132506-c0b29a24-c428-476e-928e-24742bb455d3.png">

The code to do this would go in https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/html/remove-empty-paragraphs.js

**Comment by mkim219** [comment]
@humphd Can I work on this?

**Comment by humphd** [comment]
Sure, that sounds great.  Start with a test for what you want to fix in https://github.com/Seneca-CDOT/telescope/blob/master/test/remove-empty-paragraphs.test.js.
