### ISSUE TITLE
Build log for autodeployment is not working properly 

### ISSUE THREAD

**Issue by Andrewnt219** [Seneca-CDOT/telescope#2486]
**What happened**:
Mismatch object shape. The script expects the response to have a `started` key...
https://github.com/Seneca-CDOT/telescope/blob/3131812c364e551b697c123aa9a66df695b9e723/src/api/status/public/js/build-log/api.js#L6-L19
... but the server response
https://github.com/Seneca-CDOT/telescope/blob/3131812c364e551b697c123aa9a66df695b9e723/tools/autodeployment/builds.js#L46-L53

**What should have happened**:
The script should check for key `current` and grab value of `current.startedDate`

**How to reproduce it (as precise as possible)**:
- Go to https://dev.api.telescope.cdot.systems/v1/status/pages/build.html
- Open DevTools > Network
- See the shape of the server response
![image](https://user-images.githubusercontent.com/52666982/142301010-1c500c89-7f01-40e0-ab20-954af4de0af2.png)

**Anything else we need to know?**:

**Environment**:

- OS: Window 11
- Browser: Chrome 96

**Comment by humphd** [comment]
While we're fixing this, let's also add `Cache-Control: no-cache` to the headers of the response we send out, so that browsers don't reuse the `/status` response.
