### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2488]
The dashboard is showing a bunch of failed CSP script issues with script loading.  Let's sort this out.

**Comment by irenejoeunpark** [comment]
@humphd This seems like something I have never worked on before. Can I work on this issue?

**Comment by humphd** [comment]
Sure.  We set our policy here: https://github.com/Seneca-CDOT/telescope/blob/master/src/api/status/src/server.js#L9-L30, and you can read about it at https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP and https://helmetjs.github.io/.

**Comment by Andrewnt219** [comment]
This was probably fixed in #2570 .
