### ISSUE TITLE
Update CONTRIBUTING.md to address different build, run, test environment setup

### ISSUE THREAD

**Issue by Reza-Rajabi** [Seneca-CDOT/telescope#249]
Currently, if we want to set up our app in a local machine for the development, test, or run purpose, we have different ways to do so, which has been discussed in the pull request #135. It would be nice to have clear instructions about these options through the detail steps in the CONTRIBUTING.md. The installation guide for Redis, Node.js and Docker could be provided through an external link in the Prerequisites section of the CONTRIBUTING.md for the different OS as well as Windows, Mac, Linux.

**Comment by manekenpix** [comment]
I can work on this one. Is that ok @SeanPrashad?

**Comment by SeanPrashad** [comment]
Give it a go @manekenpix!

**Comment by SeanPrashad** [comment]
Food for thought (_but be aware that this increases scope and is probably best for a separate ticket_): Maybe exploring [docusaurus](https://github.com/facebook/docusaurus#--docusaurus--) would be a neat project, after we've decided how to solve the [OP](https://github.com/Seneca-CDOT/telescope/issues/249#issue-523879946)!

I'd love to see @cindyledev pick up the docusaurus work! I'd be happy to pair with her and get things headed in the right direction

**Comment by jcclay33** [comment]
https://play.google.com/intl/en_us/about/developer-content-policy-print/

**Comment by humphd** [comment]
We're going to close this in favour of #386, and just use markdown in tree.  Later (next term) we can expand this if we want.  If you have things you want included, add them to that issue.
