### ISSUE TITLE
There are no pictures of students in Hacktoberfest T-Shirts on Telescope

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2490]
I'm reading lots of posts like this:

<img width="731" alt="Screen Shot 2021-11-18 at 1 35 03 PM" src="https://user-images.githubusercontent.com/427398/142476134-e0a54171-01cd-470a-b409-7e307e04b096.png">

But I see no pictures of T-Shirts from anyone.  This is a bug I want to see fixed.

**Comment by cindyledev** [comment]
I didn't know people already got their shirts! I just sent in my order last week...

**Comment by mqnguyen5** [comment]
Mine is being delivered...

**Comment by menghif** [comment]
I planted a tree 🌲

**Comment by HyperTHD** [comment]
Can I count since I did this course last year?

**Comment by humphd** [comment]
Yes!  Blog and pic :)

**Comment by Kevan-Y** [comment]
![Image from iOS](https://user-images.githubusercontent.com/58233223/154853085-6412beb3-5dd8-4e36-8a00-ff677107fb98.jpg)

**Comment by DukeManh** [comment]
@Kevan-Y 

> There are no pictures of students in Hacktoberfest T-Shirts

**Comment by humphd** [comment]
I'll note that there still isn't a single pic of a "student IN a Hacktoberfest t-shirt."  For all I know, you're all a bunch of bots.

**Comment by humphd** [comment]
This never got solved, but I'm closing.  Maybe my next group will do it.
