### ISSUE TITLE
"Unknown" for name of last contributor

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2492]
<img width="226" alt="Screen Shot 2021-11-18 at 6 05 22 PM" src="https://user-images.githubusercontent.com/427398/142510841-35bbb889-da56-40a7-8d45-03bf84340d19.png">

However, when you hover it shows @mkim219, so it must have some info.

**Comment by tpmai22** [comment]
Hi @humphd , would you be able to explain it a bit more ? I would love to work on this as soon as I got a bit more information

**Comment by humphd** [comment]
@menghif can probably shed some light on it.

**Comment by menghif** [comment]
Here we are getting an array of commits from the Github API and grabbing the contributor's name from the latest commit (first element in the array).

Not sure why but the API returns unknown for @mkim219 author name:

```console
~ % curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/Seneca-CDOT/telescope/commits"
[
  {
    "sha": "545c3edfe6f5efd4f0006986c2bfdc8fcb7614dd",
    "node_id": "C_kwDODPx6MNoAKDU0NWMzZWRmZTZmNWVmZDRmMDAwNjk4NmMyYmZkYzhmY2I3NjE0ZGQ",
    "commit": {
      "author": {
        "name": "unknown",
        "email": "mkim219@myseneca.ca",
        "date": "2021-11-17T15:19:40Z"
      },
      "committer": {
        "name": "David Humphrey",
        "email": "david.andrew.humphrey@gmail.com",
        "date": "2021-11-18T16:27:04Z"
```

The docs are [here](https://docs.github.com/en/rest/reference/repos#list-commits) if you want to have a look.

**Comment by humphd** [comment]
Interesting! @mkim219, you need to set a name on GitHub.  Closing.
