### ISSUE TITLE
Update logger to use newer pretty printing API in pino

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2497]
In #2496 we updated our logger dependencies.  The new versions have changed the way you're supposed to do pretty printing of logs, see https://getpino.io/#/docs/pretty, resulting in this warning when you start the backend:

```
(node:20671) [PINODEP008] PinoWarning: prettyPrint is deprecated, look at https://github.com/pinojs/pino-pretty for alternatives.
(Use `node --trace-warnings ...` to show where the warning was created)
```

Our [logger](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/logger.js) should get updated to use the new way of pretty printing logs in debug mode, see https://getpino.io/#/docs/pretty.

**Comment by ycechungAI** [comment]
I would like to work on this for release 0.4 primary issue

**Comment by humphd** [comment]
There's a few issues that are interrelated to this:

#2499, #2498

This one isn't huge, so you might be able to add one or both of those.

**Comment by ycechungAI** [comment]
ill add both of them as well

**Comment by Kevan-Y** [comment]
Taking this one too, since pretty similar to #2499

**Comment by Kevan-Y** [comment]
Are we still keep using `express-pino-logger`? or can be switch to `pino-http`?

**Comment by humphd** [comment]
`pino-http` please.
