### ISSUE TITLE
Remove all Elastic APM code from Telescope

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2498]
We had an idea to use Elastic APM for monitoring our logs and services.  In the end we haven't gone that route, and use a simpler Portainer setup.

Let's get rid of all the APM code from our docker/compose files, envs, logging, Satellite, docs, etc. code.

**Comment by ycechungAI** [comment]
ill add this one as well

**Comment by humphd** [comment]
Great stuff, thanks.

**Comment by humphd** [comment]
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'elastic-apm-node@3.13.0',
npm WARN EBADENGINE   required: { node: '^8.6.0 || 10 || 12 || 13 || 14' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
```

**Comment by humphd** [comment]
We need to use `Fixes #....` when we do the PR description @aserputov
