### ISSUE TITLE
[Satellite] update pino

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2499]
Similar to #2497 we need to update pino and audit [how we do pretty printing](https://getpino.io/#/docs/pretty) in Satellite to make sure it's OK with the latest versions:

- https://github.com/Seneca-CDOT/satellite/blob/master/package.json#L35-L36
- https://github.com/Seneca-CDOT/satellite/blob/master/src/logger.js

**Comment by humphd** [comment]
Let's also switch to pino-http vs. the express-pino-logger, since the latter uses the former. https://github.com/pinojs/pino-http

**Comment by ycechungAI** [comment]
i liked to work on this

**Comment by humphd** [comment]
This may not be clear, but the code for this lives in a different repo: https://github.com/Seneca-CDOT/satellite

**Comment by Kevan-Y** [comment]
I can work on it if no one picked up.

**Comment by humphd** [comment]
Sounds good, go for it.
