### ISSUE TITLE
Implement ability to email admins/users

### ISSUE THREAD

**Issue by neilong31** [Seneca-CDOT/telescope#25]
This issue is a part of the [MVP Features](https://github.com/Seneca-CDOT/telescope/blob/master/docs/overview.md#mvp-features).

It should send an email to an admin or the user if:

- A post is deemed inappropriate
- Any major errors are logged (ex. issues downloading feeds)
- If it crashed

If there any other times an email should be sent out please suggest them as well.

**Comment by s-arika** [comment]
Maybe we could use nodemailer https://nodemailer.com/about/

**Comment by humphd** [comment]
Sounds good to me, let's try it.  https://stackabuse.com/how-to-send-emails-with-node-js/ has a good discussion of this, including how to test it.  Who wants to do this?

**Comment by RyanWils** [comment]
Hi I would like to work on this
