### ISSUE TITLE
Switch to express.json() vs. body-parser in backend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2504]
Remove https://github.com/Seneca-CDOT/telescope/blob/0d83efa2f4edb1ea51f4b3f0a3840a4356807e53/src/backend/web/app.js#L3 and the dependency from `package.json` and change https://github.com/Seneca-CDOT/telescope/blob/0d83efa2f4edb1ea51f4b3f0a3840a4356807e53/src/backend/web/app.js#L52-L53 to to use:

- https://expressjs.com/en/api.html#express.json
- https://expressjs.com/en/api.html#express.urlencoded

**Comment by humphd** [comment]
@LuigiZaccagnini we try to get 2 reviews on changes before merging, mainly to spread knowledge of changes across the community, so that if something breaks, more than one person knows why.

**Comment by LuigiZaccagnini** [comment]
@humphd Sorry, I will make sure to request another review next time!

**Comment by humphd** [comment]
It's my fault for not resetting our branch protection, you couldn't have known.

**Comment by LuigiZaccagnini** [comment]
Do you think this merge will be ok?

**Comment by humphd** [comment]
Every change is dangerous, in that so many unintended things can break.  I *think* this is safe, but we need more tests.  We'll see.  But if something breaks in areas related to this, we'll have some idea why.  The key is, you need reviewers who are watching when things suddenly break or stop working correctly and can remember, "oh yeah, we just merged a change that touches this code."
