### ISSUE TITLE
Dashboard and Build Log are not the same

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2505]
Compare:

- https://dev.api.telescope.cdot.systems/v1/status/
- https://dev.api.telescope.cdot.systems/v1/status/pages/build.html

The sidebar is not the same, nor is the highlight colour.

<img width="1044" alt="Screen Shot 2021-11-21 at 12 52 17 PM" src="https://user-images.githubusercontent.com/427398/142773336-f3bd69ee-e63c-49de-a67e-f11c0203c3ce.png">

**Comment by suhhee1011** [comment]
@humphd Can I work on this? I think I can fix it

**Comment by humphd** [comment]
For sure, go for it.

**Comment by Andrewnt219** [comment]
Closed with #2570
