### ISSUE TITLE
Link to latest contribution

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2506]
In the Dashboard we list the last contributor to Telescope and Satellite, which includes a link to the user's name.  However, I can't click anything to see the PR that they made.  Let's find a way to include this info somehow and a link.

<img width="748" alt="Screen Shot 2021-11-21 at 12 55 34 PM" src="https://user-images.githubusercontent.com/427398/142773443-836579cf-b0d5-4031-9548-cfc4fefbc26b.png">

**Comment by Kevan-Y** [comment]
Hi, I never touched the front end part of telescopes dashboard. I would like to work on this issue.

**Comment by humphd** [comment]
Sounds good, @Kevan-Y.  Quite a few of your peers have written this code, so you can ask them for advice or to get reviews.

**Comment by Kevan-Y** [comment]
Wasn't able to get link to the PR, but I can get the commit URL.
Is something like that okay?
![image](https://user-images.githubusercontent.com/58233223/143068791-98135cb8-7fab-4d8c-a4fd-3371590942c8.png)

**Comment by humphd** [comment]
I think that makes sense.  Can you put it to the right of the person's name?

```
(avatar) Luigi Zaccagnini 2dc6a97
```

And have the avatar/name link to the person, and the commit sha link to the commit.   We might have to do some overflow `...` in CSS to deal with really long names.
