### ISSUE TITLE
Hide "Weekly Commits" if zero

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2507]
When the number of weekly commits is zero, let's remove the entire DOM element for "Weekly Commits" and "0" instead of showing it.  We already say "No commits this week" at the bottom, so it's not needed.

<img width="245" alt="Screen Shot 2021-11-21 at 12 57 25 PM" src="https://user-images.githubusercontent.com/427398/142773486-c47ebb0b-60f9-4a22-8106-fced0a0c7437.png">

**Comment by ycechungAI** [comment]
I would like to work on this for release 0.4 secondary issue

**Comment by suhhee1011** [comment]
@humphd Can I work on this?

**Comment by humphd** [comment]
Yes, go for it.
