### ISSUE TITLE
Instruction, and a call for help for Our Project Board

### ISSUE THREAD

**Issue by Reza-Rajabi** [Seneca-CDOT/telescope#251]
I have been trying to make a summary of all issues and pull requests status by using the [Project Board](https://github.com/Seneca-CDOT/telescope/projects/1). We could have an instantly updated and reliable board if more/all of us help with that. Here is what we can do:

- When making a new issue/ pull request (task), select the project `Main` from the `⚙️`  `👉` setting button provided under the `Labels` section.
- Once the issue gets added to the project, from the newly provided list through the previous step, select one of the: issue, discussion, todo, in progress/review, done, closed (to be explained at the bottom)
- Add `on-board` label as well as any other relevant labels to the task using `Labels` `⚙️`
- By changes on the status as we go, check if automation moved the task properly, and if not, change its status (previous step) yourself. For example, if somebody decides to take care of an issue, they need to add themself as Assignees and update the status to `in progress/review`

**Status Categories:** 
- issue: a new issue that has not any feedback or agreement from the telescope developers community or it is not clear if it could be considered as an issue.
- discussion: is a discussion to make something clear or make a decision. It could be broken down into many issues later.
- todo: obviously is an issue and is a task that needs to be done
- in progress/review: a task that has an assignee
- done: a merged pull request
- close: a finalized issue or a closed pull request

**Other Stuff**
- If the instruction above is not clear, ask me or help me with that to make it clear and concise (feel free to edit)
- If an issue that you opened up is stale, please consider closing it, and if it is necessary, opening up a new one with applicable changes.
- If you have any idea about improving our task-tracking, changing it or ignoring the whole thing, I would appreciate it very much if you could bring it up.

**Comment by humphd** [comment]
Let's discuss this as a group this week in class.

**Comment by humphd** [comment]
I'm going to start using this next week.  I've already created a 0.5 Release project.

@cindyledev we should probably convert this Issue into being some kind of documentation to our team on how to use the Project Board flow.
