### ISSUE TITLE
Prevent client from caching /status response

### ISSUE THREAD

**Issue by Andrewnt219** [Seneca-CDOT/telescope#2515]
**What would you like to be added**:
Is related to #2486 
Add Cache-Control header to endpoint /status in tools/autodeployment to prevent caching.

**Why would you like this to be added**:
Clients should always get the most up-to-date build status.

**Comment by mqnguyen5** [comment]
Can I give this a shot?

**Comment by humphd** [comment]
Sure, pair it with other things to make something large enough for 0.4 (this is small).

**Comment by mqnguyen5** [comment]
Will do, I already have another issue undergoing

**Comment by Andrewnt219** [comment]
Oh wait, I think @manekenpix  did this already.

**Comment by humphd** [comment]
This still needs to happen.

**Comment by TueeNguyen** [comment]
Hi @manekenpix, I went over some related PRs, you did mention adding Cache-Control header but you did not add right?

**Comment by manekenpix** [comment]
@TueeNguyen I didn't add it.
