### ISSUE TITLE
Use /deploy vs :4000 for autodeployment links

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2521]
Recently, @AmasiaNalbandian [added a redirect in our nginx router](https://github.com/Seneca-CDOT/telescope/blob/c505e3ba6fc38407d91514d5906cf8f6278d3799/config/nginx.conf.template#L236-L239) from :4000 -> /deploy, such that you can do https://dev.telescope.cdot.systems:4000/status or https://dev.telescope.cdot.systems/deploy/status.  The latter is much nicer from a developer experience point of view.

In a few places, we are using :4000 and I think we should switch to /deploy:

- https://github.com/Seneca-CDOT/telescope/blob/17d5c1522e7b799d4d9b826ec0223c4bb3714ea9/src/api/status/public/js/build-log/api.js#L2
- https://github.com/Seneca-CDOT/telescope/blob/ec5ddd2f97118ed3d47536c91e91cac686002120/src/api/status/src/server.js#L22
- etc

NOTE: we don't need to change every use of :4000 to /deploy; only the ones where we are acting as a consumer of the deploy routes vs. defining them.

**Comment by Qiwen-Yu** [comment]
@humphd Can I take this one, thank you so much!

**Comment by humphd** [comment]
Sure.  I would pair this with some other work, as it's pretty small.

**Comment by Andrewnt219** [comment]
@Qiwen-Yu Can you also update the links in [autodeployment README](https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/README.md)?

**Comment by Qiwen-Yu** [comment]
@Andrewnt219 Yes, sure.
