### ISSUE TITLE
Linter was not running the whole time 

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2525]
I was looking at a PR and noticed an unused variable was not detected by `npm run lint`
**Shocking discovery 🙃**

Our linting script `eslint --config .eslintrc.js` does not provide a glob pattern to ESLint and no files are linted.

Developers only notice problems found by ESLint if they have installed the VSCode ESLint extension because the extension puts squiggly underlines on them. Otherwise, running `npm run lint` doesn't show any linting problems.

Plus, we use some Eslint plugins that are not listed in `package.json`. We don't notice this because npm run lint was not running the whole time.

This can explain [the comment](https://github.com/Seneca-CDOT/telescope/pull/2420#pullrequestreview-793706259) by @humphd why the new dashboard passed all eslint tests.

**Comment by DukeManh** [comment]
I can fix this while I'm on it.

**Comment by humphd** [comment]
Fantastic!  Great work.  Looking back through blame history, looks like we never did this correctly.  Question: can we do that in the config (define the glob) vs. script?

**Comment by DukeManh** [comment]
I think it's not possible as per [this discussion](https://github.com/eslint/eslint/issues/11223#issuecomment-450545186).
