### ISSUE TITLE
Add trojan source eslint plugin to Telescope and Satellite

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2533]
Let's add https://github.com/lirantal/eslint-plugin-anti-trojan-source to Telescope and Satellite, so we can avoid some of the problems other npm packages have had recently.

**Comment by dhillonks** [comment]
@humphd Can I work on this?

**Comment by humphd** [comment]
Sure, combine this with some other fixes for 0.4.  This is pretty small.
