### ISSUE TITLE
Add padding to build log terminal

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2534]
The build log terminal's content is pressed right against the edge, and doesn't look as nice as it could.  Let's add a small bit of padding so there is some extra "black" space.

<img width="1356" alt="Screen Shot 2021-11-28 at 10 46 05 AM" src="https://user-images.githubusercontent.com/427398/143775346-d8afdcf7-b618-463d-86ac-a1972e09ac2a.png">

**Comment by menghif** [comment]
I would like to take this one
