### ISSUE TITLE
Cache build log for current/previous build

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2535]
When you go to the build log in the dashboard, it shows you what's happening with the current build:

<img width="1345" alt="Screen Shot 2021-11-28 at 10 49 36 AM" src="https://user-images.githubusercontent.com/427398/143775429-437bc028-4b12-422f-b8bc-6dbb5d937dd5.png">

That's useful, but not as useful as it could be.  What I'd really like is to see is the entire log for the current build get sent on load, and then have it continue when there is more data.

Ideally we would cache the build log and send that first, then stream the rest of the log in real-time.

If that's not doable, we can also consider switching to Web Sockets.

**Comment by suhhee1011** [comment]
Can I give it a shot?

**Comment by humphd** [comment]
@suhhee1011 sure.  This is going to likely involve updates to https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/builds.js.  @manekenpix and I are probably the ones most aware of this code, if you want to ask questions.

**Comment by humphd** [comment]
I'll take this.
