### ISSUE TITLE
Stop using actions/cache in GitHub Actions Workflows

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2537]
See https://github.com/Seneca-CDOT/telescope/pull/2536#issuecomment-981127629.  Let's try using the built-in npm `cache` facility of the setup-node action and remove the actions/cache.

**Comment by dhillonks** [comment]
@humphd Can I also work on this?

**Comment by humphd** [comment]
This is happening as part of #2545, closing.
