### ISSUE TITLE
Build log get stuck after loading

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2539]
When I go to look at a build happening in the dashboard, the log initially shows, but then nothing ever gets added.  It seems like the connection isn't being processed properly.

<img width="1359" alt="Screen Shot 2021-11-28 at 3 59 06 PM" src="https://user-images.githubusercontent.com/427398/143785786-0515fb17-e005-47ed-b9ef-9767b2d51a89.png">

**Comment by Andrewnt219** [comment]
Did it work as expected before?

**Comment by humphd** [comment]
Not sure, this is the first time I'm using it vs. reviewing.

**Comment by Andrewnt219** [comment]
I'll look into this.

**Comment by humphd** [comment]
I think the issue here is that we're processing the first chunk, and then not calling `read()` again to handle the next one.  See https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams#reading_the_stream

In my original version we create a "loop" by having `processLog` trigger the next `read()`: https://github.com/humphd/telescope/blob/9e6be5ebf663b8c28d562fab5026a95c06d2b084/tools/autodeployment/src/web/build.js#L31

**Comment by Andrewnt219** [comment]
Thanks for the lead, I'll spend time on this today.

**Comment by Andrewnt219** [comment]
> In my original version we create a "loop" by having processLog trigger the next read(): https://github.com/humphd/telescope/blob/9e6be5ebf663b8c28d562fab5026a95c06d2b084/tools/autodeployment/src/web/build.js#L31

Didn't know there was a js version of this logic. Pretty nice way to organize the logic too.
