### ISSUE TITLE
Indicate a build is in progress in Dashboard build page

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2542]
When I go to a build in GitHub Actions, I get an animated indication that a build is happening, and how long it's been going for:

<img width="249" alt="Screen Shot 2021-11-29 at 9 55 32 AM" src="https://user-images.githubusercontent.com/427398/143890526-2b06dc28-f4b0-49a4-976a-2d4eb02f8930.png">

When it's done, the yellow animated circle becomes a green check mark or a red 'x'. 

<img width="258" alt="Screen Shot 2021-11-29 at 9 58 45 AM" src="https://user-images.githubusercontent.com/427398/143890871-79d08356-1109-4308-9e42-321e0561a7ba.png">

Let's do something like this in our build dashboard, so you know what's happening when you get there.  Especially when a build step is not producing any output, it can be hard to know if it's still going.

**Comment by humphd** [comment]
Sure thing, assigned.

**Comment by Yoda-Canada** [comment]
@humphd Do I need to add the animated indication to each section? 
![764667048d4dd311a1e8b376341f2eb](https://user-images.githubusercontent.com/55161917/143933835-d498532e-ae1e-4250-bf9b-a4054dc560c4.png)

**Comment by humphd** [comment]
Not on that page, on the build page, probably in the header:

https://dev.api.telescope.cdot.systems/v1/status/pages/build.html

**Comment by Yoda-Canada** [comment]
What is the purpose of this log and who will build it? I can't find the relevant information in README and CONTRIBUTING.

**Comment by humphd** [comment]
Aren't you also working on #2519, which is related to this as well?

The autodeployment server builds our containers when someone merges/tags on GitHub, and deploys it to staging or production.  We stream that log and the build log page displays it in the terminal.

The log is available from https://dev.api.telescope.cdot.systems/deploy/log (404 if no log is happening) and the build status is at https://dev.api.telescope.cdot.systems/deploy/status.

This issue is about using the status and log info to create some kind of header that indicates if the build is happening or not.
