### ISSUE TITLE
Bookmarking posts for authenticated users

### ISSUE THREAD

**Issue by tuanthanh2067** [Seneca-CDOT/telescope#2549]
**What would you like to be added**: A feature in which authenticated user will be able to bookmark a post, and view later.

**Why would you like this to be added**: In my opinion, this is quite a cool feature as we gather all people's posts from different sites. 
For example, a person may like this post, that post, another post which are from created by `3 different people` and published from `3 different sites` (dev.to, medium.com, etc). But they don't want to go to original url's and save it on those different sites.

**Comment by tuanthanh2067** [comment]
@humphd any suggestion of how to implement this?

**Comment by humphd** [comment]
This seems like it's out of scope and not something anyone is willing to build.  Good idea, but not something we're doing.
