### ISSUE TITLE
`justify` in Grid is deprecated, use `justifyContent` instead

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2550]
There are some places in our code where we use `justify` prop in Grid component. The prop name is deprecated and we should use `justifyContent` instead.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/51073515/144130573-a611fd34-a1a6-4f96-a453-8459bdd40121.png">

**What would you like to be added**:

**Why would you like this to be added**:

**Comment by nguyenhung15913** [comment]
@DukeManh @humphd I can work on this, can you assign it to me?

**Comment by humphd** [comment]
Sure, done.
