### ISSUE TITLE
Add a template engine for status dashboard

### ISSUE THREAD

**Issue by Andrewnt219** [Seneca-CDOT/telescope#2553]
**What would you like to be added**:
A template engine somewhat like this

```handlebars
<!-- side-bar.html -->

<nav>
  Sidebar content
</nav>
```

```handlebars
<!-- index.html -->

{{> sidebar }}

<main>
  Main content 

  <ul>
  {{#each items}}
    <li>{{this.title}}</li>
  {{/each}}
 </ul>
</main>
```

At the moment, I'm looking at the good old [handlebars](https://handlebarsjs.com) from WEB322. It's the closest to HTML and has a [simple compiler setup](https://handlebarsjs.com/installation/precompilation.html#getting-started) like SCSS.

**Why would you like this to be added**:
Two main reasons:
- The duplicate of HTML: With only two active pages, we already have a problem with different sidebar on both pages in #2505 
- The verbose code to render HTML from JS in #2551

**Comment by humphd** [comment]
Sounds like a good idea to me.

**Comment by Kevan-Y** [comment]
Maybe we can separate into several issues maybe, one to setup handlebars, other to add components

**Comment by DukeManh** [comment]
Let's eventually use React to write it 😃.

**Comment by Kevan-Y** [comment]
> Let's eventually use React to write it 😃.

That what I was thinking too using Next.Js.

**Comment by humphd** [comment]
@DukeManh I'm hoping to use a different set of technologies so students not as interested in React have a place to work as well.  We have all the Next.js we can handle already :)

**Comment by Kevan-Y** [comment]
I can try and work on it.
