### ISSUE TITLE
Search page re-renders on entering input

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#2554]
**What happened**:
When entering any text inside the search bar, the search page re-renders and focus is removed from the search bar.

**What should have happened**:
When entering any text, it should keep focus so that you can continue entering your search text. This is a render issue, most likely a variable/function introduced in one of our recent PRs that caused this issue.

The issue is caused by the removal of the `autoFocus` property in [this recent commit](https://github.com/Seneca-CDOT/telescope/commit/d8a7f3330d670ec89ca499d69d94055133f46feb). Without that property, upon entering a character, our `onChange` event handler will cause a useEffect re-render from our SearchProvider, thus, the search page itself will be rendered again and the search input text field loses focus.

**Comment by drew5494** [comment]
Can I work on this? @humphd

**Comment by humphd** [comment]
Assigned!
