### ISSUE TITLE
[3.0] Investigate Supabase

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2555]
I wonder if we could use a self-hosted https://supabase.com/, (project is on https://github.com/supabase/supabase).  https://www.youtube.com/watch?v=WiwfiVdfRIc is a good overview.

One of my longer term goals is to move toward running Telescope in the cloud.  I haven't figured out how to fund that (yet), so in the meantime we probably need to create our own cloud instead.  Since we're already slightly invested in a Firebase-type model (see Users service, thanks to @chrispinkney), we could consider going toward Supabase and self-host our own instance via docker.

Currently they have:

- Database (built on top of postgres, adding REST APIs, websocket real-time) and Object Storage (like S3)
- Auth and user management (not sure how easy it would be to hook into this with our SAML auth)
- a killer dashboard UI to monitor and control things

They are working on adding functions, which would be a killer feature for us, since we could move toward servless.  I like that it's also written in a tech stack that we could help fix (mostly TS/JS).

NOTE: I'm not saying we should do this.  I'm just thinking out loud in issues :)

**Comment by DukeManh** [comment]
If I remember correctly, self-hosted Supabase doesn't have a dashboard.

**Comment by humphd** [comment]
@DukeManh they open sourced it today! https://news.ycombinator.com/item?id=29401589

**Comment by DukeManh** [comment]
@humphd That's awesome news.

**Comment by cindyledev** [comment]
I've been struggling with Next Auth and Prisma at work for who knows how long. This issue has motivated me to give Supabase a try. It actually looks super promising. If I get Supabase working at work, I'll share my knowledge with everyone at Telescope via blog post or Slack :)

**Comment by DukeManh** [comment]
I am very keen on Firebase and have worked with it for some time.
Because Supabase is a Firebase alternative I'd like to give this a try.

I'll investigate and come back here with what I learn.

**Comment by humphd** [comment]
Cool.  Another option we can consider, if this ends up being too heavy-weight, is to add a db ourselves (postgres, sqlite, etc).  We should only take this on if it gives us something we need vs. makes our setup and admin too complicated.

Thanks for looking into this.  I think it might be cool to add this, esp. when they include serverless functions.

**Comment by chrispinkney** [comment]
@DukeManh Might be worth investigating [Appwrite](https://github.com/appwrite/appwrite) too! But it's very early stage AFAIK, but I think recently secured some funding which is cool?

**Comment by HyperTHD** [comment]
I know a little bit about Supabase, having used it a bit in one of my frontend projects on the side. I can help a bit with research here so putting myself in this journey

**Comment by humphd** [comment]
https://medium.com/@gracew/using-supabase-rls-with-a-custom-auth-provider-b31564172d5d looks useful

**Comment by cindyledev** [comment]
Are we still investigating Supabase? I see it has been added to Telescope in #2743

**Comment by humphd** [comment]
Agree, closing.
