### ISSUE TITLE
Link a title to redirect to the original post

### ISSUE THREAD

**Issue by irenejoeunpark** [Seneca-CDOT/telescope#2559]
**What would you like to be added**:
When the user clicks the title, redirect to the original post on its platform.

**Why would you like this to be added**:
Currently, the title is clickable, but when clicking the post title, nothing happens. 
Want to make the title redirect to the original post.

**Comment by HyperTHD** [comment]
One thing you can also do, is have the original post open on a new tab instead of on the same tab.
Let's users continue checking out other telescope posts without having to go back while also having the blog they want to read available as well

**Comment by humphd** [comment]
Clicking on the title should expand it, for long titles.  Also, clicking that expands to show the mobile GitHub area.  If we create multiple click areas, will it get confusing?  Also, click the date, or the new share icon will do this.

**Comment by irenejoeunpark** [comment]
> Clicking on the title should expand it, for long titles. Also, clicking that expands to show the mobile GitHub area. If we create multiple click areas, will it get confusing? Also, click the date, or the new share icon will do this.

That makes more sense I guess! I will leave it like this for now!
