### ISSUE TITLE
Add a .vscode folder with VSCode Workspace recommendations

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#256]
Many of us use VSCode to do our development.  One of the features it allows is creating a set of [project-wide settings for all users who use VSCode](https://code.visualstudio.com/docs/getstarted/settings).  For example, you can see how [Microsoft does this for VSCode itself](https://github.com/microsoft/vscode/tree/master/.vscode).  A Workspace can include things like:

- common editor settings (e.g., project indent amounts, newline type, etc)
- [recommended extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) for this project (for us that would be eslint, prettier, EditorConfig, etc.)
- launch commands to be run from within VSCode's debugger

The [docs for Workspace Settings](https://vscode.readthedocs.io/en/latest/getstarted/settings/) have lots of ideas.

Let's see if we can help our developers by adding a `.vscode/` dir with Workspace settings.

**Comment by vitokhangnguyen** [comment]
This issue when solved would bring many benefits to #96 where we will have ESLint, Prettier and EditorConfig working

**Comment by manekenpix** [comment]
Closed with #285
