### ISSUE TITLE
Optimize Gitpod Environment Image

### ISSUE THREAD

**Issue by menghif** [Seneca-CDOT/telescope#2564]
In #2545 we are adding a [custom Gitpod Dockerfile](https://github.com/Seneca-CDOT/telescope/pull/2545/commits/b43484b4b83f56ef690ddbf090616c205a714296) to install `pnpm` in our Gitpod environment.

By default Gitpod uses the [`gitpod/workspace-full`](https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile) image. This includes a lot of tools we don't need. Instead we could use the smaller [`gitpod/workspace-base`](https://github.com/gitpod-io/workspace-images/blob/master/base/Dockerfile) image and only add what we need (Docker, Node, pnpm, etc).

You can follow the instructions on how to set this up in the [docs](https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile).

**Comment by dhillonks** [comment]
I'd like to give this a try.
