### ISSUE TITLE
Min-height for blog posts needs adjustment to avoid GitHub details overflowing into the next post

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2568]
**What happened**:
When a user submits a short blog, the blog details on the right side overflow into the next blog.

**What should have happened**:
The blog details should not overflow into the blog below - we should try to set a min-height per blog to avoid the overflow. This will leave some extra space in the blog area, but will not interfere with the design.

**How to reproduce it (as precise as possible)**:
You need to find a short blog, here I have attached an image for example:
![image](https://user-images.githubusercontent.com/77639637/144725731-b33767eb-8d2a-4564-ba38-4fb8ca06b4e9.png)

**Anything else we need to know?**:
There's already a min-height set. I am sure this was set before we implemented the GitHub details and therefore needs to be adjusted. We need to explore what the maximum height of the GitHub details will be(repo, issues, pull requests, users etc.), and consider that when finding the sweet spot for the min-height. Below is a screenshot at min-height of 400px from the 300px we have right now:
![image](https://user-images.githubusercontent.com/77639637/144725802-2f73d8fe-5d1b-42eb-894a-9f710be4a65d.png)

**Environment**:

- OS:
- Browser:

**Comment by humphd** [comment]
Great catch, and good suggestions.

**Comment by ritikbheda** [comment]
Hi, I would like to work on it.
