### ISSUE TITLE
Improve invalid feed handing

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2569]
Now that @hphan9's work on #2520 is merged, we can finally see what's happening with our feed parser and invalid feeds: https://dev.api.telescope.cdot.systems/v1/posts/feeds/invalid.

Looking through these I think we need to fix some things:

- remove `\n` from the `reason` so that we can display it as a single line.  We could replace them with `' '` (space)
- figure out why 304s are showing up as invalid.  This means that content hasn't been modified (and we don't need to re-download) so this is odd to see in here
- we should set a `ttl` for these `invalid` keys in Redis, so they expire and we can retry.  A blog might be invalid today, and OK in a few days or a week.  Maybe we should set a ttl of 7 days or something?

I'm excited to see us get this data into the dashboard so we can act on it.  Do we have an issue on that yet?  If not, we should file one.

**Comment by tpmai22** [comment]
I would love to give this a try !

**Comment by humphd** [comment]
@tpmai22 OK, sounds good.  @hphan9 is our resident "invalid feeds" expert, so you can chat with her and get her to review.

**Comment by DukeManh** [comment]
I think there's a problem with how feeds are invalidated. For example:
This feed https://dev.api.telescope.cdot.systems/v1/posts/feeds/8b0d40ff90 is invalid but their posts are still showing here https://telescope.cdot.systems/search/?text=vincent%20lam&filter=author.

https://telescope.cdot.systems/search/?text=Shelley%20Shi&filter=author && https://dev.api.telescope.cdot.systems/v1/posts/feeds/1ab487e171, etc

Most invalid `304 status code` feeds are from Wordpress and they are custom RSS URL, like http://hdc23.wordpress.com/category/OOP344/feed vs a full feed URL.

**Comment by humphd** [comment]
I wonder if WordPress went through some kind of down-time or migration where the returned result for these failed, and we marked them invalid; now they work.  It's very odd.  @manekenpix was discussing this too.

For sure a 304 should not be invalid.
