### ISSUE TITLE
Use Redis from Satellite in all microservices that need them

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#2574]
**What would you like to be added**:
Redis was added awhile back to Satellite. We should update our microservices that use redis to bring it from Satellite. Once that's done, any reference to `ioredis` and `ioredis-mock` can be removed from the services currently using them

**Comment by humphd** [comment]
Nice catch, thanks for filing this.

**Comment by TueNguyen2911** [comment]
I’d like to try this one
