### ISSUE TITLE
Title container floating with some space, and overflow with the scroll on mobile view.

### ISSUE THREAD

**Issue by irenejoeunpark** [Seneca-CDOT/telescope#2583]
While working on issue #2373, found out that the title container is floating and overflowing when scrolling through the content. 

https://user-images.githubusercontent.com/54859944/145267660-f8ad73fb-d6ee-4604-b781-08385c3edbb1.mov

**What happened**: 
The title container is stuck on the top, but floating with a small space so that the background content is slightly showing on top of the container.

**What should have happened**: 
It should enclose the top space without any gap.

**Environment**: 

Bug on UI - mobile 

- OS: N/A
- Browser: In all browser

**Comment by JiaHua-Zou** [comment]
Is this issue taken? If not I would like to try fixing this issue.

**Comment by irenejoeunpark** [comment]
> Is this issue taken? If not I would like to try fixing this issue.

Oh I am actually working on this issue! Thanks for the interest

**Comment by humphd** [comment]
@irenejoeunpark please assign yourself so that it's clear to others.
