### ISSUE TITLE
Add button to copy build-log content to clipboard

### ISSUE THREAD

**Issue by Andrewnt219** [Seneca-CDOT/telescope#2587]
**What would you like to be added**:
A button to copy all current content of the build-log into the clipboard

**Why would you like this to be added**:
cc @humphd

**Comment by humphd** [comment]
@tuanthanh2067 did similar work for sharing posts in #2548, which might inform this, in case that's helpful.

**Comment by Andrewnt219** [comment]
I skimmed through Xterm exposes methods, and it looks like we should be able to get the content from the canvas and then write it to the clipboard.
