### ISSUE TITLE
Create a Post type to represent the data from a feed article

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#259]
Our [feed-parser](src/feed-parser) is working now, and turns a feed URL into a JavaScript Object representing a feed article.

<details>
<summary>Here is an example of what the Object looks like</summary>
<code><pre>
{ title: 'My First Blog',
  description:
   'I have never done this before, so let\'s make this short. This post is just a test on how my blog post will look like.',
  summary: null,
  date: 2008-09-07T22:12:00.544Z,
  pubdate: 2008-09-07T22:09:00.000Z,
  pubDate: 2008-09-07T22:09:00.000Z,
  link: 'http://nadavid.blogspot.com/2008/09/my-first-blog.html',
  guid:
   'tag:blogger.com,1999:blog-7100164112302197371.post-522285656016053350',
  author: 'Neil David',
  comments:
   'http://www.blogger.com/comment.g?blogID=7100164112302197371&postID=522285656016053350',
  origlink: null,
  image: {},
  source: {},
  categories: [],
  enclosures: [],
  'atom:@': {},
  'atom:id':
   { '@': {},
     '#':
      'tag:blogger.com,1999:blog-7100164112302197371.post-522285656016053350' },
  'atom:published': { '@': {}, '#': '2008-09-07T15:09:00.000-07:00' },
  'atom:updated': { '@': {}, '#': '2008-09-07T15:12:00.544-07:00' },
  'atom:title': { '@': { type: 'text' }, '#': 'My First Blog' },
  'atom:content':
   { '@': { type: 'html' },
     '#':
      'I have never done this before, so let\'s make this short. This post is just a test on how my blog post will look like.' },
  'atom:link':
   [ { '@': [Object] },
     { '@': [Object] },
     { '@': [Object] },
     { '@': [Object] },
     { '@': [Object] } ],
  'atom:author':
   { '@': {},
     name: { '@': {}, '#': 'Neil David' },
     uri:
      { '@': {},
        '#': 'http://www.blogger.com/profile/15120043357385745054' },
     email: { '@': {}, '#': 'noreply@blogger.com' },
     'gd:image': { '@': [Object] } },
  'thr:total': { '@': {}, '#': '0' },
  meta:
   { '#ns':
      [ [Object], [Object], [Object], [Object], [Object], [Object] ],
     '@':
      [ [Object], [Object], [Object], [Object], [Object], [Object] ],
     '#xml': { version: '1.0', encoding: 'UTF-8' },
     '#type': 'atom',
     '#version': '1.0',
     title: 'DPS909 Stuff',
     description: null,
     date: 2012-02-17T03:08:28.744Z,
     pubdate: 2012-02-17T03:08:28.744Z,
     pubDate: 2012-02-17T03:08:28.744Z,
     link: 'http://nadavid.blogspot.com/',
     xmlurl:
      'http://www.blogger.com/feeds/7100164112302197371/posts/default',
     xmlUrl:
      'http://www.blogger.com/feeds/7100164112302197371/posts/default',
     author: 'Neil David',
     language: null,
     favicon: null,
     copyright: null,
     generator: 'Blogger v7.00 (http://www.blogger.com/)',
     cloud: { type: 'hub', href: 'http://pubsubhubbub.appspot.com/' },
     image: {},
     categories: [],
     'atom:@':
      { xmlns: 'http://www.w3.org/2005/Atom',
        'xmlns:opensearch': 'http://a9.com/-/spec/opensearchrss/1.0/',
        'xmlns:blogger': 'http://schemas.google.com/blogger/2008',
        'xmlns:georss': 'http://www.georss.org/georss',
        'xmlns:gd': 'http://schemas.google.com/g/2005',
        'xmlns:thr': 'http://purl.org/syndication/thread/1.0' },
     'atom:id':
      { '@': {},
        '#': 'tag:blogger.com,1999:blog-7100164112302197371' },
     'atom:updated': { '@': {}, '#': '2012-02-16T19:08:28.744-08:00' },
     'atom:title': { '@': [Object], '#': 'DPS909 Stuff' },
     'atom:subtitle': { '@': [Object] },
     'atom:link': [ [Object], [Object], [Object], [Object] ],
     'atom:author':
      { '@': {},
        name: [Object],
        uri: [Object],
        email: [Object],
        'gd:image': [Object] },
     'atom:generator': { '@': [Object], '#': 'Blogger' },
     'opensearch:totalresults': { '@': {}, '#': '1' },
     'opensearch:startindex': { '@': {}, '#': '1' },
     'opensearch:itemsperpage': { '@': {}, '#': '25' } } }
</pre></code>
</details>

The format of this Object is [documented here](https://www.npmjs.com/package/feedparser#list-of-article-properties).

For our purposes, we don't care about a lot of this, and can throw it away.  I'd like to see us create a new file, `src/post.js`, which exports an [ES6 Class](https://googlechrome.github.io/samples/classes-es6/), `Post`.

```js
class Post {...}
module.exports = Post;
```

The `Post` class should have the following properties (we can improve names, but here's a starting point):

- `title` - (String) the title of the blog post
- `author` - (String) the author of the post
- `content` - (String) the content of the post, what was originally named `description` run through our HTML sanitizer (#18) 
- `text` - (String) the content of the post after being run through our text parser (no HTML).  We could make this a method, and only generate it on demand, or could store it on the Object.
- `updated`- (Date) the date/time of the most recent update to the post
- `published` - (Date) the date/time when the post was originally published
- `url` - (String) the URL of the original post
- `site` - (String) the URL of the site from which this was published (e.g., blog).  This is available in `meta.link`
- `guid` (String) a unique ID for this post (e.g., use the `guid` property from the feed)

We should then modify our [feed-worker.js](src/feed-worker.js) to use this new Class:

```js
const post = new Post(...);
```

Then we can start working with a `Post` in our code elsewhere.

**Comment by humphd** [comment]
We should also consider whether or not to include different analysis metrics as properties or methods on this type.  Things like word count, reading level, reading time, and the other analysis we've done elsewhere.

**Comment by jatinAroraGit** [comment]
I would like to work on this one

**Comment by humphd** [comment]
It's all yours @jatinAroraGit!

**Comment by humphd** [comment]
@jatinAroraGit the work in #277 that @shmooey is doing to sanitize HTML so it's safe to use it (e.g., no XSS attacks, scripts, etc) is about to land.  When it does, please make sure you use it in this fix to clean `content`.

**Comment by jatinAroraGit** [comment]
Hey @humphd ,
Have been doing what you suggested but on uisng the function in the file: https://github.com/Seneca-CDOT/telescope/blob/master/src/sanitize-html.js
 the  promise returned takes a while to resolve. Even after using .then it does not work and outputs Promise { pending } . Some tests might be required to test the sanitize function for longer blog posts.

**Comment by jatinAroraGit** [comment]
Hey @humphd ,
Working on adding sanitize functionality now.

**Comment by jatinAroraGit** [comment]
Hey @humphd ,
I am stuck on something.
Both textParser and sanitize html  functions are promises and to set values of a class attribute in a constructor I call these functions and use 'then' to make sure to populate values but instead all i get is value set to 'Promise { pending }. Probably missing something but I am not able to find it out yet.

My Class Constructor : 
![image](https://user-images.githubusercontent.com/28763265/69751958-25daaa80-111e-11ea-91e1-236e17585f71.png)
 
My function calling the text parser:
![image](https://user-images.githubusercontent.com/28763265/69752008-4c004a80-111e-11ea-98cb-668fc1b097c8.png)

Result Object : 
![image](https://user-images.githubusercontent.com/28763265/69752038-5cb0c080-111e-11ea-9028-db514ca94cbf.png)

**Comment by humphd** [comment]
There are a few ways we could go.

1. We could require that those async operations happen *before* you get the data in the constructor, so that you don't have to wait.  This would involve changes to code in the callers of your class.  This is probably the easiest way to do it.
1. We could accept a raw `html` string in the constructor, and expose `async` methods on the Post object to *generate* the sanitized html and plain text, using `await` to call these other methods, then memoizing the result so we can return it again later.

I'd be tempted to start with 1.  In other words, you don't need to solve this, the parser who uses your code does.

**Comment by jatinAroraGit** [comment]
Hey @humphd ,
Everything seems to work fine but as soon as I include sanitize function it thows error. Trying to find a workaround for past week but could it be related to the bug mentioned in #352 ?.
If that is the case , I can just submit the PR with text parsing working and add sanitize capability in future.
