### ISSUE TITLE
Allow users to pick positive reactions to blog posts 

### ISSUE THREAD

**Issue by robertbegna** [Seneca-CDOT/telescope#26]
I think it would be interesting to allowing the users to react to each other's blog posts, similar to how facebook lets us react to posts

**Comment by agarcia-caicedo** [comment]
I don't feel this is a constructive way to interact with blogs nor a way to encourage meaningful feedback

**Comment by UltimaBGD** [comment]
I feel like for the blog writers, it would be not exactly convenient. They wouldn't get that feedback on their blogs, only on the planet.

**Comment by humphd** [comment]
I wonder if there is a positive way to do this?  I appreciate what @agarcia-caicedo  is saying.  For example, Medium does "Claps" as a positive reaction, and doesn't offer an inverse, negative reaction.  I kind of like the idea of being able to say, "This is good."  or "Me too!" or something else that would be positive.

**Comment by dbeigi** [comment]
@humphd maybe we could have multiple reactions for people to use?

**Comment by RyanMarzec** [comment]
I agree with @dbeigi idea, I think having a set of reactions would be the best implementation of this, similar to the reactions for the comments here to keep a positive environment. Then we can use the reaction count as a starting point to sort by trending mentioned in #110

**Comment by agarcia-caicedo** [comment]
After a discussion, we have decided against post interactions within telescope. This issue will be closing.
