### ISSUE TITLE
Allow a Post to get stored in Redis

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#260]
In #201 we added [storage.js](src/storage.js) and some initial [tests](test/storage.test.js).  We need to extend that to allow for a Post to be saved and returned from Redis.  We can (eventually) connect this with the work happening in #259 to add a `Post` type, accepting and returning `Post` objects.

We need `addPost()` and `getPost()` methods to be added to the `storage` module.  The code can be similar to what we have now for `addFeed()` and `getFeed()`.  In Redis, a `Post` can be a Hash, with all the different properties in the `Post` object corresponding to fields in the Hash--like the feed does with `name` and `url`.

Each `Post` in Redis will need a unique key.  Let's start by using a `Post`'s `guid` property, and see if that works well enough.

We'll also want to create a `posts` Sorted Set in Redis to hold all the `guid` keys for the posts that we store.  Adding an item to the `posts` set should include the `published` time as a score. In other words, we'll sort the posts in our set according to the date they were written, so it's easy to get them out in the order we want.

See https://redis.io/topics/data-types and other docs on how the Hash and Sorted Set data types work in Redis, and https://github.com/luin/ioredis for docs on how to call them from JavaScript.

**Comment by haichuan0424** [comment]
@humphd I'd like to work on this one with @KarlaChen.

**Comment by humphd** [comment]
OK, sounds good.  Be aware of #259 as well.
