### ISSUE TITLE
Refactor GitHub Actions workflows to use Reusable Workflows

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2602]
Our current CI and Release workflows duplicate a bunch of things.  It would be good if we could have the deploy reuse things from CI, or form a base file.  This is now supported in GitHub Actions, see https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

**Comment by dhillonks** [comment]
Can I work on this?

**Comment by humphd** [comment]
The answer is always 'yes.'

NOTE: this is a brand new feature, so you'll have to research how it works a bit, and we'll have to iterate a bunch.
