### ISSUE TITLE
Switch to Renovate from Dependabot for pnpm support

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2609]
Every dependabot PR is breaking, due to pnpm.  [Until dependabot has pnpm support, let's try renovate](https://github.com/dependabot/dependabot-core/issues/1736#issuecomment-950607617).

**Comment by DukeManh** [comment]
Let's get Renovate to work for us during Christmas.

**Comment by DukeManh** [comment]
@humphd, Renovate pins dependencies by default vs Semver style (can be configured), which style are we pursuing if we add this?
I personally like version pinning with `pnpm-lock` because it makes sure it works for everyone for having to exact same dependencies installed.

**Comment by humphd** [comment]
I'm fine with pinning. We can change later if we don't like it. Thanks for working on this.
