### ISSUE TITLE
Update frontend design to include all Post data

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#261]
In #259 we're creating a type for a Post.  Our frontend UI should take the various properties of a Post into account, and somehow make use of them.  We should also figure out how to display things like reading time, word count, or other analysis we might include.  Not all of this has to be visible in the UI (yet), but we should try to think about where it might go.

**Comment by KarlaChen** [comment]
@humphd  I want to  try it with @haichuan0424 , can you assign it for me?
