### ISSUE TITLE
Update swr to 1.1.1 in order to pick up Andrew's feature work

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2610]
One of my goals for 2022 is that we start to become more outward facing in our Telescope contributions, and find ways to give back to the projects that we depend upon.  Christmas came early and we have one of our first examples of what this looks like.  One of our favourite front-end dependencies is Vercel's [swr](https://swr.vercel.app/), and our colleague @Andrewnt219 has been on an epic journey adding a new feature to it:

- https://github.com/vercel/swr/pull/1690
- https://github.com/vercel/swr/pull/1691
- https://github.com/vercel/swr-site/pull/190

This work has been shipped upstream in v1.1.1.  Let's update in order to get the benefits in Telescope!

**Comment by Andrewnt219** [comment]
Thanks for the shout-out. I'll happily make this upgrade. 

As for its use, I can only think of this case where [backend includes an interval in the response](https://github.com/vercel/swr/releases/tag/1.1.1)

**Comment by humphd** [comment]
We don't need to find a way to use the feature, I just want it updated as reflection of the work, and what it represents.  This is the way to exist in the open source ecosystem: dependencies should be something we use, but also something we help maintain.
