### ISSUE TITLE
Update environment-setup.md to install and use pnpm

### ISSUE THREAD

**Issue by irenejoeunpark** [Seneca-CDOT/telescope#2620]
**What happened**: Current document instructs to use npm

**What should have happened**: Update the document on how to install and run using pnpm

**Environment**:

- OS: Windows
- Browser:

**Comment by cindyledev** [comment]
Hi @irenejoeunpark, seems like this issue has already been fixed https://github.com/Seneca-CDOT/telescope/commit/119f829237bfe1746266db781c2659aea8de9f0d. Closing.
