### ISSUE TITLE
Build log claims to not be able to get build status when no build running

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2622]
When there's no current build running, the build log page shows an error message:

<img width="1275" alt="Screen Shot 2021-12-16 at 9 54 31 AM" src="https://user-images.githubusercontent.com/427398/146394676-5c490487-04ad-4005-88da-674eeb0ffeeb.png">

However, the problem isn't that it can't get build status, it's just that there is no `current` build running.  Let's improve this.

Also, ideally we should be showing details about the previous build, so if you come and the build finished 5 mins ago, it shows you that instead of nothing.

**Comment by nguyenhung15913** [comment]
Hi @humphd if there is no current, the page show no error message, that is the message that has been set up if there is no current. I have fixed it to make it more clear. Please take a look at my PR for more detail. Thanks
