### ISSUE TITLE
Fix naming of "Users" in GitHub Info

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2627]
What we're calling "Users" in the GitHub info sidebar is really "Users/Orgs" or "Users and Orgs":

<img width="183" alt="Screen Shot 2021-12-18 at 9 47 56 AM" src="https://user-images.githubusercontent.com/427398/146645168-bffdcb3c-1362-48ae-acf8-c52eae687591.png">

**Comment by HyperTHD** [comment]
Taking this
