### ISSUE TITLE
Update frontend to fetch() post data from the web server

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#263]
In #262 we're adding routes to the web server to allow for getting `data from the database, /posts` (all post IDs in the database); and `/post/<id>` (get a particular post).  In #261 we're updating the frontend code to make use of all the data in a post (see #259).

We also need to change the frontend code so that it uses [fetch()](https://developers.google.com/web/updates/2015/03/introduction-to-fetch) to get post JSON data from the server, and "renders" it in our frontend.

For now, we can do this with jQuery or raw DOM API calls, and later we can move to some framework and components.

Keep the scope of this fix small: we need to get data from the web server, and use it to show posts in the page.

**Comment by lucacataldo** [comment]
I'm going to work on this as more data gets exposed from the webserver (ie #262 gets done). In fact, I'm thinking of pairing these two together to try and speed things up if no one else claims 262 by the end of today.

**Comment by humphd** [comment]
Awesome, thanks @lucacataldo.  One thought for you and others, as we begin this: we can feed fake data into the pipeline at any point to help connect the system.  What I mean is, don't get blocked on missing pieces (e.g., posts in Redis), just land code that returns fake data of the right format until we get real pieces in place to give good data.  Make sense?

**Comment by lucacataldo** [comment]
Yup makes sense! Thanks I'll try and get started then
