### ISSUE TITLE
Happy New Year!

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2639]
We're failing CI with a front-end snapshot test that is hard-coding the year 2021.  Welcome to 2022 everyone!

See:

- https://github.com/Seneca-CDOT/telescope/runs/4693402544?check_suite_focus=true
- https://github.com/Seneca-CDOT/telescope/blob/d751549c04d99d366f88bed624cdda5ff2b40fa5/src/web/src/components/__snapshots__/AboutFooter.test.tsx.snap#L155

**Comment by DukeManh** [comment]
It's probably better to mock the `Date()` function. https://jestjs.io/docs/snapshot-testing#2-tests-should-be-deterministic
