### ISSUE TITLE
Build a better picture of our dependency graph

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2649]
One of the 3.0 goals is to start being better stewards of the ecosystems we depend upon.  Telescope has lots of its own code, but if you consider all of the things we use (npm modules, docker images, command line tools, libraries, frameworks, etc.), it's massive.  However, we have very little visibility into it.  I'd like to change that.

Students often want help finding projects to work on in OSD600/DPS909, and it would be good if we could point at a giant (dynamic) list of Issues marked `bug, `good first issue`, `help wanted`, etc.

In addition, I'd like to see us contributing fixes and features to some of these upstream projects in 2022, and helping to maintain the open source we need.

Let's begin to build this graph.  At first, it could be a manual thing we create.  Later, once we understand it a bit more, we can try to automate it.

Google has a neat tool for helping to find and visualize your dependencies: https://deps.dev.  Here is Satellite for example: https://deps.dev/npm/%40senecacdot%2Fsatellite.

**Comment by menghif** [comment]
The "Insights" tab also provides a list of GitHub links to all the dependencies we use.
https://github.com/Seneca-CDOT/telescope/network/dependencies

**Comment by humphd** [comment]
I really want to do this in an automated way.

Because we're now using `pnpm` we can use the [`list` command](https://pnpm.io/cli/list) to help us:

```
$ pnpm list --recursive --depth 2 --json

/Users/humphd/repos/telescope/tools/autodeployment/node_modules/.pnpm/type-is@1.6.18
/Users/humphd/repos/telescope/tools/autodeployment/node_modules/.pnpm/unicode-byte-truncate@1.0.0
/Users/humphd/repos/telescope/tools/autodeployment/node_modules/.pnpm/utils-merge@1.0.1
/Users/humphd/repos/telescope/tools/autodeployment/node_modules/.pnpm/vary@1.1.2
/Users/humphd/repos/telescope/tools/autodeployment/node_modules/.pnpm/vary@1.1.2
/Users/humphd/repos/telescope/tools/autodeployment/node_modules/.pnpm/vizion@2.2.1
/Users/humphd/repos/telescope/tools/autodeployment/node_modules/.pnpm/whatwg-url@5.0.0
/Users/humphd/repos/telescope/tools/autodeployment/node_modules/.pnpm/ws@7.4.6
/Users/humphd/repos/telescope/tools/autodeployment/node_modules/.pnpm/ws@7.5.6
/Users/humphd/repos/telescope/tools/autodeployment/node_modules/.pnpm/yamljs@0.3.0
...
```

This gives us our dependencies, and their dependencies, up to a depth of 2 (we can go deeper if we want).  With a bit of regex parsing, we can extract the package names, and then use that to query the GitHub API for bugs we could fix.

We could probably extend https://github.com/mjswensen/shoulders to do this for pnpm, since it already does most of what we need.

**Comment by JerryHue** [comment]
I am aware that this might be a little bit too early to ask about this question, but I am wondering how the end application is going to be like.

Do we want a CLI like [`shoulders`](https://github.com/mjswensen/shoulders), which you invoke at the root of your project and extract the information from the package.json file? Or do we want a CLI that accepts a link to a GitHub repository?

**Comment by humphd** [comment]
I think that since Telescope is a web service and web app, we should think in those terms.  Imagine a little microservice that does periodic querying of our dependencies and gets GitHub data, caches it in Redis, then uses that to create some dashboard views that users can look through.

A cool first prototype might be a list of Issues labelled "good first issue" in any of our dependencies, or their dependencies, that you can scroll though, and click to go see them on GitHub.

**Comment by JerryHue** [comment]
> I think that since Telescope is a web service and web app, we should think in those terms. Imagine a little microservice that does periodic querying of our dependencies and gets GitHub data, caches it in Redis, then uses that to create some dashboard views that users can look through.

This sounds promising! I will try to see if I can come up with anything during the weekend. If anybody else is up for this prototype, you may contact me. I'd love to discuss it further.

**Comment by TDDR** [comment]
Related discussion #2666
