### ISSUE TITLE
Rendering bug in macOS Monterey with Chromium browsers

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2659]
There's an interesting rendering bug happening in Chrome (and other Chromium-based browsers) in macOS Monterey.  Here's Firefox, Safari, and Chrome (right-hand side).  Notice the `-` vs. `x`:

<img width="719" alt="Screen Shot 2022-01-16 at 11 24 50 AM" src="https://user-images.githubusercontent.com/427398/149668630-14b322e5-90d3-4ba2-8503-dfe25dca48c3.png">

Apparently it's [fixed in Chrome 98](https://bugs.chromium.org/p/chromium/issues/detail?id=1267606), due later in February.  Until then, I wanted to file an issue on it, and also point at a [work-around](https://www.bram.us/2021/12/18/broken-hyphens-in-chromium-96-an-explanation-and-fix/).

**Comment by JiaHua-Zou** [comment]
Is this issue still available?

**Comment by humphd** [comment]
There's nothing to be done on our side, it's just informational.

**Comment by menghif** [comment]
Chrome 98 was released today and I can confirm that it fixed this bug. Closing Issue.
