### ISSUE TITLE
Connect wiki-feed-parser to feed queue

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#266]
We have code to download and parse the Wiki Feed List page in [wiki-feed-parser.js](src/wiki-feed-parser.js).  We should connect this into our [logic for enqueuing feed jobs](https://github.com/Seneca-CDOT/telescope/blob/master/src/index.js#L50).  Most of the code in [src/index.js](src/index.js) related to reading [feeds.txt](feeds.txt) can get deleted now, along with that file.

When this is done, our feed queue should get filled with all the real feeds of our wiki list.

NOTE: #265 is adding tests for the wiki-feed-parser.

**Comment by cryolis** [comment]
Can I try this if none is working on it yet?

**Comment by humphd** [comment]
Sure @cryolis, go for it.

**Comment by humphd** [comment]
@cryolis how is this coming?  We are going to need this to land soon.  If you can't do it, I'll give it to someone else so we make sure it gets done.  Let me know.

**Comment by cryolis** [comment]
@humphd Sorry I was working on the external project. I will start on this today.

**Comment by cryolis** [comment]
I think im done with it, but when I run it some jobs get completed and some get errors, could that be because the urls that are getting read no longer exist?

**Comment by humphd** [comment]
Great, thanks for diving into this.  In terms of the errors, I suspect that using that live data set is going to mean we'll uncover a lot of edge cases (blogs that don't exist anymore, invalid URLs, servers that sometimes return data and sometimes don't, HTML being sent back vs. XML, etc).

This is part of why I want to get your code in quickly, so we can start filing/fixing these issues.

I'd say get a PR up with what you have, and let's start the review process so we can get it merged.
