### ISSUE TITLE
Add autodeployment server to Status list for services

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2663]
Right now the autodeployment server is down (https://dev.telescope.cdot.systems/deploy is 502).  If I go to https://dev.api.telescope.cdot.systems/v1/status, at the bottom, we have a bunch of status checks for our services.  However, the autodeployment server isn't there.

Let's add it so we can see when it fails.

**Comment by JiaHua-Zou** [comment]
I can add the status if its not done yet.
