### ISSUE TITLE
Update the `.travis.yml` to use Docker's Redis image for all OS platforms

### ISSUE THREAD

**Issue by Reza-Rajabi** [Seneca-CDOT/telescope#267]
Travis uses its virtual build and test environment to build and test our pull requests on Github. Sometimes before sending a pull request, we might want to make sure that all Travis tests will be passed. In this case, we need to set up and test with Travis locally. The problem arises when the local installation is needed: Redis installation for local Travis seems to be a pain.
- The first solution is running Travis on Docker Desktop. This solution will be included in our Docker files in #4 .
- The second solution is installing Travis itself locally which is the subject of this issue.
   Currently, our `.travis.yml` is using different sets of commands to install Redis based on different local OSs. That would be nice if we could get it to work by only pulling one Docker image for Redis. This problem has experimented so far in #181 . 
This issue might end up having no solution.

**Comment by humphd** [comment]
If we can make it work, the actual code change needed here is pretty simple, see [docs](https://docs.travis-ci.com/user/docker/).  Essentially:

1. add `docker` to the list of [`services` we have](https://github.com/Seneca-CDOT/telescope/blob/master/.travis.yml#L4)
1. for [one (or all) of the OS install steps](https://github.com/Seneca-CDOT/telescope/blob/master/.travis.yml#L30-L42), run the appropriate `docker` command(s) to get Redis

**Comment by humphd** [comment]
This same pattern could be used with Circle CI, see @robertbegna.

**Comment by humphd** [comment]
@Manan311 and I were discussing this in class today, and https://github.com/travis-ci/travis-ci/issues/5738 would seem to indicate that using Docker on Mac is not going to happen.

**Comment by Manan311** [comment]
@humphd I think we might be able to incorporate it with Linux and windows but I am still looking into it and need to do a bit more research on it.

**Comment by humphd** [comment]
The problem I had on Windows is that Travis is using AMD64 for Windows and I couldn't find a compatible Windows AMD64 docker image that would work.  There are some, but they seemed to be built for Linux.

**Comment by Manan311** [comment]
[How to install docker chocolatey way.](https://stefanscherer.github.io/how-to-install-docker-the-chocolatey-way/)
[Docker for Windows](https://chocolatey.org/packages?q=docker)
[Get started: Prep Windows for containers - Microsoft Docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server)

I am not far in research yet or tried anything out yet but these are some links I am looking at right now. I remember that Travis only had support for only 1 version of windows. Docker doesn't work on windows server 2016 and 2019.

> Travis uses its virtual build and test environment to build and test our pull requests on Github. Sometimes before sending a pull request, we might want to make sure that all Travis tests will be passed. In this case, we need to set up and test with Travis locally. The problem arises when the local installation is needed: Redis installation for local Travis seems to be a pain.
> 
> * The first solution is running Travis on Docker Desktop. This solution will be included in our Docker files in #4 .
> * The second solution is installing Travis itself locally which is the subject of this issue.
>   Currently, our `.travis.yml` is using different sets of commands to install Redis based on different local OSs. That would be nice if we could get it to work by only pulling one Docker image for Redis. This problem has experimented so far in #181 .
>   This issue might end up having no solution.

I have been looking at number 2 more since we have a start on it with Redis right now but I think we might need to start looking for option one where we pull the Travis image from docker itself.

**Comment by Manan311** [comment]
I don't think this is possible for windows and mac so we decided to close this. All my findings are in my blog [here](https://manan-patels-blog.blogspot.com/2019/12/the-learning-curve.html).
