### ISSUE TITLE
Add a bundler to dashboard

### ISSUE THREAD

**Issue by Andrewnt219** [Seneca-CDOT/telescope#2671]
**What would you like to be added**:
Options:
- [Vite](https://vitejs.dev/)
- [Snowpack](https://www.snowpack.dev/)
- [Parcel](https://parceljs.org/)

These bundlers work out-of-the-box. For simple use cases, they require little to zero configs. Speed is a plus, but we only have vanilla js so it is not really an issue.

**Why would you like this to be added**:
- Mix `import` and `require`
- Polyfill cutting-edge syntax.
- Browsers only download one js file instead of multiple modules (because of how js native modules work).

**Comment by Andrewnt219** [comment]
Just some updates on this issue:

### Snowpack
Snowpack [doesn't work with `pnpm`](https://github.com/pnpm/pnpm/issues/3749), so it's out of question.

### Vite
There's documentation for express or [handlebars](https://handlebarsjs.com/) (client-side), but not express-handlebars.

### Parcel
Same problem as Vite.

# Possible solutions (not tested, just theory)

### Using Vite Backend integration
https://vitejs.dev/guide/backend-integration.html
I've just found out about this, but it seems like hope. So technically, we don't process the HTML (i.e handlebars), just bundling the javascript and point the handlebars to that.  


### Using handlebars client-side
Some hassle to move away from express-handlebars, but after that, there are examples I can follow. Of course, the current server-side javascript fetching (e.g. fetch weekly commit count) has to become API end-point or client-side fetching.

### Using Vite.js SSR
https://vitejs.dev/guide/ssr.html#setting-up-the-dev-server
This is NOT production-ready. 
Summary: we write the logic to transform handlebars to HTML, then pass that to vite middlewares.

### Using webpack
There were some similar answers came up for webpack with express-handlebars, but they were cryptic. Need time to figure out how to set up that.

**Comment by humphd** [comment]
This is great background, thanks for digging into this.  Another wrinkle we'll have is that we (currently) use `pnpm` in the monorepo, and `npm` in our container when we deploy.
