### ISSUE TITLE
`useMedia` When server side rendering, defaultState should be defined to prevent a hydration mismatches.

### ISSUE THREAD

**Issue by chrispinkney** [Seneca-CDOT/telescope#2672]
**What happened**:
While running the front-end the message in the title constantly appears.

**What should have happened**:
No error message should have occurred.

**How to reproduce it (as precise as possible)**:
Run the front-end locally.

**Environment**:
- OS: Manjaro Linux
- Browser: Firefox 96

**Comment by DukeManh** [comment]
This warning comes from 'react-use/useMedia' hook. Basically, 'useMedia' hook is asking for a default state otherwise the browser will fall back to `false` when server-side rendering which might not match the client's state.
