### ISSUE TITLE
Avatar initials should only use letters

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2674]
I added a second blog feed for myself to test the work that @dbelokon is doing with YouTube feeds, and the feed's name is "David Humphrey (YouTube)".  Our avatar logic is using `(` as my final initial:

<img width="216" alt="Screen Shot 2022-01-19 at 10 14 07 AM" src="https://user-images.githubusercontent.com/427398/150159495-badd0aba-9133-4223-adaa-64e3ee6e912e.png">

We should probably have this only use letters.  I'm not sure what the right logic would be here to have it get "DH" vs. "DY" for YouTube.

**Comment by joelazwar** [comment]
@humphd just want to make sure, so for video Feeds the initials would be first letter of first name and Y for youtube(e.g. DY)? Assuming that all the feeds will have the same format of `"{name} (Youtube)"` we can just invoke the replace("(Youtube)", "Y") method and the logic.

```js
if (name.length > 0) {
    const initials = name
      .replace("(YouTube)", "Y")
      .split(' ')
      // splitName represents the current value, i represents its index, and arr represent the whole splitted name-word array
      // if the index is 0, means it's the first word in the name
      // if the index+1 equals to the array length, it means the current value is the last word in the name
      // anything rather than first word or last word will not be included in initials
      .map((splitName, i, arr) =>
        i === 0 || i + 1 === arr.length ? splitName[0].toUpperCase() : null
      )
      .join('');
```
any other use cases you can think of?

**Comment by humphd** [comment]
I don't have any opinion on what the name will be, I just know that when I included a `(...)` it did something surprising.  I would maybe consider removing characters like (...) from the string first.

**Comment by joelazwar** [comment]
we could use regex to eliminate subtitles in brackets like those e.g. `const initials = name.replace([\(\]]\w*[\)\]] '').trim()`
