### ISSUE TITLE
Allow YouTube channels to be added via the sign-up UI

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2676]
In #2675 we're adding support for YouTube feed discovery.  We need to update the UI to allow a user to include their YouTube channel, along with their blog(s).

**Comment by nguyenhung15913** [comment]
Hi David,  I would like to know this issue in more details. Should we add a new form field for the user to enter the Youtube channel in the Sign Up page? Also at the moment, when I am trying to sign up for Telescope, there is a pop-up but it only has 2 buttons (previous and next)

**Comment by nguyenhung15913** [comment]
![image](https://user-images.githubusercontent.com/69558780/150237220-186eadec-1ec4-4628-b5a4-3fc9c6cf1774.png)
here is the screenshot

**Comment by humphd** [comment]
We have a form now for adding your blog URL(s), and we need to update the wording and verification code so it is clear you can include a YouTube channel.

**Comment by nguyenhung15913** [comment]
I guess the form you are talking about is in <code>src\web\src\components\SignUp\Forms\RSSFeeds.tsx</code> right? My question is how does it look like in the browser or where can I see the form? Because the screenshot above is what I have when I press the Sign Up button.

**Comment by humphd** [comment]
We've got the sign-up stuff turned off at the moment.  Talk to @DukeManh, he wrote a lot of it, and can give some ideas.

**Comment by DukeManh** [comment]
I'll have a PR for fixing this Bug.

**Comment by JerryHue** [comment]
@nguyenhung15913, what is the progress related to this issue? Have you managed to implement a small PR that can address it?

**Comment by DukeManh** [comment]
@nguyenhung15913 , if you can make a draft PR, I can help debug the CSS with you.

**Comment by nguyenhung15913** [comment]
> @nguyenhung15913 , if you can make a draft PR, I can help debug the CSS with you.

For now, I have been working on the loading posts for Mobile app, because we don't have a lot of time and the posts component is huge. If no one is working on this, I can do it

**Comment by menghif** [comment]
Closed in #3505
