### ISSUE TITLE
Wrap URL links into <a> elements in YouTube descriptions

### ISSUE THREAD

**Issue by dbelokon** [Seneca-CDOT/telescope#2679]
## What would you like to be added

I would like any links found in YouTube descriptions to be actually clickable links, which can be done by being wrapped in an anchor  (`<a>`) element.

## Why would you like this to be added

To improve overall navigation. A mobile user might find cumbersome to copy the whole link and paste it in their browser to be able to navigate to that link. The same applies to PC users.

## Additional information

In #2581, we added support to track video posts from an RSS feed produced by an old YouTube API. The description of the video is considered the text of a regular blogpost. 

In #2596, these video posts are now displayed in the timeline. During review, @humphd noticed that links found in the descriptions do not actually work. This issue is supposed to address this.

**Comment by tpmai22** [comment]
@dbelokon I think it will be a quick fix. I can work on this
