### ISSUE TITLE
[Satellite] Migrate npm engine to pnpm

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-CDOT/telescope#2694]
**What would you like to be added**:
I would like to migrate satellite repo that currently uses `npm` to `pnpm` engine, like what we did in telescope

**Comment by menghif** [comment]
You should open this issue in the [Satellite](https://github.com/Seneca-CDOT/satellite/issues) repo.

**Comment by menghif** [comment]
No problem. Also #2677 is related, we're looking to move satellite into this repo.

**Comment by humphd** [comment]
PR in Satellite repo, Issue here.
