### ISSUE TITLE
Wrong commit SHA in `staging`

### ISSUE THREAD

**Issue by dbelokon** [Seneca-CDOT/telescope#2697]
**What happened**: Today, I head over the [`staging`](https://dev.telescope.cdot.systems) deployment, and I clicked on the version tag (as of right now, it is version 2.5.0). After clicking it redirected to a commit that does not exist (the SHA in the link does not reference an existing commit).

**What should have happened**: A page that shows an existing commit.

**How to reproduce it (as precise as possible)**: Go to [`staging`](https://dev.telescope.cdot.systems) and click on the version tag.

**Anything else we need to know?**: This might be related to #2650 or not. I am not really sure.

**Environment**:

- OS: Windows 10
- Browser: FireFox v. 95.0.2

**Comment by manekenpix** [comment]
It seems that this issue only happens during releases.
From what I can see, the current commit displayed in staging is https://github.com/Seneca-CDOT/telescope/commit/fd66d60f67d6491e4fd008a1deeee620e2711ea1, and checking the logs, I see that 2 events took place during the `2.5.0` release:
![image](https://user-images.githubusercontent.com/23108901/150444268-34df6166-0a36-41d0-8114-e79d45d6f241.png)

and one of them had this payload:
```json
"ref": "refs/tags/2.5.0",
"before": "0000000000000000000000000000000000000000",
"after": "fd66d60f67d6491e4fd008a1deeee620e2711ea1",
```
with the same commit sha that's currently displayed in `staging`. I wonder if somehow we process this request and end up with this wrong sha in `staging`.
