### ISSUE TITLE
Refactor wiki-feed-parser.js to use text-parser.js

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#270]
We've got two parallel implementations of "HTML to Text" parsers in the tree:

- [src/wiki-feed-parser.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/wiki-feed-parser.js) and `getData()`
- [src/text-parser.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/text-parser.js)

In #187 we're going to be reworking our code to use [Puppeteer](https://pptr.dev/), which has a lot more power than JSOM.

Let's refactor the wiki-feed-parser code to also use our text-parser.

cc @PavanKKamra, @cryolis, @giatuongtran9

**Comment by giatuongtran9** [comment]
I can give it a try since I do the testing for ```text-parser.js```

**Comment by humphd** [comment]
@giatuongtran9 do you want to pick one to work on between this and #187?  We can let others work on it too that way.  Ideally we'll do 1 issue per person to start, so we have something for everyone.

**Comment by giatuongtran9** [comment]
I will work on the #187 then

**Comment by humphd** [comment]
Great.  If you get #187 done and this is still open, go ahead and grab it.

**Comment by UltimaBGD** [comment]
The idea for this one is to remove the getData function from wiki-feed-parser and replace it with the exported run function from text-parser.js? I can take a look at it if that is the case.
