### ISSUE TITLE
GitHub Users tagged in posts are not showing under user/organization

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2707]
**What happened**:
My github profile was linked in Luigi's post, but I do not see my avatar under user/organization
![image](https://user-images.githubusercontent.com/77639637/150625651-2a53baec-52d6-4635-86f2-0228c512cf2e.png)

**What should have happened**:
I should see my avatar for GitHub under the user/organization. Like this post: 
![image](https://user-images.githubusercontent.com/77639637/150625746-229661db-b5f2-4ec2-9eb8-bbb5a6bf5b3e.png)

**How to reproduce it (as precise as possible)**:
If you add a blog with a link to a github profile, it will not show up. If you add a repository owned by a user (not organization), the user will show up under user/orgs. This is confusing, the reference was to the repository, which already has its own section on the side. 

**Anything else we need to know?**:

The posts are different because the correct one includes a link to open parliament `https://github.com/michaelmulley/openparliament`, however when we look at the user/orgs we are directed to Michael Mulley's GitHub Page... This can be a bit confusing because I think that Michael Mulley is involved in the post, not his repository (the repo is already in the repository section).

Can we look into whether the users are the repositories for the users, or the actual users' page? It would be cool if we can tag each other's GitHub in the posts. I was considering this when writing mine, but wasn't too sure if it picks up on Telescope... (it doesn't). 

**Environment**:

- OS:
- Browser:

**Comment by Andrewnt219** [comment]
https://github.com/Seneca-CDOT/telescope/blob/e1e546a58039d7bee642f5ee25fa55865f0a6524/src/web/src/components/Posts/GitHubInfo.tsx#L54-L64

So the problem is from this line. It expects GitHub links to always have the repos in it (e.g. /username/repo ✅, /username ❌). We can try to make the second capturing group `(?<repo>[^/]+)` optional as well, then test if the 4 listed examples are still working. [Regex 101](regex101.com) is a good tool for testing.

**Comment by AmasiaNalbandian** [comment]
> https://github.com/Seneca-CDOT/telescope/blob/e1e546a58039d7bee642f5ee25fa55865f0a6524/src/web/src/components/Posts/GitHubInfo.tsx#L54-L64
> 
> So the problem is from this line. It expects GitHub links to always have the repos in it (e.g. /username/repo ✅, /username ❌). We can try to make the second capturing group `(?<repo>[^/]+)` optional as well, then test if the 4 listed examples are still working. [Regex 101](regex101.com) is a good tool for testing.

Ok this sounds good - we should decide if we want to include the users who's repo it is in the user section though.

**Comment by Andrewnt219** [comment]
> However when we look at the user/orgs we are directed to Michael Mulley's GitHub Page... This can be a bit confusing because I think that Michael Mulley is involved in the post, not his repository

This is a feature, not a bug (not joking 🙂). The GitHub Info tab does not represent all the links that are mentioned in a post. It simply extracts all the info from GitHub links in a post. Therefore, if a post only mention a single link /Seneca-CDOT/telescope, the Users will have Seneca-CDOT and the repos will have telescope.

I think this also answer the above question.

**Comment by AmasiaNalbandian** [comment]
Yes it does @Andrewnt219 . So we missed a scenario when implementing this. Thank you for investigating all of this! I really appreciate it.

**Comment by Kevan-Y** [comment]
If that issue is not taken. I can work on it.
