### ISSUE TITLE
http://localhost:3000 is missing styles, logo, needs express.static middleware

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#271]
Our current frontend doesn't load properly:

<img width="1091" alt="Screen Shot 2019-11-17 at 7 15 53 PM" src="https://user-images.githubusercontent.com/427398/69016690-bbcc4380-096e-11ea-8270-eb7d112912fe.png">

There are a bunch of issues:

- style/main.css is being sent with a mime type of text/html vs. text/css
- 404 on /dialogue.js
- 404 on img/logo.svg

**Comment by cindyledev** [comment]
I can fix this

**Comment by cindyledev** [comment]
I lied I don't know how to fix this....

**Comment by humphd** [comment]
@cindyledev see https://expressjs.com/en/starter/static-files.html.  The problem is that our web server is serving the index.html raw as a file, but none of the other resources are being served.  Add express static middleware.

cc @miggs125

**Comment by lucacataldo** [comment]
@cindyledev Hey, if you need some help I put together a fix in a temp branch I've got for some frontend stuff. In /src/backend/web/routes/index.js you can replace the router.get("/"...) with the following to create a static server in the frontend directory:

![image](https://user-images.githubusercontent.com/35984346/69253102-0ffb4180-0b82-11ea-9e88-58264090decc.png)

**Comment by cindyledev** [comment]
Thanks @lucacataldo , your fixed worked, I'm gonna submit a PR after #305 gets merged
