### ISSUE TITLE
Sign in 400 Error: Unexpected access of callback

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2710]
I was working on integrating `Supbase` and `Auth` service and encountered this login error. It happened both on `dev` and `production`.

I suspect it must have something to do with the `user session` because I can still sign in in `incognito` mode in `production`. On `dev`, sign-in doesn't work in any mode.

cc @humphd 
Please help me

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/51073515/150641135-735081a7-6e94-4971-88e9-f952fa1ec2a2.png">

**What happened**:

**What should have happened**:

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by humphd** [comment]
So this is only about dev?  I'd like more details and STR.

I wonder if we should get on a call this week so you can demo what's up.

**Comment by DukeManh** [comment]
It's on production too, it should happen when you sign in or log out and sign in. https://telescope.cdot.systems/

Do you mean demo the bug or the Supbabase stuff? Either one, let's talk about it this week.

**Comment by DukeManh** [comment]
I can't replicate this anymore. I am closing this and will open it when it happens again.
