### ISSUE TITLE
Security update for node-fetch

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2711]
We have a security issue that needs to be fixed ASAP: node-fetch 2.6.x -> 2.6.7 https://github.com/node-fetch/node-fetch/releases/tag/v2.6.7.  We need this in Telescope and Satellite:

- https://github.com/Seneca-CDOT/telescope/search?q=node-fetch
- https://github.com/Seneca-CDOT/satellite/blob/master/package.json#L36

Most users of `node-fetch` in microservices get it via Satellite, so fixing it there and doing a new release of Satellite, then bumping Satellite will fix that. But we also have it in tests and the legacy backend.

cc in-coming Sheriffs: @AmasiaNalbandian, @DukeManh

**Comment by AmasiaNalbandian** [comment]
What happened to the PR by the bot? It wasn't merged but closed...?

**Comment by humphd** [comment]
I'm not sure.  It was having issues with wanting to go to the `3.x` release.  We're still at `2.6.6`, see https://github.com/Seneca-CDOT/telescope/blob/master/package.json#L69

**Comment by DukeManh** [comment]
It was strange that Renovate opened and closed it.

**Comment by humphd** [comment]
There was some chatter on GitHub over the weekend about some security tools incorrectly flagging the `3.x` release as the only secure one vs. `2.6.7`.  I wonder if it got closed due to it thinking it didn't address the problem.

**Comment by DukeManh** [comment]
@humphd I couldn't find the discussion, could you link it here, please.

**Comment by humphd** [comment]
Sorry, it was on Twitter.  I don't think I can find it again.  At any rate, we can do it manually if we need to.

**Comment by DukeManh** [comment]
This was partially fixed in #2724, there's an issue for why Renovate didn't update it in './tools' as well. https://github.com/Seneca-CDOT/telescope/issues/2725
