### ISSUE TITLE
Autodeployment sends wrong status code

### ISSUE THREAD

**Issue by Andrewnt219** [Seneca-CDOT/telescope#2719]
**What happened**:

Build success but auto-deployment send code 1.

![image](https://user-images.githubusercontent.com/52666982/150663612-667585db-380e-4641-b4ac-76992dd53381.png)

![image](https://user-images.githubusercontent.com/52666982/150663615-a9b341ab-d714-43b9-98db-d9d805ff258d.png)

**What should have happened**:

Auto-deployment should send code 0.

**How to reproduce it (as precise as possible)**:

Pre-condition: the lastest build is success

- Access https://dev.telescope.cdot.systems/deploy/status
- `previous.code` is 1 instead of 0.

**Anything else we need to know?**:

**Environment**:

- OS: Window 11
- Browser: Chrome 97

**Comment by tpmai22** [comment]
I will take this as well since it related to my area !

**Comment by humphd** [comment]
We set the build exit code [here](https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/builds.js#L80), and this is using [`shelljs.exec()`](https://github.com/shelljs/shelljs#execcommand--options--callback), which is supposed to return the process exit code as the first arg to the callback.  [Here's the code that it's running](https://github.com/shelljs/shelljs/blob/master/src/exec.js#L148-L158).

So maybe the build process is always failing, and we should figure out why.

**Comment by tpmai22** [comment]
But base on the code I guess it will always return the previous build.  Yesterday when I try to ran it on local host it return `404` on `localhost/deploy/status` as  well so I wonder if it hit the correct URL

**Comment by Andrewnt219** [comment]
> But base on the code I guess it will always return the previous build.

Yes, if there's no on-going build. 

> I wonder if it hit the correct URL

Same with the build-header PR, you cannot run auto-deployment (i.e. /deploy) locally. To test that, point it to [staging](https://dev.telescope.cdot.systems/deploy/status). If the result column show "Success" instead of "Error", you are heading the right way.

![image](https://user-images.githubusercontent.com/52666982/150802468-b4a7fe8b-19d3-4f52-a739-8b37db04dc2d.png)

**Comment by tpmai22** [comment]
I try to research on what @humphd was mentioned about our build might not be success but I got no clue yet. The fix will be easy where you only change one logic but I guess we try to find the root of cause here

**Comment by humphd** [comment]
It's possible that our [deploy script](https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/deploy.sh) is erroring on the last step (or one of the last steps) and we are returning that result each time.  cc @manekenpix

**Comment by manekenpix** [comment]
I'll do some testing later to see which step is failing

**Comment by tpmai22** [comment]
As dicussed [here](https://github.com/Seneca-CDOT/telescope/pull/2695#issuecomment-1020760044) after I jump on call with @manekenpix he had kindly fix it so I will close this issue

**Comment by Andrewnt219** [comment]
@manekenpix I think someone accidentally fixed the issue?  Working on staging 🤣.

![image](https://user-images.githubusercontent.com/52666982/151095382-5c8d88b2-194c-4afd-9007-f08d2c7e10b7.png)

**Comment by humphd** [comment]
Can we get #2695 reviewed and merged before we tackle this?  I'm changing a bunch of related code.
