### ISSUE TITLE
Add webhint for extra frontend checks

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#272]
Let's integrate https://webhint.io/ into our npm scripts.  Webhint is cool because it gives you all kinds of [information about errors, warnings, and other issues in a web page](https://webhint.io/docs/user-guide/hints/).  You use the `hint` command to test your page, for us that would be `http://localhost:3000/`, and it gives back a report with all sorts of things you can improve with CSS, security, accessibility, performance, etc.

I ran it on our current page and it gives 107 errors/warnings, many of which we could easily fix.

The [User Guide](https://webhint.io/docs/user-guide/) is great, and it talks about how to integrate this into [local dev](https://webhint.io/docs/user-guide/development-flow-integration/local-server/), [Travis CI](https://webhint.io/docs/user-guide/development-flow-integration/travisci/), or [Circle CI](https://webhint.io/docs/user-guide/development-flow-integration/circleci/), all of which we use.

We probably don't need to fail our builds over these errors, like eslint; but we should add a way to run this easily so people working on the frontend can find issues and fix them.

**Comment by robertbegna** [comment]
I'd like to try this for release 0.4

**Comment by humphd** [comment]
OK @robertbegna, let's discuss when we see each other and make a plan.  I'll assign it to you.

**Comment by humphd** [comment]
Closed in d36593d7b5785912933f1aeac250eb02dc9c98db
