### ISSUE TITLE
Integrate RN project into monorepo, integrate with existing project tooling

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2729]
**What would you like to be added**:
Lets start the directory system, and get it working with pnpm environment. We just need the basic project set up so we can start. 

Note: We can just have the RN application run with just a logo - that is completely fine. 
**Why would you like this to be added**:

**Comment by humphd** [comment]
I would put this in `src/mobile` when you do it, so it mirrors `src/web`
