### ISSUE TITLE
Write a command line tool for injecting a feed into the queue

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#273]
In #112, I mentioned a cool idea that I got from [this code](https://github.com/GetStream/Winds/blob/48cda6bef1ae4cd0612368bef86becead4f0e8c5/api/src/commands/winds-og.js) is to add a node.js command-line tool that lets you inject a feed name/URL manually into the running queue.

This would be great for debugging, and for our testing purposes right now, while we wait to get all the feeds loading automatically.

This is somewhat similar to #266, but where that one is an automated process that goes and reads data from the wiki page, this one would be to write a command line tool that works like this:

```
$ node add-feed.js "FirstName LastLastName" https://url.to/user/feed.xml
```

This would cause the user "FirstName LastName", and their feed URL to be inserted into our running feed queue, and make it easier to test.

**Comment by miggs125** [comment]
I'll take this
