### ISSUE TITLE
React Native: Basic UI Started for the app

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2731]
**What would you like to be added**:
We want to see our React Native App have some basic UI, with some navigation.

Will be blocked by https://github.com/Seneca-CDOT/telescope/issues/2730
**Why would you like this to be added**:

**Comment by Kevan-Y** [comment]
I think at the same time we can set the structure of the repo.
For examples
```
├── src
│   ├── assets
│   │  ├── fonts
│   │  ├── images
│   ├── components
│   ├── navigations
│   ├── screens
│   ├── styles
│   ├── utils
│   ├── App.tsx
├── app.json
```
