### ISSUE TITLE
Documentation for React Native

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2733]
**What would you like to be added**:
1. How we run the code
2. Basic idea of how it works
3. Navigation - Where is the code?
4. Link to the packages used
5. Testing documentation, if exists (if not we need to add, create issue please)
6. Link to the wiki

please get a review from someone who has not worked in this area.

**Why would you like this to be added**:

**Comment by LuigiZaccagnini** [comment]
Just providing some information that can help with the documentation. 

# React Native Documentation 

## Installing React Native Expo
Installing the command line tool so you can run Expo commands.
`npm install --global expo-cli`

## How to run the code?
To start a development server to start testing code you would run `expo start` and in your terminal a QR code will pop up. You will need to install the Expo app on your phone to scan and install the app for development. 

## Navigation - Where is the code?
![](https://miro.medium.com/max/700/1*tO2tbjRwF5tIePjwg-nLBw.png)
With the starting off React Native code, `App.js` is the root file with all the components. Think of it like an `Index.html`. This is where navigation code would go or if it is a single page app, all of the components. `App.json` has the information about our app (Name, splash image, etc.). As we get more into development this part of the documentation will change a lot. 

## Link to the packages used
[Expo](https://expo.dev/)

**Comment by humphd** [comment]
Is it possible to use `expo-cli` without having it installed globally?  Can we install it as a devDependency, and then write npm scripts to call the version in `node_modules/.bin`?

**Comment by tpmai22** [comment]
[#96](https://github.com/expo/expo-cli/issues/96) We can install it to `devDependency`

**Comment by tpmai22** [comment]
#2841
