### ISSUE TITLE
Documentation for Supabase

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2734]
**What would you like to be added**:
1. How we run the code
2. Basic idea of how it works
3. Navigation - Where is the code?
4. Link to the packages used
5. Testing documentation, if exists (if not we need to add, create issue please)
6. Link to the wiki
**Why would you like this to be added**:

**Comment by sirinoks** [comment]
The doc was started in our Wiki so that it is fast to edit and we don't need to wait for PRs for small changes. Please add what you know
https://github.com/Seneca-CDOT/telescope/wiki/Supabase-documentation
