### ISSUE TITLE
Start migrating our monorepo linting to our microservices using turborepo

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2736]
**What would you like to be added**:
We are just focusing on moving our linting

We just need to add the lint script to the package.json 

Goal pnpm lint and should run turborepo

**Why would you like this to be added**:

**Comment by menghif** [comment]
The first part of this Demo was really helpful to understand how Turborepo works: https://youtu.be/YX5yoApjI3M

**Comment by DukeManh** [comment]
The meeting about Turborepo with Francesco can help with this.
