### ISSUE TITLE
Documentation for Turborepo and how it works

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2737]
**What would you like to be added**:

**Why would you like this to be added**:

**Comment by DukeManh** [comment]
Let's have a meeting for @menghif to explain and answer questions about Turborepo and make the docs.

**Comment by sirinoks** [comment]
#2736 can be done for 2.6 (eslint)
For the next steps legacy back end needs to be sorted first
For each micrososervice we have there needs to be a config
A bunch of issues/a checklist needs to be made for each microservice

**Comment by aserputov** [comment]
I changed this issue to 2.7, but decided that maybe we can finish issue #2805 for 2.6.

**Comment by sirinoks** [comment]
O, ok, someone's is working on it
