### ISSUE TITLE
Add Pino logging to our Express web server

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#274]
We've got [logging](docs/logging.md) now, so let's [add it to our Express web server](http://getpino.io/#/docs/web?id=express).

See also #204, which is doing similar work elsewhere in the backend.

**Comment by humphd** [comment]
This should probably also update our `package.json` file so that in development, we [pretty-print our logs](http://getpino.io/#/docs/pretty).  NOTE: [special case on Windows](https://github.com/pinojs/pino-pretty/issues/71).

**Comment by miggs125** [comment]
I'll take this
