### ISSUE TITLE
Create the Docs Microservice

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#2746]
**What is the idea?**
We started loving docs again and will be spawning a great number of new docs:
- #2733 Documentation for React Native
- #2734 Documentation for Supabase
- #2737 Documentation for Turborepo
- #203 Documentation for REST API
and more to come...

We can create a microservice for our docs and containerize the web application where our docs will live. Such an idea has been brewing since 2019 #290 

**How would it look like? (if applicable)**
We kind of started working on this for Telescope 2.0, so we have some sort of MDX implementation (for the About Us page). Let us move the MDX stuff into its own microservice since it's not really related to the main Telescope app. This microservice will live in /src/api/docs so when we visit https://telescope.cdot.systems/docs, we can easily find whatever document we need instead of going to the [/docs](https://github.com/Seneca-CDOT/telescope/tree/master/docs) directory in the Telescope repo

**What existing technologies need to be used? (if applicable)**
I want to try this stack to build this web app.
- Next.js
- MDX
- TailwindCSS

**What areas will have to be worked on? (issue labels of type `area`) Describe which, how, and why.**
- Documentation
- Developer Experience
- User Experience

**What does the idea solve?**
Documentation for our documentation because who is enjoying Telescope's bowl of spaghetti docs?

We can have docs for developers. Docs for users. Docs for Windows, Docs for Mac. Docs for Linux... Docs for everyone. While this may seem like a 'nice-to-have' feature, it should really be 'fun-to-have' because it will be FUN. F-U-N. Fun. Just to further prove how fun this can be, I'm willing to help get this started (once the team has approved this proposal), and whoever wants to jump in can jump in. I'm also okay with munching on this solo if no one else shows interest since I don't see this blocking anything in progress.

**Comment by sirinoks** [comment]
I am interested in this. Since we already used MDX, it shouldn't be too difficult to do it for docs. The faster we do this, the faster I can work on actual docs.
Also happy to see Tailwind, was interested in it for a long time.

**Comment by cindyledev** [comment]
> The faster we do this, the faster I can work on actual docs

While I appreciate the interest, I can also hear @humphd yelling at me in the background, like "dammit, Cindy, why did you coerce my developers with your terrible marketing skills into your docs project? They need to be writing actual docs!". You guys still need to be writing and maintaining docs. Treat this microservice as a mistress or sidedish. It's an absolutely beautiful distraction but don't forget about your immediate responsibilities.

**Comment by cindyledev** [comment]
I guess this was approved. I'm going to transition this forward and lay out what needs to be completed to build an MVP for this microservice.

**Comment by tpmai22** [comment]
@cindyledev I will try to get the doc for `react-native` up by next week
