### ISSUE TITLE
[Satellite] Cannot set property statusCode of Error which has only a getter

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2755]
While I was testing #2753, I ran into a crash in our error handling code:

```
TypeError: Cannot set property statusCode of Error which has only a getter
    at createError (/app/node_modules/http-errors/index.js:101:33)
    at /app/src/routes/query.js:13:10
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
{
  error: ResponseError: index_not_found_exception
      at onBody (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:337:23)
      at IncomingMessage.onEnd (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:264:11)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    meta: {
      body: [Object],
      statusCode: 404,
      headers: [Object],
      meta: [Object]
    }
  }
} query error
/app/node_modules/http-errors/index.js:101
    err.status = err.statusCode = status
```

This is being caused by the following code in the search servce:

```js
// search.js

const search = async (
  textToSearch,
  filter = 'post',
  page = 0,
  perPage = ELASTIC_MAX_RESULTS_PER_PAGE
) => {
  ...
  const {
    body: { hits },
  } = await client.search({
    from: calculateFrom(page, perPage),
    size: perPage,
    _source: ['id'],
    index,
    type,
    body: query,
  });

  return {
    results: hits.total.value,
    values: hits.hits.map(({ _id }) => ({ id: _id, url: `${POSTS_URL}/${_id}` })),
  };
};

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// query.js
router.get('/', validateQuery, async (req, res, next) => {
  try {
    const { text, filter, page, perPage } = req.query;
    res.send(await search(text, filter, page, perPage));
  } catch (error) {
    console.log({ error }, 'query error');
    next(createError(503, error));   // <-- crash is here
  }
});

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// http-errors/index.js

  if (!HttpError || !(err instanceof HttpError) || err.status !== status) {
    // add properties to generic error
    err.expose = status < 500
    err.status = err.statusCode = status
  }
```

So what's happening here is that we do a call to Elasticsearch, and because there is no index built yet (I hadn't started the parser), it fails (Promise rejects).  This takes us to the `catch` block in the router, and we try to `createError()` using `503` and the `err` object.  This calls into this code (not ours): https://github.com/jshttp/http-errors/blob/master/index.js#L42-L105.  It is trying to decorate the error with a status code property, but it fails:

```
TypeError: Cannot set property statusCode of Error which has only a getter
    at createError (/app/node_modules/http-errors/index.js:101:33)
    at /app/src/routes/query.js:13:10
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
{
  error: ResponseError: index_not_found_exception
      at onBody (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:337:23)
      at IncomingMessage.onEnd (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:264:11)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    meta: {
      body: [Object],
      statusCode: 404,
      headers: [Object],
      meta: [Object]
    }
  }
}
```

This causes the server to crash.  This same problem will affect *all* of our microservices.

We should add a test to Satellite [here](https://github.com/Seneca-CDOT/satellite/blob/d5c35e071eb3f858e1e484152d4443af86ddbeb8/test.js#L894) that tries to pass an `Error` object vs. a `string` as the second arg, and figure out whose bug this is: ours, elasticsearch's, or http-errors.

**Comment by rclee91** [comment]
After doing tests for Search, I think its us.
We might need a Try-catch statement around the `client.search()`, like I've mentioned in #2892

**Comment by AmasiaNalbandian** [comment]
While working on my branch for the search bar with the latest changes from master, I ran into the same issue. I fixed the cause on my end, but will need to confirm it again after I hook up everything to work from 8080 with the front end.

**Comment by humphd** [comment]
Would love a fix for this, thanks @AmasiaNalbandian!

**Comment by AmasiaNalbandian** [comment]
After exploring this, I found the reason we keep getting this error. The issue is when we try to call elastic port which is http://127.0.0.1, it doesn't work. The work around for development right now is to change `env.development` file 
https://github.com/Seneca-CDOT/telescope/blob/8a76ffb3529edd022430278851da046430b2ea9f/config/env.development#L246 

to use `ELASTIC_URL=http://localhost`

http://127.0.0.1 is returning a 404 page not found error. 


Unfortunately, this is completely blocking search - however I'm using the workaround to work on both right now.

**Comment by rclee91** [comment]
I've updated the tests.

I'm not sure if I should post this in Satellite or here. But, the ES Error change was in `7.16`, it's written here in the [documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/breaking-changes.html). No direct link, but its right under the first code block

**Comment by humphd** [comment]
I've only seen it happen locally, but I wonder if this is what the feed-discovery service is doing when it crashes.

**Comment by rclee91** [comment]
Wondering if any similar crashes are still happening after the fix in [Satellite](https://github.com/Seneca-CDOT/satellite/pull/64)

**Comment by humphd** [comment]
Not sure.  We can close this for now and re-open if we see it again.
