### ISSUE TITLE
Use better message for build header

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2761]
I just merged a PR and it build on staging.  The build header looked like this:

![image](https://user-images.githubusercontent.com/427398/151462383-253930c1-d292-4d8c-aa75-c209287159ce.png)

I think that message `humphd synchronized .....` isn't idea, especially since we have the commit `message` in the GitHub data:

```json
"head_commit": {
                "id": "e663d8c9a8a8e8fc3d8764e43cc3cad356b4e03b",
                "tree_id": "ba6cac166a6e1fcde688287c6135e573df0a6615",
                "distinct": true,
                "message": "All the Elastic APM code from our docker/compose files, envs, logging, Satellite, docs, etc., is cleaned..",
                "timestamp": "2022-01-27T18:47:07-05:00",
                "url": "https://github.com/Seneca-CDOT/telescope/commit/e663d8c9a8a8e8fc3d8764e43cc3cad356b4e03b",
                "author": {
                    "name": "Anatoliy Serputov",
                    "email": "aserputov@myseneca.ca",
                    "username": "aserputov"
                },
                "committer": {
                    "name": "David Humphrey",
                    "email": "david.andrew.humphrey@gmail.com",
                    "username": "humphd"
                },
                "added": [],
                "removed": [],
                "modified": [
                    "docker/docker-compose.yml",
                    "docker/production.yml",
                    "src/api/readme.md"
                ]
            }
```

Let's use a better string here.

**Comment by tpmai22** [comment]
I will be working on it but can we put it in 2.7 ? and what would be your recommended message to be displayed ?

**Comment by humphd** [comment]
Two things strike me:

1. I'm not the author of the commit, I only merged it.  It would be better show that aserputov wrote the code vs me.
2. `"message": "All the Elastic APM code from our docker/compose files, envs, logging, Satellite, docs, etc., is cleaned.."` seems like a useful string.  We could shorten it with ellipses in CSS so it fits in the space we have.
