### ISSUE TITLE
Launching expo-cli is difficult without instructions

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2767]
**Where is the problem?**

- [ ] Link **comment/file/somewhere else**
- [ ] Screenshot

**What exactly is wrong:**
I tried to run the expo-cli directory and unfortunately its pretty difficult. I already had to install expo-cli globally, and then also installed android studio. I can get the cli to start running, however, I can't get it to open in a virtual device to see it. The CLI instructions are also not clear enough - I tried to follow these to use android on it.

**What should it be instead:**
I think we need some repro steps - for how others were able to do this on both iOS and Android. This would allow others to become more involved in the project too.

**Comment by tpmai22** [comment]
What are you using and can you tell me steps to reproduce that ? I might spot something out and put it in the docs as well

**Comment by AmasiaNalbandian** [comment]
I've uninstalled android studios twice now... How are you guys able to get the emulator running? Mine keeps crashing from adb.exe. I'm going to try and get this to run again tomorrow.....

**Comment by AmasiaNalbandian** [comment]
I cant get it to run with android, i'm going to try a virtual box actually.

**Comment by AmasiaNalbandian** [comment]
I'm sorry for the spam but I got it!!! 
![image](https://user-images.githubusercontent.com/77639637/153898106-ed2e2827-8f5f-40d7-b406-aedb37fe452f.png)

We need to note that the documents are a little wrong, you do IN FACT need to set the environment variable for Windows too. 
My issue was exactly this. I will add it into our docs.
