### ISSUE TITLE
Horizontal overflow when window at various sizes

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2778]
Something is causing horizontal overflow.  When the window is not maximized, but still quite large, something is causing scrollbars to appear, and the content jumps.

https://user-images.githubusercontent.com/427398/151680939-53c8544c-6a5e-43ff-ad0a-2da7df66c209.mov

**Comment by menghif** [comment]
It seems to be caused by the GitHub info sidebar:
https://telescope.cdot.systems/search/?text=Testing%20many%20repos/issues&filter=post

**Comment by humphd** [comment]
cc @sirinoks
