### ISSUE TITLE
Expose Supabase via Traefik, nginx

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2791]
In #2743 we added a bunch of Supabase containers to our docker network.  This includes a few that we need to expose publicly:

- Kong API Gateway (access to all other internal containers) - http://kong:8000
- Web Studio (console) - http://studio:3000

You can start everything with `pnpm services:start` and then browse to http://localhost:8910 and http://localhost:8911, or do something similar on GitPod.  This is not going to work in production.

We discussed the need to be careful with exposing ports in staging and production: we don't want to open any ports beyond 80/443 that we can avoid.  Instead, we need to route all traffic through our various routers and proxies:

- nginx - manages our SSL certs and serves as our main ingress point from outside traffic.  Everything in Telescope goes through nginx.
- Traefik - sits behind nginx and manages access to our services via URL routing at `/v1/*` endpoints.  So the Posts service lives at `/v1/posts`, and search lives at `/v1/search`, etc.

I think the logical approach here is to do the following:

1. Expose the Kong API Gateway via Traefik at `/v1/supabase/*`, which will route to `http://kong:8000` within docker
2. Expose the Web Studio via nginx at `/supabase`.  This is similar to how we run `/portainer` right now.

Here are some examples of how to do each of these:

1. Modify `docker/supabase/docker-compose.yml` to add `labels`, with Traefik routing details, see https://github.com/Seneca-CDOT/telescope/blob/master/docker/docker-compose.yml#L213-L223 for an example, and do it here: and https://github.com/Seneca-CDOT/telescope/blob/master/docker/supabase/docker-compose.yml#L22-L36
2. Modify `config/nginx.conf.template` to do something similar to how we expose `/portainer/` and `/deploy/`.  See https://github.com/Seneca-CDOT/telescope/blob/master/config/nginx.conf.template#L228-L239

Once we do this, we should be able to modify https://github.com/Seneca-CDOT/telescope/blob/master/config/env.staging#L13 to include the Supabase docker-compose file like this: https://github.com/Seneca-CDOT/telescope/blob/master/config/env.development#L13, which would turn it on in staging.

cc'ing our "docker" folks, so one or more of you can pick this up: @TDDR, @aserputov, @Kevan-Y, @DukeManh, @sirinoks, @TueeNguyen, @menghif, @rclee91, @tcvan0707, @tpmai22.  This could be split in two, if two people want to do it.

**Comment by humphd** [comment]
The Supabase front-end needs this to reach its API gateway (it can't hit http://kong:8000):

<img width="1179" alt="Screen Shot 2022-02-02 at 4 04 45 PM" src="https://user-images.githubusercontent.com/427398/152237176-02a3388d-7ce6-413c-a74b-6436e81747f8.png">

**Comment by DukeManh** [comment]
The API page doesn't work anyway, can you access the /users or/tables page?

**Comment by humphd** [comment]
Yeah, they all resolve OK
