### ISSUE TITLE
Create a base Docker image for our microservices

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2803]
In #2796 we're starting to use `pnpm` in our microservice Dockerfiles.  Instead of repeating this same change to a dozen Dockerfiles, let's create a base Telescope Service Docker image that includes everything we need for any of our Microservices.

I've done a bunch of updates to how a Dockerfile should look in https://github.com/Seneca-CDOT/telescope/blob/master/src/api/sso/Dockerfile, which we could simplify and adapt.

CC'ing @raygervais in case he has advice.

**Comment by raygervais** [comment]
I love the idea, will review and advise this week!
Are we worried at all about space complexity? Asking because I know you also want to push to an image repository

**Comment by humphd** [comment]
Space is a concern, yes.

Also, reducing complexity/duplication of what we put in each of the microservice.  I think having an LTS node + global deps + process runner package, labels, and whatever else is common all in this one Dockerfile that lives in `src/api/Dockerfile` or something would be great.

**Comment by Kevan-Y** [comment]
Do we want to create that base image and upload it to the GitHub docker registry?

**Comment by humphd** [comment]
Yes, we will add it to the other images we put up in a registry, see #2801 for discussion.

**Comment by cindyledev** [comment]
Nice info for best practices from Snyk recommendations in #1668 :)

**Comment by humphd** [comment]
While looking at some other code, I noticed how we are using `tini` in the web Dockerfile: https://github.com/Seneca-CDOT/telescope/blob/master/src/web/Dockerfile#L14-L23

This shows a good example of how to run `tini` in a base layer that gets invoked in a subsequent layer, as the docs describe: https://github.com/krallin/tini#using-tini

Our base image can do something like this.
