### ISSUE TITLE
Supabase issues

### ISSUE THREAD

**Issue by sirinoks** [Seneca-CDOT/telescope#2814]
# What issues to make

If you see an issue on a described topic already made, or you have made an issue, tick the checkbox and link the issue by editing this post!

### Notes from the meeting:

- [x] Row level security - database tokens
- [x] #2822 Backups - do one and restore form it 
- [x] Migrate feeds from the wiki
- [x] Feed parser to use supabase table
- [x] Delete user service once we migrate

### [Comment](https://github.com/Seneca-CDOT/telescope/issues/2735#issuecomment-1035103556) 

- [x] We define a JWT secret in our environment, see https://github.com/Seneca-CDOT/telescope/blob/master/config/env.development#L279.  This variable needs to be exposed to our SSO service via Docker (i.e., unless you explicitly tell Docker to allow access to a variable, it won't forward it to the container).  Right now we expose a `SECRET` variable here https://github.com/Seneca-CDOT/telescope/blob/master/docker/docker-compose.yml#L98, and we need to switch this to use `JWT_SECRET`.  Doing so will mean we can share this same secret between all of our backends (microservices, Supabase).
- [x] Now that we have this `JWT_SECRET` in the SSO service, we need to use it to sign the token we create for a client in https://github.com/Seneca-CDOT/telescope/blob/master/src/api/sso/src/token.js#L51.  This will mean that we've signed our token with the same secret that Supabase (i.e., Kong) expects to see when a request comes in.
- [x] We need to update the secret we give each microservice to use when verifying a user request.  We do that in the environment for each service in the `docker/docker-compose.yml` file, for example https://github.com/Seneca-CDOT/telescope/blob/master/docker/docker-compose.yml#L23-L26.  Instead of using `SECRET`, we need to forward `JWT_SECRET` into these microservice's environments.  This change needs to happen for every service.
- [x] Satellite is expecting to see a `SECRET` environment variable, see https://github.com/Seneca-CDOT/satellite#configure.  We need to modify this to `JWT_SECRET`, and update all uses of `SECRET` in the code, see https://github.com/Seneca-CDOT/satellite/search?q=SECRET.  We then need to ship a new release of Satellite with these changes.
- [x] Next we need to update our front-end code to authorize the Supabase `client` with the JWT we get back from the SSO service.  We would do that by calling [`supabase.auth.setAuth()`](https://supabase.com/docs/reference/javascript/auth-setauth) in the front-end when we get back the JWT from the SSO service, maybe here: https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/components/AuthProvider.tsx#L120-L122.  We might decide to return a Supabase `client` object with the `useAuth()` hook, so callers can use it directly without having to figure out this authentication step.
- [x] We need to update the SSO tests that I started to simulate what I just described in 5., see https://github.com/DukeManh/telescope/pull/60/files#diff-1a0d51d80b8a06d29578dde6cd6eb37ce97b5c770d977d60628bb54795c8c603R123.  That is, we need to have a browser use the JWT from the SSO service, call `supabase.auth.setAuth(token)` and then use the authorized client to try doing some call to the Supabase API, and make sure it works.  An example might be: update the user's name in the profiles table.
- [x] We need to add Row Level Security (RLS) to our `telescope_profiles` and `feeds` tables (as well as any others we create).  See https://blog.crunchydata.com/blog/a-postgresql-row-level-security-primer-creating-large-policies or other tutorials on how RLS works. If you run our containers now, you can go to http://localhost:8910 to see the Supabase console.  Click on "Default Project" to see our Telescope project, then on the "Table editor" to see our tables, or "Authentication" to see our security setup.  At http://localhost:8910/project/default/auth/policies you can see our Policies for each table.  Currently, RLS isn't enabled for either table, but we can click Enable RLS to add it, and then click "New Policy" to define a policy.  There are templates we can use to write these.  For us, an example might be: "Users can only modify/delete records in feeds if the `id` in the JWT matches the `id` of the owner of the feed."  We'll need to manually add these policies to our `.sql` so they get created automatically, but the GUI is nice for experimenting.
- [x] We need to add tests to make sure that these policies work.  For example, we could write a test that logs a user in, and tries to edit a feed they don't own, and make sure it fails.  Same thing for one they do own, and it should work.

**Comment by sirinoks** [comment]
What issues to make:
1. Look at the [comment](https://github.com/Seneca-CDOT/telescope/issues/2735#issuecomment-1035103556)
2. Notes from the meeting:

- Row level security - database tokens
- Backups - do one and restore form it
- Migrate feeds from the wiki
- Feed parser to use supabase table
- Delete user service once we migrate

**Comment by sirinoks** [comment]
@joelazwar

**Comment by TueeNguyen** [comment]
Closing since most issues are done, waiting for Parser to be changed #3363
