### ISSUE TITLE
Build log dashboard doesn't always show build log

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2818]
While we were shipping 2.6.0 and 2.6.1,  I wasn't able to get the build log to show.

I notice there's an error in the console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'substring')
    at _ (build.1bd82331.js:1:2923)
    at R (build.1bd82331.js:1:3380)
    at U (build.1bd82331.js:1:3617)
    at p (build.1bd82331.js:1:3703)
```

**Comment by Andrewnt219** [comment]
If we ignore all the stuff in node_modules, and we don't use bootstrap-notify, these lines are very likely the cause. 

https://github.com/Seneca-CDOT/telescope/blob/dbf5d245111954c97e2730e6bfa77fc566573527/src/api/status/public/js/build-log/build-header.js#L27-L30

**Comment by humphd** [comment]
Yeah, that's it.  The change in how we do the `sha` for a build has broken this (we don't send `after` any more).  We should use `build.sha`:

https://github.com/Seneca-CDOT/telescope/blob/dbf5d245111954c97e2730e6bfa77fc566573527/tools/autodeployment/builds.js#L34-L46
