### ISSUE TITLE
Redis container not populating with posts from bull queue

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#2819]
**What happened**:
When running the backend, redis does not appear to be grabbing the new feeds/posts from the bull queue, and as a result, the redis database is empty. 

**What should have happened**:
The backend should populate the redis database with new posts, so that the posts service can obtain them and pass to the frontend. It should also continuously update the redis database as long as the backend is still currently running.

**How to reproduce it (as precise as possible)**:
- Delete the `redis-data` folder
- Run `pnpm services:start` to run the services
- Check the appendonly.aof file. The file should not be empty

**Anything else we need to know?**:

**Environment**:

- OS: Windows 10 Home
- Browser:

**Comment by humphd** [comment]
You have to run `npm start` to get the back-end parser to run and populate the Redis db after you start the services.

**Comment by HyperTHD** [comment]
> You have to run `npm start` to get the back-end parser to run and populate the Redis db after you start the services.

I should've mentioned in the instructions to run the backend afterwards, but unless there's a specific amount of time to wait, there's no change to the redis db

**Comment by humphd** [comment]
Do you have `MOCK_REDIS=1` set somewhere?

Try logging `process.env` when your server starts, to see what it's using.

**Comment by HyperTHD** [comment]
The mock_redis variable is empty as it should. My redis container is also not getting any feeds either so the bull-queue is not sending any feeds it's processed either. Looking at the new info route added shows that it's empty. Perhaps because it's not in use right now
This is very hard to say where exactly, mainly because no one is able to reproduce. Only thing I can think of is that the redis url and port are not being passed in properly, but since I can connect fine, that's off the table.

**Comment by manekenpix** [comment]
@HyperTHD can you share a branch or something so we can take a look?

**Comment by humphd** [comment]
Do you have an `.env` file?  We stopped using them a while back, but if people have them in the root, we still honour it.  I wonder if that's causing something?

**Comment by HyperTHD** [comment]
> @HyperTHD can you share a branch or something so we can take a look?

It's the master branch that this is causing for me, but I'll make a branch and share it.
[This should be fine](https://github.com/HyperTHD/telescope/tree/REDIS_BUG)

> Do you have an `.env` file? We stopped using them a while back, but if people have them in the root, we still honour it. I wonder if that's causing something?

I do still use the `.env` file since the backend parser needs it to start, I was shocked that the microservices still work without it, but no luck still regarding any problems it might have caused

**Comment by manekenpix** [comment]
@HyperTHD everything seems to be ok running your branch.

![Peek 2022-02-06 02-10](https://user-images.githubusercontent.com/23108901/152671077-3609cec6-8ff6-4ffe-ba72-a3d3c695f82e.gif)

These are the steps I took to run telescope, in case you want to try:
- clone your repo
- `git checkout REDIS_BUG`
- `cp config/env.development .env`
- `pnpm i`
- `docker-compose --env-file config/env.development up --build` and wait until the output stops (to make sure all the containers are ready)
- in a different terminal `pnpm start`

and after a while, I could load telescope with all the posts. Have you tried a fresh build of everything removing all the containers and images?

**Comment by HyperTHD** [comment]
I'm very confused by this in general. Running everything the way you mentioned @manekenpix, the bull queue finally sent everything to redis. I'm wondering why running the docker-compose command did what the pnpm script did not. 

Regardless, this was a nightmare that I can say ended. It sounds very trivial, and honestly, it is, but I've literally tried everything, including cloning Telescope again and deleting all the images and building them all fresh. It makes no sense and yet, here it is right now.

**Comment by humphd** [comment]
So frustrating.  There's nothing worse than a ghost-in-the-machine bug that haunts you, and only you, like this for so long.  Glad you finally got past it.
