### ISSUE TITLE
Supabase backup strategy

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2822]
We're adding Supabase, and going to start keeping data in it.  It includes a postgres db and an object store.  We need to figure out how and where to back these up.

I think we can use any [postgres backup tool/technique](https://www.postgresql.org/docs/9.1/backup.html).  I don't have any experience with these, so I can't recommend anything.

According to https://supabase.com/docs/guides/database#fn-backups, the object store is not part of the database, so we might need something for that too.

**Comment by sirinoks** [comment]
What data do we need to keep? 
How do we store it right now? Where in the repo is it located currently?

**Comment by humphd** [comment]
We don't know what we'll keep in there exactly.  Currently we store everything in Redis (User info, Feed info, Post info).  We can likely move Users and Feeds to postgres, but this is beyond the scope of this issue (i.e., we have to solve that first).

Beyond that, Supabase stores its data in postgres, so we need that data too.  The entire db needs to get backed up, whatever we put in it.

**Comment by aserputov** [comment]
@humphd I have a curiosity question: Is Telescope web deployed on Vercel from GitHub repo? What I mean exactly is that I also work on Cloudflare research right now and got this question: are our src/web/public static files not cached anywhere? How do they connect to the frontend code? Just simple by local path in a folder, or do we have storage&public links? 
Also, pictures from the posts, where are they cached, stored?

**Comment by humphd** [comment]
We have Vercel deployments for PRs, but we don't deploy staging or production there.  Instead, we host it from our own nginx container.  The images in people's blogs are not cached by us: the browsers will pull from the original sources, which we don't control.

**Comment by JerryHue** [comment]
> We don't know what we'll keep in there exactly. Currently we store everything in Redis (User info, Feed info, Post info). We can likely move Users and Feeds to postgres, but this is beyond the scope of this issue (i.e., we have to solve that first).
> 
> Beyond that, Supabase stores its data in postgres, so we need that data too. The entire db needs to get backed up, whatever we put in it.

A few important questions:

- Where would we store the backups? The idea is that we have backups made and then stored in a separate geographical location. Should we store the backups on a cloud service like AWS?
- How often should a backup be done?
- How long should we keep a backup?
- In the case the schema of the database changes, how can we apply a backup in such case?

**Comment by humphd** [comment]
One option would be to run our own S3 server like `docker.cdot.systems`, using https://hub.docker.com/r/minio/minio/, and we can post the backups there.
