### ISSUE TITLE
Add Lighthouse CI

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#283]
Similar to #272, it would be interesting to experiment with [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci).  Lighthouse is Google's tool for finding performance and other frontend web issues in a site.

Like with webhint, I'm not sure we need to run this by default with `npm test`; but it could be an optional thing people can run if they are working on the frontend code.

**Comment by vitokhangnguyen** [comment]
I have no experience with CI/CD before os I would like to try this out.

**Comment by dbeigi** [comment]
@humphd @vitokhangnguyen Possible to have two people work on this issue?

**Comment by humphd** [comment]
@vitokhangnguyen since you've got some other PRs going, I'm going to give this to @dbeigi so we spread the load.  Maybe @vitokhangnguyen can be one of the reviewers.

**Comment by vitokhangnguyen** [comment]
@humphd Yep, that will work
