### ISSUE TITLE
Improve size of web Dockerfile

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2835]
In our `src/web/Dockerfile`, we can use a smaller nginx image:

https://github.com/Seneca-CDOT/telescope/blob/master/src/web/Dockerfile#L56

That could be `nginx:stable-alpine`.  I'm not sure if we have other `nginx` layers anywhere that we could update as well.

**Comment by menghif** [comment]
When I try using `nginx:stable-alpine` the container keeps restarting. I can't figured out the reason why.

Log:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
2022/02/08 02:12:31 [emerg] 1#1: getpwnam("www-data") failed in /etc/nginx/nginx.conf:22
nginx: [emerg] getpwnam("www-data") failed in /etc/nginx/nginx.conf:22
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/02/08 02:12:32 [emerg] 1#1: getpwnam("www-data") failed in /etc/nginx/nginx.conf:22
nginx: [emerg] getpwnam("www-data") failed in /etc/nginx/nginx.conf:22
/docker-entrypoint.sh: /docker-
```

@humphd @TDDR Any ideas?

**Comment by humphd** [comment]
http://blog.tobiasforkel.de/en/2016/09/10/nginx-docker-container-and-getpwnamwww-data-problem/ due to https://github.com/Seneca-CDOT/telescope/blob/master/config/nginx.conf.template#L22

**Comment by TDDR** [comment]
> http://blog.tobiasforkel.de/en/2016/09/10/nginx-docker-container-and-getpwnamwww-data-problem/ due to https://github.com/Seneca-CDOT/telescope/blob/master/config/nginx.conf.template#L22

I have spent some time with this now and am unable to add a user like that article suggested: 
![image](https://user-images.githubusercontent.com/59970326/153462771-65e6d756-81cb-4352-af92-2e8d608b2686.png)


I also tried the way they claim to do it in the [official docs](https://docs.docker.com/engine/reference/builder/#user): 
![image](https://user-images.githubusercontent.com/59970326/153463482-12cd4899-62ee-4218-a206-ed16d78be81d.png)

[GeeksforGeeks](https://www.geeksforgeeks.org/docker-user-instruction/) had a suggestion that gave me the same error as the one the official docs did.

I found an answer on [Stackoverflow](https://stackoverflow.com/questions/39855304/how-to-add-user-with-dockerfile) that gave me slightly different results: 
![image](https://user-images.githubusercontent.com/59970326/153464808-4c4c4f38-9ef2-4b1d-a243-dad86669b531.png)

**Comment by TDDR** [comment]
> They define the user here: https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile#L17
> 
> We could just have it use the `nginx` user in our files, so it matches. The point is to not be `root`.

I'm assuming you mean the `www-data` user defined [here](https://github.com/TDDR/telescope/blob/77e5d5045790abbeae31f97c55fe44b03207b398/config/nginx.conf.template#L22). I tried to add the user like in that example you linked, which is also the same as the [example](https://www.nginx.com/blog/deploying-nginx-nginx-plus-docker/) I found on the official site. I also came [across this](https://nginx.org/en/docs/ngx_core_module.html#user) in the documentation and tired setting `USER www-data`, and `USER nginx` as shown.  None of which have worked. 

Do you know where I could find the documentation to show what all the flags and arguments mean in that `adduser` statement you linked? I can't seem to find any mention of it in [these documents](https://nginx.org/en/docs/)
