### ISSUE TITLE
Switch Users service back-end from Firebase to Supabase

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2837]
Our current [Users service](https://github.com/Seneca-CDOT/telescope/tree/master/src/api/users) uses Firebase.  The person who knows it best is @chrispinkney.

It works in conjunction with the sso (formerly auth) service, and provides a user profile, and feed storage, for our Telescope users.  We differentiate a "user" as:

- Seneca user: someone who can login on Seneca's SSO system (e.g., any student/faculty/staff at Seneca)
- Telescope user: a Seneca user who has also created a Telescope profile (i.e., authenticated via Seneca's SSO and create a user profile in the Users service).

When a Telescope user is authenticated, we give them a JWT that is used to authenticate with our various microservices via [middleware in Satellite](https://github.com/Seneca-CDOT/satellite#middleware).

The users service makes use of [Firestore](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/users/src/services/firestore.js) to work with user info. The [routes need to be updated](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/users/src/routes/users.js) to use [Supabase's JS client](https://github.com/supabase/supabase-js), and connect to our Supabase backend.

We also use a [docker container to emulate Firestore](https://github.com/Seneca-CDOT/telescope/blob/master/docker/development.yml#L47-L59).  This needs to get removed, and replaced with another way to do the testing against Supabase.

**Comment by DukeManh** [comment]
Is it a good idea to have a dedicated users service when we could access the user's profiles directly through the Supabase-js client?

**Comment by humphd** [comment]
I think Users can wrap around Superbase-js, and secure access to the key we have to send to Supabase.  My reading into auth with Supabase leads me to believe there's no simple path for us to do sign-up flows from the browser with Supabase.  We have to backdoor our way into the database with admin rights.  And doing so will require us to wrap our calls in server-side requests.

**Comment by DukeManh** [comment]
@humphd, I've played around with it a bit and this is what I think would work.
 - Disable Supabase sign-up because we are not handling user credentials ourselves
 - Make `Telescope_users` table that use SSO user's id as primary key
 - When users login/register, look up the table to see if they have been registered with Telescope
 - Sign users info and send back the JWT to the client

**Comment by humphd** [comment]
@DukeManh this is basically done or in motion, should we close?

**Comment by DukeManh** [comment]
This can be closed.
