### ISSUE TITLE
Refactor the `index.html` to a template file ?

### ISSUE THREAD

**Issue by Reza-Rajabi** [Seneca-CDOT/telescope#284]
I am not sure if we would accept this issue, so I will edit the title and content properly.

Currently, our `index.html` is only an example of how the frontend would look like. Soon, we will need to load the processed data into it. One option would be using a template engine, and nowadays [PugJs](https://pugjs.org/api/getting-started.html) (formerly known as Jade) looks to be the most popular one.
The benefit of this refactoring, other than making our MVP, is that it will show us which roots and which support functions we need to implement. It also gives us an idea of our data structure.

**Comment by humphd** [comment]
We can also do this client side, and do the "templating" in the DOM vs on the server side.  This is a more modern approach, and is the basis for many virtual DOM implementations, like React, Vue, Angular, etc.

We don't need a full blown framework yet; but we could use basic DOM manipulation to first `fetch()` data from our API (#262) and then display it in the page (#261).

If someone *also* wants to experiment with server-side templating, that's fine too.  But eventually this should all happen client side.

**Comment by Reza-Rajabi** [comment]
@humphd I will close this issue if that's OK. Working with virtual DOM on the client-side makes more sense. I thought we couldn't have done that without using React or Vue.

**Comment by humphd** [comment]
Sure, let's close.  If someone really wants to do a server-side templated version, we can let both happen in parallel, and eventually remove one.  But I'm all for experimentation and learning, so whatever people want to try...
