### ISSUE TITLE
Allow users to include Twitch channels in sign up

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2843]
We added RSS-Bridge to our system, and it lets you create feeds for various services that don't support it.  For example, Twitch channels.

You can access our instance at https://dev.api.telescope.cdot.systems/v1/rss-bridge/

If a user signs up for Telescope and has a Twitch channel, we should let them put in their Twitch channel info, then construct a URL to use our RSS-Bridge instance so we can add it as a feed.

I don't use Twitch so I don't have a good example here.  Maybe @sirinoks can point us at a channel we can use as an example.

cc @dbelokon, @sirinoks

**Comment by AmasiaNalbandian** [comment]
We just need an input field to store the twitch channel and then use the rss bridge. This Issue is just to wire up the front end so that we can begin to use the Twitch implementation

**Comment by tcvan0707** [comment]
Assigned to @menghif. @dbelokon and @JerryHue will help on the side

**Comment by JerryHue** [comment]
Let's not forget that we will want to file a test case in the `feed-discovery` service for a Twitch channel.

**Comment by humphd** [comment]
#3488 is doing a bunch of work on this front.
