### ISSUE TITLE
Tim's blog not showing up in Telescope

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2850]
@TDDR is [writing some great stuff](https://dps909tddr.tech.blog/container-registry-101/), but none of it shows up in Telescope.  There's something wrong with how the feed is being generated: https://dps909tddr.tech.blog/feed/ is empty, which is why Telescope has no data.

I want to see this fixed so that we get this info in front of the community.  Maybe there's a fix to be done on the WordPress side, or maybe the posts need to be tagged somehow?  Or maybe the blog needs to get moved to dev.to or something else that we know works. 

https://telescope.cdot.systems/search/?text=Tim%20Roberts&filter=author should be returning something.

**Comment by humphd** [comment]
We have this in our feed list, btw:

```
[https://dps909tddr.tech.blog/category/opensource/feed/]
name=Tim Roberts
```

**Comment by JerryHue** [comment]
Could we generate Tim's feed with `rss-feed`? They already seem to have a bridge for it.

**Comment by humphd** [comment]
Does doing so change anything?  Worth a try.  If it works, that's an easy fix.

**Comment by TDDR** [comment]
Fixed issue by creating a new blog on dev.to and ditching WordPress
