### ISSUE TITLE
Renovate: Reached branch limit - skipping branch creation 

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2852]
**What happened**:

Renovate doesn't make any dependency PRs for Telescope this week, despite having the same configuration as Satellite.

**Anything else we need to know?**:

Looking at the [logs](https://app.renovatebot.com/dashboard#github/Seneca-CDOT/telescope/572147471), it looks like Renovate is hitting the branch creation limit and has to skip PR creation.

**Comment by humphd** [comment]
Should we delete this?  I think you're right.

**Comment by TueeNguyen** [comment]
To confirm: deleting the extra branch created by renovate works

**Comment by humphd** [comment]
I wonder if we should document this somewhere.  I bet we'll have this happen again, and forget how to fix.

cc @sirinoks

**Comment by humphd** [comment]
https://github.com/Seneca-CDOT/telescope/blob/master/docs/renovate.md for example.

**Comment by TueeNguyen** [comment]
I'll do it, there's a broken link in renovate doc as well
