### ISSUE TITLE
Latest commit remains undefined in local development

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#2854]
On the dev build of Telescope, the commit link still shows undefined, which is strange considering that we fixed this awhile ago. The reasoning for this lies [here](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/health.js#L7).

When building Telescope locally, the frontend uses the legacy backend's url as the API_URL. It looks for a health check route that exists. This route tried to obtains the sha variable via an env value that doesn't exist anymore. This is not an issue on staging or production since the sha is obtained differently than how it is here. 

Since I'm pretty sure we don't plan on adding dev checks to the status service, this line will need to be fixed up.

**Comment by humphd** [comment]
We could change that default to `master`, which would forward you to the latest commit on `master`:

https://github.com/Seneca-CDOT/telescope/commit/master
