### ISSUE TITLE
React native - Display posts

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-CDOT/telescope#2857]
**What would you like to be added**:
Able to fetch and render posts.

- Able to fetch post from telescope API 
- Create a post based on the current telescope design

Note: 
Create a follow-up issue, for the GitHub summary.

**Comment by TueeNguyen** [comment]
Testing, Notion webhook

**Comment by Kevan-Y** [comment]
The post API returns the post in HTML. We cannot render directly HTML in React native.
I'm wondering if we should use some third library for that. Or use some other solution.
Some are the library I found.
- https://www.npmjs.com/package/react-native-webview
- https://www.npmjs.com/package/react-native-render-html

**Comment by tpmai22** [comment]
[Kevan set up](https://github.com/Kevan-Y/telescope/tree/issues/issue-2857) for whoever interested
