### ISSUE TITLE
React Native - About Page

### ISSUE THREAD

**Issue by joelazwar** [Seneca-CDOT/telescope#2859]
**What would you like to be added**:
Create Home Page for the Telescope app based on the web app design

**Comment by tpmai22** [comment]
@Kevan-Y I guess we need to prior the bottom navigation bar first before this issue ?

**Comment by nguyenhung15913** [comment]
I can work on this if you are busy

**Comment by tpmai22** [comment]
@nguyenhung15913 thank you for that I just got stuck a bit because I did not know we will display the whole string or we gonna create a json file to parse it into our component

**Comment by tpmai22** [comment]
@nguyenhung15913 we can work together you can share your set up here if you already have one
