### ISSUE TITLE
Fail CircleCI build if any test skipped/waiting due to async

### ISSUE THREAD

**Issue by sukhbeersingh** [Seneca-CDOT/telescope#286]
This is a bug that I noticed in commit ff4643a28 for pull request #252. This fails for Travis but not for [CircleCI](https://circleci.com/gh/Seneca-CDOT/telescope/348?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). We need to configure CircleCI to fail the build if all the tests didn't pass successfully.

**Comment by Sbaah** [comment]
Hello i would like to attempt this issue.

**Comment by humphd** [comment]
@sukhbeersingh I'm just chatting with @Sbaah in the lab, and we're not sure what can really be done with this issue.  Did you have something specific you wanted here?  As far as we can tell, Circle CI already does what we want.

**Comment by humphd** [comment]
I'm going to close this.  If we come up with a solution, please file again.
