### ISSUE TITLE
Adding Twitch feeds in registration

### ISSUE THREAD

**Issue by sirinoks** [Seneca-CDOT/telescope#2866]
Referenced [here](https://github.com/Seneca-CDOT/telescope/pull/2844#discussion_r801218823).

- Research if accounts need to be linked, what needs to be done on Youtube/Twitch end. 
- Add fields for Youtube and Twitch feed links.
- Make sure Telescope "reads" those new feeds.

*If I understood the comment wrong, please edit and correct this issue, + remove this message when you're done*

**Comment by JerryHue** [comment]
Is this the back-end for #2676?

**Comment by AmasiaNalbandian** [comment]
This is the duplicate of another issue - https://github.com/Seneca-CDOT/telescope/issues/2843
