### ISSUE TITLE
Remove MDX-related stuff from our Next.js Telescope frontend

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#2868]
Now that we have a Docusaurus website to hold our docs #2853, we should remove or migrate what we can from Next.js to Docusaurus. Specifically

- [src/web/src/pages/about.mdx](https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/pages/about.mdx)
- [src/web/src/markdown-pages/about.md](https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/markdown-pages/about.md)

Changes needed for [src/web/package.json](https://github.com/Seneca-CDOT/telescope/blob/master/src/web/package.json#L7):
- https://github.com/Seneca-CDOT/telescope/blob/34b37902569c221041c5c02a5364c5f5721e46a7/src/web/package.json#L7
- https://github.com/Seneca-CDOT/telescope/blob/34b37902569c221041c5c02a5364c5f5721e46a7/src/web/package.json#L30-L32

Changes needed for [src/web/next.config.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/web/next.config.js):
- https://github.com/Seneca-CDOT/telescope/blob/34b37902569c221041c5c02a5364c5f5721e46a7/src/web/next.config.js#L12-L14
- https://github.com/Seneca-CDOT/telescope/blob/34b37902569c221041c5c02a5364c5f5721e46a7/src/web/next.config.js#L66-L67
- https://github.com/Seneca-CDOT/telescope/blob/34b37902569c221041c5c02a5364c5f5721e46a7/src/web/next.config.js#L75-L76

I might have missed something so please check previous PRs and git blame to see where/when the mdx stuff was added

**Comment by menghif** [comment]
After today's meeting we decided to translate the About page in multiple languages https://github.com/Seneca-CDOT/telescope/issues/2962. We also decided to keep the About page on the Telescope app and to remove MDX.

This issue can be converted into removing MDX.

**Comment by cindyledev** [comment]
I will also assign myself this issue since this needs some delicate surgery done and I think I know it well enough... maybe _fingerscrossed_
