### ISSUE TITLE
Setting up mock SAML2 server

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#287]
https://github.com/Sustainsys/Saml2

I believe this is something we can utilize. That we might be able to add the right parts to our code so we can start setting up simple login.

However, if you have better recommendation perhaps we can incorporate that instead! This is open for discussion!

**Comment by humphd** [comment]
Let's not use C# and ASP.NET.  What about the ideas in https://medium.com/disney-streaming/setup-a-single-sign-on-saml-test-environment-with-docker-and-nodejs-c53fc1a984c9?

**Comment by humphd** [comment]
cc @wajeehsheikh, @Reza-Rajabi, @manekenpix who have been pretty active on our Docker work so far.  The article I linked above uses a SAML identify provider already implemented as a PHP app running in Docker.

@Grommers00 so for our work, we'd need to add this docker container in our dev/testing environment so we can mock Seneca's SSO server.  These guys can probably lend you a hand figuring out the Docker bits to make this happen.  It would be very similar to what we do now for Redis on Docker.

**Comment by humphd** [comment]
Link drop:

- Grafana does this in their config https://github.com/grafana/grafana/blob/e83953f24ec18f5ed47c1d326bff829693bfdea8/devenv/docker/blocks/saml/docker-compose.yaml
- Express app that uses this docker container https://github.com/Tandem-App-Tuni/Kivako-app-backend/blob/fd26699a6599213b7e455e238188e2cd30731d9c/src/configs/app.js
- and more results searching for that container on github in other projects https://github.com/search?q=%22kristophjunge%2Ftest-saml-idp%22&type=Code

**Comment by manekenpix** [comment]
@Grommers00 @humphd @Reza-Rajabi @wajeehsheikh Just tested our `docker-compose` adding SAML following the medium article:

![Screenshot from 2019-11-19 23-05-03](https://user-images.githubusercontent.com/23108901/69208268-ed850c00-0b20-11ea-81bc-88911f7301e4.png)

**Comment by Grommers00** [comment]
I will be looking at seeing how the configuration is set-up to move this forward, so from my understnading this is installed? @manekenpix

**Comment by manekenpix** [comment]
@Grommers00 right now @Reza-Rajabi is working on it so I think we'll get a PR from him soon that'll include this.

**Comment by Reza-Rajabi** [comment]
@Grommers00 I got back to the article that @humphd [mentioned](https://medium.com/disney-streaming/setup-a-single-sign-on-saml-test-environment-with-docker-and-nodejs-c53fc1a984c9) before with more attention, and it could answer the ambiguities for me. I thought you might also find it useful.

**Comment by Reza-Rajabi** [comment]
> @Grommers00 right now @Reza-Rajabi is working on it so I think we'll get a PR from him soon that'll include this.

@manekenpix Your changes for the docker-compose file in the image you shared, was quite useful and I almost had nothing to change more than that. Thank you.

**Comment by Grommers00** [comment]
Hey @Reza-Rajabi,
Would you be able to push the current set-up you have for Docker and the saml2 to our github?

**Comment by Reza-Rajabi** [comment]
@Grommers00 Hi. Sorry for the delay. Sure, I will do it when I reach home tonight. Currently, I can not get the localhost and I am not sure if that can help you in any way. My aim is to make the localhost accessible until tomorrow night. Currently, I am communicating with a student from the computer networking program about this issue.

**Comment by Grommers00** [comment]
Okay awesome, we can talk about it during class Thursday. Once it's up, I will try seeing about switching those URLs too.

**Comment by Reza-Rajabi** [comment]
@Grommers00 it's there 👆

**Comment by Grommers00** [comment]
I'm going to consider this close based on @Reza-Rajabi pull request. And a seperate issue I'm going to create for the configuration of it.
