### ISSUE TITLE
Define dev vs. staging/production settings for Supabase containers

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2876]
We're starting to add the Supabase containers to our Docker network.  Currently, we layer the [docker/supabase/docker-compose.yml](https://github.com/Seneca-CDOT/telescope/blob/master/docker/supabase/docker-compose.yml) file with our existing files via this line https://github.com/Seneca-CDOT/telescope/blob/master/config/env.development#L18 in development (we do something similar in staging and production, for example https://github.com/Seneca-CDOT/telescope/blob/master/config/env.production#L18).

The Supabase containers are all set to `restart: unless-stopped`.  This means that whenever I start Docker Desktop, these containers all restart, whether I'm doing Telescope work or not.  I don't want them to always run, so in development, we should not add `restart: unless-stopped` to each of these.  We should only add this when we do production/staging.

So we need to remove all the `restart: unless-stopped` lines from `docker/supabase/docker-compose.yml`, and create a new file `docker/supabase/production.yml` that lets us override aspects of `docker/supabase/docker-compose.yml`, similar to what we do in https://github.com/Seneca-CDOT/telescope/blob/master/docker/production.yml#L98-L100.

We can also use this separation of dev vs. production to open various ports on the Supabase containers (development) but close them in production.  I'll file another issue on that.

**Comment by AmasiaNalbandian** [comment]
Closing because supabase Postgre database needs restart:unless-stopped to shutdown and start again due to how supabase deals with race condition. This is important for our sso's e2e test.
