### ISSUE TITLE
Show "last updated" information for docs in Docusaurus

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#2885]
Many documentation websites have additional information about who last updated a file and when the file was last modified. We should do that for our docs as well

![2022-02-11 14_18_28-Installation _ Docusaurus - Brave](https://user-images.githubusercontent.com/36822198/153655784-a74d2536-857c-4a55-8a7e-6503d8ec9230.png)

**Comment by sirinoks** [comment]
Is this something we can automate?

**Comment by cindyledev** [comment]
We can use the [plugin-content-docs](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#showLastUpdateAuthor) to showLastUpdateAuthor and showLastUpdateTime
