### ISSUE TITLE
Server crashes if LOG_LEVEL is upper case

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#289]
```
$ LOG_LEVEL=INFO npm start
/Users/humphd/repos/telescope/node_modules/pino/lib/levels.js:153
    throw Error(`default level:${defaultLevel} must be included in custom levels`)
    ^

Error: default level:INFO must be included in custom levels
    at assertDefaultLevelFound (/Users/humphd/repos/telescope/node_modules/pino/lib/levels.js:153:11)
    at pino (/Users/humphd/repos/telescope/node_modules/pino/pino.js:96:3)
    at Object.<anonymous> (/Users/humphd/repos/telescope/src/lib/logger.js:24:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Comment by ragnarokatz** [comment]
@humphd Unfortunately, I am unable to reproduce this issue on Ubuntu 18.04. Anyone else able to reproduce this?

**Comment by humphd** [comment]
Interesting.  @ragnarokatz, what command did you run exactly?

The crash originates here: https://github.com/pinojs/pino/blob/master/lib/levels.js#L157.

We need to deal with the case of bad log levels when starting the logger.  In [src/lib/logger.js](src/lib/logger.js) we should be careful about how we pass the level from the `env` to Pino.  It needs to be one of the expected levels, see http://getpino.io/#/docs/api?id=options.

It's possible to get these labels before we do our initial config of the logger:

```
const pino = require('pino');
pino.levels.values
{ trace: 10, debug: 20, info: 30, warn: 40, error: 50, fatal: 60 }
```

So probably we should be careful to check that the `LOG_LEVEL` we're passed is a) converted to lowercase; b) one of the expected levels (i.e., a key in `pino.levels.values`); c) log a warning if we get an unexpected log level; d) convert to use something like `info` if it's not know.

**Comment by humphd** [comment]
See http://getpino.io/#/docs/api?id=levels

**Comment by ragnarokatz** [comment]
@humphd I pulled a fresh copy of telescope on to my laptop since it doesn't have it yet. here are the commands i ran in order:
`npm install`
`docker-compose up -d redis`
`LOG_LEVEL=INFO npm start`

**Comment by humphd** [comment]
The code I linked to above doesn't seem to have OS related checks.  Interesting that you don't hit it.

Regardless, let's fix how we do this based on my suggestion above.  Because this can throw, we should be dealing with it.

**Comment by miggs125** [comment]
I was able to reproduce this. ``` LOG_LEVEL=info ``` seems to work

**Comment by ragnarokatz** [comment]
@humphd magically, I am able to reproduce this now. No idea why :laughing:
