### ISSUE TITLE
Add Test for '409: Feeds exists' in SSO Service 

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2909]
**What would you like to be added**:

Our SSO service is missing a case when users register using a feed that has been registered and a feed URL must be unique. 

It's important to add this case to make sure we don't run into regression in the future.

The 409 error is returned here
https://github.com/Seneca-CDOT/telescope/pull/2901/files/b287b7f0ccab577ca3340dad0d39aca6584d6c7c#diff-6c0acb684bf6dc50333f3aae0c5e578ed885ede749bd0b13505ce721b7fbe18b

**Comment by JerryHue** [comment]
Closed via #3335.
