### ISSUE TITLE
Explore supporting different languages for our docs

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#2922]
Docusaurus has a tutorial on the basics of the [Docusaurus i18n system](https://docusaurus.io/docs/i18n/tutorial). I don't know any languages well enough to translate but if we had someone on the team willing to try this out, I help get this rolling. This would pave the way for Hacktoberfest contributors since it seems to be pretty popular to translate docs for that event. We can try a single doc first.

**Comment by humphd** [comment]
I wonder when the right time to do this is?  I suspect that localizing fast-moving docs is going to be hard.  Probably a goal of 3.0 should be to have the docs stay relatively stable for the 3.x lifecycle.  In the 4.x lifecycle, we could revamp them.

That means, we should plan out what needs to get written between now and 3.0, and file those issues.

**Comment by cindyledev** [comment]
I imagine this would be a post-3.0 thing since we're still waiting on a number of docs to be added:

- #203 Document REST API
- #2734 Documentation for Supabase
- #2920 Windows installation for React Native
- #2855 and #2880 Telescope Architecture Diagram

and I'm sure there will be new docs that need to be written before 3.0

We also need to dogfood and audit the docs before they're ready to be translated

**Comment by sirinoks** [comment]
I'm down to translate to Russian

**Comment by humphd** [comment]
One thing I'm going to push people on re: translation, is that they have to build a team.  Just like I wouldn't let a student drop a PR in some programming language none of us knows, there's no way I'm going to take a translation that I have to maintain without it also arriving as part of a team.

Years ago, a bunch of my Ukrainian students got together and translated the Rect docs as a team, see https://uk.reactjs.org/.  It was inspiring to watch.  We can do the same for Telescope, but we need to build some teams of people to do the work, and people to review, and ideally, people who want to help maintain it later.

**Comment by sirinoks** [comment]
There's a tool I saw used for Staxel translations, where it automatically makes tables with original and translation columns and it's really nice to use for non developers. I'm not sure what it was though..

**Comment by TueeNguyen** [comment]
Should this be closed? We haven't implemented the full feature

**Comment by aserputov** [comment]
@TueeNguyen I think this one closed automatically because I merged PR.

**Comment by tpmai22** [comment]
We got this keeping track in #2962
