### ISSUE TITLE
Add a code snippet copy button

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2923]
**What would you like to be added**:

We are a programming blog platform and a lot of code is written every week. It would be nice to have a `Copy` button on the top right of every code block to encourage people to include their code snippets or terminal logs so others can copy to try it out or help with debugging.

**Comment by humphd** [comment]
Love this!  @Andrewnt219 did something similar for our [build log output](https://dev.api.telescope.cdot.systems/v1/status/build), and @tuanthanh2067 did something like this for being able to copy the links for a blog URL.
