### ISSUE TITLE
Improve landing page performance

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#2925]
We have an Image service that gives the Telescope landing page a random picture on page load. This is nice but not yet optimal. 
On slow internet connections, these high-quality banner images take a couple of seconds to load and reduce the overall performance.

Moving forward, we should improve the Image service and the front page to: 
 - Return [responsive image ](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images), with various sizes that fit well on different devices
 - Return a low-quality, blurred-out image for initial page load and replace it with a high definition one when it finishes loading

**Why would you like this to be added**:

**Comment by humphd** [comment]
We do a responsive image already.  I stole the same logic that next.js uses server side, see https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/components/DynamicImage.tsx#L52.  We can add more sizes easily, if you think we don't have enough.

The second one could be done by the image service too (return a super tiny version we expand and blur with CSS, then replace when full image is loaded).  We could automate https://css-tricks.com/the-blur-up-technique-for-loading-background-images/.
