### ISSUE TITLE
Create an Expo dev account 

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-CDOT/telescope#2933]
In https://github.com/Seneca-CDOT/telescope/issues/2732, to publish our mobile to Expo, we need to create Expo dev account in order to publish it. 
[Signup](https://expo.dev/signup)

**Comment by Kevan-Y** [comment]
Sorry to reply late, reading from the documentation, we can create a secret token key that we gonna be using it for Github action.
[link for secret token](https://docs.expo.dev/accounts/programmatic-access/#programmatic-access).
[Expo workflow](https://github.com/expo/expo-github-action#example-workflows) if I understand correctly we need to place that in secret key in or repo setting. So when running the Github actions it will pickup that key.

**Comment by humphd** [comment]
This is working now with my account, closing.
