### ISSUE TITLE
pnpm won't update satellite to latest version

### ISSUE THREAD

**Issue by joelazwar** [Seneca-CDOT/telescope#2934]
**What happened**:
`pnpm install` doesn't fetch the satellite upstream, and we have to manually update it by deleting the node_modules folder or running pnpm update on each microservice. (but this changes the package.json files)

**What should have happened**:
`pnpm install` should automatically fetch the latest version of satellite for all dependencies
**How to reproduce it (as precise as possible)**:
Run pnpm install and check the satellite version. ([Latest release](https://github.com/Seneca-CDOT/satellite/releases))
**Anything else we need to know?**:

Related Discussion #2892 

**Environment**:

- OS:
- Browser:

**Comment by humphd** [comment]
Can someone test what happens if we use the `"latest"` version in `package.json`?

**Comment by humphd** [comment]
cc @rclee91 @JiaHua-Zou

**Comment by rclee91** [comment]
I tried it out in just the search `package.json`. Changing to `"latest"` and then running `pnpm install` will update the `pnpm-lock.yaml`

![image](https://user-images.githubusercontent.com/32626950/154078029-35eb2827-30cd-4b11-9e23-7c9d55708b8f.png)

![image](https://user-images.githubusercontent.com/32626950/154078276-0a89d270-0772-4138-98f6-95f3610112c5.png)

**Comment by humphd** [comment]
This is great news. The only thing it means is that our release process should use `pnpm install` to get the package-lock file updated with the most recent version of Satellite.  We could automate that when we call `pnpm version`.

**Comment by rclee91** [comment]
I have a few questions regarding this issue. 
Besides changing all of the Satellite `"^1.x"` to `"latest"` in all the relevant `package.json`, are we trying to get it so our release workflow will run `pnpm install`, which will update the `pnpm-lock.yaml`, commit and merge the updates, and then also get published with our releases?

I've been trying to read the pnpm documentation, and I think, but I'm not sure, if we'll need to use [changesets](https://pnpm.io/using-changesets) for this. 

Also, what would our solution be if Satellite updated in between our releases? Do we do a mini release to get the updated version?

**Comment by humphd** [comment]
I think the answer here is to have whoever bumps the version of Satellite to also update the lock file after it ships.  That is, it's your responsibility to also update the rest of the tree.  What do you think?

**Comment by rclee91** [comment]
Yeah, I think this makes more sense, makes it simpler as well. 

I'll create a PR to bump the Satellite versions for now. So our Search tests can move forward
