### ISSUE TITLE
nginx.conf issuew with /planet

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2936]
When I look at the logs of the nginx container, I see it complaining about our `/planet` definition:

```
2022/02/15 14:45:19 [emerg] 1#1: host not found in upstream "planet" in /etc/nginx/nginx.conf:144
nginx: [emerg] host not found in upstream "planet" in /etc/nginx/nginx.conf:144
```

Which I assume is this:

```
 # Cache content served by /planet forever
    location /planet {
      proxy_cache_bypass 1;
      proxy_set_header Connection "";
      proxy_pass http://planet:9876;
    }
```

This might be a dependency load order issue, where nginx needs these upstream servers to exist, and if those containers aren't started yet, it complains.

**Comment by Kevan-Y** [comment]
How do I reproduce that? I tried on my local I don't see this in the nginx logs

**Comment by humphd** [comment]
I think this is a hiccup related to load ordering.  I'm going to close, since I can't see the logs in staging.
