### ISSUE TITLE
Exclude `img` tags from linkifyHtml

### ISSUE THREAD

**Issue by 416rehman** [Seneca-CDOT/telescope#2941]
**What would you like to be added**:
The `img` tag needs to be excluded when we call `linkifyHtml` in https://github.com/Seneca-CDOT/telescope/blob/f80b0b9f673b51cded172c91719e4c0b564d31fe/src/backend/data/post.js#L158
**Why would you like this to be added**:
Right now all the `img` tags inside a post content are wrapped by `a` tags, this results in the images acting like an `a` tag (open as URL on click) and also interferes with the new image zoom feature, more specifically this issue pointed out by @TueeNguyen https://github.com/Seneca-CDOT/telescope/pull/2932#pullrequestreview-883265391

**Comment by TueeNguyen** [comment]
Great, let's finish this #2932 and then we can move on to this.

**Comment by humphd** [comment]
It would be useful to compare the list against what we allow through the sanitizer, https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/html/sanitize.js#L10-L42, and see if we can skip others in the list that might be affected by this later.

The only thing we want to do with the linkifier is to turn text node URLs into anchors.

We need to add some tests so we catch this happening with images, etc. as well.  They go in https://github.com/Seneca-CDOT/telescope/blob/master/test/sanitize-html.test.js.

**Comment by menghif** [comment]
@416rehman Would you like to take this on?

**Comment by aserputov** [comment]
@416rehman any updates ?

**Comment by 416rehman** [comment]
> 

Haven't had the time to look into this, been busy with school. Feel free to assign it if someone is interested.

**Comment by humphd** [comment]
Looks like we can `ignoreTags`: https://linkify.js.org/docs/options.html#ignoretags
