### ISSUE TITLE
Add extra padding for content inside the build log terminal 

### ISSUE THREAD

**Issue by tpmai22** [Seneca-CDOT/telescope#2952]
**What would you like to be added**:
I would love to add a pit of left padding for the cotent inside the build log terminal
**Why would you like this to be added**:
It make the content get displayed more accessible

**Comment by tcvan0707** [comment]
Is this how you want to be added for the build log content?

<img width="1846" alt="image" src="https://user-images.githubusercontent.com/69607880/154347330-f5a3e1ca-debc-4e89-85d7-d9d0be5f59bb.png">

**Comment by tpmai22** [comment]
yes seem good to me ! @Andrewnt219 how do you feel ?

**Comment by Andrewnt219** [comment]
That's odd. Where has the padding gone? The terminal used to have padding #2534.

**Comment by tcvan0707** [comment]
> That's odd. Where has the padding gone? The terminal used to have padding #2534.

I have no idea where the padding has gone. `padding: 0.5rem` seems to be disappeared

**Comment by DukeManh** [comment]
closed via #3140
