### ISSUE TITLE
How Auth works doc

### ISSUE THREAD

**Issue by sirinoks** [Seneca-CDOT/telescope#2955]
After today's meeting turned out Auth is complicated and keeps getting explained every time again and again. There needs to be a single place to look for that information - the doc.

I have started a scrap one in Wiki - https://github.com/Seneca-CDOT/telescope/wiki/How-Auth-works
To save time and not wait for PRs on small fixes, we instead can work on it in the Wiki, until we have a cohesive result.

#### Here are some sources where you can gather information on it:
![Screen Shot 2021-02-19 at 7 11 49 PM](https://user-images.githubusercontent.com/427398/108574827-5c35b400-72e6-11eb-8a47-b3d3ce781c16.png)

[Blog post](https://blog.humphd.org/not-so-simple-saml)

If you are familiar with our Auth process, please add what you know to the page!

**Comment by humphd** [comment]
NOTE: #3030 is extending this.

**Comment by humphd** [comment]
Discussed on Teams in https://seneca.sharepoint.com/sites/Telescope/Shared%20Documents/General/Recordings/JWT%20Secret%20in%20Telescope-20220406_135311-Meeting%20Recording.mp4?web=1
