### ISSUE TITLE
Automatically update Satellite dependency versions

### ISSUE THREAD

**Issue by rclee91** [Seneca-CDOT/telescope#2959]
**What would you like to be added**:
Find a way to automatically update Satellite dependency versions

**Why would you like this to be added**:
Following the conversations through #2934 , we have to manually get the Satellite updates.
Let's see if we have a way to automate this before Satellite is moved into Telescope in #2677

**Comment by humphd** [comment]
Talking with @joelazwar on Slack today, one thing that does work is:

```
pnpm update -r --latest @senecacdot/satellite
```

This will rewrite all the `package.json` files throughout the monorepo, and also update the lock file.

**Comment by joelazwar** [comment]
been googling for a workaround, i guess this is our best option so far. We could document this step in the Satellite Shipping guide docs TBD

**Comment by rclee91** [comment]
No, I don't know this command at all, I wish I did. 
Since we're manually doing it anyways, might as well do it how it manually works for us.

**Comment by rclee91** [comment]
I'm guessing from this line that we get sometimes after running `pnpm install`
```
Lockfile is up-to-date, resolution step is skipped
```
The lockfile will only update with `pnpm install` if something is changed in the various `package.json`

**Comment by humphd** [comment]
Correct, which is why `pnpm update ...` makes it happen, since it updates the `package.json` files.
