### ISSUE TITLE
Update outdated npm packages

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#296]
We have a few packages that could be updated (`npm outdated` will show you):

```
$ npm outdated
Package                 Current  Wanted  Latest  Location
bull                     3.11.0  3.11.0  3.12.1  telescope
eslint-config-prettier    6.5.0   6.5.0   6.7.0  telescope
nodemon                  1.19.4  1.19.4   2.0.0  telescope
pino-pretty               3.3.0   3.3.0   3.4.0  telescope
stylelint                11.1.1  11.1.1  12.0.0  telescope
```

NOTE: the `pino-pretty` update is happening in #278, so ignore that one.  But the rest might be good to do.  The only two that need a bit of investigation, to make sure they don't break us with API changes, are `nodemon` and `stylelint`.  Go look at these repos and their releases/changelog to see what changed in the new version, and if we have to do anything to switch to it.

NOTE2: If you haven't updated to `master` recently, note that we removed `package-lock.json` and switched to exact versions in `package.json` in #295.  We don't use `^` or `~` semver prefixes on package versions anymore.

**Comment by shmooey** [comment]
I'll try this one
