### ISSUE TITLE
Use Mermaid for Docusaurus docs

### ISSUE THREAD

**Issue by JerryHue** [Seneca-CDOT/telescope#2960]
**What would you like to be added**: The [mermaid plugin](https://github.com/sjwall/mdx-mermaid) for Docusaurus.

**Why would you like this to be added**: The plugin can let us write diagrams in text form that are then used to generate images. This is super powerful, since we don't need to maintain separate assets. Everything is centralized in the mdx files.

**Comment by DukeManh** [comment]
close via #3150
