### ISSUE TITLE
Add language switch functionality in the front-end

### ISSUE THREAD

**Issue by TueeNguyen** [Seneca-CDOT/telescope#2963]
**What would you like to be added**:

A way to switch to different languages in the front-end

**Why would you like this to be added**:

#2962 probably needs this feature to move forward, at least for the about page for now

**Comment by menghif** [comment]
We can use this: https://www.npmjs.com/package/next-i18next

**Comment by rclee91** [comment]
I stumbled on a project back in the Hacktoberfest days. It was a repo called Directus and they had it set up like [this](https://github.com/directus/directus/tree/main/app/src/lang) using `vue-i18n `. Maybe the setup might be similar with [next-i18next](https://www.npmjs.com/package/next-i18next)

**Comment by AmasiaNalbandian** [comment]
updates: I integrated next-i18next but I'm stuck on an error I keep receiving - hoping to figure out the error soon otherwise I am posting it up as a draft PR tonight for help.
