### ISSUE TITLE
Separate eslint overrides into each sub-project

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2965]
We have a fancy new shared eslint config, and it includes a bunch of [overrides for specific sub-projects](https://github.com/Seneca-CDOT/telescope/blob/master/tools/eslint/index.js#L26-L54).  Let's split these out into each of the sub-projects instead, similar to how the `src/web/*` eslint stuff works.

**Comment by tpmai22** [comment]
This have moving to meta issue #3135
