### ISSUE TITLE
[X-Post][Satellite] Document JWT_SECRET with more information (README.md)

### ISSUE THREAD

**Issue by joelazwar** [Seneca-CDOT/telescope#2966]
**Where is the problem?**

- [ ] Link **comment/file/somewhere else**
- [ ] Screenshot

**What exactly is wrong:**
We need to document more info about our recently updated JWT_SECRET and how it integrates with Supabase on telescope/satellite

**What should it be instead:**

**Comment by humphd** [comment]
Discussed on Teams in https://seneca.sharepoint.com/sites/Telescope/Shared%20Documents/General/Recordings/JWT%20Secret%20in%20Telescope-20220406_135311-Meeting%20Recording.mp4?web=1
