### ISSUE TITLE
dialogue.js not working properly

### ISSUE THREAD

**Issue by ODAVING** [Seneca-CDOT/telescope#298]
Somehow in one of the front-end iterations, the code that made dialogue.js functional has been deleted. I could put it back again, but I'm already busy with another issue. Could someone please edit the html in a way that gets the dialogue.js working again. 

Once it's fixed, I'll create another issue for styling, to ensure it's compatible with mobile devices.

**Comment by humphd** [comment]
See also #221, #271, which this might dupe.

**Comment by ODAVING** [comment]
Yep! I'll close it then

**Comment by jatinAroraGit** [comment]
Hey @ODAVING, 
I just did a PR for #221 , I fixed the errors thrown initially on loading website but it will still error out when we click the 'Participants' button and the reason for that is the index.html does not have any id with 'dialogue'.

**Comment by ODAVING** [comment]
> Hey @ODAVING,
> I just did a PR for #221 , I fixed the errors thrown initially on loading website but it will still error out when we click the 'Participants' button and the reason for that is the index.html does not have any id with 'dialogue'.

I made a comment on #221 , Please take a look at a we'll discuss it there. This issue is closed and we'll talk on #221
