### ISSUE TITLE
Home Page for Docusaurus needs to be updated

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#2987]
Our current Docusuarus home page looks like this:

![Screenshot 2022-02-18 at 14-34-55 Hello from Telescope Telescope](https://user-images.githubusercontent.com/36822198/154750635-61adbf6e-0e8c-49d2-b634-a15ec9ac3dd0.png)

Could probably use fewer dinosaurs and more telescopes? Suggestions are open.

cc @sirinoks because she has mentioned interest in this on Slack and https://github.com/Seneca-CDOT/telescope/issues/2924#issuecomment-1039885003

**Comment by sirinoks** [comment]
Looking into https://greensock.com/ - a tool to make CSS animation

**Comment by TueeNguyen** [comment]
Perhaps we can make a telescope rotating in the center and blog posts moving around as stars.

**Comment by cindyledev** [comment]
Do a good job on the Docusaurus home page and we'll ask you to redo the Telescope home page too XD
