### ISSUE TITLE
Replace JWT_TOKEN with JWT_SECRET in deploy script

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#2989]
The [deploy.sh](https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/deploy.sh) script used by our autodeployment server is injecting a new jwt secret and storing it in an env var named `JWT_TOKEN.

This env var should be renamed `JWT_SECRET`, [here](https://github.com/Seneca-CDOT/telescope/blob/53eee4b9cafc35568b55ed7d2f7b9f149ef05fda/tools/autodeployment/deploy.sh#L44).

**Comment by humphd** [comment]
cc @joelazwar
