### ISSUE TITLE
Share single nginx container for all static sites

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2993]
Follow-up to https://github.com/Seneca-CDOT/telescope/pull/2973#discussion_r810409547, let's run a single nginx container, and have all of our static web content get served by this one instance.

1. `src/web` is our next.js website
2. `src/docs` is our Docusaurus website
3. `test/test-web-content` is a static testing site we only need in development, see https://github.com/Seneca-CDOT/telescope/blob/aca9f75e2c1359bfa02dfd38f4eb6947f1a05644/docker/development.yml#L47-L56

I think this is everything, but let me know if I'm missing anything.

What would be ideal is if we restructured things like this:

```
src/web/Dockerfile
src/web/app
src/web/docs
src/web/test-content
```

The `Dockerfile` in `src/web` would build/copy all the static sites so that the nginx instance can serve them.  We'd have to update our `root` for each server definition to look in the right directory, see https://github.com/Seneca-CDOT/telescope/blob/aca9f75e2c1359bfa02dfd38f4eb6947f1a05644/config/nginx.conf.template#L230.

**Comment by cindyledev** [comment]
Can we also rename the `src/web/docs` to `src/web/docusaurus` to avoid file paths from looking like `src/web/docs/docs/*`?

`docs/docs` is waiting for typos to happen.
