### ISSUE TITLE
Configure ESLint for Backend sub-project

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#3000]
Related to #2965 

After #2862, a number of ESLint errors showed up in the `src/backend` files. Eg

```
Parsing error: The keyword 'const' is reserved
```

Please see ESLint override configs
https://github.com/Seneca-CDOT/telescope/blob/372976bd563e58d79ad177c00eb645a060a07ca0/tools/eslint/index.js#L26-L33

These ESLint errors have our developers switching from VS Code to other Code Editors :(

**Comment by humphd** [comment]
See #2994

**Comment by humphd** [comment]
Also, #3000! Time to focus on #2982

**Comment by cindyledev** [comment]
Resolved by #3199
