### ISSUE TITLE
Telescope not loading proper healthcheck

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3022]
<img width="477" alt="Screen Shot 2022-02-21 at 7 56 48 PM" src="https://user-images.githubusercontent.com/427398/155044164-a5ebebd2-79cf-433e-97be-ba842bbaeafa.png">

cc @HyperTHD

**Comment by HyperTHD** [comment]
Yup, follow up to my recent PR that updated the health-check
Gonna fix this one up too
For reference, [view here](https://github.com/Seneca-CDOT/telescope/pull/2856#discussion_r802128307)

**Comment by HyperTHD** [comment]
@humphd I'm not getting that error, actually it appears to be working fine on my end.
![image](https://user-images.githubusercontent.com/16841702/155389004-e60314bf-a2d3-44dc-bad6-d22120e66982.png)

**Comment by humphd** [comment]
Interesting.  OK, same for me.  Not sure what I saw.  I'll re-file it I see it again.  Thanks for checking.
