### ISSUE TITLE
Investigate using AWS for ephemeral dev environments

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3024]
Somewhat connect to #3017, I'd like to see if we can figure out how to do a turn-key AWS-dev solution using https://code.visualstudio.com/docs/remote/ssh.  I know @cindyledev has done something pretty similar and documented it.

My idea is to figure out how best to leverage the AWS accounts I can create for students.  My requirements and limitations are as follows:

- students get a sandboxed AWS account with $100 credits for the duration of the "course" (the timeframe is arbitrary, so let's assume a term)
- the sandboxed accounts don't have a credit card attached, and resources are enabled/disabled when the student starts/stops the environment.  By default, it uses a 6 hour window of time, but you can extend this as many times as possible
- the AWS credentials for the student account change every time you start/stop the environment.
- a student can create EC2 instance types of nano, micro, small, medium, and large only.  I think the biggest instance we can start is a 2 vCPU, 16 GiB RAM r5.large instance
- a student can start multiple instances at once, as long as you don't exceed 32 vCPUs
- a student can use up to 100GB Elastic Block Storage with General Purpose SSD (gp2, gp3), cold HDD (sc1), or standard
- we can only use Amazon Linux or Windows AMIs
- we can only use on-demand instances

I think we could work with this to do something interesting for our devs.  Imagine if Seneca student Telescope developers had an AWS account like I mention above.  I'd like to to be able to have them start the AWS environment, then type a couple of commands to have all of our containers running in an EC2 instance, and VSCode connected over SSH to that instances filesystem.  They could do their development, review, testing, etc. and then terminate the instance.  When they need another one, we repeat.

It's a bit like GitPod, but we can control it more.

**Comment by humphd** [comment]
https://github.com/Seneca-CDOT/telescope/blob/master/src/docs/docs/getting-started/aws-cloud9.md has a ton of info already.

**Comment by cindyledev** [comment]
Trying this out in a Cloud9 environment. Seems like if we're using only allowed `.large` instances, we only have t3, c5, t2, m4, and c4 available. Unfortunately means only a maximum of 8 GB of RAM

![2022-02-22 17_57_03-Window](https://user-images.githubusercontent.com/36822198/155233629-0301498b-a2d8-4f1e-bfb7-8e85fb81f58d.png)

Will continue to investigate

**Comment by c3ho** [comment]
There’s also digital ocean (droplets) for students, I’m not too sure on the specifics. However it’s an alternative to look at, they have the cheapest VMs out of all the cloud providers for the same specs

**Comment by cindyledev** [comment]
I can use VSCode to SSH into a r5.large instance (16GB RAM!) as mentioned above. I still gotta make some configurations because it doesn't have a lot of things installed like docker-compose, node, git. This is getting even more exciting.

**Comment by humphd** [comment]
> There’s also digital ocean (droplets) for students, I’m not too sure on the specifics. However it’s an alternative to look at, they have the cheapest VMs out of all the cloud providers for the same specs

DigitalOcean is out for me personally.  Even though I love and use them, for Telescope I want to leverage the AWS classes I can create.

**Comment by humphd** [comment]
> I can use VSCode to SSH into a r5.large instance (16GB RAM!) as mentioned above. I still gotta make some configurations because it doesn't have a lot of things installed like docker-compose, node, git. This is getting even more exciting.

This is what I wanted to hear!  Ideally we make some kind of script or use infrastructure automation to take the base Linux AMI and add that stuff and leave the environment ready for action.

**Comment by cindyledev** [comment]
I'm happy to report that I got Telescope working on an EC2 instance made by an AWS Learner Lab account! The [docs](https://github.com/Seneca-CDOT/telescope/blob/master/src/docs/docs/getting-started/vscode-ssh.md) need work. PR to come.

Our frontend and backend feeds
![2022-02-23 22_03_45-Window](https://user-images.githubusercontent.com/36822198/155450097-0103787e-4fc1-4ea8-8803-38b47469e1a0.png)

Microservice also work, just showing the Status board because it's cool
![2022-02-23 22_04_10-Window](https://user-images.githubusercontent.com/36822198/155450123-0e567758-1dfc-42cb-87c6-7969ab4fa81c.png)

**Comment by humphd** [comment]
This is very exciting, thanks for sharing!  I really interested in to hear all the gory details when you have time.

**Comment by humphd** [comment]
I wonder if we can use https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html to automatically set up the instance when it boots, via a shell script or cloud-init.

**Comment by tpmai22** [comment]
Closed this due to #3061
