### ISSUE TITLE
Remove the skips from feed-parser-test.js

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#303]
Since we have mock network tests ready, we should remove any of the tests with skip in them.

**Comment by jerryshueh** [comment]
To clarify, we're removing the tests that are using "test" urls, correct? If so, I can certainly do this little maintenance task.

**Comment by c3ho** [comment]
Hey @jerryshueh, there's already a PR for this #304. Feel free to add on more tests though!
