### ISSUE TITLE
Use oauth2-proxy with GitHub Auth Provider to secure Admin apps

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3030]
We've pretty much solved authentication for users.  Next, I want to solve authentication for our "admin" apps.  These are areas of the system that only our dev team should be able to access (e.g., Supabase console).

One solution is for us to add [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) and configure it with the [GitHub Auth Provider](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#github-auth-provider), which can be set up to further limit to use a GitHub org, team, repo, etc.

We can connect [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) to either nginx or traefik.

**Comment by humphd** [comment]
I *think* that once we do this, we can configure Portainer to use it too (this needs more research, see https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints):

<img width="978" alt="Screen Shot 2022-02-23 at 5 23 15 PM" src="https://user-images.githubusercontent.com/427398/155419476-c908e2fc-ff83-44e2-9c13-87fa72b1320f.png">

**Comment by humphd** [comment]
See https://github.com/Seneca-CDOT/telescope/issues/2801#issuecomment-1049947905 which outlines some of what has to happen.  NOTE: we don't need to do SSL or the like here.

In the case of Telescope, we need to:

- add the [oauth2-proxy container](https://hub.docker.com/r/bitnami/oauth2-proxy/) to our services in the `docker/production.yml` file
- proxy connections to `portainer.telescope.cdot.systems` or `supabase.telescope.cdot.systems` in our production nginx config to oauth2-proxy.  See the latter part of https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/tls/
- configure the [GitHub Provider](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#github-auth-provider) to use the Telescope Maintainers team (same thing @TDDR is doing for the docker registry, so you can collaborate).
- configure Portainer to use our oauth2 proxy's endpoints: https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints

Each of you can take some part of this and file new issues to get it landed.  Let me know who is doing what, and what help you need.

**Comment by Kevan-Y** [comment]
Spend a few days doing research and testing this. 
I was able to enable it in my local and protect some routes for demo purposes. 
For example access to treafik we need to call localhost:8085 which is our oauth2_proxy, then on successful login it will redirect to treafik. 

https://user-images.githubusercontent.com/58233223/155909028-86c64dd2-8d36-4761-96f1-f93e5cd5e2cc.mp4

But I have some questions, do we use oauth2 proxy's endpoints for sign out? I never used portainer, not sure how that works. I looked at @humphd discussion with the picture of some sort of UI, but not sure where that is from.

One thing we need to set up is [GitHub Authorizing OAuth Apps](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps). One thing I read is that it doesn't support subdomain, so we might need 2 OAuth Apps, so we will have 2 secret and client-key.

**Comment by humphd** [comment]
@Kevan-Y fantastic!

Can you say more about your concerns with signout?

Portainer is like the Traefik dashboard you used: just a web app we want to restrict access to.  If you can make this work with Traefik's dashboard, we can do it with anything.

"it doesn't support subdomain" can you say more? So we'd have to do it per sub-domain?  That's not a huge problem.

**Comment by Kevan-Y** [comment]
I never used portainer before, I'm not sure if there is a signout button or it's a login without signout.
If there is I'm not sure how we could handle that to overwrite it button. (Maybe that case we shouldn't worry too much about it).

Sorry, I think I wrongly described my thought in the previous message. 
Let me reformulate here.
As I was reading the docs for [GitHub Authorizing OAuth Apps](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps), I found this.
![image](https://user-images.githubusercontent.com/58233223/155910829-f65c3d3e-2f5d-4281-be1d-8ac20a8c6aba.png)
Where in our case with have `https://dev.portainer.telescope.cdot.systems` and `https://portainer.telescope.cdot.systems`. We will need to create 2 OAuth apps per sub-domain. Because GitHub OAuth app can only have one exact URL per OAuth app .

**Comment by Kevan-Y** [comment]
> I _think_ that once we do this, we can configure Portainer to use it too (this needs more research, see https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints):
> 
> <img alt="Screen Shot 2022-02-23 at 5 23 15 PM" width="978" src="https://user-images.githubusercontent.com/427398/155419476-c908e2fc-ff83-44e2-9c13-87fa72b1320f.png">

I think if we put oauth proxy behind portainer. We don't need to set up this configuration in portainer.
I looked at portainer custom oauth, we can setup to login with GitHub, but I think at the end we still have to manually add the user and set the admin/non-admin for them.

A solution for this issue would be (Will have a PR this week for portainer):
Go to our oauth proxy -> login -> redirect to portainer
Note: 
- Portainer won't expose any port, oauth proxy will handle that.
- Need disable auth in portainer so we don't have to login twice.
![Blank diagram](https://user-images.githubusercontent.com/58233223/156103310-560af07e-d516-47f6-bc8a-ba0474dd24e7.png)

Later on in follow up issue:
I done more deep research to support like multiple upstream, it seems that oauth proxy doesn't very have a way itself.
We might later on use nginx to do some redirection, when we gonna have `dev.supabase.telescope.cdot.systems` and `dev.portainer.telescope.cdot.systems`. 
[Instruction nginx with subdomain with oauth proxy](https://github.com/18F/hub/blob/master/deploy/SSO.md) (nginx stuff is confusing 😅)

**Comment by humphd** [comment]
There's no way to disable auth in Portainer, so I'd like to have the oauth method work if possible.

**Comment by humphd** [comment]
I think turning off automatic user provisioning, and having to create a user, whose name matches the GitHub username, isn't a terrible way to handle this. cc @cindyledev

**Comment by Kevan-Y** [comment]
If we go this way oauth2-proxy will be used here but would be useful for cases like supabase.
I noticed I don't have permission to create OAuth app in this organization.
We need to create Oauth app to enable GitHub oauth in Portainer .

**Comment by Kevan-Y** [comment]
> > If we go this way oauth2-proxy will be used here but would be useful for cases like supabase.
> 
> Do you mean "won't be used here"?

yes sorry, typo

**Comment by humphd** [comment]
What's the process to create a GitHub app?

**Comment by Kevan-Y** [comment]
authorization callback URL is  https://dev.portainer.telescope.cdot.systems/

**Comment by humphd** [comment]
<img width="655" alt="Screen Shot 2022-03-02 at 11 23 45 AM" src="https://user-images.githubusercontent.com/427398/156403626-ded1cb15-3a78-4954-9e8c-518b3ee51c34.png">

Staging and Production are both using GitHub OAuth now!  Thank you @Kevan-Y.  If you need an account created, @cindyledev can hook you up.
