### ISSUE TITLE
Sharing student quotes service between web application and mobile application

### ISSUE THREAD

**Issue by nguyenhung15913** [Seneca-CDOT/telescope#3081]
**What would you like to be added**:
According to this [conversation](https://github.com/Seneca-CDOT/telescope/pull/3020#discussion_r812272777), we should move the <code>[src/mobile/src/student-quotes.js](https://github.com/Seneca-CDOT/telescope/pull/3020/files/84859c7d0ada2613e24acd43c5f3cd31e5a8b087#diff-c45fba8b9d568aeb5153a0b3897cd67c8db6653c30142904e0cc7a78240d5ed2)</code> to different location where it can be shared by both web app and mobile app

**Why would you like this to be added**:
Avoid duplicating the file.

**Comment by Kevan-Y** [comment]
I have a suggestion, would it be too much if we build small microservices for that, and use supabase for storing those data?

**Comment by humphd** [comment]
We don't even need a service, just put them in Supabase.  Done!

**Comment by humphd** [comment]
It looks like you're going above the root of the sub-project, which won't work.

We could make this a module that exports a file imported in both projects, and use pnpm workspaces to get at it?

cc @Meneguini

**Comment by AmasiaNalbandian** [comment]
@tpmai22 Can you document more about your findings for this issue?

**Comment by tpmai22** [comment]
Here is my [inistial set up](https://github.com/tpmai22/telescope/tree/issue-3081). This is the original [supabase doc](https://supabase.com/docs/guides/with-expo). In my set up you should look at changes in `src/mobile/src/api/supabase_client.js` and `src/mobile/src/components/Banner/BannerText.jsx`. So when I build all of the `services` I receive this [error](https://github.com/supabase/supabase/discussions/6018) 

I also follow a well written article might solve the problems : https://medium.com/@kelvinpompey.me/things-to-look-out-for-using-supabase-with-react-native-9638b23e98c2
cc: @humphd @Kevan-Y @nguyenhung15913

**Comment by tpmai22** [comment]
@humphd @DukeManh @Kevan-Y I doubt that it might related to our self host `supabase`. Specific is the `docker` set up

**Comment by DukeManh** [comment]
@tpmai22, I see you have some work going on already, could you make a draft PR for what you have?

**Comment by tpmai22** [comment]
@humphd This is the error. The link above is a discussion from upstream 

![image](https://user-images.githubusercontent.com/43376325/160051294-704ffbe6-5b61-4b9f-a2b0-2b3dc2171adb.png)
