### ISSUE TITLE
Adding Image service to the home page of mobile app

### ISSUE THREAD

**Issue by nguyenhung15913** [Seneca-CDOT/telescope#3082]
**What would you like to be added**:
Image service needs to be added to the front-end of mobile app after we merge #3020 . 
To be more specific, [Banner](https://github.com/Seneca-CDOT/telescope/pull/3020/files#diff-944ac70444e74b1b3209cdd6deec86c5ff70bcece397929f906baf6786423d07) component has only the background color. An image service from Telescope API needs to be added so that it will match the current UI of Telescope.

**Comment by tpmai22** [comment]
@nguyenhung15913 the `Banner` component link is broken. Would you mind updating it in the issue description

**Comment by nguyenhung15913** [comment]
@tpmai22 done

**Comment by manekenpix** [comment]
Closing since the mobile version of telescope was removed in #3805
