### ISSUE TITLE
Fix contributors documentation links

### ISSUE THREAD

**Issue by pbelokon** [Seneca-CDOT/telescope#3091]
**Where is the problem?**

- [x] Link **comment/file/somewhere else**
- [x] Screenshot

**What exactly is wrong:**
On the contributors documentation page of github,  Architecture and Develop on Gitpod links do not work. 
https://github.com/Seneca-CDOT/telescope/blob/master/src/docs/docs/contributing/CONTRIBUTING.md

![issue](https://user-images.githubusercontent.com/88114764/156435473-6ac62398-d1af-4610-ae8e-c69991e1237d.jpg)
![ark](https://user-images.githubusercontent.com/88114764/156435788-20dea887-1261-4270-9934-2809bacbf8ad.png)
![gitpod](https://user-images.githubusercontent.com/88114764/156435800-ccf5e5a9-6df8-4bab-95e9-896251e9efd0.png)

**What should it be instead:**
Working pages.

**Comment by JerryHue** [comment]
Do you want to fix this one, @pbelokon?

**Comment by pbelokon** [comment]
Do I have a permission to edit this page  ?

**Comment by JerryHue** [comment]
> Do I have a permission to edit this page ?

Technically, you can change the whole repo, since you have a copy of it :smiley:

 As long as you submit a PR that addresses these changes, it should be fine.

The broken links should point to the docs found [here](https://github.com/Seneca-CDOT/telescope/tree/master/src/docs/docs).
