### ISSUE TITLE
Add support for EditorConfig

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#31]
It would be nice to make editor settings predefined in the repo like VSCode does with [EditorConfig](https://editorconfig.org/).  You can see their setup at https://github.com/microsoft/vscode/blob/master/.editorconfig.

For us, I'd suggest:

- 2 or 4 space indent
- Unix LF end of line
etc

**Comment by ragnarokatz** [comment]
@humphd I would like to take on this issue please.

**Comment by ragnarokatz** [comment]
reference PR #36
