### ISSUE TITLE
Reduce frequency of Renovatebot

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3120]
I'm getting overwhelmed by the frequency of emails/PRs from Renovatebot.  Can we reduce or control it a bit better?  It's to the point where I'm going to set a rule to delete all these emails, which makes me think it's probably not effective.

I don't think we need to jump every time a package goes from 1.2.3 to 1.2.4.

**Comment by cindyledev** [comment]
Sorry, that was me triggering Renovatebot throughout this week. I forgot you get emails. I'll stop triggering them. Terribly sorry!

**Comment by humphd** [comment]
Ah, I didn't realize it was happening due to manual intervention.  That's fine if you're doing it and monitoring (i.e., I *can* ignore them).

Maybe let people in Slack know (esp. Sheriffs) so whiny people like me don't complain.

**Comment by cindyledev** [comment]
<s>cindybot is a menace</s> I'll find something more useful to do XD
