### ISSUE TITLE
Improve test coverage for email-sender.js

### ISSUE THREAD

**Issue by neilong31** [Seneca-CDOT/telescope#313]
Currently the test for email-sender covers 14% of the statements. The current status of the test can be seen at #268

**Comment by RyanWils** [comment]
Hi Neil,

If you want to test nodemailer with an SMTP server you can use the following, this is the one I've been testing it with. 
![image](https://user-images.githubusercontent.com/49354833/69652659-02413280-1040-11ea-88a8-48859d0ac743.png)
```
let transporter = nodemailer.createTransport({
        host: 'smtp.googlemail.com', // Gmail Host
        port: 465, // Port
        secure: true, // this is true as port is 465
        auth: {
            user: 'GMAIL_USERNAME', //Gmail username
            pass: 'GMAIL_PASSWORD' // Gmail password
        }
    });
```
