### ISSUE TITLE
Add React Native to our pnpm workspace

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#3130]
We are currently installing our React Native dependencies using `npm`. 

https://github.com/Seneca-CDOT/telescope/blob/40f6f78e8f25ced6139ac572ae7757693d7a4128/package.json#L39

We should add `src/mobile` to our [pnpm-workspace.yaml](https://github.com/Seneca-CDOT/telescope/blob/master/pnpm-workspace.yaml)

**Comment by humphd** [comment]
I think this was done due to limitations with expo.  @menghif might know more.

**Comment by menghif** [comment]
When I setup expo, there were issues with `pnpm` so I had to resort to `npm`.

It seems like there were successful attempts to make expo work with `pnpm`: 
https://github.com/vjpr/pnpm-react-native-expo-example

If anyone is interested they could look into this further.

**Comment by cindyledev** [comment]
This is hard for me to test if any of the following works because I always hit the same error I've hit in https://github.com/Seneca-CDOT/telescope/pull/3020#issuecomment-1058724926 at the very end

I removed this line
https://github.com/Seneca-CDOT/telescope/blob/6e59d166dc3d4a921b2a0bd91b1c87a46ecad166/package.json#L39

Added this to `pnpm-workspace.yaml`
```
  # React Native app
  - 'src/mobile' 
```

According to `expo update`, we need to download the following packages
```
    "expo-status-bar": "~1.2.0",
    "expo-updates": "~0.11.6",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-screens": "~3.10.1",
    "react-native-web": "0.17.1"

    "@babel/core": "^7.12.9",
```

Note: if we use pnpm to manage the dependencies in React Native repo, we should not use `expo upgrade/update` because it will remove `node_modules` and `package-lock.json` then rebuild both. pnpm does not use package-lock.json

Create a new file `src/mobile/.npmrc` with the following
```
hoist-pattern[]=*babel*
shamefully-hoist=true
node-linker=hoisted
symlink=false
```

**Comment by cindyledev** [comment]
There doesn't seem to be an elegant way of adding our React Native app into pnpm workspace. We shouldn't force this because I think the benefits of being able to run `expo upgrade` properly outweighs the benefit of being able to get rid of the `postinstall` step. We haven't had the need for our React Native to share anything within our workspace yet. 

We can revisit this in the future when the time arises.
