### ISSUE TITLE
Specific E2E test constantly time out during CI deployment

### ISSUE THREAD

**Issue by tpmai22** [Seneca-CDOT/telescope#3139]
**What happened**:
This specific E2E test usually time out when it should not
![image](https://user-images.githubusercontent.com/43376325/157237558-09daed36-9eb6-40d3-be1d-25f8dbee0883.png)

**Comment by DukeManh** [comment]
Related to #3031

**Comment by tpmai22** [comment]
Closed due to duplicate. Thank @DukeManh
