### ISSUE TITLE
Add Server Sent Events to web server to signal new posts

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#314]
We need a way to signal to the browser that new posts are available to be downloaded.  When our feedQueue completes processing all the posts, we need to listen for an event, and then trigger a message to the browser.

Let's try using [Server Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events).

In another PR, we also need to update our frontend index.html to connect to this route, and listen for these updates.

**Comment by cindyledev** [comment]
Reopening because there are two parts for this issue

**Comment by c3ho** [comment]
Permission to work on part2 of this?
