### ISSUE TITLE
Add and expose logic that close all db connections (Redis & Elastic) from Satellite

### ISSUE THREAD

**Issue by TueeNguyen** [Seneca-CDOT/telescope#3148]
**What would you like to be added**:

I want to add a static function, let's say `close()` that closes all db connections (Redis, Elastic) in `Satellite` class. 

The reason is I don't want to create an instance of `Satellite`, I just want to close all db connections leveraging existing code, it would look like this 
```js 
static closeClients() {
  return Promise.all([redis.shutDown(), elastic.shutDown()]);
}
```

https://github.com/Seneca-CDOT/telescope/blob/18a86cec8ef1e0e20e6692d3fc36a1be10333c6b/src/satellite/src/satellite.js#L16

**Why would you like this to be added**:
I'm trying to add e2e test to parser service, Jest would hang because of open handles, db connections that aren't close before Jest tries to exit. Refer to #3040

**Comment by TueeNguyen** [comment]
@humphd @Kevan-Y What do you guys think?

**Comment by humphd** [comment]
I would modify https://github.com/Seneca-CDOT/telescope/blob/18a86cec8ef1e0e20e6692d3fc36a1be10333c6b/src/satellite/src/satellite.js#L68-L85 to do what you want, and have `onSignal` call this same function, https://github.com/Seneca-CDOT/telescope/blob/18a86cec8ef1e0e20e6692d3fc36a1be10333c6b/src/satellite/src/satellite.js#L54-L60.

You can modify that code to return a Promise if you want.
