### ISSUE TITLE
Fix all current ESLint configs

### ISSUE THREAD

**Issue by menghif** [Seneca-CDOT/telescope#3152]
**What happened**:

The current `pnpm lint` implementation does not run ESLint.

**What should have happened**:

`eslint` and `@senecacdot/eslint-config-telescope` need to be installed as devDependecies in each project.

We also need `eslint` in `scripts`:
```
"eslint": "eslint --config .eslintrc.js /* files to lint */"
"eslint-fix": "eslint --config .eslintrc.js /* files to lint */ --fix",
```

In addition, we need to set 
https://github.com/Seneca-CDOT/telescope/blob/5ede9fa8ea22d60bd6daecebf8e2fcb84381148f/tools/eslint/index.js#L123

to `off` instead of `error` as it's causing throwing `Definition for rule '@typescript-eslint/no-shadow' was not found` errors when creating `.eslintrc.js` files in our sub-projects

**Comment by aserputov** [comment]
Do we also need to fix for src/backend, mobile, jest ?

**Comment by menghif** [comment]
> @menghif do we also need to fix for src/backend, mobile, jest, test folder ? Should we merge this one #3135, or how we will do all of that ?

Yes all of them.

You can make the necessary changes for backend in https://github.com/Seneca-CDOT/telescope/pull/3135 since it's not merged yet.
