### ISSUE TITLE
[Metabug] Configure ESLint on all projects

### ISSUE THREAD

**Issue by JerryHue** [Seneca-CDOT/telescope#3153]
This issue's purpose is to track all other issues that focus on adding ESLint configuration on each specific project. They are not cleanly separated, so read the issue's title and thread properly.

- [X] #2560 
- [x] #3000
- [x] #3152 
- [x] #3144 
- [X] #3002
- [X] #2999
- [X] #2998 
- [X] #2970 
- [x] #3154
- [x] #3155 
- [x] #3156 
- [x] #3157 
- [x] #3158 
- [x] #3159
- [x] #3160 
- [x] #3161
- [x] #3198

Add as many as necessary.

May be related:
- #2965

**Comment by cindyledev** [comment]
Let this be our metabug for all the ESLint configuration bugs

**Comment by cindyledev** [comment]
All projects have now been configured with ESLint
