### ISSUE TITLE
To connect main page with login page

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#316]
We have an issue with our main page not connected to the login page. 

Would someone be able to connect these two. This is still for testing purposes, and not the final look for the login page, ideally we will eventually be able to point this towards the Seneca Login Page.

**Comment by agarcia-caicedo** [comment]
Can I work on the issue?

**Comment by Grommers00** [comment]
Yes, thank you!

**Comment by agarcia-caicedo** [comment]
00fd39b46110c682f48a7395385e4ee4f401e033
