### ISSUE TITLE
Configure docker to allow for mock SAML2 Server.

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#317]
Docker allows for SAML2 mock server. We need this set-up and configured, this relates too #287 .

**Comment by manekenpix** [comment]
Part of the work is already done in #287 (see [this](https://github.com/Seneca-CDOT/telescope/issues/287#issuecomment-555828061)), and from that I think it won't need much tweaking. We can work together on this one.

**Comment by Reza-Rajabi** [comment]
@Grommers00 @manekenpix As you know, we need to update the Docker file to do that for us. I am trying to finish the final version of docker files this weekend both for development and deployment. The solution for this mock server is already tested by @manekenpix on #287, so I can include that in our development docker file with my pull request, or I can ignore this, letting you guys update the coming docker file for this purpose.

**Comment by manekenpix** [comment]
@Reza-Rajabi I'm sorry, I just remembered that you mention this in another issue and I completely forgot. Please keep working on the docker files and feel free to include my suggestion from #287 (it might need a bit of tweaking) or maybe you can come up with a better approach. Let me know when your PR is ready and I'll be happy to review it.

**Comment by Reza-Rajabi** [comment]
@manekenpix No worries sir. My pleasure.

**Comment by Grommers00** [comment]
Sounds good @manekenpix @Reza-Rajabi Are you guys fine with me closing this issue and just keeping #287 ?

**Comment by Reza-Rajabi** [comment]
@Grommers00 Sure. Go for it.
