### ISSUE TITLE
Satellite test suites run 10 times

### ISSUE THREAD

**Issue by rclee91** [Seneca-CDOT/telescope#3175]
**What happened**:
In #3145 Satellite was added to jest configs.

I'm running tests on Satellite for ElasticSearch updates and noticed that there's an unusually large amount of tests for Satellite.
Satellite has only one test suite but tests are running 10 times. 
![image](https://user-images.githubusercontent.com/32626950/157948030-4385ec81-5e8e-4cab-83fd-84f776b47135.png)
Not sure why it is 10. It might be because we have 10 Services covered by tests that have Satellite as a dependency 

**What should have happened**:
Satellite tests should only run one test suite

**How to reproduce it (as precise as possible)**:
```
pnpm test satellite
``` 
```
pnpm test src/satellite
``` 
```
pnpm test src/satellite/test
```
all run the same test 10 times

**Anything else we need to know?**:
I am guessing it has something to do with the Satellite [jest.config](https://github.com/Seneca-CDOT/telescope/blob/master/src/satellite/jest.config.js) which wasn't updated on the merge into Telescope

**Environment**:

- OS:
- Browser:

**Comment by cindyledev** [comment]
Resolved in #3178
