### ISSUE TITLE
Dependency collection script fails during `pnpm version`

### ISSUE THREAD

**Issue by JerryHue** [Seneca-CDOT/telescope#3181]
**What happened**: The `collect-dependencies.js` script fails during `preversion`.

**What should have happened**: The `collect-dependencies.js` script should work as expected when running `pnpm version`, just like `node tools/collect-dependencies.js -- -o src/api/dependency-discovery/deps.txt` works.

**How to reproduce it (as precise as possible)**: You'd need to remove the `postversion` script in `package.json` to avoid uploading the new commit to `telescope/master`. After that, you can run `pnpm version`.

**Anything else we need to know?**: This error log:

```
> @senecacdot/telescope@2.8.1 preversion /home/gerardo/workspace/telescope
> node tools/collect-dependencies.js -- -o src/api/dependency-discovery/deps.txt && git add src/api/dependency-discovery/deps.txt

Starting to collect dependencies
Invoking pnpm list...
Processing file...
/home/gerardo/workspace/telescope/tools/collect-dependencies.js:28
  ...new Set([...output.matchAll(regex)].map((results) => results[1].replaceAll('+', '/')).sort()),
                                                                     ^

TypeError: results[1].replaceAll is not a function
    at /home/gerardo/workspace/telescope/tools/collect-dependencies.js:28:70
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/gerardo/workspace/telescope/tools/collect-dependencies.js:28:42)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @senecacdot/telescope@2.8.1 preversion: `node tools/collect-dependencies.js -- -o src/api/dependency-discovery/deps.txt && git add src/api/dependency-discovery/deps.txt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @senecacdot/telescope@2.8.1 preversion script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gerardo/.npm/_logs/2022-03-11T21_40_28_436Z-debug.log
```

**Comment by JerryHue** [comment]
I'm baffled. I ran the program over 10 times to understand the reason as to why a variable that is clearly a string, does not have the [function replaceAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) defined. The worst part is that this happens ONLY when you run `pnpm version`. If you run it as a regular script with `node`, it works out just fine.

Well, here's the funny: `replaceAll` has support on [Node.js from version 15 onwards](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility). A relatively modern feature. Not too bad, since almost everybody in Telescope uses `node` version 16. So, when I put `node collect-dependencies.js` in the `package.json`, I can expect the `node` is going to be the one used in the user's computer, right?

Yeah no. `npm` uses another version. When I put `console.log(process.versions)` in the script, and then run `pnpm version`, I get the nice answer to my problem:

```js
{
  node: '14.19.0',
  v8: '8.4.371.23-node.85',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.4',
  openssl: '1.1.1m',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}
```

**Comment by cindyledev** [comment]
Sorry, I don't fully understand this problem because I haven't worked with the dependency-discovery service yet but if I'm getting this correctly, the `pnpm preversion`, `pnpm version` and `pnpm postversion` scripts aren't running as expected? 

According to the [pnpm docs](https://pnpm.io/cli/run#differences-with-npm-run)

> By default, pnpm doesn't run arbitrary pre and post hooks for user-defined scripts (such as prestart). This behavior, inherited from npm, caused scripts to be implicit rather than explicit, obfuscating the execution flow.

If for some reason you need the pre/post scripts behavior of npm, use the enable-pre-post-scripts option.

This can be done by adding `enable-pre-post-scripts=true` to the `.npmrc` file

**Comment by JerryHue** [comment]
> Sorry, I don't fully understand this problem because I haven't worked with the dependency-discovery service yet but if I'm getting this correctly, the `pnpm preversion`, `pnpm version` and `pnpm postversion` scripts aren't running as expected?
> 
> According to the [pnpm docs](https://pnpm.io/cli/run#differences-with-npm-run)
> 
> > By default, pnpm doesn't run arbitrary pre and post hooks for user-defined scripts (such as prestart). This behavior, inherited from npm, caused scripts to be implicit rather than explicit, obfuscating the execution flow.
> 
> If for some reason you need the pre/post scripts behavior of npm, use the enable-pre-post-scripts option.
> 
> This can be done by adding `enable-pre-post-scripts=true` to the `.npmrc` file

The main error is not that they are not running as expected, the error is that the version of `node` being used in the `postversion` script is not the one installed globally (which for me is `node` v16), but instead the one specified locally to the project (this is my guess, don't quote me on that).

The reason I am so caught off-guard is because there is nowhere in the documentation that specifies this, which is why I took so long to understand the actual reason as to why a function is not actually defined (because the version of `node` used does not support the function itself).
