### ISSUE TITLE
502 from /health on Telescope backend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3183]
The backend's [health check](https://github.com/Seneca-CDOT/telescope/blob/e1d7c96eb998ffca900bf046f043c978fffb774f/src/backend/web/routes/health.js) often returns a 502:

```
206.174.190.116 - - [11/Mar/2022:23:44:30 +0000] "GET /health HTTP/2.0" 502 552 "https://telescope.cdot.systems/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
206.174.190.116 - - [11/Mar/2022:23:45:13 +0000] "GET /favicon.ico HTTP/2.0" 502 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
206.174.190.116 - - [11/Mar/2022:23:45:16 +0000] "GET /health HTTP/2.0" 502 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
206.174.190.116 - - [11/Mar/2022:23:45:16 +0000] "GET /favicon.ico HTTP/2.0" 502 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
```

<img width="496" alt="Screen Shot 2022-03-11 at 6 46 38 PM" src="https://user-images.githubusercontent.com/427398/157991475-49187073-9712-401c-ae0c-0fd135383261.png">

I wonder if we're running into rate limiting or something and the request to GitHub fails?  At any rate, we need to fix this.

**Comment by humphd** [comment]
@manekenpix reminds me that we don't run a web server on the backend anymore, only the parser, so this route can't work.

**Comment by humphd** [comment]
...correction, it looks like we do https://github.com/Seneca-CDOT/telescope/blob/62c76d08ef853887af27bede044265820770b09e/src/backend/index.js#L10

**Comment by HyperTHD** [comment]
@humphd Tested this, looking good right now, not code related so probably the former
![image](https://user-images.githubusercontent.com/16841702/159397024-b7f1355b-1e88-43ab-aeea-52ce46e8898a.png)

**Comment by humphd** [comment]
Backend is going away, closing.
