### ISSUE TITLE
Migrate staging and production to docker.cdot.systems based images

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3189]
Last night we turned on our new Docker Registry at https://docker.cdot.systems.  The [README](https://github.com/Seneca-CDOT/docker.cdot.systems#readme) has info on how it works if you're interested.

We also migrated our first service to use it: our beloved `feed-discovery`.  To do this, we had to make these changes:

1. Create a [workflow to build and deploy](https://github.com/Seneca-CDOT/telescope/blob/master/.github/workflows/deploy-feed-discovery-image.yaml) the service.  We may need to create 1 of these for each of our images, or maybe we can find a way to do a matrix in this file and selectively build/release only the ones that need it.
1. [Remove the `build` section](https://github.com/Seneca-CDOT/telescope/blob/master/docker/docker-compose.yml#L175-L197) from the service definition in `docker/docker-compose.yml`.  Now our base `docker-compose.yml` file defines the service, but not how it gets built/downloaded.
1. [Add the `build` section](https://github.com/Seneca-CDOT/telescope/blob/master/docker/development.yml#L96-L99) to `docker/development.yml`.  This will extend `docker/docker-compose.yml` in development and build from out local `Dockerfile`.
1. [Add an `image` section](https://github.com/Seneca-CDOT/telescope/blob/master/docker/production.yml#L118-L120) to `docker/production.yml`.  This will extend `docker/docker-compose.yml` in production to download the pre-built image from our registry.

We need to do this same dance for all of our Dockerfiles.

Next, I'd like to start using the following Docker tags:

1. `production` - this is the tag we'll `pull` on our production box, for example: `docker.cdot.systems/feed-discovery:production`.  
1. `staging` - this is the tag we'll `pull` on our staging box, for example: `docker.cdot.systems/feed-discovery:staging`.  
1. `latest` - this is the tag we'll `pull` locally or on gitpod if we want to get the most recent build, for example: `docker.cdot.systems/feed-discovery:latest` or just `docker.cdot.systems/feed-discovery`

We'll have to update our `docker/*.yml` files to use environment variable names for the image tags (e.g., `docker.cdot.systems/feed-discovery:${VERSION}` where `VERSION` is `latest` (default), `staging`, or `production` 

Doing this will require a whole bunch of fixes and separate PRs/people.  We should be able to do it in small stages.

**Comment by humphd** [comment]
@rclee91 ran into an issue in our AWS docs where we don't seem to do the right thing:

![image](https://user-images.githubusercontent.com/427398/158069728-6952c5eb-0511-467f-b5c7-118ac43f7777.png)

We need to make sure that we either build or use a pre-built image, which requires using one of `docker/development.yml` or `docker/production.yml` along with `docker/docker-compose.yml`.

**Comment by humphd** [comment]
cc @cindyledev

**Comment by cindyledev** [comment]
> @rclee91 ran into an issue in our AWS docs where we don't seem to do the right thing:
> 
> ![image](https://user-images.githubusercontent.com/427398/158069728-6952c5eb-0511-467f-b5c7-118ac43f7777.png)
> 
> We need to make sure that we either build or use a pre-built image, which requires using one of `docker/development.yml` or `docker/production.yml` along with `docker/docker-compose.yml`.

I filed issue #3201
