### ISSUE TITLE
Fix image profile flickering on star field

### ISSUE THREAD

**Issue by dbelokon** [Seneca-CDOT/telescope#3193]
In #3149, a star field animation was added to the About page.

For some strange reason, there is flickering, where some profile pictures would appear somewhat big and then disappear.

**Comment by TueeNguyen** [comment]
Also, can we slow down the animation, my eyes actually hurt :)

**Comment by humphd** [comment]
> Also, can we slow down the animation, my eyes actually hurt :)

That's an interesting point, especially for users with Epilepsy or others who might have [set `prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).

I wonder if we should add a check for `prefers-reduced-motion` and not animate it, just show a static frame with the faces.  That can be another follow-up PR too, beyond this flickering fix.

**Comment by JerryHue** [comment]
I would like to work on this. I think we would have to improve the way the current math works to actually create the feeling of depth.

> > Also, can we slow down the animation, my eyes actually hurt :)
> 
> That's an interesting point, especially for users with Epilepsy or others who might have [set `prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).
> 
> I wonder if we should add a check for `prefers-reduced-motion` and not animate it, just show a static frame with the faces. That can be another follow-up PR too, beyond this flickering fix.

I think we could make the speed of the stars much slower, as a way to not overwhelm the viewer, and limit the number of stars on the screen, as a way to not have all profiles shown at once.

However, to do all of this we might need to revamp the current rendering code. While Dan's code works, it was written very quickly for the sake of the coding challenge, and thus is not very adaptable.
