### ISSUE TITLE
Add ESLint to lint all our JS/JSON

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#32]
We should really have a proper automated linting step using [ESLint](https://eslint.org/).  You can see good docs on how to do this at https://eslint.org/docs/user-guide/getting-started, and look at how lots of other projects do their linting by reading their `.eslintrc` file(s).

Until we get automated tests written, this can serve as our `npm test` step, and let us start automating CI in other bugs.

**Comment by kartik-budhiraja** [comment]
We can use [Airbnb Javascript style](https://github.com/airbnb/javascript) guide as starting base and extend it. The eslint config is available through npm package `eslint-config-airbnb-base`.

**Comment by UltimaBGD** [comment]
In the event Airbnb style is something we are interested in, I will quickly put up a pull request with it setup for people to test with.

**Comment by UltimaBGD** [comment]
The pull request has been merged, shall we close this issue or keep it up for further discussion?

**Comment by humphd** [comment]
Close.  Also, we should make sure that people use the "Fixes <issue number>" style in their PRs so GitHub will auto-close issues fixed by PRs.

Thanks for working on this!
