### ISSUE TITLE
Adding footer for mobile app's about screen

### ISSUE THREAD

**Issue by nguyenhung15913** [Seneca-CDOT/telescope#3203]
**What would you like to be added**:
After this [PR](https://github.com/Seneca-CDOT/telescope/pull/3167) gets merger, a footer needs to be added to the about screen of our React Native app.
![image](https://user-images.githubusercontent.com/69558780/158086115-54df243f-20b1-42e0-8f58-947ce5969329.png)
**Why would you like this to be added**:
Because of the original design of Telescope

**Comment by mikepng** [comment]
Hi,can someone elaborate on what's going on with the react native app? What's the state of the app? I can certainly help.

**Comment by humphd** [comment]
> Hi,can someone elaborate on what's going on with the react native app? What's the state of the app? I can certainly help.

cc @nguyenhung15913, @tpmai22, @Kevan-Y

**Comment by tpmai22** [comment]
@mikepng Right now we try to putting small PRs to have the app up and running. Our recent work have been working on the About page, Home page, setting up basic navigation for the app. We try to have some blog post by the end of our 2.9. So right now I would say our mobile app just beginning

**Comment by mikepng** [comment]
@tpmai22 is there a figma link for the design of the screens?

**Comment by mikepng** [comment]
@tpmai22 is there a figma link for the UI of the screens?

**Comment by TueeNguyen** [comment]
@mikepng, we use our own web app https://telescope.cdot.systems/ for the design
