### ISSUE TITLE
[Image]: Banner image failed to load because CORS violation

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#3212]
The banner image is not showing on staging

**What happened**:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/51073515/158313462-03f65123-8626-4e2a-baac-e9c08ad9d766.png">

**Environment**:
- OS: macOS Montery
- Browser: Any browser

**Comment by DukeManh** [comment]
I used [git bisect](https://git-scm.com/docs/git-bisect) and found the commit that introduced this. cc @menghif 

<img width="827" alt="image" src="https://user-images.githubusercontent.com/51073515/158321327-4c46917a-2968-450a-a14c-17798b047cb2.png">

**Comment by cindyledev** [comment]
ESLint? *sweats*

Satellite? *sweats even more*

**Comment by DukeManh** [comment]
>ESLint? sweats

Satellite? sweats even more
I don't know how this commit could introduce this bug. It seems innocent enough.

Why are you staying up so late :) btw

**Comment by cindyledev** [comment]
> > ESLint? sweats
> 
> Satellite? sweats even more I don't know how this commit could introduce this bug. It seems innocent enough.
> 
> Why are you staying up so late :) btw

I think I'm addicted to Telescope 🤔

**Comment by humphd** [comment]
Reading https://github.com/Seneca-CDOT/telescope/commit/5ede9, I notice that we updated [helmet](https://www.npmjs.com/package/helmet) from `4.6.0` to `5.2.0`, which is maybe what's broken us here.

**Comment by DukeManh** [comment]
If we expand the diff view of pnpm-lock from the commit, we'll see that satellite module is being link to the local repo rather than node_modules. Did you run pnpm link by accident Francesco.

**Comment by humphd** [comment]
In case it is helmet, here's the changelog https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md

**Comment by DukeManh** [comment]
You are right, it's because of the helmet updated from this [PR](https://github.com/Seneca-CDOT/satellite/pull/76). This change has not been released but `satellite` is linked as a local dependency, not the published one, which causes this.
