### ISSUE TITLE
Add .ts and .tsx to `prettier` script in root package.json

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#3213]
We need to make our `.ts` and `.tsx` code pretty. Can't believe we haven't been using prettier for our `.ts` and `.tsx`

https://github.com/Seneca-CDOT/telescope/blob/6439dbd2f7111c210fa68bbf58fd3ee6fd53988c/package.json#L20-L21

**Comment by cindyledev** [comment]
I did some weird stuff last night with TypeScript and ESLint complained and prettier acted like it didn't know me

**Comment by 1ibrahimhassan1** [comment]
Hello

**Comment by humphd** [comment]
cc'ing @menghif, @tcvan0707, @JiaHua-Zou, @aserputov, who can lend support (they know this code well).

**Comment by cindyledev** [comment]
Closed via #3316
