### ISSUE TITLE
Use Postgres to store GitHub data

### ISSUE THREAD

**Issue by JerryHue** [Seneca-CDOT/telescope#3215]
There has been a lot of discussion regarding storing and indexing GitHub information that appears on posts, and how this information can also be used to leverage the use cases of the `dependency-discovery` issue. For example, in #2831 and #2827, we have mentioned several times this, so I think it is time to lay some foundations.

### Motivation

The reason I would like to store all of this in Postgres has been mentioned in [this comment](https://github.com/Seneca-CDOT/telescope/issues/2831#issuecomment-1059820095) of #2831, but I can summarize it like this:

- Although the GitHub data is data we can extract by analysing the posts, the idea is to save that analysis to avoid repeating the work.
- Postgres is more flexible and general than Elasticsearch.

There is also the fact that we are working with an API that has a limit of requests per hour (that being the GitHub API), so storing part of that information in our side would reduce the amount of requests we would have to make.

### Usage of Postgres

How would Postgres be used across the services? Well, since every service might have a specific use case, the idea is to define a simple, flexible interface in Postgres that all services have to respect to use it.

Part of this interface is, of course, the SQL tables we would have to create. 

I can only speak accurately for the `dependency-discovery`. The way that the `dependency-discovery` service might use the store is keeping the repositories relevant to the dependency list, and caching the issues that users are interested the most (like issues labelled "good first issue").

### Table design

The starting point is three tables:

- GitHub Users (these include organizations),
- GitHub Issues (these include Pull requests),
- GitHub Repositories.

You might see the relationships between all of these:

- A GitHub User can have zero or several Repositories,
- A GitHub repository can have zero or several issues.

### Extended design

As you can see the initial design is very generic, and thus, might need more information depending on the use case. Let's think, for example, the search service.

The search service wants to find the posts depending on the GitHub users mentioned. In this case, we would want to connect the GitHub user we have stored with all of the posts we currently have stored in our tables. We can easily connect these two entities by creating a joint/bridge table.

## Let's discuss

I would like to hear anybody's opinions regarding this. The main problem I currently have is that we may be saving too much information that we could easily get from GitHub. I am aware that the main reason we do this is to avoid asking GitHub several times (and thus reach our request limit too quickly), but we might need to refresh this GitHub information quite frequently. Would we need to program some kind of "update info on demand", and the parts that are less requested we update less frequently?

**Comment by humphd** [comment]
I think we have two types of data:

- historical data (GitHub users, orgs, pull requests)
- current and evolving data (values returned by the GitHub API for things like Issues with a given Label)

The historical data belongs in postgres, I agree.  The latter is probably better thought of as being cached vs. stored long term, since it will change frequently, and storing a list of "current" issues doesn't make sense.  For this info, I'd suggest Redis with a TTL that expires the data when we should go get more.

**Comment by TueeNguyen** [comment]
Would the `github_issues` table  consists of issues and pull requests that are mentioned in any blog posts?
