### ISSUE TITLE
Search icon floating with window resize

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#322]
In #302 we added a search field and icon to the frontend mockups.  Testing this locally, I notice that it seems to be positioned relative to the viewport vs. it's container, and changing the window size causes it to float around.

![search-icon-bug](https://user-images.githubusercontent.com/427398/69382833-09ee8900-0c86-11ea-8cb1-b93117fddc2e.gif)

**Comment by humphd** [comment]
cc @ODAVING

**Comment by eekbatani** [comment]
I can go ahead and get this fixed.
