### ISSUE TITLE
Fix naming for workflow job

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3221]
https://github.com/Seneca-CDOT/telescope/blob/master/.github/workflows/release.yml#L56

This should be:

```yaml
name: Production Deploy
```

**Comment by humphd** [comment]
Let's have a first-time contributor take this one, please.

**Comment by aMaksimets** [comment]
https://github.com/Seneca-CDOT/telescope/pull/3227

**Comment by cindyledev** [comment]
Closed via #3227
