### ISSUE TITLE
Add .gitattributes file and disable linebreak-style

### ISSUE THREAD

**Issue by sukhbeersingh** [Seneca-CDOT/telescope#323]
Currently, when windows users run npm test against the latest changes prettier complains about line endings. Same for our CI services. See #194. This issue can be solved for the time being by disabling the `linebreak-style` rule from `.eslintrc.js`.

**Comment by humphd** [comment]
Specifically, see my comment in https://github.com/Seneca-CDOT/telescope/pull/194#issuecomment-556061359.  Also, @sukhbeersingh is referring to our eslintrc.js file, which needs to have the ['linebreak-style': 'off'](https://eslint.org/docs/rules/linebreak-style) rule set, to ignore end of line checks, and let Prettier do them.

**Comment by humphd** [comment]
Also note: this is pretty high priority, so the sooner we get this done, the better.  It should help people moving forward, especially on Windows.

**Comment by sukhbeersingh** [comment]
I will send a pr in a few minutes. and then follow up another to fix the windows Circle CI issue

**Comment by humphd** [comment]
Thank you, @sukhbeersingh, really appreciated!

**Comment by humphd** [comment]
Fixed by #324
