### ISSUE TITLE
e2e tests not using Docker registry cache with docker-compose

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3230]
I just [ran some e2e tests on CI](https://github.com/Seneca-CDOT/telescope/pull/3229/checks) and noticed that `pnpm services:start` isn't using our Docker registry cache.  When we run this, internally we do this: https://github.com/Seneca-CDOT/telescope/blob/master/tools/services.js#L16-L30

That is basically calling `docker-compose ... --build --remove-orphans`.  It looks like `docker` builds vs. `docker-compose` builds use slightly different digests, so they don't seem to be interchangable.

See:

- https://github.com/moby/moby/issues/40126
- https://github.com/docker/build-push-action/issues/493

It would be great if we could use our registry cache for these builds to speed things up.  I'm not 100% clear on the right way to accomplish this.

**Comment by menghif** [comment]
Fixed in #3254
