### ISSUE TITLE
Set up a GitHub Provider config with team, token access

### ISSUE THREAD

**Issue by TDDR** [Seneca-CDOT/telescope#3240]
This is a follow up to issue #2801 

There was only one task left on the initial checklist to setting up the Docker registry. 
![image](https://user-images.githubusercontent.com/59970326/158811220-193672f6-4ee9-4b0b-b5bc-fffe8cb6787e.png)

We need to figure out how to set up a GitHub Provider config with team, token access:
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#github-auth-provider

**Comment by humphd** [comment]
This has been done.

**Comment by humphd** [comment]
This is working fine now the way we have it.
