### ISSUE TITLE
Eslint hangs

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#3245]
Running `pnpm lint` won't finish.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/51073515/158870361-20376733-ae6e-448e-bcca-f7ecfab84198.png">

**Environment**:

- OS:macOS 12

**Comment by cindyledev** [comment]
I suspect it hangs because we didn't set any ignore patterns so eslint might be going into node_modules

**Comment by DukeManh** [comment]
I thought eslint ignores node_modules by default
