### ISSUE TITLE
Dark mode github stylesheet sometimes used in light mode

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3252]
Something has recently changed our colour highlighting so that it's really washed out.  Let's revert it.

<img width="789" alt="Screen Shot 2022-03-17 at 8 11 18 PM" src="https://user-images.githubusercontent.com/427398/158913701-a1ad7fbf-20b2-41da-874e-e9553c3ce7f5.png">

**Comment by humphd** [comment]
I think I've figured out what this is, and it only happens sometimes.  The dark vs. light stylesheet is being applied in light mode:

<img width="1373" alt="Screen Shot 2022-04-07 at 5 30 54 PM" src="https://user-images.githubusercontent.com/427398/162323102-c6c2a3c9-89da-4ce0-b8dd-02970994d268.png">

**Comment by SerpentBytes** [comment]
@humphd it does not seem to happen anymore. Perhaps, #3761 may have fixed the problem. It would be safe to close this issue.
