### ISSUE TITLE
Update eslint and stylelint configs for Prettier plugins

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#326]
The prettier docs have some guidelines on plugins to use with eslint and stylelint, both of which we use:

- eslint: https://prettier.io/docs/en/integrating-with-linters.html#recommended-configuration
- stylelint: https://prettier.io/docs/en/integrating-with-linters.html#stylelint

cc @vitokhangnguyen

**Comment by vitokhangnguyen** [comment]
I can take on this issue.

The guideline of Prettier for ESLint has been followed when I set them in #96. I can do the same for stylelint, too.
