### ISSUE TITLE
Videos from Youtube feed appear twice

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#3288]
I notice youtube videos appear twice.
https://dev.telescope.cdot.systems/search/?text=azure%20sdk&filter=post
<img width="654" alt="image" src="https://user-images.githubusercontent.com/51073515/159570945-ea6e724a-e33c-4f8f-b6a8-7861509f9299.png">
- Deployment: staging + production
- OS: macOS 12
- Browser: Firefox

**Comment by humphd** [comment]
"A lecture so nice we're showing it twice!"

**Comment by JerryHue** [comment]
I checked the changes in #3282, and it seems that @dbelokon fixed this.
