### ISSUE TITLE
Branding: we need a logo!

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#33]
Is anyone good at drawing logos?  We could use one, so we can put it in our README.

**Comment by brucremo** [comment]
I could draw us a logo for our README!

**Comment by PavanKKamra** [comment]
Can I also attempt to draw a logo for our README? :) 

Regards,
Pavan K.

**Comment by humphd** [comment]
@PavanKKamra it sounds like @brucremo is going to do this, maybe you can help with reviews?

**Comment by lucacataldo** [comment]
Hey @brucremo when making the UI [mockup](https://xd.adobe.com/view/f1e160d0-2c49-4700-4ca6-2f2f660dfb6f-87d0/) I created a very simple logo as a placeholder before seeing this. If you want to use it as a basis let me know and I can send you the SVG! If not I'll include yours in the mockup when it's ready. 😄

**Comment by lucacataldo** [comment]
@brucremo hey any progress on this or would you like me to take over / help out?

**Comment by brucremo** [comment]
Good morning @lucacataldo! I am almost done with my last sketch and should have the PR up by the end of today, got some nice things cooking!

**Comment by lucacataldo** [comment]
Awesome @brucremo I'm looking forward to it! 👍

**Comment by humphd** [comment]
First attempt at this landed in #175.
