### ISSUE TITLE
Remove GitHub Webhooks

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3306]
Last night we tested our new deploy webhook, and @TDDR has updated the code for the bugs we found (see #3303).  After we see it successfully do the release on production, we can remove the current webhooks.

**Comment by TDDR** [comment]
Would it be these webhooks that I am removing? 
![image](https://user-images.githubusercontent.com/59970326/160626347-76efc158-e10f-4028-8e91-8af46c515e18.png)

**Comment by humphd** [comment]
Yes, they can go now.  Can you do it?  There might be secrets we can remove too.

**Comment by TDDR** [comment]
These secrets?
![image](https://user-images.githubusercontent.com/59970326/160629071-dcefdfd3-4ad9-4b0f-9394-84d4742f7c61.png)

**Comment by TDDR** [comment]
Okay, so now that those old webhooks have been removed I can close this issue?
