### ISSUE TITLE
CI overlooks mismatched pnpm-lock.yaml file

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#3311]
**What happened**:
We have been getting CI to fail the check to see if the pnpm-lock.yaml file is up to date. 

**What should have happened**:
CI should fail every commit that does not have the correct pnpm-lock.yaml file.

**How to reproduce it (as precise as possible)**:
Put up an outdated pnpm-lock.yaml, watch CI pass on Telescope PRs. I think on local branch it's different.

**Anything else we need to know?**:
### Cindy's commit in master - passed CI. 
![chrome_dXEXp9PT3O](https://user-images.githubusercontent.com/77639637/159972465-92f6acc8-ab8b-4041-8e5d-363ca817029d.png)

### Cindy's PR Actions Report
![chrome_EJw6HAUZdf](https://user-images.githubusercontent.com/77639637/159972453-581adf05-641a-40d6-b768-6c594a49e248.png)

### Cindy's Branch on her fork for the same code:
![chrome_Tm67y7xKhQ](https://user-images.githubusercontent.com/77639637/159972429-609ebab1-f78a-40ca-bf18-cad242efe006.png)
**Environment**:

- OS:
- Browser:

**Comment by JerryHue** [comment]
Should we have a single workflow that checks for this and avoids running the rest of the runs, so that we don't have to wait for the rest?

**Comment by humphd** [comment]
Do a test: make a PR that intentionally has the lock-file out of sync, and see what our CI does?

**Comment by JerryHue** [comment]
I will do it now. I think it is urgent we push this, because there are other PRs that add a few dependencies, and we don't want master to start having a stale `pnpm-lock`.

**Comment by JerryHue** [comment]
Also, I think Cindy's CI broke because of an unrelated issue: 
![image](https://user-images.githubusercontent.com/53304516/159974121-409a5bd4-94fb-4879-a88c-131c9e877e38.png)

Seems to be related to Vercel deployment.

**Comment by JerryHue** [comment]
Some interesting results:

- If the `pnpm-lock` file is *stale*, `pnpm install` will fail, and thus CI fails. Here is an example run: 
![image](https://user-images.githubusercontent.com/53304516/159987341-b63041bb-55f0-47f5-a398-fc5f9808d8c8.png)
- If the `pnpm-lock` file is *broken*, `pnpm install` does not fail, and thus CI does not fail either. You can check the run: 
![image](https://user-images.githubusercontent.com/53304516/159987277-cf08e632-2e31-4c28-862a-58a80507603b.png)

**Comment by JerryHue** [comment]
We can add a job to check that the `pnpm-lock` is not broken, by using `pnpm list` (it was thanks to the `collect-dependencies.js` script that we noticed this issue, and the script uses `pnpm list`).

**Comment by humphd** [comment]
Also, what does "broken" mean in the screenshot above?  What is broken about that lock file?

**Comment by DukeManh** [comment]
@JerryHue, I think that's the issue, if pnpm-lock is broken and needs to be updated then it should fail too. We should file an issue in the `pnpm` repo.

**Comment by humphd** [comment]
I agree, this sounds like a `pnpm` bug to me.

**Comment by JerryHue** [comment]
> What will `pnpm list` do for us in this case?

It will exit code with status 1 (error), if the lock-file is broken.

> Also, what does "broken" mean in the screenshot above? What is broken about that lock file?

Here's the message that it shows:

```
 WARN  Ignoring broken lockfile at /home/gerardo/workspace/telescope: The lockfile at "/home/gerardo/workspace/telescope/pnpm-lock.yaml" is broken: duplicated mapping key (1041:3)

 1038 |       - supports-color
 1039 |     dev: false
 1040 |
 1041 |   /@babel/helper-define-polyfill ...
----------^
 1042 |     resolution: {integrity: sha5 ...
 1043 |     peerDependencies:
```

I am not sure why this occurs in the first place, but we have to check against this to avoid a similar situation.

**Comment by JerryHue** [comment]
> @JerryHue, I think that's the issue, if pnpm-lock is broken and needs to be updated then it should fail too. We should file an issue in the `pnpm` repo.

I don't want to speak for the `pnpm` developers, but they never promised anything like that. If you read carefully the [`pnpm install` docs](https://pnpm.io/cli/install):

     In a CI environment, installation fails if a lockfile is present but needs an update.

The lockfile does not need an update, it is just broken. That is why the current behaviour is a warning and not an error.

I could try to clarify this matter with the developers if necessary.

**Comment by humphd** [comment]
Asked on twitter https://twitter.com/humphd/status/1507067840825856008

**Comment by JerryHue** [comment]
Should I submit a discussion in the pnpm repo? So that other people could notice about this?

**Comment by JerryHue** [comment]
I think the current `pnpm` twitter account is suspended :(
![image](https://user-images.githubusercontent.com/53304516/159991159-0b23c97a-2ec3-4989-9935-7e194641dfa8.png)

**Comment by humphd** [comment]
Ah, that sucks.  Thanks for doing the discussion.

**Comment by humphd** [comment]
https://twitter.com/pnpmjs
