### ISSUE TITLE
Build log no longer able to show build

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#3318]
**What happened**:
Build log is no longer showing. 

**What should have happened**:
Build log should show. 

**How to reproduce it (as precise as possible)**:
Trigger a build, see it missing on Build. 

**Anything else we need to know?**:
When you revert 33858ecb2b27f86c59b710a84cc9f14ec51f4376, the build log works when we trigger a build.

**Environment**:

- OS:
- Browser:

**Comment by humphd** [comment]
The error I see is the one I thought you fixed:

<img width="1358" alt="Screen Shot 2022-03-24 at 9 13 07 PM" src="https://user-images.githubusercontent.com/427398/160035489-0418523e-e834-406e-81f6-f031e713da0f.png">

**Comment by manekenpix** [comment]
#3341 was targeting a different bug, but it seems that it also fixed this one.
