### ISSUE TITLE
Move constants to .env file

### ISSUE THREAD

**Issue by ragnarokatz** [Seneca-CDOT/telescope#334]
link to issue #297, as per comment left by @humphd

> These magic numbers (`8`, `60 * 1000`) should probably go in the env. Would be good in another PR.

Move constants from `src/index.js` file into the `.env` file.

```
await feedQueue.add(feedJob, {
      attempts: 8,
      backoff: {
        type: 'exponential',
        delay: 60 * 1000,
      },
```

**Comment by nazneennahar** [comment]
hey can i work on this please
