### ISSUE TITLE
Adding GitHub API service to footer of mobile app

### ISSUE THREAD

**Issue by nguyenhung15913** [Seneca-CDOT/telescope#3343]
**What would you like to be added**:
Right now the contributor card in the [footer](https://github.com/Seneca-CDOT/telescope/pull/3320) is just a placeholder. Once the PR (https://github.com/Seneca-CDOT/telescope/pull/3320) gets merged, A GitHub API service needs to be added to make it dynamically display Telescope's contributors.
![image](https://user-images.githubusercontent.com/69558780/160260247-65a09b09-9fe6-4041-a3fe-26daba19cfb8.png)

**Why would you like this to be added**:

**Comment by tcvan0707** [comment]
@nguyenhung15913, what is your status for this issue?

**Comment by manekenpix** [comment]
Closing since the mobile version of telescope was removed in #3805
