### ISSUE TITLE
Remove duplicity caused by using both async and Promise in a function

### ISSUE THREAD

**Issue by ragnarokatz** [Seneca-CDOT/telescope#335]
reference comments left by @humphd in PR #297:

> NOTE: Because you already `await` on line 8 above, and because this is an `async` function, you can skip the `Promise.resolve()` and `Promise.reject()` throughout this function. An `async` function implicitly returns a `Promise`. What you've done here will work, but is unnecessary, and the `Promises` will get unwrapped to expose your result as intended.
> 
> If you were in a function, and wanted to convert a synchronous call to be a `Promise`, you could do this. However, if you're going to use both `Promise.resolve()` and `Promise.reject()`, you might was well `return new Promise((resolve, reject) => { /* your code here */ })`.
> 
> We should probably clean this up later in another PR, since this has been merged.

This is referring to code:
```
exports.workerCallback = async function(job) {
  const { url } = job.data;
  try {
    const posts = await feedParser(url);
    const processedPosts = [];
    if (posts.length > 0) {
      posts.forEach(post => {
        // We can extract any other information from the post that we need here.
        const processedPost = {
          author: post.author,
          date: post.date,
          title: post.title,
          description: post.description,
          postURL: post.link,
        };
        processedPosts.push(processedPost);
        extractUrls.extract(post.description);
      });
      // We can pass these objects into another queue, For now just printing to the console.
      console.log(processedPosts);
      return Promise.resolve(processedPosts);
    }
    return Promise.reject(new Error(`Failed to extract posts from url: ${url}`));
  } catch (err) {
    return Promise.reject(err);
  }
};
```

in `src/feed-worker.js`

**Comment by robertbegna** [comment]
I can try fixing this

**Comment by humphd** [comment]
Some more background here.  Our current feed workers are all reporting failures:

```
[ 2019-11-24 12:34:40.120 ] INFO  (22813 on brightness.local): Job 291 is waiting.
    module: "queue:feed-queue"
[ 2019-11-24 12:34:40.120 ] INFO  (22813 on brightness.local): Job 291 is active
    module: "queue:feed-queue"
[ 2019-11-24 12:34:40.243 ] ERROR (22813 on brightness.local): Job 291 failed: {}
```

This is because of the way the `Promise` is being done from this function.  A worker function should return a `Promise` that gets `resolved` or `rejected`.

This code should get rid of all the `Promise.reject(...)` and `Promise.resolve(...)` code, and replace it with `throw ...` or `return ...`.  I think that will fix things.

**Comment by ragnarokatz** [comment]
so there are two ways to write a callback function that can either success or fail a job, according to documentation of `bull`: https://github.com/OptimalBits/bull#documentation

no promise:
```
queue.process(function(job, done){
  // do something here
  ...

  // call done when finished
  done();

  // or give a error if error
  done(new Error('error transcoding'));
});

```

using promise:
```
queue.process(function(job){ // don't forget to remove the done callback!
  // do something here
  ...

  // Passes the value the promise is resolved with to the "completed" event
  return Promise.resolve({ object: 'blahblah' });

  // or give it an error if it fails
  return Promise.reject(new Error('some unexpected error'));
});
```

**Comment by humphd** [comment]
```js
queue.process(async (job) => {
    return await someAsyncCall();
});
```

Is a third way, and doesn't involve explicit use of `Promise`.

**Comment by humphd** [comment]
@robertbegna this issue needs a fix very soon, as it will block other work.  Are you close?  If you can't get it done, I'll do it.  Let me know.
