### ISSUE TITLE
Get feed information directly from Supabase

### ISSUE THREAD

**Issue by JerryHue** [Seneca-CDOT/telescope#3355]
For #1907, we need to figure out the code dependent on the feeds-related route in the `posts` service. One of these dependents is the front-end. The front-end needs access to Supabase to get the related information.

**Comment by HyperTHD** [comment]
Related to #1907 as well, so perhaps could be dealt with as well?

**Comment by TueeNguyen** [comment]
Seems like the only place that uses `FEED_URL`, this PR #3465  changes to use Supabase instead
