### ISSUE TITLE
Write Postgres Seed script to popluate Feeds table in production and development

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#3359]
The script will use [/tools/migrate/migrate.js](https://github.com/Seneca-CDOT/telescope/blob/master/tools/migrate/migrate.js) and `supabase-js` API to insert feeds to a Table.

Ideally, we only need to run this script once in production. The production Supabase Studio is what we use to manage feeds from now on.

**Comment by tpmai22** [comment]
can we do the same thing for `quotes` table ?

**Comment by TueeNguyen** [comment]
It's posible yeah.
