### ISSUE TITLE
nginx: Unsuccessful OAuth authentication

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#3374]
I was not able to log in to Supabase subdomain.

I notice the `redirect_uri` query param is not right.

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/51073515/161176150-4eb729b1-25b7-4af2-a3b9-4715bdc6557d.png">

**Comment by Kevan-Y** [comment]
Are you using staging or production?

**Comment by humphd** [comment]
`redirect_uri` looks right to me, what do you mean?

**Comment by DukeManh** [comment]
@Kevan-Y, I'm on staging.

@humphd, I'm trying to log in to dev.supabase.telescope.cdot.systems, but it redirects me to portainer.telescope.cdot.systems.

**Comment by Kevan-Y** [comment]
@DukeManh Interesting, staging is down completely. Did you test when my PR for that merged?

**Comment by DukeManh** [comment]
Last night, after your PR.

**Comment by Kevan-Y** [comment]
Was staging working that time?

**Comment by Kevan-Y** [comment]
Ok weird might have another bug.
Techinically it should show this page 🔽
![image](https://user-images.githubusercontent.com/58233223/161292906-87ff0a55-5353-499f-9e40-c8a77b22ec29.png)

**Comment by DukeManh** [comment]
close via #3379
