### ISSUE TITLE
Link to login.html doesn't work

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#338]
![Annotation 2019-11-23 213212](https://user-images.githubusercontent.com/36822198/69488555-cc7e2d00-0e38-11ea-842a-177527d50763.png)

**Comment by humphd** [comment]
Nice catch.  Let's move `src/login/login.html` to `src/frontend/login.html` and also update `src/frontend/index.html` to refer to the correct relative URL for login.

cc @agarcia-caicedo, @Grommers00

**Comment by Grommers00** [comment]
Good find! it starts locally from the direct.html site, but not when the server is booted up. Interesting!

**Comment by vitokhangnguyen** [comment]
The `login` folder is not being served as a static asset.

This line in the `app.js` would help but I think there is a more appropriate fix than this as @humphd  mentioned:
```js
app.use(express.static('src/login'));
```
