### ISSUE TITLE
Add links for Portainer and Supabase to the Dashboard

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3380]
We've got two new admin apps that we need to access:

1. Portainer
    - Staging = https://dev.portainer.telescope.cdot.systems/
    - Production = https://portainer.telescope.cdot.systems/
2. Supabase
    - Staging = https://dev.supabase.telescope.cdot.systems
    - Production = https://dev.supabase.telescope.cdot.systems

Let's add these links to the sidebar of the Dashboard, so they are easier to find.

NOTE: in order to access these, you have to be a member of the 'Telescope Admins' group on GitHub.  I can add whoever needs it (everyone that's maintaining things should already have it).

**Comment by joelazwar** [comment]
Gonna push a quick PR for this, just one thing, the links for Supabase are the same for staging and prod. Are we using the same Supabase instance for both staging and production?
