### ISSUE TITLE
Fix anon and service roles keys in kong.yml

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3381]
We almost have Supabase working in production.  Next problem is that we have incorrect, hard-coded keys at https://github.com/Seneca-CDOT/telescope/blob/master/docker/supabase/volumes/api/kong.yml#L6-L12

We either need to move this file to staging and production and hard-code the proper keys there (probably easiest), or we need to figure out how to overwrite with variables from the env on startup.

@manekenpix if I prepare two files for you with the right keys, would you put them in `../config/kong.yml`?

**Comment by manekenpix** [comment]
@humphd of course!
