### ISSUE TITLE
Clean-up Satellite project

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3389]
We've moved the Satellite project into Telescope, and we need to clean up the remaining bits of it:

- [x] Migrate the issues to Telescope https://github.com/Seneca-CDOT/satellite/issues
- [x] Deal with the pull request https://github.com/Seneca-CDOT/satellite/pulls
- [x] Update the README to indicate that it has moved to Telescope
- [x] Archive the repo
- [x] Remove the "Satellite" bits of the Dashboard (and anywhere else we still have links)

**Comment by menghif** [comment]
Should we also remove the 2 GitHub Apps (Renovate, Slack) installed in the Satellite repo before archiving it?

**Comment by humphd** [comment]
Yeah, that's a good idea, can you do it?

**Comment by menghif** [comment]
No, it says only owners can do it.

**Comment by humphd** [comment]
I removed Renovate for Satellite, but Slack seems to be ORG-wide, so I left it.

**Comment by menghif** [comment]
The Satellite repo has been archived.
