### ISSUE TITLE
Improve readability of CSS in frontend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#339]
I took a look at a few sites that are focused on presenting articles, reading, and doing similar things to what we're building.  I wanted to find inspiration and some CSS patterns and techniques we could leverage.  Consider:

- [Medium](https://medium.com/@REAS/collecting-in-the-age-of-digital-reproduction-ab0640a42fe6)
- [Longreads](https://longreads.com/2019/11/07/california-burning/)
- [The New Yorker](https://www.newyorker.com/sports/sporting-scene/the-blockbuster-video-game-that-wants-to-make-america-whole-again?utm_source=twitter&utm_brand=tny&mbid=social_twitter&utm_social-type=owned&utm_medium=social)
- [The New York Times](https://www.nytimes.com/2019/11/04/science/voyager-2-interstellar-solar-wind.html).

All of them use a similar pattern:

1. Title of the article: `font-size` is often `2rem` to `2.5rem`, or `45px` to `48px`.  The `line-height` is `1.5rem` to `3rem`.  Font families used for titles: Palatino, Georgia, Cambria, "Times New Roman", Times, Helvetica Neue, Helvetica, Arial.
1. The article itself has a `width` of `600px` to `671px` to `680px` to `728px`, giving an average width of `670px`.  The `font-size` is usually `21px` or `1.25rem`. The `line-height` ranges from `1.43` to `1.58` to `1.875`, average is `1.6`.  All use left aligned text.  The `p` elements use a `margin` of `1em`.
1. Images use a width of `671px` to `945px` with a `max-width` of `1200px` or even `100vw`.

Based on this, some initial suggestions for improving readability:

1. Use a `font-size` of `2.5rem` for the post title
1. Use a `font-size` of `1.25rem` on the post's text and a `line-height` of `1.6`.
1. Set a `width` of `670px` on the content, and split the extra space using `margin-left: auto` and `margin-right: auto`.
1. Left align text vs. justifying
1. Force `img` elements to not exceed a `max-width` of `1200px` or less

I played with these a bit in dev tools, and it looks something like this:

<img width="761" alt="Screen Shot 2019-11-24 at 12 33 09 PM" src="https://user-images.githubusercontent.com/427398/69498506-a5664080-0eb6-11ea-8b5f-ef55c36be189.png">

There are other things we could learn by studying how these well-designed sites present text heavy articles.  This is just a beginning.

**Comment by aprilllllllll** [comment]
Could I take this issue?

**Comment by humphd** [comment]
Go for it
