### ISSUE TITLE
Add API to storage.js for getting number of feeds and posts in Redis

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#340]
Our storage.js code should make it possible to get the number of feeds and posts in the Redis database:

```
const feedsCount = await storage.getFeedsCount();
...
const postsCount = await storage.getPostsCount();
```

Both of these are implemented as Sets in Redis, and a Redis Set has `SCARD` to determine this, see https://redis.io/commands/scard.

Depends on work happening in #332 right now.

**Comment by mskuybeda** [comment]
I will work on it as discussed in class

**Comment by humphd** [comment]
Please assign yourself when taking issues.  I've done it for you this time, next time you can do it.
