### ISSUE TITLE
Link Docs from Telescope's main page 

### ISSUE THREAD

**Issue by TueeNguyen** [Seneca-CDOT/telescope#3402]
- Our docusaurus just landed in #3400, let's update our web page's nav bar from `About us | Login` to `About us | Docs | Login`
- We can also add it in our [`CONTIBUTING.md`](https://github.com/Seneca-CDOT/telescope/blob/master/src/web/docusaurus/docs/contributing/CONTRIBUTING.md)
- Docs link on staging: https://dev.telescope.cdot.systems/docs/

**Comment by manekenpix** [comment]
Closed via #3538  and #3767.
