### ISSUE TITLE
Use "Telescope Overview" from the docs as our About Us page.

### ISSUE THREAD

**Issue by menghif** [Seneca-CDOT/telescope#3407]
**What would you like to be added**:

As @manekenpix noticed today, our [Telescope Overview](https://dev.telescope.cdot.systems/docs/overview) and [About Us](https://telescope.cdot.systems/about/) page are very similar. It would make sense to remove the "About Us" page and redirect the user to "Telescope Overview".

![image](https://user-images.githubusercontent.com/53121061/161876001-da300036-a789-4a3c-870f-79a53466f2d1.png)

We should bring the recent updates from https://github.com/Seneca-CDOT/telescope/pull/3404 over to "Telescope Overview" as well.

**Comment by sirinoks** [comment]
Our about us is a .tsx on react that also has a star field. Our overview.md is an .md file. There is a current [PR on fixing the starfield](https://github.com/Seneca-CDOT/telescope/pull/3512). We first need to have this land. 

If I understand correctly, we need to move the starfield over to the overview. However, it is an md file, I'm not sure how we would put the starfield there. This might actually seem more difficult than seemed. Plus we have the language select option in the .tsx

Therefore, it's not just text stuff:
- [ ] Merge new About us changes with versioning info from Telescope Overview
- [ ] Remove old About us content
- [ ] Carry over the starfield
- [ ] Carry over the language select functionality
- [ ] Keep in mind to properly carry over React structured content into an .md file (if we even want to use an .md file at this point. Either way, our docasaurus is not on react, so structure changes will be needed either way.)

**Comment by JerryHue** [comment]
> Our about us is a .tsx on react that also has a star field. Our overview.md is an .md file. There is a current [PR on fixing the starfield](https://github.com/Seneca-CDOT/telescope/pull/3512). We first need to have this land.
> 
> If I understand correctly, we need to move the starfield over to the overview. However, it is an md file, I'm not sure how we would put the starfield there. This might actually seem more difficult than seemed. Plus we have the language select option in the .tsx

You are correct, it is not as easy as we might think. [Docusaurus understands `mdx`](https://docusaurus.io/docs/markdown-features/react), which means you can use React-like component in the `md` file. The star field depends on `p5.js`, which means we need to somehow make Docusaurus include that library, and then simply include the `StarField` component in the `mdx` file.

I worked on [something like this before](https://github.com/Seneca-ICTOER/Intro2C/pull/171), and I think I could try to make it happen. I will follow up with a PR.

**Comment by menghif** [comment]
@sirinoks No need to carry over the language select functionality since Docusaurus already has it implemented.
