### ISSUE TITLE
Add RLS for existing Postgres tables

### ISSUE THREAD

**Issue by DukeManh** [Seneca-CDOT/telescope#3408]
We currently have [6 SQL tables](https://dev.supabase.telescope.cdot.systems/project/default/editor) and 4 don't have RLS enabled. To protect our data, we should add RLS to all of them.

For `quotes` table, we should allow read access to everyone and disable update/delete access. 

For how to write RLS, see https://github.com/Seneca-CDOT/telescope/blob/ec33441c3b34a28e5e816ba57103465b546ac4be/docker/supabase/volumes/db/init/04-telescope-schema.sql#L53

**Comment by joelazwar** [comment]
I can take this on

**Comment by DukeManh** [comment]
@joelazwar Please take it.

**Comment by JerryHue** [comment]
I think the policies for the other 3 tables should be read access to everyone, and only allow the `parser` service to use an update/insert/delete access.

**Comment by DukeManh** [comment]
Cool, no need to write tests for these RLS I think.

**Comment by JerryHue** [comment]
Related: #3305
