### ISSUE TITLE
Fix frontend issues uncovered by Webhint

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#342]
The work in #291 added support for [Webhint](https://webhint.io/) reporting.  This gives us insight into frontend web issues with performance, accessibility, security, etc.

I ran it just now using `npm run webhint` and this is what I see:

```
✖ Finishing...
You can view the HTML report in "/Users/humphd/repos/telescope/hint-report/http-localhost-3000/index.html"
http://localhost:3000/
                 Error    'http://localhost:3000/' does not support HTTPS.                                                                                                                                        ssllabs
                 Error    Response should not include disallowed 'x-powered-by' header.                                                                                                                           no-disallowed-headers
                 Error    Response should include 'x-content-type-options' header.                                                                                                                                x-content-type-options
                 Error    Response should be compressed with gzip when gzip compression is requested.                                                                                                             http-compression
                 Warning  'div[dir]' is not supported by Edge, Internet Explorer.                                                                                                                                 compat-api/html
                 Error    '<a class="goog-logo-link" href="https://translat … -right: 3px" alt="Google Translate">Translate</a>' should have 'rel' attribute value include 'noopener' and 'noreferrer' keywords.  disown-opener
                 Warning  'div[dir]' is not supported by Edge, Internet Explorer.                                                                                                                                 compat-api/html
                 Error    Response with status code 404 should have more than 512 bytes.                                                                                                                          no-friendly-error-pages
line 5   col 5   Error    'x-ua-compatible' meta element should not be specified as it is not needed.                                                                                                             highest-available-document-mode
line 28  col 13  Error    Button type attribute has not been set                                                                                                                                                  button-type
line 34  col 13  Error    Button type attribute has not been set                                                                                                                                                  button-type
line 40  col 13  Error    Button type attribute has not been set                                                                                                                                                  button-type
line 46  col 13  Error    Button type attribute has not been set                                                                                                                                                  button-type
line 54  col 17  Error    Form elements must have labels                                                                                                                                                          axe/forms
line 55  col 17  Error    Buttons must have discernible text                                                                                                                                                      axe/name-role-value
line 74  col 7   Warning  Ensure that scrollable region has keyboard access                                                                                                                                       axe/other
✖ Found 13 errors and 3 warnings

http://localhost:3000/style/main.css
                  Error    Static resources should have a long cache value (31536000):
Directives used: public, max-age=0                                                                      http-cache
                  Error    Static resources should use the "immutable" directive:
Directives used: public, max-age=0                                                                           http-cache
                  Error    Response should not include disallowed 'x-powered-by' header.                                                                                                       no-disallowed-headers
line 8    col 5   Error    Response should include 'x-content-type-options' header.                                                                                                            x-content-type-options
line 8    col 5   Error    Response should be compressed with gzip when gzip compression is requested.                                                                                         http-compression
line 27   col 11  Warning  'display: grid' is not supported by Chrome < 57, Internet Explorer. Add 'display: -ms-grid' to support Internet Explorer 10+.                                       compat-api/css
line 28   col 2   Warning  'grid-template-columns' is not supported by Chrome < 57, Internet Explorer.                                                                                         compat-api/css
line 29   col 2   Warning  'grid-template-rows' is not supported by Chrome < 57, Internet Explorer.                                                                                            compat-api/css
line 30   col 2   Warning  'grid-template-areas' is not supported by Chrome < 57, Internet Explorer.                                                                                           compat-api/css
line 38   col 2   Warning  'grid-area' is not supported by Chrome < 57, Internet Explorer.                                                                                                     compat-api/css
line 94   col 2   Warning  'grid-area' is not supported by Chrome < 57, Internet Explorer.                                                                                                     compat-api/css
line 103  col 11  Warning  'display: grid' is not supported by Chrome < 57, Internet Explorer. Add 'display: -ms-grid' to support Internet Explorer 10+.                                       compat-api/css
line 104  col 2   Warning  'grid-template-rows' is not supported by Chrome < 57, Internet Explorer.                                                                                            compat-api/css
line 105  col 2   Warning  'grid-template-areas' is not supported by Chrome < 57, Internet Explorer.                                                                                           compat-api/css
line 113  col 2   Warning  'grid-area' is not supported by Chrome < 57, Internet Explorer.                                                                                                     compat-api/css
line 119  col 12  Warning  'position: sticky' is not supported by Chrome < 56, Internet Explorer, Safari, iOS Safari. Add 'position: -webkit-sticky' to support Safari 6.1+, iOS Safari 6.1+.  compat-api/css
line 130  col 2   Warning  'grid-area' is not supported by Chrome < 57, Internet Explorer.                                                                                                     compat-api/css
line 164  col 4   Warning  'grid-template-columns' is not supported by Chrome < 57, Internet Explorer.                                                                                         compat-api/css
line 165  col 4   Warning  'grid-template-rows' is not supported by Chrome < 57, Internet Explorer.                                                                                            compat-api/css
line 166  col 4   Warning  'grid-template-areas' is not supported by Chrome < 57, Internet Explorer.                                                                                           compat-api/css
✖ Found 5 errors and 15 warnings

http://localhost:3000/dialogue.js
                 Error  Static resources should have a long cache value (31536000):
Directives used: public, max-age=0  http-cache
                 Error  Static resources should use the "immutable" directive:
Directives used: public, max-age=0       http-cache
                 Error  Response should not include disallowed 'x-powered-by' header.                                   no-disallowed-headers
line 299  col 5  Error  Response should include 'x-content-type-options' header.                                        x-content-type-options
line 299  col 5  Error  Response should be compressed with gzip when gzip compression is requested.                     http-compression
✖ Found 5 errors and 0 warnings

http://localhost:3000/img/logo.svg
                Error  'content-type' header charset value should be 'utf-8'.                                          content-type
                Error  Static resources should have a long cache value (31536000):
Directives used: public, max-age=0  http-cache
                Error  Static resources should use the "immutable" directive:
Directives used: public, max-age=0       http-cache
                Error  Response should not include disallowed 'x-powered-by' header.                                   no-disallowed-headers
line 22  col 9  Error  Response should include 'x-content-type-options' header.                                        x-content-type-options
line 22  col 9  Error  Response should be compressed with gzip when gzip compression is requested.                     http-compression
✖ Found 6 errors and 0 warnings

http://localhost:3000/favicon.ico
Error  No "cache-control" header or empty value found. It should have a value  http-cache
Error  Response should not include disallowed 'x-powered-by' header.           no-disallowed-headers
✖ Found 2 errors and 0 warnings

✖ Found a total of 31 errors and 18 warnings
```

Let's see if we can reduce this!

**Comment by cindyledev** [comment]
I got the same error running `npm run hint` on Linux, I don't understand most of the errors XD like what's wrong with our logo and favicon?

**Comment by lozinska** [comment]
Hey, I would like to do investigation on this issue

**Comment by lozinska** [comment]
Hi @humphd ,@robertbenga I'm trying to run `npm run webhint` and it's giving me error (see pic below). 
NOTE: Before I `pull upstreammaster` I was able to generate report.
Question: Is it just me or there were some updates that stop this command from generating report? 
![image](https://user-images.githubusercontent.com/49209351/70157998-828d1680-1684-11ea-8ce0-f6b979035c93.png)

**Comment by humphd** [comment]
Delete your `node_modules` and re-run `npm install` to get all the deps installed properly.  I found just running `npm install` didn't do it.

<details>
<summary>Here is what I get when I do that</summary>
<pre>✖ Finishing...
You can view the HTML report in "/Users/humphd/repos/telescope/hint-report/http-localhost-3000/index.html"
http://localhost:3000/
                 Error              'http://localhost:3000/' does not support HTTPS.                                                                                                                      ssllabs
                 Warning            Response should not include disallowed 'x-powered-by' header.                                                                                                         no-disallowed-headers
                 Error              Response should include 'x-content-type-options' header.                                                                                                              x-content-type-options
                 Error              Response should be compressed with gzip when gzip compression is requested.                                                                                           http-compression
                 Warning            'div[dir]' is not supported by Edge, Internet Explorer.                                                                                                               compat-api/html
                 Error              '<a class="goog-logo-link" href="https://translat … -right: 3px" alt="Google Translate">Translate</a>' should have 'rel' attribute value include noopener keyword.    disown-opener
                 Warning            '<a class="goog-logo-link" href="https://translat … -right: 3px" alt="Google Translate">Translate</a>' should have 'rel' attribute value include noreferrer keyword.  disown-opener
                 Warning            'div[dir]' is not supported by Edge, Internet Explorer.                                                                                                               compat-api/html
                 Hint  Response with status code 404 should have more than 512 bytes.                                                                                                        no-friendly-error-pages
line 5   col 5   Hint  'x-ua-compatible' meta element should not be specified as it is not needed.                                                                                           highest-available-document-mode
line 28  col 13  Hint  Button type attribute has not been set                                                                                                                                button-type
line 34  col 13  Hint  Button type attribute has not been set                                                                                                                                button-type
line 40  col 13  Hint  Button type attribute has not been set                                                                                                                                button-type
line 46  col 13  Hint  Button type attribute has not been set                                                                                                                                button-type
✖ Found 4 errors, 4 warnings, 6 hints and 0 informations

http://localhost:3000/style/main.css
                  Hint  Static resources should have a long cache value (31536000):
Directives used: public, max-age=0                                                                      http-cache
                  Hint  Static resources should use the "immutable" directive:
Directives used: public, max-age=0                                                                           http-cache
                  Warning            Response should not include disallowed 'x-powered-by' header.                                                                                                       no-disallowed-headers
line 8    col 5   Warning            No configured patterns for cache busting match http://localhost:3000/style/main.css. See docs to add a custom one.                                                  http-cache
line 8    col 5   Error              Response should include 'x-content-type-options' header.                                                                                                            x-content-type-options
line 8    col 5   Error              Response should be compressed with gzip when gzip compression is requested.                                                                                         http-compression
line 27   col 11  Error              'display: grid' is not supported by Chrome < 57, Internet Explorer. Add 'display: -ms-grid' to support Internet Explorer 10+.                                       compat-api/css
line 28   col 2   Warning            'grid-template-columns' is not supported by Chrome < 57, Internet Explorer.                                                                                         compat-api/css
line 29   col 2   Warning            'grid-template-rows' is not supported by Chrome < 57, Internet Explorer.                                                                                            compat-api/css
line 30   col 2   Warning            'grid-template-areas' is not supported by Chrome < 57, Internet Explorer.                                                                                           compat-api/css
line 38   col 2   Warning            'grid-area' is not supported by Chrome < 57, Internet Explorer.                                                                                                     compat-api/css
line 94   col 2   Warning            'grid-area' is not supported by Chrome < 57, Internet Explorer.                                                                                                     compat-api/css
line 103  col 11  Error              'display: grid' is not supported by Chrome < 57, Internet Explorer. Add 'display: -ms-grid' to support Internet Explorer 10+.                                       compat-api/css
line 104  col 2   Warning            'grid-template-rows' is not supported by Chrome < 57, Internet Explorer.                                                                                            compat-api/css
line 105  col 2   Warning            'grid-template-areas' is not supported by Chrome < 57, Internet Explorer.                                                                                           compat-api/css
line 113  col 2   Warning            'grid-area' is not supported by Chrome < 57, Internet Explorer.                                                                                                     compat-api/css
line 119  col 12  Error              'position: sticky' is not supported by Chrome < 56, Internet Explorer, Safari, iOS Safari. Add 'position: -webkit-sticky' to support Safari 6.1+, iOS Safari 6.1+.  compat-api/css
line 130  col 2   Warning            'grid-area' is not supported by Chrome < 57, Internet Explorer.                                                                                                     compat-api/css
line 164  col 4   Warning            'grid-template-columns' is not supported by Chrome < 57, Internet Explorer.                                                                                         compat-api/css
line 165  col 4   Warning            'grid-template-rows' is not supported by Chrome < 57, Internet Explorer.                                                                                            compat-api/css
line 166  col 4   Warning            'grid-template-areas' is not supported by Chrome < 57, Internet Explorer.                                                                                           compat-api/css
✖ Found 5 errors, 14 warnings, 2 hints and 0 informations

http://localhost:3000/img/logo.svg
                Warning            'content-type' header charset value should be 'utf-8'.                                                            content-type
                Hint  Static resources should have a long cache value (31536000):
Directives used: public, max-age=0                    http-cache
                Hint  Static resources should use the "immutable" directive:
Directives used: public, max-age=0                         http-cache
                Warning            Response should not include disallowed 'x-powered-by' header.                                                     no-disallowed-headers
line 22  col 9  Warning            No configured patterns for cache busting match http://localhost:3000/img/logo.svg. See docs to add a custom one.  http-cache
line 22  col 9  Error              Response should include 'x-content-type-options' header.                                                          x-content-type-options
line 22  col 9  Error              Response should be compressed with gzip when gzip compression is requested.                                       http-compression
✖ Found 2 errors, 3 warnings, 2 hints and 0 informations

http://localhost:3000/dialogue.js
                 Hint  Static resources should have a long cache value (31536000):
Directives used: public, max-age=0                   http-cache
                 Hint  Static resources should use the "immutable" directive:
Directives used: public, max-age=0                        http-cache
                 Warning            Response should not include disallowed 'x-powered-by' header.                                                    no-disallowed-headers
line 299  col 5  Warning            No configured patterns for cache busting match http://localhost:3000/dialogue.js. See docs to add a custom one.  http-cache
line 299  col 5  Error              Response should include 'x-content-type-options' header.                                                         x-content-type-options
line 299  col 5  Error              Response should be compressed with gzip when gzip compression is requested.                                      http-compression
✖ Found 2 errors, 2 warnings, 2 hints and 0 informations

http://localhost:3000/server-sent-events.js
                 Hint  Static resources should have a long cache value (31536000):
Directives used: public, max-age=0                             http-cache
                 Hint  Static resources should use the "immutable" directive:
Directives used: public, max-age=0                                  http-cache
                 Warning            Response should not include disallowed 'x-powered-by' header.                                                              no-disallowed-headers
line 301  col 5  Warning            No configured patterns for cache busting match http://localhost:3000/server-sent-events.js. See docs to add a custom one.  http-cache
line 301  col 5  Error              Response should include 'x-content-type-options' header.                                                                   x-content-type-options
line 301  col 5  Error              Response should be compressed with gzip when gzip compression is requested.                                                http-compression
✖ Found 2 errors, 2 warnings, 2 hints and 0 informations

http://localhost:3000/favicon.ico
Error    No "cache-control" header or empty value found. It should have a value  http-cache
Warning  Response should not include disallowed 'x-powered-by' header.           no-disallowed-headers
✖ Found 1 error, 1 warning, 0 hints and 0 informations

✖ Found a total of 16 errors, 26 warnings, 14 hints and 0 informations
</pre>
</summary>

<

**Comment by lozinska** [comment]
@humphd thank you. Will do

**Comment by humphd** [comment]
We're going to refactor the frontend and write in Gatsby, so let's close this for now and circle back later.
