### ISSUE TITLE
Search bar button misalignment

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#3426]
**What happened**:
The searchbar UI has changed causing it to look weird.
The search icon button should be centered properly in the input box.

**What should have happened**:

**How to reproduce it (as precise as possible)**:
I am on chrome, and I go to the telescope site. I select to search. 
![image](https://user-images.githubusercontent.com/77639637/162333690-976a162e-e46d-4d12-8ed0-acc56ed6b593.png)

**Anything else we need to know?**:
The height of the input box seems to have changed... so try to revert that, and avoid making the button smaller.
**Environment**:

- OS:
- Browser:

**Comment by AmasiaNalbandian** [comment]
When you type something in the field you also see the font size difference because the outline of the input overlaps the title of the input:
![image](https://user-images.githubusercontent.com/77639637/162334669-4d05e1e2-803f-47cc-a78b-57bf3ae82555.png)


see how "st" from post is overlapped by the navy outline?

**Comment by humphd** [comment]
I filed separate issues on these.
