### ISSUE TITLE
Clearing up Docker disk space for Staging

### ISSUE THREAD

**Issue by rclee91** [Seneca-CDOT/telescope#3440]
ElassticSearch detected low docker disk space (less than 10%) on Staging. 

```
TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block
```
```
{"type": "server", "timestamp": "2022-04-08T20:19:22,337Z", "level": "WARN", "component": "o.e.c.r.a.DiskThresholdMonitor", "cluster.name": "docker-cluster", "node.name": "65500aa47ac8", "message": "high disk watermark [90%] exceeded on [nptVf9UvRMy0HB6-4lcPEg][65500aa47ac8][/usr/share/elasticsearch/data/nodes/0] free: 2.8gb[7.4%], shards will be relocated away from this node; currently relocating away shards totalling [0] bytes; the node is expected to continue to exceed the high disk watermark when these relocations are complete", "cluster.uuid": "auVH-cD4QSm7Dqu150atQQ", "node.id": "nptVf9UvRMy0HB6-4lcPEg"  }
```

`Parser` is currently paused on `Staging`, under the original assumption that it and `backend` may be creating duplicate indexes. 

However, it seems ES might not be the one hogging all the disk space, just the one who can detect it, and the issue may be with our docker cleanup strategy. 

Currently, we'd need to manually clean up our docker disk space. 
If @manekenpix could help with that when he's free, that'll be awesome. 

After the cleanup, @humphd or someone will have to re-enable `Parser` on `Staging` again.

**Comment by humphd** [comment]
It looks like this was done (I assume by @manekenpix--thank you!).  Closing.
