### ISSUE TITLE
Fix padding around search button

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3442]
The padding around the search button isn't uniform anymore:

<img width="167" alt="Screen Shot 2022-04-08 at 7 03 59 PM" src="https://user-images.githubusercontent.com/427398/162544749-5fbd475e-2fa7-4640-893f-8a853d2f9f08.png">

**Comment by DukeManh** [comment]
On mobile
![image](https://user-images.githubusercontent.com/51073515/162582531-4e7c3219-c654-42b5-9bb1-fd860b0d604e.jpeg)
