### ISSUE TITLE
Search label text cut off

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3443]
In the [search page](https://telescope.cdot.systems/search/), when the text moves to be a label, it gets cut off (not enough width?):

<img width="160" alt="Screen Shot 2022-04-08 at 7 05 16 PM" src="https://user-images.githubusercontent.com/427398/162544848-9e33332d-187c-4f29-abaa-2ed9db7f1ed1.png">

**Comment by humphd** [comment]
Same happens for title of post:

<img width="170" alt="Screen Shot 2022-04-08 at 7 07 09 PM" src="https://user-images.githubusercontent.com/427398/162544938-474b3ea7-e58a-4bf4-8ae0-75e2838730eb.png">

**Comment by AmasiaNalbandian** [comment]
The error here is from the fact that the text size of the input and the label are wrong. Just make sure in the CSS they are both the same text size, even one px misaligns it

**Comment by humphd** [comment]
@Kevan-Y's fix in #3487 has this same problem:

<img width="770" alt="Screen Shot 2022-04-14 at 3 36 08 PM" src="https://user-images.githubusercontent.com/427398/163463413-d62c287f-262b-4387-aa7e-da5c0c37110c.png">
