### ISSUE TITLE
Improve styling of autocomplete results

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3444]
<img width="803" alt="Screen Shot 2022-04-08 at 7 07 59 PM" src="https://user-images.githubusercontent.com/427398/162545004-cc8bac1d-eb1a-4319-83b6-f73ba48fa7cf.png">

- Use a background colour that won't show (e.g., white on light theme)
- Use the same fonts as the rest of the site

Also consider adding a border that links it all together.  Here's how Google does it:

<img width="615" alt="Screen Shot 2022-04-08 at 7 10 14 PM" src="https://user-images.githubusercontent.com/427398/162545106-f1c16a2e-7383-48e3-812f-ed00ef5fae34.png">

**Comment by DukeManh** [comment]
On mobile
![image](https://user-images.githubusercontent.com/51073515/162582549-0bbc8616-363e-4a70-aae9-f9967393a096.jpeg)
