### ISSUE TITLE
Documentation link points to Docusaurus

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3445]
On https://telescope.cdot.systems/docs/ in the bottom-right, the Documentation link is pointing to Docusaurus.  Let's point back to our docs:

<img width="180" alt="Screen Shot 2022-04-08 at 7 12 32 PM" src="https://user-images.githubusercontent.com/427398/162545237-277b2157-45ba-4bd7-abdd-f9e189bdcef2.png">

**Comment by DiegoHdz7** [comment]
Hi, I would like to take this issue for the hacktoberfest, can I take it?

**Comment by humphd** [comment]
@DiegoHdz7 finish the other one first.  We only do 1 issue per person at a time.

**Comment by mnosov622** [comment]
Hi @humphd !

Can you assign this issue to me, please ? I would love to work on it as my first issue for hacktoberfest :)

**Comment by humphd** [comment]
@mnosov622 all yours!
