### ISSUE TITLE
Update `Feed` in `parser` service to talk to Supabase instead of Redis

### ISSUE THREAD

**Issue by TueeNguyen** [Seneca-CDOT/telescope#3464]
In #1907 #3355, we talked about removing feed-related code in Posts. 

- [ ] Change `setInvalidFeed` function to use Supabase https://github.com/Seneca-CDOT/telescope/blob/d56306a75f25622176a18730246f9ffbf588a046/src/api/parser/src/utils/storage.js#L111-L115

- [ ] https://github.com/Seneca-CDOT/telescope/blob/d56306a75f25622176a18730246f9ffbf588a046/src/api/parser/src/utils/storage.js#L137-L139

**Comment by JerryHue** [comment]
There's also this:

> * The parser service does not need to `updateFeed`s anymore. Refer to:
> https://github.com/Seneca-CDOT/telescope/blob/d56306a75f25622176a18730246f9ffbf588a046/src/api/parser/src/parser.js#L48
> https://github.com/Seneca-CDOT/telescope/blob/d56306a75f25622176a18730246f9ffbf588a046/src/api/parser/src/parser.js#L12-L28
>

**Comment by TueeNguyen** [comment]
I'm working on this issue to make parser save flagged feeds to supabase (simply change `flagged` of `feed` to true/false). I encountered this piece of code

https://github.com/Seneca-CDOT/telescope/blob/47fd69e62a3d2a85a1950f841fb74a5ca504217b/src/api/parser/src/utils/storage.js#L53
I will also need to change this line if I'm removing all the redis flagging feed code, something like this 
```js
if (await isFlaggedFeed(feed.id)) // isFlaggedFeed() is function that uses supabase
  return; 
```
Therefore, the test won't pass and there's no mock cilent for supabase at the moment. Not sure what's the next step is

**Comment by humphd** [comment]
Mock the `isFlaggedFeed()` function to return `Promise.resolve(true)` or `Promise.resolve(false)` as you require in your tests.

**Comment by TueeNguyen** [comment]
I'll try, thanks

**Comment by TueeNguyen** [comment]
After looking at the function 
https://github.com/Seneca-CDOT/telescope/blob/9ec0cf0c6ab9ecb54a7d96a264d86c5d013782ed/src/api/parser/src/parser.js#L12-L28
I believe we can keep it as it looks for feed object in Redis not in Supabase.
