### ISSUE TITLE
Create GitHub templates for pull requests and issues

### ISSUE THREAD

**Issue by RyanMarzec** [Seneca-CDOT/telescope#347]
As discussed in class about pull requests without enough details,  I was thinking it would be a good idea to create a pull request template for the repo. I think this could help reduce review time for both the contributor and reviewer. 

I believe since this project will be continuously worked on by new students who may have no open-source background as we did at the beginning of the course it could also help set a standard for what a proper pull request should look like and contain for contribution to external projects as well.

it could include things such as:
description - what/why/type of change
A checklist - quality/style/comments/tests

**Comment by humphd** [comment]
This is a great idea.  See [docs](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) from GitHub on how to do it.

**Comment by Grommers00** [comment]
Perhaps this could be done for issues as well?

**Comment by humphd** [comment]
Great idea, updated the title.

**Comment by manekenpix** [comment]
I think Kubernetes has [good templates](https://github.com/kubernetes/kubernetes/issues/new/choose), we could try to come up with something similar.

**Comment by UltimaBGD** [comment]
Can we break this down into two separate PR's? PR's and Issues likely won't have the same template, and I would like to try my hand at making a template for one of them.

**Comment by humphd** [comment]
@UltimaBGD sure, just do it.

**Comment by Grommers00** [comment]
@UltimaBGD @RyanMarzec Can we perhaps create them in sync so that way they kind of feed into each other opposed to two seperate templates that do not talk to each other or have similar layouts.

**Comment by cindyledev** [comment]
@manekenpix I really like Kubernetes' issue templates too

**Comment by RyanMarzec** [comment]
@UltimaBGD you can definitely help out, but I agree with @Grommers00, we should come together and make sure that we follow the same layout for every template.

**Comment by UltimaBGD** [comment]
Right, that was always the intent!

**Comment by UltimaBGD** [comment]
As for Kubernetes templates, the issue one is almost perfect, with maybe just a few modifications to the environment section as not everything there applies. The PR template has type tagging, which would be good in standardizing the use of those. We could also add a section about if the new code has tests running for it already.

**Comment by shmooey** [comment]
I'm late, but Home Assistant has a pretty good PR template with fixed issue #, description and a checklist to confirm tests have been ran

**Comment by RyanMarzec** [comment]
ignore 77e394. 
@humphd @UltimaBGD @Grommers00 @manekenpix. I started first draft of the pull request template and just wanted some input on what I currently have, let me know if you think anything should be changed/added/removed. 
or @ anyone you think might have good input to add!

Thanks

**Comment by UltimaBGD** [comment]
Okay, I will follow suit with one in a similar format for issues shortly.

**Comment by UltimaBGD** [comment]
My apologies, misclicked.
