### ISSUE TITLE
Update logo link to Seneca-CDOT's GitHub Repository

### ISSUE THREAD

**Issue by brucremo** [Seneca-CDOT/telescope#348]
The link to the image on our Readme.md still points to my GitHub repo, this needs to be fixed in order to maintain consistency of the repo's assets

**Comment by brucremo** [comment]
Addressed via the [pull request #349 ](https://github.com/Seneca-CDOT/telescope/pull/349)

**Comment by kartik-budhiraja** [comment]
Closed through #351.
