### ISSUE TITLE
[dependency-discovery] - Add a field for GitHub issue URL in /projects/:namespace/:name route

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-CDOT/telescope#3495]
In our dependency-discovery services, It would be nice to have a field for the GitHub issue URL in the return JSON of `/projects/:namespace/:name` route.
So in our front-end, we do not have to construct this URL.

The URL should be the Github issues that filter open issues and with the label `hacktoberfest` or `good first issue` or `help wanted`

**Comment by humphd** [comment]
I think it's better to do this in the front-end, so we don't get throttled in the backend.  However, I think we should construct and return that URL in the JSON response, so the front-end can use it without constructing it.
