### ISSUE TITLE
Add logging support to our backend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#35]
Let's do proper logging for everything in the back-end using [Pino](http://getpino.io/#/).  Ideally, I'd like to see us logging things for regular operations, errors, but also offer debug logs to help developers see what's going on.

We can roll this out in stages, but it would be good to add initial logging support with at least INFO or ERROR levels.

**Comment by hansal7014** [comment]
Hi @humphd,
I would like to work on this issue.

**Comment by humphd** [comment]
Awesome @hansal7014, go for it!
