### ISSUE TITLE
Automate dev environment for parser to run normally

### ISSUE THREAD

**Issue by TueeNguyen** [Seneca-CDOT/telescope#3526]
Refer to this comment https://github.com/Seneca-CDOT/telescope/pull/3413#pullrequestreview-947240607

With our changes to Supabase/Prisma migrate. We need to automate these steps to seed the feeds for `Parser` to work in development mode
```bash
pnpm services:start
cd src/db
cp env.example .env
pnpx prisma migrate dev
cd ../../tools/migrate
cp env.example .env
pnpm to_supabase
```

**Comment by humphd** [comment]
I think we should consider eliminating the "download from wiki" step in the migration tools.  We aren't going to care about the wiki, but we'll want that data.

Maybe we can run that script, capture the output we have now, and then put the sql file into the repo to be run as part of this.
