### ISSUE TITLE
Improve CSS in dependencies page 

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-CDOT/telescope#3535]
After the dependencies page was added in this https://github.com/Seneca-CDOT/telescope/issues/3357. We can improve on the CSS to make some part stands out more.

Dependencies page: https://dev.telescope.cdot.systems/dependencies/

Example of possible CSS fix:
- Slightly different color (Make it stand out)
- Change the font 
- Adjust font-size

**Comment by Eakam1007** [comment]
Hi, I would like to work on this.
Did you have something specific in mind? I am thinking of improving the CSS for the dependency names

**Comment by humphd** [comment]
@Eakam1007 assigned to you.

cc'ing @JerryHue as well for thoughts.

**Comment by RC-Lee** [comment]
Please fix the lines in dark mode while you're at it too (maybe make it lighter?). 
I seem to get a headache when I scroll too quickly
Much appreciated!
![image](https://user-images.githubusercontent.com/32626950/194168240-ca2435ea-a269-4fb1-bc87-efa62baa52ef.png)
