### ISSUE TITLE
Fix planet when starting docker containers

### ISSUE THREAD

**Issue by JerryHue** [Seneca-CDOT/telescope#3537]
If you start all of the services with `pnpm run services:start`, you will also start up `planet`.

However, there are some configuration issues related to the `planet` container, since accessing it through `localhost:9876/planet` gives some errors.

A few hints:

- one error (`ECONNECTIONREFUSED` when connecting to `supabase`) is due to the `SUPABASE_URL` being pointing to `localhost/v1/supabase` (picked up from the `.env` file). We want to point to `http://kong:8000`, written directly in the `docker/development.yml` file.
- another error (`ECONNECTIONREFUSED` when connecting to `posts` service), may be to a similar issue.

**Comment by manekenpix** [comment]
Closing since the planet service was removed in #3804
