### ISSUE TITLE
Updating the login button to point to the saml2 server

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#354]
Once issue #287 is set up, we will need to update the login button to point towards the saml2 server. 

This can be set up to be hard coded at first, but will eventually need to take use of the process.env variables.

**Comment by agarcia-caicedo** [comment]
I'll work on it

**Comment by Grommers00** [comment]
@agarcia-caicedo as soon as issue #319 lands, we can continue with this process. 

https://medium.com/disney-streaming/setup-a-single-sign-on-saml-test-environment-with-docker-and-nodejs-c53fc1a984c9

We will keep going through this.

**Comment by agarcia-caicedo** [comment]
e6224e337d74c7b2357e2af96183849e3092097e
