### ISSUE TITLE
Rework SVG in Docusaurus home page to be responsive

### ISSUE THREAD

**Issue by JerryHue** [Seneca-CDOT/telescope#3545]
In #3486, we got a beautiful looking art for the Telescope docs home page. There are a few things we would like to fix:

- Remove all white space,
- Resize or rework the svg to make the page shorter,

https://user-images.githubusercontent.com/58532267/164485931-d48b0ab0-5e25-4ba8-8d1d-c8b6adf215a5.mp4

_Originally posted by @TueeNguyen in https://github.com/Seneca-CDOT/telescope/pull/3486#pullrequestreview-948764864_

**Comment by sirinoks** [comment]
SVG is 16:9 currently, so hopefully there is no need to change it. It's pretty tedious to edit the svg. But if it's needed, I can make other resolution versions
