### ISSUE TITLE
db-migration container can get into a loop

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3559]
I notice that we have a `migration` container on production that's running and stuck in a loop:

```
[..................] \ : WARN using --force Recommended protections disabled.
[..................] \ : WARN using --force Recommended protections disabled.
[..................] \ : WARN using --force Recommended protections disabled.
[..................] \ : WARN using --force Recommended protections disabled.
```

We should figure out why, since this can't be good.

cc @TueeNguyen, @DukeManh.

**Comment by humphd** [comment]
I've stopped and removed the `migration` container.

**Comment by humphd** [comment]
Did this container get started with `restart: always` or something?  I'm not clear why this would re-run the migration over and over.

Also, our docs should probably emphasis the need to stop/remove the container when done.  I think they do, but that seems to have been missed here, so maybe it's not clear.

**Comment by TueeNguyen** [comment]
I'm pretty sure, I've removed the container when I finished doing the migration. The restart policy by default is also `Never`

**Comment by DukeManh** [comment]
Sorry, I made it unless-stopped last night so it doesn't exit while I'm testing.
