### ISSUE TITLE
Rename files in src/feed/ to drop feed- prefix

### ISSUE THREAD

**Issue by miggs125** [Seneca-CDOT/telescope#359]
I've noticed under the feed folder, we have three different modules worker, queue and parser. Perhaps we can create an index.js module under src/feed/ that imports all feed-* files and exports all of them under one module. This way we only have to ``` require('./src/backend/feed') ``` once while having access to all feed related functionality.

**Comment by miggs125** [comment]
@humphd ^

**Comment by humphd** [comment]
I would leave them separate, but drop the `feed-` prefix from all of them, so we have `src/backend/feed/parser`, `src/backend/feed/worker`, and `src/backend/feed/queue`.

**Comment by drwm-base** [comment]
I would like to work on this

**Comment by manekenpix** [comment]
Closed via #360
