### ISSUE TITLE
Announce Sign-Ups in Slack

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3604]
When a new user signs up on Telescope, get a bot to announce it in a new `#telescope-bot` channel.

**Comment by SerpentBytes** [comment]
@humphd, may I work on this for 0.4?

**Comment by humphd** [comment]
Sure.  I think @manekenpix has done some similar work with respect to our builds.

**Comment by SerpentBytes** [comment]
@humphd, thanks. I will contact @manekenpix if the need arises. 🙂
