### ISSUE TITLE
Fix all log.error() calls to include full error object + message

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#361]
We have a bunch of cases [where we call `log.error`](https://github.com/Seneca-CDOT/telescope/search?q=log.error&type=Code) with our Pino logger. Sometimes we log a message, sometimes a string, sometimes the error itself.

We should be doing something like this:

```js
...function fooBar(err) {
  if(err) {
    log.error({ err }, 'Some helpful info about what this error means');
    ...
}
```

This way we'll get an error message, some info from our program, and also a full call stack.  This is critical for debugging, especially in production.  You can see an example where this burned us in https://github.com/Seneca-CDOT/telescope/pull/341#issuecomment-558868965

**Comment by SeanPrashad** [comment]
Looks like we have the following `log.error()` calls in the codebase at the moment:

```sh
test/basic_analysis.test.js
21:  log.error(err);

src/backend/index.js
54:    log.error('unable to read initial list of feeds', err.message);
67:      log.error(error);

src/backend/lib/queue.js
34:      log.error(`Queue ${name} error:`, error, ' Stack: ', error.stack);
59:      log.error(`Job ${job.id} failed:`, err);

src/backend/utils/inactive-blog-filter.js
79:      log.error('unable to read initial list of feeds, cannot update', err.message);
134:            log.error('unable to write to feeds-redlist.json, cannot update', err.message);

src/backend/utils/count-blog-domain.js
59:        log.error(err);

src/backend/utils/email-sender.js
37:        log.error(error);
```
