### ISSUE TITLE
Sign-up flow fetched Twitch links are incorrect

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#3610]
**What would you like to be added**:
Change the links for twitch to be correct when they are fetched. The twitch link is not from telescope. 

![image](https://user-images.githubusercontent.com/77639637/168726199-c5deb1d2-08be-48d6-9555-b482a56431d3.png)

**Why would you like this to be added**:
It is confusing. You are asking the user to confirm the link but you provide an incorrect one.

**Comment by SerpentBytes** [comment]
@AmasiaNalbandian  I would like to work on this issue, please assign it to me.

**Comment by cychu42** [comment]
Hi, is this still being worked I? May I take it?

**Comment by SerpentBytes** [comment]
@cychu42  I am unassigning myself from this issue, as I have a backlog of stuff to work on. Sorry!

**Comment by cychu42** [comment]
No problem. I can take over then!

**Comment by manekenpix** [comment]
@cychu42 all yours.

**Comment by cychu42** [comment]
Thanks.

**Comment by cychu42** [comment]
@SerpentBytes Just in case, if you want to send me code you have done or there something I should know about, let me know. 👍
