### ISSUE TITLE
Sign-up flow confirmation page has overflow

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#3611]
**What happened**:
There is overflow in the confirmation page for the sign-up flow
![chrome_Xcc4I4UEmW](https://user-images.githubusercontent.com/77639637/168727012-bfb2d39a-a03b-4fb5-b39d-9b09ca0a2abb.png)

**What should have happened**:
Remove the overflow or handle it. 

**How to reproduce it (as precise as possible)**:
Complete sign up link  and get to the confirmation page.

**Comment by cypersii** [comment]
Shall i work on this issue?

**Comment by humphd** [comment]
By all means, @cypersii.

**Comment by sirinoks** [comment]
To make this issue hacktoberfest ready, the following needs to be improved:
- Where is this page/issue located? (link on the website; location in the code)
- Clean up issue text

**Comment by AmasiaNalbandian** [comment]
> To make this issue hacktoberfest ready, the following needs to be improved:
> 
> * Where is this page/issue located? (link on the website; location in the code)
> * ~Clean up issue text~

The file to change can be found here: 
https://github.com/Seneca-CDOT/telescope/blob/master/src/web/app/src/components/SignUp/Forms/Review.tsx

**Comment by humphd** [comment]
@DiegoHdz7 sure, go for it.

**Comment by DiegoHdz7** [comment]
can I work on this issue for Hacktober fest?

**Comment by cychu42** [comment]
Hello, it seems no one is working on this issue. Maybe I take it?

**Comment by manekenpix** [comment]
@cychu42 all yours!

**Comment by cychu42** [comment]
I managed to find that the long RSS URL at the bottom is the culprit, so I added `word-break: 'break-word'` to the CSS for `blogRSS` class div, which solves the overflow issue presented. 

However, I'm not sure how to make the `container` class div(the one with blue background) auto adjust in case the user wants to add more than 1 of those long RSS. As you can see, the second Twitch URL is overlapping with the buttons.
![review_page](https://user-images.githubusercontent.com/83015577/197864314-7c1cda41-830b-449c-81e3-9755c58d03c0.JPG)

I can just set the height to bigger...but I doubt it’s a good solution.

**Comment by humphd** [comment]
cc @PedroFonsecaDEV.  Maybe we should use trailing ellipses `...` to shorten it, and show the whole thing on hover?

**Comment by cychu42** [comment]
My first thought was making a scrollable box, but the ellipses idea would look way better.
I can try to implement the idea and make a PR for further review.
