### ISSUE TITLE
User name covers tooltip when hovering over user's avatar.

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#3614]
When signed in, hovering over a user's avatar in the banner buttons displays the user name covering the tooltip from `ButtonTooltip`. We can probably display the tooltip **outside** the user's avatar, as we do in our `NavBar`.

`BannerButtons`
![image](https://user-images.githubusercontent.com/23108901/168928793-8a091ada-901f-4219-8592-a6c959efd804.png)

`NavBar`
![image](https://user-images.githubusercontent.com/23108901/168930183-cf53d9a6-8b67-465f-b94e-53865e52fce6.png)

**Comment by SerpentBytes** [comment]
@sirinoks @humphd  I am working on this issue for Hactoberfest. Can one of you please assign it to me?
