### ISSUE TITLE
Running "npm start" causes error, start script doesn't seem to be pointing to the right path

### ISSUE THREAD

**Issue by lucacataldo** [Seneca-CDOT/telescope#362]
Not sure if this is an issue with my current system / setup, but it looks like the npm start script is pointing to /src which is not where the index.js entry point is located. The start script in package.json currently reads:
`node src`

It looks like it should be 
`node src/backend`

Again, I could be wrong but the above fix seems to work for me.

Steps to reproduce:

1.  Clone repo
2.  Run npm install
3.  Run npm start

Output:
![image](https://user-images.githubusercontent.com/35984346/69778088-03be4800-1171-11ea-96ee-389a2b87c332.png)

**Comment by humphd** [comment]
Thanks for filing, @lucacataldo.  It looks like this got lost in a rebase during https://github.com/Seneca-CDOT/telescope/commit/3cd0686db1b7e99c9250939d359b1e9aa2c44db7.  cc @lozinska.

We really need to add a test to make sure that `npm start` works.

**Comment by humphd** [comment]
I filed a new issue on adding a test for this, #363

**Comment by cagomezr** [comment]
working on it

**Comment by humphd** [comment]
Fixed by #364.
