### ISSUE TITLE
Add test to make sure our app starts

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#363]
We broke `npm start` recently (#362), and one of the problems here is that we have no test to check if our app works or not.

Let's add a test using Let's add a test for this using https://www.npmjs.com/package/start-server-and-test to make sure that `npm start` a) works; and b) allows us to hit a route (e.g., get the home page at `/`).

**Comment by evlnyng** [comment]
I would like to work on this one.
