### ISSUE TITLE
Remove reference to `localhost:3000/posts` in Environment Setup docs

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#3656]
**Where is the problem?**

- [x] Link **comment/file/somewhere else**
- [ ] Screenshot

**What exactly is wrong:**
https://github.com/Seneca-CDOT/telescope/blob/07e530a0132d9a756ae962340a1c60b2c03c5735/src/web/docusaurus/docs/getting-started/environment-setup.md?plain=1#L265

We got rid of the backend and we're using the Posts microservice now so `localhost:3000/posts` will not show you the list of posts in JSON

**What should it be instead:**
This needs to be changed from
`Then visit localhost:8000 in a web browser to see Telescope running locally. localhost:3000/posts will show you the list of posts in JSON`

to

`Then visit localhost:8000 in a web browser to see Telescope running locally.`

**Comment by dhruvdabhi101** [comment]
I would like to take this issue .
