### ISSUE TITLE
Create a React Component Hierarchy for Next.js Frontend

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#3657]
I've been reading [Learning Patterns by Lydia Hallie and Addy Osmani](https://ia902209.us.archive.org/4/items/learning-patterns/learning-patterns-v1.1.pdf), and I would really like to have a visual diagram or something similiar to show how our components are broken up. There is barely any documentation on our frontend other than the fact that we're using Next.js, and it's hard to jump into.

We should break our frontend UI into a hierarchy similar to this example

![2022-09-15 11_22_35-learning-patterns-final-v1 1 - Brave](https://user-images.githubusercontent.com/36822198/190443575-5ddb43d3-9e82-48ad-9966-367148cc9924.png)

![2022-09-15 11_23_18-learning-patterns-final-v1 1 - Brave](https://user-images.githubusercontent.com/36822198/190443591-a88deb42-3e37-476b-b701-4dcd58f0f98a.png)

[The Best Approach to Design React Component](https://medium.com/javascript-essentials/the-best-approach-to-design-react-component-hierarchy-978bb152dbb2) is another approach as well. It can't hurt to have both

**Comment by cindyledev** [comment]
I'm assigning myself, but I'm also willing with other collaborators. This issue is mainly creating a React component hierarchy in it's current state but we can do better, there is room for improvement and any input/feedback is welcomed

**Comment by sirinoks** [comment]
> I'm assigning myself, but I'm also willing with other collaborators. This issue is mainly creating a React component hierarchy in it's current state but we can do better, there is room for improvement and any input/feedback is welcomed

I am interested and curious about this, but I don't fully understand it. Do you think we could have a call or something about this? Once I get it, I definitelly can contribute

**Comment by humphd** [comment]
I don't think this is going to happen.  Closing for now, someone who actually wants to do it can re-open.
