### ISSUE TITLE
`About Us` button in all environments redirect to the Docusaurus site in staging

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#3658]
**What happened**:
![2022-09-15 11_38_10-Telescope - Brave](https://user-images.githubusercontent.com/36822198/190447288-cc2a549a-a7eb-42fb-beb1-2c977029a084.png)
The `About Us` button in development, staging, and production all redirect to `https://dev.telescope.cdot.systems/docs/overview/`

**What should have happened**:
The button should not redirect to a static URL.

- In development, the button should redirect to `http://localhost:8000/docs/overview`
- In staging, the button should redirect to `https://dev.telescope.cdot.systems/docs/overview/`
- In production, the button should redirect to `https://telescope.cdot.systems/docs/overview/`

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by cindyledev** [comment]
Perhaps we should consider renaming the button to `DOCS`

**Comment by HyperTHD** [comment]
Technically speaking, the page still is an overview about Telescope and what it's about. I think the name should be still the same

**Comment by TueeNguyen** [comment]
How about both `About Us/Docs`
