### ISSUE TITLE
[Preemptive] CSS issues with real-world blog post elements and content

### ISSUE THREAD

**Issue by lucacataldo** [Seneca-CDOT/telescope#366]
Once #346 gets merged, we will see some sample posts being rendered with real-world blog content on the front-end. While working on this, I came across some issues with the CSS where titles would overflow, responsive views weren't optimized and various other smaller fixes to the UI that could use some polishing. In the review, others made a valid point that these fixes shouldn't be included in that PR. Since I've got a lot of fixes to these little UI bugs ready to go, I figured I'd put up an issue so that the same work isn't done twice when the code is merged.

Specifics:

- Mobile view post header is broken with longer titles
- Images can cause overflow
- `<ol>` and `<ul>` can overflow the `<article>` container
- Whitespace can overflow the body, meaning that horizontal scroll bars appear when they shouldn't
- Google Translate toolbar is awkwardly placed
- Search bar button renders improperly
- Various smaller CSS fixes

**Comment by miggs125** [comment]
Hey @lucacataldo, we've decided to go a different direction so we will be closing this issue. Feel free to checkout our open issues and contribute there :)
