### ISSUE TITLE
Add Logging for the Feed parser

### ISSUE THREAD

**Issue by cagomezr** [Seneca-CDOT/telescope#367]
The Feed parser  doesn't  provide us with   a lot of  feedback,  it be very useful to  have a way to get a log of where failures happened so that we can review later.

**Comment by giatuongtran9** [comment]
I can give it a try.

**Comment by PavanKKamra** [comment]
Hello, I would like to attempt to try this issue!

**Comment by humphd** [comment]
I'm doing this, closing.
