### ISSUE TITLE
Translate about page to Mandarin

### ISSUE THREAD

**Issue by sirinoks** [Seneca-CDOT/telescope#3686]
Related to: #2962 
If you would like to contribute to our translations, please visit the above issue and comment with the language you wish to translate in! (provided it isn't taken yet)

Translate About us page from English to Mandarin

**Comment by cychu42** [comment]
Please assign this to me. Thank you!

**Comment by cychu42** [comment]
I just thought of something.
While I primarily use traditional Chinese myself, I can also read simplified Chinese. Therefore, I can easily make two versions for Mandarin with a conversion tool, like a conversion feature in LibreOffice (open source), and some double-checking on my part.
Would using LibreOffice (or other tools you want me to use instead) pose any issue legally?
Also, would the two versions require two separate issues? Traditional Chinese and simplified Chinese are essentially just two ways of writing the same words.

**Comment by humphd** [comment]
Assigned.  I would suggest doing these one at a time, in two different PRs.

You can use any tool you want, it doesn't matter.  Ideally you won't use machine translation, as that will often produce non-idiomatic language.  But it's also fine to consult it.

**Comment by cychu42** [comment]
That makes sense. I think it's better for me to stick to traditional Chinese. I'm worried I would miss certain phrasing or terminologies that are more natural to cultures that use simplified Chinese.

When I translate, I'll try my best to stick to the wording and definitely the meaning.
Do I have permission to take small liberty with some phrases so it sounds less weird and robotic? Or should this be 100% direct translation?

**Comment by cychu42** [comment]
For the current draft, I stick closely to what's written in English, unless the sentence structure or the literal translation of words don't really make sense or is rather awkward to native speakers.
