### ISSUE TITLE
Auto-select feed in sign-up if only one is available

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3687]
When a user goes through our sign-up process, one of the steps is to enter their Blog URL, and we return a set of possible Feed URLs from the feed-discovery service.  If the length of the possible feed URLs is 1, let's automatically select it and move forward to the next step, since there's nothing more for the user to do.

**Comment by Eakam1007** [comment]
This sounds interesting; I would like to work on it

**Comment by humphd** [comment]
Great, thank you!  Let us know when you need help.

**Comment by Eakam1007** [comment]
Hey, @humphd I noticed that the user needs to declare that they are the owner of the blog before they can move on to the next step. So, if there is only one feed, should it be limited to auto selecting it or should it also move to the next step ignoring this declaration?
<img width="600" alt="image" src="https://user-images.githubusercontent.com/67077705/199123445-25834103-6049-4845-88b3-1cbc331c3fe1.png">

**Comment by humphd** [comment]
I think the declaration is separate from picking the single feed.
