### ISSUE TITLE
Skip returning irrelevant feeds from feed-discovery service

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3688]
When we query the feed-discovery service for a blog's feed URLs, some hosts return feeds for things like comment feeds (I think Medium and WordPress, but need to confirm).  We never want to include these, so it would be good to add special cases to the feed-parser to filter out those particular feed patterns.

The main blog hosts we see people using are:

- dev.to
- medium.com
- blogspot.com
- wordpress.com

There are likely others, but this is the main list.  Let's look at what each of these returns for feeds for a given blog, and write rules to strip out the feeds we know we don't want.

**Comment by Eakam1007** [comment]
Hi, I would like to work on this

**Comment by manekenpix** [comment]
@Eakam1007 :+1:
