### ISSUE TITLE
[Meta] Node.js 12 runtime End-Of-Life (EOL) reached on April 30, 2022

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#3710]
**What happened**:
Node.js 12 runtime has hit its End-Of-Life. This means it is no longer being maintained and does not receive critical bug fixes and security updates. The Active LTS is Node.js 16, so we should update our packages that specify the engine

```diff
-"node": ">=12"
+"node": ">=16"
```

- [x] #3711
- [x] #3712 
- [x] #3713 
- [x] #3714 
- [x] #3715 
- [x] #3716 
- [x] #3717

Node.js 14 is in Maintenance, so we could update the following package.json as well:
- https://github.com/Seneca-CDOT/telescope/blob/06100a722c4077157e0844be93610bd9907972dd/package.json#L89
- https://github.com/Seneca-CDOT/telescope/blob/06100a722c4077157e0844be93610bd9907972dd/src/api/parser/package.json#L40
- [x] #3727 
- https://github.com/Seneca-CDOT/telescope/blob/06100a722c4077157e0844be93610bd9907972dd/src/web/docusaurus/package.json#L63

**What should have happened**:
We should make sure our microservices runs as expected with Node.js 16. Most of our Dockerfiles already use `node:16` or `node:lts` as its base so I don't think we need to make any changes there

Our CI tests also do not rely on Node.js 12 so we're good on that front as well.

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by AmasiaNalbandian** [comment]
@cindyledev Did we get all of these? I think there's one points missing for package.json in root folder of Telescope right?

**Comment by HyperTHD** [comment]
> @cindyledev Did we get all of these? I think there's one points missing for package.json in root folder of Telescope right?

The root package.json is using node ver-14. To remain consistent, should also be upgraded too. Just my thought

**Comment by humphd** [comment]
Closing in favour of #3721.
