### ISSUE TITLE
Feature Request: Add pre-defined themes user can select

### ISSUE THREAD

**Issue by SerpentBytes** [Seneca-CDOT/telescope#3719]
**What would you like to be added**:

***(This is more than toggling Dark mode on and off)***

A drop-down to select a theme from a list of built-in themes. Selecting an option from the drop-down will render the application using the CSS styles associated with the chosen theme. The selected theme will be persisted so that when the user signs in again, they do not have to re-select the theme from the drop-down.

**Why would you like this to be added**:

An increasing amount of web applications and tools are now allowing users to customize the appearance by going to the "settings" and selecting a theme from a list. Some popular web apps/services include StackOverflow and GitHub.

GitHub offers some great customization options:

<img width="707" alt="Screen Shot 2022-10-14 at 11 20 13 PM" src="https://user-images.githubusercontent.com/50856799/195966673-132007c6-ec90-4c7c-afb6-bf33ca3c7d9f.png">

**Comment by humphd** [comment]
Make sure our current theme code can handle this.  Getting the light/dark stuff to work was non-trivial as I recall.
