### ISSUE TITLE
Satellite Service needs to be upgraded from Node.js 14 to Node.js 16

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#3727]
**What happened**:
In #3726 We updated the express dep in our Planet service from v4.17.3 to v4.18.2. We need to do the same for Satellite

Please upgrade the Satellite Service from Node.js 14 to Node.js 16. Make sure the service runs as expected using Node.js 16. This may or may not be a one-line fix.

https://github.com/Seneca-CDOT/telescope/blob/06100a722c4077157e0844be93610bd9907972dd/src/satellite/package.json#L41

**What should have happened**:

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by humphd** [comment]
I can't remember, do we need to do anything to ship a new version of Satellite now?

**Comment by cindyledev** [comment]
@RC-Lee I touched your baby. Do we need to do anything to ship a new version of Satellite?

**Comment by RC-Lee** [comment]
For making a Satellite release, we only have to change the version here
https://github.com/Seneca-CDOT/telescope/blob/e10b0ea1f1f453e7146c1808fe54c28d0f98ea3f/src/satellite/package.json#L3
make a PR, and merge to master, 
Then make another PR for all the services to use the latest Satellite. 
Can have renovate do it, but probably better to do it manually to see nothing breaks with the node upgrades.
