### ISSUE TITLE
Duplicated file storage.js

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#374]
`Storage.js` is currently in 2 different places, in `src/` and in `src/backend/utils/`
This probably happened after rebasing.

![Screenshot from 2019-11-28 13-33-25](https://user-images.githubusercontent.com/23108901/69827075-dfe81a00-11e3-11ea-8a88-24470c57f469.png)

**Comment by humphd** [comment]
cc @mskuybeda.

**Comment by KarlaChen** [comment]
@humphd the stoage.js under frontend is the latest one, should I copy all the code from there to utils/storage.js and remove the storage.js under frontend?
