### ISSUE TITLE
Make persistent font

### ISSUE THREAD

**Issue by mnosov622** [Seneca-CDOT/telescope#3750]
**What would you like to be added**:
On the search page, description of how to use search uses different font. UX could be improved by having the same font as other text on the website(Spartan).
![image](https://user-images.githubusercontent.com/73063742/199126191-93a88625-262f-4d2e-a90b-4df103e8bb4f.png)

**Why would you like this to be added**:

Improve UX. When you visit [Search page](https://telescope.cdot.systems/search/), different font simply catches the eye.

**Comment by Eakam1007** [comment]
Hey, if this is open, I would like to work on it

**Comment by humphd** [comment]
@mnosov622 you OK if @Eakam1007 works on this?

**Comment by humphd** [comment]
In the absence of comment from @mnosov622, I've assigned to @Eakam1007.

**Comment by humphd** [comment]
OK, maybe @Eakam1007 would be willing to review.

**Comment by Eakam1007** [comment]
> OK, maybe @Eakam1007 would be willing to review.

Sure, I can review this

**Comment by mnosov622** [comment]
Great !

I will make a PR today or tomorrow, so you can review it. Thank you :)
