### ISSUE TITLE
Change a magic number to somethign else for a width on sign-up page's CSS

### ISSUE THREAD

**Issue by cychu42** [Seneca-CDOT/telescope#3755]
**What would you like to be added**:
In PR #3743, there was use of a magic number for a width to handle overflow. One should look at the width of surrounding containers to set that width accordingly.  

**Why would you like this to be added**:
It's a better practice and to fit with the design of the page. I would like to handle this myself.

**Comment by cychu42** [comment]
Sorry, #3743 is the PR I was talking about. #3611 is the issue for the PR.

**Comment by AmasiaNalbandian** [comment]
For "services" like this, I would suggest we make it reusable to use elsewhere in the project.

**Comment by cychu42** [comment]
Sorry, can you clarify what you mean by "this"? Do you mean the overflow handling with use of eclipses?
