### ISSUE TITLE
About & "About us" different hyperlinks

### ISSUE THREAD

**Issue by Ririio** [Seneca-CDOT/telescope#3758]
When clicking on the "About" icon from the side navigation bar, it leads to the actual page provided by the repository, which is "404" for my case, because I'm currently running just the front-end. However, when clicking on the "About Us" at the top navigation bar, it links itself to an already published telescope as to the local one

https://user-images.githubusercontent.com/32577022/201498956-d1966a31-9662-4a1a-9244-c787a08a2564.mp4

Looking through the developer's tool, it links itself to the public url 

![image](https://user-images.githubusercontent.com/32577022/201499067-a9de772d-ee7c-4309-bfab-78350fceaa95.png)

Unlike the "About" of the side navigation bar

![image](https://user-images.githubusercontent.com/32577022/201499114-3ef29298-af82-49df-a4b0-7f5bfa7b72d7.png)

I'm not sure as to whether this is by design or not?

**Comment by humphd** [comment]
No, this seems like a bug to me.  

cc @cindyledev, @sirinoks

**Comment by Ririio** [comment]
Would it be possible to work on this for release 0.3?
