### ISSUE TITLE
`code` blocks embedded in blog entry are harder to read in light mode 

### ISSUE THREAD

**Issue by SerpentBytes** [Seneca-CDOT/telescope#3772]
**What happened**:
The embedded `code` in the default theme is harder to see because of the colours being light. However, when you toggle to dark mode and back to light mode, the `code` block colours are correctly adjusted. 

**What should have happened**:
I should not have to toggle again to light mode if I am already in the light mode to be able to read lines of `code` embedded in a blog entry.

**How to reproduce it (as precise as possible)**:
- Navigate to the Telescope website without logging in and look for blog entries with embedded  `code` blocks

https://user-images.githubusercontent.com/50856799/203443196-e94f4abe-9600-40da-827a-6cbbd0b14140.mov

**Anything else we need to know?**:

If you are unable to reproduce it, try refreshing the page.

**Environment**:

- OS: MacOS
- Browser: Safari

**Comment by humphd** [comment]
We use stylesheets here for this: https://github.com/Seneca-CDOT/telescope/tree/master/src/web/app/public/styles

**Comment by humphd** [comment]
@SerpentBytes is this still an issue?  I haven't noticed this in a long time.  If not, can you close?
