### ISSUE TITLE
Parsing information for OPML Generator

### ISSUE THREAD

**Issue by jrdnlx** [Seneca-CDOT/telescope#379]
I am building an OPML-Generator (issue #64 ) that shows feed list information in OPML format when you use the route `localhost:3000/opml` . We need to be able to get all the data and use it in that route. 

Example of the data types needed is shown in the picture.

![image](https://user-images.githubusercontent.com/42614134/69837249-c662c480-121b-11ea-8f64-0949e0116f52.png)

**Comment by humphd** [comment]
What do `text` and `type` refer to exactly?  What are the possible values of each?

**Comment by jrdnlx** [comment]
Type refers to what kind of feed format we are using, so in telescope we are using rss format for our feeds. Another format we could use is atom. 

Text refers to anything you want to, it could be the author name or title. In this example (https://github.com/paulirish/frontend-feeds/blob/gh-pages/frontend-feeds.opml) they use text as the title of the blog. Since for us we have a title already we should use text as the owner of the blog. 

xmlURL is the rss feed url.

htmlUrl is the html url of the blog.
