### ISSUE TITLE
Bug with example.env file 

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#382]
https://github.com/Seneca-CDOT/telescope/pull/381 @nazneennahar 

Looks like there's some white space in between the env environment example file when copying it to a new .env file it will give some errors while building as there can't be whitespace between the = operator and the variable name and the value.

**Comment by humphd** [comment]
@nazneennahar can you fix this in a new PR, please?  There shouldn't be any spaces after the `=` signs in an `env` file.

**Comment by humphd** [comment]
I wonder if we can lint this, or otherwise help devs get this right in the future?

**Comment by nazneennahar** [comment]
sure i will work on it

**Comment by humphd** [comment]
Fixed.
