### ISSUE TITLE
Circle CI needs to be able to run Puppeteer

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#384]
In #383 we're adding support for [Puppeteer](https://pptr.dev/), which uses Chromium in a headless way via JavaScript.  It's currently [failing in Circle CI builds](https://circleci.com/gh/Seneca-CDOT/telescope/611?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

As I [mentioned in my review](https://github.com/Seneca-CDOT/telescope/pull/383#pullrequestreview-324869453), I suspect that Chromium isn't setup/installed properly in Circle CI, and we need to add it to our `.yml` file.

cc @sukhbeersingh

**Comment by jayson528** [comment]
is it okay if i try and have a go at this?

**Comment by humphd** [comment]
@jayson528 you may have already seen this, but I've got a PR up for this in #385.

**Comment by jayson528** [comment]
@humphd yes i noticed the PR and removed unassigned my self. Just looking for an issue to work on.
