### ISSUE TITLE
CONTRIBUTING.md Redis and Prerequisites are outdated

### ISSUE THREAD

**Issue by drwm-base** [Seneca-CDOT/telescope#386]
The prerequisites and redis setup sections are redundant at this point, and should include information on getting docker-compose and docker up and running. The environment requires docker and these instructions would be misleading to future developers.

Instructions on setting up the .env file would also be helpful here, aside from just entering credentials.

**Comment by humphd** [comment]
Great suggestion.  cc'ing @Reza-Rajabi, who has spent the most time on the docker-compose pieces, and could probably help with reviewing this, or offering tips.

Another thing I think we should do in these docs is highlight the fact that you can use the `choco` package manager on Windows.  [Here's how we do Redis on Travis CI for Windows](https://github.com/Seneca-CDOT/telescope/blob/master/.travis.yml#L38-L40).  You run those few commands, you get a Windows Redis server.

**Comment by humphd** [comment]
https://chocolatey.org/ is the site for info on using `choco`.

**Comment by manekenpix** [comment]
There's already an issue for all this, it's #249. I'm working on it but I'd be happy to merge what I have with @drwm-base and/or @Reza-Rajabi.

**Comment by drwm-base** [comment]
Oops my bad. I'll let you go on with it. If I have anything to add I will after.

**Comment by humphd** [comment]
@manekenpix have you actually started work on #249?  If not, maybe we should let @drwm-base take this, since you have other issues you're doing in parallel, and I know he's looking for something.

Regardless, let's close one of these two issues, and move forward in the other.

**Comment by drwm-base** [comment]
@manekenpix its up to you, if you already started on this I can find something else.

**Comment by manekenpix** [comment]
@humphd I put together some material about installation (not much), but it'd be great if @drwm-base  could take on this one.

@drwm-base I can transfer what I have to you if you don't want to start from scratch (installing docker on windows is a pain in the neck, I already did that part).

Let's close #249 then.

**Comment by humphd** [comment]
Closed #249, thank you @manekenpix.  @drwm-base you can take this, and please get input and reviews from people who have been working on this code, so we don't miss anything.  Thanks to you both.

**Comment by drwm-base** [comment]
@manekenpix if you can send me what you have so far I would really appreciate it

**Comment by manekenpix** [comment]
@drwm-base Absolutely, let me know if I can send it you by email or some other way.

**Comment by Reza-Rajabi** [comment]
@drwm-base Let me know if I can help. Also, there are some instructions commented in `Dockerfile` and  `docker-compose` files which you may find useful.

**Comment by drwm-base** [comment]
@manekenpix I sent you an email through our internal email. Hopefully it reached you.
@Reza-Rajabi thanks for the offer, I will definitely use those comments and I will be putting up a pull request soon. I will be @ing people in that pull request whose features I am less sure of, to get feedback.
