### ISSUE TITLE
Update documentation to include instructions for using editorconfig

### ISSUE THREAD

**Issue by ragnarokatz** [Seneca-CDOT/telescope#39]
Update documentation to include instructions for using the .editorconfig file in the following IDE/environments:

the main one:
- **visual studio code**

optional ones:
- notepad++
- sublime text
- atom
- eclipse
- others

reference link: https://editorconfig.org/

**Comment by cindyledev** [comment]
PR #36 has merged; closing this issue.

**Comment by ragnarokatz** [comment]
@cindyledev This is not complete. You, or anybody is welcome to work on this issue.

This is supposed to be the follow up step after the initial commit of .editorconfig file. PR #36 fixed issue #31.

**Comment by ragnarokatz** [comment]
@robertbegna this is still an open issue. feel free to take this issue if you need something to work on.
cc @humphd
