### ISSUE TITLE
CircleCI failing to launch chrome

### ISSUE THREAD

**Issue by sukhbeersingh** [Seneca-CDOT/telescope#391]
Circle CI is failing to launch chrome for puppeteer with a third party orb. It complains of a missing shared library. However, putting the installation command for headless chrome dependencies into the config.yml file seems to solve the issue.

**Comment by humphd** [comment]
I think this won't be necessary, I wasn't calling into the orb, https://github.com/Seneca-CDOT/telescope/commit/174fa8c5a7c81f4471231515808cbe1f9adf6fa5.
