### ISSUE TITLE
Remove spam-filter module and associated code

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#415]
We're having issues using the https://www.npmjs.com/package/spam-filter module, since it depends on a really old version of node.  Let's remove it, or replace it.

We're not currently using spam filtering at all, so it's critical to have this (yet).

**Comment by cindyledev** [comment]
Seeing how spam-filter hasn't been updated in 2 years and depends on node 8 and npm 5... I started digging around our packages to see which ones are also in the same boat where it hasn't been updated in a while. 
```
opml-generator (5 years ago)
parse-github-url (2 years ago)
passport (2 years ago)
passport-openid (4 years ago)
reading-level (2 years ago)
wordcount (4 years ago)
valid-url (6 years ago)
```
These aren't complaining now but I'm worried that they might complain in the future @_@
Am I overthinking or are these ticking time bombs?

**Comment by c3ho** [comment]
@cindyledev Thank you for the good point. As she pointed out, this hasn't been updated in 2 years and its dependencies will conflict with the rest of our other libraries. Closing.

**Comment by c3ho** [comment]
@humphd are you ok with me assigning it to you so your students can take this issue?

**Comment by humphd** [comment]
That, or assign it to yourself, and you can mentor.  Either works.

**Comment by humphd** [comment]
I'm going to steal this...
