### ISSUE TITLE
Add testing infrastructure

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#42]
We're starting to get some code in the repo, and it's time to think about how we'll test all the features we add.

I'd like to see us get an initial test in place, so we can figure out our infrastructure, and let others add more tests in future PRs.

Let's use [Mocha](https://mochajs.org/) or [Jest](https://jestjs.io/) to automate our tests.  At first, we need a simple `npm test` run that runs one test against something like the feed parser function, or something else really basic: call into a function and it expects to get back a given result.

**Comment by ImmutableBox** [comment]
I would like to try my hand at this. After some research/testing I decide to use [Jest](https://jestjs.io/). My reasoning: 
- [Jest ](https://jestjs.io/)setup was easier to setup.
- [Jest ](https://jestjs.io/)sent a warning message about problems with async operations while [Mocha](https://mochajs.org/) did not.

[Mocha](https://mochajs.org/) does seem to be more flexible, but the setup takes some time. Maybe in later development there can be a switch, but for a starting point ill be using [Jest ](https://jestjs.io/).

**Comment by ImmutableBox** [comment]
Merged with https://github.com/Seneca-CDOT/telescope/pull/55.
