### ISSUE TITLE
Sanitize HTML before storing in Post

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#429]
In the feed worker, we have a function that turns parsed feed objects into `Post` objects.  We need to [update this to pass the HTML through our HTML Sanitizer](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/feed/worker.js#L13).

**Comment by humphd** [comment]
NOTE: we also need to get the raw text parsed out too, but we need to get our Puppeteer resource sharing done first, see #388.

**Comment by PavanKKamra** [comment]
Hello, I would like to give this a try :). 

Thanks, 
Pavan.
