### ISSUE TITLE
Set up CI/CD pipeline at Travis CI

### ISSUE THREAD

**Issue by kartik-budhiraja** [Seneca-CDOT/telescope#43]
Set up the base pipeline as per [comment](https://github.com/Seneca-CDOT/telescope/issues/6#issuecomment-549646158)  on Travis

**Comment by kartik-budhiraja** [comment]
I will be taking this over. :)

**Comment by humphd** [comment]
Travis is connected to telescope at https://travis-ci.org/Seneca-CDOT/telescope
