### ISSUE TITLE
Add tests for HTTP /post route

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#430]
We recently added a `/post` route to our web server.  It works by taking a Redis key (guid) for a post in the database, and returning a JSON object for that that post.  We need tests for:

- 404 case: if we give an id that doesn't exist in the database, it should return a 404
- 500 case: possibly hard to test, we need to do the right thing if the database goes down
- 200 case: given a key in the database, expect this to return it.
- Deal with encoded and non-encoded URI guids that contain path separators

To test the latter case, you would need to add something to the database using `storage.js` and `addPost()`, then call this route and make sure it can return it.

**Comment by izhuravlev** [comment]
I would be happy to work on it!
