### ISSUE TITLE
Limit number of posts returned by HTTP /posts route

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#432]
We got the code to run today, and it's already obvious that we can't ever return/use all posts from the database--there are too many.

We should start by updating the `/posts` route to take an optional number: `/posts/:count?`, where `count` should be a number.  We'd use this as the upper limit for the number of posts we request from the database.

By default, I suggest that we should limit this to the most recent 10 posts, unless `count` is provided.  That is:

- `/posts` - should return an Array of 10 elements
- `/posts/15` - should return an Array of 15 elements

**Comment by humphd** [comment]
I wonder if my design for this is wrong.  Probably we should look at prior art.  Maybe we should allow query string params with a range?

Another thing we should do is reverse the order of what Redis returns from the set.  I would expect the most recent posts, not the oldest.  We can do that in this PR or in another.

**Comment by manekenpix** [comment]
I think `/posts` vs `/posts/:count` would be enough unless we want to limit or alter the number of returned posts in other ways, all at once.

I'll add sorting most recent to oldest in this PR.

**Comment by manekenpix** [comment]
I'm wrong. From what I've been reading, it seems that:
> . If you want to identify a resource, you should use Path Variable. But if you want to sort or filter items, then you should use query parameter. 

So I guess I'll use query parameters. @humphd what do you think?

**Comment by humphd** [comment]
I think we should [follow GitHub's lead here](https://developer.github.com/v3/#pagination), they do it well.  Specifically:

- `/posts` should return 30 items by default
- `/posts?per_page=15` should return 15 items
- `/posts?per_page=101` should return 100 items (i.e., cap it at 100 as a max value)

Given the above, we can also do pagination, either in this PR or a new one:

- `/posts?page=2` should return 30 items, but the second 30 items in our set
- `/posts?page=3&per_page=10` should return 10 items, but the third page of 10 items

We should also add a `Link` header with URLs for `next`, `prev`, `first`, `last`.  These would allow the browser to navigate without having to construct URLs for the other pages.

This work could easily be split up.  The most pressing part is the limit to 30 items by default, with `per_page` allowing an override up to 100 items.  The rest could happen in follow-ups.  If so, we should break those out into other PRs.

cc @lucacataldo.

**Comment by humphd** [comment]
https://developer.github.com/v3/guides/traversing-with-pagination/ is really useful to understand this, especially from the consumer side.

**Comment by manekenpix** [comment]
@humphd I'll include `per_page`. `page` and `Link` can be part of different PR(s).
