### ISSUE TITLE
Intermittent timeouts in text-parser tests

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#439]
Sometimes, when running tests locally, I'm failing text parser tests due to timeouts.  I wonder if we need to bump up the timeout for these tests to 10s or something?  cc @giatuongtran9, @PavanKKamra:

```
 FAIL  test/text-parser.test.js (8.161s)
  ● Testing text-parser

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

       5 |  * Function should only extract what in the body
       6 |  */
    >  7 | test('Testing text-parser', async () => {
         | ^
       8 |   const result = await textParser('<!DOCTYPE html><p>Hello World</p>');
       9 |   expect(result).toBe('Hello World');
      10 | });

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (test/text-parser.test.js:7:1)
```

**Comment by UltimaBGD** [comment]
As mentioned in my PR above, which does not change any of these files, it has also timed out when being tested on Travis. Circle CI however, remained fine.

These are the logs for the timeouts on [Windows](https://travis-ci.org/Seneca-CDOT/telescope/jobs/620759132?utm_medium=notification&utm_source=github_status) and [Mac](https://travis-ci.org/Seneca-CDOT/telescope/jobs/620759131?utm_medium=notification&utm_source=github_status).

The windows build after passed, which shows this is indeed intermittent, and can occur in our CI environments as well.

**Comment by UltimaBGD** [comment]
The Mac build passed as well in the latest build of my PR, despite no changes that should affect the test or the code.

**Comment by humphd** [comment]
Let's bump these tests up.  You do it like this:

```js
test('....', async => { ... }, 10000)
```

Add a third arg to the test to specify a timeout in ms.

**Comment by giatuongtran9** [comment]
@humphd sorry for my late reply, do you want to increase the run time for that specific test? I found this on the Jest document https://jestjs.io/docs/en/configuration#timers-string that you can create a fake timer but I don't know how to add it to the project

**Comment by UltimaBGD** [comment]
Would you need to create a fake timer? I think adding the timeout at the end of the test should be enough, but I could be wrong.
