### ISSUE TITLE
Update /posts route to support paging

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#441]
We should [follow GitHub's lead](https://developer.github.com/v3/#pagination), they do pagination well.  Specifically:

- `/posts?page=2` should return 30 items, but the second 30 items in our set
- `/posts?page=3&per_page=10` should return 10 items, but the third page of 10 items

We should also add a `Link` header with URLs for `next`, `prev`, `first`, `last`.  These would allow the browser to navigate without having to construct URLs for the other pages.

cc @lucacataldo, @manekenpix

**Comment by manekenpix** [comment]
Closed via #474
