### ISSUE TITLE
Support Accept header in /posts route

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#443]
Our `/post` route returns JSON for a post, given a key.  Let's add support for `Accept: text/plain`.  Using [`req.accepts()`](https://expressjs.com/en/api.html#req.accepts), we can check for text or json, and give back either JSON, or return the pure text content of the post.  We might also want to support `text/html` and just send the HTML content?

**Comment by humphd** [comment]
From discussions in class today with @yatsenko-julia, I wanted to give some more info on where to look for this in our code.

The code where we do the `/posts` route lives in https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/posts.js, and in particular, we want to deal with the case that a post is requested by its `guid`, which is https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/posts.js#L74-L95.  The tests that go with this are in https://github.com/Seneca-CDOT/telescope/blob/master/test/posts.test.js.

When we return JSON (the default) for `/posts`, we include a whole bunch of data about a Post, which comes from https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/post.js.  One of the properties in a Post is `text`, and we should return this vs. the entire JSON record in the case that the user wants `text/plain`.  We might consider also adding the `title`, maybe with a newline after it.

@yatsenko-julia, feel free to ask any questions you have here or in Slack, and I'll help you get started or overcome any problems.

**Comment by cindyledev** [comment]
Hi @yatsenko-julia , it seems you pushed a branch instead of submitting a pull request. Please refer to https://github.com/Seneca-CDOT/telescope/blob/master/docs/CONTRIBUTING.md#workflow-in-git-and-github to setup your remotes so that `origin` is your fork and `upstream` is the telescope repo. If you need further assistance, we're available on Slack.
