### ISSUE TITLE
Short circuit feed processing if we already have processed data

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#445]
If you run the server, and let it process all the feeds, it will have all the data it needs cached in Redis when it ends.  However, if you restart the server, it will start again, and re-process all the data.

We should try and be smarter about this.  A few ideas:

- When we download a feed, we could first check headers, and see if it's been updated since the last time we downloaded.  We'd have to store this info in our feed hash in Redis.
- Or, we could download the feed again, and check each post to see if it's been updated, compared to the date we have in the hash for this post.

Eventually, it would be great if the server was smart enough to only download and process new feeds and posts vs. always doing everything we tell it.

**Comment by c3ho** [comment]
Where would you suggest making these changes? Should the change happen in worker.js or in addPost() of storage.js?

Expanding on this should we include an updatePost for storage.js?

**Comment by humphd** [comment]
What about this.  Here's the headers of your blog feed:

```
$ curl -I https://c3ho.blogspot.com/feeds/posts/default/-/SPO600
HTTP/2 200
date: Fri, 06 Dec 2019 01:05:00 GMT
content-type: application/atom+xml; charset=UTF-8
server: blogger-renderd
cache-control: public, must-revalidate, proxy-revalidate, max-age=1
vary: Accept-Encoding
expires: Fri, 06 Dec 2019 01:05:01 GMT
x-content-type-options: nosniff
x-xss-protection: 0
last-modified: Mon, 02 Dec 2019 09:52:14 GMT
x-frame-options: SAMEORIGIN
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
accept-ranges: none
```

What if we did a HEAD request to a feed URL, and determined if it's been updated since we last downloaded and parsed it?  We have some info in the headers:

- date
- cache-control
- expires
- last-modified

See https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers.

We could add some of this data to our `feed` record in Redis, and then the next time we go through the feeds, we can compare to what's there.  If we did that, we could add this as a step before we run through the feedparser.

**Comment by humphd** [comment]
We could also add an `If-modified-since` header to let the remote server tell us if we need to re-download it.  See https://flaviocopes.com/http-request-headers/#if-modified-since

**Comment by humphd** [comment]
So summing up, what if we try this:

1. When we parse a feed in our worker, we try to get a `last-modified` key value out of the feed hash from Redis (it won't exist the first time).  We'll have to add this to our storage code.
1. If it exists, we can use it to do a node-fetch HEAD request, passing `If-Modified-Since: ''+date.toUTCString()` on the headers.  If we get back a 200, we go ahead and process this, storing the new `last-modified` in our feed hash (we can parse it with `new Date('Fri, 06 Dec 2019 01:13:17 GMT')`.  If we get a 304, we bail.

Does that make sense?

**Comment by c3ho** [comment]
Yep, that should be enough info for anyone wanting to work on this one.

**Comment by humphd** [comment]
I think we can probably use https://github.com/jshttp/fresh to do a bunch of this.
