### ISSUE TITLE
Set up CI/CD pipeline at Circle CI

### ISSUE THREAD

**Issue by kartik-budhiraja** [Seneca-CDOT/telescope#45]
Set up a base pipeline as per [comment ](https://github.com/Seneca-CDOT/telescope/issues/6#issuecomment-549646158) at Circle CI.

**Comment by sukhbeersingh** [comment]
Hey @Reza-Rajabi do you need help with this? My submission for Github Actions couldn't be merged due to limitations of beta program.

**Comment by Reza-Rajabi** [comment]
Hi @sukhbeersingh my pleasure. I absolutely need help for that. So far I have learned that we need to make a Circle account and add its dependency on our repo. So feel free to start working on it.
