### ISSUE TITLE
Add new templates for the next release

### ISSUE THREAD

**Issue by cyh0968** [Seneca-CDOT/telescope#452]
The current version of the index.html page has been developed a lot. It seems good but it should contain a lot of functionality so the index.html code will be very complicated in the end. It might be a good idea to make another clean template that focuses on UI/UX because when we complete the basic functionalities, we can easily integrate our code with the new templates. Plus, it is always nice to have multiple design options since our stage is on a very early stage.

**Comment by cyh0968** [comment]
If you don't mind, I want to handle this part.

**Comment by agarcia-caicedo** [comment]
This is being fixed on #514, so we'll be closing this issue
