### ISSUE TITLE
Add comments features on the blog post. 

### ISSUE THREAD

**Issue by cyh0968** [Seneca-CDOT/telescope#453]
The telescope will be the place for Seneca opensource community. Therefore, it seems like a good idea to have comment section. If we add comments sections, we can easily communicate. For instance, when someone tries to follow some content of the feed, he may face some trouble. In this case, if telescope support to read/write comments features, he can easily solve a problem. Plus, other readers can get useful information.

**Comment by cyh0968** [comment]
For this issue, I will add a comment section on the index.html.

**Comment by aprilllllllll** [comment]
> For this issue, I will add a comment section on the index.html.

Can I do the CSS for this part?

**Comment by cyh0968** [comment]
> > For this issue, I will add a comment section on the index.html.
> 
> Can I do the CSS for this part?

Sure, once I finish the html, then you can add CSS. I will tell you when I update the html component about the comment.

**Comment by lozinska** [comment]
Thank you @cyh0968 filing this issue. For now we decide that we will not use this option in Telescope project and may be return to this later once the project launched.
