### ISSUE TITLE
Add post analysis information to index.html 

### ISSUE THREAD

**Issue by cyh0968** [Seneca-CDOT/telescope#454]
Even though the telescope has a variety of options to analyze the blog post, the current version of the index.html template does not reflect the update. It will be a good idea to contain that information in the template.

**Comment by cyh0968** [comment]
My workflow is related to this part, so I will handle this part.

**Comment by manekenpix** [comment]
Could you explain what you mean with `update`?

**Comment by cyh0968** [comment]
> Could you explain what you mean with `update`?

Oh yes, for instance, our analysis feature provides information about a blog post such as reading time, reading level, word count and summary. But the current version of index html has no html component to show that information. So I think it would be good that the index.html has an element to show analysis information.

**Comment by lozinska** [comment]
Thank you @cyh0968 for opening this issue. We value your contribution to Telescope project, but for now I will close this issue, because we decide to show only reading time. Thank you again
