### ISSUE TITLE
New Feature Suggestion: Add like feature

### ISSUE THREAD

**Issue by cyh0968** [Seneca-CDOT/telescope#456]
One of the purposes of the telescope project is to share useful information. Since a lot of Seneca students or graduates will read and update post, I think it is crucial to know which information is more valuable than others. One solution can be counting the number of like of each post for a specific period (it can be one week or one month like git trend). Plus, to categorize each topic, using hashtags can be nice. 

I believe that the telescope should be more than just a feed reader. If we are just trying to make a better version of the planet, then our efforts can be meaningless since there are a better version of feed readers. Then we may need another reason to make our own telescope. 

Once I read a book about [a complex system](https://en.wikipedia.org/wiki/Complex_system). There was an interesting feature of a complex system. In the system, each component interacts with another component. When there are new interactions between components in the system, and the interaction is over the threshold, it generates a new system which is fully different from the previous system. One example can be the emergence of civilization, industrialization, Open source culture, and even Facebook. 

Then you might ask what relation between the telescope and the complex system. What I want to is that if we can create a new interaction in the complex system ( this case Seneca), we can make a new culture (like Facebook did or Instagram did). And I think that Telescope can accomplish it. I think it worth thinking about the interaction and communication that will happen on the Telescope. 

I think it would be nice to discuss the telescope in terms of tools that create a new culture.

**Comment by manekenpix** [comment]
See #26

**Comment by cyh0968** [comment]
> See #26

Well, I think the feature seems similar but the intention is different. The reason I suggested "like feature" is to distinguish more valuable information, not to find who is the most popular one. The basic idea is from [hacker news](https://news.ycombinator.com/). 

If we can't distinguish which information is more weighted, then it would be extremely hard to find proper information. If our project cannot help us to find valuable information, the telescope will be cold soon. Plus, if the site only works as a feed reader, then it would be better just using feeldly and sharing the list of subscriptions.

I think to make our efforts to build the new planet meaningful, the telescope should work as a kind of community. 

Perhaps someone may concern about a like button can disrupt others, then it can be solved easily not exposing the number of like. The number only can be used to decides monthly major posts or weekly interesting posts such as the top ten posts. 

Besides, I think it would be good if the telescope provides incentive participants to write their blogs. If the telescope cannot provide any positive incentive, then most people will stop to write their blogs after the end of the courses. A human being is sociable, so when people write a blog post, they want their posts will be read by others. If people can't check any response, they will not keep write posts.

I believe that we should discuss more the way the telescope will go.

**Comment by asyam1** [comment]
I would like to help you with this feature

**Comment by manekenpix** [comment]
Thank you for your proposal. This could be a good idea to develop in the future. We're closing this issue and we'll open a new one if/when it's decided to develop this idea.
