### ISSUE TITLE
Formatting error in CONTRIBUTING.md

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#464]
I'm not sure but I think this part of [CONTRIBUTING.md](https://github.com/Seneca-CDOT/telescope/blob/master/docs/CONTRIBUTING.md) is not supposed to look like this. @drwm-base can probably verify it

![Screenshot from 2019-12-05 15-11-06](https://user-images.githubusercontent.com/23108901/70270130-b72acc00-1771-11ea-9821-522026e889ae.png)

**Comment by humphd** [comment]
I keep seeing this file get updates in people's PRs.  I wonder if we need to do `npm run prettier` to reformat it?
