### ISSUE TITLE
Content scrolls beyond post title header

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#467]
There's a width/scrolling bug with how the post headers are done, allowing content to scroll to the left/right of it.  The header should extend 100% of the width of the content container, such that the post itself scrolls beneath it.

![scroll-bug](https://user-images.githubusercontent.com/427398/70288648-3f27ca80-17a0-11ea-80a5-cf1df40c02d9.gif)

**Comment by asyam1** [comment]
I would like to work on it

**Comment by miggs125** [comment]
Hi @asyam1, we are currently fixing this in #531 so this issue will be closed. Feel free to contribute there :)
