### ISSUE TITLE
add more test cases to sanitize-html.test.js

### ISSUE THREAD

**Issue by ragnarokatz** [Seneca-CDOT/telescope#468]
This issue was created as a result of fixing #458 

Add more unit test cases to `sanitize-html.test.js`. This will serve as documentation as to how `sanitize-html` behaves according to different content passed in.

**Comment by KarlaChen** [comment]
@ragnarokatz Tony and I are going to add more test for it.

**Comment by humphd** [comment]
It would be helpful to take a look at the actual HTML being sent to our server now, and write some cases for things people actually do in their posts.
