### ISSUE TITLE
Add support for ?since to /posts route

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#475]
In #474 we're adding support for paging.  If you know how many items you want, you can request to receive them in pages of up to 100 elements.

Another approach I'd like to see us implement in parallel is adding code to handle `?since` queries to the `/posts` route.  Here, we'd allow requesting new posts, which have been added/updated in our sorted set *since* the given time.

We could either have `since` accept a date/time (e.g., `(new Date()).getTime()`), or we could follow what Shopify does with their API, and do `since_id`, where you pass the `guid` of a post, and we look up its order in the set, and get everything added/updated after it.

**Comment by agarcia-caicedo** [comment]
Right now, this isn't a focus for us. While we might like to look into this later, I'm closing this issue for right now.
