### ISSUE TITLE
Post Author and Date Inconsistencies

### ISSUE THREAD

**Issue by s-arika** [Seneca-CDOT/telescope#478]
Some of the post author and date have inconsistent layout. 
<img width="909" alt="Screen Shot 2019-12-06 at 4 47 26 PM" src="https://user-images.githubusercontent.com/28491962/70358767-21ae3b80-1848-11ea-89e9-f58c87ed897d.png">

<img width="1070" alt="Screen Shot 2019-12-06 at 4 47 35 PM" src="https://user-images.githubusercontent.com/28491962/70358771-2246d200-1848-11ea-8bc7-0d8f85b739c7.png">

<img width="872" alt="Screen Shot 2019-12-06 at 4 48 21 PM" src="https://user-images.githubusercontent.com/28491962/70358828-3d194680-1848-11ea-9a09-690d89a8e360.png">

**Comment by cindyledev** [comment]
I'd like to try this one

**Comment by cindyledev** [comment]
We are currently reworking our front-end. This issue will not carry over to the new UI. Closing

**Comment by cindyledev** [comment]
We are currently reworking our front-end. This issue will not carry over to the new UI. Closing
