### ISSUE TITLE
ECONNREFUSED while requesting the feed URL.

### ISSUE THREAD

**Issue by aprilllllllll** [Seneca-CDOT/telescope#48]
I download the code and try to run it. It is giving me Error: connect ECONNREFUSED while requesting the feed URL.

**Comment by manekenpix** [comment]
Than happens when Redis is not running. Try to run Redis before launching telescope

**Comment by ImmutableBox** [comment]
This is also explain in the pull request https://github.com/Seneca-CDOT/telescope/pull/34 which adds the CONTRIBUTING.md. If someone can review, approval and merge it that would be great.

**Comment by aprilllllllll** [comment]
Thank you~

**Comment by humphd** [comment]
@aprilllllllll we should add some code that gives a more useful error message if Redis can't be found.  Do you want to work on a PR to address this?  We probably need to catch an error case in `Bull` so that it doesn't crash like this.

**Comment by aprilllllllll** [comment]
> @aprilllllllll we should add some code that gives a more useful error message if Redis can't be found. Do you want to work on a PR to address this? We probably need to catch an error case in `Bull` so that it doesn't crash like this.

yes sure~
