### ISSUE TITLE
PR Template has different sized headings

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#485]
**What happened**:

The recently added template for PRs has some issues, and the size of headings is different, see example:

<img width="696" alt="Screen Shot 2019-12-06 at 8 53 06 PM" src="https://user-images.githubusercontent.com/427398/70367052-88445100-186a-11ea-965f-9177fabd9ebb.png">

**What should have happened**:

Let's standardize all the headings to be the same size.

**How to reproduce it (as precise as possible)**:

Try creating a new PR

**Comment by cindyledev** [comment]
I'd like to take this
