### ISSUE TITLE
Replace HMSET to HSET when becomes avaliable

### ISSUE THREAD

**Issue by mskuybeda** [Seneca-CDOT/telescope#489]
**What would you like to be added**:
Replace HMSET with HSET in storage.js and storage.test.js

**Why would you like this to be added**:
HMSET is deprecated as of now and is replaced with HSET. I was not able to use HSET originally since it was not implemented in neither ioredis nor mock-redis. 

I have implemented the functionality of HSET into ioredis, please refer [HERE](https://github.com/luin/ioredis/pull/1012)

However, redis-mock as of 2019-12-07 is being reviewed. Refer to my [PR](https://github.com/stipsan/ioredis-mock/pull/898) and [Issue](https://github.com/stipsan/ioredis-mock/issues/899) .

**Comment by humphd** [comment]
This is still blocked on https://github.com/stipsan/ioredis-mock/pull/898.

**Comment by humphd** [comment]
Fixed in https://github.com/stipsan/ioredis-mock/pull/1007, we can pull in ioredis 5.1.0 to get this I think (needs to be tested).

**Comment by manekenpix** [comment]
All tests passed using [ioredis-mock](https://github.com/stipsan/ioredis-mock) 5.1.0 and using `HSET` in [storage.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/storage.js).

**Comment by zg3d** [comment]
Can I try to do this issue.
