### ISSUE TITLE
Integrate adding feeds from storage.js

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#491]
**What would you like to be added**:
Store feeds in Redis. This should probably be added in worker.js or add-feed.js

**Why would you like this to be added**:
We have code in storage.js to store feeds, but we currently don't use it

**Comment by humphd** [comment]
This is a great idea.  We need this so we can get the proper names of people, too, via HTTP end points.

I think we should consider changing what we use for our key in Redis to be the feed URL, since they will be unique.

**Comment by Silvyre** [comment]
I believe this was resolved by #592
