### ISSUE TITLE
Populate missing fields in Redis Post data

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#496]
**What happened**:

The data we store in Redis for a Post is incomplete.  Here's an example:

```js
  post: {
    published: 'Wed Dec 04 2019 21:49:08 GMT-0500 (Eastern Standard Time)',
    author: 'danielameresekere',
    content: '<p>In my last blog I mentioned that...</p>',
    text: 'textContent',
    site: '',
    guid: 'http://danielspo600.wordpress.com/?p=248',
    link: '',
    url: '',
    title: 'SPO600 Project (Part 7) Stage 3',
    updated: 'Wed Dec 04 2019 21:49:08 GMT-0500 (Eastern Standard Time)'
  }
```

**What should have happened**:

We should be parsing and populating data for all fields.  Specifically, we're missing:

- `site`: the URL of the post's main blog site (i.e., where you'd go to see all the HTML posts). This is available in `meta.link` from the feed parser data.
- `url`: the URL to the original post (HTML) 

We seem to also have a `link` field in our database, but I don't know what it's supposed to be.  Can we remove it?

**Comment by Reza-Rajabi** [comment]
could link possibly be an array of all links on the page?

**Comment by humphd** [comment]
We could augment with link info, yes.  But that would need another field.  This issue is about fixing the data that we currently get from the feedparser and which we store vs. adding to it.
