### ISSUE TITLE
Add support for multiple "timelines"

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#502]
**What would you like to be added**:

Talking with @cathyatseneca today about Telescope, and she made an interesting suggestion:  It would be neat if you could create multiple, separate timelines out of the various feeds in the system.

Let's define a "timeline" as a set of posts, ordered by publication date, from a group of authors.  A "feed" is one author's output (e.g., an RSS feed for a blog).  So a timeline is made up of some number of feeds.

What this change would do is to add a layer of organization on top of our current system, such that you can have multiple timelines instead of just one.

For now, we can add timelines and still continue to only have one.  Later, when we get the login UI working fully, we can add the ability to create user-defined timelines, and add/remove feeds from them.

**Why would you like this to be added**:

Adding multiple timeline support would make it possible to reuse the functionality of Telescope across courses, projects, or communities.  All of the infrastructure is the same, and this way you don't have to host many instances of Telescope to get the benefit of multiple timelines.

**Comment by c3ho** [comment]
Beyond scope of current 1.0, will reopen later.
