### ISSUE TITLE
add catch after exports.start in feed-worker.js

### ISSUE THREAD

**Issue by robertbegna** [Seneca-CDOT/telescope#51]
I would like to add a catch after this function so that any errors can be dealt with

**Comment by Reza-Rajabi** [comment]
Would you like to take a look at [this](https://javascript.info/async-await) and decide about how would you like to approach this issue?

**Comment by vitokhangnguyen** [comment]
I can work on this issue and at the same time, switch all Promise-based then() catch() to async/await. Does that sound good?

**Comment by Reza-Rajabi** [comment]
@robertbegna I am closing this issue since the related pull request is closed.
Please reopen it again if this is a mistake from my side.
