### ISSUE TITLE
Rename /post/:guid route to /posts/:guid

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#510]
**What happened**:

We added both `/posts` and `/post/:guid` routes.

**What should have happened**:

We should have done `/posts` (i.e., return all posts) and `/posts/:guid` (i.e., return the post with `guid`).

We'll have to update the implementation, tests, and frontend, which calls it.

**Comment by ragnarokatz** [comment]
@humphd hello, I would like to work on this please.

**Comment by humphd** [comment]
@ragnarokatz hit it!
