### ISSUE TITLE
UI Enhancement: Colours

### ISSUE THREAD

**Issue by wlto** [Seneca-CDOT/telescope#511]
This issue is more of a discussion than a code issue. This is a smaller piece that is extracted from #505 . It includes colour enhancement suggestions. Currently the main colour of the website is white, red and black. While it fits well with Seneca's colour scheme, I personally think the bright red colour we have can be a bit distracting for users. Hence, I would like us to have a discussion more on the colour choices for the front-end of the website.

For colours, I recommend [this website](http://stencil.wiki/colors), which has various colour palettes from printers that we can use. I recommend it because the colours look very natural to me and down-to-Earth (if that makes sense).

Let me know what you guys think!

**Comment by humphd** [comment]
https://www.happyhues.co/ is another one that's being discussed a lot right now.

See also https://coolors.co/, http://colormind.io/, etc.  There are a lot of good ones out there.

I would say that less-is-more for what we're doing, since we want to mix arbitrary content from users with whatever we choose, and their posts will include images that will introduce all kinds of crazy colours to the page.

I'd take a note from what Medium, WordPress, etc. do here.  We're mostly about "text," so let's lean in into that and not over saturate or distract from the main content.  I agree that we don't have to be locked into white/red/black.

**Comment by wlto** [comment]
I agree. I will try to experiment with different colour schemes that fit our website and present it here for everyone to take a look.

**Comment by wlto** [comment]
Hi @humphd , shouldn't this issue be labeled `area:front-end` instead of `area:back-end`?

**Comment by humphd** [comment]
Indeed, thank you.  @wlto I'm going to add you as a collaborator, so you can make fixes like this yourself.

**Comment by wlto** [comment]
ok! Thank you!

**Comment by wlto** [comment]
Hi everyone, hope you have had a great holiday!

Today I played around with some colour choices for Telescope. So I usually go pretty minimal for colours. I would pick a monochrome palette in black & white as main colours and one or two accent colours in the same family. Here are some previews for you:

# Monochrome & Coral

![Monochrome and Coral](https://i.imgur.com/0zkJHgo.png)

# Monochrome & Yellow

![Monochrome and Yellow](https://i.imgur.com/4yt3l0g.png)

# Monochrome & Blue

![Monochrome and Blue](https://i.imgur.com/IrbmOA3.png)

And here is the [Figma link](https://www.figma.com/file/mLDvtJXEebKbwJhPqDvAuE/Telescope-Colours?node-id=4%3A55) in case anyone wants to take a look. Let me know what you guys think!

**Comment by humphd** [comment]
Of the three here, I'd vote for either Monochrome & Coral or Monochrome & Blue.

My only suggestion would be around contrast and accessibility.  The lighter buttons don't pass accessibility contract guidelines, for example [the first Read More button above fails](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=FF989A&api).  You can test this in Chrome's dev tools, or with an online tool like https://webaim.org/resources/contrastchecker/.

Let's update these so we have better contrast and can pass accessibility guidelines.

Thanks for starting this work, @wlto.

**Comment by wlto** [comment]
Hi @humphd , thank you for your suggestion! I couldn't find a good deep coral colour that can go well with others. Hence, for the **Monochrome & Coral** colour scheme, I propose that we don't have to use the coral/fluorescent orange colour in buttons. Here are the revised versions of those two colour schemes:

# Monochrome & Coral

![Monochrome & Coral](https://i.imgur.com/SzrJikG.png)

# Monochrome & Blue

![Monochrome & Blue](https://i.imgur.com/hz00PH7.png)

I have ran these colours through WebAIM and they passed all cases. Please let me know what you think.

**Comment by manekenpix** [comment]
They both look nice, I vote for **Monochrome & Blue**.

**Comment by miggs125** [comment]
I agree with @manekenpix I like **Monochrome & blue**

**Comment by agarcia-caicedo** [comment]
Our current colour selection derives from this issue, however, further discussion about the choice can go to https://github.com/orgs/Seneca-CDOT/teams/telescope-frontend/discussions
