### ISSUE TITLE
UI Enhancement: CSS styling

### ISSUE THREAD

**Issue by wlto** [Seneca-CDOT/telescope#512]
This issue is a smaller piece which is extracted from #505.

Currently, I see that we don't have much consistent in our CSS code. I would like to propose using [BEM](https://blog.decaf.de/2015/06/24/why-bem-in-a-nutshell/) as a general style guide for how we name our classes and how we structure our CSS code.

And also, I realized that we are using various types of selectors in our CSS. I would suggest using classes over ids, since it has more scalability and prevent unwanted styling bugs. You can read more [here](https://stackoverflow.com/questions/8279132/why-shouldnt-i-use-id-selectors-in-css) for more information about this.

This is not super important but if possible, we might experiment with SASS as well, that way we can ensure that we're getting as much juice out of the power of CSS as possible.

Let me know what you guys think!

**Comment by cindyledev** [comment]
I like the idea of enhancing our CSS styling and structure. I tried to play around with the header in #478 but it's hard to get around because we're using both flexbox and css grid for some reason. 

And I also like having classes over ids. If we can, I want to move away from using `px` units and use `rem` if we can.

**Comment by wlto** [comment]
Yes! Totally agree! We should be consistent with the units as well.

**Comment by agarcia-caicedo** [comment]
This conversation can be moved to https://github.com/orgs/Seneca-CDOT/teams/telescope-frontend/discussions

**Comment by wlto** [comment]
cool!
