### ISSUE TITLE
UI Enhancement: Components

### ISSUE THREAD

**Issue by wlto** [Seneca-CDOT/telescope#514]
This issue is extracted from #505.

As more work on the back-end is under construction, we should also start thinking about core UI components that are used throughout the website (buttons, links, headings, content, etc.). By doing this, we can work on each component one-by-one and hopefully, at the end we can combine them together for different pages and layouts.

In my experience, components should be self-contained, meaning each component's properties should not affect another one. For testing components, I recommend [Storybook](https://storybook.js.org/). I have experience with this and can help set things up for everyone to start working on components.

Let me know what you guys think!

**Comment by miggs125** [comment]
@humphd  Do we want to make our own components or are we open to using something like material UI?

**Comment by humphd** [comment]
Can we go one step backward and first answer: what do we even need?

I think there's an issue missing here: what is our UI?  Components should flow from that.  Want to file and lead this discussion with @agarcia-caicedo, et al?

**Comment by wlto** [comment]
Hi @humphd , should I close this issue since we are already having a discussion issue #536 ?

**Comment by humphd** [comment]
@wlto good idea, let's continue this in #536 and follow-ups from that.
