### ISSUE TITLE
unable to discard working directory changes

### ISSUE THREAD

**Issue by ragnarokatz** [Seneca-CDOT/telescope#515]
**What happened**:
unable to discard working directory changes after pulling latest changes from upstream master:
![image](https://user-images.githubusercontent.com/33646954/70854100-0d3ff380-1e85-11ea-8dff-ec5516954738.png)

**What should have happened**:
after running `git checkout .` or `git checkout -- specfic_file`, the changed file in the working directory should be discarded.

**How to reproduce it (as precise as possible)**:
1. be on Windows OS
2. have an outdated local copy of telescope that is quite behind from upstream. The local copy should be clean and no changes in the current working directory.
3. `git checkout master`
4. `git pull upstream master`
5. `git push origin master`
6. `git status` to see the `.png` files that have been changed
7. run `git checkout .` or `git checkout -- specific_file` to attempt to discard the changes
8. `git status` to see that the changes are unable to be discarded

**Anything else we need to know?**:
running `git diff` shows the following:
![image](https://user-images.githubusercontent.com/33646954/70854142-a242ec80-1e85-11ea-8279-20119bc9f92b.png)

**Environment**:
- OS: Windows

**Comment by humphd** [comment]
Why are you doing `git pull origin master`?  Your fork's `master` shouldn't really be involved.

To fix this, I'd do `git checkout upstream/master src/frontend/img/feed-icon-10x10.png` etc.

I wonder if your `master` is way out of date, and missing the `.gitattributes` file you need to solve the CRLF issues?

**Comment by ragnarokatz** [comment]
oh that `git pull origin master` step is just an extra step for myself. I can be on either ubuntu or windows, so my local copy can be behind the `master` branch on `origin`. I've removed this extra step from the issue description above.
