### ISSUE TITLE
Use Let's Encrypt for certs on staging

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#519]
**What would you like to be added**:

When we ship to staging (and eventually production), we'll need proper certs that aren't self-signed.  We can [use Let's Encrypt](https://www.humankode.com/ssl/how-to-set-up-free-ssl-certificates-from-lets-encrypt-using-docker-and-nginx) for free.  We'll need to do this automatically when we push to staging.

**Why would you like this to be added**:

We'll need to run our app over HTTPS when not in a dev setup.

**Comment by manekenpix** [comment]
2 articles that I think could be useful for adding Let's Encrypt:
https://medium.com/@yash.kulshrestha/using-lets-encrypt-with-express-e069c7abe625
https://flaviocopes.com/express-letsencrypt-ssl/

**Comment by manekenpix** [comment]
I think @miggs125 wants to try this.

**Comment by humphd** [comment]
Assigned!  I spoke to @ctyler and he suggested we might want to start with some manual work to just generate and then copy/paste certs over.

BTW, I've filed #530 for the domains we'll need to get this working.  Let's Encrypt needs public domains to exist.
