### ISSUE TITLE
Add /feeds route to match what /posts does

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#523]
**What would you like to be added**:

Everything we did for the `/posts` route is going to be necessary for `/feeds` once we get `Feed` landed (#520).

One thing we'll have to consider is how to deal with active vs. inactive feeds, maybe via query string params?
 
**Why would you like this to be added**:

We're going to need a way to query the feeds we have, and get info out of them.

**Comment by manekenpix** [comment]
I'll work on this one after 0.5
