### ISSUE TITLE
Create domains for staging and production

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#530]
**What would you like to be added**:

We need domains for hosting our staging and production deployments.  @ctyler has said we can run these off of the cdot.systems domain.  We need to create both of:

1. telescope.cdot.systems for production
1. dev.telescope.cdot.systems for staging

**Why would you like this to be added**:

We're hoping to get things deployed during January, and we need a way to get at our systems via a domain.  We also need to get moving on SSL, which will require public domain names. #519 is related to this.

@ctyler what needs to happen for this to move ahead?  @manekenpix, do you have sufficient rights, or does Chris need to do it?

**Comment by manekenpix** [comment]
@humphd Chris will have to do it.

**Comment by humphd** [comment]
Assigning to @ctyler.

**Comment by humphd** [comment]
Via Slack, I see that the following domains now exist:

1. `telescope.cdot.systems` - production
2. `dev.telescope.cdot.systems` - staging

I think we can close this now.  @manekenpix agree?  Or do you have anything else we need to do?

One thing we should probably do is to add these domains (and what they each represent) to our docs.  Maybe a PR can happen for that and then we close this.

**Comment by manekenpix** [comment]
@humphd
> Maybe a PR can happen for that and then we close this.

I think that's a good idea.
