### ISSUE TITLE
Initial work on GatsbyJS based frontend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#531]
**What would you like to be added**:

Bootstrap the new [GatsbyJS](https://www.gatsbyjs.org/) based frontend.  I want to use a [monorepo](https://en.wikipedia.org/wiki/Monorepo) for Telescope, which means we will have to deal with having multiple projects (web server, web frontend, etc) all in the same repo.

In this issue, I'd like to see us add a new GatsbyJS project inside our repo living at `/src/app`.

**Why would you like this to be added**:

In discussions with devs on the team, I've heard a lot of interest in using frontend tooling like React and Components (#514) to build our UI.  I've also heard from multiple students who enjoyed working with [GatsbyJS](https://www.gatsbyjs.org/).

Since we're building a pretty simple UI, and it's heavily data driven and mostly static, [GatsbyJS](https://www.gatsbyjs.org/) should be a nice fit, and let us also leverage React at the same time.

This issue can be about getting a basic "hello world" type [GatsbyJS](https://www.gatsbyjs.org/) project bootstrapped into our repo, and connecting the various scripts so we can do development.  From there, we can start making it look, feel, and work the way we want.

I'm going to assign this to @agarcia-caicedo to lead, and she can pull in other people/delegate as necessary.

*NOTE: I suspect that we'll need to refactor our tree to better reflect that fact that we have more than 1 project in the repo.  After this code goes in, we'll essentially have 3 different projects all living in the tree: 1) a feed parser pipeline; 2) an Express web server; 3) a [GatsbyJS](https://www.gatsbyjs.org/) frontend web app.  We'll probably want to move these out of `src/` and into the top level to dirs like `/feed-parser`, `/api`, and `/app`.  But that can happen later.*

**Comment by humphd** [comment]
I filed #532 for the qraphql work.

**Comment by miggs125** [comment]
I would like to be part of front end

**Comment by humphd** [comment]
I notice that the [GatsbyJS repo](https://github.com/gatsbyjs/gatsby) itself does [exactly what I'm suggesting we do](https://spectrum.chat/gatsby-js/general/nesting-a-gatsby-site-within-an-existing-project~d8a0c112-fece-4a74-969c-5ba73e363200), namely, their website and docs are sub-dirs within the root of the project's monorepo.  See their [www/](https://github.com/gatsbyjs/gatsby/tree/master/www) directory as an example.

In our project root's `package.json`, we could augment the `install` script to also install deps in our Gatsby dir.  Assuming it lives in `src/app/`, we'd do something like this in `package.json` at the top level:

```json
"scripts": {
  "postinstall": "cd src/app && npm install",
  ...
}
```

Then when you run `npm install` from the root, it will also do it for the Gatsby app.

**Comment by miggs125** [comment]
Here are some screenshots of what I have been working on:

![telescope1](https://user-images.githubusercontent.com/32024054/72674727-26b9f980-3a48-11ea-9130-6ea133c05221.png)
![telescope2](https://user-images.githubusercontent.com/32024054/72674729-2b7ead80-3a48-11ea-9f10-394aab8125e1.png)
![telescope3](https://user-images.githubusercontent.com/32024054/72674731-2f123480-3a48-11ea-8cb7-6ce085cc9ac1.png)

The line beside "Telescope" on the header is supposed to be a hamburger button which toggles the sidebar. There are lots of bugs to fix and features we can add.
