### ISSUE TITLE
Add graphql support to our server

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#532]
**What would you like to be added**:

Expose the equivalent of our current `/post`, `/posts`, etc. REST endpoints as a [GraphQL](https://graphql.org/).  Much as [GitHub does with its API](https://github.blog/2016-09-14-the-github-graphql-api/), we can support both REST and GraphQL in parallel (maybe later we'll remove the REST API, but for now it's good to have it, since it's working).

**Why would you like this to be added**:

In #531 we're adding a [GatsbyJS](https://www.gatsbyjs.org/) frontend.  [GatsbyJS](https://www.gatsbyjs.org/) works best when used in conjunction with a [GitHub does with its API](https://github.blog/2016-09-14-the-github-graphql-api/) API (it can also use REST APIs, but with some loss of functionality).

The fastest path forward here is likely to [use express-graphql](https://graphql.org/graphql-js/running-an-express-graphql-server/).

Assigning this to @manekenpix, who said he wanted to work on it.  For now, I'll add this to the 0.5 project, but we might want to push it out to 0.6 if we run out of time.

**Comment by humphd** [comment]
Another interesting implementation I saw on Twitter: https://dev.to/apollographql/add-a-graphql-server-to-a-restful-express-js-api-in-2-minutes-4gdb

**Comment by manekenpix** [comment]
@humphd Thank you, I went with [express-graphql](https://github.com/graphql/express-graphql), but I'll take a look at Apollo to see how it works (mentioned in your link).

**Comment by humphd** [comment]
I'm happy for us to use any graphql implementation at this stage (we can change later), but let's pick whichever one is:

- best supported (getting updates, contributors, etc)
- most compatible with what we need for Gatsby (it might not make a difference, but let's confirm)

**Comment by humphd** [comment]
Once this is in, [these docs on using 3rd party graphql APIs](https://www.gatsbyjs.org/docs/third-party-graphql/) should be helpful.  cc @agarcia-caicedo.
