### ISSUE TITLE
Audit and Improve our Contributing docs for new Linux and Mac contributors

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#533]
**What would you like to be added**:

Go through our current docs for new developers in [README.md](README.md), [CONTRIBUTING.md](docs/CONTRIBUTING.md), etc. and figure out where we have shortcomings, what is unclear, what is in need of correction and make fixes. 

To help this happen in a realistic way, I'm going to ask that @cindyledev work with @yatsenko-julia.  @yatsenko-julia let's assign you your first issue in this project, and get you to set-up the environment, run the tests, run the app, and fix some code.  In doing so, you can work closely with @cindyledev to let her know what is confusing, missing, or needs fleshing out in our docs.  @cindyledev has extensive experience working with all aspects of the project, and can help you, or guide you to the right person.

I looked through the existing issues, and here are a few ideas you could work on in the next week or so:

1. https://github.com/Seneca-CDOT/telescope/issues/451 - we need to be able to generate SSL certs on Windows.  Currently we have a script for Linux/macOS, but not Windows.  If you're on Windows, this might be perfect.
1. https://github.com/Seneca-CDOT/telescope/issues/443 - we have a `/post` HTTP route, which returns HTML.  We want to also support requesting plain text if the client uses the `accept` header.  If you've worked with REST APIs and Express (or want to learn them), this would be good.  This will also need unit tests.

@yatsenko-julia please let me know which one of these you want to work on, and we'll assign it to you.  Also, I've sent you a request to join this project as a collaborator, which you'll need to accept so you can do admin tasks yourself.

**Why would you like this to be added**:

We want to make sure that a new developer coming to our project cold can get it set-up and running quickly, and without confusion.  Our app has a lot of complexity that might stump new developers, so we have to work hard to support them.

Ideally when @yatsenko-julia finishes her work, we'll have a much better sense of everything we need to fix in our docs, and hopefully we'll also have the fixes in place.

**Comment by yatsenko-julia** [comment]
Thanks, David. I guess I'll be working on #443 since I use Mac. My task is to fix the issue and at the same time look for things that are unclear to me in the documentation, right?  
Also, I am not sure I received any request to join the project.

**Comment by humphd** [comment]
@yatsenko-julia correct.  Because you're new to this project, you're in a perfect position to help us determine what is out-of-date, unclear, or missing in our documentation and on-boarding process for new community members.  Please keep a list as you go, and share your findings with all of us, but @cindyledev in particular, who is leading work on improving our docs in general.

You can use a combo of GitHub Issues and [our #telescope Slack channel](https://seneca-open-source.slack.com/archives/CS5DGCAE5) to co-ordinate this work.

**Comment by humphd** [comment]
NOTE: I went through a similar process with the [plumadriver project](https://github.com/Seneca-CDOT/plumadriver) this weekend, see my notes in https://github.com/Seneca-CDOT/plumadriver/issues/117.

**Comment by c3ho** [comment]
I checked the issue we were having in class with docker-compose up for Redis. @manekenpix  and I confirmed that part is working and can npm start telescope on Mac without natively starting Redis.

**Comment by cindyledev** [comment]
I have successfully completed the setup of our Telescope project on Ubuntu with Docker and on Mac with Docker as well. I ran into a few problems on Linux but I was able to figure it out; I had no problems on Mac. The documentations do need some work but not a lot so I'll make a formal write up soon. `npm run server` works.

@yatsenko-julia what problems are you encountering?

**Comment by yatsenko-julia** [comment]
@cindyledev I run the project during last class with a help of out classmates and everything worked fine. I believe that instructions should be updated, as it is hard to set up everything correctly if you follow what we have in set up section right now. I already created issues for the problems I found: [#555](https://github.com/Seneca-CDOT/telescope/issues/555) and [#554](https://github.com/Seneca-CDOT/telescope/issues/554).

**Comment by cindyledev** [comment]
This task has been completed for Linux and Mac. I'm opening a new issue for Windows users.
