### ISSUE TITLE
Add full-text indexing and search to our backend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#537]
**What would you like to be added**:

When we process feeds in our backend, and add them to Redis, let's also do full-text search indexing.

One common approach to this would be to use [Elasticsearch](https://www.elastic.co/products/elasticsearch):

- https://blog.logrocket.com/full-text-search-with-node-js-and-elasticsearch-on-docker/
- https://blog.patricktriest.com/text-search-docker-elasticsearch/

Since we're already using Redis, we could also try and use a Redis-backed solution:

- https://oss.redislabs.com/redisearch/index.html
- JS API https://github.com/stockholmux/redredisearch (not getting a lot of updates though...)

There are other options as well, so this needs some research.

I'll file a separate issue related to the REST API aspects of this.

**Why would you like this to be added**:

In the frontend, we're going to need to be able to search for things in old posts.  This will enable that to work.

**Comment by humphd** [comment]
Filed #538 to cover the web server aspect of this.

**Comment by manekenpix** [comment]
An option to consider: [FlexSearch](https://github.com/nextapps-de/flexsearch)
