### ISSUE TITLE
Remove GraphQL implementation

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#552]
**What would you like to be added**:

Our backend will soon incorporate [GraphQL](https://graphql.org/) support (#532 ) and we'll need tests for queries requesting both feeds and posts. 

Here is [a module](https://www.apollographql.com/docs/apollo-server/testing/testing/) for testing developed by the Apollo-server community.

Another possibility could be [easygraphql-tester](https://github.com/EasyGraphQL/easygraphql-tester).

**Why would you like this to be added**:

We need to make sure that our GraphQL endpoint answers queries correctly.

**Comment by c3ho** [comment]
Let's have this finished prior to 1.0

**Comment by manekenpix** [comment]
I was planning to do some work on this, but after seeing comments and discussions on slack, maybe we should close this and start thinking about the new fron-tend. Thoughts?

**Comment by humphd** [comment]
I think tests for the REST API and GraphQL endpoints would be good for any/all frontends we do, no?  I can't see a downside to you working on this.

Or, if you would rather, spec it out as bugs other students could do?

**Comment by manekenpix** [comment]
It's just that it seems our REST API fits better with the way Telescope works, and maybe we're going to end up removing all our GraphQL code (we barely use it), that's why I wasn't sure about spending time on this.

**Comment by humphd** [comment]
That's another way to go: rip it all out.  We should discuss with people and see what the consensus is.

I could go either way.

**Comment by humphd** [comment]
Morphing this to be about removing GraphQL, since we don't need it for next.js.

**Comment by c3ho** [comment]
![image](https://user-images.githubusercontent.com/18711727/97814904-948e8500-1c58-11eb-98c5-bafc33d4832d.png)
