### ISSUE TITLE
Block iframes from our sanitized HTML

### ISSUE THREAD

**Issue by Silvyre** [Seneca-CDOT/telescope#556]
**What happened**:

While running Telescope (via Ubuntu Desktop on VMWare), my Avast anti-virus consistently flags this one blog (URL in screenshot below) as malicious:

<img width="449" alt="Threat" src="https://user-images.githubusercontent.com/13500769/72737516-b7d6c080-3b6d-11ea-9b8c-3ce3c40cb177.png">

**What should have happened**:

The [HTML sanitizer](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/sanitize-html.js) is currently our only line of defense against malicious scripts.

If this script originates from a blog post on the pictured blog, the HTML sanitizer is not doing it proper job.

If this script does _not_ originate from a blog _post_, where is it coming from? How do we guard against malicious code from this unknown source?

_(Or, is it just a false alarm; a mistake on Avast's part?)_

**How to reproduce it (as precise as possible)**:

My set-up is mentioned: I'm running Ubuntu on VMWare and have Avast Web Shield enabled. After this person's blog feed is parsed, Avast throws this warning up. This appears to happen periodically, every five to ten or so minutes Telescope is running.

**Anything else we need to know?**:

Again, the origin of this script needs to be confirmed. Whether this is the fault of the HTML sanitizer, whether we require additional security measures (or whether Avast is overreacting) needs to be determined.

**Environment**:

- OS: see above
- Browser: N/A

**Comment by humphd** [comment]
I don't think this is malicious, just a parked domain,  I'm not sure why it's triggering Avast.  Here is what I get:

<details>
<summary>$ curl http://blog.jordantheriault.com/category/open-source/feed/</summary>
<pre>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
<title>Welcome blog.jordantheriault.com - BlueHost.com</title>
<link rel="stylesheet" href="//www.bluehost.com/media/shared/info/index/_bh/home.css" type="text/css" />
<link rel="stylesheet" href="//www.bluehost.com/media/shared/general/_bh/main.css" type="text/css" />
<meta name="description" content="Bluehost - Top rated web hosting provider - Free 1 click installs For blogs, shopping carts, and more. Get a free domain name, real NON-outsourced 24/7 support, and superior speed. web hosting provider php hosting cheap web hosting, Web hosting, domain names, front page hosting, email hosting.  We offer affordable hosting, web hosting provider business web hosting, ecommerce hosting, unix hosting.  Phone support available, Free Domain, and Free Setup." />
<meta name="keywords" content="web hosting, provider, php hosting,web hosting, free domain names, domain name, front page hosting, web site, web design, domain name registration, business web site, web site hosting, web space, picture hosting, small business, cheap web hosting, webmaster, web site builder, web space, affordable web hosting, marketing, cgi perl php hosting, blog, blogs, blogger, weblog, web log, weblogs, web logs, internet marketing, internet advertising" />
<script src="//www.bluehost.com/media/shared/general/cookies.js" type="text/javascript"></script>
<script type="text/javascript">
if (window.top !== window.self) {document.write = "";window.top.location = window.self.location; setTimeout(function(){document.body.innerHTML='';},1);window.self.onload=function(evt){document.body.innerHTML='';};}
</script>
<meta name="revisit-after" content="10">
<meta name="ROBOTS" content="NOINDEX, NOFOLLOW"> 
<script type="text/javascript" src="http://cdn.dsultra.com/js/registrar.js"></script>
<noscript><style type="text/css">.live_chat{display:none;}</style></noscript>
</head>

<body>
<div class="frame center">
<div class="content">
<div class="header">
<div class="header_top">
<div class="header_c h_tl"></div>
<div class="header_c h_tr"></div>
<div class="header_c h_bl"></div>
<div class="header_c h_br"></div>
<a href="http://www.bluehost.com/" rel="nofollow"><img alt="Bluehost" id="logo" src="//www.bluehost.com/media/shared/info/index/_bh/logo.jpg"></a>
<div id="divider"></div>
<div id="grad_break"></div>
<h1>Affordable, Reliable<br />Web Hosting Solutions</h1>
<a class="login_container" style='text-decoration: none; font-weight: bold;color:#FFF;width:inherit; font-size: 12px;width: auto;' href="http://www.bluehost.com/" rel="nofollow">Web Hosting - courtesy of www.bluehost.com</a>

</div>
</div>

<div style="padding-bottom:7px"></div>

<div class="body_container">

<div class="body_container">

<script type='text/javascript' src=//www.bluehost.com/media/shared/general/jquery/jquery.min.js></script>
<style>
.icontent {
    width: 1025px;
    height: 700px;
    border: none;
    margin-top: 4px;
    margin-bottom: 4px;
}
.frame {
    width: 1065px;;
}

.header_top {
    width: 1025px;
}
#grad_break {
    left: 334px;
}
</style>

<script>
    var gaJsHost = ("https:" == document.location.protocol) ? "https://ssl." : "http://www.";
    document.write("<scr"+"ipt src='" +gaJsHost+ "google-analytics.com/ga.js'></scr"+"ipt>");
</script>
<script>
    var pageTracker = _gat._getTracker("UA-9156498-1");
    pageTracker._initData();
    pageTracker._trackPageview("/parked/[% parked_type %]/blog.jordantheriault.com/[% request_uri %]");
</script>

<center>
        <iframe id="ad_frame" frameborder="1" height="800" scrolling="no" width="100%" src="http://www.iyfubh.com/?dn=blog.jordantheriault.com&pid=9POJB64QD"></iframe>
</center>

<hr class="bbar" />

</div>
</div>
<div class="frame_c frame_br"></div>
<div class="frame_c frame_bl"></div>
</div>
<div id="footer"><center>
    <ul class="footer_links">
        
        <li><a href="http://www.bluehost.com/cgi/help" rel="nofollow">Help Center</a></li>

        <li><a href="http://www.bluehost.com/cgi/info/contact_us" rel="nofollow">Contact Us</a></li>
        <li><a href="http://www.bluehost.com/cgi/info/about_us" rel="nofollow">About Us</a></li>
        <li><a href="http://www.bluehost.com/cgi-bin/partner" rel="nofollow">Affiliates</a></li>
        <li><a href="http://www.bluehost.com/cgi/terms" rel="nofollow">Terms</a></li>
    </ul>
    <div id="copyright">&copy;2012 Bluehost.com. All rights reserved.</div>
</center></div>


</body>
</html>
</pre>
</details>

**Comment by miggs125** [comment]
Interesting...when I looked at the site in class I found a hidden iframe which had a link but had height and width set to 0 and "display" set to "none" as if someone was trying to hide it. When I access the link now, I can only see the blue host header, no hidden iframe

**Comment by humphd** [comment]
Maybe they alter what you get served depending on the UA string?  I was coming at it via curl vs. a browser.  They may also be injecting it at runtime, which would help explain why it's not in the HTML above.

Regardless of intent, we should also deal with the case that a "feed" URL is returning something other than RSS/ATOM XML.  Probably #548 covers this case, but we should confirm.

**Comment by humphd** [comment]
Also, I was reading about our sanitizer, and currently `iframes` are allowed, see https://github.com/apostrophecms/sanitize-html#what-are-the-default-options.

**Comment by miggs125** [comment]
@humphd you answered my question before I could ask haha. I'm not sure we should allow iframes as these can be a security issue.

**Comment by humphd** [comment]
So I can tell you that in the past 15 years, there have been exactly `61` `<iframe>` elements used in all the blog posts to our planet.

As such, I think it's reasonable to consider removing support for them.  Want to do a PR to adjust that in our sanitizer, and add a test to confirm that it does?

**Comment by miggs125** [comment]
sounds good!

**Comment by humphd** [comment]
Let's fix this by blocking `<iframe>` elements in our HTML sanitizer.

**Comment by yatsenko-julia** [comment]
@humphd I am not sure I get  everything correctly. Do I need to add iframe tag to disallowedTagsMode?

**Comment by humphd** [comment]
You should do 3 things:

1. Add another test case to https://github.com/Seneca-CDOT/telescope/blob/master/test/sanitize-html.test.js that includes an `<iframe>` and make sure that it gets removed after being run through the sanitize HTML function.  Make sure the test fails
1. Splice `<iframe>` out of the array at https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/sanitize-html.js#L10
1. Make sure your test now passes
