### ISSUE TITLE
Divide our web API server from the feed parser

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#566]
**What would you like to be added**:

Our "backend" is really two separate things:

1. an express web API server, exposing HTTP REST/GraphQL endpoints and some UI.
1. a feed parsing service that runs forever and keeps downloading/parsing feeds of blog posts

The two are connected via a Redis database, in which they both share state (feeds, posts, etc).

Let's divide them into two separate node apps. 

**Why would you like this to be added**:

As we work toward deployment (#494), we're starting to think about leveraging scaling in our Kubernetes platform.  Let's say we need to scale the web server, adding more nodes to deal with increased traffic.  In our current code, that would mean we'd also add more feed parsers.

The architecture of our feed parser is that we have a single co-ordinator that adds feeds to a job queue, and then parallel, concurrent processes that get jobs from the queue and deal with them.  The data the the co-ordinator is working with doesn't grow like web traffic: we won't ever have 100,000 new student blog feeds suddenly show up and need processing.  We might see an increase of 50 or 100, but it's always going to be small.

Our co-ordinator service starts workers in the same node as itself, spinning up one worker per CPU core on the box.  So we might have 1 co-ordinator and 4 workers.  The workers run in their own process outside the co-ordinator.

We *could* further divide the app into 3:

1. an express web API server, exposing HTTP REST/GraphQL endpoints and some UI.
1. a feed parsing service co-ordinator that runs forever and keeps filling a queue with feed jobs
1. a worker that operates on feed jobs

This would allow us to scale the workers in response to the demands of the queue, but honestly, I think it's overkill: our data is always going to be tiny (Seneca students don't blog enough!).

But web traffic is always an unknown.  A post from a student *could* go viral and end up on Hackernews, suddenly bringing a ton of traffic.  In this case, being able to scale the web nodes up or down seems wise.

I want to see if we can do this in such a way that it doesn't complicate things too much for our developers (e.g., we can still use something like `npm start` to run both apps), and also that we do the necessary Docker/Kubernetes changes to make it work.

@Reza-Rajabi points out that we'll need to consider the healthcheck portion of separate apps, so that we don't leave any part of our code in an unreliable state.

**Comment by humphd** [comment]
Here's a proposal for restructuring our code:

```
/
├── web
├── app
├── feeds
├── lib
├── test
```

1. Get rid of `src/` and move things up to the top-level, dividing into the following directories
1. `web/` - our express-based web API server.  It would share data with the "feeds" app via Redis. This would be most of what we have now in `src/backend/web`.
1. `app/` - our GatsbyJS-based web app.  This would be most of what we have now in `src/frontend`.
1. `feeds/` - our pipeline service for processing blog feeds and posts into Redis.  This would be most of what we have now in `src/backend/feed`.
1. `lib/` - common code shared among our different apps.  This would be things like the config, logger, and other utils
1. `test/` - tests for any of our code.  This is the same as we have now

I'm leaving out other directories and files, since they aren't really affected by this.

Do you see any issues with this?  It would allow us to host 3 apps (2 servers and 1 web app) in the same monorepo, and build our Docker/Kubernetes infrastructure around these divisions more easily.

**Comment by c3ho** [comment]
Let's do this for post 1.0

**Comment by humphd** [comment]
Our work in https://github.com/Seneca-CDOT/telescope/projects/20 is going to do this, closing.
