### ISSUE TITLE
Add support for JSDoc and TypeScript type checking 

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#567]
**What would you like to be added**:

Let's add support for type checking in our functions based on arguments and return types using [JSDoc and @ts-check](https://ricostacruz.com/til/typescript-jsdoc).  This issue will be about adding the infrastructure to make it work, and in subsequent issues, we can work on adding annotations one file at a time.

We can engage new developers who want to join the project by getting them to pick a file and add type annotations to it via a "good first issue".

**Why would you like this to be added**:

We ran into an issue today where it wasn't clear if our linter was wrong, or our code was wrong with respect to `async` and `await`:

![bug](https://user-images.githubusercontent.com/427398/72821235-3ac74c00-3c3e-11ea-81c7-9d951336e040.png)

To answer this question, you have to understand the call graph fully, and whether or not any of the code being used here gets back a `Promise`.  The answer is [yes, we need `await`](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd), but you only know that if you go read a lot of docs.

It would be nicer if our code had some simple type annotations for what functions take in as parameters, and what they return.  Then we can use tools to help us figure out if our code is calling things the way it should.

We could switch over to TypeScript or Flow completely.  But I think we should walk before we run.  This will let us experiment with the benefits of some type checking, without taking on all the extra burden of limiting ourselves to pure TS.

**Comment by humphd** [comment]
I started to play with this, and it got messy really fast.  I'm going to pause on it for now, since I think it will cause a lot of churn until our code settles down a bit more.

**Comment by humphd** [comment]
I want to re-open this, and see if we can implement the ideas in https://css-tricks.com/typescript-minus-typescript/, which sound quite useful.

**Comment by manekenpix** [comment]
I'd like to help with this one. The project I'm currently on is in typescript (both front and back-end), so I'm comfortable using it. Also, I think @c3ho was also interested in this.

**Comment by chrispinkney** [comment]
With the backend being split up into multiple pieces this issue is starting to be too big to be managed at this time. At any time that we want to work on this, we should re-evaluate this and split it into multiple pieces.
