### ISSUE TITLE
Add static route to serve new GatsbyJS frontend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#569]
**What would you like to be added**:

Let's include static routes for our GatsbyJS web app.  This should work for the built version, and potentially for the development version as well (I'm not sure if that's ideal or if we should let Gatsby's dev server do it instead).

**Why would you like this to be added**:

We're adding a GatsbyJS app in #541, and we'll need to be able to build and host it with our web server.

**Comment by agarcia-caicedo** [comment]
I'll work on this issue

**Comment by humphd** [comment]
@agarcia-caicedo some thoughts on this, as you begin.

- When we're in development mode, it would be useful to have the Gatsby dev server setup to proxy requests to our other routes (graphql, rest apis, etc).  We can do that via https://www.gatsbyjs.org/docs/api-proxy/
- Based on those docs, I'm wondering if we should consider namespacing all of our web "APIs" with `/api`, for for example: `/api/graphql`, `/api/posts`, `/api/feeds`, etc.  cc @manekenpix for thoughts on this too.  We'll want to make sure that the React router in the frontend doesn't misinterpret requests to things at `/*` as pages in the Gatsby app, and unless we have some kind of top-level name, or if we can specify multiple names, it will be hard.
- When we we're in production mode (i.e., when `process.env.NODE_ENV==='production'` in the Express web server code), we'll want to add a static route for `/` to serve what's built in the `src/frontend/public` folder.  We could also tell Gatsby to put this folder in the root of our app, if that makes more sense.

There might be a way to have `/` work as we'd expect in development mode (i.e., have express proxy to the Gatsby dev server), I'm not sure.  But I think it's more common to run the frontend on a separate origin from the backend.

These are just some things I saw while researching other things tonight, in case they are helpful to this work.  Thanks for taking this!

**Comment by humphd** [comment]
@manekenpix in our new nginx staging/production setup, we should skip the express static routing completely, and let nginx do it for us.  That probably needs another issue, but I'll wait until the rest of the nginx stuff lands.
