### ISSUE TITLE
Wrong port used in env.example file

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#574]
**What happened**:

Currently, our `env.example` has:

`REDIS_URL=redis://127.0.0.1:6379`
`REDIS_PORT=6739`

In our `docker-compose-yml`, we use [`REDIS_PORT` with a wrong port number](https://github.com/Seneca-CDOT/telescope/blob/2074cc592a92c8a7d95f164f0a35aec45ca2fa55/env.example#L20) for deployment, and it crashes at launch.
The port number should be `6379`, as we use in `REDIS_URL`

Also, we should consider having only one var with the port number. We could combine them or just get rid of one of them.

**How to reproduce it (as precise as possible)**:

Run telescope with docker-compose using default values in `env.example` (`REDIS_PORT=6739`).

**Environment**

- OS:
Linux, Windows

**Comment by humphd** [comment]
Thank you for doing this today, this was a bad bug to have in master.
