### ISSUE TITLE
Deal with gatsby front end directories in .gitignore

### ISSUE THREAD

**Issue by miggs125** [Seneca-CDOT/telescope#579]
**What would you like to be added**:
certain directories in the frontend need to be prefixed in the project's root .gitignore file. Some of these include `public/` and `.cached` which are created when running `npm i`

**Why would you like this to be added**:
prefix directories we want to ignore in the frontend inside .gitignore

**Comment by humphd** [comment]
Things like `public/` and the like may need to get added, but things like `node_modules` are already covered.
