### ISSUE TITLE
Restructure frontend  components to include logic and style in component directory

### ISSUE THREAD

**Issue by miggs125** [Seneca-CDOT/telescope#584]
**What would you like to be added**:
Previously, style had been separated from react logic but as we are removing sass, we can restructure the frontend directory to include both logic and style, thereby keeping all parts of the component together

**Why would you like this to be added**:
This would make it easier to remove and replace components without too much stuff breaking. It also makes debugging a little easier.

This issue references #541

**Comment by cindyledev** [comment]
Closing. PR has merged
