### ISSUE TITLE
Fix hamburger button

### ISSUE THREAD

**Issue by miggs125** [Seneca-CDOT/telescope#585]
**What happened**:
The hamburger button is not styled to look like a hamburger. We need to fix this.
**What should have happened**:
The button should look like a hamburger button: 
![image](https://user-images.githubusercontent.com/32024054/72931222-7b50c380-3d2b-11ea-87bc-f6feb745922d.png)

**How to reproduce it (as precise as possible)**:
navigate to `/src/frontend/` and run `npm i` then `gatsby-develop`. Then go to `localhost:8000` and checkout the element to the right of the header title 

![image](https://user-images.githubusercontent.com/32024054/72931531-05992780-3d2c-11ea-8d4e-408d4d01dc26.png)

This issue references #541

**Comment by LuigiZaccagnini** [comment]
I can take this issue!

**Comment by humphd** [comment]
Great.  @LuigiZaccagnini please chat with @miggs125 and @agarcia-caicedo on Slack about any questions you have.

Assigning to myself so it's clear that this is being worked on.

**Comment by miggs125** [comment]
@LuigiZaccagnini 
> The sass for the hamburger-button is completely empty. How do we get the icon? Maybe if I know how we get it or what icon package  we use, I can fix this faster!

To answer your question, we are not using any icon packages for this. You can style the button using css or sass (which ever you prefer) inside the `hamburger-button` sass file. You then import this into the main.scss file. If you need to add any classes to the component, you can do so in the component file by adding it to the `className` property.

**Comment by miggs125** [comment]
I will be restructuring the frontend in the future to make this process easier
