### ISSUE TITLE
Improve frontend styling

### ISSUE THREAD

**Issue by miggs125** [Seneca-CDOT/telescope#586]
The frontend looks like it is a website out of the 90's. We need to style it to look like more of a modern web app.

**Comment by c3ho** [comment]
@wlto Would you be interested in this issue? I noticed you had a few discussions open regarding styling/design.

**Comment by wlto** [comment]
@c3ho Yep sure! I'll start working on it on Thursday perhaps?

**Comment by c3ho** [comment]
Great I'll assign this issue to you. Feel free to reach out to @miggs125 and @agarcia-caicedo  as they're the ones leading the charge for front-end related stuff

**Comment by wlto** [comment]
@c3ho Sounds good! Thanks!

**Comment by agarcia-caicedo** [comment]
@wlto have you used AdobeXD before?

**Comment by wlto** [comment]
Hi @agarcia-caicedo , no I haven't used Adobe XD before. But I've used Skecth, Photoshop and Figma. I think XD is a UI design software by Adobe with prototyping?

**Comment by miggs125** [comment]
@wlto I think photoshop should be good enough to create some styles for the UI.

**Comment by wlto** [comment]
@miggs125 Yep definitely. However, if possible, I would like to use Figma since it's web-based so others don't have to download and install it :)

**Comment by wlto** [comment]
This issue is currently being discussed in the `telescope-frontend` team.

**Comment by agarcia-caicedo** [comment]
I have made a figma file with the components. I'm open to trying using it alongside xd
