### ISSUE TITLE
Remove email-sender.js and related code

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#589]
We're not using email-sender.js anywhere and probably won't be using it in the future. We should remove it and anything in the env.example file connected to it. We can remove the nodemailer dependency in the package.json as well.

[More detail in this comment](https://github.com/Seneca-CDOT/telescope/pull/571#issuecomment-576957748)

**Comment by LuigiZaccagnini** [comment]
I can take this issue!

**Comment by humphd** [comment]
Go for it @LuigiZaccagnini.
