### ISSUE TITLE
Add filters to GraphQL to remove getPost

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#591]
**What happened**:

Recently #565 was merged and the way we store posts and feeds changed. That affected GraphQL, specifically our [getPost](https://github.com/Seneca-CDOT/telescope/blob/08c55d4d694cf7b8a2c37b7945606c792976191d/src/backend/web/graphql/index.js#L40) query. `getPost` was kept for legacy reasons, so this issue wont' prevent Telescope from serving all available posts.
Instead of patching `getPost`, it'd be better if we implement filters that would work with our getPosts query, that way we could filter by any subfield included in our Post type.

**How to reproduce it (as precise as possible)**:

Use the getPost query passing a `guid` as argument.

**Comment by c3ho** [comment]
#592 may or may not fix some of the concerns

**Comment by c3ho** [comment]
Got an issue with filters, Prisma doesn't support Redis as of yet... So all the documents on Apollo Server doesn't apply. I just spent 3/4 hours figuring this out.

**Comment by humphd** [comment]
I don't follow, we can connect to redis ourselves, we don't need Prisma afaict.

**Comment by c3ho** [comment]
https://www.howtographql.com/graphql-js/8-filtering-pagination-and-sorting/. I think to use any of this it relies on things generated by Prisma.

**Comment by humphd** [comment]
This stuff is more for when you have a really big database/query set, and need to automate a lot of the code.  For our needs, we're going to have a handful of things we need to return and query by.  Let's find a way to accomplish what we need without worrying about Prisma.

**Comment by c3ho** [comment]
Ok, so you're fine with the way I kind of had it in the blog to test out nested queries? I was trying to find some "elegant" way to do it like a traditional DB, instead of retrieving all the posts then filtering it.

**Comment by humphd** [comment]
I appreciate you trying to do this in an elegant, idiomatic way; but I want it to ship on time even more.  Let's go with the stuff you were doing in your blog, and refine that as we learn more about our needs.  Shipping Code > Perfect Code (that never ships).
