### ISSUE TITLE
Display reading time for every article

### ISSUE THREAD

**Issue by lozinska** [Seneca-CDOT/telescope#598]
**What would you like to be added**:

Add reading time for each blog post on the Telescope front end. 

**Why would you like this to be added**:
While we already have included npm package reading time into our project, we should use that code to display how long it will take to read certain blog post on the Telescope page.

**Comment by humphd** [comment]
I think we should consider moving this into our frontend.  It would be a lot cheaper to calculate it on the browser when rending the post instead of doing it for every post and storing that in Redis.  It's a really small amount of code to accomplish it.
