### ISSUE TITLE
Start using .env to configure our system

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#60]
In keeping with the [12 Factor App](https://12factor.net) approach, we need to move toward using environment variables so we can have a proper [config](https://12factor.net/config).

Let's use `dotenv` for this.  Here's a good discussion on how to set this up: https://www.twilio.com/blog/2017/08/working-with-environment-variables-in-node-js.html

Once we have the env system in place, we can start enabling/disabling parts of the system or features based on flags in our environment.  It will also make it easier to configure things like Redis in dev, CI, or deployment environments.

The first part of this should be to get an initial config file in place that we can add to over time.

**Comment by s-arika** [comment]
@humphd Could I try this one out?

**Comment by humphd** [comment]
@s-arika it's all yours.  Let us know how you make out with your research, and any questions you might have.

**Comment by hansal7014** [comment]
This would be useful for my issue too (#35 ). We can use an environment variable to set the log level.

**Comment by s-arika** [comment]
@humphd  If I create an .env.sample file and have the developer fills in the values for the keys in the .env.sample file and rename it as .env file is that ok? Or should I just create both an .env.sample file and .env file and put the .env file in .gitignore.

**Comment by s-arika** [comment]
@hansal7014 If you know the variables that you'll need, I could add them if you'd like

**Comment by manekenpix** [comment]
>  If I create an .env.sample file and have the developer fills in the values for the keys in the .env.sample file and rename it as .env file

I'd go with that option. Also, maybe we could call it .env.example?

**Comment by s-arika** [comment]
Yes sorry got confused, even if I create a .env file and ignore it, we'll still need the .env.example

**Comment by SeanPrashad** [comment]
Fantastic work on this @s-arika - I was wondering if we can close this issue now? 🤔

**Comment by s-arika** [comment]
Yup, thanks @SeanPrashad !
