### ISSUE TITLE
Switch to beforeExit from exit event on process

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#606]
Our code to handle the `exit` event should probably be using `beforeExit`, since it looks like [you can't run asynchronous code in the `exit` handler but can in `beforeExit`](https://blog.heroku.com/best-practices-nodejs-errors#node-js-exit-events):

```diff
diff --git a/src/backend/index.js b/src/backend/index.js
index c8d2591..7835fdf 100644
--- a/src/backend/index.js
+++ b/src/backend/index.js
@@ -12,7 +12,7 @@ require('./web/server');
 /**
  * Shutting Down Logic for most Server Shutdown Cases
  */
-process.on('exit', shutdown('exit'));
+process.on('beforeExit', shutdown('beforeExit'));
 process.on('SIGTERM', shutdown('SIGTERM'));
 process.on('SIGINT', shutdown('SIGINT'));
 process.on('SIGQUIT', shutdown('SIGQUIT'));
```

**Comment by jossiey** [comment]
What else I can do for this issue? Looks like you have fixed it.

**Comment by c3ho** [comment]
@jossiey it is not fixed, feel free to submit a PR for it
![image](https://user-images.githubusercontent.com/18711727/95163461-ea652f80-0775-11eb-9f35-b1321614089a.png)

**Comment by jossiey** [comment]
Thanks. I will handle with it.
