### ISSUE TITLE
Add UI dashboard support for Bull queues

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#62]
We're using Bull to manage our work queues, so let's also add a UI so we can see what's happening.  https://github.com/vcapretz/bull-board will give us the ability to add a route to a web server to show what's happening in our queues:

![](https://raw.githubusercontent.com/vcapretz/bull-board/master/shot.png)

Eventually this should be behind an admin login, but for now, we can expose it.  It will probably make debugging easier too.

**Comment by varshannagarajan** [comment]
I would like to look into setting this up. I could try and just start on setting this up while someone is working on issue #63  if that makes sense. Than add it to that server.

**Comment by neilong31** [comment]
@varshannagarajan I'd like to work on this with you if that's okay?

**Comment by varshannagarajan** [comment]
Yeah absolutely!

**Comment by humphd** [comment]
The Express web server just landed on `master` (thanks @miggs125)!  You can do this easily now.  Take a look at the code in `src/server` to hook your route into it.

**Comment by humphd** [comment]
Fixed in https://github.com/Seneca-CDOT/telescope/pull/200
