### ISSUE TITLE
Deal with 429 responses from medium.com, and other feeds

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#624]
**What happened**:

I noticed that [Tim's blog feed](https://medium.com/feed/@timfosteman) is showing on our 
old planet, but not on Telescope.  I took a look through the logs:

```
[ 2020-01-28 21:02:49.116 ] INFO  (80376 on brightness.local): [HTTP 429 - Too Many Requests] Feed not downloaded: https://medium.com/feed/@timfosteman
```

Most likely we're being rate limited, and it would be good to try and get the `Retry-After` value (if sent) so we can hold off before we attempt to request it again.

**What should have happened**:

We're probably hitting the site too often, and need to slow down our update rate

**How to reproduce it (as precise as possible)**:

I was able to reproduce this manually by running this curl command a bunch of times:

```
curl -I https://medium.com/feed/@timfosteman
HTTP/2 429
date: Wed, 29 Jan 2020 02:15:06 GMT
content-type: application/octet-stream
content-length: 59
set-cookie: __cfduid=d71f3769d4fd81234fc3a8896ffdc46791580264106; expires=Fri, 28-Feb-20 02:15:06 GMT; path=/; domain=.medium.com; HttpOnly; SameSite=Lax
cf-cache-status: DYNAMIC
set-cookie: uid=lo_Am9JI3p26hzR; Expires=Thu, 28-Jan-21 02:15:06 GMT; Domain=.medium.com; Path=/; Secure; HttpOnly
set-cookie: __cfruid=764ce017648591f95313a363a58144e49c585a94-1580264106; path=/; domain=.medium.com; HttpOnly; Secure; SameSite=None
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
alt-svc: h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
strict-transport-security: max-age=15552000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 55c7b249591af981-YYZ

Too many feed requests. See: https://medium.superfeedr.com
```

It doesn't give a `Retry-After`, and if I wait a few minutes it starts working again.  I can't find good docs on how long to wait, but I wonder if we should just wait for 1 hour when we hit this for a feed.

**Comment by humphd** [comment]
One way to approach this would be to [add a key to Redis for a feed, and give it a time to live (TTL) so it expires](https://redis.io/commands/setex) after some period (1 hour = 3600 seconds)

```
SETEX t:feed:ebbb25abaa:wait 3600 1
```

This would create a new key `t:feed:ebbb25abaa:wait` that includes the `id` of the affected feed, and give it a TTL of 3600 seconds (1 hour).  When we start a feed update process, we would look for `t:feed:{feed.id}:wait` and see if it exists.  If it does, we'd either quit right away, or check it's TTL to see how long we have to wait still, and log that.  Eventually Redis will expire this key, and we'll be able to continue processing the feed.

@Silvyre maybe you and I could try working on this one together when have time.  Let me know if you have interest.

**Comment by Silvyre** [comment]
This sounds interesting! I appreciate (and would like to accept) the offer to collaborate on this!

**Comment by Silvyre** [comment]
I plan to collaborate on this as part of Release 0.7
