### ISSUE TITLE
Create HTTP server 

### ISSUE THREAD

**Issue by miggs125** [Seneca-CDOT/telescope#63]
We need to create a web server for telescope. We should add what has been mentioned in #62 to this.

**Comment by humphd** [comment]
Great idea.  Something that this can eventually do is connect via `ioredis` to our Redis instance, and provide a way to query into our cache for posts, analytics, etc.

When you do this, it would be good to start with a health check endpoint, https://microservices.io/patterns/observability/health-check-api.html.

**Comment by humphd** [comment]
See also https://cloud.ibm.com/docs/node?topic=nodejs-node-healthcheck

**Comment by robertbegna** [comment]
if anyone isn't doing this, I'd like to set up a basic web server to start us off
