### ISSUE TITLE
nginx configuration for staging and production

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#634]
**What would you like to be added**:

A few things we should do in our nginx config for staging and production:

- setup nginx to [serve our static content](https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/) (e.g., GatsbyJS frontend) instead of the node app
- setup proper [caching for our endpoints](https://serversforhackers.com/c/nginx-caching) to reduce load on the node app

**Why would you like this to be added**:

The nginx server is better a certain tasks than our node app, and we should leverage it where possible.

**Comment by miggs125** [comment]
I'll take this
