### ISSUE TITLE
Add OPML endpoint export for feed list

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#64]
In #59 we're adding the ability to ingest our current feed list from the wiki.  In #63 we're adding a web server.  It might be nice to connect both of these and offer a way to get the feed list *out* of our app as an [OPML](https://en.wikipedia.org/wiki/OPML) file.  OPML seems to be the standard way of sharing a feed list these days.

What I envision is adding a route that allows for obtaining an XML file in OMPL format with all our student feeds included.  We might be able to use something like https://www.npmjs.com/package/@kohlmannj/opml-generator to do it.

**Comment by humphd** [comment]
Here's an example of what one looks like https://github.com/paulirish/frontend-feeds/blob/gh-pages/frontend-feeds.opml

**Comment by jrdnlx** [comment]
Hey, may I try to do this?
