### ISSUE TITLE
Create a blog component

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#643]
**What would you like to be added**: A component for blog posts 

**Why would you like this to be added**: Currently, the Gatsby posts don't show all the information we want from the posts. Additionally, they do bot make their best use of the space and do not fit our desired look for telescope.

What the blog posts should have: Post title, Date post was made, author, whole blog post content.

How the component should look like: 
![image](https://user-images.githubusercontent.com/49992710/73661355-ed98a080-4667-11ea-80b4-2691b5c3e112.png)

The bookmark does not need to be implemented. 
The space for the avatar should exist, but the logic to retrieve the avatar does not need to be implemented for this issue. 

Font for the title: Roboto Bold, color: #002944, font size: 3rem
Font for blog post: Lora, color: #000000, font size: 1.3125rem
Font for Author and Date: Lora, color: #A4D4FF, font-size: 1.3125rem

Author section color: #444444
Blog post section color: #9E9E9E
Title section color: #3670A5

**Comment by cindyledev** [comment]
Closing. Initial work in #659 and completed in #663
