### ISSUE TITLE
Switch from in-memory to Redis-backed session management

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#648]
**What would you like to be added**:

Let's switch from [express-session](https://www.npmjs.com/package/express-session) to [connect-redis](https://www.npmjs.com/package/connect-redis) for proper session management.

**Why would you like this to be added**:

We need to use a [proper session management provider](https://www.npmjs.com/package/express-session) in production with Express:

> Warning The default server-side session storage, MemoryStore, is purposely not designed for a production environment. It will leak memory under most conditions, does not scale past a single process, and is meant for debugging and developing.

**Comment by c3ho** [comment]
I'll take this issue on
