### ISSUE TITLE
Check if a feed is already added to the feed set before setting it to invalid

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#654]
**What would you like to be added**:
PR for #462 is going to land and the `setInvalidFeed` function within `src/backend/utils/storage.js` will need a check to see if the feed exists before it can be invalidated

**Why would you like this to be added**:
Before a feed is invalidated (added to the Invalid Feeds set), it should be added to the Feeds set

**Comment by humphd** [comment]
Fixed by https://github.com/Seneca-CDOT/telescope/pull/639
