### ISSUE TITLE
Remove /planet/compare route

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#660]
**What would you like to be added**:

Remove the `/planet/compare` route that got added in https://github.com/Seneca-CDOT/telescope/commit/4770bad385eee1899a91d6142b73f0e0b5bcfc65

**Why would you like this to be added**:

My beloved CDOT planet is now officially dead:

<img width="581" alt="Screen Shot 2020-02-05 at 6 58 02 PM" src="https://user-images.githubusercontent.com/427398/73894267-f21caf00-4849-11ea-8294-acc54dc2fcef.png">

:(

**Comment by c3ho** [comment]
I'll help put this poor route out of its misery
