### ISSUE TITLE
Nested Queries in GraphQL

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#665]
**What would you like to be added**:
GraphQL filters should be going in soon (crosses fingers), we should get nested queries going in too.

**Why would you like this to be added**:
Gives our front-end people more flexibility when using GraphQL APIs

**Comment by c3ho** [comment]
@manekenpix you've previously done work/research on nested queries so I'm going to volunteer you for this.

**Comment by manekenpix** [comment]
Nice, I'll need your help since you worked on the filters so we can come up with something good combining filters and nested queries.

**Comment by c3ho** [comment]
Closed via #718.

**Comment by manekenpix** [comment]
I think I can do some more work with this one.
