### ISSUE TITLE
Compare our nginx config with Mozilla's recommendations

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#668]
**What would you like to be added**:

Let's make sure our ngix config is correct in terms of security.

**Why would you like this to be added**:

Mozilla has a really [good tool](https://ssl-config.mozilla.org/) for [safely configuring your server](https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_Server_Configurations).  Let's compare what we have to what the recommend and adjust as necessary.

**Comment by c3ho** [comment]
#691
