### ISSUE TITLE
Use helmet security module for our express server

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#669]
**What would you like to be added**:

Let's add the [helmet](https://www.npmjs.com/package/helmet) module to our express server, and start tightening our security practices.

There are a lot of things we can enable with helmet, and not all of them will make sense.  We can start with:

```js
app.disable('x-powered-by')
```

**Why would you like this to be added**:

We want to get ready for production and our 1.0, and we should begin by taking security more seriously.

**Comment by c3ho** [comment]
Can take this issue on. Did you want to use default settings?

**Comment by c3ho** [comment]
@humphd did you want to disable it.. or [fake](https://helmetjs.github.io/docs/hide-powered-by/) it?

**Comment by humphd** [comment]
Disable.
