### ISSUE TITLE
Running both ESLint and Jest together

### ISSUE THREAD

**Issue by ImmutableBox** [Seneca-CDOT/telescope#67]
Currently ESLint and Jest is run by using different commands:
`npm run eslint`
`npm run eslint-fix`
`npm run jest`

Would be nice that have something like a prescript as @UltimaBGD suggested to run these commands.

### More information/options:
- - -
@humphd :
the && operator won't work on all shells (e.g., many Windows shells). There are few work arounds for this: 
1. we can use pre and post scripts to run things before/after other steps, https://docs.npmjs.com/misc/scripts
2. we could use https://www.npmjs.com/package/npm-run-all to allow for a set of steps

In general, we have to be careful that our scripts work on Windows, since so many common tricks like this will fail :(
- - -

**Comment by UltimaBGD** [comment]
I'll get something up really quick.

**Comment by UltimaBGD** [comment]
This was worked on and merged via #69.
