### ISSUE TITLE
Wrong path to telescope's cert files

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#674]
**What happened**:

After using our script for SAML setup, a `certs` directory was created inside of the `tools` directory.
At launch, telescope shows this error:
```
[ 2020-02-07 11:20:52.301 ] ERROR (6466 on spain.cdot.systems): Unable to load certs/key.pem
    error: {
      "errno": -2,
      "syscall": "open",
      "code": "ENOENT",
      "path": "/home/josue/Projects/telescope/certs/key.pem"
    }
```
Telescope is trying to load `key.pem` from `telescope/certs`, but the folder `certs` was created in the `tools` directory. The path should be `telescope/tools/certs`.

**How to reproduce it (as precise as possible)**:

Execute `generate-ssl-certs.sh` in the `tools` directory and then launch telescope.

**Environment**:

- OS: Fedora 30
- Browser:

**Comment by humphd** [comment]
Let's move the path for loading the certs into the `.env` so that we can do a better job indicating where they are.  I also want this badly for the SAML setup on staging, so I can connect with your Let's Encrypt certs.
