### ISSUE TITLE
Add documentation for staging + production deployment

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#680]
**What would you like to be added**:
Now that #649 landed, we need documentation to setup the staging server, including information about our settings for the [staging docker-compose file](https://github.com/Seneca-CDOT/telescope/blob/master/docker-compose-staging.yml), [nginx config file](https://github.com/Seneca-CDOT/telescope/blob/master/nginx.conf), [certbot](https://github.com/Seneca-CDOT/telescope/blob/f6253bf0fe21e9dbacdbe412becd19a810470231/docker-compose-staging.yml#L62) and [SSL](https://github.com/Seneca-CDOT/telescope/blob/f6253bf0fe21e9dbacdbe412becd19a810470231/nginx.conf#L11).

**Comment by humphd** [comment]
For sure we need this before @manekenpix is allowed to leave Seneca!
