### ISSUE TITLE
Reduce size of telescope Docker container

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#682]
**What would you like to be added**:

Audit our Dockerfile, and see what we can do to trim it down.  I did an initial experiment tonight:

```diff
diff --git a/Dockerfile b/Dockerfile
index daa9093..55abf83 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -10,7 +10,7 @@
 # Dockerfile

 # Use `node` long term stable image as the parent to build this image
-FROM node:lts
+FROM node:lts-alpine

 # Use Redis image via compose-file

@@ -25,7 +25,7 @@ COPY .npmrc ./
 COPY . .

 # Install all Node.js modules on the image
-RUN npm install --no-package-lock
+RUN npm install --no-package-lock --production

 # Build Frontend before deployment
 RUN npm run build
```

This only installs production node dependencies, and no devDependencies.

That resulted in this size change:

```
$ docker images
telescope_telescope           latest              fc16ffa3cfd5        36 seconds ago      640MB
<none>                        <none>              b7e07ea508dc        About an hour ago   1.91GB
```

That's a 1.2G saving!  The `node:lts` image alone goes from `913MB` to `85.2M` with `node:lts-alpine`, which is huge.  There are details about trade-offs using `-alpine` based node images [here](https://github.com/nodejs/docker-node#nodealpine).

**Why would you like this to be added**:

The Docker container is getting big, and build times are long.  It's hard to people on under-powered machines to run it at all.

There's probably lots more we can do to reduce this size.

cc @manekenpix, @c3ho, @raygervais

**Comment by manekenpix** [comment]
Also, we can consider the same option for the other images used in our `docker-compose.yml` and `docker-compose-staging.yml` files.
-  [redis:alpine](https://github.com/docker-library/redis/blob/b6d413ceff3a2bca10a430ace121597fa8fe2a2c/5.0/alpine/Dockerfile)
-  [nginx:alpine](https://github.com/nginxinc/docker-nginx/blob/5971de30c487356d5d2a2e1a79e02b2612f9a72f/mainline/alpine/Dockerfile)

Maybe not all of them have to be alpine, but I think it's worth giving a try.

**Comment by raygervais** [comment]
Alpine was designed from my understanding for containerization, at the cost of many build tools and libraries being missing from the base image. Their lack of glibc truly does make building and running certain applications border-line impossible. Still, if there is an Alpine for Node, Redis, NGINX, I say go forward with using it if possible. 

The other item that we should explore @humphd is multi-stage Docker builds, which enable us to save the final container (which contains the output/`dist` files alone) and discard the rest. For a Gatsby project, this greatly reduces container size further I imagine.
I had suggested this previously while looking into CircleCI after noticing the size of the containers and dependencies: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by humphd** [comment]
My sense of the `alpine` stuff is that it either works or doesn't with musl vs. glibc, so we can test and see how it goes.  The redis container is already pretty small, but for the node container, it's a huge win.

I love the idea of doing multi-stage builds to throw away build artifacts.  Some notes:

- we have a 2 stage build for our node app(s).
- `npm install` will install the stuff you need for the server api and feed pipeline (we should split these into two apps at some point, #566)
- after `npm install` finishes, we have a `postinstall` script that goes into `src/frontend` and also runs `npm install` there for the Gatsby stuff
- when Gatsby is built, we'll generate a bunch of stuff in `src/frontend/.cache` that probably isn't needed, but `src/frontend/public` will be.
