### ISSUE TITLE
Allow authentication tokens to make it through nginx proxy

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#691]
Our login on staging doesn't work correctly anymore:

<img width="973" alt="Screen Shot 2020-02-09 at 11 23 42 AM" src="https://user-images.githubusercontent.com/427398/74105761-a65e5400-4b2e-11ea-8121-0f7e6c489a3c.png">

I think the issue here is that our HTTPS ngnix reverse proxy to the node app is not allowing authentication headers to pass through to the client.

I'm not 100% how to fix this.  Some initial reading points at http://nginx.org/en/docs/http/ngx_http_auth_request_module.html and also these extra nginx config settings:

```
       proxy_pass_header  Authorization;
       proxy_set_header Authorization $http_authorization;
       proxy_pass_request_body off;
       proxy_set_header Content-Length "";
       proxy_set_header X-Original-URI $request_uri;
```

We might also need to do something in our node app to have it trust tokens that have come across from a proxy.

**Comment by c3ho** [comment]
I’ll take this issue on, want to learn about this stuff.

**Comment by humphd** [comment]
I ran into another issue with login today on HTTPS for staging.  When I try to login, our express server is using a GET request to `/auth/login/callback` but it should be a POST.

You can try to Login on https://telescope-eq0rhvdfk.now.sh/ and after you do, you'll see that it gives a 404 while trying to GET `/auth/login/callback`.  We have that, but it's POST.

**Comment by humphd** [comment]
@c3ho @manekenpix, have we covered all this?  I think it's working well.  Can we close this?

**Comment by humphd** [comment]
I'm going to close this until we hit a bug that relates to needing it.
