### ISSUE TITLE
Logout Needs to be fixed on the express server

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#694]
**What would you like to be added**:
I would like to add the ability to logout of our site, you can login, and currently you are there forever.

**Why would you like this to be added**:
Let's remedy that so people can leave telescope.

**Comment by humphd** [comment]
@Grommers00 linked me to to this article suggesting we not bother with logout: https://uit.stanford.edu/service/saml/logout at all.  Another option to consider.
