### ISSUE TITLE
Simple Text Analysis

### ISSUE THREAD

**Issue by UltimaBGD** [Seneca-CDOT/telescope#7]
As stated in the overview document, we would like to implement some form of text analysis.

Simple text analysis: Word Length, Reading Time, Writing level, etc

Would be the focus for this issue. This can most likely be developed as a stand alone feature before being integrated into the project. In essence, it can be developed to work on some text, and when the project is advanced enough to support the integration of this feature, easily integrated.

This train of thought could also work for checking the zero content posts, but that may be better to leave for another issue.

I would like to work on this, are there any ideas or ways to improve it that anyone has in mind?

**Comment by jatinAroraGit** [comment]
Hey @UltimaBGD and @humphd ,
We can also implement npm packages that already does this and on top can provide certain characteristics of a post like sentiment, writing level and support more languages other than English.
I can look for some packages that can do this.

**Comment by humphd** [comment]
@jatinAroraGit exactly!

```js
const { someExistingFunctionWeWant } = require('external-module');

// Wrap the call to some external API we use in a promise
module.exports = exports = async function(text) {
   // If the code we use is not promise based, do that, or just return the promise
   const value = someExistingFunctionWeWant(text);
   return Promise.resolve(value);
};
```

**Comment by jerryshueh** [comment]
If we're doing any sort of NLP at all, I recommend we use Python for this particular module. The support for data science work on Python is fantastic, with many libraries and modules we can use that require just single lines of code to run. We can export the final metrics out in a CSV file for use by the core systems, or even a JSON file if we need more semantics. Just my two cents - I've personally never done any actual text analysis work in node.js, so I can't attest to the conveniences and challenges of doing so.

**Comment by humphd** [comment]
@jerryshueh you can run models pretty much in any backend ML engine (tensorflow has bindings for c++, python, node, and the browser), but we can also leverage other tools as well.  Our wrappers can return JSON, agreed, and then we can connect them to REST endpoints for others to consume.

Let's not worry about which tech we use at this point, and focus instead on which analysis we want to do.  Let the requirements (and existing code/stack) drive our decisions.

**Comment by cyh0968** [comment]
I think we can use [reading-level](https://www.npmjs.com/package/reading-level) to measure the level of writing.

**Comment by UltimaBGD** [comment]
That seems like a good plugin!

**Comment by humphd** [comment]
This is underway in numerous PRs now and follow-up Issues with more specific details.  Closing in favour of the work happening there.
