### ISSUE TITLE
Add a .md file to discuss the modules/dependencies being used 

### ISSUE THREAD

**Issue by asyam1** [Seneca-CDOT/telescope#70]
Since we will be using NodeJS, it will be appropriate to have a discussion page to add or remove modules/dependencies. It would also help others to understand why a particular module is used and how it will help the project.

**Comment by robertbegna** [comment]
i can work on this

**Comment by asyam1** [comment]
@robertbegna I am currently working on it, once modules.md file gets uploaded to the project, feel free to update the information or add missing modules

**Comment by asyam1** [comment]
@robertbegna oh I see that you have already made the file and changes, thanks

**Comment by robertbegna** [comment]
@asyam1 yep feel free to add changes to it, could you also review my pull request and help me get it merged thanks!

**Comment by humphd** [comment]
I'm going to close this, I don't think we need it.
