### ISSUE TITLE
Change storage.js to support the adding of feeds

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#706]
**What would you like to be added**:
We need to change code in `storage.js` to allow new namespaces:
- `t:user:` to store feeds for individual users, one user can have multiple feeds for example `t:user:user@myseneca.ca` can contain a feed for OSD700 and one for SPO600

We'll need a new redis key called `t:users`

We need additional functions to:
- create the keys with the namespaces
- add feeds to a user, if we don't have the user yet, create a user then add feed
- identify feeds already existing in wiki feeds, we'll tag them with admin so an existing feed such as `t:feed:ab3b313` will become `t:feed:ab3b313:admin` since we won't have a user to attach to them.

So in the end we'll have the following sets:
- users --> contains all the users and their respective feeds
- feeds --> contains all feeds
- posts --> contains all posts

`storage.js` is code we use to interact with Redis, `feed.js` and `post.js` will also have to be updated to also use the new code that will be written in `storage.js`. However we'll only focus on updating `storage.js` code in here for now.

**Why would you like this to be added**:
We need additional functionality to support the adding of feeds

**Comment by c3ho** [comment]
For all issues mentioned, feel free to refer to this:
![image](https://user-images.githubusercontent.com/18711727/74402301-d6894980-4df1-11ea-8be5-6faee6422c9d.png)

**Comment by Grommers00** [comment]
So I'm not sure, but I think @humphd added this feature with the create function in `../../data/feed.js `

**Comment by Grommers00** [comment]
This next step will probably have to be added in 0.8.

**Comment by humphd** [comment]
I'm still trying to decide the best way to approach this.  My goals are:

- store as little data as possible about authenticated users.
- expose as little of what we store via APIs as possible.
- keep the design simple.

User A authenticates with the SSO provider.  We get back a "profile" object that has some data, probably email, username, a user id, etc.

User A wants to add a feed.  When we create that feed, we can stamp it with the user's info somehow (maybe add their `uid` or `email` or some other piece of public profile data to the `Feed` object).

A few days later, User A returns and wants to see all her feeds again.  This means we need a reverse lookup that shows us all of User A's feeds.

That might be enough.  Maybe we should also keep a set of users `t:users` that has all the unique user ID's we've had add feeds.

## TODO:

1. Make it possible for "user" info to get added to a Feed when we create it.  It should also be possible to have this be null, indicating a feed doesn't belong to a particular user (e.g., the wiki feed list we import won't have any user info).  The alternative here is to use some default "admin" kind of user info in those Feeds, but `null` probably does the same thing.
1. We need to create a set of feeds for a user, `t:user:{userid}:feeds`, so we can find all the feed ids for this authenticated user.
1. Maybe add a set for `t:users`, holding all the "userid" values that own feeds.

**Comment by humphd** [comment]
I think this can be closed now, as we have coverage for everything in other issues.  I want to try and do a bunch of it without modifying the backend significantly.
