### ISSUE TITLE
Create a design for a page to allow users to add feeds

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#708]
**What would you like to be added**:
Create a design/mockup for users to add feeds

**Why would you like this to be added**:
Once #706 and #707 goes in, we need to update Gatsby to use the updated code from those two issues.

**Comment by cindyledev** [comment]
This can be broken up into smaller issues:
1) mockups and maybe prototype (I'm getting clarification on what prototype is)
2) implementing the design

Additional information:
This is how we're adding feeds right now https://wiki.cdot.senecacollege.ca/wiki/Planet_CDOT_Feed_List
Let's make adding feeds to Telescope better than this :)

**Comment by c3ho** [comment]
@cindyledev changed, thanks!

**Comment by cindyledev** [comment]
Design mockups were posted [here](https://github.com/Seneca-CDOT/telescope/issues/725#issuecomment-586726492) as a comment. 

Closing this issue. To be continued in #725.
