### ISSUE TITLE
Create relational database and its interface to store all information from parsed feeds

### ISSUE THREAD

**Issue by mskuybeda** [Seneca-CDOT/telescope#71]
I would like to implement the MySql to store data from parsed feeds and overall information about posts. I think we will also need to have an interface for the server so back end scripts can exchange data. The data about that posts also needs to be properly organized  and structured. As a result, there should be a js script which gets infromation from MySql and format it into JSON so other back end scripts can use it. 

If you want to jump in and help me with MySql organization, feel free to join discussion.

**Comment by mskuybeda** [comment]
The parsed data from [Issue#16/PR#37](https://github.com/Seneca-CDOT/telescope/pull/37) can be stored in this database and can be communicated using js script. I will attempt to implement both. But feel free to give me suggestions.

**Comment by humphd** [comment]
Let's try and do this with Redis first.  We probably don't need anything else.  You can use `ioredis` from npm to work against the Redis instance.

**Comment by izhuravlev** [comment]
Hey @humphd  @mskuybeda, 
I am interested in working on data storing via Redis. Can I help?

**Comment by mskuybeda** [comment]
@humphd Okay, we will move on with redis. The requirements and script will still kind of be in the same work load. 

@izhuravlev Sure, we can work on these together if we can split it all of these into 4 pull requests so we both get a grade. @humphd is it a possiblity to for example create the database structure together and both of us get a grade? Its kind of a big pull request if compared to existing ones.

**Comment by izhuravlev** [comment]
@mskuybeda Thank you!
I believe we can probably separate this into two issues that will be correlated: one for Redis data storage implementation and another one for data retrieval script.

**Comment by izhuravlev** [comment]
I will start researching Redis, `ioredis` and will post here as soon as I have any updates.

**Comment by mskuybeda** [comment]
@izhuravlev I wanted to do both and already started on database design. We can cooperate on that if you want.

**Comment by mskuybeda** [comment]
@humphd I will do the functionality to pass the parsed data made by @cryolis as a pull request. It will be passed to redis db which can be implemented in the next couple of weeks. I will use this issue as a branch

**Comment by humphd** [comment]
"next couple of weeks" is not going to work.  I'm looking for something "this week."  We already have a Redis database attached to our project.  All you need to do is use https://github.com/luin/ioredis to connect to it from node.js, and store your data in a key.

**Comment by humphd** [comment]
@mskuybeda's initial work on this to connect with redis has landed on `master`.  I'm going to close this, and file some follow-up issues to build on it.
