### ISSUE TITLE
Frontend code cleanup

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#712]
**What would you like to be added**:
Go through the frontend code and ensure its being done the proper way (Some research required)
Utilize Gatsby things, such as
- Proper React procedures
- Use `<Link>` instead of `href=`

**Why would you like this to be added**:
Our code should be consistent and utilize as much Gatsby as possible

**Comment by humphd** [comment]
@cindyledev can we close this?  If there are things to fix now, we should probably file more specific bugs.

**Comment by cindyledev** [comment]
Yeah let's close this and file more specific issues when  they come up
