### ISSUE TITLE
Improve docs for prettier/eslint/vscode environment setup

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#715]
Prettier is creating a lot of errors for people. 

Can we post below and include the 
OS
Issue
How to replicate the issue

**Comment by humphd** [comment]
I'd like some more info on this.  I've seen first hand that it doesn't work on James laptop.

@Grommers00 can you try some things for me?

- delete your `node_modules` folder
- confirm that you're on `master`, and it's exactly the same commit as the `upstream`
- make sure you version of node.js is `12.*.*` and update if it's older than that.
- make sure your version of VSCode is `1.42.0` and update if it's older than that.
- run `npm install`
- follow [these instructions](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) to install workspace recommended extensions
- confirm you have all of these extensions installed: 

```
    "editorconfig.editorconfig",
    "dbaeumer.vscode-eslint",
    "esbenp.prettier-vscode",
    "streetsidesoftware.code-spell-checker"
```

Let's start there and give me more info.

**Comment by Grommers00** [comment]
Okay - so I was never npm installing before, as I exclusively ran everything with docker previously.

npm install fixed this for me, I also had prettier/eslint already installed previously as extensions on visual studio code!

Thansk @humphd 

@cindyledev not sure if this will help you?

**Comment by humphd** [comment]
Great, I'll morph this into a bug about fixing our docs to be more clear on how to set this up.

**Comment by cindyledev** [comment]
@Grommers00 um I never had any Prettier or ESLint errors, did you tag the wrong person?

**Comment by Grommers00** [comment]
> @Grommers00 um I never had any Prettier or ESLint errors, did you tag the wrong person?

Perhaps. It was @lozinska

**Comment by lozinska** [comment]
@Grommers00 that's right I have same problems. Will reproduce steps that was mentioned earlier and let see if it will fix for me
