### ISSUE TITLE
Create a User class

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#717]
**What would you like to be added**:
We currently have a feed class in `feed.js`, a post class in `post.js`, but we need one more, a user class in `user.js` to use the functions we are going to add to `storage.js` in #706 . Good references would be the other existing classes we have currently to give you an idea.

All code that interact directly with Redis will be in `storage.js`, any code that uses the functions we created in `storage.js` will be used by either `feed.js`, `post.js` or the yet to be created `user.js`

**Why would you like this to be added**:
We need this to allow users to add feeds

**Comment by humphd** [comment]
The way we've done our users, I think we can simplify this so that it's only doing queries for the currently logged in user.  Here is what I'd suggest:

1. We modify the serialize/deserialize code in our SamlStrategy passport.js code to build a more functional `User` Object based on the value of `req.user.id`.
1. The `User` type should allow for getting any feeds/posts owned by this user.  This means supporting things like:

    ```js
    // Get Feeds for this user
    let feeds = await user.feeds();
    
    // Get Posts belonging to Feeds owned by this user (can use feeds() to help get this data) 
    let posts = await user.posts();
    
    // Check if a user owns a given feed or feed id (returns true/false)
    if(user.owns(feed)) {...} 
    ```

**Comment by humphd** [comment]
From our call:

```js
  // Add session user object de/serialize functions. We put the whole
  // user object on the session unaltered.
  passport.serializeUser(function (user, done) {
    // Create the object that you store on req.user (serialize into request)
    done(null, user);
  });
  passport.deserializeUser(function (user, done) {
    // Deserialize from request (rehydrate) back into a usable Object

    /**
     * function User(id, name, email) {
     *   this.id = id;
     *   ...
     * }
     *
     * // Get all feeds that belong to this user
     * User.prototype.feeds = async function() {
     *   const id = this.id;
     *   const feeds = await Feeds.all(); // [ feed, feed, ... ]
     *   return feeds.filter(feed => feed.id === id);
     * };
     *
     * // Does this user own a given feed/feed-id?
     * User.prototype.owns = async function(feed) {
     *  if(typeof feed === 'number') {
     *    return this.owns(Feed.byId(feed));
     *  } else {
     *    return feed.user === this.id;
     *  }
     * };
     * 
     * class Admin extends User {
     *   owns() {
     *     return Promise.resolve(true);
     *   }
     * }
     * 
     */

    let u = new user(user.id, user.name, user.email);
    // Pass this new user object on so it attaches to req.user
    done(null, u);
  });

 /// Later on in your routes:
feeds.post('/', protect(), async (req, res) => {
  let user = req.user;
```
