### ISSUE TITLE
Create test for feed-parser

### ISSUE THREAD

**Issue by ImmutableBox** [Seneca-CDOT/telescope#72]
A test is needed for feed-parser once https://github.com/Seneca-CDOT/telescope/pull/37 is merge. You can start working on this now, can be a basic check to see if feed-parser returns values.

Can check if the feed-parser is able to parser these blogs below:
- [Blogger](https://www.blogger.com/about/?r=1-null_user)
- [Medium](https://medium.com/)
- [Wordpress](https://wordpress.com/)

`feed-queue.test.js` can also be removed once some actual tests are added since the test doesn't accomplish much https://github.com/Seneca-CDOT/telescope/pull/55.

**This doesn't need to be all implemented in one pull request, can be separated into multiple issues.**

Test are written in [Jest](https://jestjs.io/docs/en/getting-started).
Commands to run test: `npm test` or `npm run jest`

Save test under `test` folder.
Save test as `testname.test.js` replacing `testname` with the name of your test.

**Comment by nazneennahar** [comment]
hey i would wanna work on this issue.

Thanks.
