### ISSUE TITLE
Create a search bar component

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#721]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/49992710/74490791-b744f780-4e97-11ea-9bf7-5fa37b53f174.png)

The component should look like this. 
The drop down menu should currently only have "Author" as an option.

Assets: 
Drop down background and search button colour:
#3670A5
Drop down text colour and icon colour:
#002944
Placeholder text colour: 
#6E6E6E
Search input background colour:
#9E9E9E

Font: Roboto

Shadow: x: 0, y: 5 B:10 #000000 with 0.5 opacity

**Why would you like this to be added**:

This needs to be added to be able to use a search function

**Comment by cindyledev** [comment]
Maybe
- https://material-ui.com/components/selects/#customized-selects
- https://material-ui.com/components/app-bar/#app-bar-with-search-field
