### ISSUE TITLE
Create an Author Result Component

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#722]
**What would you like to be added**:
A component that shows the author as a result of a search need to be created. It should look like this:

![image](https://user-images.githubusercontent.com/49992710/74491462-a39a9080-4e99-11ea-831f-01086288745c.png)

The avatar picture does not need to be implemented at this time.
The last post should be a link the last post the author made.
The more>  will currently not connect to anything

Assets: 
Font: Roboto
icon colour: #3670A5
font color: #002944
Text section background colour: #9E9E9E
Avatar section background color: #444444

**Why would you like this to be added**:
This is part to implement the search functionality

**Comment by humphd** [comment]
There are quite a few "Letter" avatar or placeholder avatar React components, which give a circle and the initials of a user, or just the first letter, etc.  We can probably use one of them.

Material UI, which I think we already have included in our tree, has some.

**Comment by cindyledev** [comment]
Some Material UI components I think would be useful in creating this:
- [Letter Avatars using Material UI](https://material-ui.com/components/avatars/#letter-avatars)
- [Over 1000 icons](https://material-ui.com/components/material-icons/) to use
- Maybe [Expansion Panel](https://material-ui.com/components/expansion-panels/) for the 'more'?
