### ISSUE TITLE
Prototype the Add Feed view in React

### ISSUE THREAD

**Issue by Silvyre** [Seneca-CDOT/telescope#725]
**What would you like to be added**:

Anticipating @yatsenko-julia's delivery of a design/mockup for a new `Add Feed` view, we should take at least the initial steps necessary to implement this design by creating a React component to house this design.

**Why would you like this to be added**:

Once @yatsenko-julia delivers her design for the `Add Feed` page, these initial steps task will already be complete, reducing the amount of time it will take to implement it later.

**Comment by yatsenko-julia** [comment]
Here is a rough sketch of how the Add Feed page could look like. 
 
![Untitled-1 2](https://user-images.githubusercontent.com/28925746/74608365-5ba08700-50ae-11ea-9f33-3a6ff219d15a.jpg)

When user clicks on 'Add blog link' the dropdown with URL field appears on the screen. I've also added _i_  tooltip with more detailed information about what exactly could be added in this section and why. 

![Untitled-1](https://user-images.githubusercontent.com/28925746/74608367-5c391d80-50ae-11ea-9a3a-0fd0428b6ab7.jpg)

User inserts a URL, clicks submit button and blog appears in the 'Personal information' section. The 'Add a blog link' is moved down so in a future user could add another blog link if needed (could be removed for Release 0.7). Also, user could edit a URL with a button next to it. 
![Untitled-1 3](https://user-images.githubusercontent.com/28925746/74608366-5c391d80-50ae-11ea-8928-82d630423719.jpg)

**Comment by Grommers00** [comment]
I like it. 

Just to note that 
![image](https://user-images.githubusercontent.com/42331013/74608816-47f71f80-50b2-11ea-9211-09bff4b31cbf.png)

It will have to be done in 0.8 as we aren't linking users to there blog at this time, however, a place holder maybe can be put into place?

**Comment by Grommers00** [comment]
One more note, I realize as I'm adding the back end.

The problem with the name currently is that we don't have a name (author) linked to our current SSO.

We can either use a default name - e.g. David Humphrey if we test this out, or we can use email.

Once we have the Seneca SSO, we should be able to get a first/last name that we can use for the author going forward. 

@humphd thoughts on how to proceed?

**Comment by humphd** [comment]
This is really cool, thanks @yatsenko-julia.  One thing that would be very useful to do in a follow-up release is to leverage what you have here to provide a better user experience for adding a blog feed if a user doesn't know what a feed URL is.

What I mean is, imagine these different scenarios and users:

1. User A comes to Telescope and knows that his blog is http://myblog.com, but has no idea what an "RSS feed" is.  We send that URL to our backend, and do a lookup in our server code to figure out whether this is an HTML page or some kind of feed.  We could send back a feed URL if we can determine it (you sometimes can), or we could check the domain (e.g. WordPress, Medium.com, Blogspot, etc) and provide some hint URLs.  The UI could give options to choose, or some notes in your info box on how to proceed.

2. User B comes to Telescope and knows exactly what her blog feed URL is.  She pastes it in, we send it to the backend, try to parse it and confirm it works.  We send feedback to the frontend UI to say that it worked.

@Grommers00 I would use the email address for the user or something in 0.7, or hard code a name like you suggest, maybe "User Name".

**Comment by Silvyre** [comment]
Regarding the creation of a React component/prototype: I ran into [some issues](https://github.com/orgs/Seneca-CDOT/teams/telescope-frontend/discussions/5) when attempting to add a component that would be rendered post-login. Resolving my own issues will likely required first resolving the redirection-related issue #732.

**Comment by humphd** [comment]
@Silvyre notice you took yourself off this issue.  I'd suggest you still consider taking it, and we can hack around the auth problem.  Fixing it perfectly doesn't need to block your work on this bug.  Happy to discuss options on Slack or in person.

**Comment by Silvyre** [comment]
> 
> 
> @Silvyre notice you took yourself off this issue. I'd suggest you still consider taking it, and we can hack around the auth problem. Fixing it perfectly doesn't need to block your work on this bug. Happy to discuss options on Slack or in person.

I am hoping to get the auth problem solved with some in-person help, tomorrow. After I'm sure I am capable of contributing, I plan to reassign. 👍
