### ISSUE TITLE
Remove second react dependency

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#728]
We have react defined in two different places:

1. https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/package.json#L18
1. https://github.com/Seneca-CDOT/telescope/blob/master/package.json#L99

The first one (in `src/frontend/package.json`) is correct, and the other one (`package.json`) needs to get removed.

**Comment by humphd** [comment]
Maybe I'm wrong.  Did we do this for detecting the react version?  cc @agarcia-caicedo, @miggs125 

One way or the other, let's only include this once so we don't have version conflicts later.

**Comment by agarcia-caicedo** [comment]
The one in the package.json was for detecting react

**Comment by miggs125** [comment]
Leaving it in package.json means that every time we do `npm i` we will download react twice. Once in the frontend and once in the root of the project. Is there a way to detect react without downloading it twice? Perhaps we can link to the frontend package.json from the root of the project?

**Comment by humphd** [comment]
Let's find a way to link to the one in frontend, yes.

**Comment by agarcia-caicedo** [comment]
> 
> 
> The one in the package.json was for detecting react

I was wrong, detecting react happens in the eslint config file, not in package.json
