### ISSUE TITLE
Updating/Adding to readme file

### ISSUE THREAD

**Issue by MusaBajwa** [Seneca-CDOT/telescope#73]
A README file is a text file that contains information for the user about the software program. README files often contain instructions and additional help, and details about patches or updates. Our README file is only a couple of lines, and I will be adding information on how our system works.

**Comment by cindyledev** [comment]
Can I work on this with you? I can provide instructions and common errors with solutions for Linux (specifically Fedora).

**Comment by MusaBajwa** [comment]
Yeah go for it.
