### ISSUE TITLE
Validate blog URLs

### ISSUE THREAD

**Issue by Cadesh** [Seneca-CDOT/telescope#74]
Currently the feeder do not validate the blog's URLs. Students will add and modify blogs URLs and there must be a way to check if these new URLs are valid and reachable.  In this issue the objective is to check for valid format of URLs only.

**Comment by Cadesh** [comment]
The idea is to create a utils.js file to hold and export the method to validate the URLs. This utils.js file will have more functions in the future. 
There are several possibilities to validate a URL:
1) is-url package: [https://www.npmjs.com/package/is-url](url)
2) validurl package [https://www.npmjs.com/package/valid-url](url)
3) with NodeJS url module [https://nodejs.org/docs/latest/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost](url)
4) use a regex and code it yourself.

**Comment by humphd** [comment]
4. is out.  URLs are really tricky to get right in a regex.
