### ISSUE TITLE
Refactor frontend CSS into CSS-in-JS

### ISSUE THREAD

**Issue by Silvyre** [Seneca-CDOT/telescope#741]
All of our convential frontend CSS styling solutions should be refactored into Material UI's [CSS-in-JS](https://material-ui.com/styles/basics/) styling solution.
<hr>
<details>
<summary><em>(Old issue text)</em></summary>

Currently [`index.css`](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/pages/index.css) imposes its styling rules upon all Gatsby Pages. While developing [the `Add Feeds` component](https://github.com/Seneca-CDOT/telescope/pull/735), I found some of these rules (namely the scaled-down font size) to be less-than-helpful, [as I noted in my pull request](https://github.com/Seneca-CDOT/telescope/pull/735):

> It is worth noting that this component currently ends up being rendered quite small due to styling enforced by `src/frontend/src/pages/index.css`:
   https://github.com/Seneca-CDOT/telescope/blob/9dc85649f1c29d1a7fceafc9b7ccbda668beb22d/src/frontend/src/pages/index.css#L9-L13

This is not, however, the only styling issue I ran into with `index.css`. I noticed that, due to the stylesheet [enforcing a `body` height of `100vh`](https://github.com/Seneca-CDOT/telescope/blob/9dc85649f1c29d1a7fceafc9b7ccbda668beb22d/src/frontend/src/pages/index.css#L20), the `Add Feed` component's [current use of margins](https://github.com/Seneca-CDOT/telescope/blob/24c6a44423e887991d032f2425cb39a0ab044943/src/frontend/src/pages/myfeeds.js#L8) forces an unnecessary scrollbar to appear:

![margin](https://user-images.githubusercontent.com/13500769/74790231-010d5380-5285-11ea-9c65-f5263d61f791.gif)

<hr>

There is [some discussion](https://github.com/Seneca-CDOT/telescope/issues/730#issuecomment-587138483) about eventually replacing our CSS files, like `index.css`, with CSS-in-JS (JSS). Until we have come to an agreement to that end, I believe that refactoring our CSS files (i.e. to ensure their global styling does not adversely affect new components) prevents a good stop-gap. (Again, at this point, we definitely don't want to outright _remove_ any CSS files...)

<hr>

To summarize what I believe should be done:
- Rework the two aforementioned styling rules within [`index.css`](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/pages/index.css) to be more selective about the components it targets (namely the incoming `Add Feeds` component):
  1. The rule governing the global scaling down of font size should be reworked to exempt at least the `Add Feeds` component from being targeted. (This rule is currently causing the `Add Feeds` component to be rendered too small.)
  1. The rule governing the enforcement of a `100vh` `body` height should be reworked to exempt at least the `Add Feeds` component from being targeted. (This rule is currently causing the `Add Feeds` page to have an unnecessary scroll bar.)

Please note that, however, these global styling rules should *keep affecting existing/working components* (as we can assume that these components have been designed with this global styling in mind)!

<hr>

@yatsenko-julia expressed interest in tackling this, so I am assigning this issue to her! (Julia, please feel welcome to reach out to me if you have any questions, or would like any assistance with this!)

</details>

**Comment by yatsenko-julia** [comment]
While I was trying to figure out why I cannot load the myfeeds page, 2 issues that you mentioned @Silvyre were resolved. What do you think if I'll try to replace CSS with CSS-in-JSS for release 0.7?

**Comment by Silvyre** [comment]
> 
> 
> 2 issues that you mentioned @Silvyre were resolved.

[`index.css`](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/pages/index.css) is still imposing two overbearing styling rules on the My Feeds component:

![demo](https://user-images.githubusercontent.com/13500769/75630100-b6a9a200-5bb5-11ea-8700-67afedaf32c1.gif)

As such, these tasks still need to be completed:

>   1. The rule governing the global scaling down of font size should be reworked to exempt at least the `Add Feeds` component from being targeted. (This rule is currently causing the `Add Feeds` component to be rendered too small.)
>  1. The rule governing the enforcement of a `100vh` `body` height should be reworked to exempt at least the `Add Feeds` component from being targeted. (This rule is currently causing the `Add Feeds` page to have an unnecessary scroll bar.)

> What do you think if I'll try to replace CSS with CSS-in-JSS for release 0.7?

I don't believe that we've come to a full agreement on this matter. While I support this initiative, others might not. Let's chat about that tomorrow, in class.

**Comment by yatsenko-julia** [comment]
Thanks for your reply, @Silvyre. I still cannot reproduce your issue. I've tried Safari and Chrome before I saw that you are using Firefox. When I run the project in Firefox instead of styles I receive inline styles. Here is a screenshot: 
<img width="1920" alt="Screen Shot 2020-03-01 at 4 25 19 PM" src="https://user-images.githubusercontent.com/28925746/75634176-490f6d00-5bd9-11ea-9502-09f9b2d00734.png">

I also tried to change index.css, rebuild containers and restarted the app, but there are no visible changes. ( I added font size and color changes to the `.MuiPaper-root.MuiCard-root.MuiPaper-elevation1.MuiPaper-rounded` class )

Could you please help me understand why my changes do not take effect and how can I reproduce your issue?

**Comment by Silvyre** [comment]
Oh, I see; it seems like you're encountering the same phenomena that Cindy just commented on here: https://github.com/Seneca-CDOT/telescope/pull/748#issuecomment-593152548

You are viewing an incompletely-styled `My Feeds` component being served by our backend (`localhost:3000`), while I am being served by the Gatsby live-reloading development server on `localhost:8000`.

You should navigate to http://localhost:8000/myfeeds.

**Comment by Silvyre** [comment]
The focus on this issue has shifted. The original post has been updated accordingly.

**Comment by humphd** [comment]
Blocking #922.

**Comment by humphd** [comment]
Taking this, as we need it now.
