### ISSUE TITLE
Prevent <h1> and <h2> tags within blog posts from being sanitized

### ISSUE THREAD

**Issue by Silvyre** [Seneca-CDOT/telescope#768]
[By default](https://github.com/apostrophecms/sanitize-html#what-are-the-default-options),  `<h1>` and `<h2>` tags are not included within [our list of allowed HTML tags](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/sanitize-html.js#L10-L43), causing them to be stripped out by our `sanitize-html` module:

https://github.com/Seneca-CDOT/telescope/blob/62087be0501d18f7500ae8f9d62761e65bb4f08a/src/backend/utils/sanitize-html.js#L10-L43

`<h2>` tags are used frequently within blog posts (e.g. are the default header for WordPress blogs), and stripping them out is causing more harm than good to our styling.

<hr>

It is worth noting that, since each blog post title is wrapped within `<h2>` tags, this change would introduce headers that sit at or above the same header level as the blog post title:

![image](https://user-images.githubusercontent.com/13500769/75703256-19b63a00-5c85-11ea-97fb-a55ad169ce4a.png)

If we wish to have the title of each blog post to possess a larger text size than any other header within the post, the following changes should additionally be made:
1. Blog post titles should be wrapped within `<h1>` tags (instead of `<h2>`).
   - Some additional styling would have to be applied to `<h1>` tags, to ensure they fit our current theme.
1. All non-title `<h1>` tags should be styled with a reduced `font-size`.

<hr>

Other changes required:
- Our list of allowed tags, shown above, should be alphabetized.

**Comment by humphd** [comment]
Good catch.  Let's add `<h1>` too.

**Comment by humphd** [comment]
Let's also alphabetize this list so it's easier to see if we miss things.  I think we missed the `<h1>` and `<h2>` because they are scattered through the list.

**Comment by smilegodly** [comment]
I'd like to work on this one if that is alright.

**Comment by Silvyre** [comment]
@smilegodly That would be great!

**Comment by humphd** [comment]
Awesome, @smilegodly, thanks!  FYI, #813 is pretty similar to this if you want another one while you're at it!

**Comment by Silvyre** [comment]
Resolved by https://github.com/Seneca-CDOT/telescope/pull/835
