### ISSUE TITLE
Darkmode js incorporation

### ISSUE THREAD

**Issue by smilegodly** [Seneca-CDOT/telescope#77]
For me personally, Darkmode on a website is a must have as it becomes much easier to read all of the text that website. Seeing as the purpose for this website is reading blogs, it seems like a good idea to have the option to toggle darkmode on/off.

One option to achieve this is Darkmode.js
https://darkmodejs.learn.uno/

We can customize this to our needs (colors, animations, etc)

**Comment by cindyledev** [comment]
I'd like to have a dark mode eventually but I don't think we should use Darkmode js since we have other options available:
1) [gatsby-plugin-dark-mode](https://www.gatsbyjs.org/packages/gatsby-plugin-dark-mode/) or
2) [MUI Dark mode](https://material-ui.com/customization/palette/#dark-mode)
