### ISSUE TITLE
Remove broken drawer from the mobile version

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#771]
**What happened**:

When the mobile telescope site is accessed, there is an open drawer which is not properly formatted and cannot be closed. It looks like this:

![image](https://user-images.githubusercontent.com/49992710/75704845-24be9980-5c88-11ea-8fc1-4c22e3e515ac.png)
 

**What should have happened**:

As we currently, don't have a proper pull out menu, it should not appear

**Environment**:

- OS: Windows
- Browser: Firefox

**Comment by cindyledev** [comment]
But I like the iPants feature...
