### ISSUE TITLE
Wrong redirection when trying to access /admin/queues for logged-in users

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#775]
**What happened**:
Accessing `/admin/queues` after logging in redirects to `/`.

**What should have happened**:
`/admin/queues` should be reachable by logged-in users

**How to reproduce it (as precise as possible)**:
After logging in, try to access `/admin/queues`

**Anything else we need to know?**:
Tested on staging server and localhost. Both show same behaviour.

**Environment**:

- OS: Linux
- Browser: Firefox

**Comment by humphd** [comment]
I ran `git bisect` to figure this out, and the last time it worked was `v.0.6.0`.  Immediately after that we landed https://github.com/Seneca-CDOT/telescope/commit/07c308ed1bac7295898b75fa04e9383d31e5a68d and it broke.  Before this change, we used to do the admin route like this:

```js
router.use('/queues', authenticateWithRedirect, UI);
```

Where `authenticateWithRedirect()` was:

```js
function authenticateWithRedirect(req, res, next) {
  // If the user is already authenticated, let this pass to next route
  if (req.isAuthenticated()) {
    next();
    return;
  }

  // Redirect the unauthenticated user to our SSO provider
  if (req.session) {
    // Remember where we were trying to go before logging in so we can get back there
    req.session.returnTo = req.originalUrl;
  } else {
    logger.warn('SAML - authenticateUser: No session property on request!');
  }
  res.redirect(telescopeLoginUrl);
}
```

So I guess the way that `passport.authenticate('saml')` is working isn't right.
