### ISSUE TITLE
Stickers and other Swag for 2.0

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#780]
Let's design and buy some stickers for the Telescope 1.0 release.  We can use a service like https://www.stickermule.com/ca to print them.   Things to consider:

- what should it be?  We have a few logos floating around, and it could also be something else that's fun to remember the work
- how many do we need?  I suspect that a bunch of people who worked on this last term will want one

I'm willing to fund the purchase if others will do the design work necessary to send it for printing.

**Comment by agarcia-caicedo** [comment]
I'm willing to work on the design

**Comment by humphd** [comment]
Updating this for 2.0.  Let's figure this out!

cc @PedroFonsecaDEV, @foxviet, and other design folks.

**Comment by humphd** [comment]
cc @izhuravlev, who also expressed some interest.

**Comment by chrispinkney** [comment]
I can't offer much besides a review: I've used Vistaprint before (and found a random coupon code online that actually worked.) They were great. I think they're an American company but the factory is in Mississauga (or Toronto? Somewhere in the GTA.) Shipping was fast but they made a mistake on the poster I printed and express shipped me a second one at no charge.

They do various printing related stuff (bags, stickers, posters, etc.), just supply a design and they'll handle the rest.

**Comment by PedroFonsecaDEV** [comment]
I've used [redbubble](https://www.redbubble.com/) to buy a bunch of stickers. Everything was okay.

**Comment by izhuravlev** [comment]
For Fun to remember: we can come with some "Telescope memes" (For example a telescope logo with a "Don't mind me - just watching", "Scoping around", "This one is a superstar!" or anything like those phrases) and probably make a slack channel for everybody to make new ones and rate them. I can also help with the design, but I think our most recent logo #1698  is pretty great.
We can also try to make something more animated (cartoonish) so we have something like a Mascot - and the Mascot will be on the sticker. 

Once again, I am not a great painter (artist), but I'd love to help!

**Comment by izhuravlev** [comment]
Another point is As I am in Russia rn, it might be cheaper to do that here for me - but then we'll need to do everything before the First of April.

**Comment by izhuravlev** [comment]
I actually asked my friend, who is a professional designer and artist, and she is willing to help us do it :3 

She can create a Mascot if we come up with some ideas. She also worked at the printing agency before, so she knows what needs to be done. She is not a Seneca student and doesn't have a GitHub, but we can find ways to contact her apart from through me.

**Comment by izhuravlev** [comment]
Btw, can anybody remind me why did we get rid of the old logo?

**Comment by PedroFonsecaDEV** [comment]
@izhuravlev That's nice. 
We are heading to 2.0(microservices + TS + next), so we deserve a new logo and a new UI.

**Comment by izhuravlev** [comment]
Okay, so here are 2 variants I personally sketched (paper and pencil, I'm not a digital artist, I am sorry, pro-designer will get on it soon) for the Telescope Mascot. 

You can take a look at them, comment which you like more, and I will get back with more when my friend gets me some more pro-sketches. 

React on your Favourite down below!

**Comment by izhuravlev** [comment]
1:
![photo_2021-02-16_17-45-34](https://user-images.githubusercontent.com/36719387/108552807-db38e580-7302-11eb-92a5-851129dee5f3.jpg)

**Comment by izhuravlev** [comment]
2:
![photo_2021-02-19_22-05-37](https://user-images.githubusercontent.com/36719387/108552834-e55ae400-7302-11eb-9bed-4c17514ff085.jpg)

**Comment by izhuravlev** [comment]
Also, the problem we have now is 
### LOGISTICS:

1. How many stickers (or packs of stickers) do we want to print in the first batch? 
When the files for the print are ready, we will store them (probably on GitHub) - so later on another batch of stickers can be printed.
2. Money: how do we process it, how do we collect it, what is the right way to do it?
3. How to send them to all the people who wanted them?

**Comment by izhuravlev** [comment]
I have a question @humphd: Should we at this point create a separate issue for the Mascot and mention it here?

**Comment by chrispinkney** [comment]
Obviously (unfortunately) not humphd but I think yeah probably. Or maybe we could use the new discussions feature of github? I think it needs to be turned on though and might be weird to use for this one time issue.

**Comment by PedroFonsecaDEV** [comment]
@humphd ^ 

@chrispinkney I can't find this feature. can you?

**Comment by izhuravlev** [comment]
@humphd attention needed here

**Comment by humphd** [comment]
As I've said previously, I'm not going to drive this.  If people want to do it, that's cool, but it's not something I can spearhead easily.

**Comment by izhuravlev** [comment]
## Hello Everybody, 

Here is what is going on. 

My friend [Diana](https://github.com/dianaxantiart) and I were thinking about what we can do for our stickers. 
As you remember, I already proposed a couple of variants, and Diana made them look better in her sketches. 


We first tried to figure out what the body of our Mascot will look like:
![Faces and Bodies](https://user-images.githubusercontent.com/36719387/111833498-504c0a80-8903-11eb-8111-62924322ba4c.jpg)


Then we worked on some emotions and expressions:
![emotions_and_body1](https://user-images.githubusercontent.com/36719387/111833539-6063ea00-8903-11eb-9cf6-034975a34f4b.jpg)
![emotions_and_body2](https://user-images.githubusercontent.com/36719387/111833546-622dad80-8903-11eb-945b-7a26ccd60887.jpg)


And afterwards, we decided to ignore the tall guy and focus a bit more on the tiny cute guy (The Inspiration was based on  BMO from Adventure Times).
![photo_2021-03-18_22-31-44](https://user-images.githubusercontent.com/36719387/111833732-a1f49500-8903-11eb-9ee5-c82b67ae603b.jpg)


But just a couple of days ago Diana had a genius idea. Just take a look at what she came up with:
![photo_2021-03-19_22-28-44](https://user-images.githubusercontent.com/36719387/111833833-c5b7db00-8903-11eb-8986-296db32df18a.jpg)


So, the task for **YOU** guys is to tell us - which one do you like? Tiny Guy or a Cat? Or maybe Tall Guy? Or maybe you have some other ideas we should consider?

Vote for your favourites below!
👍 is for the Tiny Guy
🎉 is for the cat
💯 if you have other ideas.

You can write your thoughts below.

**Comment by izhuravlev** [comment]
Also, if we go with the cat, we might want to think about what colour it should be. The Telescope is quite obvious, but the cat is not that simple.

**Comment by chrispinkney** [comment]
I really love both haha, I'm learning more towards a telescope based mascot but that cat looking through a telescope is just too perfect. How about both mascots, Telly & Dave the cat (_like the unix command_)?

I vote for a black cat... for reasons.
![i_view64_2021-03-19_16-04-54](https://user-images.githubusercontent.com/7242003/111836570-df89fb80-88cc-11eb-97e3-72c0a862c052.png)

**Comment by izhuravlev** [comment]
> I really love both haha, I'm learning more towards a telescope based mascot but that cat looking through a telescope is just too perfect. How about both mascots, Telly & Dave the cat (_like the unix command_)?
> 
> I vote for a black cat... for reasons.
> ![i_view64_2021-03-19_16-04-54](https://user-images.githubusercontent.com/7242003/111836570-df89fb80-88cc-11eb-97e3-72c0a862c052.png)

I absolutely Love the Unix Reference. 

Then the question is how many and which do we want? Like what emotions?

**Comment by izhuravlev** [comment]
So, Because I want to be able to provide us those stickers, we will do the following:

[Here ](https://docs.google.com/spreadsheets/d/1E0TwI6qyP98GCgzuVBzz6sA4apVupcF1REIdKoBpJAU/edit#gid=0) is the Google Sheets document  - anybody interested in receiving those stickers - please fill in at least your name and email so I can contact you. 

My plan is to finalize the documents for stickers (the files to be printed) - and then organize the printing, so by end of May, we should get our Swag!

I will contact everybody on the list after I hear from my designer about the files.

**Comment by humphd** [comment]
I think that this isn't needed anymore so I'll close.  If that's wrong, feel free to re-open.
