### ISSUE TITLE
myfeeds.js should use sitemetadata hook for telescopeUrl

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#784]
In https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/pages/myfeeds.js#L30, we need to switch to use the sitemetadata hook.  Take a look at https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Login/LoggedOut.jsx for an example of how to do this.

**Comment by Silvyre** [comment]
I'll take this.
