### ISSUE TITLE
Add some interesting data points and info to the hero banner

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#789]
**What would you like to be added**:

Let's find a way to add some details to the Hero banner.  We already have the version info, which is cool.  Here are some other ideas:

- GitHub stats about the project.  This is a system built by our students for our students.  We could show things like how many lines of code, how many contributors, etc.
- Writing stats.  We have a `/stats` route that gives us details about what happened [today](https://dev.telescope.cdot.systems/stats/today), [this week](https://dev.telescope.cdot.systems/stats/week), [this month](https://dev.telescope.cdot.systems/stats/month), and [this year](https://dev.telescope.cdot.systems/stats/year)--did you know we've written 40K words since January 1? Impressive!

Some of this could be done with words or numbers, some could be done with graphics or graphs, or some other visualizations.

**Why would you like this to be added**:

Since we've decided to try having a Hero banner at the top of our site, I'd love for it to be something that provides quick and useful info to inspire our users.

**Comment by raygervais** [comment]
Taking a crack this weekend on it. I really like your example `did you know we've written 40K words since January 1? Impressive!` as a basis of how we are conveying stats.

**Comment by humphd** [comment]
Awesome, thanks @raygervais.  Another existing api endpoint you might find useful:

```
GET /posts
```

In headers you'll get:

```
X-Total-Count: 5536
```

If you want to use that number in any way (it will always grow).
