### ISSUE TITLE
Add "Load More" button to add more posts

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#790]
In theory we have infinite scrolling.  In practice, you can easily hit the bottom of the page and you get no more posts.

Let's add a mechanism for loading more posts.  It could be manual ("Load More..." button at the bottom) or automatic.

Having this will also allow us to load fewer posts on startup, which should help load times.

**Comment by humphd** [comment]
I feel like this can be closed, @raygervais, @Grommers00?

**Comment by raygervais** [comment]
Yes, given that we have the follow up #999 to address behavior. Closing.
