### ISSUE TITLE
Add a way to receive updates when new posts are available

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#791]
If I leave Telescope running in a tab for a long time, I want it to tell me when there are new posts available.  I think it should work like this:

1. We setup a long-poll (i.e., keep calling `fetch()` or do a graphql query) every few minutes
1. When we get back data that is different from our current state, we know that there are updates
1. Show some kind of "Toast" or "Banner" or some other floating action button that says, "New posts available..." or something, and clicking it loads them in and shows the new data
1. We should also update the favicon in the tab to indicate that there are updates (red/white notification circle).

This is somewhat connected to #790.

**Comment by c3ho** [comment]
We can probably use the stuff going into #750 for this. I'm thinking of using the GraphQL getPosts query that will just run every 60s and check if the value of the query is the same as currentState.
