### ISSUE TITLE
Scroll to the top button does not stand out

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#793]
After #772 was pushed, the scroll to the top button was changed from blue to the same colour as the background. This creates no contrast between the elements and does not make for a good user experience.

![image](https://user-images.githubusercontent.com/49992710/75889840-82272780-5dfb-11ea-8607-4da1591774da.png)

The button should be changed to be a different colour, preferably the same blue ad the post title section

![image](https://user-images.githubusercontent.com/49992710/75890041-cdd9d100-5dfb-11ea-87f9-2eeb58fb4477.png)

**Comment by humphd** [comment]
This would be a good experiment to try and make use of the new theme.js file that I had to add.  We should be able to set that blue as our primary colour, in which case this will "just work."

**Comment by raygervais** [comment]
Assigning to myself if no one else is interested. Curious to dive deeper into React and utilize the `theme.js` file @humphd mentioned.

**Comment by raygervais** [comment]
Thoughts on this @agarcia-caicedo?, This uses the heading background-color `#335A7E`
![image](https://user-images.githubusercontent.com/14265337/75941815-a7994d00-5e5e-11ea-82f4-516f7a33f0f6.png)

VS

Heading Color `#002944`
![image](https://user-images.githubusercontent.com/14265337/75941868-d6afbe80-5e5e-11ea-8905-eac001292b63.png)

VS

Title Color `#a4d4ff`
![image](https://user-images.githubusercontent.com/14265337/75941955-137bb580-5e5f-11ea-9528-9ef5ed944891.png)
