### ISSUE TITLE
Import PHP, DOS modules into syntax-highlight.js

### ISSUE THREAD

**Issue by Silvyre** [Seneca-CDOT/telescope#798]
**What would you like to be added**:

Syntax highlighting support for PHP and DOS is missing from [`syntax-highlight.js`](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Post/syntax-highlight.js) and should be added.

**Why would you like this to be added**:

Code in these languages may plausibly make its way onto Telescope, as they are languages taught within Seneca College courses.

**Comment by humphd** [comment]
Closed by #812
