### ISSUE TITLE
Discussion: where to host?

### ISSUE THREAD

**Issue by ragnarokatz** [Seneca-CDOT/telescope#8]
Where are we hosting this application?
- seneca zenit/matrix server?
- heroku?
- others

Also, are we hosting it behind a web server?
- nginx
- apache tomcat
- others
this is for useful functionalities such as ip-whitelisting, firewall, load-balancing, https, etc.

**Comment by humphd** [comment]
We have a Kubernetes Container Cloud at Seneca that we'll use to host this.  Any containerized app(s) we want to run will work.

I imagine we'll have a few web servers: node micro-service REST apis; maybe an nginx reverse proxy or static server, but the rest of load balancing etc. will happen via Kubernetes automagially.

**Comment by Silvyre** [comment]
@ragnarokatz May I suggest closing this issue and moving discussion on this subject to #4?

**Comment by ragnarokatz** [comment]
moving dicussion to #4
