### ISSUE TITLE
Use multiple images for our hero banner

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#802]
**What would you like to be added**:

Let's consider including a bunch of images in our tree that we use (randomly) for the hero banner background image.  We'd still have only 1 image showing (I don't mean rotate through them when you load), but every time you reload the site, you'd get a new one.

Here are some queries with images to consider:

- https://unsplash.com/s/photos/telescope
- https://unsplash.com/s/photos/space
- https://unsplash.com/s/photos/blog
- https://unsplash.com/s/photos/code
- https://unsplash.com/s/photos/developer
- https://unsplash.com/s/photos/technology
- https://unsplash.com/s/photos/learn
- https://unsplash.com/s/photos/write

I'm not sure how many we'd want to have, but "more than one."  We can probably do some processing (manual or via Gatsby plugins) to build all the right sizes https://help.groupthought.com/article/24-images-that-work-well-with-multiple-device-sizes.

This bug is really a 2 (or more) issue:

- decide if we want to do this at all
- pick images we want to use
- integrate them into our Gatsby build so sizing works well for all devices
- add code to the frontend to deal with showing a different each time
- figure out how to do attribution, since we're using CC licensed images

**Why would you like this to be added**:

I really like the image we have, but I also look at it over and over again, and it's losing its interest with repeated expose.  I think if I got a different image every time I went to the site, I might be more engaged with the hero banner, and not want to move past it immediately.

I also think the hero banner image could be another subtle way for us to communicate Telescope's culture and meaning to users.  Over time, and through repeated visits, we could start to seed different ideas about what we're doing here.

I'd love to showcase things like writing, openness, diversity, technology, etc. For example, some random ones to give you a sense (I'm not suggesting we use these, just want to show a bunch of different ideas):

![](https://images.unsplash.com/photo-1485822115845-08ff6aecb3ab?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60)
![](https://images.unsplash.com/photo-1569012871812-f38ee64cd54c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80)
![](https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60)
![](https://images.unsplash.com/photo-1577095688357-e4955b1dc91c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80)

This is somewhat connected to #789

**Comment by raygervais** [comment]
Would like to work on this after I have #789 landed since it's the same component. Will start the conversations of do we want the image to change every refresh, or over time?
