### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#804]
**What would you like to be added**:

Let's add a static About page to Telescope, which people can use to learn more about the app and project, who built it, how to get involved, etc.

Gatsby supports using Markdown, so we might be able to do this without much/any code, see https://www.gatsbyjs.org/docs/adding-markdown-pages/.

**Why would you like this to be added**:

We've had a number of discussions about the need for better docs on what Telescope is, both at the development and user levels.  We have a few dev docs that discuss this, but nothing for users.  We should include a page dedicated to the history of Telescope, indicate how to get involved, how to add a feed, etc.

**Comment by humphd** [comment]
We should include links here to anything related to the project, including:

- https://github.com/Seneca-CDOT/telescope
- https://wiki.cdot.senecacollege.ca/wiki/Planet_CDOT_Feed_List
- https://seneca-open-source.slack.com/archives/CS5DGCAE5
- etc

**Comment by agarcia-caicedo** [comment]
I'll work on it

**Comment by cindyledev** [comment]
This is something I've been looking into since #290 . @agarcia-caicedo I don't know if you wanna do the About Page solo or if you're open to collaborate with me but I'm happy to assist you with this issue.

**Comment by agarcia-caicedo** [comment]
@cindyledev I'm open to collaborate, let me know what you're thinking

**Comment by cindyledev** [comment]
I like this kind of style for the footer to include the links Dave mentioned
![Annotation 2020-03-07 135051](https://user-images.githubusercontent.com/36822198/76150683-2965c200-607b-11ea-8b17-48d4ccff67b8.png)

**Comment by manekenpix** [comment]
I noticed that the title doesn't work for this page. It usually shows the title of where you were right before opening `About`.
Here I went to `Search` and the `About`:
![image](https://user-images.githubusercontent.com/23108901/77603932-a69c8e00-6ee7-11ea-8108-ad600ffe896f.png)
Since this is general issue for the `About` page, I thought it'd be a good idea to mention this here.

**Comment by cindyledev** [comment]
Thanks @manekenpix, we'll add the title when we iterate on this.
