### ISSUE TITLE
Ability to translate page to different languages

### ISSUE THREAD

**Issue by smilegodly** [Seneca-CDOT/telescope#81]
We could add a drop down menu that displays a list of different languages. When the user clicks a language the text on the page gets translated to the selected language.. 
The page default should be English obviously.

**Comment by Sbaah** [comment]
Hello, I would like to attempt this.

**Comment by Sbaah** [comment]
According to @humphd this is something that should be done, down the road after we have a working site. So i would like to retract my previous statement.

**Comment by humphd** [comment]
Fixed in #184
