### ISSUE TITLE
Whitelist YouTube/Vimeo iframe elements in post content

### ISSUE THREAD

**Issue by ragnarokatz** [Seneca-CDOT/telescope#813]
**What happened**:
A blog post containing video (youtube link) is not showing on telescope.

**What should have happened**:
The video should appear in the blog post on telescope.

**How to reproduce it (as precise as possible)**:
- use google chrome
- login to wordpress
- make sure this blog is subscribed to telescope's blog feed. Sign up if it's not.
- start a new blog post
- copy and paste a youtube video link into your blog post
- hit Enter, wait for the video embed/render
- click publish and check to make sure that the blog post is indeed published
- check telescope at https://dev.telescope.cdot.systems/

**Anything else we need to know?**:

How the post look on telescope: https://dev.telescope.cdot.systems/
![image](https://user-images.githubusercontent.com/33646954/76134432-40110800-5fec-11ea-8a24-83585f54cb6f.png)

Original wordpress post: https://ragnarokatz.wordpress.com/blog-feed/
![image](https://user-images.githubusercontent.com/33646954/76134440-4bfcca00-5fec-11ea-89af-bdad34a6f861.png)

**Environment**:

- OS: windows 10
- Browser: google chrome

**Comment by humphd** [comment]
This is fallout from https://github.com/Seneca-CDOT/telescope/issues/556.

I wonder if we should whitelist a few domains, such as the youtube-embed case?

**Comment by Silvyre** [comment]
>I wonder if we should whitelist a few domains, such as the youtube-embed case?

I think that would be worthwhile.

**Comment by humphd** [comment]
In fact, this case seems pretty easy to implement: https://github.com/apostrophecms/sanitize-html#iframe-filters.

I think we should allow youtube/vimeo at least.

**Comment by Silvyre** [comment]
@ragnarokatz Were you interested in working on this?

**Comment by ragnarokatz** [comment]
@Silvyre Nope, just reporting a bug. Please feel free to take this issue and work on it.

**Comment by smilegodly** [comment]
I'd like to work on this if that's alright.

**Comment by c3ho** [comment]
Thank you for taking on the issue @smilegodly

**Comment by smilegodly** [comment]
Currently we have a test that checks if the iframe tag gets sanitized. Should we still have this test?  
The iframe tag needs to be allowed in order to allow the hostnames

**Comment by humphd** [comment]
Split that test into 3 tests:

- an iframe to a YouTube embed should work (i.e., iframe is still there)
- an iframe to Vimeo embed show work (i.e., iframe is still there)
- iframe to anything else should get removed

**Comment by cindyledev** [comment]
Another YouTube video didn't show up properly today
![Annotation 2020-03-22 211941](https://user-images.githubusercontent.com/36822198/77270743-2e359300-6c83-11ea-935f-b293f0e0b2f2.png)

**How to reproduce it (as precise as possible)**: 
Visit the following:
https://dev.telescope.cdot.systems/
https://cleung.wordpress.com/2020/03/22/a-video-to-show-what-i-have-done/

**Anything else we need to know?**:
Blog is originally posted on WordPress

**Environment**:

- OS: Windows
- Browser: Chrome
