### ISSUE TITLE
"WORKDIR paths should be absolute"

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#819]
In `Dockerfile` and `developer.Dockerfile` I'm seeing this warning from VSCode:

<img width="595" alt="Screen Shot 2020-03-08 at 2 42 29 PM" src="https://user-images.githubusercontent.com/427398/76169272-dc522080-614c-11ea-996d-e13bed43ac0f.png">

cc @raygervais

**Comment by raygervais** [comment]
This appears to be fixed in the next release of the Docker-linter plugin for VS Code. https://github.com/microsoft/vscode-docker/issues/1492

**Comment by raygervais** [comment]
Still, we could simply remove the quotations (they aren't mandatory I believe) and have the warning / error disappear now :). Thoughts on direction @humphd?

**Comment by humphd** [comment]
If it's not a real problem, and the linter will catch up, I'm happy to close it.  Thanks for researching.
