### ISSUE TITLE
Creating a Test that ensure's the email ability is working correctly

### ISSUE THREAD

**Issue by neilong31** [Seneca-CDOT/telescope#82]
Creates testing for feature in #25 

I will be using nodemailer and ethereal to test that the we are able to send emails out.

Similar to [https://nodemailer.com/smtp/testing/](https://nodemailer.com/smtp/testing/)

**Comment by RyanWils** [comment]
Hi Neil, 
I will submit a PR for a basic email sending function so you can start on your tests.
Sorry I miss clicked on the close issue button.
