### ISSUE TITLE
Document, use, or remove developer.Dockerfile

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#820]
We have `Dockerfile` and `developer.Dockerfile`, and I'm unclear what the latter is.  Can we either document/use it somewhere, or remove?  Nothing currently references it in our tree.  Is that by design or a bug?  If you have to use it via a command line flag, we should document that.

cc @raygervais

**Comment by raygervais** [comment]
This was the original `Dockerfile` that Telescoped used prior to me introducing the multi-stage builds. Reason I had opted to keep it around was purely for those who were using Docker locally and needed the `node:lts` container base for any reason. Pretty safe to delete if no one is leveraging Docker in their local workflow.
