### ISSUE TITLE
Telescope needs a <title>

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#827]
**What would you like to be added**:

Currently, Telescope doesn't have a `<title>`, so Telescope's tab(s) are shown like this:

![image](https://user-images.githubusercontent.com/23108901/76318470-23a6f100-62b4-11ea-9211-1ebb714add93.png)

This could be easily done using [helmet](https://www.npmjs.com/package/react-helmet) (which is already part of Telescope's frontend, I think).

**Comment by agarcia-caicedo** [comment]
I'll work on it
