### ISSUE TITLE
Add a "ready" event for redis to match elasitic

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#828]
In #822 we're adding Elasticsearch, and the way we're doing it adds logic to our feed worker on startup to make sure Elastic is "ready" before processing posts.  We should probably do the same for Redis. [ioredis has an `enableReadyCheck` option and `ready` event we can use](https://github.com/luin/ioredis#connection-events).

**Comment by manekenpix** [comment]
Doing a bit of reading to find a way to tackle this issue, I ran into [this](https://github.com/OptimalBits/bull/commit/ce0048c1a7e3903d25d048572919e5c11697adc5). It seems the `OptimalBits` people (responsible for `bull`) already added a way to check if redis is up and running before start processing jobs.
@humphd can you confirm this so we can close this issue?

**Comment by humphd** [comment]
That's great for the running of the queue, but for the person developing or deploying the app, it doesn't give us the visibility I want.  I'd still love some kind of logging or logic to let us know what's up with the Redis backend.

**Comment by chrispinkney** [comment]
Closed in favour of #1938
