### ISSUE TITLE
Scroll buttons are not the same size

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#830]
Follow up to #815 

The scroll down button on the Hero banner and the scroll to the top button are not the same size
<img width="64" alt="Screen Shot 2020-03-10 at 3 59 57 PM" src="https://user-images.githubusercontent.com/427398/76354171-57037300-62e8-11ea-82a4-d813f4ac1deb.png">
<img width="73" alt="Screen Shot 2020-03-10 at 3 59 49 PM" src="https://user-images.githubusercontent.com/427398/76354172-579c0980-62e8-11ea-9438-7780f967a037.png">

Please change them so they are the same size :)

**Comment by agarcia-caicedo** [comment]
I'll work on it
