### ISSUE TITLE
Support <del> elements in our html sanitizer

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#837]
**What happened**:
Strikeout text doesn't show up properly in blog post on Telescope. Original source is from Wordpress. Strikeout text is inside of an unsorted list

https://dev.telescope.cdot.systems/
https://cindyledev.wordpress.com/2020/03/14/osd-700-release-0-8-progress/

![Annotation 2020-03-14 235354](https://user-images.githubusercontent.com/36822198/76694950-64ee2680-664f-11ea-982d-130bfadaf3fc.png)

**Environment**:
- OS: Windows
- Browser: Chrome

**Comment by humphd** [comment]
This will be due to our html-sanitizer stripping `<strike>` elements.  I wonder what we should do here, since `<strike>` is [obsolete in HTML5](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike) (you're supposed to use `text-decoration: line-through;` in CSS now).

**Comment by Silvyre** [comment]
Wordpress uses `<del>` elements, which we're currently sanitizing out. Resolving this issue would likely be as simple as adding `<del>` to our array of allowed tags:

https://github.com/Seneca-CDOT/telescope/blob/f13d52f12150ca173f71e9e9a321a0f8294ff953/src/backend/utils/sanitize-html.js#L10-L43

**Comment by humphd** [comment]
Morphing this bug....

@smilegodly you seem to know this code best, want to tackle this for us?

**Comment by cindyledev** [comment]
Ah I just created a PR for this D:
