### ISSUE TITLE
API Route caching

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#838]
We're using things like `/posts` and `/stats/year` on every load of the app.  Let's cache these results (memory or redis).  We should return cached results when possible.

If using redis, we can use `redis.setex()` and set a key that will expire in N seconds.  We'd just need some middleware to check if the value exists in cache before we do the work of looking it up.

**Comment by manekenpix** [comment]
I think this is included in #634. @c3ho and I are working on this. I'll probably be ready tomorrow or Tuesday.

**Comment by humphd** [comment]
Closing as dupe of #634.
