### ISSUE TITLE
Search Bar submit button + onClick()

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#839]
**What would you like to be added**:
#792 should hopefully go in soon. It doesn't have a search button, but dynamically returns results based on user input. I made it this way currently because I'm unable to prevent the onClick function from triggering non stop after the initial user click

Here's some code snippets that may speed up the process to resolve the issue:

I removed the following code from `SearchBar.jsx`:
line 90
```
        <IconButton
          type="submit"
          className={classes.iconButton}
          aria-label="search"
          onClick={event => handleClick(event)}
        >
          <SearchIcon />
        </IconButton>
```

Code for `SearchPage.jsx`:
```
  function onClickHandler() {
    executeSearch();
  }
```
line 103
```
      <SearchBar
        onClickHandler={onClickHandler}
        searchText={searchText}
        onChangeHandler={onChangeHandler}
      />
```

**Why would you like this to be added**:
Up for debate, should we search upon user input or when the user clicks on button? If this is not a concern, we can close this issue.

**Comment by humphd** [comment]
This really needs to happen in the future, because we waste so much bandwidth searching and pulling in posts while you're typing.  We shouldn't do anything until the user tells us they are done.

**Comment by raygervais** [comment]
Been doing quite a bit of DevOps style items for the past two weeks at work etc, plus having issues with #1008 on the Windows Testing side so I'm going to hash out this one as a weekend-long break. Will return to 1008 after.
