### ISSUE TITLE
Implementing writing level

### ISSUE THREAD

**Issue by lozinska** [Seneca-CDOT/telescope#84]
I would like to add feature to check the writing level

**Comment by cyh0968** [comment]
you may refer [this link](https://github.com/Seneca-CDOT/telescope/issues/7#issuecomment-551151290). I think we can use [reading-level](https://www.npmjs.com/package/reading-level) to measure the level of the writing. you may refer [issue 19](https://github.com/Seneca-CDOT/telescope/issues/19). One thing I'm worried about is the duplication of the work since the level of the writing may affect the time of reading.

**Comment by lozinska** [comment]
@cyh0968 Thank you for your comment. I think that reading-time and reading-level are part of the analysis that suppose to perform on the text mention in issue #7 and they are not a duplication of each others. This conclusion is based on the fact that reading time doesn't analyze the complexity of the text but just do rough estimation base on the plain text, while reading-level determine level base on the word complexity using  [Flesch-Kincaid Grade Level Readability Formula](https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests). 
@cyh0968 what do you think?

**Comment by lozinska** [comment]
@humphd please review if you have time and leave comment as well. Thank you

**Comment by humphd** [comment]
Reading Level and Reading Time are indeed different things.  It's fine to do PRs for both (I think Reading Level is underway already).

**Comment by dbeigi** [comment]
@lozinska is this feature still being worked on?

**Comment by lozinska** [comment]
@dbeigi you can work on it

**Comment by jordanhui19** [comment]
Is anyone working on this? If not, I can take it.

**Comment by lozinska** [comment]
Thank you @jordanhui19 for creating PR for this issue. This is very nice to have this feature. As your piece of code had been merger already I will close this issue.

**Comment by lozinska** [comment]
Reading level was implemented in PR 373 and merged into our code. As this issue had been resolved I will close it now. Thank you @jordanhui19 for your contribution for this nice feature.
