### ISSUE TITLE
Header Bar text increases size when search button clicked

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#841]
**What happened**:
When a user goes to the search page and clicks the search button, regardless of filter, the text in the header bar grows in size. This is how it looks.

![image](https://user-images.githubusercontent.com/49992710/76881013-e6f86e00-684e-11ea-8d8f-cef895e2e9f4.png)

**What should have happened**:
This is how the header should look:

![image](https://user-images.githubusercontent.com/49992710/76881057-f8417a80-684e-11ea-8787-0e27dc457d04.png)

**How to reproduce it (as precise as possible)**:
Go to the search page and click the search button in the search bar. Typing anything in the bar or changing the filter has no different effect.

- Browser: Firefox

**Comment by cindyledev** [comment]
Does it think the magnify glass button means zooms in or something? 😂

**Comment by cindyledev** [comment]
This is a very weird bug, I can't seem to be able to reproduce this locally on Linux or Windows but it's definitely happening at `https://dev.telescope.cdot.systems/search`

**Comment by cindyledev** [comment]
Let's see if this is still a problem after #792 gets merged...

**Comment by cindyledev** [comment]
I might have found the culprit. I was going through our code looking for .css files to delete for #856 and as a test, I deleted `/src/frontend/src/pages/index.css`. This is the exact look that happens after the search button in the search bar is clicked... I think `index.css` is somehow applying itself here.

Before delete:
![Annotation 2020-03-22 091904](https://user-images.githubusercontent.com/36822198/77250416-40311a80-6c1e-11ea-9a83-dc848f9ffe6b.png)

After delete:
![Annotation 2020-03-22 091904_](https://user-images.githubusercontent.com/36822198/77250445-6b1b6e80-6c1e-11ea-8119-e9d51fffd75f.png)

Unfortunately, everything else gets huge `index.css` gets deleted...
![Annotation 2020-03-22 091904__](https://user-images.githubusercontent.com/36822198/77250505-c3eb0700-6c1e-11ea-9a07-5729ae84f41a.png)
![Annotation 2020-03-22 091904___](https://user-images.githubusercontent.com/36822198/77250507-c5b4ca80-6c1e-11ea-8673-d03bc1d50606.png)

I guess this is another effect of what @Silvyre was talking about last month in #741

**Comment by cindyledev** [comment]
While trying to reproduce #912 , I ran into this hot mess
![Annotation 2020-04-01 152813](https://user-images.githubusercontent.com/36822198/78178317-71cf9000-742d-11ea-9388-ed20086be599.png)

How to reproduce:
- Visit https://dev.telescope.cdot.systems/
- Click on the Search icon in AppBar to go to Search page
- Hit refresh to refresh the page
- Click on the Home button in AppBar

**Comment by humphd** [comment]
Blocking #922.

**Comment by humphd** [comment]
Taking this, as we need it now.
