### ISSUE TITLE
Switch our REST APIs to serverless

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#844]
**What would you like to be added**:
We should switch our REST API's to become serverless functions

**Why would you like this to be added**:
This was discussed at the beginning of our OSD700 course and I think now is a good opportunity to implement this.

**Comment by humphd** [comment]
I would caution against this for 1.0.  It will change so much about how we deploy and run our backend.  Without Kubernetes, this is going to be hard to do well imho.

**Comment by humphd** [comment]
If this happens, it needs a better plan than this bug.  Like the future Kubernetes discussions, I'm going to close it now, and we'll file new issues when we're ready.
