### ISSUE TITLE
Date and time of the post

### ISSUE THREAD

**Issue by lozinska** [Seneca-CDOT/telescope#85]
May be we can add feature that will show date and time when the post came up?

**Comment by humphd** [comment]
cc @lucacataldo, as I think this is referring to frontend design?

**Comment by lucacataldo** [comment]
@lozinska just to clarify, do you mean including a date/timestamp for when we index / fetch the post? Or when the post was written? The latter is already included (although missing the time) but regardless the former could also be useful although maybe not crucial to display in the header so as not to confuse the reader in regards to which date is which. Just something to keep in mind 😄 

(thanks for the ping @humphd )

**Comment by lozinska** [comment]
Hi @lucacataldo. I think I should close this issue because as you said that date is already implemented in another PR. I don't think we need to have 2 different dates when feed came into queue and when blog was posted, because it will be confusing. Do you think we should include time?
