### ISSUE TITLE
/stats/* reporting incorrect values

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#858]
We noticed that the stats visible on the front page (from `/stats/year`) were not updating.  Now I see this:

<img width="851" alt="Screen Shot 2020-03-22 at 5 39 52 PM" src="https://user-images.githubusercontent.com/427398/77261344-4518bd00-6c64-11ea-9001-5ac759a573b6.png">

Something is broken.

**Comment by humphd** [comment]
Is this a date issue in the container?

**Comment by humphd** [comment]
From Slack, this might be related to the indexing restarting on staging.

**Comment by manekenpix** [comment]
Currently, `/stats/year` returns:

![image](https://user-images.githubusercontent.com/23108901/77284729-b75dc180-6ca5-11ea-927d-617da973e252.png)

Many authors have posted more than 1 post this year, so it's possible that the same value is being used for both `posts` and `authors`.

**Comment by cindyledev** [comment]
I think its showing number of posts. The count for number of authors seems wrong.

**Comment by humphd** [comment]
We're still seeing issues here, with newly added posts not triggering a change to the total word count.  I wonder if this is somehow date related, and we're not including the new post in what gets counted, but are including it in what we show?

**Comment by humphd** [comment]
The number is updated this morning, 11 hours later--so it does the right thing in less than 12 hours.  I wonder if we're off by some amount of hours attributable to timezone differences in how dates are being calculated?  This is how we figure out the range of time to use for getting posts from Redis:

https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/data/stats.js#L68-L75

**Comment by manekenpix** [comment]
@humphd The staging box was used for testing 7 hours ago, and telescope had to be relaunched many times to test the new features. I think we should consider that as one of the possible reasons why the number got updated.

**Comment by humphd** [comment]
@manekenpix OK, that's really useful to know.  I assumed that it has been stable over the night, but if it got restarted, that complicates things.

**Comment by cindyledev** [comment]
Yeah, I noticed the number changed after dev was back up last night around 4am

**Comment by humphd** [comment]
> around 4am

Speaking of time zones, you're all crazy.

**Comment by humphd** [comment]
The value we get back from `startOfYear()` is using `05` for the hour, instead of `00`, so it's off by 5 hours when what we'd expect.  This explains why we have a delay, which goes away after some number of hours.

I filed https://github.com/date-fns/date-fns/issues/1698 upstream to see if it's our bug or something deeper.

**Comment by humphd** [comment]
Also, this is odd between staging (bottom) and production (top):

<img width="1232" alt="Screen Shot 2020-04-18 at 6 37 32 PM" src="https://user-images.githubusercontent.com/427398/79672893-d3208e80-81a3-11ea-9595-c4475b5d1d29.png">

**Comment by chrispinkney** [comment]
Related to #1829, we'll land these fixes there. Closing for now.
