### ISSUE TITLE
Embedded YouTube videos does not showing up on Telescope

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#859]
**What happened**:
Not sure if this was intentional but embedded YouTube video doesn't show up on Telescope
![Annotation 2020-03-22 211941](https://user-images.githubusercontent.com/36822198/77270743-2e359300-6c83-11ea-935f-b293f0e0b2f2.png)

**What should have happened**:
Embedded YouTube videos should be displayed or at least a link

**How to reproduce it (as precise as possible)**: 
Visit the following:
https://dev.telescope.cdot.systems/
https://cleung.wordpress.com/2020/03/22/a-video-to-show-what-i-have-done/

**Anything else we need to know?**:
Blog is originally posted on WordPress

**Environment**:

- OS: Windows
- Browser: Chrome

**Comment by manekenpix** [comment]
Related to (if not the same) #813.

**Comment by cindyledev** [comment]
@manekenpix I was looking for that issue but couldn't find it so I thought I might have imagined it XD

Closing this one because duplicate
