### ISSUE TITLE
SAML2 - Middleware

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#86]
Please add the middleware that we can start using to start building out our SAML2 system

Do some research to make sure these are compatible before pushing and merging.

**Comment by neilong31** [comment]
@Grommers00 I'd like to work on this issue!

**Comment by Grommers00** [comment]
Cool, I assigned you!

**Comment by vitokhangnguyen** [comment]
Issue #63 when solved can have great benefit for this issue
