### ISSUE TITLE
Expand <iframe> video to fill available width and keep aspect ratio

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#869]
**What would you like to be added**:

Let's add some code to wrap our `<iframe>` elements for YouTube/Vimeo such that we can [expand them to fill the available width and keep their aspect ratio](https://css-tricks.com/fluid-width-video/#article-header-id-0).  There are two ways we can do this:

1. Re-work the HTML we get, and add a wrapper container that we can use to do relative positioning of the iframe within.

2. Use JS to do this at runtime.

I suspect that 2. is easier.  The article I linked discusses both options.

**Why would you like this to be added**:

We just had a an awesome PR land that adds support for `<frame>` video from YouTube and Vimeo.  It would be great to maximize the size of these elements so they are similar to what we've done for `<img>` elements, which fill the available space and keep their aspect ratio.

**Comment by smilegodly** [comment]
I'd like to work on this

**Comment by humphd** [comment]
Awesome, thanks @smilegodly.

**Comment by cindyledev** [comment]
Just a picture to show what the problem looks like on mobile
![Screenshot_20200416-010101_Chrome](https://user-images.githubusercontent.com/36822198/79416490-cfabbe00-7f7d-11ea-9498-b525ddd0e8ab.jpg)
It kinda sticks out a little bit on the right.

**Comment by humphd** [comment]
It's possible that #869 will fix this, too.

**Comment by humphd** [comment]
Holy crap, this *is* #869, ignore me!

**Comment by humphd** [comment]
@smilegodly I'm going to steal this, I have a fix.
