### ISSUE TITLE
Tests for SAML2

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#87]
We will need a list of tests that will test our SAML2 out. I believe these can be done before hand. Can anyone take charge?

**Comment by vitokhangnguyen** [comment]
Thanks for the issue. I will collaborate with you on this.

**Comment by Reza-Rajabi** [comment]
@Grommers00 I thought you want to work on some automation on our project board, and I apologize for that. Feel free to add a new page inside any boards that I made, or let me know if you want me to do so. If you want to make a separate project only for SAML2, it is also fine, but we can only have issues assigned to one project at a time. That means I don't need to (I can't) keep track of them. In brief, I would be more than happy to help with this issue in any way, and sorry that I didn't get your point today.

**Comment by Grommers00** [comment]
This is actually already built into the SSO server that we are currently testing, currently most testing is done already on whoever the test SSO provider is. I'm going to close this - and we can consider other forms of testing when our front end is actually done.
