### ISSUE TITLE
Adjust responsive sizing, positioning on mobile 

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#872]
<img width="386" alt="Screen Shot 2020-03-24 at 8 21 21 PM" src="https://user-images.githubusercontent.com/427398/77488958-23a70500-6e0d-11ea-8d37-54687a8f977d.png">

There are a couple of paper-cuts we can fix:

- Login and the Hamburger menu are cut off.  We could switch form words to icons on mobile, or we could move everything across the top into the hamburger menu.
- The "scroll down" circular button (what's it called?) is not centered, and is too close to the bottom of the viewport.  It should be above and centered.
- The left position of the text for the stats is a lot larger than the right margin.  At this sizing, we should probably centre that div.

**Comment by raygervais** [comment]
I'd like to take this on. It's always fun improving responsiveness of a site for more view-ports.

**Comment by humphd** [comment]
You have a twisted sense of fun, but I'm here for it.  It's all yours!

**Comment by cindyledev** [comment]
First bullet point is similar to #860 :o

**Comment by raygervais** [comment]
If @agarcia-caicedo hasn't yet started, I can tackle #860 same time and we iterate from there. Or, I can leave `Header.jsx` alone entirely.
