### ISSUE TITLE
Leverage Gatsby's Image Optimization for Unsplash API

### ISSUE THREAD

**Issue by raygervais** [Seneca-CDOT/telescope#876]
**What would you like to be added**:
For 0.9, we've added the dynamic banner background which polls Unsplash API collection. Going forward, let's integrate this into the build step of Gatsby to leverage the image optimization. That would mean pulling down the collection and then randomizing which is used during runtime.

**Why would you like this to be added**:

**Comment by humphd** [comment]
We've done this now with the image service, closing.
