### ISSUE TITLE
Redis - add user to own a list of feeds.

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#883]
**What would you like to be added**:
Step 1 Add a user field to Redis 
Step 2: Our Feed data type, graphql 
Step 3: Update our tests

**Why would you like this to be added**:
So users can remove and add there own feeds, this will let us move in the right direction, and make the next steps easier.

**Comment by humphd** [comment]
This will involve updating a bunch of things:

- adding an `owner` line and value to https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/storage.js#L35-L45
- updating the tests in https://github.com/Seneca-CDOT/telescope/blob/master/test/storage.test.js to work with this new value present
- updating `Feed` to have a `user` (could be `null`) here https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/data/feed.js#L15-L30
- dealing with various `Feed` creation functions, adding `user` https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/data/feed.js#L73-L97
- updating the `/feed` tests in https://github.com/Seneca-CDOT/telescope/blob/master/test/feed.test.js
- updating our graphql schemas here https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/graphql/index.js
- etc.

**Comment by humphd** [comment]
When you are working on this, you'll need to wipe your redis database.  This requires using:

```
npx redis-cli flushall
```

**Comment by humphd** [comment]
Where I said `owner` above, I meant `user`.

**Comment by humphd** [comment]
The work @c3ho did in https://github.com/Seneca-CDOT/telescope/pull/807/files is a nice template for what you have to do here, fyi.
