### ISSUE TITLE
Logged In state for Header needs to be updated

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#889]
**What happened**:
After #882 landed, we are now able to log in AND log out and after #877, we have display names for users who successfully signed in. However, the Header doesn't display them nicely.

![Screenshot_2020-03-28 Home](https://user-images.githubusercontent.com/36822198/77817173-4cdec400-709f-11ea-9f87-a3aeed06d671.png)

**What should have happened**:
Please fix so that Username and LOGOUT lines up with the rest of the other links in the Header. You can probably use [MUI Divider](https://material-ui.com/components/dividers/#vertical-dividers) instead of `|`. Remove the word "Welcome" as it makes the whole thing unnecessarily long and remove the unavatar.

**How to reproduce it (as precise as possible)**:
Using Docker:
- `sudo systemctl start docker` in Linux or run Docker Desktop for Windows or Mac
- `docker-compose up --build redis login elasticsearch`
- `npm start`
- visit `localhost:3000/auth/login` (LOGIN button navigates to `https://dev.telescope.cdot.systems/auth/login`)
- sign in using `Username: user1` `Password: user1pass`

You reproduce this using native redis and elasticsearch too

**Anything else we need to know?**:
This issue will likely touch one or more of the following files:
- [LoggedIn](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Login/LoggedIn.jsx)
- [LoggedOut](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Login/LoggedOut.jsx)
- [Header](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Header/Header.jsx)

**Environment**:
- OS: All
- Browser: All

**Comment by humphd** [comment]
Yes, let's do this.  And let's drop the avatar, since we don't/won't have this info for 99% of people using the system.  Also, the `Welcome...` part is probably not needed, since we don't have tons of space.

**Comment by cindyledev** [comment]
Updated issue with @humphd 's suggestions

**Comment by agarcia-caicedo** [comment]
I'll work on it, now that we have a drawer we can declutter the navbar

**Comment by cindyledev** [comment]
Updated the issue with more accurate reproduction instructions:
- `docker-compose up --build redis login elasticsearch`
- `npm start`
- visit `localhost:3000/auth/login` (LOGIN button navigates to `https://dev.telescope.cdot.systems/auth/login`)
