### ISSUE TITLE
Create custom pages for HTTP 404, 403, 500s

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#890]
**What would you like to be added**:

Let's consider adding some custom pages for a few error cases that we have.  I'm not 100% clear on the right way to deal with the difference between what lives in Gatsby and what is just static that we can access via Express.  This will need some research.

What I'd like to deal with are these cases:

- 404s: when we can't find something
- 401s, 403s: when the user isn't allowed to do something
- 500s: we crashed

I don't think there are other cases, but people can add them if I'm missing any.

**Why would you like this to be added**:

This is something we could have some fun with, and bring a bit of whimsy or branding to our app.  But it's not a critical component for a 1.0.

In Express we can do custom error handling with a function at the end of the middleware stack.  Here are some links:

- https://stackoverflow.com/questions/6528876/how-to-redirect-404-errors-to-a-page-in-expressjs
- http://expressjs.com/en/starter/faq.html
- http://expressjs.com/en/guide/error-handling.html

**Comment by raygervais** [comment]
Curious to take this on, expand out from the banner component.
