### ISSUE TITLE
declutter Banner layout

### ISSUE THREAD

**Issue by raygervais** [Seneca-CDOT/telescope#893]
**What would you like to be added**:

Based on comments of @agarcia-caicedo, let's investigate how we can balance the text and various elements found in the Banner component so that on both widescreen and mobile, it doesn't seem overbearing or lopsided.

**Why would you like this to be added**:

**Comment by Jasper-Mui** [comment]
Is this still relevant? The banner looks fairly good on both mobile and widescreen now.

**Comment by humphd** [comment]
@raygervais @agarcia-caicedo I'm not sure if you have concrete asks here, or if we should close this now?  I'm tempted to close it.

**Comment by raygervais** [comment]
I'd be fine with closing it, this was during the design phase. Since then, banner UI has seen updates.

**Comment by humphd** [comment]
Thanks @raygervais, closing.
