### ISSUE TITLE
Choose Unsplash images to use with banner

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#894]
**What would you like to be added**:

We've just merged the work @raygervais did to add Unsplash photos to our banner.  As a start he's using the photos in this collection: https://unsplash.com/collections/894/earth-%26-planets.

Let's see if we can create a Collection that can be shared across accounts, or I can make one, and people can tell me which photos to add.

**Why would you like this to be added**:

There's lots of great photos in there, but let's do a bit more work to figure out what we actually want to showcase here.

Let's try and think about the Telescope brand: what are these images trying to say?  It's more than just "looking through a telescope" I think.  It has to do with learning, a diversity of voices, education, etc.

If we choose wisely, we can say a lot without having to do a ton of work here.

**Comment by humphd** [comment]
One thing I'm noticing, as I watch all the new photos go by on staging, is that some of them work better with out colour scheme than others.  We could eliminate those that don't work, and prefer those that do in our collection.

**Comment by humphd** [comment]
From https://github.com/Seneca-CDOT/telescope/pull/897/files#r400181330, we should consider moving the URL to our Unsplash collection to the gatsby-config, so it can be changed at build time.

**Comment by raygervais** [comment]
I'll start the thread I suppose: 
https://unsplash.com/photos/ZMcLVBi9xx4

_From the Earth & Planets Collection_
![From the Earth Collection](https://images.unsplash.com/photo-1441716844725-09cedc13a4e7)

**Comment by agarcia-caicedo** [comment]
Here are some that I think would fit Telescope's vibe.
https://unsplash.com/photos/npxXWgQ33ZQ
![image](https://user-images.githubusercontent.com/49992710/78098393-f4fcd180-73ac-11ea-9a6c-683beac98247.png)

https://unsplash.com/photos/fIq0tET6llw
![image](https://user-images.githubusercontent.com/49992710/78098419-0f36af80-73ad-11ea-88b1-589fa3cd279a.png)

https://unsplash.com/photos/2FPjlAyMQTA
![image](https://user-images.githubusercontent.com/49992710/78098477-39886d00-73ad-11ea-8ac6-5e59758edd80.png)

https://unsplash.com/photos/oMpAz-DN-9I
![image](https://user-images.githubusercontent.com/49992710/78098564-6e94bf80-73ad-11ea-9c78-536cd06145f3.png)

https://unsplash.com/photos/IgUR1iX0mqM
![image](https://user-images.githubusercontent.com/49992710/78098621-9edc5e00-73ad-11ea-9149-3ffbb327367b.png)

https://unsplash.com/photos/wW0BUXTTUmU
![image](https://user-images.githubusercontent.com/49992710/78098738-e8c54400-73ad-11ea-84fb-3721026afe54.png)

https://unsplash.com/photos/ourQHRTE2IM
![image](https://user-images.githubusercontent.com/49992710/78098980-920c3a00-73ae-11ea-8948-b8389d7ba48b.png)

https://unsplash.com/photos/k_T9Zj3SE8k
![image](https://user-images.githubusercontent.com/49992710/78099007-a6503700-73ae-11ea-9462-c5234f50ebae.png)

**Comment by raygervais** [comment]
Another that I like, 

![image](https://user-images.githubusercontent.com/14265337/78518511-af664d00-778e-11ea-8713-43aede7f7778.png)

_From the Milky-way Collection_
https://unsplash.com/photos/sJGvoX_eVhw

**Comment by humphd** [comment]
This is done, and still happening in #1170.
