### ISSUE TITLE
buymeacoffee button

### ISSUE THREAD

**Issue by smilegodly** [Seneca-CDOT/telescope#90]
There is this cool website called Buy Me A Coffee: https://www.buymeacoffee.com/?=ga2
It is a website that you can pay creators by buying them a coffee if you enjoy their work.
Should we incorporate this into our Planet Cdot?

Let me know what you all think..

**Comment by dbeigi** [comment]
This issue might relate to #26 . I think this is a great idea.

**Comment by Reza-Rajabi** [comment]
If we want to implement some donation feature, I suggest making our own rather than having payment to a mediator. Because CDOT and Seneca are known, we don't need to lock the donation system to any third party. A third party is a desirable choice for an individual who does not connect to any organization like a personal Github page.

**Comment by smilegodly** [comment]
@Reza-Rajabi I disagree with your premise that we would want to connect Seneca and/or CDOT to donations/tips. 

A third party works fine because at the end of the day we are all individual developers working on this project. Furthermore this solution helps to incentivize bug bounties or features that somebody wants added in the future.. It would serve as an extra motivation to get the ball rolling in a particular direction for large features or bugs that could take considerable time to implement.
 
The last thing I personally would would want is to get CDOT or Seneca involved with an individual person tipping another individual for a considerable amount work they have done. That would only cause problems when considering copyright and ownership down the road. If Seneca decided they own the planet CDOT website, they could try and get in the middle of these tips/donations, and cause disruptance in the community..

**Comment by smilegodly** [comment]
Another idea I had in substitute of this would be to do tips/donations/bounties via crypto wallet public keys.

**Comment by Reza-Rajabi** [comment]
@smilegodly What I meant by that is the fact that we are paying a part of the donation to the third party for their service, and I was saying let's use Seneca resources to donate, directly and completely, to the developers. So in this sense, I am in accord with you actually. I am not sure though if the whole thing is appropriate or feasible and just wanted to clarify that I would rather taking care of students in the first place.

**Comment by humphd** [comment]
We discussed this a bit more with the team implementing this term, and decided against adding any kind of monetization features.  I'm going to close.
