### ISSUE TITLE
Eslint issue in Banner.jsx

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#901]
<img width="799" alt="Screen Shot 2020-03-30 at 11 17 45 AM" src="https://user-images.githubusercontent.com/427398/77929913-363f9500-7278-11ea-9df4-1c12f3764757.png">

My VSCode linter catches this, but our eslint config doesn't.  The fix is to move `getStats` above this invocation.

**Comment by Silvyre** [comment]
Fixed in #1002
