### ISSUE TITLE
Authenticated users should be able to add, list, modify, or delete their own feeds

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#908]
We're going to allow users to add feeds in production.  When we do, we'll need a way for them to manage them.  Basically, we need full CRUD support via our REST API for authenticated users.  This can leverage #717 to figure out what is and isn't allowed for the currently logged in user.

We can break this down into smaller PRs, and do it bit at a time, but I want one bug that tracks it all.  We need:

- support in backend (redis, elastic, node) for adding, modifying, removing feeds and the posts that belong to them
- support in REST API for all necessary operations on feeds
- support in frontend to be able to call the REST API

**Comment by Silvyre** [comment]
Related: https://github.com/Seneca-CDOT/telescope/issues/760

**Comment by c3ho** [comment]
This can be closed no?

**Comment by humphd** [comment]
Yup.
