### ISSUE TITLE
Admins should be able to modify or delete any user's feeds via frontend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#909]
Similar to #908, we need to allow administrators to manage any user's feeds.  Whatever check we do in #908 to block users from working with feeds they don't own, this would make it possible for an admin to override that and do updates.

**Comment by Silvyre** [comment]
Related: https://github.com/Seneca-CDOT/telescope/issues/294

**Comment by Silvyre** [comment]
@humphd Does the current solution (of listing all feeds for admins) sufficiently resolve this issue?

**Comment by humphd** [comment]
Yeah, what we have now works.
