### ISSUE TITLE
Finish Search feature

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#911]
We have the beginnings of a search feature, and a backend ready to support it, but right now the search returns no results for me.

I'm also not clear why we have `None` selected by default in the drop-down, and what `Filter2` and `Filter3` do.

We need to connect all the pieces and polish this so that it's usable for 1.0.

**Comment by cindyledev** [comment]
Related #839

**Comment by humphd** [comment]
We should add a progress spinner if we are doing work.
