### ISSUE TITLE
Clicking "Home" in search page doesn't work

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#912]
When I click 'Home' in the Search page, I get errors:

<img width="1231" alt="Screen Shot 2020-04-01 at 10 40 31 AM" src="https://user-images.githubusercontent.com/427398/78150423-4769dc80-7405-11ea-84e4-0001b9409f7f.png">

**Comment by cindyledev** [comment]
I can't reproduce this error. The Home button on the Search page redirects me to Home like it should...
I've tested https://dev.telescope.cdot.systems/ on both Firefox and Chrome on Windows and Chrome on Android

**Comment by humphd** [comment]
STR:

- Go to Search
- Type something into the search box
- Press Enter
- Text goes huge
- URL changes to add `/search/?filter=` to the end
- Click HOME

Nothing happens for me.

**Comment by cindyledev** [comment]
@humphd I get this https://github.com/Seneca-CDOT/telescope/issues/841#issuecomment-607447726 when I followed your steps to reproduce

**Comment by cindyledev** [comment]
OH I FINALLY GOT THE ERROR ON FIREFOX

**Comment by humphd** [comment]
"..and I'm using Firefox" would have been helpful, sorry!

**Comment by agarcia-caicedo** [comment]
I think #928 fixed this issue

**Comment by humphd** [comment]
Great, we can follow-up with #841 for the other bits.
