### ISSUE TITLE
Add link to /myfeeds page to AppBar

### ISSUE THREAD

**Issue by Silvyre** [Seneca-CDOT/telescope#914]
**What would you like to be added**:

As mentioned during today's triage meeting, a button to navigate to the `/myfeeds` page needs to be added to the home page.

**Why would you like this to be added**:

No convenient means to navigate to the `/myfeeds` page currently exists. Users need to be made aware of this page's existence.

<hr>

Related: https://github.com/Seneca-CDOT/telescope/issues/889

**Comment by cindyledev** [comment]
I think putting this in the Header bar makes more sense than the Hero Banner...

**Comment by Silvyre** [comment]
Yeah, that's what I meant.

**Comment by cindyledev** [comment]
Okay, so this is actually related to #889, not #893 . I know this is very easy to get mixed up because they both mention "decluttering" something and everyone gets confused with naming conventions navbar/banner/topbar/header/appbar... header is probably the worst name imho but it's what MUI calls it :/

**Comment by Silvyre** [comment]
> header is probably the worst name imho but it's what MUI calls it :/

MUI actually calls it an [AppBar](https://material-ui.com/api/app-bar/). 😀 

https://github.com/Seneca-CDOT/telescope/blob/86fbd217a2c6701ad4a20729951bbd2e9d85ebfc/src/frontend/src/components/Header/Header.jsx#L100

**Comment by cindyledev** [comment]
> > header is probably the worst name imho but it's what MUI calls it :/
> 
> MUI actually calls it an [AppBar](https://material-ui.com/api/app-bar/). 
> 
> https://github.com/Seneca-CDOT/telescope/blob/86fbd217a2c6701ad4a20729951bbd2e9d85ebfc/src/frontend/src/components/Header/Header.jsx#L100

I stand corrected. I see it as `Header (AppBar)` pretty often too XD

**Comment by agarcia-caicedo** [comment]
I think it should go in the drawer, since we do not want to clutter the header bar

**Comment by cindyledev** [comment]
I mean, it can go in the Header on desktop screens since there is room for it and it can go in the drawer on mobile

**Comment by Silvyre** [comment]
@cindyledev @agarcia-caicedo What do you think about linking part of our [`<LoggedIn/>`](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Login/LoggedIn.jsx) component's welcome message and/or avatar image to the My Feeds page? i.e. Welcome, [User](#) [&lt;img&gt;](#)

https://github.com/Seneca-CDOT/telescope/blob/d0a1f66552bcb43f3eb04390c819028b6b31365e/src/frontend/src/components/Login/LoggedIn.jsx#L35
