### ISSUE TITLE
Use redis feeds vs. wiki feeds when adding to feed queue

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#920]
Previously, we only had the wiki feed list.  It was our "database" of feeds.  Every time we wanted to parse all feeds into posts, we had to download it and add those feeds to the feed queue.

Next, we added the ability for users to create their own feeds in Redis, separate to the wiki feed list.  Eventually, we'll completely replace the wiki feed list with adding feeds directly to Telescope.

Right now, we live in between these two worlds, and need to support both.  To do this, we need to make a few changes:

- We need to keep downloading the wiki feed list regularly, so we can get updates
- We need to stop using the wiki feeds as our feed list in the feed queue, and instead need to get our feeds from Redis

Connected to this is #294, but we don't need to fix that for this to happen.

**Comment by Silvyre** [comment]
Resolved by https://github.com/Seneca-CDOT/telescope/pull/1015
