### ISSUE TITLE
Regression: CSS Update changed Post heading spacing

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#930]
After the `PageBase` CSS update, I notice that the vertical spacing for post headings has increased.

Before:

<img width="791" alt="Screen Shot 2020-04-03 at 9 27 31 AM" src="https://user-images.githubusercontent.com/427398/78365701-757a2880-758d-11ea-8a9a-e10441b20ed3.png">

After:

<img width="788" alt="Screen Shot 2020-04-03 at 8 04 05 PM" src="https://user-images.githubusercontent.com/427398/78413661-74c1b080-75e6-11ea-9712-801d63a7cdf6.png">

**Comment by cindyledev** [comment]
I will look into this and I want to try to expand the scope of this issue to include
https://material-ui.com/components/lists/#pinned-subheader-list
