### ISSUE TITLE
Allow custom headers to pass through CORS

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#934]
**What would you like to be added**:
We're unable to fetch custom headers right now for some reason. After lots of work by @manekenpix we found out it was a CORS related setting.

**Why would you like this to be added**:
We have custom headers but we're unable to get them and can only get 'Content-Type' at the moment.

**Comment by manekenpix** [comment]
This issue came from testing #931. @c3ho and I worked together to figure out what piece of Telescope was originating this problem.
