### ISSUE TITLE
Improve Docker Setup Documentation for WSL-2 /  Windows

### ISSUE THREAD

**Issue by raygervais** [Seneca-CDOT/telescope#936]
**What happened**:

Documentation does not include the following details, which are essential for setting up WSL / Docker workflow on Windows environments:

- Installing WSL 2 via Insiders Build
- Updating "Ubuntu" to WSL 2 architecture
- Utilizing WSL 2 Docker back-end instead of Hyper-V (Windows 10 Pro)

**Environment**:

- OS: Windows 10, 1909 (Latest stable release)
- Browser: N/A

**Comment by cindyledev** [comment]
I really appreciate you working on this, @raygervais :)
