### ISSUE TITLE
/myfeeds UI needs to work with longer names and URLs

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#945]
Reviewing #933, I noticed that our UI for working with feeds isn't ideal for the kind of data that we have:

![](https://user-images.githubusercontent.com/36822198/78559187-ef0a5480-77e1-11ea-9698-ff836c5a9f24.png)

This shows a feed `https://blog.mozilla.org`

This URL is 24 characters long.  I checked and our data looks like this:

|String | Max Length | Average Length |
|-------|-------------|-----------------|
|URL    | 87 | 51 |
|Author| 35 | 13.5|

We're going to need to adjust our UI in `/myfeeds` so it works for more realistic author names and URLs.

**Comment by Silvyre** [comment]
One idea is to only display parts of the feed URL, e.g. its [origin](https://developer.mozilla.org/en-US/docs/Web/API/URL/origin) or even just its [hostname](https://developer.mozilla.org/en-US/docs/Web/API/URL/hostname). We do this in our backend to build our OPML output:

https://github.com/Seneca-CDOT/telescope/blob/9cba5ed46c166f620c21f19f16baeccc383a44f6/src/backend/web/routes/feed.js#L131

**Comment by humphd** [comment]
We have a ton of space to the left and right that's empty, why not expand the width of this component?

**Comment by Silvyre** [comment]
Ah, I misunderstood which URL you were referring to! We can definitely expand the width of the entire My Feeds component, which is currently being constrained to 'xs' size:

https://github.com/Seneca-CDOT/telescope/blob/9cba5ed46c166f620c21f19f16baeccc383a44f6/src/frontend/src/pages/myfeeds.js#L55

We may, however, still want to limit the size of the URL displayed within the feed deletion confirmation modal.

**Comment by humphd** [comment]
Fixed in #1001, but wasn't autoclosed.  Closing manually.
