### ISSUE TITLE
NPM Packages are behind and need updating. 

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#947]
**Package**                                             
express-handlebars    4.0.1   -> 4.0.3  
jest                 25.2.6  -> 25.2.7  
pino                  6.0.0  ->   6.1.1  
prettier              2.0.2   ->   2.0.4 

**What would you like to be added**:
I would like all these to be updated for our 0.9 release. 
**Why would you like this to be added**:
It's good to be up-to-date on our packages.

**Comment by humphd** [comment]
@Grommers00 and I will do this one together early next week.
