### ISSUE TITLE
Test the function of counting each domain post.

### ISSUE THREAD

**Issue by KarlaChen** [Seneca-CDOT/telescope#95]
There is a function to counting each domain posting, such as from WordPress, blogger. This function is counting how many blogs are coming from those domains.

**Comment by haichuan0424** [comment]
Hi Karla, I'd like to work on this.

**Comment by Silvyre** [comment]
During [our latest Triage Meeting](https://github.com/Seneca-CDOT/telescope/wiki/Triage-Meeting-Jan-13-2020), we have decided to backbench several outstanding data analytics functionalities. As such, this issue will be closed. If you are interested in resuming development on this feature, please feel welcome to reach out on the Telescope Slack channel. Thank you!
