### ISSUE TITLE
Text overflow bugs

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#950]
A few text overflow bugs we've seen lately, maybe connected, maybe one off?

<img width="826" alt="Screen Shot 2020-04-06 at 10 03 52 PM" src="https://user-images.githubusercontent.com/427398/78622387-00d81000-7853-11ea-9f2d-bb3649c03c4a.png">

![Annotation 2020-04-01 152813](https://user-images.githubusercontent.com/36822198/78178317-71cf9000-742d-11ea-9388-ed20086be599.png)

**Comment by Jasper-Mui** [comment]
I have not been able to reproduce this bug. Can you mention when/how this occurs?

**Comment by humphd** [comment]
I haven't seen it happen in a long time.  It's possible it's been fixed.  Let's close until we can reproduce.

@Jasper-Mui once again, thank you for testing and triaging these issues.  It's really appreciated.

**Comment by Jasper-Mui** [comment]
Happy to help.
