### ISSUE TITLE
Move the parentheses text to another line in .env file

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#952]
**What would you like to be added**:
We currently have this in our .env file
![image](https://user-images.githubusercontent.com/18711727/78625636-97f49600-785a-11ea-896b-649fb944ab43.png)

We should update it so that the text in parentheses such as (our staging server) should be on another line.

**Why would you like this to be added**:
I was using `https://dev.telescope.cdot.systems` in place of my {telescopeUrl} while developing on the front end because I wasn't able to get my front-end to use the .env var set. I just realized it was the `(`text)` right beside the urls causing the issue

**Comment by humphd** [comment]
Yes, move those lines above the line vs. to the right.  That's my fault, sorry about it.

**Comment by neilong31** [comment]
Hey, I'd love to take care of this

**Comment by agarcia-caicedo** [comment]
thanks @neilong31
