### ISSUE TITLE
Combine EditConfig, ESLint, and Prettier to manage code style and formatting

### ISSUE THREAD

**Issue by vitokhangnguyen** [Seneca-CDOT/telescope#96]
A noticeable example of this is the size of code indentation: ESLint is expecting 2 spaces while EditConfig is specifying 4.

I can uniform these miscellaneous things.

**Comment by ragnarokatz** [comment]
@vitokhangnguyen you should be able to set the parameters in the eslint config file. please refer to this link: https://stackoverflow.com/questions/48902050/eslint-airbnb-with-4-spaces-for-indent

**Comment by manekenpix** [comment]
@vitokhangnguyen I think the best solution would be getting rid of EditConfig. It seems ESLint is the one we're going to be using, so I don't see the need of having EditorConfig.

**Comment by vitokhangnguyen** [comment]
@ragnarokatz Thank you for the link. I will fix the bug accordingly.

@manekenpix After some research, I find that there is still value to keep both. Although ESLint checks the code for quality and rule compliance, it does not adjust the configuration of the code editor. This can lead to situations that the contributor has to see a lot of errors/warnings during writing code before they run a command to lint the code or fix them manually.

**Comment by manekenpix** [comment]
@vitokhangnguyen how about using [prettier](https://www.npmjs.com/package/prettier) then? It's an npm package and it [integrates with linter](https://prettier.io/docs/en/integrating-with-linters.html) quite smoothly. Would you think it'd be a better option?

**Comment by vitokhangnguyen** [comment]
@manekenpix Funny that you mention it. During my reading, I came across this article: https://blog.theodo.com/2019/08/why-you-should-use-eslint-prettier-and-editorconfig-together/
I think that using a combination of these 3 is a good solution too.

I can go ahead and configure for these 3 to work together smoothly.

**Comment by jerryshueh** [comment]
Which style are we going with? This conflict is causing eslint testing to fail, we should decide on a standard soon. There's also other default rules such as `noplusplus` which shouldn't affect the readability of the code. Unless we want to enforce rules like that as a standard going forward.

**Comment by vitokhangnguyen** [comment]
We are  going with most of the rules of [Airbnb Coding Styke ](https://github.com/airbnb/javascript) with some changes, I suggest, such as indentation size of 4 spaces in stead of 2,

**Comment by humphd** [comment]
By the way, my goal this week is to get all of EditorConfig, eslint, and Prettier integrated in our repo.  They can, and should!, live happily together.

**Comment by humphd** [comment]
I'm going to morph this bug so that it's about getting these three to work together.

In class on Monday/Tuesday I'll talk about Prettier in depth.  @vitokhangnguyen are you OK to own this in its expanded scope?  NOTE: one thing that will be a bit tricky about this will be timing the merge, since it will reformat all the existing code while people are still doing PRs.  We might want to schedule it for after the 0.3s all get done this week.

**Comment by humphd** [comment]
btw, [VSCode](https://github.com/Microsoft/vscode) is an example of a project that uses all 3 together.  It's pretty common now.

**Comment by vitokhangnguyen** [comment]
Hi @humphd,

I am more than happy to own the expanded scope. As you mentioned, I will configure the tools, pull the `master` branch and make the PR on Friday night/Saturday morning so all codes are well-formatted.

**Comment by humphd** [comment]
https://blog.echobind.com/integrating-prettier-eslint-airbnb-style-guide-in-vscode-47f07b5d7d6a is another good read on how to approach this.  There are a few ways.

**Comment by vitokhangnguyen** [comment]
@humphd 
Thank you for the link. I will make a **draft** PR soon so people can suggest changes but won't finalize it until all codes come in for re-formatting.

**Comment by jerryshueh** [comment]
What should we do in the meantime for eslint tests? Would including the config file edits violate the context of the PRs, as they technically aren't related to other issues (seeing as how hard we're cracking down on that)?

**Comment by vitokhangnguyen** [comment]
Hi @humphd,
Release 0.3 dues tonight. May I have a go for ESLint,  Prettier and EditConfig integration late tonight or tomorrow morning?

**Comment by humphd** [comment]
@vitokhangnguyen Let's leave to Monday when I see you in person.  I suspect we'll still have unmerged work I need to figure out.  Sorry to delay you, but it will be too painful to have to fight through all these rebases.

**Comment by vitokhangnguyen** [comment]
@humphd For sure. I will see you next week andd talk about this, then.

**Comment by humphd** [comment]
@vitokhangnguyen when you do this, can I add a couple things to the list?

- update the README.md to use a Prettier badge vs. the Standard one that is there now, since we don't actually use Standard.
- talk to me and see if we can remove this code https://github.com/Seneca-CDOT/telescope/blob/master/.travis.yml#L20-L25.  I don't think we'll need it once we properly rewrite the files using LF everywhere.

OK if I add these to your PR vs. filing new Issues?

**Comment by vitokhangnguyen** [comment]
Hi @humphd,

Sorry for my late reply. I have been in bed all day.

I surely can add more to-do things to the list. I completely agree that we do not need that snippet anymore in Travis setup since EditConfig will take on that responsibility.

I do not understand what you mean by Prettier badge vs. Standard badge. If you can kindly explain that to me, I would definitely be able to have it in my upcoming PR, too.

**Comment by humphd** [comment]
Our README has ![](https://camo.githubusercontent.com/d0f65430681b67b7104f6130ada8c098ec5f66ba/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636f64652532307374796c652d7374616e646172642d627269676874677265656e2e7376673f7374796c653d666c6174) in it, and should have ![](https://camo.githubusercontent.com/687a8ae8d15f9409617d2cc5a30292a884f6813a/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636f64655f7374796c652d70726574746965722d6666363962342e7376673f7374796c653d666c61742d737175617265)

**Comment by vitokhangnguyen** [comment]
> Our README has ![](https://camo.githubusercontent.com/d0f65430681b67b7104f6130ada8c098ec5f66ba/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636f64652532307374796c652d7374616e646172642d627269676874677265656e2e7376673f7374796c653d666c6174) in it, and should have ![](https://camo.githubusercontent.com/687a8ae8d15f9409617d2cc5a30292a884f6813a/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636f64655f7374796c652d70726574746965722d6666363962342e7376673f7374796c653d666c61742d737175617265)

Thank you for your explanation, I can have that in my PR.

**Comment by vitokhangnguyen** [comment]
Hi, @humphd,

I propose some more changes to add to my PR if you think they fit in:

1. Adding instruction to install ESLint, Prettier and EditorConfig plugins to VSCode (and maybe other editors)
1. Modify some ESLint rules that can benefit the developers to avoid bugs. Here is the list of it:

```
    rules: {
        'prettier/prettier': ['error'],

        /**
         * Disallow Reassignment of Function Parameters
         * https://eslint.org/docs/rules/no-param-reassign
         */
        "no-param-reassign": ['error'],

        /**
         * Disallow Assignment Operators in Conditional Statements
         * https://eslint.org/docs/rules/no-cond-assign
         */
        'no-cond-assign': ['error'],

        /**
         * Disallow Unnecessary Semicolons
         * https://eslint.org/docs/rules/no-extra-semi
         */
        'no-extra-semi': ['warn'],

        /**
         * Require or disallow named function expressions
         * https://eslint.org/docs/rules/func-names
         */
        'func-names': ['off'],

        /**
         * Disallow the use of console
         * https://eslint.org/docs/rules/no-console
         */
        'no-console': ['off'],
    }
```

If you don't think they should be in this PR, I can open a new issue for it if necessary.

**Comment by humphd** [comment]
For 1., I filed #256, which is probably the right place to do that.  Can you comment on that issue?  We can automate some of it, and add the docs in that issue vs. here.

For 2. can you explain why these extra rules are necessary in this change?

**Comment by vitokhangnguyen** [comment]
Hi @humphd,

1. I just did. I can take that on after this one if you are cool with that.

2. The extra rules are not necessary for this change except the `'prettier/prettier': ['error']` where we delegate all styling/formatting error to Prettier instead of ESLint.

So for the other extra 2:
```
        /**
         * Disallow Assignment Operators in Conditional Statements
         * https://eslint.org/docs/rules/no-cond-assign
         */
        'no-cond-assign': ['error'],

        /**
         * Disallow Unnecessary Semicolons
         * https://eslint.org/docs/rules/no-extra-semi
         */
        'no-extra-semi': ['warn'],
```
Should I file a new issue for that since, in some case, they will help avoiding potential bugs?

**Comment by humphd** [comment]
When we see each other tomorrow, let's go over this in person, and make some decisions.  I'm happy to consider changing some of the eslint rules if we have to; but if we don't have to, I'd prefer not to.
