### ISSUE TITLE
Show About in header at larger header widths

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#962]
Reviewing #896, I'm noticing that the About link is not visible at desktop widths, and to get it, I have to click into an otherwise completely empty hamburger menu.

This seems odd to me.  Let's show About in the main header for larger widths and hide the hamburger menu, since we're not using it to store any content in the app (it's just for overflow of the header on mobile).

<img width="1228" alt="Screen Shot 2020-04-08 at 1 32 13 PM" src="https://user-images.githubusercontent.com/427398/78815033-a39ca580-799d-11ea-86b3-dfe13035d98c.png">

**Comment by cindyledev** [comment]
Yeah, it's kinda lonely
![Annotation 2020-04-08 133843](https://user-images.githubusercontent.com/36822198/78815447-4c4b0500-799e-11ea-91f0-b7ebebb80dfe.png)

**Comment by agarcia-caicedo** [comment]
Is this still an issue? I think @cindyledev's PR fixed this

**Comment by humphd** [comment]
Yeah, this is gone, closing.  Thanks for catching this.
