### ISSUE TITLE
Remove stray photo1.jpg

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#965]
**What happened**:
#896 accidentally added `telescope/src/frontend/src/images/photo1.jpg` and forgot to remove it. Please remove the picture. Thanks.

**Comment by chrispinkney** [comment]
Hi Cindy,

I see the picture has now moved to `\src\frontend\src\images\backgrounds`, sorry for my likely dumb question but is this still an issue?

If so I'd like to take a crack at it.

**Comment by humphd** [comment]
Not a dumb question at all.  That file, no matter where it lives now, if not being used, should be removed.  I'll assign this to you @chrispinkney, thanks.

**Comment by chrispinkney** [comment]
@humphd I forked, branched, and `git rm`'d the file and pushed to my repo.

Are there any tests I should run before submitting a PR? If so (and either way) I don't know how to run any tests as I've never done them 😟. I did a search in the telescope directory but found no instances of `photo1.jpg` being referenced in the code so I'm assuming it's never used and figure that this alone is enough but just thought I'd ask.

**Comment by manekenpix** [comment]
@chrispinkney I don't think you need to run test for this particular case, but for future reference you can run `npm run test` in the telescope directory to run all the tests. Take a look at [package.json](https://github.com/Seneca-CDOT/telescope/blob/master/package.json) to see all the scripts that Telescope uses.

**Comment by chrispinkney** [comment]
Thanks so much! I'll submit my PR now.

**Comment by chrispinkney** [comment]
See #1147. So `npm run test` passes with a 1 pixel image but not with only a `.keep` file 👎. Does anyone have any suggestions on how to further approach this?

**Comment by chrispinkney** [comment]
@raygervais wondering if you have any guidance for me too!

**Comment by raygervais** [comment]
@chrispinkney, I see your previous branch was deleted. What was the issue with the 1x1 placeholder image?

**Comment by chrispinkney** [comment]
No issue, the tests passed no problem. It just feels like a non-solution to add a placeholder image along with a readme file explaining why said image exists, rather than address the actual issue of why the stray image should exist in the first place.

That being said if a PR is a fine solution in your eyes I'm game for that too haha.

**Comment by c3ho** [comment]
This issue has been resolved via #1147.
