### ISSUE TITLE
Change favicon when there are new posts available

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#966]
**What would you like to be added**:
Change favicon when there are new posts

**Why would you like this to be added**:
#791 should be going in soon, we have an alert or toast notifying users there are new posts available. However this only happens once and the alert duration is 6 seconds. We should also change the favicon with either a blue or orange circular dot to let users know there are new posts.

**Comment by cindyledev** [comment]
#816 has a notification badge suggestion with the red dot which I think is exactly what we want.

**Comment by zjjiang2** [comment]
I can try working on this, is it still available?

**Comment by humphd** [comment]
Fixed by #1441.
