### ISSUE TITLE
Fix icons in About page footer

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#968]
**What would you like to be added**:
![Annotation 2020-04-08 231504](https://user-images.githubusercontent.com/36822198/78854249-cf944700-79ee-11ea-9d6b-87e6d9c9d708.png)
- The word LOGO is just a placeholder for Telescope's actual [logo](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/images/logo.svg) 
`src/frontend/src/images/logo.svg`. Please add Telescope's logo there.
- MUI has an icon for GitHub but not Slack. Find and add an icon for Slack. It's best if they are both from the same source. Be sure to size them appropriately.

Files related to this issue:
- [AboutFooter.jsx](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/AboutFooter/AboutFooter.jsx) this component contains the footer for the About page, you will likely spend the most time here.
- [template.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/templates/template.js) this is where `AboutFooter.jsx` is imported into
- [about.md](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/markdown-pages/about.md) contains the raw markdown content for the About page
- [gatsby-node.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby-node.js) this file contains how the markdown pages are generated

Also see [Gatsby Adding Markdown Pages](https://www.gatsbyjs.org/docs/adding-markdown-pages/) for more information on how this all works

**Comment by agarcia-caicedo** [comment]
I'll work on it
