### ISSUE TITLE
Login button in MobileHeader's drawer isn't fully clickable 

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#971]
**What happened**:
![Annotation 2020-04-09 000758](https://user-images.githubusercontent.com/36822198/78857002-36692e80-79f6-11ea-8b3d-85be18ed438b.png)
If you click on HOME or ABOUT button, it will take you to the appropriate pages. However, for the Login, you need to click only on the text. If you click on the ListItem but outside of the LOGIN text, it just closes drawer and you don't get redirected.

**What should have happened**:
Clicking on anywhere within Login ListItem should redirect me to the Login page

**How to reproduce it (as precise as possible)**:
- visit https://dev.telescope.cdot.systems/ on mobile and try clicking on Login ListItem, not the LOGIN text

**Anything else we need to know?**:
This is happening because we cannot do `component={Link}` to `<Login />` like for HOME and ABOUT
```
        <ListItem button component={Link} to="/about" className={classes.item}>
          ABOUT
        </ListItem>
        <ListItem button className={classes.item}>
          <Login />
        </ListItem>
```
This may require refactoring the Login component into the Header component

Files related to this issue:
- [MobileHeader.jsx](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Header/MobileHeader.jsx)
- [Login.jsx](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Login/Login.jsx)

**Environment**:

- OS: All
- Browser: Chrome

**Comment by rogercyyu** [comment]
Hi, I would like to fix this bug. Thank you.
