### ISSUE TITLE
Page title missing for Home

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#972]
**What happened**:
The page title for `Home` is missing in Telescope's tab

**What should have happened**:
I should be able to see `Home` when I navigate to Telescope

**How to reproduce it (as precise as possible)**:
Go to `dev.telescope.cdot.systems` and check its tab

![image](https://user-images.githubusercontent.com/23108901/78862890-5dc7f780-7a06-11ea-824e-8b87693331bf.png)

- OS: Linux
- Browser: Firefox, Chrome

**Comment by cindyledev** [comment]
I'm pretty sure it was Calvin's Snack PR. I'll fix this in a bit. Small fix :)
