### ISSUE TITLE
Remove className="..." from Header.jsx

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#974]
In src/frontend/src/components/Header/Header.jsx, we're using unnecessary `className` attributes.  They can be removed:

```js
 {matches ? <MobileHeader className="mobile-header" /> : <DesktopHeader className="header" />}
```

**Comment by pyvelkov** [comment]
Hey,
I'm willing to give this a shot. Can I take a crack at this?

**Comment by c3ho** [comment]
Yep, go ahead

**Comment by PedroFonsecaDEV** [comment]
Can I give a try?

**Comment by manekenpix** [comment]
@PedroFonsecaDEV yes, thank you!
