### ISSUE TITLE
Separate existing feeds UI from adding new feed on /myfeeds

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#976]
I'm an admin user, so I get everybody's feeds in `/myfeeds`.  It scrolls for a days:

<img width="1234" alt="Screen Shot 2020-04-09 at 10 39 28 PM" src="https://user-images.githubusercontent.com/427398/78957366-23686400-7ab3-11ea-9e09-90f2f638c059.png">

#945 will likely change this, but it might be good to think about how to best use the available space.

One quick fix I can see is that it would be nice if the component for adding a new feed was always at the top vs. the bottom.  To get mine, I'd have to scroll all the way to the end of the existing feeds:

<img width="1226" alt="Screen Shot 2020-04-09 at 10 42 47 PM" src="https://user-images.githubusercontent.com/427398/78957487-74785800-7ab3-11ea-878f-2ddb9661ad77.png">

What if we move that to the top, and maybe put a little bit of empty vertical space between it and the existing feed list?

Most users will only have 1 or 2 feeds, so this won't be an issue for everyone.  Nevertheless, I think having the place that you add new ones always be at the top would be good.

**Comment by Silvyre** [comment]
Good idea. I'll make a quick fix but leave any precise styling details to @yatsenko-julia in #945.
