### ISSUE TITLE
Remove "feed added successfully" after some period

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#978]
When I successfully add a new feed via /myfeeds, there is a message that shows, saying that it was added successfully:

<img width="650" alt="Screen Shot 2020-04-09 at 10 49 02 PM" src="https://user-images.githubusercontent.com/427398/78957836-6ecf4200-7ab4-11ea-9046-aa6a6a7a42f0.png">

This is useful, but it never goes away.  The work @c3ho has done with the snackbar might be something we can leverage here to show a short message, then get rid of it.

**Comment by Silvyre** [comment]
The work @c3ho has done with the snackbar might be something we can leverage here to show a short message, then get rid of it.

I was actually thinking the same thing!

**Comment by c3ho** [comment]
Did I just get assigned an issue

**Comment by c3ho** [comment]
I'll work on this today

**Comment by Silvyre** [comment]
(As this is a bug, not a feature, moving this issue into [our 1.0 project](https://github.com/Seneca-CDOT/telescope/projects/14), accordingly.)
