### ISSUE TITLE
Can't add/delete multiple feeds one after another in /myfeeds

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#979]
I add a feed to /myfeeds, and it works.  However, I'm not able to then add another.  If I click the + sign, it doesn't show another empty area with space to enter URL and Name, I get a 409 error:

<img width="508" alt="Screen Shot 2020-04-09 at 10 51 40 PM" src="https://user-images.githubusercontent.com/427398/78957980-d4bbc980-7ab4-11ea-8423-388c6f11417f.png">

409 Conflict means something to a web developer, but it won't to a user.  Can we do a better job of letting them know what this error means, and also provide a new empty set of boxes for entering another feed?

**Comment by humphd** [comment]
I also note that I can't delete this feed either.  If I notice there's an error, I can't click the garbage can icon, it only shows the ? icon.

**Comment by Silvyre** [comment]
A few relevant developments:

>If I click the + sign, it doesn't show another empty area with space to enter URL and Name

> ![](https://user-images.githubusercontent.com/427398/78957980-d4bbc980-7ab4-11ea-8423-388c6f11417f.png)

#994 adds functionality that clears the 'Blog feed URL' form field upon clicking the '+' button.

>Can we [...] also provide a new empty set of boxes for entering another feed?

As of #994, when a feed is submitted, that feed gets added to the list of feeds (within a set of disabled textboxes). In conjunction with the form field clearing functionality I just mentioned, this should prevent the need to render an addition set of form fields (we can simply reuse what we have).

>I also note that I can't delete this feed either. If I notice there's an error, I can't click the garbage can icon, it only shows the ? icon.

Newly-added feeds can be deleted after they are rendered within the existing feed list. My intention is to keep use this initial set of form controls exclusively for the addition of feeds, leaving deletion of feeds the purview of the existing feed list.

> I get a 409 error

> Can we do a better job of letting them know what this error means[...]?

For sure; just pushed an update to #994 that addresses this: https://github.com/Seneca-CDOT/telescope/pull/994/commits/edc976949a5793fa2d43ffc540a6452bd686e795

This should compliment the work that @c3ho is doing with using snackbars to display status messages.
