### ISSUE TITLE
Set up CI/CD pipeline at Jenkins

### ISSUE THREAD

**Issue by wajeehsheikh** [Seneca-CDOT/telescope#98]
Seeing that David is open to multiple CI/CD platforms.
I would like to work on [Jenkins](https://jenkins.io)

Thank you,
Waj

**Comment by dbeigi** [comment]
Hey @wajeehsheikh, I would like to help you set up the pipeline. Excited for the learning experience.

**Comment by humphd** [comment]
This doesn't seem to have happened, and we now have both Travis CI and Circle CI landed in our tree.  Should we keep this open?

**Comment by wajeehsheikh** [comment]
No need to keep this open if we have two working CI platforms.
