### ISSUE TITLE
No indication that a deleted feed has been deleted

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#980]
I have a feed in /myfeeds, and I want to delete it.  I click the garbage can icon, and in my network dev tools I see a 204 DELETE (it worked).  However, in the UI, nothing changes:

<img width="464" alt="Screen Shot 2020-04-09 at 10 55 21 PM" src="https://user-images.githubusercontent.com/427398/78958170-56135c00-7ab5-11ea-9ace-89958175923b.png">

Probably the easiest thing to do here is to reload the feed list for this user, and populate the view again with a new data set, which won't have the old feed.

**Comment by humphd** [comment]
We could use the snackbar for this, too.

**Comment by Silvyre** [comment]
> Probably the easiest thing to do here is to reload the feed list for this user, and populate the view again with a new data set, which won't have the old feed.

Ha, I had this functionality in my PR [but removed it](https://github.com/Seneca-CDOT/telescope/pull/933/commits/4f6506e3325e687180c5b3015ac8c5fd56afe67a). I'll readd it.

**Comment by Silvyre** [comment]
> We could use the snackbar for this, too.

Yeah, I'll use the same solution I implement for https://github.com/Seneca-CDOT/telescope/issues/978

**Comment by Silvyre** [comment]
(As this is a bug, not a feature, moving this issue into [our 1.0 project](https://github.com/Seneca-CDOT/telescope/projects/14), accordingly.)

**Comment by c3ho** [comment]
My pr hasn’t gone in yet, we can add this to my PR

**Comment by Silvyre** [comment]
@c3ho Thanks!
