### ISSUE TITLE
Make "Add Yours!" link to /myfeeds

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#981]
Let's have the "Add Yours!" text in the banner link to /myfeeds, so people can literally add theirs.

<img width="1356" alt="Screen Shot 2020-04-09 at 11 00 45 PM" src="https://user-images.githubusercontent.com/427398/78958445-126d2200-7ab6-11ea-84d8-879e7e837778.png">

I am assuming that /myfeeds will go to the login page if you're not logged in, which is a nice way to discover this feature for people: they click `Add Yours!` and are taking into the login flow, and then to add their feed via /myfeeds

**Comment by smilegodly** [comment]
I'd like to work on this!

At the moment going to /myfeeds if you're not logged in redirects to the Telescope 404 page. I'll change that to redirect to the login page as it should in this PR also.
