### ISSUE TITLE
Remove references to BLOG_INACTIVE_TIME

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#988]
Our env example files have references to `BLOG_INACTIVE_TIME`, but we don't use it anymore.  Let's remove from our tree.

**Comment by trybick** [comment]
@humphd I noticed `BLOG_INACTIVE_TIME` is still in the example ENV file, although it is commented out. Do we want to have it totally removed? If so, I can do it.

**Comment by humphd** [comment]
Yup, sounds good @trybick, go for it.

**Comment by humphd** [comment]
It's in a few places, https://github.com/Seneca-CDOT/telescope/search?q=BLOG_INACTIVE_TIME
