### ISSUE TITLE
On initial load do not show "load more button"

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#999]
**What happened**:
Currently, before it loads posts, the button says "No more posts add yours!"

**What should have happened**:
It shouldn't show anything till after the first posts load. 

**How to reproduce it (as precise as possible)**:
Before the first posts, load you can see it.

**Anything else we need to know?**:
Nope!

**Environment**:

- OS:
- Browser:

**Comment by humphd** [comment]
I think it's a matter of dealing with the initial load case vs. an empty set of posts vs. a set of posts.  I'd set the state to `null` on load and then you can treat `[]` and `[post, post, ...]` differently.
